export const PLAN_TIERS = [
  { key: 'Soft', label: 'Soft (Safe / IG)' },
  { key: 'Fanvue', label: 'Fanvue (Tease)' },
  { key: 'Unrestricted', label: 'Unrestricted' },
]

export const EMPTY_BLOCKS = {
  identity: '',
  age: '',
  location: '',
  time: '',
  pose: '',
  clothing: '',

  ethnicity: '',
  body_shape: '',
  eye_color: '',
  hair: '',
  breast_size: '',
  glute_size: '',

  outfit_archetype: '',
  undress_state: '',
  clothing_instability: '',
  intimate_framing: '',
  voyeur_energy: '',
  micro_action: '',

  lingerie: '',
  mood: '',
  camera: '',
  lighting: '',
  style: '',
  quality: '',
}

export const FIELD_ORDER = [
  ['identity', 'Identity'],
  ['age', 'Age'],
  ['ethnicity', 'Ethnicity'],
  ['body_shape', 'Body Shape'],
  ['eye_color', 'Eye Color'],
  ['hair', 'Hair'],
  ['breast_size', 'Breast Size'],
  ['glute_size', 'Glute Size'],

  ['location', 'Location'],
  ['environment_detail', 'Environment Detail'],
  ['time', 'Time'],
  ['pose', 'Pose / Staging'],
  ['clothing', 'Clothing'],

  ['outfit_archetype', 'Outfit Archetype'],
  ['undress_state', 'State of Undress'],
  ['clothing_instability', 'Clothing Instability'],
  ['intimate_framing', 'Intimate Framing'],
  ['voyeur_energy', 'Voyeur Energy'],
  ['moment', 'Moment'],
  ['micro_action', 'Micro Action'],

  ['lingerie', 'Lingerie'],
  ['mood', 'Mood'],
  ['camera', 'Camera'],
  ['lighting', 'Lighting'],
  ['style', 'Style'],
  ['quality', 'Quality'],
]

export const PLAN_RULES = {
  Soft: {
    allowFields: [
      'identity',
      'age',
      'location',
      'time',
      'pose',
      'clothing',
      'ethnicity',
      'body_shape',
      'eye_color',
      'hair',
      'mood',
      'camera',
      'lighting',
      'style',
      'quality',
    ],
    allowLingerie: false,
    allowLocationCats: [
      'All',
      'Countries',
      'Cities',
      'Beaches',
      'Hotels',
      'Hotel – Lobby',
      'Hotel – Suite Bedroom',
      'Hotel – Living Room',
      'Home – Bedroom',
      'Home – Kitchen',
      'Home – Living Room',
      'Studios',
      'Nature',
      'Rooftops / Penthouses',
      'Gyms',
    ],
  },

  Fanvue: {
    allowFields: [
      'identity',
      'age',
      'location',
      'time',
      'pose',
      'clothing',
      'ethnicity',
      'body_shape',
      'eye_color',
      'hair',
      'breast_size',
      'glute_size',
      'outfit_archetype',
      'undress_state',
      'clothing_instability',
      'intimate_framing',
      'voyeur_energy',
      'micro_action',
      'lingerie',
      'mood',
      'camera',
      'lighting',
      'style',
      'quality',
    ],
    allowLingerie: true,
    allowLocationCats: [
      'All',
      'Countries',
      'Cities',
      'Beaches',
      'Hotels',
      'Hotel – Lobby',
      'Hotel – Suite Bedroom',
      'Hotel – Living Room',
      'Home – Bedroom',
      'Home – Kitchen',
      'Home – Living Room',
      'Studios',
      'Nature',
      'Rooftops / Penthouses',
      'Gyms',
      'Gym – Locker Rooms',
    ],
  },

  Unrestricted: {
    allowFields: [
      'identity',
      'age',
      'location',
      'time',
      'pose',
      'clothing',
      'ethnicity',
      'body_shape',
      'eye_color',
      'hair',
      'breast_size',
      'glute_size',
      'outfit_archetype',
      'undress_state',
      'clothing_instability',
      'intimate_framing',
      'voyeur_energy',
      'micro_action',
      'lingerie',
      'mood',
      'camera',
      'lighting',
      'style',
      'quality',
    ],
    allowLingerie: true,
    allowLocationCats: [
      'All',
      'Countries',
      'Cities',
      'Beaches',
      'Nightclubs',
      'Gyms',
      'Gym – Locker Rooms',
      'Gym – Showers',
      'Hotels',
      'Hotel – Lobby',
      'Hotel – Suite Bedroom',
      'Hotel – Living Room',
      'Hotel – Shower',
      'Home – Bedroom',
      'Home – Shower',
      'Home – Kitchen',
      'Home – Living Room',
      'Studios',
      'Nature',
      'Rooftops / Penthouses',
    ],
  },
}

export const LIB_SPLITS = {
  identity: { softEnd: 3, fanvueEnd: 10 },
  pose: { softEnd: 6, fanvueEnd: 14 },
  clothing: { softEnd: 5, fanvueEnd: 11 },
  lingerie: { softEnd: 5, fanvueEnd: 10 },
  mood: { softEnd: 5, fanvueEnd: 11 },
  camera: { softEnd: 5, fanvueEnd: 11 },
  lighting: { softEnd: 5, fanvueEnd: 11 },
  style: { softEnd: 5, fanvueEnd: 11 },
  quality: { softEnd: 4, fanvueEnd: 9 },

  outfit_archetype: { softEnd: 3, fanvueEnd: 6 },
  undress_state: { softEnd: 2, fanvueEnd: 4 },
  clothing_instability: { softEnd: 2, fanvueEnd: 4 },
  intimate_framing: { softEnd: 2, fanvueEnd: 4 },
  voyeur_energy: { softEnd: 2, fanvueEnd: 4 },
  micro_action: { softEnd: 2, fanvueEnd: 4 },
}