export const STORY_WORLD_AFTER_DARK = {
  id: 'after-dark',
  name: 'After Dark',
  description:
    'A cinematic world of late-night luxury — VIP club back rooms, penthouse after-parties, 3am hotel corridors, champagne and silk, the electric private world that only exists after midnight. Glamorous, slightly reckless, entirely intentional.',

  geography: { country: 'private interior / luxury nightlife', region: 'penthouse suite, VIP room, hotel corridor, after-hours private spaces' },

  identity: {
    archetype: 'late-night luxury woman',
    vibe: ['penthouse after-party energy', 'champagne at 3am', 'VIP back-room intimacy', 'the night that never ends', 'electric and private and entirely in control'],
    tone: ['electric', 'glamorous', 'late-night', 'warm', 'slightly reckless', 'controlled', 'intimate'],
    persona: ['the one who arrives last and owns the room', 'comfortable in the private world that exists after midnight', 'the night makes her more beautiful and more herself', 'glamorous without trying in the late-night private world'],
  },

  phaseOrder: ['wake', 'morning_refresh', 'getting_dressed', 'breakfast', 'late_morning', 'lunch', 'afternoon', 'reset', 'golden_hour', 'dinner', 'evening', 'night'],

  phases: {
    wake:            { label: 'Wake',            timeWindows: ['late morning wake-up after a late night', 'slow warm late-start morning'],              pacing: 'slow',   subLocations: ['penthouse-bedroom', 'hotel-suite-morning'] },
    morning_refresh: { label: 'Morning Refresh', timeWindows: ['late morning bathroom ritual', 'hotel or penthouse bathroom warmth'],                   pacing: 'slow',   subLocations: ['hotel-bathroom', 'suite-vanity'] },
    getting_dressed: { label: 'Getting Dressed', timeWindows: ['late morning dressing', 'afternoon pre-night preparation begins'],                      pacing: 'slow',   subLocations: ['penthouse-dressing', 'suite-vanity'] },
    breakfast:       { label: 'Breakfast',       timeWindows: ['late brunch in penthouse or hotel', 'slow warm late morning meal'],                     pacing: 'slow',   subLocations: ['penthouse-lounge', 'hotel-suite-morning'] },
    late_morning:    { label: 'Late Morning',    timeWindows: ['afternoon leisure before the night', 'penthouse or hotel afternoon ease'],               pacing: 'slow',   subLocations: ['penthouse-lounge', 'penthouse-bedroom'] },
    lunch:           { label: 'Lunch',           timeWindows: ['late afternoon pre-night ease', 'room service or penthouse meal'],                       pacing: 'slow',   subLocations: ['penthouse-lounge', 'hotel-suite-morning'] },
    afternoon:       { label: 'Afternoon',       timeWindows: ['pre-night private preparation hour', 'penthouse leisure before the evening begins'],     pacing: 'slow',   subLocations: ['penthouse-bedroom', 'suite-vanity'] },
    reset:           { label: 'Reset',           timeWindows: ['the night preparation ritual', 'pre-going-out vanity hour'],                             pacing: 'slow',   subLocations: ['suite-vanity', 'penthouse-dressing'] },
    golden_hour:     { label: 'Golden Hour',     timeWindows: ['penthouse at golden hour before the night', 'city view in last daylight'],               pacing: 'slow',   subLocations: ['penthouse-view', 'penthouse-lounge'] },
    dinner:          { label: 'Dinner',          timeWindows: ['VIP restaurant or private dinner early evening', 'before the clubs open'],              pacing: 'slow',   subLocations: ['vip-dinner', 'penthouse-view'] },
    evening:         { label: 'Evening',         timeWindows: ['early night VIP venue arrival', 'first club or private event moment'],                   pacing: 'medium', subLocations: ['vip-venue', 'club-back-room'] },
    night:           { label: 'Night',           timeWindows: ['2am-4am penthouse after-party or private late-night', 'the deepest after-dark moment'],  pacing: 'slow',   subLocations: ['penthouse-after-party', 'club-back-room'] },
  },

  locations: [
    'penthouse suite bedroom in warm morning light after a late night', 'hotel suite bathroom in warm morning',
    'penthouse lounge with city view before the night begins', 'VIP restaurant or private dinner setting',
    'VIP club back room with champagne and warm ambient', 'penthouse after-party in the early hours',
    'hotel corridor at 3am in warm dim light', 'club booth with bottle service and night energy',
  ],

  subLocations: {
    'penthouse-bedroom': {
      id: 'penthouse-bedroom', name: 'Penthouse Bedroom', mapAnchor: 'penthouse suite bedroom',
      category: 'private-morning-after',
      bestPhases: ['wake', 'afternoon', 'night'],
      overlays: ['luxury hotel bedding', 'city view through tall windows', 'warm morning-after calm', 'late-start luxury private morning'],
      locations: ['penthouse bedroom with city view', 'hotel suite bed in late morning light', 'private penthouse morning-after bedroom'],
    },
    'hotel-suite-morning': {
      id: 'hotel-suite-morning', name: 'Hotel Suite Morning', mapAnchor: 'luxury hotel suite',
      category: 'morning-luxury',
      bestPhases: ['wake', 'breakfast', 'lunch'],
      overlays: ['luxury hotel suite interior', 'room service or suite breakfast', 'warm late-morning hotel calm', 'after-night private luxury'],
      locations: ['hotel suite with room service', 'luxury morning-after hotel interior', 'warm hotel suite with city view'],
    },
    'hotel-bathroom': {
      id: 'hotel-bathroom', name: 'Hotel Bathroom', mapAnchor: 'luxury hotel bathroom',
      category: 'self-care',
      bestPhases: ['morning_refresh'],
      overlays: ['marble hotel bathroom', 'warm morning-after bathroom light', 'luxury self-care morning interior'],
      locations: ['hotel marble bathroom', 'luxury morning bathroom ritual', 'warm private hotel bathroom after a late night'],
    },
    'suite-vanity': {
      id: 'suite-vanity', name: 'Suite Vanity', mapAnchor: 'hotel or penthouse vanity',
      category: 'preparation',
      bestPhases: ['morning_refresh', 'getting_dressed', 'reset'],
      overlays: ['lit vanity mirror', 'glamour makeup setup', 'warm evening preparation light', 'night preparation ritual'],
      locations: ['lit vanity mirror in hotel suite', 'night preparation vanity', 'glamour makeup vanity in penthouse'],
    },
    'penthouse-dressing': {
      id: 'penthouse-dressing', name: 'Penthouse Dressing', mapAnchor: 'penthouse dressing area',
      category: 'dressing',
      bestPhases: ['getting_dressed', 'reset'],
      overlays: ['evening wear hanging', 'night preparation ritual', 'glamorous dressing energy', 'pre-night outfit selection'],
      locations: ['penthouse dressing area with evening wear', 'pre-night outfit ritual', 'glamorous dressing preparation'],
    },
    'penthouse-lounge': {
      id: 'penthouse-lounge', name: 'Penthouse Lounge', mapAnchor: 'penthouse living room with city view',
      category: 'luxury-leisure',
      bestPhases: ['breakfast', 'late_morning', 'lunch', 'golden_hour'],
      overlays: ['penthouse lounge with panoramic city view', 'champagne or coffee in luxury interior', 'warm ambient lounge light', 'pre-night ease'],
      locations: ['penthouse lounge with city panorama', 'luxury lounge before the night', 'champagne or coffee in penthouse view'],
    },
    'penthouse-view': {
      id: 'penthouse-view', name: 'Penthouse View', mapAnchor: 'penthouse terrace or window city view',
      category: 'city-view',
      bestPhases: ['golden_hour', 'dinner'],
      overlays: ['panoramic city view at dusk or night', 'penthouse glass with city lights below', 'luxury above-the-city perspective', 'pre-night city energy'],
      locations: ['penthouse terrace or window at golden hour', 'city lights view from penthouse height', 'luxury city panorama before the night'],
    },
    'vip-dinner': {
      id: 'vip-dinner', name: 'VIP Dinner', mapAnchor: 'VIP restaurant or private dining',
      category: 'pre-night-dining',
      bestPhases: ['dinner'],
      overlays: ['VIP or private dining room', 'warm evening restaurant ambient', 'champagne and elegant dinner setting', 'pre-club dinner energy'],
      locations: ['VIP restaurant booth or private room', 'luxury pre-club dinner table', 'warm elegant dinner before the night begins'],
    },
    'vip-venue': {
      id: 'vip-venue', name: 'VIP Venue', mapAnchor: 'VIP club or private event space',
      category: 'nightlife',
      bestPhases: ['evening'],
      overlays: ['VIP club or bar with warm bottle-service ambient', 'electric night venue energy', 'champagne and warm glow', 'early-night club arrival'],
      locations: ['VIP club interior', 'bottle service area in warm venue light', 'VIP arrival at the night venue'],
    },
    'club-back-room': {
      id: 'club-back-room', name: 'Club Back Room', mapAnchor: 'VIP back room or private club area',
      category: 'private-nightlife',
      bestPhases: ['evening', 'night'],
      overlays: ['private VIP back room', 'warm low ambient club light', 'champagne and intimate private nightlife', 'after-hours private energy'],
      locations: ['VIP club back room with champagne', 'private nightlife intimate setting', 'warm low-lit exclusive back room'],
    },
    'penthouse-after-party': {
      id: 'penthouse-after-party', name: 'Penthouse After-Party', mapAnchor: 'penthouse at 3am',
      category: 'after-hours',
      bestPhases: ['night'],
      overlays: ['penthouse at 3am with city lights below', 'after-party warm ambient light', 'champagne and silk in late night penthouse', 'the private after-hours world'],
      locations: ['penthouse at 2am-4am with city visible', 'after-party penthouse interior in warm low light', 'the private after-dark penthouse world'],
    },
  },

  sceneVariants: {
    wake: ['waking slowly in a penthouse bed after a late night with the city below', 'the morning-after hotel suite — late start in luxury sheets with warm light'],
    morning_refresh: ['marble hotel bathroom morning-after ritual in warm light', 'the penthouse or suite vanity morning with luxury self-care'],
    getting_dressed: ['slow late-morning dressing in the penthouse or hotel suite', 'the pre-night preparation energy beginning in the afternoon'],
    breakfast: ['late brunch with champagne or coffee in the penthouse lounge with city view', 'room service in the hotel suite in warm late-morning light'],
    late_morning: ['penthouse afternoon ease before the night begins', 'slow luxury leisure in the penthouse or hotel before getting ready'],
    lunch: ['room service or penthouse meal in warm afternoon hotel interior', 'slow pre-night late lunch in luxury surroundings'],
    afternoon: ['penthouse private preparation hour before the night', 'lying in the penthouse bedroom in afternoon light before the evening'],
    reset: ['the night preparation vanity ritual — the full glamour transformation', 'getting ready for the night in the penthouse or hotel suite vanity'],
    golden_hour: ['penthouse terrace or lounge at golden hour with the city turning amber below', 'champagne at the penthouse window as the city lights begin'],
    dinner: ['VIP restaurant or private dinner setting before the clubs open', 'champagne dinner in a private booth before the night starts'],
    evening: ['arriving at the VIP venue or club in full evening glamour', 'the private back room with champagne and warm low club ambient'],
    night: ['penthouse after-party at 2am-4am with the city below', 'the club back room at the most private and electric late-night moment'],
  },

  actionPools: {
    wake: ['waking slowly in luxury sheets after a late night', 'reaching for the phone before leaving the bed', 'the slow late-morning wake in a penthouse or hotel suite'],
    morning_refresh: ['marble bathroom morning-after ritual', 'the luxury hotel vanity morning self-care', 'getting fresh after a late night in warm hotel bathroom'],
    getting_dressed: ['slow pre-night dressing beginning in the afternoon', 'choosing the night outfit in the penthouse', 'the first steps of the glamour night preparation ritual'],
    breakfast: ['champagne or coffee in the penthouse lounge with city view', 'room service breakfast in hotel suite in warm morning', 'slow late brunch before the night begins'],
    late_morning: ['penthouse lounge afternoon ease', 'the slow luxury leisure before getting ready for the night', 'champagne in the penthouse in the afternoon light'],
    lunch: ['room service or suite lunch in warm afternoon hotel interior', 'the pre-night fuel in private luxury surroundings', 'slow afternoon in the penthouse before everything begins'],
    afternoon: ['lying in the penthouse bedroom in afternoon warmth', 'the private pre-night hour in penthouse ease', 'slow private preparation beginning in afternoon luxury'],
    reset: ['the full night preparation vanity ritual — makeup, hair, complete transformation', 'choosing the night look at the penthouse or suite vanity', 'getting glamorous for the night in full preparation ritual'],
    golden_hour: ['champagne on the penthouse terrace as the city turns amber', 'the pre-night golden-hour moment with city below in warm light', 'standing at the penthouse glass as the city lights begin to come on'],
    dinner: ['VIP private dinner before the clubs — champagne and elegant table', 'the pre-club private dinner with warm evening ambience', 'sitting in a VIP booth with the night charged ahead'],
    evening: ['arriving at the VIP club in full night glamour', 'the private VIP back room with champagne and low warm ambient', 'the early-night electric club energy at full momentum'],
    night: ['penthouse after-party at 3am — champagne and city lights below', 'the private club back room in the deepest after-dark moment', 'the night world at its most electric and private after midnight'],
  },

  environmentPools: {
    wake: ['penthouse bedroom in warm late-morning light after a full night', 'hotel suite in soft warm morning-after interior', 'luxury bedroom with city view through tall windows in morning'],
    morning_refresh: ['marble hotel bathroom with warm morning-after light', 'luxury suite bathroom in clean warm morning', 'hotel bathroom vanity in private warm light'],
    getting_dressed: ['penthouse dressing area with night outfit preparation', 'suite vanity mirror in afternoon preparation warm light', 'hotel suite dressing in pre-night glamour energy'],
    breakfast: ['penthouse lounge with panoramic city view and champagne or coffee', 'hotel suite with room service in warm late-morning', 'luxury private morning-after brunch setting'],
    late_morning: ['penthouse lounge in warm afternoon ease before the night', 'hotel suite lounge in private luxury afternoon calm', 'penthouse interior with city view in afternoon light'],
    lunch: ['penthouse or hotel room service in warm afternoon interior', 'luxury suite meal in private afternoon warmth', 'penthouse lounge pre-night afternoon meal setting'],
    afternoon: ['penthouse bedroom in warm afternoon private ease', 'hotel suite in warm private pre-night preparation hour', 'penthouse interior in the hour before getting ready'],
    reset: ['lit vanity in hotel or penthouse — the glamour transformation', 'suite vanity in warm preparation light', 'penthouse dressing zone in pre-night glamour ritual'],
    golden_hour: ['penthouse terrace or window at golden hour with city turning amber', 'champagne in penthouse lounge as city lights begin', 'panoramic city view from penthouse height at golden hour'],
    dinner: ['VIP restaurant private booth in warm candlelit early evening', 'private dinner room before the clubs with champagne and elegant table', 'VIP dinner setting in warm pre-night ambient'],
    evening: ['VIP club interior with warm bottle-service ambient and electric energy', 'private club back room with champagne and low ambient', 'VIP venue at the most electric early-night moment'],
    night: ['penthouse at 3am with city lights spread below in warm low light', 'club private back room in the deepest after-dark intimate setting', 'penthouse after-party at its most electric and private after midnight'],
  },

  moodPools: {
    wake: ['slow glamorous morning-after luxury', 'the warm private late start of an after-dark life', 'unhurried penthouse morning after a full night'],
    morning_refresh: ['warm morning-after self-care ease', 'private luxury bathroom morning ritual calm', 'the after-dark world waking slowly in warm hotel interior'],
    getting_dressed: ['the beginning of the pre-night transformation ritual', 'slow deliberate pre-night preparation energy', 'the night world preparing itself in the afternoon'],
    breakfast: ['luxurious late brunch ease above the city', 'penthouse champagne morning-after mood', 'the warm private morning-after club world'],
    late_morning: ['pre-night leisure in penthouse luxury', 'the slow warm afternoon before the electric night', 'penthouse ease in golden afternoon before everything begins'],
    lunch: ['warm afternoon private luxury before the night', 'the penthouse pre-night afternoon ease', 'slow luxurious pre-club afternoon energy'],
    afternoon: ['the pre-night private hour in penthouse warm interior', 'slow private preparation energy before the transformation', 'warm penthouse afternoon calm before the ritual begins'],
    reset: ['full glamour transformation energy — the night preparation ritual', 'electric pre-night preparation at the vanity', 'the deliberate building of night-world identity at the mirror'],
    golden_hour: ['penthouse golden-hour with city below — the most beautiful pre-night moment', 'champagne and city view at golden hour', 'the anticipation of the electric night from penthouse height'],
    dinner: ['VIP pre-club dinner warmth and elegance', 'champagne and elegant dinner energy before the clubs', 'the charged pre-night dinner with everything ahead'],
    evening: ['electric club arrival energy in full night glamour', 'VIP venue warmth and bottle-service social energy', 'the night at its early electric charged peak'],
    night: ['penthouse after-dark — the private world after midnight', 'club back room at 3am — the most intimate electric late-night', 'the after-dark world at its most private and alive'],
  },

  cameraPools: {
    wake: ['85mm low angle from penthouse bed edge, shallow focus, city window dissolved behind', '135mm close-up at face height, warm late-morning light defining edge of subject'],
    morning_refresh: ['85mm hotel bathroom mirror close, reflection at same focal plane as subject', '50mm suite vanity mid shot, warm morning light compressing behind'],
    getting_dressed: ['50mm penthouse dressing mirror framed shot, wardrobe depth receding behind', '85mm mid-length pre-night dressing angle, warm interior depth soft behind'],
    breakfast: ['24mm wide penthouse lounge, city panorama filling background beyond', '85mm soft seated champagne or coffee framing, city view dissolved behind'],
    late_morning: ['85mm penthouse lounge medium, warm interior depth soft behind subject', '50mm hotel suite framing, city window dissolving in background'],
    lunch: ['85mm suite or penthouse meal framing, warm interior depth behind subject', '50mm room-service or lounge framing, hotel suite depth behind'],
    afternoon: ['85mm penthouse bedroom afternoon, window view dissolving in soft bokeh', '135mm intimate pre-night close, warm afternoon interior behind'],
    reset: ['85mm lit vanity close, warm vanity light on face against dark background', '50mm vanity mid shot — full transformation ritual in progress'],
    golden_hour: ['135mm penthouse golden-hour backlit close, warm city amber rim light', '24mm wide penthouse shot, city turning gold in full background below'],
    dinner: ['85mm VIP dinner candlelit seated portrait, warm restaurant ambient behind', '50mm private dinner table medium, candlelit depth behind subject'],
    evening: ['85mm club or VIP back room medium, warm low ambient bokeh filling background', '50mm VIP venue interior, warm electric night depth behind subject'],
    night: ['85mm penthouse night or back room, city lights bokeh filling warm background', '135mm after-dark intimate close, warm night ambient as soft background'],
  },

  lightingPools: {
    wake: ['warm 4800K late-morning light through penthouse windows, soft shadows across luxury sheets', 'soft diffused morning light through hotel curtains, warm edge on pillow'],
    morning_refresh: ['clean 5500K hotel bathroom light, fresh and warm on marble surfaces', 'warm 4500K suite vanity daylight, soft morning self-care light'],
    getting_dressed: ['warm 4200K penthouse interior in afternoon preparation, soft and flattering', 'suite ambient at 4000K, even warm fill across dressing area'],
    breakfast: ['warm 4800K penthouse lounge in late morning, champagne catching light', 'soft hotel suite morning at 5000K with room service detail'],
    late_morning: ['warm 4200K penthouse afternoon interior, soft and easy', 'hotel suite afternoon at 4500K, even warm fill in lounge'],
    lunch: ['warm 4000K afternoon hotel interior, soft and flattering', 'penthouse lounge at 4200K in afternoon ease'],
    afternoon: ['warm 3800K penthouse bedroom afternoon, soft and private', 'suite interior at 4000K in pre-night private ease'],
    reset: ['warm 3200K vanity preparation light — flattering and deliberate', 'lit vanity at 3000K against darker suite background, beauty preparation portrait'],
    golden_hour: ['rich 2800K city golden-hour through penthouse glass, amber across interior', 'warm sunset from the city below at 2600K through penthouse window, amber edge'],
    dinner: ['restaurant candlelight at 1900K mixed with warm VIP ambient at 2700K', 'warm intimate dinner at 2600K, champagne catching light in warm fill'],
    evening: ['warm 2500K VIP club ambient with electric colored fills', 'low warm 2400K back-room intimate light with deep shadow beyond'],
    night: ['warm 2200K penthouse after-party light, city glow from below adding secondary fill', 'low 1900K warm club back-room in deep private night — intimate and electric'],
  },

  stylingPools: {
    wardrobe: {
      wake: ['silk or satin in luxury hotel sheets', 'dishevelled glamour morning-after private look', 'barely dressed post-night morning luxury'],
      morning_refresh: ['white hotel robe or towel post-shower', 'morning-after silk wrap in hotel bathroom', 'luxury morning-after hotel bathroom look'],
      getting_dressed: ['beginning the night transformation — the first pre-night outfit piece', 'starting the glamour build in casual pre-night dressing', 'penthouse afternoon leisure before the night look'],
      breakfast: ['silk robe or wrap in penthouse lounge for late brunch', 'dishevelled glamour morning in penthouse with champagne', 'luxury late-morning private look'],
      late_morning: ['comfortable luxury pre-night interior afternoon look', 'penthouse afternoon ease before getting ready', 'warm afternoon in penthouse in soft pre-night wear'],
      lunch: ['pre-night afternoon comfortable luxury look', 'penthouse or suite afternoon interior wear', 'warm pre-night ease in luxury interior'],
      afternoon: ['penthouse or suite pre-night private wear', 'the hour before the transformation — comfortable private look', 'beginning to layer for the night in penthouse private'],
      reset: ['the night look fully assembled at the vanity', 'complete glamour night outfit for the VIP world', 'full after-dark transformation — silk dress, evening shoes, complete'],
      golden_hour: ['pre-night champagne look on the penthouse terrace', 'the first full assembled night look at golden hour', 'glamorous pre-dinner penthouse look'],
      dinner: ['VIP dinner look — elegant, glamorous, and charged', 'the full pre-club dinner styling', 'champagne dinner dress or elevated night outfit'],
      evening: ['full club night look — the most glamorous and electric', 'VIP club or back-room night styling in full', 'the after-dark world in complete night glamour'],
      night: ['after-party late-night styling — slightly loosened from the night', 'penthouse after-party in night look softened', 'the deep after-dark private late-night look'],
    },
    details: {
      wake: ['morning-after hair dishevelled on luxury pillow', 'mascara or eye makeup slightly worn', 'last night\'s jewelry still on in the morning'],
      morning_refresh: ['fresh face after hotel shower', 'clean morning skin after the late night', 'hotel robe and fresh hair in morning bathroom'],
      getting_dressed: ['beginning to apply makeup for the night', 'first jewelry piece going on for the evening', 'hair styling beginning for the night'],
      breakfast: ['minimal morning detail with silk robe', 'champagne flute in morning light', 'lazy glamour in the penthouse morning'],
      late_morning: ['pre-night afternoon accessories minimal', 'penthouse lounge ease before glamour begins', 'warm afternoon pre-night detail'],
      lunch: ['casual warm pre-night interior detail', 'room service or champagne glass in afternoon', 'pre-night hair beginning or undone'],
      afternoon: ['beginning the night makeup at the pre-vanity stage', 'skin prep for the night look', 'pre-night afternoon interior styling'],
      reset: ['full glamour complete — hair, makeup, jewelry all done', 'the complete night transformation finished at the vanity', 'final night jewelry and accessories in place'],
      golden_hour: ['first champagne glass with complete pre-night look', 'golden-hour jewelry catching warm city light', 'pre-night look in warm amber city glow'],
      dinner: ['VIP dinner glamour — complete, precise, and charged', 'champagne and jewels at dinner table', 'pre-club dinner complete styling'],
      evening: ['full club night glamour detail', 'electric night accessories and styling in VIP venue', 'complete after-dark styling at the night peak'],
      night: ['late-night slightly loosened glamour detail', 'hair softer at 3am after-party', 'champagne glass and late-night styling'],
    },
    changeMoments: {
      wake: ['morning-after in luxury sheets, last night\'s look wearing off', 'waking in the night world\'s private morning'],
      morning_refresh: ['transitioning from night to morning in hotel bathroom', 'hotel robe phase after showering'],
      getting_dressed: ['beginning the night build in the afternoon', 'early stage of the glamour ritual'],
      breakfast: ['in morning or lounge wear for late brunch before the night', 'penthouse morning-after ease'],
      late_morning: ['pre-night afternoon interior comfort before the transformation', 'the calm before the glamour ritual'],
      lunch: ['pre-night private wear in warm afternoon', 'the afternoon luxury before the build begins'],
      afternoon: ['penthouse private pre-night wear', 'between afternoon ease and the vanity ritual'],
      reset: ['the full night transformation at the vanity — complete', 'from private to glamorous in the after-dark world'],
      golden_hour: ['first full assembled night look at golden hour', 'pre-dinner complete night glamour'],
      dinner: ['full VIP night look at the dinner table', 'pre-club glamour in complete styling'],
      evening: ['the most glamorous version — full club night look at peak', 'after-dark world styling at maximum'],
      night: ['slightly softened after-party late-night look', 'the night look settling at 3am'],
    },
  },

  sensoryPools: {
    wake: ['luxury silk or satin against skin in warm morning-after hotel', 'champagne or perfume scent in the penthouse morning', 'the warm private late-start morning above the city'],
    morning_refresh: ['warm marble hotel bathroom after a late night', 'fresh hot shower washing off the night', 'the private warm hotel bathroom morning'],
    getting_dressed: ['the build of anticipation in the afternoon preparation ritual', 'fragrance layering in the penthouse before the night', 'the electric pre-night energy beginning'],
    breakfast: ['champagne bubbles and late brunch ease in penthouse warmth', 'city view and coffee or champagne in morning luxury', 'the penthouse morning-after ease'],
    late_morning: ['warm penthouse afternoon ease before the electric night', 'champagne or comfort in penthouse interior afternoon', 'the private calm before the night world opens'],
    lunch: ['room service and warm hotel interior before the night', 'private afternoon luxury in penthouse before the transformation', 'the warm pre-night ease'],
    afternoon: ['penthouse warm private afternoon ease', 'the calm private hour before the glamour ritual begins', 'warm interior ease in the penthouse before everything changes'],
    reset: ['the glamour transformation at the vanity — fragrance, makeup, jewelry', 'the electric pre-night preparation sensory ritual', 'the full transformation energy building at the mirror'],
    golden_hour: ['champagne and city amber light at penthouse height', 'the warm pre-night city view below turning gold', 'golden-hour penthouse energy — anticipation and warmth'],
    dinner: ['VIP dinner champagne and warm restaurant air', 'the pre-club dinner charged anticipation sensory', 'warm candlelit dinner before the electric night'],
    evening: ['electric VIP club energy — music, champagne, warm ambient', 'the VIP venue charged social sensory peak', 'the after-dark world at its most electric and alive'],
    night: ['penthouse 3am — city lights below, champagne, and total privacy', 'the after-dark intimate private world sensory', 'the deepest most private after-midnight after-dark experience'],
  },

  socialEnergyPools: {
    wake: ['completely private morning-after luxury', 'no performance — the after-dark world at rest in the morning'],
    morning_refresh: ['private morning hotel self-care', 'alone in warm hotel bathroom after the night'],
    getting_dressed: ['private pre-night transformation beginning', 'alone in the penthouse building the night identity'],
    breakfast: ['private penthouse morning ease', 'warm late brunch before the social night world opens'],
    late_morning: ['pre-night private penthouse leisure', 'the after-dark world in its private afternoon state'],
    lunch: ['private pre-night luxury', 'penthouse interior afternoon ease before the glamour build'],
    afternoon: ['private penthouse hour before the transformation', 'completely alone in warm afternoon before the night'],
    reset: ['private transformation ritual — self-directed glamour', 'alone at the vanity building the night identity'],
    golden_hour: ['the pre-night social energy beginning to build', 'champagne on the penthouse before the world opens'],
    dinner: ['VIP dinner social energy — seen and glamorous and charged', 'the pre-club social table — visible and elegant'],
    evening: ['full social VIP club energy — the after-dark world social peak', 'visible in the most electric glamorous setting'],
    night: ['private after-party social energy — selective and intimate after midnight', 'the most private glamorous social world — after 2am'],
  },

  atmospherePools: {
    wake: ['warm private late-morning penthouse after the long night', 'luxury morning-after hotel calm', 'the after-dark world in its private morning state'],
    morning_refresh: ['hotel bathroom warm morning-after atmosphere', 'private luxury self-care calm after the night', 'the warm private hotel morning'],
    getting_dressed: ['penthouse afternoon ease before the night ritual begins', 'the calm private pre-transformation atmosphere', 'warm pre-night preparation energy building'],
    breakfast: ['penthouse morning brunch atmosphere above the city', 'champagne and city view in private warm morning', 'the after-dark world in warm late-morning ease'],
    late_morning: ['penthouse pre-night leisure atmosphere', 'warm private afternoon ease in luxury interior', 'the calm that precedes the electric night'],
    lunch: ['penthouse private pre-night afternoon atmosphere', 'warm luxury interior ease in the afternoon', 'private pre-night comfort in penthouse surroundings'],
    afternoon: ['penthouse private hour before the transformation', 'warm interior ease in the calm pre-night', 'the quiet before the glamour storm'],
    reset: ['full electric glamour transformation atmosphere at the vanity', 'the night identity building in charged preparation energy', 'the after-dark world preparing itself'],
    golden_hour: ['penthouse city golden-hour — champagne and anticipation', 'the warm pre-night atmosphere at penthouse height', 'city amber at golden hour with the night ahead'],
    dinner: ['VIP dinner warm pre-club atmosphere', 'champagne and elegant table — the night building', 'warm charged pre-club dinner ambience'],
    evening: ['electric VIP club atmosphere at full peak', 'the after-dark world in full social electric flow', 'warm glamorous nightlife at maximum energy'],
    night: ['penthouse 3am private after-party atmosphere', 'the most intimate electric private after-midnight world', 'the deep after-dark penthouse in warm low light with city below'],
  },

  propPools: {
    wake: ['luxury hotel or penthouse bedding', 'champagne glass still on bedside from last night', 'last night\'s heels or jewelry near the bed'],
    morning_refresh: ['hotel robe on hook', 'luxury morning bathroom products', 'hotel amenity detail in warm marble bathroom'],
    getting_dressed: ['evening wear hanging ready in penthouse', 'vanity with products being applied', 'pre-night jewelry laid out'],
    breakfast: ['champagne flute in morning penthouse light', 'room service tray or coffee cup in suite', 'city view through penthouse window in morning'],
    late_morning: ['penthouse lounge furniture in afternoon light', 'champagne or afternoon drink in penthouse ease', 'city view from penthouse height in afternoon'],
    lunch: ['room service or penthouse meal setting', 'wine or champagne in afternoon penthouse interior', 'hotel suite comfort props in warm afternoon'],
    afternoon: ['penthouse bedroom or lounge afternoon ease', 'pre-night preparation items beginning to appear', 'warm interior props before the transformation'],
    reset: ['full vanity setup — makeup, brushes, jewelry', 'the complete night transformation in progress', 'champagne glass at the vanity while getting ready'],
    golden_hour: ['champagne flute on penthouse terrace with city amber behind', 'city lights beginning below through penthouse glass', 'golden-hour prop on penthouse at pre-night peak'],
    dinner: ['champagne glass at VIP dinner table', 'candlelit VIP table setting detail', 'pre-club dinner prop in warm restaurant ambient'],
    evening: ['bottle service in VIP club interior', 'champagne in warm VIP back-room setting', 'electric VIP club detail in night ambient'],
    night: ['champagne at penthouse after-party with city below', 'VIP back-room champagne in warm 3am light', 'city lights as the prop and background at the after-dark peak'],
  },

  bodyLanguagePools: {
    wake: ['slow dishevelled morning-after posture in luxury sheets', 'warm private late wake posture in hotel or penthouse', 'the unhurried morning-after body language of the after-dark world'],
    morning_refresh: ['warm bathroom morning posture after the late night', 'relaxed post-shower hotel robe stance', 'gentle morning-after self-care body language'],
    getting_dressed: ['slow pre-night afternoon dressing body language', 'building energy in the pre-night preparation phase', 'deliberate afternoon pre-transformation posture'],
    breakfast: ['relaxed penthouse morning brunch posture', 'champagne and lounge ease body language', 'warm private morning-after penthouse body language'],
    late_morning: ['penthouse lounge afternoon ease body language', 'relaxed pre-night private afternoon posture', 'warm interior comfort before the night'],
    lunch: ['penthouse pre-night afternoon ease', 'relaxed private interior body language before the transformation', 'warm afternoon in penthouse in comfortable ease'],
    afternoon: ['pre-night private ease in penthouse', 'the quiet afternoon posture before the build', 'warm interior rest before the night ritual begins'],
    reset: ['deliberate upright vanity transformation posture', 'focused pre-night preparation at the mirror', 'composed building glamour ritual body language'],
    golden_hour: ['champagne penthouse posture — relaxed elegance before the night', 'confident pre-night city-view stance at golden hour', 'the first fully assembled night look at golden-hour confidence'],
    dinner: ['VIP dinner glamorous seated posture', 'champagne dinner confidence and elegance', 'charged pre-club dinner body language'],
    evening: ['electric VIP club arrival confidence and glamour', 'back-room intimate club posture with complete control', 'the night at its most energetic and physically present'],
    night: ['private after-party slightly softened late-night posture', '3am penthouse body language — still glamorous but completely private', 'the after-dark world in its most private physical state'],
  },

  facialExpressionPools: {
    wake: ['slow morning-after soft expression in luxury warmth', 'dishevelled private morning face after a full night', 'warm private late-morning ease on the face'],
    morning_refresh: ['fresh post-shower morning expression', 'clean morning-after hotel bathroom face', 'warm morning-after private expression in hotel light'],
    getting_dressed: ['beginning to build the night expression in the afternoon', 'pre-night preparation energy starting on the face', 'the quiet before the full transformation expression'],
    breakfast: ['relaxed penthouse morning brunch expression', 'champagne ease and warm morning private face', 'the after-dark world in warm late-morning private ease'],
    late_morning: ['pre-night afternoon ease expression', 'warm private interior afternoon expression', 'the calm before the night expression'],
    lunch: ['private pre-night afternoon expression', 'warm afternoon luxury ease on the face', 'pre-night private relaxed expression'],
    afternoon: ['pre-night private afternoon expression', 'the hour before the transformation quiet on the face', 'warm interior ease before the night ritual expression'],
    reset: ['focused deliberate glamour transformation expression at vanity', 'building the night identity expression in the mirror', 'the electric pre-night at the vanity — focused and magnetic'],
    golden_hour: ['pre-night champagne glamour expression at golden hour', 'city-view anticipation expression in golden-hour warmth', 'the first full night look expression — confident and charged'],
    dinner: ['VIP dinner glamorous composed expression', 'charged pre-club dinner expression with everything ahead', 'champagne dinner elegance on the face'],
    evening: ['electric club arrival expression — the most glamorous alive expression of the day', 'VIP night world confidence at full peak', 'the after-dark world at its most socially electric'],
    night: ['private after-party expression at 3am — still glamorous but soft', 'penthouse late-night warm private expression after midnight', 'the deepest most private after-dark expression in the world'],
  },

  handDetailPools: {
    wake: ['hand on luxury pillow after the late night', 'last night\'s ring or bracelet still on', 'reaching for phone or champagne glass remnant'],
    morning_refresh: ['hand on hotel bathroom counter in morning', 'hotel robe held in morning', 'hands in hotel bathroom in warm morning light'],
    getting_dressed: ['fingers applying morning makeup beginning the transformation', 'hand reaching for jewelry to begin the night build', 'pre-night preparation hand detail'],
    breakfast: ['hand around champagne flute in penthouse morning', 'fingers on room service tray in hotel suite', 'hand resting on penthouse lounge furniture'],
    late_morning: ['hand resting in penthouse lounge in afternoon ease', 'champagne or drink in hand in penthouse afternoon', 'fingers trailing on penthouse furniture before the night'],
    lunch: ['hand near lunch or room service in hotel afternoon', 'fingers on suite furniture or champagne in afternoon', 'warm pre-night hand detail in penthouse'],
    afternoon: ['hand on penthouse furniture in pre-night private ease', 'fingers on bedding or lounge surface before transformation', 'warm private penthouse afternoon hand placement'],
    reset: ['fingers applying makeup or lipstick at vanity', 'hand placing jewelry on in complete night preparation', 'full transformation hands at the mirror — deliberate and focused'],
    golden_hour: ['champagne flute in warm golden-hour penthouse light', 'hand near penthouse window with city amber outside', 'fingers on jewelry in golden-hour pre-night light'],
    dinner: ['champagne glass at VIP dinner in warm candlelight', 'fingers on VIP table in pre-club dinner', 'hand detail at VIP dinner with complete glamour'],
    evening: ['champagne or cocktail in warm VIP club ambient', 'hand near bottle service in back room', 'electric night hand detail in VIP venue warm glow'],
    night: ['champagne at penthouse after-party in 3am city light', 'hand near late-night drink in warm private penthouse', 'fingers trailing on penthouse glass above city at after-dark peak'],
  },

  movementEnergyPools: {
    wake: ['slow', 'warm', 'morning-after'],
    morning_refresh: ['gentle', 'private', 'recovering'],
    getting_dressed: ['building', 'deliberate', 'pre-night'],
    breakfast: ['relaxed', 'warm', 'private'],
    late_morning: ['easy', 'leisure', 'penthouse'],
    lunch: ['slow', 'private', 'pre-night'],
    afternoon: ['calm', 'building', 'interior'],
    reset: ['deliberate', 'electric', 'transformation'],
    golden_hour: ['confident', 'charged', 'pre-night'],
    dinner: ['elegant', 'composed', 'charged'],
    evening: ['electric', 'glamorous', 'alive'],
    night: ['warm', 'private', 'after-midnight'],
  },

  transitionPools: {
    human: {
      wake: ['the after-dark world waking slowly in penthouse morning', 'slow warm morning-after luxury beginning'],
      morning_refresh: ['the hotel bathroom morning ritual after a late night', 'warming up after the night world rested'],
      getting_dressed: ['the pre-night transformation beginning in the afternoon', 'building toward the night identity slowly'],
      breakfast: ['late penthouse brunch with champagne and city view', 'the warm after-dark world in late morning ease'],
      late_morning: ['penthouse afternoon before the night builds', 'the calm private pre-night world'],
      lunch: ['penthouse pre-night afternoon ease', 'warm private interior before the ritual begins'],
      afternoon: ['the private penthouse hour before the full transformation', 'building toward the vanity ritual'],
      reset: ['the full glamour night transformation at the vanity', 'the after-dark world preparing itself completely'],
      golden_hour: ['penthouse golden-hour with champagne and city turning amber', 'first full night look at golden-hour height'],
      dinner: ['VIP pre-club dinner charged and glamorous', 'the night beginning over champagne dinner'],
      evening: ['the electric VIP club arrival in full night glamour', 'after-dark world at its most social and alive'],
      night: ['penthouse after-midnight private world', 'the after-dark world at its most intimate and electric'],
    },
  },

  narrativeIntentPools: {
    wake: ['the after-dark world in private morning — unglamorous but warm and true', 'the private human morning behind the late-night world'],
    morning_refresh: ['resetting from night to day in luxury hotel warmth', 'the after-dark identity refreshing in warm morning private space'],
    getting_dressed: ['the slow afternoon build toward the night identity', 'the after-dark world constructing itself deliberately'],
    breakfast: ['penthouse morning ease before the next night begins', 'the after-dark life in its most private and human form'],
    late_morning: ['private afternoon ease in the after-dark lifestyle', 'the calm private pre-night hour in luxury surroundings'],
    lunch: ['pre-night private luxury ease', 'the penthouse world before the night ritual begins'],
    afternoon: ['the private hour before the full transformation', 'the after-dark world in its most private afternoon moment'],
    reset: ['the full glamour night transformation — the most defining ritual of the after-dark day', 'building the night identity completely at the vanity mirror'],
    golden_hour: ['penthouse pre-night golden hour — the most beautiful pre-club moment', 'champagne and city amber before the electric night opens'],
    dinner: ['the VIP pre-club dinner — the night charged and ready to begin', 'champagne and elegant dinner with everything electric ahead'],
    evening: ['the after-dark world at its most glamorous and electric peak', 'VIP club night at full social and visual maximum'],
    night: ['the private after-midnight penthouse world — the deepest after-dark moment', 'the most intimate and electric private late-night experience'],
  },

  fallbackRules: {
    pacingProfile: { wake: 'slow', morning_refresh: 'slow', getting_dressed: 'slow', breakfast: 'slow', late_morning: 'slow', lunch: 'slow', afternoon: 'slow', reset: 'slow', golden_hour: 'slow', dinner: 'slow', evening: 'medium', night: 'slow' },
    repetitionBreakers: { avoidBackToBackSameLocation: true, avoidBackToBackSameLightingStyle: true, encourageWardrobeEvolution: true },
    worldDefaults: { allowSceneGroupFallbackToPhasePools: true, allowSubLocationFallbackToWorldPools: true, preferSceneGroupsWhenPresent: true },
  },

  exclusions: {
    premium: ['daytime outdoor public spaces', 'corporate or office settings', 'athletic or gym environments', 'cold harsh lighting'],
    hard: ['bright outdoor daylight', 'business settings', 'suburban or domestic spaces', 'morning rush energy'],
  },

  routeRules: {
    worldIdentity: ['the after-dark world is defined by penthouse luxury, VIP nightlife, champagne, and the private world after midnight', 'warm low ambient lighting and electric social energy are the core aesthetics'],
    humanFlow: ['the day begins late with a slow morning-after, builds through afternoon private preparation, reaches the glamour transformation at reset, and peaks in the VIP club and penthouse after-party at night'],
    styling: ['morning-after dishevelled glamour → pre-night casual luxury → full night glamour at the vanity and beyond', 'champagne and luxury accessories define the world'],
    atmosphere: ['warm low nightlife ambient, penthouse city views, VIP back rooms, and late-night private spaces', 'the after-dark world is warm, electric, and always above the city'],
  },
}
