export const STORY_WORLD_BOUDOIR = {
  id: 'boudoir',
  name: 'Boudoir',
  description:
    'A cinematic boudoir world of intimate luxury — silk sheets, mirror rituals, vanity candlelight, lace and satin, the private feminine world at its most beautiful and intentional. Sensual, elegant, personal, powerful.',

  geography: { country: 'private interior', region: 'intimate boudoir suite' },

  identity: {
    archetype: 'intimate luxury creator',
    vibe: ['silk and satin in candlelight', 'private feminine power', 'mirror honesty', 'sensual self-possession', 'the bedroom as the most powerful room'],
    tone: ['sensual', 'intimate', 'candlelit', 'silk-soft', 'mirror-honest', 'quietly powerful', 'warm'],
    persona: ['completely at ease in her most intimate and private world', 'fully in control of the image she creates', 'beautiful without trying and powerful because of it', 'the camera as intimate witness not audience'],
  },

  phaseOrder: ['wake', 'morning_refresh', 'getting_dressed', 'breakfast', 'late_morning', 'lunch', 'afternoon', 'reset', 'golden_hour', 'dinner', 'evening', 'night'],

  phases: {
    wake:            { label: 'Wake',            timeWindows: ['soft morning light on silk sheets', 'pale bedroom dawn'],              pacing: 'slow',   subLocations: ['bedroom-suite', 'bedside-zone'] },
    morning_refresh: { label: 'Morning Refresh', timeWindows: ['warm bathroom morning', 'vanity daylight'],                           pacing: 'slow',   subLocations: ['bathroom-vanity', 'mirror-corner'] },
    getting_dressed: { label: 'Getting Dressed', timeWindows: ['morning dressing light', 'wardrobe soft interior'],                   pacing: 'slow',   subLocations: ['mirror-corner', 'wardrobe-zone'] },
    breakfast:       { label: 'Breakfast',       timeWindows: ['kitchen morning light', 'window glow'],                               pacing: 'slow',   subLocations: ['kitchen-zone', 'window-zone'] },
    late_morning:    { label: 'Late Morning',    timeWindows: ['clean indoor natural light', 'morning content window'],               pacing: 'medium', subLocations: ['mirror-corner', 'bedroom-suite'] },
    lunch:           { label: 'Lunch',           timeWindows: ['soft afternoon room light', 'midday lounge'],                         pacing: 'slow',   subLocations: ['lounge-zone', 'chaise-longue'] },
    afternoon:       { label: 'Afternoon',       timeWindows: ['warm afternoon interior', 'bath or window light'],                    pacing: 'slow',   subLocations: ['bath-zone', 'window-zone', 'chaise-longue'] },
    reset:           { label: 'Reset',           timeWindows: ['late afternoon vanity light', 'golden pre-evening'],                  pacing: 'slow',   subLocations: ['vanity-zone', 'mirror-corner'] },
    golden_hour:     { label: 'Golden Hour',     timeWindows: ['warm amber interior glow', 'window golden hour light'],               pacing: 'slow',   subLocations: ['window-zone', 'vanity-zone', 'bedroom-suite'] },
    dinner:          { label: 'Dinner',          timeWindows: ['candlelit room', 'early evening warm interior'],                      pacing: 'slow',   subLocations: ['bedroom-suite', 'vanity-zone', 'chaise-longue'] },
    evening:         { label: 'Evening',         timeWindows: ['low warm evening ambient', 'intimate evening light'],                 pacing: 'slow',   subLocations: ['bedroom-suite', 'mirror-corner', 'chaise-longue'] },
    night:           { label: 'Night',           timeWindows: ['candlelight only', 'very soft warm night light'],                     pacing: 'slow',   subLocations: ['bedroom-suite', 'bedside-zone'] },
  },

  locations: [
    'silk-sheeted bed in morning or candlelight', 'full-length bedroom mirror', 'vanity table with jewelry and perfume',
    'window with sheer curtain in warm light', 'deep bathtub with candles and rose petals', 'walk-in wardrobe with lace and silk',
    'chaise longue in warm interior light', 'penthouse bedroom with city view', 'candle-lit intimate room',
  ],

  subLocations: {
    'bedroom-suite': {
      id: 'bedroom-suite', name: 'Bedroom Suite', mapAnchor: 'private boudoir bedroom',
      category: 'private-core',
      bestPhases: ['wake', 'late_morning', 'dinner', 'evening', 'night'],
      overlays: ['silk bedding', 'warm ambient light', 'private intimate atmosphere', 'velvet or linen textures'],
      locations: ['silk-sheeted bed', 'soft pillow arrangement', 'private bedroom interior', 'warm bedroom corner'],
    },
    'bedside-zone': {
      id: 'bedside-zone', name: 'Bedside Zone', mapAnchor: 'bedside table area',
      category: 'wake-detail',
      bestPhases: ['wake', 'night'],
      overlays: ['bedside candle or lamp', 'perfume bottle nearby', 'silk sheets', 'quiet intimate detail'],
      locations: ['bedside table with candle and perfume', 'soft sheets edge', 'intimate morning detail'],
    },
    'bathroom-vanity': {
      id: 'bathroom-vanity', name: 'Bathroom Vanity', mapAnchor: 'private boudoir bathroom',
      category: 'self-care',
      bestPhases: ['morning_refresh'],
      overlays: ['bathroom mirror lit', 'beauty products arranged', 'steam or warm light', 'private ritual atmosphere'],
      locations: ['bathroom vanity mirror', 'beauty ritual setting', 'warm private bathroom', 'skincare ritual corner'],
    },
    'mirror-corner': {
      id: 'mirror-corner', name: 'Mirror Corner', mapAnchor: 'full-length bedroom mirror',
      category: 'reflection-styling',
      bestPhases: ['morning_refresh', 'getting_dressed', 'late_morning', 'reset', 'evening'],
      overlays: ['full-length mirror', 'warm interior light', 'reflection framing', 'intimate self-study'],
      locations: ['full-length mirror', 'mirror reflection zone', 'private styling mirror', 'bedroom mirror corner'],
    },
    'wardrobe-zone': {
      id: 'wardrobe-zone', name: 'Wardrobe Zone', mapAnchor: 'walk-in wardrobe',
      category: 'dressing',
      bestPhases: ['getting_dressed'],
      overlays: ['lace and silk hanging', 'warm wardrobe interior light', 'lingerie and robes arranged', 'intimate dressing energy'],
      locations: ['walk-in wardrobe with lace and silk', 'lingerie selection corner', 'private dressing zone'],
    },
    'kitchen-zone': {
      id: 'kitchen-zone', name: 'Kitchen Zone', mapAnchor: 'boudoir apartment kitchen',
      category: 'lifestyle-morning',
      bestPhases: ['morning_refresh', 'breakfast'],
      overlays: ['morning coffee setup', 'soft interior daylight', 'rose or candle on counter', 'intimate morning atmosphere'],
      locations: ['kitchen with morning coffee', 'intimate apartment kitchen morning'],
    },
    'window-zone': {
      id: 'window-zone', name: 'Window Zone', mapAnchor: 'sheer-curtain window light',
      category: 'light-mood',
      bestPhases: ['breakfast', 'afternoon', 'golden_hour'],
      overlays: ['sheer curtain moving in light', 'soft directional daylight', 'warm window glow', 'private intimate frame'],
      locations: ['window with sheer curtain', 'golden window light corner', 'soft window morning light'],
    },
    'lounge-zone': {
      id: 'lounge-zone', name: 'Lounge Zone', mapAnchor: 'intimate lounge area',
      category: 'leisure',
      bestPhases: ['lunch', 'afternoon'],
      overlays: ['soft lounge interior', 'warm ambient light', 'plush textures', 'private afternoon ease'],
      locations: ['private lounge with soft lighting', 'intimate sofa area', 'boudoir lounge corner'],
    },
    'chaise-longue': {
      id: 'chaise-longue', name: 'Chaise Longue', mapAnchor: 'bedroom chaise or daybed',
      category: 'reclining-luxury',
      bestPhases: ['lunch', 'afternoon', 'dinner', 'evening'],
      overlays: ['velvet or silk chaise', 'warm ambient lamp beside', 'private reclining luxury', 'intimate afternoon or evening'],
      locations: ['velvet chaise longue', 'silk daybed in warm light', 'private reclining corner'],
    },
    'bath-zone': {
      id: 'bath-zone', name: 'Bath Zone', mapAnchor: 'deep bathtub with candles',
      category: 'sensory-ritual',
      bestPhases: ['afternoon'],
      overlays: ['deep bathtub with candles', 'rose petals on water', 'steam and warm light', 'private ritual bathing'],
      locations: ['deep bathtub with rose petals and candles', 'candlelit bath ritual', 'warm private bath setting'],
    },
    'vanity-zone': {
      id: 'vanity-zone', name: 'Vanity Zone', mapAnchor: 'vanity table with mirror and lights',
      category: 'preparation-ritual',
      bestPhases: ['reset', 'golden_hour', 'dinner'],
      overlays: ['lit vanity mirror', 'perfume and jewelry laid out', 'warm vanity bulb glow', 'private beauty ritual energy'],
      locations: ['vanity table with mirror and perfume', 'jewelry and beauty ritual zone', 'lit vanity mirror corner'],
    },
  },

  sceneVariants: {
    wake: ['waking slowly in silk sheets with soft light crossing the bedroom floor', 'lying still in warm boudoir morning before rising', 'first light entering through sheer curtains across white linen'],
    morning_refresh: ['morning skincare ritual at the vanity in soft daylight', 'wrapped in a silk robe at the bathroom mirror after showering', 'applying perfume and touching jewelry in the morning routine'],
    getting_dressed: ['choosing lace lingerie in front of the full-length mirror', 'stepping into silk and making small adjustments in the mirror', 'the slow ritual of selecting what to wear in warm wardrobe light'],
    breakfast: ['morning coffee at the window in a silk robe with sheer curtains behind', 'light breakfast with a rose beside it in warm boudoir morning light'],
    late_morning: ['mirror study in deliberate morning light — full-length, intimate, honest', 'candid bed-side moment in lace in natural late-morning light'],
    lunch: ['reclining on the chaise longue in soft afternoon light', 'slow midday in a private boudoir lounge in warm interior calm'],
    afternoon: ['long candlelit bath with rose petals and complete privacy', 'afternoon chaise recline in silk in warm room light', 'lying by the sheer window in warm afternoon glow'],
    reset: ['vanity ritual reset before the evening — perfume, jewelry, and deliberate presence', 'retouching at the lit vanity in warm late-afternoon indoor light'],
    golden_hour: ['golden window light falling across silk and skin in the most cinematic boudoir moment', 'standing at the golden-hour window in lace with warm amber light behind'],
    dinner: ['candlelit chaise or bedroom sitting in intimate warm evening', 'slow intimate dinner moment in a private boudoir room lit only by candles'],
    evening: ['lying across the bed in candlelight — the most intimate boudoir evening energy', 'mirror evening moment in low ambient intimate boudoir light'],
    night: ['candlelit bedside moment before sleep — silk, perfume, private calm', 'the final private boudoir moment — deep warm night light and silk sheets'],
  },

  actionPools: {
    wake: [
      'lying still in silk sheets before fully waking',
      'reaching slowly for the perfume bottle on the bedside while still half in the sheets',
      'stretching slowly in warm private morning with one arm extended across the linen',
      'turning onto one side in silk sheets as the morning light shifts across the pillow',
      'pressing one palm flat to the warm mattress before rising — unhurried private morning',
      'eyes half-open, one hand trailing the silk edge of the duvet in pale first light',
    ],
    morning_refresh: [
      'applying skincare at the vanity mirror with deliberate morning attention',
      'wrapping in a silk robe after showering — tying it slowly at the waist',
      'touching perfume to the throat and wrist in the morning ritual',
      'leaning close to the bathroom mirror, studying the bare morning face in clean light',
      'running hands through damp hair at the vanity, looking into the mirror without hurry',
      'pressing a warm towel to the face after skincare — private self-care ease',
    ],
    getting_dressed: [
      'selecting lace or silk lingerie from the wardrobe in warm interior light',
      'stepping in front of the full-length mirror to check the look with a slow assessment',
      'adjusting a bralette strap with both hands, eyes on the mirror with complete self-possession',
      'pulling a silk slip over bare skin and letting it fall in front of the mirror',
      'holding a lace piece up to the body in wardrobe light before selecting it',
      'fastening a delicate clasp at the back in slow deliberate close movement',
    ],
    breakfast: [
      'making coffee in a silk robe in soft morning light by the kitchen window',
      'standing at the window with coffee, looking out through sheer curtains in private morning warmth',
      'placing a single rose beside the breakfast cup on the kitchen counter',
      'sitting at the kitchen window ledge with a cup in both hands, robe barely tied',
      'pouring cream into coffee slowly at the kitchen counter, morning window behind',
      'bringing a warm mug to the lips at the window — the sheer curtain moving softly beside',
    ],
    late_morning: [
      'studying the full-length mirror with honest deliberate attention',
      'lying on the bed in lace in clean natural morning light — at ease and composed',
      'moving slowly through the boudoir interior, touching a fabric or surface in passing',
      'sitting at the edge of the bed in natural morning light with hands resting in lap',
      'turning profile to the mirror, assessing the look with calm self-awareness',
      'leaning against the bedroom wall near the mirror in lace — easy natural presence',
    ],
    lunch: [
      'reclining fully on the chaise longue in warm afternoon light with legs extended',
      'lying on soft lounge furniture in private boudoir ease, one arm draped over the edge',
      'slow idle private afternoon in silk on the chaise, gaze soft and unhurried',
      'bringing a glass of water or wine to the lips while reclining on the chaise',
      'adjusting position on the velvet lounge in a long silk slip, one knee bent',
      'trailing one hand slowly across the chaise fabric while looking toward the window',
    ],
    afternoon: [
      'lying in a candlelit bath with rose petals and steam — eyes closed in private pleasure',
      'reclining on the chaise by the window in warm afternoon light, arm resting along the back',
      'slowly adjusting position in warm afternoon interior light — the most private ease',
      'lowering into the bath slowly, one hand on the edge, candlelight on water around',
      'lying by the sheer afternoon window on the chaise, light falling across bare skin',
      'sitting up in the bath, arms crossed on the edge, looking out with private calm',
    ],
    reset: [
      'touching up at the lit vanity before the evening with deliberate precision',
      'applying perfume at the vanity mirror — pressing it to the throat with eyes closed briefly',
      'placing jewelry on at the vanity in deliberate slow ritual — pearl or gold against warm skin',
      'leaning into the vanity mirror, applying lipstick with complete private composure',
      'brushing hair at the vanity, eyes in the mirror, warm light surrounding the face',
      'opening the jewelry box at the vanity, selecting a piece and holding it to the light',
    ],
    golden_hour: [
      'standing in warm window light as it falls across silk and skin — turning slowly toward it',
      'turning slowly in golden-hour light in front of the mirror as amber fills the room',
      'holding a sheer curtain edge and looking out as golden light floods in from behind',
      'sitting at the window ledge in lace as amber light crosses the fabric and skin',
      'raising one hand to touch the sheer curtain as golden-hour light moves through it',
      'standing with eyes half-closed in the warmest amber light of the day',
    ],
    dinner: [
      'reclining on the chaise in candlelight with complete warm intimate ease',
      'sitting at the bedroom edge in warm intimate evening, hands resting in silk lap',
      'slow movement through the candlelit boudoir room with deliberate composure',
      'holding a champagne glass in candlelight, looking into it before the first sip',
      'lying across the chaise in candlelight with one arm trailing toward the floor in lace',
      'turning slowly in the candlelit room, fabric catching the warm orange light',
    ],
    evening: [
      'lying across the bed in warm intimate candlelight, legs extended in silk',
      'touching perfume or fabric in low ambient boudoir evening with deliberate ease',
      'mirror moment in intimate low evening light — studying the reflection with private warmth',
      'reclining against the silk headboard in low evening glow, one knee drawn up',
      'trailing fingers across the silk duvet surface while looking toward the warm lamp',
      'sitting at the bedroom vanity in low evening ambient, touching jewelry before removing it',
    ],
    night: [
      'the final candlelit bedside moment in silk — sitting at the edge before lying back',
      'lying back in deep private boudoir calm with one candle as the only source',
      'closing the day in the warmth of silk and candle — hand resting near the flame',
      'reaching to extinguish the candle slowly in the near-dark private night',
      'lying completely still in silk in warm candlelight as the room breathes around',
      'one hand pulling the silk sheet up slowly in the deepest most private night moment',
    ],
  },

  environmentPools: {
    wake: [
      'silk-sheeted bed in pale morning boudoir light with city just visible through sheer curtain',
      'soft pillow and ivory linen in warm pale first-light, room in private still silence',
      'private bedroom interior in early morning stillness with warm amber lamp still glowing at bedside',
      'rumpled silk bedding with pale window light crossing the floor in long warm diagonal',
      'bedroom corner in soft morning diffuse — silk catching first light at the window edge',
      'bedside zone in warm pre-dawn boudoir quiet, candle just extinguished, silk warm around',
    ],
    morning_refresh: [
      'bathroom vanity with soft daylight and beauty products arranged in warm order',
      'bathroom mirror in clean natural morning light — face close and private',
      'warm private bathroom with steam rising and soft diffuse morning filling the room',
      'marble vanity with skincare laid out in soft 5500K window daylight',
      'bathroom with clean white surfaces and a single candle still lit at the mirror edge',
      'intimate bathroom ritual corner — warm towel, damp skin, and natural morning around',
    ],
    getting_dressed: [
      'walk-in wardrobe with lace and silk pieces hanging in warm interior amber light',
      'full-length mirror corner in morning dressing light — room depth behind in soft focus',
      'private wardrobe zone with lingerie arranged on hooks and folded silk on shelves',
      'warm bedroom dressing corner with silk robe draped over a chair near the mirror',
      'open wardrobe with ivory and blush lace visible in soft interior morning glow',
      'bedroom mirror against a wall of warm interior — deep room receding in bokeh behind',
    ],
    breakfast: [
      'kitchen with rose and coffee in soft morning window light, sheer curtain behind',
      'window seat with sheer curtain and morning light filling the frame from behind',
      'intimate apartment morning with coffee and calm — silk robe against kitchen warmth',
      'kitchen counter in clean 5000K window light, coffee steam rising beside a small rose',
      'boudoir kitchen window moment — warm cup, pale morning, no city noise yet',
      'window ledge at breakfast in soft directional morning light, curtain catching a gentle draft',
    ],
    late_morning: [
      'full-length mirror in clean natural late-morning light — the most honest and private frame',
      'silk-sheeted bed in natural daylight — honest clean morning light across white linen',
      'private bedroom in clean interior noon light, warm and even across skin and fabric',
      'bedroom corner in even natural morning with no harsh shadow — intimate and editorial',
      'mirror study position with soft window at one side, room warm behind in shallow focus',
      'boudoir bedroom in late-morning natural light — lace casting soft shadow on warm skin',
    ],
    lunch: [
      'chaise longue in soft warm afternoon boudoir light — velvet catching the ambient glow',
      'private lounge with plush textures and warm ambient lamp as the only visible source',
      'intimate afternoon in soft interior glow — chaise and silk together in quiet warmth',
      'velvet chaise in warm 4000K room ambient, sheer curtain filtering soft afternoon behind',
      'lounge corner with silk cushions and afternoon light grazing across the chaise fabric',
      'boudoir afternoon lounge — lamp lit beside the chaise, warm pool of amber around',
    ],
    afternoon: [
      'deep bathtub with candles, rose petals on warm water, and steam rising in private calm',
      'chaise longue by the sheer window in warm afternoon — skin and silk in soft direct light',
      'soft boudoir interior in warm afternoon intimate light, sheer curtain casting moving shadow',
      'bath ritual zone — candles at the rim, water catching amber flicker, private and still',
      'afternoon window in long warm diagonal across the chaise — sheer fabric over skin',
      'deep private bath in near-dim room, candles as the only source, rose petals on still water',
    ],
    reset: [
      'lit vanity mirror with perfume and jewelry in late afternoon warm glow',
      'vanity table in warm pre-evening indoor 3200K glow — beauty ritual laid out with care',
      'intimate vanity ritual corner — lit mirror, warm bulb, and quiet preparation energy',
      'vanity with open jewelry box and perfume arranged in warm soft light',
      'mirror-lit vanity in the last of the afternoon before evening — the golden in-between',
      'boudoir preparation zone — lipstick, pearls, and warm vanity light against darker room behind',
    ],
    golden_hour: [
      'sheer-curtain window in full golden-hour amber light flooding the silk and room',
      'bedroom with amber window light catching silk and skin in warm diagonal glow',
      'vanity in warm golden-hour indoor amber — jewelry glowing, mirror warm-toned',
      'window corner in the richest amber of the day — silk curtain backlit and glowing',
      'boudoir interior at golden hour — every surface in warm amber, shadow soft and long',
      'full-length mirror at golden-hour angle — amber room behind, subject edged in warm rim',
    ],
    dinner: [
      'candlelit bedroom in intimate warm evening — single candle as the sole visible source',
      'warm boudoir interior lit only by candles — deep warm shadow beyond the flame',
      'private dinner-hour candlelit intimate room — chaise in warm orange pool',
      'candlelit velvet chaise with warm orange detail and deep boudoir darkness behind',
      'bedroom edge in candle glow — silk, warm orange, and deep intimate quiet',
      'boudoir dinner setting — three candles on the vanity, room in deep amber warmth',
    ],
    evening: [
      'low ambient candlelit bedroom in evening warmth — every surface in soft gold',
      'mirror corner in intimate low evening light — warm reflection and deep room behind',
      'soft private boudoir evening with warm textures catching a single lamp glow',
      'bedroom in low warm evening ambient — silk duvet catching the lamp from the bedside',
      'chaise in deep boudoir evening glow — velvet and warm lamplight and quiet',
      'evening boudoir interior — two sources of warm light, everything else in soft shadow',
    ],
    night: [
      'candlelit bedside in deep private warm night — one candle, total darkness beyond',
      'silk sheets in single warm night lamp glow — bed warm, room almost dark around',
      'deep private boudoir night in warm darkness — barely anything visible beyond the candle',
      'bedside zone in near-dark with a single small candle, silk catching warm orange',
      'the boudoir at its darkest — one flame, silk, and complete private calm',
      'night boudoir — warm candle at the bedside, room in absolute intimate darkness',
    ],
  },

  moodPools: {
    wake: [
      'soft private intimate waking calm — completely unhurried and completely alone',
      'silk-warm morning ease before any awareness of the world outside',
      'unhurried boudoir morning luxury — the day has not begun, only warmth exists',
      'the most private and beautiful morning state — half-asleep in silk and light',
      'warm private waking ease — no performance, no audience, only this room',
      'boudoir morning stillness — the private world at its most gentle and real',
    ],
    morning_refresh: [
      'clean private self-care ritual energy — deliberate and completely personal',
      'warm fresh boudoir morning composure building at the mirror',
      'private morning elegance in candlelit warmth — the ritual that creates the day',
      'intimate bathroom calm — beauty ritual as a form of private feminine power',
      'focused self-care presence in morning light — quiet, precise, and deeply personal',
      'the morning bathroom as the most private stage — no one watching, completely free',
    ],
    getting_dressed: [
      'deliberate feminine preparation — each piece chosen with complete self-awareness',
      'slow beautiful dressing ritual — private and powerful before anyone else sees',
      'intimate self-aware morning transformation — lace and silk as the day\'s first language',
      'the wardrobe as a space of total feminine control — everything selected, nothing rushed',
      'dressing with complete self-possession — the ritual that signals the day has intention',
      'private sensual morning ease while dressing — unhurried, beautiful, self-directed',
    ],
    breakfast: [
      'quiet private morning ease — silk and coffee and no one in the world yet',
      'warm window-light boudoir calm — the soft in-between of morning and day',
      'slow private luxury morning — the best hour before the world makes demands',
      'boudoir kitchen warmth — the most private and human part of the intimate morning',
      'coffee and silk and morning light — the simplest form of boudoir luxury',
      'unhurried window morning — private feminine ease at its most beautiful and unguarded',
    ],
    late_morning: [
      'honest intimate confidence — the mirror and the light and nothing to hide',
      'self-possessed boudoir natural presence in clean honest morning light',
      'warm private editorial energy — natural light making everything real and beautiful',
      'the boudoir in its most truthful form — natural, honest, and quietly powerful',
      'morning bedroom presence that needs no performance — ease and beauty together',
      'clean late-morning intimacy — lace in natural light and complete private composure',
    ],
    lunch: [
      'slow private afternoon indulgence — chaise, silk, and complete warm ease',
      'warm intimate leisure ease — the afternoon that belongs entirely to her',
      'reclining private boudoir calm — the midday world outside doesn\'t exist',
      'the deepest unhurried afternoon in a private silk world',
      'chaise ease in warm ambient — private feminine indulgence at its most honest',
      'boudoir afternoon as pure pleasure — nothing needed, nothing demanded',
    ],
    afternoon: [
      'deep sensory bathing ritual pleasure — candle warmth and rose-scented water',
      'warm private boudoir afternoon luxury — the bath as a complete private world',
      'slow intimate self-indulgence in a room lit only by candles',
      'the afternoon that exists only for sensation — no audience, no schedule',
      'rose petals and warm water and total private ease — the boudoir at its most sensory',
      'the most indulgent private hour of the boudoir day',
    ],
    reset: [
      'deliberate vanity ritual composure — the moment the day pivots toward evening',
      'warm pre-evening feminine refinement — precise, controlled, and completely aware',
      'controlled private preparation energy — the most intentional moment of the day',
      'the vanity as threshold — between the private day and the intimate evening',
      'pre-evening boudoir composure building at the lit mirror — focused and beautiful',
      'the ritual of evening preparation — slow, warm, and completely self-directed',
    ],
    golden_hour: [
      'the most cinematic boudoir moment — golden light on silk and skin and total warmth',
      'warm intimate golden anticipation — the evening waiting in amber behind the window',
      'beautiful private presence in perfect golden light — completely at ease and magnetic',
      'the boudoir in its most photographic state — golden, warm, and entirely itself',
      'amber-soaked intimate luxury — the hour that makes every surface into gold',
      'golden-hour boudoir ease — the most naturally beautiful moment of the entire day',
    ],
    dinner: [
      'warm candlelit intimate evening — the boudoir sealed in orange and private',
      'slow private boudoir evening sensuality — every movement deliberate in the candle warm',
      'deliberately intimate controlled warmth — the evening deepening with intention',
      'the boudoir after dark — candle, silk, and the particular warmth of complete privacy',
      'candlelit intimate elegance — beautiful and private and completely unhurried',
      'the most intimate dinner hour — no restaurant, no world, only this room and this light',
    ],
    evening: [
      'deep private intimate warmth — the boudoir at its most deliberately feminine',
      'low light boudoir feminine power — shadow and warm glow and complete ease',
      'slow deliberate intimate evening — every surface soft, every moment private',
      'the evening boudoir as a sealed world — warm, dark, intimate, and entirely hers',
      'intimate evening ease in low warm glow — no performance, only presence',
      'warm amber boudoir evening — quiet power and total private feminine calm',
    ],
    night: [
      'the deepest most private boudoir calm — candle, silk, and near-total darkness',
      'soft warm intimate night energy — the day complete, the privacy absolute',
      'completely private silk and candlelight stillness — the boudoir at its most truthful',
      'the final intimate hour — warm, quiet, and entirely personal',
      'deep private night warmth — the world sealed out, the boudoir sealed in',
      'the boudoir night at its most powerful — not for anyone, not for any reason, just this',
    ],
  },

  cameraPools: {
    wake: [
      '85mm low angle from bed edge, shallow focus, window dissolved in morning bokeh behind',
      '135mm close-up at face height, pale morning light defining skin edge against silk linen',
      '50mm mid-level from bedside, full sheet scene, morning window soft fill in background',
      '85mm slightly elevated from above, straight down on pillow and face in pale first-light',
      '135mm extreme close on hand resting on silk edge, morning light raking across fabric texture',
      '50mm wide from bedroom doorway, silk bed in full frame, sheer curtain light behind subject',
    ],
    morning_refresh: [
      '85mm bathroom mirror close, reflection at same focal plane as subject in morning light',
      '50mm vanity mid shot, beauty products compressing behind in soft warm bokeh',
      '135mm extreme close on hands at skincare ritual, face softly focused behind',
      '85mm over-shoulder into mirror, double-image depth in warm bathroom light',
      '35mm wide bathroom vanity scene, products and mirror and morning light all in frame',
      '135mm close on face in mirror, bathroom receding into warm blur behind reflection',
    ],
    getting_dressed: [
      '50mm mirror-framed full-length shot, wardrobe depth receding behind in warm bokeh',
      '85mm mid-length dressing angle, soft room depth and silk pieces hanging behind subject',
      '135mm close on hands adjusting lace or clasp, face blurred in soft background',
      '85mm side angle at wardrobe, lace and silk in shallow focus behind subject',
      '50mm floor-to-ceiling mirror shot with full-body in frame, room warm and receding behind',
      '135mm over-shoulder into full mirror — face and hands in sharp focus, room dissolving',
    ],
    breakfast: [
      '85mm window-side seated, sheer curtain dissolving in morning bokeh behind subject',
      '50mm kitchen medium, morning light compressing soft warm behind subject',
      '135mm close on hands around coffee cup, window light raking across silk robe detail',
      '85mm low kitchen angle looking up slightly, window bright behind subject in warm silhouette rim',
      '35mm wide kitchen morning scene — robe, cup, rose, and sheer window all in frame',
      '135mm tight on face at window, warm morning dissolving to bright in background behind',
    ],
    late_morning: [
      '85mm full-length mirror study, honest natural light, room depth in background',
      '135mm close-up at face or chest height, natural light defining every intimate detail',
      '50mm wide bedroom natural light, full scene with bed and window visible behind subject',
      '85mm from corner of room, clean natural noon light on subject, soft wall behind',
      '135mm tight on reflection in mirror, both real and reflected subject in natural light',
      '50mm mid-length side angle, natural window light as clean key, no artificial fill',
    ],
    lunch: [
      '85mm chaise long angle, warm room depth and lamp glow receding behind subject',
      '135mm reclining close, silk texture in sharp foreground, face and room soft behind',
      '50mm wide chaise scene, lounge and window and afternoon light all present',
      '85mm from floor level beside chaise, subject elevated and reclining against warm depth',
      '135mm close on face reclining, chaise arm visible in foreground, room amber behind',
      '85mm side angle on chaise, silk fabric in close foreground, warm room dissolving back',
    ],
    afternoon: [
      '85mm bath bird\'s eye, candles creating warm secondary bokeh in water and around',
      '135mm close bath detail, steam diffusing background into warm atmospheric blur',
      '50mm wide bath scene, candles at rim, rose petals on water, private complete frame',
      '85mm chaise afternoon side, sheer window behind, skin and silk in soft natural light',
      '135mm close on hand at bath rim with petals, face softly focused beyond in candle warm',
      '85mm low angle from bath floor edge, steam in foreground, face above water line behind',
    ],
    reset: [
      '85mm lit vanity close, vanity mirror creating double-image depth in warm interior',
      '50mm vanity mid shot, warm interior depth receding behind reflection and subject',
      '135mm extreme close on jewelry being placed on bare skin at vanity — hands and throat',
      '85mm over-shoulder into lit vanity mirror, face and hands sharp in warm mirror light',
      '35mm wide vanity scene — products, mirror, warm light, full preparation tableau',
      '135mm close on face in vanity mirror, warm bulb ring as halo, dark room behind',
    ],
    golden_hour: [
      '135mm window backlit close, golden rim light defining edge of subject beautifully',
      '24mm wide window shot, golden light flooding the full room and all surfaces behind',
      '85mm low angle at window, amber light raking across silk and skin from behind subject',
      '135mm tight backlit golden close, face in soft shadow, amber rim-lit silhouette edge',
      '50mm medium from inside room, golden window behind subject flooding ambient with amber',
      '85mm side angle at window, amber light crossing room diagonally, silk catching glow',
    ],
    dinner: [
      '85mm candlelit seated portrait, candle glow as key light source at medium close',
      '135mm intimate evening close, candle dissolved in warm background bokeh behind subject',
      '50mm wide candlelit chaise scene, multiple candles visible, room receding in amber dark',
      '85mm low angle from floor, candle as foreground warm light, face above in candle glow',
      '135mm extreme close on face in single candle — warm orange edge on skin, dark behind',
      '85mm from across the room, subject in center of candlelit warm pool, dark room framing',
    ],
    evening: [
      '85mm low ambient bedroom medium, warm glow filling soft background around subject',
      '135mm intimate evening close, single lamp as the sole warm source in the frame',
      '50mm wide bedroom evening, lamp at bedside casting warm pool, darkness beyond it',
      '85mm side angle from mirror corner, low warm ambient, soft double-light from lamp',
      '135mm tight on face in low warm ambient, dark room dissolved behind in soft amber',
      '85mm from door angle, subject in warm lamp pool, long room in evening dark behind',
    ],
    night: [
      '135mm candlelit bedside close-up, single candle as warm sole source in near-darkness',
      '85mm soft side angle, deep warm shadow framing subject with one candle barely holding',
      '50mm wide night boudoir, candle in mid-ground, silk bed in darkness behind subject',
      '135mm extreme close on candle and hand in night dark — the most intimate night detail',
      '85mm low from mattress level, candle at height of frame, face in warm orange above',
      '135mm tight face in near-total darkness, only warm candle edge defining the subject',
    ],
  },

  lightingPools: {
    wake: [
      'pale 5200K morning light entering through sheer curtains, long warm shadows across silk linen',
      'soft diffused white morning entering through sheer fabric, warm edge on pillow and sheet',
      '5000K even window diffuse through two layers of sheer curtain — no shadow, just warmth',
      'first morning light at 5400K entering at a low diagonal, silk catching warm orange edge',
      'pre-dawn warm lamp still glowing at 2800K, pale window beginning at the horizon behind',
      'morning window at 5200K through sheers with barely visible city beyond — pure pale warmth',
    ],
    morning_refresh: [
      'clean 5500K vanity daylight on bare skin and mirror, no harsh shadows anywhere',
      'reflected morning light bouncing off white bathroom surfaces into the vanity interior',
      '5200K window fill bouncing from white tiles — even, fresh, and skin-warm throughout',
      'bathroom mirror with 5000K daylight key from window and soft white tile fill',
      'vanity lit at 4800K warm daylight with white towel bounce softening every shadow',
      'clean morning 5600K direct through frosted bathroom window — honest flattering fill',
    ],
    getting_dressed: [
      'warm 4800K interior morning light on fabric and skin, gold catching lace detail',
      'soft directional window light through curtains, even warm fill across the dressing area',
      '4500K interior morning key from one window, silk and lace in sharp warm foreground',
      'wardrobe interior at 3800K ambient warm bulb, deep room behind in soft dark',
      'morning interior at 5000K from window, lace casting delicate warm shadow on skin',
      'full-length mirror catching 4800K window light and bouncing it back onto subject',
    ],
    breakfast: [
      'warm 5000K morning window light, sheer curtain diffusing direct source to soft fill',
      'kitchen morning light at shallow angle, coffee steam catching warm directional glow',
      '5200K direct morning window at side angle — silk robe lit on one face, gentle shadow',
      '4800K kitchen window light with sheer bounce — warm, even, and completely flattering',
      'morning window at 5000K catching the coffee cup and robe and curtain simultaneously',
      'soft 5400K window backlight through sheer — warm rim on subject, even ambient fill',
    ],
    late_morning: [
      'clean 5600K natural daylight through window, honest and direct, no artificial fill',
      'soft interior noon light, even and flattering, natural color rendering throughout',
      'even 5500K north-facing window — completely flat, completely honest, completely beautiful',
      '5600K natural daylight at noon — no shadow direction, every detail softly visible',
      'clean window noon at 5400K with soft white ceiling bounce — editorial natural fill',
      'natural 5500K midday light filling the room with even flattering warmth',
    ],
    lunch: [
      'warm 4000K afternoon room ambient, no direct source, even fill across lounge surfaces',
      'soft filtered afternoon light through curtains, warm stripe across chaise velvet fabric',
      '4200K afternoon window through heavy curtain, warm wash across chaise and silk',
      'single 3800K amber lamp at chaise edge — soft warm pool over the reclining subject',
      '4000K room ambient with warm lamp adding 2800K secondary pool at side of chaise',
      'afternoon window at 4500K, partially filtered by sheer curtain, stripe on velvet',
    ],
    afternoon: [
      'candlelight at 1700K as primary source in bath, warm orange glow on steam and water',
      'warm afternoon window at 4200K, soft and flattering across the chaise',
      'multiple bath candles at 1700K-1800K creating warm even orange fill with soft bokeh',
      'bath interior at 1600K candle only — deep orange, steam refracting the light warmly',
      'afternoon window through heavy sheer at 3800K, soft warm horizontal stripe on skin',
      'candlelit bath at 1700K with secondary 4200K afternoon window fill creating contrast',
    ],
    reset: [
      'warm 3200K vanity bulb ring, intimate close flattering light with no harsh shadow',
      'warm vanity interior at 3000K, soft fill bouncing from mirror back onto subject face',
      'vanity bulb at 3400K warm — slightly golden on skin, dark room behind the subject',
      '3200K warm vanity key with soft mirror bounce fill — the most flattering preparation light',
      'lit vanity at 3000K against darker room interior — beauty portrait in warm indoor glow',
      'warm 3200K vanity with dark room behind creating intimate pre-evening portrait depth',
    ],
    golden_hour: [
      'rich 2800K golden window light entering at low angle, amber across silk and skin',
      'warm golden backlight from window, rim lighting subject edge, room interior dissolved in glow',
      '2600K deep amber through sheer curtain — richest warmth of the day on every surface',
      'golden-hour window at 2700K — warm long horizontal beam crossing the room at low angle',
      '2800K amber window key with 3200K interior ambient fill — golden ratio perfect ratio',
      'setting sun at 2600K through sheers — backlit rim on subject, room in amber gold beyond',
    ],
    dinner: [
      'candlelight at 1800K as sole key source, intimate warm fill, deep shadow beyond',
      'warm 2500K single candle, flickering orange edge on skin and fabric',
      'candle at 1700K as the only light in the room — maximum intimacy, deep warm shadow',
      'two candles at 1800K creating cross-light on subject — warm from both sides, dark beyond',
      'single candle at 1900K on vanity, face half in warm light and half in deep intimate dark',
      'candlelit chaise scene at 1700K — warm orange pool on subject, velvet in soft dark around',
    ],
    evening: [
      'low 2400K ambient room lamp, soft warm fill, all surfaces in soft golden evening shadow',
      'single bedside or chaise lamp at 2200K, intimate pool of warm light in private room',
      '2600K warm lamp at room edge — soft warm fill spreading across silk and skin',
      'two warm lamps at 2400K and 2200K — layered warm ambient in low intimate evening',
      'single low lamp at 2200K at bedside, dark room behind, silk catching warm amber glow',
      '2400K room ambient with candle at 1800K adding secondary warm pool on subject',
    ],
    night: [
      'single candle at 1600K, deep warm orange light in total room darkness',
      'bedside lamp at 2100K, soft warm pool in dark boudoir room',
      'one candle at 1500K barely burning — minimum light, maximum intimate warmth remaining',
      'near-dark at 1600K candle — deep orange edge on silk and skin, everything else in black',
      'final candle at 1700K in room otherwise totally dark — warm and completely private',
      'single warm night source at 2000K, just enough to see the silk and no more beyond',
    ],
  },

  stylingPools: {
    wardrobe: {
      wake: [
        'ivory silk nightgown barely held at one shoulder, catching pale morning window',
        'nothing but silk sheets and a bare shoulder in warm morning light',
        'soft oversized sleep shirt in pale linen, half off one shoulder in morning ease',
        'barely-there morning warmth — slip of silk covering nothing more than necessary',
        'white cotton sleep dress with thin straps — delicate and private in early light',
        'blush silk chemise, straps slipping, linen around and warm morning in the room',
      ],
      morning_refresh: [
        'ivory silk robe barely tied after shower — open at the collar and falling loose',
        'white towel wrapped high after bath, skin warm and damp in morning light',
        'skin-forward bare morning before dressing — nothing but bare post-shower ease',
        'pale pink silk robe, belt hanging undone, at the bathroom mirror in steam',
        'cream cotton wrap robe, loosely knotted, damp skin and hair in morning light',
        'nothing but a towel at the vanity — bare shoulders and morning skincare ritual',
      ],
      getting_dressed: [
        'ivory lace bralette with matching high-cut brief — warm detailed lingerie in morning light',
        'sheer silk slip in nude or blush, catching warm interior light at the mirror',
        'intimate luxury lingerie set — black lace on pale skin in warm interior',
        'balcony bra with garter detail in ivory — full intimate dressing ritual piece',
        'white satin soft-cup bra and high-waist brief — sleek and intimate in morning glow',
        'pale blush corset-inspired bralette and matching low brief — lace edge at the skin',
      ],
      breakfast: [
        'ivory silk robe at the kitchen window, belt barely tied, morning light behind',
        'pale soft morning wrap in cashmere or cotton, cup in both hands at the window',
        'barely dressed boudoir morning at the window — robe open, coffee in hand',
        'cream satin knee-length robe, loosely tied, at the kitchen counter in morning',
        'linen wrap-robe in pale oat, bare feet on kitchen tile in morning light',
        'oversized white sleep shirt and nothing else at the window with morning coffee',
      ],
      late_morning: [
        'ivory lace set in honest natural light — simple and completely self-possessed',
        'nude silk slip or bralette in natural morning bedroom light',
        'pale blush lace bralette and high-cut brief in clean late-morning window light',
        'sheer ivory bodysuit in natural morning — editorial and intimate simultaneously',
        'white cotton bralette and matching brief in clean window noon light',
        'blush satin two-piece intimate set in natural morning — warm and deliberate',
      ],
      lunch: [
        'ivory silk slip against velvet chaise in warm afternoon — simple and beautiful',
        'blush lace cami and soft short brief on lounge furniture in afternoon warmth',
        'soft pale feminine midday private wear — minimal lace and maximum ease',
        'cream satin shorts and matching cami on the chaise in afternoon amber',
        'white silk robe half-open on the chaise, one leg extended on velvet',
        'sheer slip over bralette and brief on the chaise — layered intimate afternoon',
      ],
      afternoon: [
        'nothing in the bath — rose petals on warm water and steam around bare skin',
        'ivory sheer wrap at the afternoon window after the bath — barely covering anything',
        'blush silk robe on the chaise in afternoon light, loosely open at the front',
        'damp skin with just a towel wrapped low after the bath — still in the warmth',
        'white cotton gauze wrap loosely draped at the afternoon window',
        'nothing on the chaise but a sheer lace robe in afternoon sun, skin visible through',
      ],
      reset: [
        'ivory dressing robe half-tied at vanity, slip visible beneath in warm light',
        'pale silk slip at the lit vanity mirror in warm pre-evening preparation',
        'pre-evening lingerie selection at vanity — high-quality lace piece in warm light',
        'cream satin robe open at the vanity, choosing jewelry in warm mirror glow',
        'sheer ivory robe over bralette and brief at the lit vanity in pre-evening ritual',
        'blush slip and bare feet at the warm vanity mirror — between day and evening',
      ],
      golden_hour: [
        'ivory or blush sheer lace against golden window backlight — translucent in amber',
        'silk against warm amber glow — fabric glowing in the richest light of the day',
        'the most photographic intimate look — white lace in golden-hour window light',
        'barely-there silk slip in warm backlit golden hour — the most cinematic moment',
        'pale satin corset-bralette in golden-hour window light, amber filling the room',
        'sheer bodysuit in amber backlight at the window — completely cinematic and deliberate',
      ],
      dinner: [
        'ivory silk corset or boned intimate piece in warm candlelight — the best evening look',
        'deep cream velvet robe in intimate dinner evening, belted and elegant',
        'lace-and-silk evening intimate styling — pale bralette and matching brief in candle warm',
        'blush satin slip with lace hem in warm candlelight — the most beautiful evening piece',
        'ivory long-line corset with suspender detail in warm candle glow',
        'white silk slip cut on the bias, falling beautifully in candlelit warm intimate evening',
      ],
      evening: [
        'low-cut ivory silk in warm ambient glow — simple, deliberate, and beautiful',
        'intimate evening lingerie in deep warm ambient — pale lace against warm skin',
        'barely-there silk evening in low private warm light — not quite nothing',
        'cream satin bralette and matching brief in low warm evening ambient',
        'sheer lace bodysuit in warm low evening light — deliberate and composed',
        'pale slip barely covering in warm low ambient — the boudoir evening at full depth',
      ],
      night: [
        'ivory silk nightgown or bare skin in final candlelight — the most private night state',
        'nothing but the silk sheets in the deepest private boudoir night moment',
        'soft night intimate luxury — white slip and candlelight and complete private calm',
        'pale silk chemise in single warm candlelight — the most intimate end of day',
        'bare skin with just the silk duvet pulled loosely in warm candlelit night',
        'cream silk nightgown with thin straps in warm final candlelight — simple and complete',
      ],
    },
    details: {
      wake: ['undone morning hair loose on silk pillow', 'bare skin in early pale light', 'perfume bottle catching first light on bedside', 'silk duvet edge close to bare shoulder', 'morning hair spread across ivory pillow', 'barely visible gold earring left on overnight'],
      morning_refresh: ['damp skin after shower in warm morning light', 'hair pinned loosely after bathing', 'minimal bare skin in bathroom light and steam', 'skincare bottle close-up on marble surface', 'wet hair ends on silk robe collar', 'single drop of serum on fingertip at vanity'],
      getting_dressed: ['pearl or gold jewelry placed slowly on bare warm skin', 'slow deliberate hands on lace detail at the mirror', 'perfume applied to throat or wrist in morning ritual', 'lace bralette strap being adjusted with both hands', 'silk slip falling over bare shoulder in soft light', 'cool gold chain against warm bare chest'],
      breakfast: ['coffee cup against silk robe in morning window light', 'rose petal on kitchen counter beside the cup', 'morning hair loose in warm window light', 'steam from cup catching window light', 'bare feet on kitchen tile in morning', 'silk robe sleeve near the countertop detail'],
      late_morning: ['honest bare-face or minimal makeup in natural light — clean and powerful', 'gold detail catching natural window light', 'soft deliberate posture at the mirror — self-possessed', 'hair loose or loosely pinned at the mirror', 'lace casting delicate shadow on skin in noon light', 'mirror edge close detail — reflection just visible beside subject'],
      lunch: ['hair down loose on velvet chaise in afternoon', 'bare leg on velvet fabric in warm afternoon light', 'silk against skin on afternoon lounge furniture', 'glass of wine or water near the chaise edge', 'silk slip hem above bare knee in afternoon', 'hair spread on chaise cushion in warm ambient'],
      afternoon: ['rose petals on bathwater surface in warm candlelight', 'steam and damp skin in candlelight after bath', 'wet hair after bath in warm interior light', 'candle wax pooled at bath rim in warm glow', 'bare arm resting on bath edge among petals', 'candlelight reflected in still bathwater surface'],
      reset: ['perfume applied at the vanity — wrist and throat in warm mirror light', 'jewelry placed slowly in vanity light', 'hair pinned or finished at lit mirror before evening', 'lipstick on vanity surface near the mirror', 'jewelry box open with pieces selected on velvet', 'warm vanity bulb halo catching loose strand of hair'],
      golden_hour: ['golden light catching lace or pearl detail on skin', 'hair loose in amber backlight at the window', 'jewelry glowing warm gold in golden-hour window light', 'sheer curtain edge glowing in golden backlight', 'silk fabric catching amber glow in the richest detail', 'warm amber rim on bare shoulder and collarbone in window light'],
      dinner: ['candle-lit jewelry detail catching warm orange', 'deep lace or silk against warm candleflame edge', 'perfume and intimate styling in warm candlelit evening', 'champagne glass catching candle glow', 'single candle flame beside a gold earring detail', 'silk hem in warm orange pool at the chaise edge'],
      evening: ['hair loose in low warm ambient boudoir evening', 'bare skin in warm evening ambient glow', 'silk and skin in intimate low warm light', 'warm lamp catching a single earring in low glow', 'bare shoulder in warm low evening light', 'hair slightly undone in warm low intimate evening'],
      night: ['final perfume or candle detail at the close of the day', 'hair down in night private calm — the most natural', 'silk against skin in warm candlelight — simple and beautiful', 'single candle flame reflected in a perfume bottle surface', 'bare collarbone in final warm candlelight', 'silk sheet edge near the bedside candle in near-dark'],
    },
    changeMoments: {
      wake: ['still in silk nightgown or nothing in sheets — the most private morning state', 'pre-dressing private morning warmth in silk ease'],
      morning_refresh: ['wrapped in a towel or robe after showering — between sleep and dressing', 'between sleep and dressing in warm private bathroom'],
      getting_dressed: ['mid-change in lace in front of the full mirror — private and composed', 'choosing and placing intimate pieces in wardrobe light'],
      breakfast: ['already in morning robe or wrap at the window — dressed for privacy not the world', 'the private morning look at its most honest and warm'],
      late_morning: ['in intimate daywear for the private morning content moment', 'lace set in natural honest light — private and self-possessed'],
      lunch: ['relaxed silk on the chaise — soft afternoon private styling at its most natural', 'barely changed from morning in warm midday ease on the chaise'],
      afternoon: ['undressed for the bath or post-bath in a robe or nothing at all', 'between afternoon and evening — damp skin and warm light'],
      reset: ['between afternoon and evening at the vanity — refining and elevating the look', 'choosing the evening intimate look at the vanity with deliberate care'],
      golden_hour: ['golden-hour intimate styling at its most photographic and cinematic', 'wearing the elevated intimate look in amber light at the window'],
      dinner: ['fully in the intimate evening look — silk, lace, and candle warmth', 'candlelit boudoir intimate styling at its most beautiful and complete'],
      evening: ['low-light intimate evening styling in warm ambient glow', 'deep private intimate evening wardrobe in warm low depth'],
      night: ['final private night styling — silk or nothing in warm candlelight', 'the most private and intimate end-of-night boudoir state'],
    },
  },

  sensoryPools: {
    wake: ['silk against bare skin in warm morning quiet', 'the scent of perfume in the still morning room', 'soft warm light and total privacy'],
    morning_refresh: ['warm water on skin in a private bathroom', 'perfume applied after shower — the ritual warmth', 'clean bare skin and morning light on the mirror'],
    getting_dressed: ['lace fabric against warm skin', 'cool gold jewelry placed on bare skin', 'the slow pleasure of intimate dressing in private'],
    breakfast: ['warm coffee in a silk-robe morning', 'light coming through sheer curtains on the face', 'rose scent and morning warmth'],
    late_morning: ['honest morning light on bare skin at the mirror', 'silk fabric and natural light together', 'the warm private intimacy of a natural boudoir morning'],
    lunch: ['velvet chaise against bare skin in warm afternoon', 'silk slip in afternoon indoor light', 'private slow afternoon warmth and ease'],
    afternoon: ['rose petal-scented bath water', 'candle warmth in a private steamy room', 'the deep pleasure of a long private bath'],
    reset: ['perfume being applied at the warm vanity', 'cool jewelry touching warm skin', 'lit vanity warmth and the ritual of preparation'],
    golden_hour: ['golden window light on silk and skin', 'warm amber air as the afternoon light changes', 'the most beautiful light in the boudoir world'],
    dinner: ['candle warmth in a private intimate room', 'silk fabric in warm flickering light', 'intimate darkness and warm candle air'],
    evening: ['low warm glow on skin and fabric', 'private intimate air in a dark warm room', 'the slow sensory warmth of a boudoir evening'],
    night: ['candlelight in total private darkness', 'silk sheets and warm candleflame scent', 'the deepest private boudoir warmth at night'],
  },

  socialEnergyPools: {
    wake: ['entirely private — no external presence, no performance', 'the most personal unwatched moment of the boudoir day'],
    morning_refresh: ['completely personal self-care, no outside eye', 'private ritual energy in warm intimate space'],
    getting_dressed: ['private transformation ritual — intimate and intentional', 'self-directed without audience in the wardrobe'],
    breakfast: ['private morning ease — silk and coffee and no one watching', 'soft private breakfast before any performance begins'],
    late_morning: ['first private intimate content energy of the day', 'honest self-study in natural light'],
    lunch: ['private lounge ease — intimate and unperforming', 'warm midday private boudoir rest'],
    afternoon: ['deeply private bath ritual — no performance, only sensation', 'slow intimate private afternoon'],
    reset: ['private preparation ritual at the vanity', 'controlled personal refinement before the evening'],
    golden_hour: ['the boudoir creator in full golden-hour photographic presence', 'slightly more visible — golden-hour is for the camera'],
    dinner: ['intimate candlelit warmth — controlled audience connection', 'slow deliberate intimate evening energy for the viewer'],
    evening: ['deepening intimacy — the boudoir evening begins its private escalation', 'warm low-light intimate presence'],
    night: ['the most intimate private moment of the boudoir day', 'final private warm boudoir night'],
  },

  atmospherePools: {
    wake: ['total private morning silence in a warm silk room', 'the boudoir at its most peaceful and unwatched', 'soft pale light and complete intimacy'],
    morning_refresh: ['private bathroom warm ritual atmosphere', 'steam, light, and self-care calm', 'the most personal intimate room at morning'],
    getting_dressed: ['warm wardrobe intimacy — the private dressing ritual', 'quiet selection and transformation energy'],
    breakfast: ['morning window light and coffee and silk — the best private morning atmosphere', 'gentle boudoir morning before the world'],
    late_morning: ['honest natural-light intimate atmosphere', 'boudoir in clean honest morning energy'],
    lunch: ['warm private afternoon indulgence on soft furniture', 'slow intimate midday boudoir ease'],
    afternoon: ['deep candlelit bath ritual atmosphere', 'the most private sensory intimate afternoon energy'],
    reset: ['warm vanity refinement atmosphere — deliberate and controlled', 'private preparation energy in warm indoor glow'],
    golden_hour: ['the golden-hour boudoir — the most cinematic private intimate moment', 'amber light and silk and total feminine presence'],
    dinner: ['candlelit intimate private evening atmosphere', 'warm boudoir dinner-hour private energy'],
    evening: ['deep warm intimate evening — the boudoir at its most deliberately intimate', 'low ambient warm private ease'],
    night: ['the deepest private boudoir night atmosphere — candle, silk, and total calm', 'complete private warm feminine power'],
  },

  propPools: {
    wake: ['silk pillows and white linen', 'perfume bottle on bedside table', 'sheer curtain barely moving in morning light'],
    morning_refresh: ['beauty products on vanity', 'white towel on hook or chair', 'candle beside bathroom mirror'],
    getting_dressed: ['lace bralette laid on wardrobe shelf', 'pearl or gold jewelry on the dressing table', 'silk robe on chair near mirror'],
    breakfast: ['coffee cup and rose on kitchen counter', 'white morning window light', 'sheer curtain framing the window'],
    late_morning: ['full-length mirror', 'silk sheets in natural light', 'scattered lace detail near the bed'],
    lunch: ['silk cushion on velvet chaise', 'afternoon glass of water or wine on lounge table', 'sheer fabric draped on chaise'],
    afternoon: ['rose petals on bath water surface', 'candles at bath edge', 'glass of wine or champagne near the bath'],
    reset: ['perfume bottle at lit vanity', 'jewelry box open on vanity table', 'lipstick and mirror detail at vanity'],
    golden_hour: ['sheer curtain in full amber window light', 'golden jewelry catching warm light', 'single rose in warm window glow'],
    dinner: ['candle as sole light source', 'champagne glass in candlelight', 'lace fabric against warm candle glow'],
    evening: ['ambient candle or lamp on side table', 'silk fabric in low warm light', 'perfume visible on bedside in low ambient'],
    night: ['single candle burning in darkness', 'silk sheets in warm candle glow', 'perfume and jewelry in quiet candlelit detail'],
  },

  bodyLanguagePools: {
    wake: ['soft reclined posture in silk sheets', 'half-awake slow stretch with relaxed limbs', 'rested private posture toward morning light'],
    morning_refresh: ['calm upright posture at vanity mirror', 'relaxed post-shower wrap posture', 'gentle self-care stance in private morning'],
    getting_dressed: ['deliberate slow movement while dressing', 'one-arm lift fastening jewelry', 'composed mirror assessment posture'],
    breakfast: ['relaxed robe posture at kitchen window', 'standing at window with cup — easy private stance', 'unhurried morning kitchen body language'],
    late_morning: ['composed self-study posture at full mirror', 'relaxed seated or standing morning intimate presence', 'easy natural body language in private space'],
    lunch: ['reclining chaise posture — fully private and at ease', 'slow comfortable afternoon body language', 'soft lounging intimate body ease'],
    afternoon: ['submerged bath posture — private sensory ease', 'reclining chaise afternoon body language', 'slow deliberate stretch in warm afternoon light'],
    reset: ['upright deliberate vanity posture', 'slow jewelry placement — hands and neck focused', 'composed pre-evening mirror assessment'],
    golden_hour: ['slow turn in golden window light', 'cinematic still posture in amber warmth', 'soft elevated body language in best light of the day'],
    dinner: ['slow deliberate candle-lit posture', 'reclining on chaise in candlelight with controlled ease', 'intimate seated body language in warm evening'],
    evening: ['soft reclining intimate evening body language', 'low slow movement in private intimate warm light', 'private composed feminine ease in warm glow'],
    night: ['fully reclined private bedside posture', 'slow intimate body language in candlelight', 'the most private still posture of the boudoir day'],
  },

  facialExpressionPools: {
    wake: ['just-awake softness — bare and private', 'rested morning gaze toward the light', 'slow waking private expression'],
    morning_refresh: ['focused self-study expression at the mirror', 'fresh bare-face morning calm', 'composed post-shower intimate expression'],
    getting_dressed: ['soft confident dressing-room gaze', 'deliberate self-aware mirror expression', 'light intimate composure while dressing'],
    breakfast: ['peaceful window-morning private expression', 'soft contentment with coffee in hand', 'unhurried warm morning ease on the face'],
    late_morning: ['honest natural-light expression — no performance', 'soft confident boudoir self-awareness', 'warm private morning self-study expression'],
    lunch: ['relaxed private afternoon expression', 'soft reclining boudoir ease', 'warm midday private feminine calm'],
    afternoon: ['eyes closed or half-open in bath sensory pleasure', 'slow private bath expression', 'deep sensory afternoon facial ease'],
    reset: ['deliberate focused vanity mirror expression', 'pre-evening composure building on the face', 'calm controlled preparation expression'],
    golden_hour: ['the most beautiful face of the day — in perfect golden light', 'soft warm cinematic expression in amber', 'quiet intimate magnetism in golden-hour glow'],
    dinner: ['warm candlelit intimate expression', 'slow deliberate evening eye contact', 'intimate private warm evening facial composure'],
    evening: ['deep private warm intimate expression', 'slow low-light boudoir evening gaze', 'soft intimate private evening calm'],
    night: ['the most private intimate night expression', 'warm eyes in candlelight — fully private', 'deep intimate nighttime stillness in the face'],
  },

  handDetailPools: {
    wake: ['hand resting on silk pillow edge', 'fingers lightly touching the linen beside', 'one hand near perfume bottle on bedside'],
    morning_refresh: ['hand on bathroom counter edge', 'fingers touching face in morning skincare', 'hand holding brush or product at vanity'],
    getting_dressed: ['fingers adjusting lace bralette strap', 'hand fastening jewelry at throat or wrist', 'fingers trailing over wardrobe fabric while selecting'],
    breakfast: ['hand around morning coffee cup', 'fingers touching the stem of the rose on the counter', 'resting hand on kitchen window ledge'],
    late_morning: ['hand touching mirror edge during self-study', 'fingers adjusting fabric or strap in mirror', 'one hand resting on hip at mirror'],
    lunch: ['hand trailing over velvet chaise fabric', 'fingers resting loosely on the lounge surface', 'hand near a glass of water or wine'],
    afternoon: ['hand resting on bath edge with rose petals', 'fingers in water with rose petals around', 'hand on the bath rim in candlelight'],
    reset: ['fingers holding perfume bottle at vanity', 'hand placing jewelry on at the lit mirror', 'fingertips applying lipstick or product'],
    golden_hour: ['hand holding sheer curtain edge in golden light', 'fingers trailing across silk in amber window glow', 'one hand touching jewelry in warm backlight'],
    dinner: ['hand near champagne glass in candlelight', 'fingers touching lace fabric in warm evening', 'slow hand placement on chaise or bed edge'],
    evening: ['hand resting against soft intimate surface in warm ambient', 'fingers touching fabric or skin in low evening light', 'deliberate slow hand movement in warm intimate glow'],
    night: ['hand near the candle in night darkness', 'fingers on silk sheet edge in candlelight', 'one hand resting near the face in deep intimate night warmth'],
  },

  movementEnergyPools: {
    wake: ['slow', 'private', 'waking'],
    morning_refresh: ['ritual', 'deliberate', 'intimate'],
    getting_dressed: ['slow', 'intentional', 'precise'],
    breakfast: ['unhurried', 'private', 'warm'],
    late_morning: ['composed', 'self-aware', 'intimate'],
    lunch: ['reclining', 'slow', 'private'],
    afternoon: ['sensory', 'still', 'warm'],
    reset: ['deliberate', 'composed', 'refining'],
    golden_hour: ['cinematic', 'slow', 'golden'],
    dinner: ['intimate', 'controlled', 'warm'],
    evening: ['slow', 'private', 'deliberate'],
    night: ['minimal', 'intimate', 'still'],
  },

  transitionPools: {
    human: {
      wake: ['waking slowly in the private boudoir morning', 'coming into the silk-soft first light'],
      morning_refresh: ['moving into the bathroom ritual', 'beginning the private morning self-care'],
      getting_dressed: ['choosing the intimate look of the day', 'the private dressing ritual begins'],
      breakfast: ['moving to the kitchen in a silk robe', 'the quiet morning coffee ritual'],
      late_morning: ['the natural light boudoir moment', 'honest private intimate morning presence'],
      lunch: ['settling into afternoon private ease', 'the slow midday boudoir rest'],
      afternoon: ['moving into the bath ritual', 'the private afternoon sensory moment'],
      reset: ['the vanity ritual reset before evening', 'refining for the intimate evening ahead'],
      golden_hour: ['the golden light boudoir moment — the most cinematic', 'amber window light on silk and skin'],
      dinner: ['candles lit, evening intimate energy begins', 'the warm boudoir evening moment'],
      evening: ['the intimate boudoir evening deepens', 'low light and warm private presence'],
      night: ['the final private boudoir candlelit night', 'the deepest warm intimate close of the day'],
    },
  },

  narrativeIntentPools: {
    wake: ['the private unwatched beginning of the most intimate day', 'silk and quiet before the world'],
    morning_refresh: ['turning sleep into feminine ritual through private self-care', 'the private morning that creates the day'],
    getting_dressed: ['choosing the intimate identity of the day in private warmth', 'the dressing ritual as the first act of self-possession'],
    breakfast: ['private morning ease before the boudoir world opens', 'silk and coffee and no performance required'],
    late_morning: ['honest intimate presence in natural morning light', 'the boudoir in its most truthful daytime form'],
    lunch: ['slow private feminine indulgence in warm afternoon light', 'the boudoir afternoon as pure private pleasure'],
    afternoon: ['deep sensory private ritual in candlelit warmth', 'the bath as the most intimate act of self-care'],
    reset: ['deliberate preparation for the evening escalation', 'the vanity as the threshold between day and night'],
    golden_hour: ['the most cinematic moment of the boudoir world — gold light on intimate beauty', 'amber warmth turning private luxury into art'],
    dinner: ['intimate controlled warm evening energy — the boudoir at dusk', 'candle and silk and deliberate intimate presence'],
    evening: ['the boudoir deepening into its most intimate evening form', 'warm low light and completely private feminine power'],
    night: ['the final intimate private night — the boudoir world complete', 'candle, silk, and total feminine calm'],
  },

  fallbackRules: {
    pacingProfile: { wake: 'slow', morning_refresh: 'slow', getting_dressed: 'slow', breakfast: 'slow', late_morning: 'slow', lunch: 'slow', afternoon: 'slow', reset: 'slow', golden_hour: 'slow', dinner: 'slow', evening: 'slow', night: 'slow' },
    repetitionBreakers: { avoidBackToBackSameLocation: true, avoidBackToBackSameLightingStyle: true, encourageWardrobeEvolution: true },
    worldDefaults: { allowSceneGroupFallbackToPhasePools: true, allowSubLocationFallbackToWorldPools: true, preferSceneGroupsWhenPresent: true },
  },

  exclusions: {
    premium: ['clinical or harsh lighting', 'gym or athletic settings', 'outdoor public spaces', 'busy backgrounds'],
    hard: ['daylight outdoor scenes', 'group social settings', 'office or corporate environments', 'cold or blue-toned lighting'],
  },

  routeRules: {
    worldIdentity: ['the boudoir world must feel deeply private, warm, intimate, and feminine — never performative or cold', 'silk, lace, candlelight, and mirrors are the core visual language'],
    humanFlow: ['the day moves from private morning waking through self-care ritual into afternoon sensory pleasure and evening escalating intimate warmth', 'every phase should feel like an invitation deeper into privacy'],
    styling: ['intimate apparel only — silk, lace, satin, robes, nightgowns, nothing public or athletic', 'jewelry and perfume are signature accessories'],
    atmosphere: ['candlelight, warm interior lamps, and golden-hour window light only — never harsh or cold', 'the boudoir is always warm, private, and beautiful'],
  },
}
