export const STORY_WORLD_DARK_SIREN = {
  id: 'dark-siren',
  name: 'Dark Siren',
  description:
    'Sea witch meets femme fatale. Dark ocean energy, wet skin, moody coastlines, mythic seduction. Where the water is black, the mist is permanent, and she is the most dangerous thing in the frame.',

  geography: { country: 'mythic coastline', region: 'dark siren shore' },

  identity: {
    archetype: 'dark siren',
    vibe: ['wet hair on dark rocks', 'ocean mist and black water', 'mythic feminine danger', 'the sea as power source', 'femme fatale in her element'],
    tone: ['dark', 'magnetic', 'mythic', 'moody', 'stormy', 'seductive', 'cinematic'],
    persona: ['the ocean answers to her', 'dangerous beauty that does not perform — it commands', 'at home where the land ends and the dark water begins', 'the camera is the last thing she allows to see her'],
  },

  phaseOrder: ['wake', 'morning_refresh', 'getting_dressed', 'breakfast', 'late_morning', 'lunch', 'afternoon', 'reset', 'golden_hour', 'dinner', 'evening', 'night'],

  phases: {
    wake:            { label: 'Dawn Shore',        timeWindows: ['pre-dawn coastal mist', 'dark ocean first light'],                    pacing: 'slow',   subLocations: ['sea-cave', 'dark-shoreline'] },
    morning_refresh: { label: 'Tide Ritual',        timeWindows: ['early morning tidal light', 'mist on dark water morning'],             pacing: 'slow',   subLocations: ['tide-pool', 'sea-cave'] },
    getting_dressed: { label: 'Siren Preparation',  timeWindows: ['cool coastal morning', 'mist-lit rocky shore'],                       pacing: 'slow',   subLocations: ['sea-cliff', 'dark-shoreline'] },
    breakfast:       { label: 'Shore Solitude',     timeWindows: ['quiet coastal morning light', 'low ocean horizon morning'],            pacing: 'slow',   subLocations: ['coastal-rocks', 'dark-shoreline'] },
    late_morning:    { label: 'Coastal Power',      timeWindows: ['mid-morning overcast coastal', 'moody late morning shore'],            pacing: 'medium', subLocations: ['sea-cliff', 'coastal-rocks'] },
    lunch:           { label: 'Deep Tide',          timeWindows: ['overcast coastal midday', 'storm-light noon on water'],               pacing: 'medium', subLocations: ['coastal-rocks', 'tide-pool'] },
    afternoon:       { label: 'Storm Energy',       timeWindows: ['stormy afternoon coastal', 'dramatic cliff afternoon'],                pacing: 'medium', subLocations: ['sea-cliff', 'dark-shoreline'] },
    reset:           { label: 'Siren Dusk',         timeWindows: ['dusk light on dark water', 'pre-evening coastal storm'],              pacing: 'slow',   subLocations: ['sea-cave', 'coastal-rocks'] },
    golden_hour:     { label: 'Dark Gold',          timeWindows: ['golden hour through storm clouds', 'amber breaking through coastal mist'], pacing: 'slow', subLocations: ['sea-cliff', 'dark-shoreline', 'coastal-rocks'] },
    dinner:          { label: 'Night Tide',         timeWindows: ['night coastal darkness', 'moonlit black ocean'],                      pacing: 'slow',   subLocations: ['dark-shoreline', 'sea-cave'] },
    evening:         { label: 'Siren Night',        timeWindows: ['moonlit ocean evening', 'coastal night energy'],                      pacing: 'slow',   subLocations: ['sea-cave', 'coastal-rocks'] },
    night:           { label: 'Black Water',        timeWindows: ['full night on dark ocean', 'bioluminescent tide'],                    pacing: 'slow',   subLocations: ['dark-shoreline', 'sea-cave'] },
  },

  locations: [
    'dark volcanic rock shore at pre-dawn', 'sea cave with tidal pool and dramatic opening',
    'cliff edge above crashing ocean in storm light', 'dark sand beach in coastal mist',
    'tide pool at low water with wet rock reflections', 'rocky coastal outcrop in low cloud',
    'black water shoreline under full moon', 'coastal cave mouth with ocean light entering',
  ],

  subLocations: {
    'sea-cave': {
      id: 'sea-cave', name: 'Sea Cave', mapAnchor: 'tidal sea cave interior',
      category: 'dark-sanctuary',
      bestPhases: ['wake', 'morning_refresh', 'reset', 'evening', 'night'],
      overlays: ['cave walls wet with tide', 'dramatic opening to ocean beyond', 'ocean echo and mist', 'tidal pool on cave floor'],
      locations: ['interior of sea cave with ocean entrance', 'cave tidal pool with reflective dark water', 'rocky cave arch framing ocean beyond'],
    },
    'dark-shoreline': {
      id: 'dark-shoreline', name: 'Dark Shoreline', mapAnchor: 'black sand ocean edge',
      category: 'ocean-edge',
      bestPhases: ['wake', 'getting_dressed', 'dinner', 'night'],
      overlays: ['dark wet sand', 'ocean mist close on water', 'dark horizon line', 'receding tidal foam'],
      locations: ['dark sand beach at waterline', 'wet shoreline with ocean receding behind', 'black volcanic sand with dark water edge'],
    },
    'coastal-rocks': {
      id: 'coastal-rocks', name: 'Coastal Rocks', mapAnchor: 'rocky coastal outcrop',
      category: 'dramatic-terrain',
      bestPhases: ['breakfast', 'late_morning', 'lunch', 'golden_hour'],
      overlays: ['barnacle-covered rock formations', 'ocean spray mist around base', 'dramatic rock silhouette', 'wet rock texture catching light'],
      locations: ['rocky ocean outcrop in mist', 'barnacle rocks with ocean crashing behind', 'coastal rock formation against dark water horizon'],
    },
    'tide-pool': {
      id: 'tide-pool', name: 'Tide Pool', mapAnchor: 'natural tidal rock pool',
      category: 'reflective-surface',
      bestPhases: ['morning_refresh', 'lunch'],
      overlays: ['still dark water reflecting sky', 'sea anemone and kelp visible', 'low rock walls around pool', 'shallow water movement'],
      locations: ['tidal rock pool with calm reflective dark water', 'low-edge tide pool with coastal rock surround'],
    },
    'sea-cliff': {
      id: 'sea-cliff', name: 'Sea Cliff', mapAnchor: 'cliff edge above ocean',
      category: 'elevated-drama',
      bestPhases: ['getting_dressed', 'late_morning', 'afternoon', 'golden_hour'],
      overlays: ['dramatic cliff drop to crashing ocean below', 'coastal wind and mist', 'ocean horizon at cliff level', 'wild coastal vegetation at edge'],
      locations: ['cliff edge with ocean far below', 'cliff-top above crashing shore in mist', 'dramatic coastal cliff with stormy horizon'],
    },
  },

  sceneVariants: {
    wake:            ['emerging from a sea cave at pre-dawn as the first pale light breaks on dark water', 'lying on dark wet rock at the tide line as morning mist begins to lift'],
    morning_refresh: ['standing in a tidal pool in early morning — water at ankles, mist around', 'emerging from the ocean in dawn light, water running off bare skin and dark hair'],
    getting_dressed: ['on the cliff edge at coastal morning in wet silk — wind moving the fabric', 'standing on dark rocks getting dressed with ocean behind in mist'],
    breakfast:       ['sitting alone on coastal rocks in the morning with ocean stretching behind', 'on dark shoreline in early quiet coastal morning with coffee steam in cold air'],
    late_morning:    ['striding across coastal rocks in the moody late morning light', 'standing on a rocky outcrop in overcast coastal light with mist behind'],
    lunch:           ['seated on coastal rocks at the tide pool in dramatic overcast noon light', 'standing at the water edge at midday with storm clouds rolling in behind'],
    afternoon:       ['on the cliff edge in full storm afternoon energy — wind and ocean below', 'dark shoreline in dramatic afternoon storm light with rain on the horizon'],
    reset:           ['in the sea cave at dusk, tidal pool at feet, cave opening glowing with last light', 'sitting on dark coastal rocks at pre-evening, ocean settling into darkness'],
    golden_hour:     ['on the cliff edge as amber light breaks through storm clouds over the ocean', 'dark shoreline in rare golden coastal light, sea mist catching the amber'],
    dinner:          ['dark shoreline at night, moonlight on black water, tidal foam at feet', 'entering the sea cave by moonlight with ocean phosphorescence behind'],
    evening:         ['on coastal rocks in full moonlight with dark ocean beyond', 'in the sea cave at evening — moonlight entering through the cave mouth'],
    night:           ['standing at the black water line at full night, bioluminescent foam at feet', 'in the sea cave in near-total dark with distant ocean light entering'],
  },

  actionPools: {
    wake:            ['rising slowly from dark wet rock as the first coastal light breaks', 'standing still at the tide line as dawn mist begins to move around', 'turning from the cave interior toward the pale ocean entrance at pre-dawn', 'running one hand through dark wet hair in the first pale coastal light', 'emerging from the sea cave interior as morning barely begins over the horizon', 'looking out from a low coastal rock as the dark ocean surface catches first light'],
    morning_refresh: ['standing in the tidal pool — water still, ankles deep in dark cool water', 'slowly running both hands through drenched hair after emerging from the water', 'pressing both palms flat on a wet rock surface in tidal morning light', 'lifting face toward the pale morning sky from inside the sea cave', 'stepping slowly through very shallow ocean water in early morning', 'crouching at the tide pool edge, fingers tracing the dark water surface'],
    getting_dressed: ['pulling dark wet silk over bare skin on the cliff edge in coastal morning', 'adjusting sheer dark fabric against skin with ocean wind moving it from behind', 'fastening a dark chain at the throat while standing on wet rock with ocean behind', 'slowly pulling damp hair over one shoulder while standing on the cliff above the water', 'tying a dark silk wrap around the waist with one hand while the wind catches the end', 'holding a dark lace garment against bare skin, assessing it against the grey ocean light'],
    breakfast:       ['sitting on a flat coastal rock with hands wrapped around a dark ceramic cup', 'standing on dark shore with coffee, facing the ocean in the cold coastal morning', 'perching on a rock at the ocean edge in the quiet coastal morning solitude', 'pressing the warm cup to the throat while looking out over the dark horizon', 'crouching on dark sand with a cup, ocean foam inches from bare feet', 'sitting with one knee up on a flat rock at tide line, looking into the dark water'],
    late_morning:    ['walking slowly across coastal rocks in overcast light, water below and around', 'standing with arms at sides on a rock outcrop in the moody late morning', 'looking down into the ocean from a rock edge with the water below in motion', 'turning profile against the overcast coastal horizon, wind moving the hair and fabric', 'placing one foot on a higher rock and looking out — commanding coastal posture', 'running fingers along the surface of a barnacle rock in late morning overcast light'],
    lunch:           ['seated cross-legged on flat coastal rock in overcast noon, ocean stretching behind', 'standing at the cliff edge at midday with arms slightly lifted and wind from below', 'crouching at the tide pool at midday, looking into the still dark reflective surface', 'standing on a rock in shallow tidal water at noon — completely still in overcast light', 'sitting on a coastal rock with knees to chest, ocean crashing below in dramatic noon', 'looking directly into the overcast noon sky while standing on the exposed rocky shore'],
    afternoon:       ['standing on the cliff edge in full storm afternoon wind — fabric streaming behind', 'facing into the coastal storm wind on the dark shoreline with hair driven across the face', 'raising both arms slightly on the cliff edge as storm energy builds around', 'walking fast along the dark shoreline with storm energy arriving from behind', 'standing at the cliff edge looking down at white ocean foam far below in storm light', 'bracing on a rock with both hands as a wave crashes close in dramatic afternoon storm'],
    reset:           ['sitting in the sea cave entrance at dusk, legs toward the fading ocean light', 'slowly drying hair with a dark cloth at the cave mouth as last light fades', 'standing at the cave entrance looking at the ocean settling into evening darkness', 'applying dark lip colour at the cave wall in dusk coastal light', 'running both hands through damp hair one last time at the cave mouth at dusk', 'sitting at the tide pool edge at pre-evening, looking at the darkening water reflection'],
    golden_hour:     ['standing on the cliff edge as amber breaks through storm cloud over the ocean', 'turning slowly in rare coastal golden light with sea mist catching the amber behind', 'on dark coastal rock with golden-hour amber crossing the dark water far below', 'lifting face to the amber light breaking between storm clouds at the cliff edge', 'on dark shoreline as golden coastal light crosses the wet sand and foam in front', 'standing in the tide pool at golden hour — amber light on dark water around the ankles'],
    dinner:          ['walking the dark shoreline at night with moonlight on the black water ahead', 'standing at the sea cave entrance by moonlight with phosphorescent foam behind', 'submerging both hands in the dark tidal pool surface by moonlight', 'sitting on dark coastal rock at night with the ocean glowing faintly with moonlight', 'looking out from the sea cave at full ocean night — black water, distant light', 'trailing one hand in a tidal pool at night while crouching on dark rock in moonlight'],
    evening:         ['on coastal rocks in full moonlight with ocean extending to the horizon behind', 'standing at the cave mouth in evening with moonlight beginning to cross the water', 'sitting on a rock at the ocean edge in the calm coastal evening with moon rising', 'trailing fingers through the sea cave tidal pool in the even cool of the evening', 'standing on the cliff in the coastal evening, ocean wind steady and the moon rising', 'reclining on a flat coastal rock in moonlight with waves below in gentle motion'],
    night:           ['standing at the absolute black water edge at full night, bioluminescent foam around the feet', 'inside the sea cave in near-total dark with faint ocean phosphorescence entering', 'lying on a flat dark rock at full night with the stars and dark ocean around', 'looking directly at the moon from the cliff edge at full coastal night', 'knee-deep in black night ocean with moonlight on the water surface in all directions', 'crouching at the dark tide pool edge, fingers in water, phosphorescent light faint below'],
  },

  environmentPools: {
    wake:            ['dark volcanic shoreline at pre-dawn with first pale ocean light on wet rock', 'sea cave interior in coastal pre-dawn — black water at the entrance and mist beyond', 'dark coastal rock formation in early light with ocean disappearing into grey horizon', 'wet rock surface at the tide line in pre-dawn, foam just retreating into dark water', 'cave entrance at dawn with the ocean barely visible beyond in pale cold light', 'dark beach at the very first coastal morning with mist sitting on the water surface'],
    morning_refresh: ['tidal pool in early morning — dark reflective water, surrounding rock, mist above', 'sea cave interior in morning light entering from the ocean entrance behind', 'coastal rock tide pool in cool morning light with dark water still and reflective', 'ocean edge at morning with shallow dark water and mist on the horizon', 'tidal zone in cool coastal morning with rock surfaces wet and textured around', 'sea cave mouth in early morning with ocean moving just beyond in soft grey light'],
    getting_dressed: ['cliff edge in coastal morning mist with ocean far below in dark grey', 'dark shoreline in morning with wet rock, dark sand, and grey ocean behind', 'rocky coastal outcrop in cool overcast morning with ocean spray around the base', 'cliff top in morning coastal wind — grey ocean to horizon, sky low and moving', 'dark volcanic rock shore in morning overcast with ocean surface textured by wind', 'coastal rock platform in cool morning light with dark water below and mist around'],
    breakfast:       ['flat coastal rock at the tide line in quiet morning with dark ocean behind', 'dark sand beach in early morning coastal quiet with ocean foam barely moving', 'rock outcrop above gentle morning tide with grey horizon beyond', 'coastal rocky seat in the cold morning with ocean stretching to flat grey horizon', 'dark shoreline in coastal quiet morning with mist still sitting on the water surface', 'tidal zone in the coastal morning before the wind arrives — still and dark and cold'],
    late_morning:    ['rocky coastal outcrop in overcast late morning with ocean below in motion', 'cliff edge in moody overcast coastal light with dark horizon beyond', 'barnacle rocks in late morning coastal overcast with spray and mist around', 'coastal rock formation in dramatic overcast late morning — sky moving behind', 'dark shoreline in late morning overcast — wet sand, dark water, low sky', 'sea cliff in moody late morning with the ocean swell visible far below'],
    lunch:           ['tide pool in overcast noon light with dark water and rock surround', 'coastal rocks at midday with storm clouds building on the ocean horizon', 'rocky shore in storm noon light — dark water, white foam, dramatic grey sky', 'cliff edge at noon with the full storm building over the dark ocean below', 'dark shoreline at noon in dramatic storm light — wet sand reflecting dark sky', 'tidal pools at midday in dramatic overcast — every surface dark and reflective'],
    afternoon:       ['cliff edge in full storm afternoon — ocean foam visible far below, sky driving', 'dark shoreline in afternoon storm — rain on the water horizon, wind from behind', 'sea cliff in coastal storm — dramatic sky, ocean in full motion below', 'rocky shore in afternoon storm energy — white ocean spray catching dark sky above', 'coastal rocks in driving afternoon mist — every surface wet and dramatic', 'cliff top in storm afternoon — wind making fabric and hair horizontal, sky racing'],
    reset:           ['sea cave at dusk — cave mouth in last light, ocean settling into dark beyond', 'coastal rocks at pre-evening with ocean going quiet as light fails', 'sea cave tidal pool at dusk — still water, fading sky in cave opening above', 'dark shoreline at dusk — last pale horizon light on the water surface ahead', 'coastal cave interior in fading coastal dusk with tide barely moving', 'cliff edge at pre-evening — ocean darkening below, last warm light on the horizon'],
    golden_hour:     ['cliff above the ocean as rare amber breaks through coastal storm cloud', 'dark shoreline in golden coastal light — amber catching wet sand and foam', 'sea cliff in golden-hour ocean amber with mist turning gold around the base', 'coastal rocks in rare warm ocean golden hour — dark rock, amber light, black water', 'dark volcanic shore in golden-hour light — amber on the wave faces approaching', 'cliff top at golden hour — amber light crossing the ocean to the darkening horizon'],
    dinner:          ['dark shoreline at night with moonlight on the black water and white foam at feet', 'sea cave by moonlight — cave interior dark, phosphorescent ocean beyond the entrance', 'coastal rocks at night in moonlight — dark rock wet, moon full on the water', 'dark sand beach at full night with moonlight making the ocean surface visible', 'cliff edge at night — black ocean below, moonpath on the water to the horizon', 'sea cave tidal pool at night — still dark water with faint moon reflection inside'],
    evening:         ['coastal rocks in full moonlight with open ocean extending behind in silver', 'sea cave at evening with moon rising over the water just visible through the entrance', 'cliff edge in coastal evening — moon rising, ocean settling, wind quieting slightly', 'dark shoreline in the coastal evening with the tide coming in under moonlight', 'rocky coast at evening with moon path on the water to the horizon ahead', 'sea cave mouth at evening — calm dark water inside, moonlit ocean beyond'],
    night:           ['black water shoreline at full night — bioluminescent foam at the tide edge', 'sea cave in full dark night — phosphorescent ocean barely entering the darkness', 'cliff edge at full coastal night — black ocean below, stars above, moon high', 'dark sand beach at absolute night — only the moonlight on the water and the sound', 'tidal pool at full night — still black water with faint star reflection and phosphorescence', 'coastal rocks at full night in moonlight — wet dark surface, ocean breathing around'],
  },

  moodPools: {
    wake:            ['dark mythic power in the first pale coastal light', 'the siren rising before the world wakes — ocean and mist and total control', 'pre-dawn coastal silence that belongs entirely to her', 'the dark shore at its most private and most powerful before any light', 'mythic feminine calm in the cold coastal pre-dawn', 'the ocean acknowledging her presence at the edge of night'],
    morning_refresh: ['cold ocean ritual energy — water and skin and total power', 'tidal pool morning communion — she belongs to this world and it knows it', 'coastal morning solitude in the most elemental form', 'the siren at her most primal and most calm in the morning tide', 'dark water morning ritual — private, elemental, magnetic', 'cold coastal morning awakening that has nothing to do with comfort'],
    getting_dressed: ['dark feminine preparation on the cliff edge — dangerous and deliberate', 'the siren dressing for herself in the most dramatic setting on earth', 'coastal morning dressing ritual — fabric and mist and command', 'dark power building through the morning preparation on the rocks', 'deliberate siren preparation in cold mist — everything intentional', 'ocean wind and dark silk and complete femme fatale composure'],
    breakfast:       ['dark coastal morning solitude — she doesn\'t need warmth, she has the ocean', 'rocky shore morning quiet before the siren power builds fully for the day', 'cold coastal peace in the early morning before anyone arrives', 'the shoreline in the morning as her most private possession', 'dark ocean morning ease — cold, beautiful, completely self-contained', 'the siren at rest in the morning before the mythic energy fully rises'],
    late_morning:    ['coastal overcast energy building toward something dramatic', 'moody late morning on the rocks — the siren fully awake and present', 'dark coastal command in the late morning overcast', 'the rocks and the ocean and her in the dramatic late morning light', 'dark magnetic presence in moody late morning coastal energy', 'the feeling of a storm building in the late morning air on the shore'],
    lunch:           ['storm energy arriving at noon — she called it, it came', 'dark dramatic midday coastal power at full force', 'the ocean in its most dramatic form at noon — and she in the middle of it', 'storm-light noon on dark water — the most cinematic siren moment', 'powerful feminine darkness in the dramatic coastal noon light', 'the tide at its most dramatic and she completely at home in it'],
    afternoon:       ['full storm siren energy on the cliff — the most powerful the world looks', 'dark coastal storm afternoon — everything dramatic, everything her element', 'the siren in the storm as the most natural thing in the frame', 'cliff-edge storm afternoon power — hair driven, fabric streaming, completely commanding', 'the storm as her most natural setting — wild, dark, magnificent', 'afternoon coastal storm energy that amplifies her magnetism'],
    reset:           ['the siren at dusk preparing for the deepest part of the day', 'dark coastal dusk settling around her at the cave mouth', 'pre-evening coastal calm — the storm passing, the dark arriving', 'the cave at dusk as the most private siren sanctuary', 'dusk coastal energy returning to something deep and private', 'the siren between storm and night — powerful, contained, waiting'],
    golden_hour:     ['rare amber breaking through storm clouds at the cliff — the most beautiful siren moment', 'coastal golden light through mist — dark and golden and completely magnetic', 'the ocean in amber at golden hour — even the dark is beautiful in this light', 'golden-hour coastal drama — the brief warm in the dark', 'storm clouds and amber light on black water — the most cinematic coastal moment', 'the siren in the only warm light she accepts — briefly golden, then back to dark'],
    dinner:          ['moonlit ocean night energy — the siren in her full nocturnal power', 'dark coastal night with the moon on black water — mythic and completely her own', 'the sea cave at night as the most complete siren sanctuary', 'moonlit shoreline power — the ocean at night and she commanding it', 'nocturnal coastal magnetism at its full dark depth', 'the siren at dinner hour on the dark shore — the most dangerous time of day'],
    evening:         ['full moonlit coastal evening — her power at its peak', 'the ocean at night acknowledging her presence on the rocks', 'dark siren evening on the coastal rocks in full moonlight', 'mythic nocturnal feminine presence in full coastal moonlight', 'the siren evening as the apex of her dark energy', 'coastal night energy fully belonging to her'],
    night:           ['bioluminescent ocean at full night — the most mythic siren moment of all', 'absolute dark coastal night with only the phosphorescent ocean as witness', 'the black water at full night and the siren completely in her element', 'the most mythic and the most private siren moment — full night, ocean glow', 'dark coastal night power at its absolute depth — no light needed', 'the siren at full night on the dark ocean — the world as it should be'],
  },

  cameraPools: {
    wake:            ['24mm wide from low rock position, dark ocean opening behind at pre-dawn', '85mm close from cave interior, ocean entrance in background, pale morning beyond', '135mm tight on face at pre-dawn, dark rock edge in close foreground, mist behind', '50mm mid from waterline level, subject above on rock, pale ocean and sky behind', '35mm dramatic wide at cave mouth, subject small against vast pre-dawn dark ocean', '85mm low angle up from dark sand, subject silhouetted in pale pre-dawn coastal light'],
    morning_refresh: ['50mm from tidal pool rock edge, dark reflective water in foreground, subject beyond', '85mm low from water surface level at tide pool, reflections visible in dark water', '135mm close on wet hair and face in cool coastal morning light at tide pool', '35mm wide sea cave shot, tidal pool visible, ocean entrance in background behind subject', '85mm from behind subject at tidal pool edge, reflection in dark water below', '135mm extreme close on hands at dark water surface in tidal morning light'],
    getting_dressed: ['35mm wide cliff edge with full ocean panorama dropping behind subject', '85mm side angle at cliff edge, ocean below and horizon behind in overcast morning', '135mm close on detail — dark fabric on pale skin against grey ocean background', '50mm dramatic cliff angle, subject in foreground, ocean drop and horizon behind', '24mm ultra-wide cliff top, subject small against vast grey ocean morning', '85mm low cliff angle looking up slightly at subject with overcast sky behind'],
    breakfast:       ['85mm rock seat medium, flat dark ocean horizon compressing behind', '50mm coastal rock scene, ocean behind, dark sand and tidal zone in full frame', '135mm close on face and cup against grey ocean horizon, mist softening distance', '35mm wide shoreline morning, subject and rock and ocean in full dramatic scene', '85mm low from sand level, subject elevated on rock, horizon line at subject height', '135mm tight on hands and cup at rock in morning coastal light'],
    late_morning:    ['85mm from below on barnacle rocks, subject above with overcast sky and ocean', '135mm close in moody overcast light — sky pressure visible above subject', '50mm dramatic coastal angle, rocks in foreground, subject, ocean behind', '35mm wide coastal scene, all elements — rock, water, sky, subject — in full frame', '85mm side cliff angle, moody overcast at full force, ocean below in frame', '24mm ultra-wide late morning coast, subject as single element in vast grey scene'],
    lunch:           ['85mm storm-light rock shot, dark water behind, storm clouds pressing in', '50mm tide pool elevated angle looking down, subject at pool edge, dark water below', '135mm close in storm noon light — dramatic sky pressure felt through framing', '35mm wide storm build shot, subject on rocks, storm front on ocean horizon behind', '85mm low from dark water level, subject on rock above, storm sky behind subject', '24mm dramatic wide storm noon — sky and ocean and rocks and subject all present'],
    afternoon:       ['24mm ultra-wide cliff storm shot, full drama of sea and sky behind subject', '35mm wide cliff edge in full storm, subject bracing, ocean visible below', '85mm close cliff angle in storm, hair driven horizontal, fabric streaming behind', '50mm mid cliff shot in storm afternoon — full force of the environment around subject', '135mm tight face in storm afternoon on cliff, wind and sky visible around edges', '24mm dramatic from below cliff edge, subject above against driving storm sky'],
    reset:           ['85mm sea cave entrance at dusk, cave depth behind subject, ocean fading beyond', '50mm cave mouth at last light, subject inside, ocean going dark in entrance behind', '135mm close in cave dusk light, cave walls in bokeh around, ocean just visible', '35mm wide cave scene at dusk, tidal pool visible, ocean entrance glowing last light', '85mm low cave angle at dusk, subject in mid-cave, darkening ocean in entrance', '135mm tight on face in cave dusk light — the most intimate siren portrait'],
    golden_hour:     ['135mm backlit cliff close, amber rim on subject, dark ocean behind in warm glow', '85mm low cliff angle at golden hour, amber light crossing dark water to horizon', '50mm wide golden cliff scene, rare amber light on full landscape and subject', '35mm ultra-wide golden-hour cliff, amber breaking storm cloud, full coastal panorama', '85mm from below cliff edge, amber sky behind subject at most dramatic golden moment', '135mm extreme backlit close — amber edge, dark face, black ocean beyond'],
    dinner:          ['85mm moonlit shore close, dark wet sand and moon-on-water behind', '135mm night face close, moonlight as single key source, ocean glow behind', '50mm sea cave moonlit mid, cave darkness, phosphorescent ocean in entrance behind', '35mm wide night shore, subject small in moonlit coastal darkness', '85mm low from sand at night, subject above on rock, moonpath on water behind', '135mm extreme close at cave entrance, phosphorescent ocean faintly visible beyond'],
    evening:         ['85mm moonlit coastal rock medium, full moonpath on ocean behind subject', '50mm wide evening coastal scene, moon risen, ocean silver behind in full frame', '135mm close on face in moonlight on coastal rocks, dark ocean in deep background', '35mm dramatic evening coast, moon reflecting on water, subject on rocks in frame', '85mm from below rock, subject above with moonlit ocean panorama behind', '24mm ultra-wide moonlit coast, subject as one element in the full silver scene'],
    night:           ['135mm close in near-dark on shore, bioluminescent foam at feet just visible', '85mm low from dark sand, subject at shoreline, phosphorescent wave behind in dark', '50mm wide night shore, black water, moonlight, subject standing at the absolute edge', '35mm sea cave night shot, phosphorescent ocean at entrance providing only light', '85mm from below cliff at full night, black ocean below, stars and moon behind subject', '24mm ultra-wide full night coastal, subject small, ocean vast and dark and alive'],
  },

  lightingPools: {
    wake:            ['pale 4800K pre-dawn coastal light through ocean mist — flat, cool, diffuse', 'first 5000K coastal dawn light barely defining wet rock and dark water', 'pre-dawn coastal ambient at 4600K — everything cool, dark, and barely visible', 'flat cool grey coastal pre-dawn at 4800K, mist diffusing any direction', 'cave entrance dawn light at 4500K entering softly from the ocean side', 'pre-dawn shoreline at 4700K — dark water, dark rock, pale grey sky barely breaking'],
    morning_refresh: ['cool 5200K coastal morning light on dark tidal pool surface', '5000K flat coastal overcast morning — clean, cool, no shadow direction', 'tidal pool morning at 5400K — reflected cool sky light in dark water', 'sea cave at 5200K with ocean light entering — cool directional from entrance', 'coastal morning at 5000K with mist softening any direct light source', '5200K cool window of morning on wet rock and dark water surface'],
    getting_dressed: ['cool overcast coastal morning at 5000K — even cool fill, no warm at all', 'cliff-edge morning at 4800K with mist diffusing the grey sky light', '5200K coastal overcast on dark rock surface with ocean far below', 'cold coastal morning at 5000K — completely flat, completely cool, dramatic', 'grey overcast cliff morning at 4800K with faint horizon rim from ocean', 'cliff-top morning light at 5200K, overcast sky pressing down, cool and even'],
    breakfast:       ['cool coastal morning rock at 5000K, flat grey light on dark sand and stone', '5200K cool morning on dark rocky shore — honest and cool and dramatic', 'coastal grey morning light at 4800K, flat even, rock and ocean equal in tone', '5000K flat coastal morning — no direction, just even cool coastal light', 'cold rock morning at 5200K — mist making everything equal in exposure', 'grey coastal morning at 5000K, dark water behind, flat northern-coast light'],
    late_morning:    ['overcast 4800K moody coastal noon approaching — drama building in light', '5000K flat heavy overcast coastal — maximum pressure in the sky and tone', 'pre-storm coastal light at 4600K — everything greying, contrast rising', 'heavy overcast 4800K over dark water — most dramatic moody coastal light', 'storm-building coastal at 4500K — flat top light with oceanic atmospheric pressure', 'moody 5000K overcast coastal late morning — the sky about to do something'],
    lunch:           ['storm 4200K light — grey-green cast, dramatic contrast, sky pressing hard', 'overcast storm noon at 4500K — all warmth gone, replaced by dramatic grey-green', '4000K storm-light coastal — the moment before rain arrives on the water', 'dramatic 4200K storm overcast at noon — the most cinematic coastal light', 'storm coastal noon at 4500K — flat aggressive light from all directions', 'full overcast storm 4200K — dark water even darker, sky even lower'],
    afternoon:       ['storm afternoon at 3800K — warm break through storm grey on cliff edge', 'dramatic coastal storm 4000K with rim light breaking from low storm sun', 'cliff storm afternoon at 3800K — side-lit from breaking storm, dramatic', '4000K storm-break side light on cliff — the most dramatic coastal lighting', 'stormy afternoon coastal at 3800K, warm break through dark storm cloud', 'storm afternoon with 3800K golden crack in the grey — rim light on everything wet'],
    reset:           ['dusk coastal 3000K — warm fading light on cave wall and dark water beyond', 'sea cave dusk at 3200K — last warm coastal light entering from the ocean side', 'pre-evening coastal at 3000K — the warmth leaving the dark shore', '3200K dusk cave entrance — warm outside light against dark cave interior', 'coastal dusk at 2800K, warm horizon still glowing through cave entrance', 'dusk rock at 3000K — the brief warm moment before coastal darkness'],
    golden_hour:     ['2600K deep amber breaking through storm cloud on cliff, dramatic and rare', 'warm 2800K ocean golden through storm mist — amber on dark wet surface', '2600K storm-break golden on cliff edge — amber rim light on everything wet', 'golden coastal at 2700K through mist — the dark shore briefly amber', '2800K warm ocean golden cutting through storm grey — dramatic contrast lighting', 'rare cliff golden hour at 2600K — the only warmth in an otherwise dark world'],
    dinner:          ['moonlight at 5600K on dark ocean surface — cool silver on black water', 'coastal night moonlit at 6000K — cool silver light on wet dark surfaces', '5800K full moon on dark shoreline — clean cool silver on rock and sand', 'sea cave moonlight at 5600K entering from ocean entrance — cool and dramatic', 'moonlit coastal at 6000K — high contrast silver and black, no warmth', 'dark shore at night with 5600K moon as only key source — pure silver'],
    evening:         ['full moon 5800K on dark coastal rocks — strong silver key, dark shadows', '6000K full moonpath on ocean — silver primary source, ocean reflecting it back', 'coastal evening moon at 5600K — clean cool silver direction from above', '5800K moonlight on wet rock, phosphorescent ocean beyond, zero warmth', 'full moon coastal evening at 6000K — maximum silver contrast on dark terrain', 'moonlit evening on dark shore at 5600K — dramatic cool directional from above'],
    night:           ['near-dark with bioluminescence as only source — pale blue-green 4800K glow', 'full night dark coastline with moonlight at 6000K and phosphorescence 4500K', 'sea cave at absolute night — phosphorescent ocean light at 4600K barely entering', 'coastal night at full dark — 6000K moon, 4500K bioluminescence, nothing else', 'black water shore at full night — moon and phosphorescence only, both cool', 'near-total night coastal — bioluminescent tide at 4600K as the only light'],
  },

  stylingPools: {
    wardrobe: {
      wake:            ['nothing but dark wet skin and dawn mist on the dark shoreline', 'black silk slip wet from the ocean — clinging and barely covering anything', 'dark green translucent sheer barely covering bare skin in pre-dawn mist', 'draped black fabric barely held — like something the ocean gave back', 'bare skin with dark tide water still on it in the first pale coastal light', 'dark charcoal wrap barely held at the shoulder, open to the ocean dawn'],
      morning_refresh: ['emerging from tidal water in nothing — bare skin in cool coastal morning', 'wet dark silk translucent from the tide — water still running off in morning light', 'barely anything in the sea cave morning — just dark damp fabric against skin', 'black sheer wrap after the tide, water still on bare shoulders and hair', 'dark silk slip worn into the water — wet and dramatic in morning tidal light', 'nothing covering what the tide touched — bare and powerful in cool morning'],
      getting_dressed: ['black draped silk on the cliff edge — one shoulder, storm-ready', 'dark bodysuit with open detail over cliff in coastal morning — powerful and precise', 'black structured corset top with silk skirt moving in the coastal wind', 'dark draped lace over bare skin on the cliff — feminine and completely dangerous', 'ink-dark wrap dress barely tied on rocky shore in coastal morning light', 'black silk set — cropped top and bias-cut skirt catching cliff-edge morning wind'],
      breakfast:       ['black oversized silk shirt in dark shoreline morning — barely buttoned', 'dark satin robe on the coastal rocks in quiet morning — not fully tied', 'black cotton wrap in cold morning coastal ease on the flat rock', 'dark knit worn loose over nothing in the cold coastal rock morning', 'oversized black silk cover at the shoreline — minimal, dark, morning-easy', 'charcoal silk slip with robe open at the coastal morning rock seat'],
      late_morning:    ['black structured bodysuit on the cliff in overcast coastal light', 'dark draped silk with architectural drape on coastal rocks in overcast', 'ink-dark lace set on rocky outcrop in moody late morning', 'black minimal silk two-piece on the coastal rocks — powerful and editorial', 'dark sculptural drape on cliff edge in overcast late morning', 'structured black bodysuit and dark wide-leg silk on rocky coastal ground'],
      lunch:           ['black asymmetric silk at the tide pool in storm noon light', 'dark wet-look bodysuit on coastal rocks in storm noon', 'black editorial set — structured top and dramatic skirt in storm light', 'dark sheer layer over minimal bodysuit at the tide pool in overcast', 'ink black draped look in the full storm noon on the coast', 'dark structured silk ensemble on rocks — storm noon editorial'],
      afternoon:       ['black silk barely covering anything in full storm cliff afternoon', 'dark sheer cape on cliff edge — the storm making it stream horizontal', 'minimal black bodysuit on the cliff in driving coastal storm', 'dark wet silk on the cliff in the storm — the most powerful visual moment', 'black architectural wrap catching full storm cliff wind behind', 'nothing but a dark silk scarf streaming in the cliff storm — deliberate minimalism'],
      reset:           ['black satin slip in sea cave dusk — minimal, dark, perfectly precise', 'dark velvet robe in cave dusk — dramatic and soft and contained', 'black lace in the cave at pre-evening — feminine, dark, controlled', 'dark silk bralette and wide-leg in cave dusk light', 'black bodysuit with open silk drape in sea cave at dusk', 'dark silk wrap at cave mouth at dusk — between worlds and perfectly composed'],
      golden_hour:     ['black sheer in the rare cliff golden light — translucent in amber', 'dark silk in golden coastal light — amber catching every wet surface and dark fabric', 'black lace in amber cliff light — the most beautiful siren has ever looked', 'dark bodysuit in golden-hour cliff light — brief amber warmth on dark skin', 'black silk against golden coastal light — the contrast of the entire world', 'dark architectural drape in amber cliff golden hour — the most cinematic look'],
      dinner:          ['black silk slip by moonlit shoreline — minimal and completely commanding', 'dark sheer barely covering anything at the night ocean edge', 'black bodysuit in moonlit coastal dark — powerful and precise at night', 'dark satin on the moonlit coastal rocks — the siren at night', 'black lace at the cave mouth by moonlight — the most feminine dark aesthetic', 'nothing but dark silk and moonlight at the black water edge'],
      evening:         ['dark silk on coastal rocks in full moonlight — the most beautiful night look', 'black sheer in moonlit coastal evening — translucent silver in the moon', 'dark satin bodysuit on the cliff in coastal evening moonlight', 'black minimal silk in the coastal evening moon — precise and commanding', 'dark lace over bodysuit in full moonlit coastal rocks', 'black silk with architectural detail in coastal moonlight evening'],
      night:           ['bare skin or minimal dark silk at the bioluminescent ocean edge', 'nothing but the night and dark silk at the black water — fully surrendered', 'black sheer at full night — bioluminescent glow visible through fabric', 'minimal dark covering at the black ocean edge at night', 'dark silk in the sea cave at absolute night — barely there', 'nothing on the dark shore at full night — only the ocean and her'],
    },
    details: {
      wake:            ['wet dark hair flat against bare skin in first coastal light', 'ocean water still on bare shoulders in pre-dawn', 'dark nail detail catching first coastal pale light', 'bare feet on wet dark volcanic rock in dawn light', 'dark chain at throat in coastal pre-dawn mist', 'salt water droplets on dark skin in pale first light'],
      morning_refresh: ['completely drenched dark hair in cool tidal morning light', 'water running down bare arms after tidal pool emergence', 'dark liner running slightly from ocean water — intentional', 'wet rock beneath bare feet in cool coastal morning', 'salt film on skin catching cool coastal morning light', 'tidal pool water pooling in collarbone hollow in morning light'],
      getting_dressed: ['dark chain or collar at throat on the cliff edge', 'black nail detail catching grey coastal light', 'dark draped fabric moving in cliff-edge wind', 'single dark cuff on bare wrist on the cliff', 'dark wet hair moving in coastal cliff morning wind', 'black ring detail on hand gripping rock edge on the cliff'],
      breakfast:       ['coffee steam in cold coastal air above a dark ceramic cup', 'dark fingers on dark rock surface in morning', 'bare feet on flat coastal rock at the tide line', 'dark simple nail on hand around the warm cup', 'hair still damp from the ocean in the quiet morning', 'dark lip in the cold coastal morning — minimal and precise'],
      late_morning:    ['hair moved by cliff-edge overcast coastal wind', 'dark precise eye in moody overcast coastal light', 'black nail on hand trailing rock surface in overcast', 'dark chain at collarbone in overcast late morning coastal', 'bare feet on barnacle rock in moody late morning', 'single dark earring catching overcast coastal light'],
      lunch:           ['storm-wet hair in dramatic noon coastal light', 'dark detail catching the dramatic storm-light contrast', 'bare skin in storm noon — rain just beginning on the water', 'dark fabric catching first drops of arriving coastal storm', 'dark lip in the full storm noon dramatic light', 'wet dark hair in the dramatic overcast coastal noon'],
      afternoon:       ['hair driven completely horizontal in cliff storm', 'dark fabric streaming behind in full storm cliff afternoon', 'bare skin in driving coastal storm mist on the cliff', 'dark chain at throat in full storm cliff energy', 'storm-wet dark hair across the face in cliff wind', 'bare feet on cliff edge rock in full storm afternoon'],
      reset:           ['dark lip applied at cave wall in dusk light', 'wet hair drying naturally in sea cave dusk', 'dark jewellery selected in cave dusk light', 'cave wall damp behind bare arm in dusk', 'dark chain at throat in sea cave pre-evening', 'single candle lit at cave mouth at dusk — the siren\'s one concession to warmth'],
      golden_hour:     ['dark skin catching rare amber cliff light', 'dark chain in golden coastal rim light', 'wet dark hair in amber coastal glow on cliff', 'dark nail in golden-hour cliff light detail', 'dark fabric amber-lit at the cliff edge', 'dark lip in rare coastal golden amber light'],
      dinner:          ['moonlight on wet dark hair at the shoreline', 'dark jewellery in moonlit coastal night', 'bare feet in wet shoreline sand at moonlit night', 'dark lip catching moonlight at the ocean edge', 'dark chain at throat in moonlit coastal darkness', 'bioluminescent foam at bare feet in dark coastal night'],
      evening:         ['full moonlight on dark hair on coastal rocks', 'dark jewellery in full coastal moonlight', 'bare feet on wet rock in moonlit coastal evening', 'dark lip in the moonlit coastal evening light', 'moon highlighting dark chain at throat on rocks', 'dark skin in full coastal moonlight — silver and dark'],
      night:           ['bioluminescent glow on bare skin at black water edge', 'nothing but dark hair and black water at full night', 'dark chain visible in near-total coastal night', 'bare feet in bioluminescent foam at full night ocean', 'moonlight on dark nail detail at the ocean edge', 'dark lip in the near-dark of full coastal night'],
    },
    changeMoments: {
      wake:            ['emerging from ocean or darkness — between water and land at dawn', 'the siren arriving on the dark shore in pre-dawn — not yet dressed for the day'],
      morning_refresh: ['between ocean and land in the tidal morning — bare and wet and elemental', 'tidal pool morning — between water and the world, nothing covering'],
      getting_dressed: ['putting on the dark coastal look on the cliff edge — deliberate and dramatic', 'the siren dressing herself in the most powerful location available'],
      breakfast:       ['already in the minimal dark morning cover on the coastal rocks', 'morning siren styling at rest on the dark shore — underdressed for the world, perfect for the ocean'],
      late_morning:    ['in the full coastal dark look in overcast late morning on the rocks', 'cliff-edge presence in the moody late morning — the siren at full capability'],
      lunch:           ['dark editorial coastal look in the storm noon light', 'storm noon siren presence on the rocks — fully dressed for the drama'],
      afternoon:       ['minimal dark in the full cliff storm — the look the wind makes the most dramatic', 'storm cliff afternoon — the siren at her most stripped-back and most powerful'],
      reset:           ['cave dusk transition — between the wild coastal day and the dark night to come', 'in the cave at dusk in dark silk — composed and preparing'],
      golden_hour:     ['dark look in the rare amber cliff light — contrast at its maximum', 'the siren in golden light — brief warmth on something that belongs to the dark'],
      dinner:          ['night siren at the black water edge — dark and minimal and completely herself', 'moonlit coastal night look — precise dark styling in silver moonlight'],
      evening:         ['full moonlit coastal evening look — dark and silver and completely commanding', 'on the coastal rocks in full evening moonlight — the siren at night'],
      night:           ['at the black water edge in the deepest night — the final siren state', 'nothing between the siren and the ocean at full dark — the most powerful state of all'],
    },
  },

  sensoryPools: {
    wake:            ['cold ocean air in pre-dawn darkness', 'wet volcanic rock under bare feet', 'the sound of dark tide pulling back from stone'],
    morning_refresh: ['cold tide pool water on bare skin', 'salt on the lips after tidal emergence', 'the cold clean coastal morning air in the lungs'],
    getting_dressed: ['fabric catching the cliff-edge wind', 'cold rock surface under hands', 'ocean spray mist on bare skin on the cliff'],
    breakfast:       ['warm cup against cold coastal morning hands', 'the cold dark rock beneath bare feet', 'ocean sound filling the rocky coastal morning'],
    late_morning:    ['overcast coastal pressure in the air', 'rough barnacle rock underfoot on the shore', 'mist and cold and ocean surrounding everything'],
    lunch:           ['storm energy arriving in the air pressure', 'first drops of coastal rain on bare skin', 'the sound of the ocean intensifying before the storm'],
    afternoon:       ['full coastal storm wind driving everything', 'rain and ocean spray mixing on the cliff', 'the roar of the sea in full storm beneath the cliff'],
    reset:           ['cave dampness cool against bare skin at dusk', 'tidal pool still water on fingertips at cave', 'the sound of the ocean settling toward evening'],
    golden_hour:     ['rare coastal warmth in the golden amber light', 'amber glow warm on dark wet rock and skin', 'the brief warmth before coastal darkness returns'],
    dinner:          ['moonlight cool and silver on dark ocean surface', 'wet dark sand cool under bare feet at night', 'the sound of the night ocean intimate and close'],
    evening:         ['full moonlight silver and cool on skin', 'wet coastal rock cool under hands in moonlight', 'the calm of the coastal evening after the storm'],
    night:           ['bioluminescent water cold on bare feet in darkness', 'absolute coastal night silence except the ocean', 'the phosphorescent tide barely visible in total dark'],
  },

  socialEnergyPools: {
    wake:            ['completely alone on the dark shore — no witness, only the ocean', 'the pre-dawn coast as total private territory'],
    morning_refresh: ['the tidal pool as private communion with the ocean element', 'completely elemental and alone in the coastal morning'],
    getting_dressed: ['dressing for the ocean not the world — private cliff preparation', 'siren self-preparation with the ocean as only audience'],
    breakfast:       ['solitary on the coastal rocks — the most private morning on earth', 'the dark shore in morning as absolute private possession'],
    late_morning:    ['commanding the rocks alone — no audience needed', 'overcast coastal solitude — complete and powerful'],
    lunch:           ['storm arriving and she is the only thing on the shore', 'noon storm energy all for her — the ocean performing for one'],
    afternoon:       ['the cliff in the storm as total siren command', 'storm afternoon as private dominion over the coastal world'],
    reset:           ['cave sanctuary at dusk — completely private and preparing', 'the sea cave at pre-evening as the most private space on the coast'],
    golden_hour:     ['rare amber light on the cliff — the ocean briefly performing warmth for her alone', 'coastal golden hour as private magnificent moment'],
    dinner:          ['the moonlit night ocean as intimate dark audience', 'night shore as the most private space in the world'],
    evening:         ['the full moon as her light — nobody else invited to this coastal evening', 'coastal moonlit evening as the siren\'s most complete moment'],
    night:           ['absolute darkness and ocean — the most private the world ever gets', 'bioluminescent ocean at full night as sole private witness'],
  },

  atmospherePools: {
    wake:            ['dark volcanic coast at pre-dawn — the whole world dark and cold and hers', 'coastal pre-dawn as the most dramatic private morning possible'],
    morning_refresh: ['cold tidal morning atmosphere — elemental and completely owned', 'tidal pool morning as the most authentic coastal ritual'],
    getting_dressed: ['cliff-edge morning mist and ocean wind and total dramatic possibility', 'coastal morning dressing atmosphere — dark, dramatic, powerful'],
    breakfast:       ['cold coastal rock morning atmosphere — the world still dark, the shore still hers', 'dark shoreline morning as the most beautiful solitude available'],
    late_morning:    ['moody overcast coastal atmosphere building toward drama', 'late morning storm-building coastal energy — pressure in the air'],
    lunch:           ['storm arrival coastal atmosphere — the world darkening and the ocean rising', 'dramatic storm noon — the most cinematic coastal atmosphere'],
    afternoon:       ['full storm cliff atmosphere — the absolute maximum coastal drama', 'storm afternoon on the cliff — the world at its most alive and dangerous'],
    reset:           ['sea cave dusk atmosphere — dark, private, transitional', 'the cave between storm day and ocean night — transitional dark atmosphere'],
    golden_hour:     ['rare amber coastal atmosphere — the brief beautiful exception to the dark', 'golden-hour storm-break — the most cinematic coastal atmosphere moment'],
    dinner:          ['moonlit black ocean atmosphere — the most mythic coastal night', 'dark shoreline at night as the most complete siren environment'],
    evening:         ['full moonlit coastal atmosphere — silver and vast and deeply dark', 'coastal moonlit evening — the siren world at its fullest'],
    night:           ['bioluminescent ocean full night — the most mythic atmosphere on earth', 'absolute coastal night with living ocean light — the final siren world'],
  },

  propPools: {
    wake:            ['dark volcanic coastal rock', 'ocean foam at the tide line', 'pre-dawn mist on dark water'],
    morning_refresh: ['dark tidal pool with still water', 'sea anemone in tide pool', 'barnacle-covered wet rock'],
    getting_dressed: ['cliff edge with ocean drop below', 'dark chain jewelry at the throat', 'coastal wind in dark fabric'],
    breakfast:       ['dark ceramic cup in cold coastal morning', 'flat coastal rock seat at tide line', 'bare feet on dark wet stone'],
    late_morning:    ['barnacle rock formations in overcast', 'dark chain catching moody coastal light', 'coastal rock horizon in overcast'],
    lunch:           ['storm clouds on ocean horizon at noon', 'dark tide pool in storm noon light', 'ocean waves intensifying before storm'],
    afternoon:       ['cliff edge with ocean below in storm', 'dark fabric streaming in storm wind', 'ocean spray on cliff rock face'],
    reset:           ['sea cave tidal pool at dusk', 'cave mouth framing last light on ocean', 'dark candle lit at cave entrance'],
    golden_hour:     ['amber light breaking through storm clouds', 'dark wet rock in golden coastal light', 'ocean surface in rare warm coastal light'],
    dinner:          ['moonlight on black ocean surface', 'dark sand with phosphorescent foam', 'sea cave mouth framing night ocean'],
    evening:         ['full moon over dark coastal rocks', 'moonpath on black ocean to horizon', 'dark coastal rock in full moonlight'],
    night:           ['bioluminescent ocean foam at bare feet', 'dark water surface with phosphorescent light', 'absolute night ocean at the dark shoreline'],
  },

  bodyLanguagePools: {
    wake:            ['still emergence from dark shore — slow, deliberate, watching the ocean', 'flat-back lying on dark wet rock, completely still, watching the pre-dawn', 'standing at tide edge with absolute stillness and complete calm'],
    morning_refresh: ['standing in tidal pool with arms loose at sides — ownership', 'crouching at tide pool edge with hands in dark water', 'slow hair-push-back after tidal emergence — unhurried and complete'],
    getting_dressed: ['cliff-edge standing posture — no lean, no guard, complete ownership', 'slow adjustment of dark fabric against cliff-edge wind', 'turning profile to the ocean while dressing — total composure'],
    breakfast:       ['sitting on rock with complete ease — cup held, ocean behind, no performance', 'standing at tide line with coffee — absolutely still in cold morning', 'perched on rock with one knee up — private coastal ease'],
    late_morning:    ['striding across rocks with complete ownership — no hesitation', 'standing at cliff edge with arms slightly back — commanding', 'looking down into ocean from rock edge — total confidence'],
    lunch:           ['cliff stand in storm — both feet planted, no lean, complete', 'seated on rocks with straight back in storm noon — unaffected', 'standing at tide pool with stillness as the storm builds around'],
    afternoon:       ['cliff stance in full storm — arms out slightly, facing the wind directly', 'standing at cliff edge with the storm driving everything around — unmoved', 'walking the dark shore in the storm with deliberate unhurried pace'],
    reset:           ['sitting in cave entrance at dusk with quiet self-contained energy', 'standing at cave mouth looking at the ocean with complete composure', 'cave interior stillness at dusk — no movement needed'],
    golden_hour:     ['turning slowly toward rare amber cliff light — allowing it', 'cliff standing in golden light with slight lift of the face to the warmth', 'stillness in the golden moment on the cliff — receiving the rare light'],
    dinner:          ['walking moonlit shore with deliberate unhurried pace', 'standing at ocean edge at night — completely still, completely present', 'entering sea cave by moonlight with slow commanding steps'],
    evening:         ['reclining on coastal rocks in moonlight — complete ease and ownership', 'standing on cliff edge in moonlight — the most powerful evening posture', 'coastal rock sitting in moonlight with complete calm'],
    night:           ['standing at black water edge at full night — absolute stillness', 'knee-deep in night ocean — below and around, complete command', 'lying on dark rock at full night — the most private and powerful state'],
  },

  facialExpressionPools: {
    wake:            ['just-emerged coastal dawn expression — bare, private, watching', 'pre-dawn face — no performance, complete private presence', 'cool coastal dawn expression — unreadable, powerful, present'],
    morning_refresh: ['tidal morning face — cool, elemental, completely unselfconscious', 'wet post-ocean expression — direct, private, powerful', 'cold tidal pool expression — deliberate, present, dark'],
    getting_dressed: ['cliff-edge composure — controlled, dark, deliberately magnetic', 'dressing-for-the-ocean expression — focused and self-directed', 'dark coastal dressing expression — cool, precise, aware'],
    breakfast:       ['cold morning rock expression — private, unhurried, complete', 'coastal rock morning face — quiet, dark, inward', 'shoreline morning expression — solitary, powerful, complete'],
    late_morning:    ['overcast coastal authority — dark, direct, commanding', 'moody late morning face on the rocks — present and magnetic', 'cliff-edge overcast expression — controlled power, dark gaze'],
    lunch:           ['storm-light noon expression — direct, unflinching, magnetic', 'storm building expression — dark anticipation, complete composure', 'tide pool noon face — still, direct, deeply present'],
    afternoon:       ['full storm cliff expression — pure power, completely unafraid', 'cliff storm face — hair driven, expression completely controlled', 'storm afternoon expression — the most magnetic and commanding'],
    reset:           ['cave dusk composure — collected, dark, deliberate', 'pre-evening cave expression — quiet preparation, complete control', 'sea cave at dusk — the most private and precise siren expression'],
    golden_hour:     ['rare golden coast expression — brief warmth accepted deliberately', 'amber cliff expression — the only moment of warmth allowed', 'golden coastal face — dark magnetism in the warmest light of day'],
    dinner:          ['moonlit night ocean expression — dark, mythic, complete', 'night shore face — the most powerful siren expression of the day', 'moonlit cave expression — dark, intimate, commanding'],
    evening:         ['full moonlit coastal expression — total command in the silver light', 'evening coastal rock face — the siren at her full nocturnal presence', 'moonlit evening expression — dark, magnetic, complete'],
    night:           ['bioluminescent night expression — the siren at absolute fullness', 'full night coastal face — nothing to hide, nothing to perform', 'the darkest most powerful siren expression — full night, full dark'],
  },

  handDetailPools: {
    wake:            ['hand flat on wet dark rock in pre-dawn', 'fingers trailing in dark tide edge at dawn', 'hand loosely gripping volcanic rock at the shore'],
    morning_refresh: ['both hands in dark tidal pool water in morning', 'fingers running through drenched hair after tidal emergence', 'hand pressing flat on wet rock surface at tidal pool'],
    getting_dressed: ['adjusting dark fabric on cliff edge against wind', 'dark-nailed hand at chain at throat on the cliff', 'hand gripping cliff rock edge while dressing'],
    breakfast:       ['both hands around dark ceramic cup in cold coastal morning', 'dark nails on flat rock surface at breakfast', 'fingers trailing the rock edge while seated at the shoreline'],
    late_morning:    ['hand on barnacle rock surface in overcast late morning', 'dark nails against grey coastal rock in moody light', 'one hand on cliff edge, looking down at ocean below'],
    lunch:           ['fingers in dark tidal pool water at storm noon', 'hand flat on rock in storm coastal noon', 'dark nails against the tide pool edge in storm light'],
    afternoon:       ['both hands on cliff edge in storm — gripping the rock', 'arms raised slightly from sides in full storm cliff wind', 'hand pushing wet storm hair from face on cliff'],
    reset:           ['fingers trailing tidal pool surface at cave in dusk', 'hand at throat chain in sea cave pre-evening light', 'dark nails touching damp cave wall at dusk'],
    golden_hour:     ['hand raised to touch amber-lit face on cliff at golden hour', 'dark nails in golden coastal amber light detail', 'fingers touching dark chain in golden-hour cliff light'],
    dinner:          ['hand submerging in dark moonlit tidal pool at night', 'dark nails at the black water edge in moonlight', 'finger trailing dark shoreline foam in moonlit night'],
    evening:         ['hand on coastal rock surface in full moonlight', 'dark nails in full coastal moonlight evening detail', 'fingers trailing through tide at moonlit evening'],
    night:           ['hand in bioluminescent water at full dark coastal night', 'dark nails in the phosphorescent tidal foam', 'both hands submerged in the glowing dark ocean at full night'],
  },

  movementEnergyPools: {
    wake:            ['emerging', 'elemental', 'still'],
    morning_refresh: ['cold', 'ritual', 'tidal'],
    getting_dressed: ['deliberate', 'coastal', 'dark'],
    breakfast:       ['solitary', 'still', 'private'],
    late_morning:    ['commanding', 'overcast', 'present'],
    lunch:           ['storm-building', 'direct', 'powerful'],
    afternoon:       ['storm', 'full-force', 'commanding'],
    reset:           ['cave', 'transitional', 'composed'],
    golden_hour:     ['rare-amber', 'cinematic', 'still'],
    dinner:          ['moonlit', 'nocturnal', 'mythic'],
    evening:         ['silver', 'complete', 'commanding'],
    night:           ['bioluminescent', 'absolute', 'still'],
  },

  transitionPools: {
    human: {
      wake:            ['the siren emerging at the first coastal dawn', 'dark shore and pre-dawn mist and the tide pulling back'],
      morning_refresh: ['tidal morning communion — cold water and dark rock', 'the ocean morning ritual at its most elemental'],
      getting_dressed: ['cliff dressing in coastal mist — dark and deliberate', 'the siren putting on her dark world'],
      breakfast:       ['quiet coastal morning on the rocks — alone with the ocean', 'cold morning on the dark shore before the day begins'],
      late_morning:    ['moody overcast coastal presence building', 'the rocky shore in dramatic late morning command'],
      lunch:           ['the storm arriving on the coast at noon', 'dark water and storm clouds at the siren\'s noon'],
      afternoon:       ['full storm on the cliff — the siren in her element', 'the coastal storm and the cliff and the power of both'],
      reset:           ['sea cave at dusk — the transition into darkness', 'the shore going dark as the siren enters the cave'],
      golden_hour:     ['the brief amber through storm clouds on the cliff', 'the one warm moment in the dark siren world'],
      dinner:          ['moonlit black ocean arriving at the dark shore', 'the night ocean and the siren together at last'],
      evening:         ['full moonlit coastal rocks — the siren at her peak', 'the coastal night in full silver command'],
      night:           ['bioluminescent ocean at full dark — the mythic finale', 'the blackest water and the siren completely at home'],
    },
  },

  narrativeIntentPools: {
    wake:            ['the dark shore at pre-dawn as the siren\'s most private beginning', 'the ocean acknowledging her arrival at the edge of night and day'],
    morning_refresh: ['the tidal ritual as the siren\'s most elemental self-care', 'cold water and dark rock as the siren morning communion'],
    getting_dressed: ['dressing on the cliff as the most dramatic private preparation', 'the siren choosing her dark coastal look with the ocean as witness'],
    breakfast:       ['the dark shore in morning as the siren\'s most private possession', 'solitary coastal morning ease — the ocean before the world'],
    late_morning:    ['moody overcast coastal command building toward the storm', 'the siren on her rocks in full late morning presence'],
    lunch:           ['the storm arriving as the siren\'s most dramatic midday backdrop', 'dark water and storm noon as the most cinematic moment'],
    afternoon:       ['the cliff in full storm as the siren at maximum power', 'the coastal storm as natural environment for the dark feminine'],
    reset:           ['the sea cave at dusk as the siren\'s most private sanctuary', 'transitioning from the stormy day into the dark coastal night'],
    golden_hour:     ['rare amber in the dark coastal world — the most beautiful exception', 'golden-hour storm-break as the most cinematic siren moment of all'],
    dinner:          ['the moonlit black ocean as the siren\'s most mythic evening', 'dark shoreline at night as the siren\'s complete domain'],
    evening:         ['the full moon on the coastal rocks as the siren\'s peak moment', 'coastal moonlit evening as the dark feminine at its fullest power'],
    night:           ['bioluminescent ocean at full dark — the siren world complete and mythic', 'the black water at night and the siren entirely at home in the dark'],
  },

  fallbackRules: {
    pacingProfile: { wake: 'slow', morning_refresh: 'slow', getting_dressed: 'slow', breakfast: 'slow', late_morning: 'medium', lunch: 'medium', afternoon: 'medium', reset: 'slow', golden_hour: 'slow', dinner: 'slow', evening: 'slow', night: 'slow' },
    repetitionBreakers: { avoidBackToBackSameLocation: true, avoidBackToBackSameLightingStyle: true, encourageWardrobeEvolution: true },
    worldDefaults: { allowSceneGroupFallbackToPhasePools: true, allowSubLocationFallbackToWorldPools: true, preferSceneGroupsWhenPresent: true },
  },

  exclusions: {
    premium: ['warm indoor spaces', 'happy or cheerful energy', 'bright sunlight', 'crowd or social settings'],
    hard: ['beach clubs or parties', 'tropical colour palette', 'swimwear without dark ocean context', 'pastel or pink tones', 'bright midday sun'],
  },

  routeRules: {
    worldIdentity: ['this world is dark, cold, coastal, and mythic — never warm or cheerful', 'the ocean is the power source, not a backdrop — she belongs to it'],
    humanFlow: ['the day moves from elemental pre-dawn emergence through moody coastal morning into dramatic storm afternoon and full mythic night ocean', 'the energy builds from stillness to storm to moonlit power'],
    styling: ['dark palette only — black, dark green, dark navy, wet silk, sheer fabric, chain jewellery — no bright colour', 'wet hair and wet skin are integral to the aesthetic, not incidental'],
    atmosphere: ['cold, dark, moody, dramatic coastal light only — overcast, storm, moonlight, bioluminescence', 'the world is always dark — even the golden hour is the exception, not the rule'],
  },
}
