export const STORY_WORLD_DARK_FEMME = {
  id: 'dark-femme',
  name: 'Dark Femme',
  description:
    'A cinematic dark femme world of gothic glamour — velvet and black lace, deep shadow, dramatic candlelight, mysterious interior spaces, dark florals, red lips, and the particular power of a woman who owns the darkness completely.',

  geography: { country: 'private interior', region: 'dark luxury interior — gothic glamour suite' },

  identity: {
    archetype: 'dark femme — gothic luxury creator',
    vibe: ['velvet in candlelight', 'shadow as power', 'dark florals and black lace', 'mysterious interior depth', 'gothic feminine control'],
    tone: ['dark', 'dramatic', 'mysterious', 'powerful', 'elegant', 'gothic', 'controlled'],
    persona: ['completely at home in the darkness she creates', 'using shadow as eloquently as light', 'beautiful in a way that unsettles and magnetizes at once', 'the most powerful person in any dark room'],
  },

  phaseOrder: ['wake', 'morning_refresh', 'getting_dressed', 'breakfast', 'late_morning', 'lunch', 'afternoon', 'reset', 'golden_hour', 'dinner', 'evening', 'night'],

  phases: {
    wake:            { label: 'Wake',            timeWindows: ['first dark morning before curtains open', 'dim morning in a darkened room'],                pacing: 'slow',   subLocations: ['dark-bedroom', 'velvet-bed'] },
    morning_refresh: { label: 'Morning Refresh', timeWindows: ['dark bathroom in morning interior light', 'mirror in dim moody morning'],                   pacing: 'slow',   subLocations: ['dark-bathroom', 'vanity-dark'] },
    getting_dressed: { label: 'Getting Dressed', timeWindows: ['dim wardrobe morning light', 'dark dressing interior'],                                     pacing: 'slow',   subLocations: ['dark-wardrobe', 'full-mirror-dark'] },
    breakfast:       { label: 'Breakfast',       timeWindows: ['dark interior morning with dramatic window light', 'moody morning interior'],               pacing: 'slow',   subLocations: ['dark-interior-morning', 'window-dramatic'] },
    late_morning:    { label: 'Late Morning',    timeWindows: ['dramatic afternoon shadow interior', 'moody filtered indoor light'],                         pacing: 'medium', subLocations: ['dramatic-interior', 'full-mirror-dark'] },
    lunch:           { label: 'Lunch',           timeWindows: ['deep interior afternoon shadow', 'dark lounge midday'],                                      pacing: 'slow',   subLocations: ['dark-lounge', 'velvet-chair'] },
    afternoon:       { label: 'Afternoon',       timeWindows: ['deep shadow afternoon interior', 'candlelit afternoon room'],                                pacing: 'slow',   subLocations: ['dark-lounge', 'candle-room'] },
    reset:           { label: 'Reset',           timeWindows: ['pre-evening dark refinement', 'dim vanity preparation'],                                     pacing: 'slow',   subLocations: ['vanity-dark', 'full-mirror-dark'] },
    golden_hour:     { label: 'Golden Hour',     timeWindows: ['low amber dramatic window light', 'dark interior with warm amber edge'],                     pacing: 'slow',   subLocations: ['window-dramatic', 'dark-bedroom'] },
    dinner:          { label: 'Dinner',          timeWindows: ['candlelit dark dinner interior', 'deep warm evening shadow'],                                pacing: 'slow',   subLocations: ['candle-room', 'dark-dining'] },
    evening:         { label: 'Evening',         timeWindows: ['very low dark ambient evening', 'shadow-dominant intimate evening'],                         pacing: 'slow',   subLocations: ['dark-bedroom', 'velvet-chair', 'candle-room'] },
    night:           { label: 'Night',           timeWindows: ['near-total darkness with single candle or lamp', 'deep private dark night'],                 pacing: 'slow',   subLocations: ['dark-bedroom', 'velvet-bed'] },
  },

  locations: [
    'velvet-sheeted bed in deep dark interior', 'full-length mirror in dramatic shadow and light', 'dark wardrobe with black lace and velvet',
    'candlelit private room with dark florals', 'dramatic window with dark curtains partly open', 'velvet armchair in deep shadow',
    'dark lounge with warm amber candle glow', 'gothic vanity with lit mirror in darkness', 'dark dining space with candles and black roses',
  ],

  subLocations: {
    'dark-bedroom': {
      id: 'dark-bedroom', name: 'Dark Bedroom', mapAnchor: 'gothic luxury bedroom',
      category: 'private-core-dark',
      bestPhases: ['wake', 'golden_hour', 'evening', 'night'],
      overlays: ['dark velvet or black linen', 'deep shadow dominant', 'warm amber edge light only', 'gothic private atmosphere'],
      locations: ['dark velvet bed in shadow', 'deep gothic bedroom interior', 'private dark bedroom with amber edge light'],
    },
    'velvet-bed': {
      id: 'velvet-bed', name: 'Velvet Bed', mapAnchor: 'velvet bedding zone',
      category: 'intimate-dark',
      bestPhases: ['wake', 'night'],
      overlays: ['black or deep velvet bedding', 'near-total darkness with single warm source', 'intimate dark private morning or night'],
      locations: ['velvet black bedding in darkness', 'deep dark intimate bed', 'gothic morning bed zone'],
    },
    'dark-bathroom': {
      id: 'dark-bathroom', name: 'Dark Bathroom', mapAnchor: 'moody gothic bathroom',
      category: 'self-care-dark',
      bestPhases: ['morning_refresh'],
      overlays: ['dramatic mirror light', 'dark tiles or surfaces', 'moody warm bath interior', 'gothic bathroom atmosphere'],
      locations: ['dark bathroom with dramatic mirror light', 'gothic bathroom vanity', 'moody warm bath interior'],
    },
    'vanity-dark': {
      id: 'vanity-dark', name: 'Dark Vanity', mapAnchor: 'gothic lit vanity',
      category: 'preparation-dark',
      bestPhases: ['morning_refresh', 'reset'],
      overlays: ['lit vanity mirror against dark background', 'beauty products in dramatic light', 'dark glamour preparation ritual'],
      locations: ['gothic lit vanity mirror', 'dark vanity ritual zone', 'dramatic beauty preparation setting'],
    },
    'dark-wardrobe': {
      id: 'dark-wardrobe', name: 'Dark Wardrobe', mapAnchor: 'gothic wardrobe',
      category: 'dressing-dark',
      bestPhases: ['getting_dressed'],
      overlays: ['black and deep velvet pieces hanging', 'dark wardrobe interior with single amber light', 'gothic dressing ritual'],
      locations: ['dark wardrobe with black lace and velvet', 'gothic dressing zone', 'dramatic wardrobe interior'],
    },
    'full-mirror-dark': {
      id: 'full-mirror-dark', name: 'Full Mirror Dark', mapAnchor: 'dramatic full-length mirror',
      category: 'reflection-dark',
      bestPhases: ['getting_dressed', 'late_morning', 'reset'],
      overlays: ['full-length mirror against dark background', 'dramatic side or rim light on subject', 'gothic self-study framing'],
      locations: ['full-length mirror in dramatic shadow', 'dark mirror corner with rim light', 'gothic reflection zone'],
    },
    'dark-interior-morning': {
      id: 'dark-interior-morning', name: 'Dark Morning Interior', mapAnchor: 'dark morning kitchen or lounge',
      category: 'lifestyle-dark',
      bestPhases: ['breakfast'],
      overlays: ['dark interior with morning light at window edge', 'black coffee in dramatic morning light', 'gothic morning atmosphere'],
      locations: ['dark kitchen with dramatic window edge', 'gothic morning interior with coffee', 'moody dark morning lounge'],
    },
    'window-dramatic': {
      id: 'window-dramatic', name: 'Dramatic Window', mapAnchor: 'dramatic dark curtain window',
      category: 'light-dark-contrast',
      bestPhases: ['breakfast', 'golden_hour'],
      overlays: ['dark curtain partially open', 'dramatic shaft of light on subject', 'high contrast dark and light window framing'],
      locations: ['dark curtain with dramatic shaft of light', 'gothic window dramatic contrast', 'amber light shaft through dark room'],
    },
    'dramatic-interior': {
      id: 'dramatic-interior', name: 'Dramatic Interior', mapAnchor: 'gothic dramatic room',
      category: 'editorial-dark',
      bestPhases: ['late_morning'],
      overlays: ['deep shadow interior', 'single directional key light', 'dramatic editorial dark atmosphere'],
      locations: ['dramatic gothic interior with single key light', 'dark editorial room setting', 'high contrast dark lounge'],
    },
    'dark-lounge': {
      id: 'dark-lounge', name: 'Dark Lounge', mapAnchor: 'gothic lounge area',
      category: 'leisure-dark',
      bestPhases: ['lunch', 'afternoon'],
      overlays: ['dark velvet lounge furniture', 'amber candle or lamp only', 'deep shadow lounge atmosphere'],
      locations: ['dark velvet lounge in amber light', 'gothic lounge interior', 'dark private afternoon lounge'],
    },
    'velvet-chair': {
      id: 'velvet-chair', name: 'Velvet Chair', mapAnchor: 'velvet throne chair',
      category: 'power-seat',
      bestPhases: ['lunch', 'evening'],
      overlays: ['dark velvet or throne-like chair', 'deep shadow behind', 'single warm key light on subject', 'gothic power seating'],
      locations: ['dark velvet throne chair in dramatic light', 'gothic power seat in deep shadow', 'dark velvet seated corner'],
    },
    'candle-room': {
      id: 'candle-room', name: 'Candle Room', mapAnchor: 'candlelit dark interior',
      category: 'intimate-dark-evening',
      bestPhases: ['afternoon', 'dinner', 'evening'],
      overlays: ['multiple candles as sole light source', 'deep warm orange glow in darkness', 'dark florals visible in candle warmth', 'gothic intimate atmosphere'],
      locations: ['candlelit dark room with dark florals', 'gothic candle interior', 'warm candle-only dark space'],
    },
    'dark-dining': {
      id: 'dark-dining', name: 'Dark Dining', mapAnchor: 'gothic candlelit dinner space',
      category: 'dining-dark',
      bestPhases: ['dinner'],
      overlays: ['dark table with candles', 'black roses or dark florals on table', 'gothic dinner atmosphere', 'deep shadow behind the table'],
      locations: ['dark candlelit dinner table with black roses', 'gothic dining interior', 'dramatic candlelit dinner setting'],
    },
  },

  sceneVariants: {
    wake: ['waking in dark velvet bedding with barely any light in the gothic morning', 'eyes opening slowly in near-darkness before any light is admitted', 'the dark femme morning — still and private in deep shadow'],
    morning_refresh: ['gothic bathroom mirror ritual in high-contrast dramatic light', 'dark vanity beauty ritual applying dark makeup in controlled interior light'],
    getting_dressed: ['choosing black lace or velvet from the dark wardrobe in single amber light', 'full-mirror dark study in dramatic rim light — the gothic self-possession ritual'],
    breakfast: ['black coffee in a dark moody morning interior with a single amber shaft of light', 'standing in the one warm beam in the dark morning room'],
    late_morning: ['full-length mirror in dramatic shadow — the dark editorial self-study', 'dark room editorial content in single directional key light'],
    lunch: ['reclining in the velvet chair in deep shadow and amber candle glow', 'the dark lounge afternoon — velvet, candle, and complete controlled ease'],
    afternoon: ['candlelit dark room with dark florals and warm orange glow in the afternoon', 'sitting among candles in deep shadow — private dark femme afternoon'],
    reset: ['gothic vanity ritual in dramatic lit mirror against darkness — dark lips being applied', 'the pre-evening dark femme refinement at the lit mirror'],
    golden_hour: ['amber shaft of light through dark curtains — the most dramatic moment in the dark femme day', 'golden-hour amber in a dark room — light as power rather than warmth'],
    dinner: ['candlelit dark dinner table with black roses and wine in warm orange glow', 'the dark femme dinner — deep shadow, candle, and complete control'],
    evening: ['deep in the dark velvet chair or on the dark bed with candle as the only light', 'the dark interior at full evening depth — velvet and shadow and warm flame'],
    night: ['near-total darkness with single candle barely burning — the dark femme at her most powerful', 'the final private dark moment in velvet and fading candlelight'],
  },

  actionPools: {
    wake: [
      'opening eyes slowly in near-darkness in velvet bedding — no urgency, only control',
      'lying completely still in the dark before admitting any light — the darkness as comfort',
      'reaching for a dark candle or lamp at the bedside to light the gothic morning',
      'pressing one dark-nailed hand flat to the velvet surface — slow controlled wake',
      'rolling onto one side in black velvet bedding, shadow absolute, composure complete',
      'sitting up slowly in near-darkness, velvet around, no light yet beyond the amber edge',
    ],
    morning_refresh: [
      'applying dark makeup in dramatic bathroom mirror high-contrast light — controlled ritual',
      'dark lip ritual at the gothic lit vanity against darkness — precise and powerful',
      'the controlled dark beauty morning ritual in single warm light — each step deliberate',
      'leaning close to the dramatic lit mirror applying mascara or liner in high contrast',
      'pressing a dark red lipstick to lips at the vanity mirror — the defining dark morning act',
      'studying the lit reflection in complete darkness behind — still and completely self-possessed',
    ],
    getting_dressed: [
      'selecting black lace or velvet from the dark wardrobe in single amber light',
      'slow deliberate dark dressing ritual in dramatic interior — each piece placed with intent',
      'placing dark garnet or onyx jewelry on warm skin in single-light wardrobe — cool against heat',
      'pulling black velvet up over bare skin in dark wardrobe interior with one warm source',
      'holding a black lace piece in the amber light before placing it — deliberate and private',
      'fastening dark jewelry at the throat at the full-length mirror with complete composure',
    ],
    breakfast: [
      'drinking black coffee in a dark interior with one amber window light shaft crossing the room',
      'standing in the one warm beam in the dark morning room with coffee — still and powerful',
      'the controlled dark morning before the day begins — coffee, shadow, and total composure',
      'holding a dark ceramic mug in both hands in the amber shaft — the only colour in the dark room',
      'standing at the curtained window with coffee, pulling the heavy curtain one inch wider',
      'turning slowly toward the one window light in the dark morning interior — power in the stillness',
    ],
    late_morning: [
      'the full-mirror dark study — dramatic rim light and deep shadow self-possession',
      'moving through dark interior with complete control — slow, deliberate, and aware',
      'filming in dramatic single-light dark editorial framing — the dark femme in full editorial mode',
      'standing in the single key light in the dark room — the most powerful editorial position',
      'turning profile to the key light in the dark room — shadow on one side, light on the other',
      'sitting in dramatic dark interior with one arm resting on dark furniture in single light',
    ],
    lunch: [
      'reclining in the dark velvet chair with amber candle as sole light — completely at ease in darkness',
      'slow private dark afternoon in the deep lounge shadow — velvet and candle and no urgency',
      'the dark femme at ease in complete shadow — one candle, velvet chair, total private power',
      'sitting deeply in the velvet chair with one dark-nailed hand resting on the arm in candle glow',
      'crossing one leg over the other in the velvet throne chair — dark ease and complete control',
      'trailing dark-nailed fingers along the velvet chair arm in amber candle light — private and slow',
    ],
    afternoon: [
      'sitting among candles and dark florals in a private dark afternoon — surrounded by warm flame',
      'lying in the dark interior in warm candle orange — the most private candlelit gothic afternoon',
      'the slow dramatic dark afternoon ritual — candles, shadow, and complete private depth',
      'placing a new candle and lighting it slowly in the dark room — private ritual power',
      'reaching toward a dark rose in candlelight — fingers close to the bloom and the warm flame',
      'reclining in dark lounge among multiple candles — warm orange on skin and velvet everywhere',
    ],
    reset: [
      'dark lipstick application at gothic vanity in lit mirror — precise, deliberate, powerful',
      'placing dark jewelry and completing dark makeup before the evening in single vanity light',
      'the deliberate dark preparation ritual at the vanity — each piece of the evening identity placed',
      'applying dark eye detail at the lit vanity mirror — face close, background completely dark',
      'selecting from dark jewelry laid out on the vanity — garnet or obsidian in warm mirror light',
      'brushing hair back deliberately at the lit vanity — dark and composed against the darkness behind',
    ],
    golden_hour: [
      'the amber shaft of light through dark curtains falling on skin and velvet — the defining moment',
      'standing in the one dramatic ray of warm light in the dark room — still and completely powerful',
      'the dark femme in her most cinematically powerful golden-hour moment — light as the exception',
      'stepping forward into the amber shaft, velvet and dark lace catching warm light in contrast',
      'holding out one dark-nailed hand into the amber shaft — watching the light on dark skin and nail',
      'turning face into the amber shaft with eyes closed — light catching dark lips and bone in warmth',
    ],
    dinner: [
      'sitting at the dark candlelit dinner table with black roses in warm orange glow — composed and powerful',
      'the dramatic dark dinner — controlled, mysterious, powerful at the table with complete ease',
      'slow candle-lit dark meal with complete composed dark control — every movement deliberate',
      'reaching for a wine glass in warm orange candlelight — dark nails and dark jewels in the glow',
      'lifting a fork or glass at the dark table in candle warm — control complete, no rush',
      'sitting back in the dark dinner chair in candlelight — completely owning the gothic dinner scene',
    ],
    evening: [
      'deep in the dark velvet chair in candle glow — the dark femme at full evening depth',
      'the dark femme evening — shadow dominant with candle edge barely holding the form',
      'moving slowly through the dark room with warm candle barely holding — completely deliberate',
      'sitting very still in velvet in the darkest room with one candle — the most powerful stillness',
      'lying across the dark bed in candlelight — velvet and shadow and warm orange edge on skin',
      'reaching slowly toward the candle in near-total dark — not to extinguish it, only to be near it',
    ],
    night: [
      'the final dark femme night — near-total darkness with single dying flame barely visible',
      'lying in velvet in the darkest most private interior at night — completely private and powerful',
      'candle burning very low in near-darkness as the dark day ends — still and complete',
      'watching the candle burn down in near-total darkness — no hurry, complete ownership of the dark',
      'lying completely still in black velvet as the last candle light barely holds in the room',
      'the final moment — one dark-nailed hand near the fading flame in near-total darkness',
    ],
  },

  environmentPools: {
    wake: [
      'dark velvet bed in near-total morning darkness — no light admitted, only shadow and warmth',
      'gothic bedroom interior before any curtains open — deep private dark morning state',
      'deep shadow bedroom with warm amber edge barely visible at one side only',
      'black velvet bedding in near-dark — barely any ambient, one warm source far at the edge',
      'dark bedroom interior at full morning dark — curtains closed, velvet warm, shadow absolute',
      'gothic morning bed zone — dark fabric, deep shadow, single low amber source at bedside',
    ],
    morning_refresh: [
      'gothic bathroom with high-contrast dramatic mirror light — face lit, everything dark beyond',
      'dark vanity with lit mirror ring against complete dark background — studio portrait in darkness',
      'moody warm dark bathroom morning interior — dark tiles and lit mirror in tension',
      'gothic bathroom mirror lit at dramatic 3000K — face bright, bathroom shadow deep behind',
      'dark bathroom vanity with single lit mirror, dark ceramic beauty products in warm glow',
      'dramatic bathroom interior — dark surfaces, lit face, dark background, gothic composition',
    ],
    getting_dressed: [
      'dark wardrobe interior with single amber light on black lace and velvet pieces hanging',
      'full-length mirror in dramatic shadow with rim light only from one directional side source',
      'gothic dressing ritual zone in dark interior — one warm source, all else in deep shadow',
      'black lace and velvet in amber wardrobe glow — the rest of the room in complete dark',
      'dark wardrobe with one hanging bulb casting amber on the gothic selection of pieces',
      'full-mirror in dark room with hard dramatic rim light from one side — deep shadow opposite',
    ],
    breakfast: [
      'dark morning interior with amber shaft of window light cutting through curtains precisely',
      'gothic kitchen or lounge with black coffee and dramatic morning contrast in deep dark interior',
      'moody dark apartment morning with one warm source — the shaft and everything else in shadow',
      'dark morning interior where only the one amber shaft is visible in otherwise total shadow',
      'gothic morning room — dark curtained, one light beam crossing the space, deep dark beyond',
      'dark interior morning with dramatic single window beam and black coffee in warm amber pool',
    ],
    late_morning: [
      'dramatic gothic interior with single directional key light on subject, deep shadow around',
      'full-length mirror in dark room with deep shadow behind — dramatic reflection composition',
      'dark editorial interior controlled for maximum drama — one source, deep black background',
      'single key light at 3500K in completely dark room — the dark femme editorial setup',
      'dark lounge interior with controlled spot on subject — everything else falls to deep dark',
      'gothic interior in controlled editorial dark — dramatic, precise, and cinematically powerful',
    ],
    lunch: [
      'dark velvet lounge with amber candle glow and deep shadow behind and around all edges',
      'velvet throne chair in dramatic dark afternoon candlelight — one candle, deep shadow throne',
      'dark interior lounge lit only by amber candle — warm pool on velvet chair, all else in dark',
      'gothic lounge in single candle at 1700K — warm orange on velvet chair, black room around',
      'dark private afternoon lounge with amber candle barely holding against deep shadow',
      'velvet lounge interior in total dark except for one amber candle — the darkest afternoon space',
    ],
    afternoon: [
      'candlelit dark room with dark florals and warm orange light in deep shadow everywhere',
      'dark interior in warm orange candle glow only — multiple candles, no other source anywhere',
      'gothic afternoon — multiple candles in complete darkness with dark roses at each',
      'deep dark room with five or six candles burning — warm orange fill, shadow between flames',
      'dark candlelit interior with black roses and dried dark florals in warm candle warm',
      'gothic afternoon candle room — completely dark except for warm flame light on each surface',
    ],
    reset: [
      'gothic lit vanity mirror in near-darkness — face fully lit, background completely dark',
      'dark vanity ritual preparation zone at lit mirror — dramatic beauty portrait in near-dark',
      'dramatic lit mirror face against deep dark room behind — the most powerful dark vanity moment',
      'lit vanity ring at 3200K against near-black — subject face bright, dark room disappearing behind',
      'gothic vanity in near-total dark with lit mirror as the only warm source in the space',
      'dark preparation interior — vanity lit bright, dark beauty products visible, darkness everywhere else',
    ],
    golden_hour: [
      'dark curtain partially open with amber shaft of light falling on skin and velvet precisely',
      'dark bedroom interior with one amber window beam entering — light as the exception in darkness',
      'the most dramatic high-contrast golden-hour interior moment — amber shaft in complete dark room',
      'dark curtained room with one controlled amber shaft at 2600K crossing the dark interior',
      'gothic room in near-dark with single amber window beam cutting at a low dramatic angle',
      'dark interior golden hour — the most powerful contrast of the entire day, amber in total dark',
    ],
    dinner: [
      'dark candlelit dinner table with black roses and deep shadow behind and around the setting',
      'gothic dining interior with candles as sole light source — dark, warm, and completely controlled',
      'dark dinner setting — controlled, mysterious, powerfully warm in deep orange candle glow',
      'gothic dinner table with black roses, candles, dark tablecloth, and deep shadow surrounding',
      'dark dining interior lit only by candles — black roses close, deep shadow beyond the table',
      'candlelit gothic dinner space — warm orange on dark table surface, blackness beyond the flame',
    ],
    evening: [
      'deep dark velvet interior with candle as the sole source — shadow everywhere beyond flame',
      'dark velvet chair in dramatic candle glow — one candle, deep dark room, orange edge on velvet',
      'the dark room at full evening depth — shadow and warm flame barely holding against the dark',
      'gothic evening interior — near-total dark with single candle barely illuminating the subject',
      'dark bedroom or lounge in deep evening dark — one candle source, all else in deep black',
      'the darkest most intimate dark femme evening — velvet, shadow, and barely a warm edge',
    ],
    night: [
      'near-total darkness with single low candle only — barely any light, maximum dark power',
      'deep dark gothic bedroom in final candlelight — velvet in near-dark, barely anything visible',
      'the darkest most private interior moment of the dark femme day — one flame, total dark',
      'gothic bedroom at final night depth — single candle almost out, near-total darkness around',
      'black velvet bed in near-total dark — one tiny candle flame as the only light in the world',
      'the deepest dark — barely any flame, velvet in near-complete darkness, total private power',
    ],
  },

  moodPools: {
    wake: [
      'dark private power before any light is admitted — the day beginning in complete control',
      'the dark femme at her most private — in velvet darkness, before any performance begins',
      'mysterious morning control in deep shadow — the darkness as home, not as absence',
      'gothic morning stillness — near-total dark and complete private feminine power',
      'the deepest private morning — no light, only velvet and shadow and complete composure',
      'waking in darkness as a choice — the dark femme world opening on her own terms',
    ],
    morning_refresh: [
      'gothic self-care ritual power in controlled dramatic light — the most deliberate morning',
      'dark bathroom composition and intensity energy — the lit mirror as a weapon of beauty',
      'dark controlled morning composure at the lit mirror — precise, powerful, and completely herself',
      'the dramatic dark beauty ritual — high contrast light as the mirror of gothic identity',
      'cold dark tile and warm dramatic mirror in tension — the gothic morning sensory contrast',
      'the dark lip and lit vanity energy — building the day\'s identity in dramatic mirror light',
    ],
    getting_dressed: [
      'the dark dressing ritual — deliberate, precise, and powerfully dark in every choice',
      'selecting darkness as the day\'s identity statement — each piece of black lace intentional',
      'gothic feminine preparation in single warm wardrobe light — darkness chosen, not inherited',
      'the velvet and lace selection ritual — the dark femme building her aesthetic in private',
      'dressing in deep shadow with one amber source — the most private and powerful act of the dark day',
      'black over bare skin — the deliberate dark feminine transformation beginning in the wardrobe',
    ],
    breakfast: [
      'dark controlled morning energy in the gothic interior — coffee and shadow and composure',
      'the dramatic dark morning with one warm beam — light used only as contrast to shadow',
      'gothic private morning composure at the dark window — still, controlled, and powerful',
      'black coffee and dark morning — the dark femme before the world is even aware she\'s awake',
      'the controlled dark morning before anything is admitted — no warmth except on her terms',
      'dramatic morning interior energy — the one shaft of light making the darkness more complete',
    ],
    late_morning: [
      'dramatic dark editorial presence in controlled interior light — shadow as the medium',
      'shadow as editorial visual language — the dark femme using darkness with complete intention',
      'the dark femme in controlled daylight — still dark by design, using light as drama',
      'gothic editorial composure in single key light — the most powerful dark daytime energy',
      'dark dramatic self-possession in single light — the editorial dark femme completely controlled',
      'shadow and single source and total dark feminine authority — the late morning dark editorial',
    ],
    lunch: [
      'private dark afternoon power in velvet and candle — the most controlled afternoon ease',
      'deep shadow lounge ease in the dark femme world — private, still, and completely powerful',
      'the dark velvet afternoon — private and completely controlled in amber and deep shadow',
      'dark lounge ease in one candle warmth — not resting but dwelling in power',
      'velvet throne afternoon energy — seated in deep shadow with candle barely holding light',
      'the dark femme at private midday ease — shadow everywhere, velvet beneath, power absolute',
    ],
    afternoon: [
      'candlelit gothic afternoon intimacy — warm flame in complete private darkness',
      'private dark sensory depth in warm candle orange — the afternoon sealed in flame warmth',
      'warm dark flame afternoon energy in deep shadow — the most intimate dark femme afternoon',
      'gothic candlelit afternoon depth — dark florals, warm flame, and complete private power',
      'the dark afternoon as sensory private world — candles and shadow and deliberate warmth',
      'candlelit dark room afternoon — the most intimate gothic private energy of the day',
    ],
    reset: [
      'the gothic refinement ritual at the lit vanity — building the evening identity precisely',
      'dark pre-evening controlled preparation energy — the most deliberate moment of the dark day',
      'deliberate dark feminine composure building for the evening — the vanity as the threshold',
      'gothic evening preparation — dark lips, dark jewelry, and controlled pre-evening power',
      'the dark femme refining herself at the lit mirror in darkness — the ritual of dark identity',
      'pre-evening dark refinement — precise, gothic, and completely controlled at the vanity',
    ],
    golden_hour: [
      'the amber shaft in darkness — the most cinematically powerful dark femme moment of the day',
      'dramatic dark golden-hour contrast at maximum — light proving the shadow, not softening it',
      'the dark femme in the light that proves she owns the dark — amber as exception',
      'one dramatic amber beam and total dark — the highest-contrast moment in the dark femme world',
      'gothic golden hour — the shaft as power rather than warmth, drama rather than ease',
      'amber in total darkness — the most cinematic and powerful image of the dark femme day',
    ],
    dinner: [
      'gothic candlelit dinner power — the most controlled beautiful dark evening moment',
      'dark controlled mysterious elegance at the dinner table — completely composed in candle warm',
      'the most deliberately powerful dark evening energy — candle, black rose, and total control',
      'gothic dinner composure — warm orange flame on dark setting and complete feminine power',
      'the dark dinner as performance of control — the table set dark, the room in deep shadow',
      'candlelit dark feminine authority at the dinner table — deliberate, beautiful, and absolute',
    ],
    evening: [
      'deep dark intimate evening control — shadow everywhere, candle barely holding the form',
      'the dark femme at full shadow depth in candlelight — near-total dark and maximum power',
      'warm candle in total darkness — ultimate feminine gothic power in the private evening',
      'the gothic evening at full depth — velvet and shadow and the barely visible warm edge',
      'dark intimate evening authority — near-total shadow, one flame, and complete composure',
      'the deepest most private dark femme evening — warm candle in absolute dark, power complete',
    ],
    night: [
      'the deepest darkest most private night of the dark femme world — near-total darkness',
      'candlelight in near-total darkness — maximum gothic intimate power at the end of the day',
      'the dark femme complete and fully private in her world — darkness as the final destination',
      'near-total dark and one dying flame — the most powerful dark femme moment of all',
      'the final private darkness — the dark femme owning the dark completely at the night\'s end',
      'gothic night at absolute depth — barely any light, velvet and shadow and total private power',
    ],
  },

  cameraPools: {
    wake: [
      '85mm low angle from velvet bed edge, near-total shadow, single warm amber edge barely at one side',
      '135mm close-up in near-darkness — one warm amber source defining the edge of subject against black',
      '50mm wide dark bedroom — velvet bed in deep shadow, one amber edge barely visible at frame side',
      '135mm extreme close on dark-nailed hand on velvet in near-total morning dark — barely lit',
      '85mm elevated above bed looking down on subject in velvet bedding in deep shadow and barely amber',
      '135mm tight face in near-darkness — barely readable, one warm amber edge at cheekbone only',
    ],
    morning_refresh: [
      '85mm dramatic bathroom mirror, dark background, lit face in high contrast against darkness behind',
      '50mm vanity mid shot — lit face and dark background, beauty portrait in near-dark',
      '135mm extreme close on dark lip application at lit mirror — warm glow on lips, dark beyond',
      '85mm over-shoulder into gothic lit mirror — face lit by warm ring, dark room completely behind',
      '35mm wide dark bathroom — lit mirror island in middle of frame, darkness surrounding completely',
      '135mm tight face at vanity — lit by mirror ring at 3000K, dark background disappearing behind',
    ],
    getting_dressed: [
      '50mm dark wardrobe framing, single amber light, deep black shadow behind subject throughout',
      '85mm full-mirror dark study, dramatic rim light only from one side, deep shadow on opposite',
      '135mm close on dark-nailed hands selecting black lace from wardrobe in amber light',
      '50mm dark wardrobe interior — subject in single amber source, black pieces hanging around',
      '85mm low angle looking up at subject in dark wardrobe with single amber overhead source',
      '135mm over-shoulder into dark full-length mirror — rim lit face in reflection, dark room behind',
    ],
    breakfast: [
      '85mm dark interior with amber light shaft from window, subject in high-contrast versus dark background',
      '35mm wide dark morning room with one warm shaft of window light cutting through completely',
      '50mm dark kitchen interior — subject in single amber shaft, dark room surrounding completely',
      '135mm tight on subject in amber shaft — warm rim, dark room dissolved beyond in near-black',
      '85mm dark morning room — subject standing in one shaft, everything else in complete shadow',
      '50mm low angle in dark morning interior, amber shaft entering from above at diagonal',
    ],
    late_morning: [
      '85mm single key light editorial in dark room, deep shadow behind subject throughout',
      '135mm close-up in controlled dramatic single key light against near-black background',
      '50mm dark editorial room — subject in single key source, background completely black',
      '85mm dramatic interior with one light, face in warm source, everything else in deep dark',
      '135mm extreme close in single key — maximum dark editorial contrast throughout the frame',
      '50mm wide dark room with single spot — subject lit, all surrounding in near-total shadow',
    ],
    lunch: [
      '85mm velvet chair in amber candle glow, deep black shadow behind and around subject',
      '135mm dark lounge close, candle as the sole warm source for the entire frame',
      '50mm wide dark lounge — velvet chair in amber pool, darkness filling rest of frame',
      '85mm low angle from floor at velvet chair, candle at frame edge, deep shadow behind',
      '135mm tight face in candle glow — warm orange from one candle, dark background completely',
      '85mm side angle at velvet chair — candle in extreme foreground, face in warm bokeh behind',
    ],
    afternoon: [
      '85mm candlelit dark room, multiple candles creating warm bokeh in dark background throughout',
      '50mm dark interior with candle key light — warm orange fill in complete darkness around',
      '135mm close on subject among candles — warm bokeh of multiple candles filling dark behind',
      '85mm wide dark candlelit room — subject in center of warm flame pool, dark beyond all edges',
      '50mm low angle in dark candle room — candles at frame level, subject above in warm glow',
      '135mm extreme close in candlelit dark — single candle creating warm halo in near-total dark',
    ],
    reset: [
      '85mm lit vanity close, dark background behind, warm mirror light on face only and nothing more',
      '50mm vanity shot — face lit by mirror ring against total darkness behind subject completely',
      '135mm extreme close on dark lip at lit vanity mirror — precise, warm, dark room disappearing',
      '85mm over-shoulder into lit vanity — face in mirror sharp and warm, dark room receding behind',
      '35mm wide dark vanity scene — lit mirror island in darkness, subject at center of warm glow',
      '135mm tight face at lit vanity in dark room — beauty portrait in complete darkness',
    ],
    golden_hour: [
      '135mm dramatic amber shaft backlit close — warm rim light from window beam, dark room behind',
      '24mm wide dark room shot — one amber shaft of light crossing the dark background at angle',
      '85mm subject in amber shaft — warm rim light on velvet and skin, dark room everywhere else',
      '135mm tight close in amber shaft — warm backlight edge, deep shadow on opposite face side',
      '50mm dark room with single amber shaft — subject partially in beam, dramatic shadow split',
      '85mm low angle in dark room, amber shaft entering high and cutting down to subject',
    ],
    dinner: [
      '85mm dark candlelit table close, candle key source, deep shadow beyond and behind throughout',
      '135mm dramatic dark dinner close-up, single candle in warm bokeh background',
      '50mm wide dark dinner scene — dark table, black roses, candles as islands of warm in dark',
      '85mm low angle at dark dinner table — candle at frame level, face above in warm orange glow',
      '135mm tight face at candle — warm orange edge on one side, deep shadow on opposite complete',
      '85mm over dark table, black roses in foreground bokeh, face sharp in candle warm behind',
    ],
    evening: [
      '85mm velvet chair or dark bed in candle glow, shadow dominant frame throughout completely',
      '135mm dark intimate close in single warm candle source against deep dark background',
      '50mm wide dark evening interior — subject barely visible in single candle pool, dark around',
      '85mm low angle in dark evening room — candle at floor level, face above in warm orange edge',
      '135mm extreme close in near-dark evening — barely lit by single candle, dark absolutely dominant',
      '85mm from far corner of dark room — subject barely visible in candle pool, maximum dark depth',
    ],
    night: [
      '135mm single candle close-up in near-total darkness — flame as sole warm source throughout',
      '85mm very low light dark bedroom — minimal warm amber rim defining one edge only',
      '50mm wide near-dark night — single candle barely burning, everything else in complete black',
      '135mm extreme close in near-total dark — barely any amber edge visible on skin and velvet',
      '85mm low angle, single candle in foreground barely burning, subject in deep dark behind',
      '135mm face in absolute near-dark — one barely visible warm edge, the rest completely black',
    ],
  },

  lightingPools: {
    wake: [
      'near-total darkness with 1700K single warm amber edge from one side — no fill, maximum shadow',
      'deep dark morning — barely any light, velvet and skin in near-complete shadow throughout',
      'single amber bedside candle at 1600K barely burning — minimum light, maximum gothic dark',
      'dark morning interior with no natural light admitted — only the dimmest amber at room edge',
      '1800K warm amber source at extreme edge of frame — subject at 80% shadow, barely visible',
      'near-complete dark at morning — barely any 1700K candle, velvet absorbing all ambient',
    ],
    morning_refresh: [
      'high-contrast bathroom mirror light at 3000K — harsh directional on face, complete darkness behind',
      'lit vanity ring at 3200K against near-black background — studio portrait in darkness',
      '3000K mirror ring light on face — warm flattering fill from front, dark room completely behind',
      'dramatic bathroom mirror at 2800K against dark tiles — the most gothic beauty portrait light',
      'lit vanity at 3200K — warm ring halo on face, complete dark room disappearing behind subject',
      'high-contrast dark bathroom at 3100K mirror source — face lit, dark surrounding absolute',
    ],
    getting_dressed: [
      '1800K single amber source in dark wardrobe — deep shadow, warm edge on lace and velvet fabric',
      'single side key light at 2800K in dark interior — rim light defining subject against total darkness',
      '1900K amber hanging bulb in dark wardrobe — warm pool on black lace, deep shadow beyond bulb',
      '2600K side rim in dark wardrobe interior — one lit edge, total shadow on all other surfaces',
      'single amber source at 1800K warming black velvet in dark wardrobe — maximum contrast detail',
      '2800K key rim in dark dressing interior — defined edge on subject, rest of room disappearing',
    ],
    breakfast: [
      'one amber shaft of window light at 2700K cutting through dark curtained interior, all else shadow',
      'dark morning interior with 2500K single warm lamp as sole visible source throughout',
      '2600K amber shaft through dark curtain — the only light in the room, high contrast complete',
      'dark morning interior at 2500K window shaft — warm light on subject, deep shadow everywhere else',
      '2700K amber window beam crossing dark room — subject in beam, rest in absolute shadow',
      'single 2600K window shaft in otherwise dark room — the light and the dark in maximum tension',
    ],
    late_morning: [
      'single directional key light at 3500K against dark room interior — editorial dark portrait',
      'controlled 4000K spot in dark room — intentional dark studio aesthetic throughout',
      '3500K single spot key in dark interior — editorial shadows, no fill, maximum dark contrast',
      'one 3800K key source in completely dark room — hard shadow on one side, lit on the other',
      'controlled 3600K directional in dark interior — editorial beauty in maximum shadow',
      'single key at 4000K with no fill in dark room — the most dramatic editorial dark portrait light',
    ],
    lunch: [
      'candle at 1700K as sole source in dark lounge — maximum orange warmth in near-darkness',
      'warm 2200K single lamp in dark lounge, all background in deep shadow beyond visible',
      'single candle at 1700K in dark lounge interior — warm amber pool on velvet chair, dark beyond',
      '1800K candle in dark lounge — orange warmth on velvet and skin, black room around completely',
      '2000K single warm lamp source in dark afternoon lounge — pool on subject, shadow dominant',
      'one candle at 1700K as sole dark lounge source — the minimum light for maximum dark power',
    ],
    afternoon: [
      'multiple candles at 1600K-1800K — warm orange fill from several directions in total darkness',
      'candlelit dark room — no other source, warm orange on dark florals and skin throughout',
      'five candles at 1700K in complete dark — warm orange from multiple soft sources, deep shadows between',
      '1700K multi-candle fill in total dark room — orange warmth everywhere, deep shadow between flames',
      'candlelit gothic afternoon — 1600K-1800K multiple flames, no ambient, maximum warm dark',
      'dark room with multiple candles at 1700K — warm fill, shadow between, dark florals in warm glow',
    ],
    reset: [
      'vanity ring at 3000K against dark background — beauty portrait lighting in darkness',
      'warm 2800K lit mirror against near-total dark background — face lit, all else dark',
      '3000K vanity ring — warm flattering face light against completely dark room behind',
      'lit vanity at 3200K in near-dark interior — the most dramatic dark beauty preparation light',
      '2800K warm mirror ring in total dark — face lit precisely, background disappearing completely',
      'gothic vanity at 3100K against black — maximum contrast dark beauty portrait preparation',
    ],
    golden_hour: [
      'amber 2600K shaft of directional light through dark curtain — highest contrast moment of day',
      'warm backlight at 2700K through dark room — rim light only, deep shadow everywhere else',
      '2600K amber shaft entering dark room — warm rim light on velvet and skin, dark overwhelming',
      'golden-hour amber at 2700K as the only light in an otherwise completely dark room',
      '2600K directional shaft — warm amber edge on subject, complete shadow dominating the frame',
      'amber 2700K window beam in dark room — the most dramatic single-source contrast of the day',
    ],
    dinner: [
      'candlelight at 1700K as sole key source — deep warm orange on dark table and dark roses',
      'two candles at 1600K creating warm cross-light in dark dining space in total darkness',
      '1700K candle key in dark dining space — warm orange on black roses and dark tablecloth',
      'single candle at 1800K on dark dinner table — warm pool on subject and dark roses, dark beyond',
      '1700K-1800K two candles in dark dining — cross-lit subject, deep shadow at all edges',
      'gothic dinner at 1700K candle — warm orange the only source, everything dark beyond the table',
    ],
    evening: [
      '1600K deep orange candle in near-total darkness — velvet and shadow completely dominant',
      'very low 2000K ambient from single lamp — maximum shadow depth throughout the interior',
      'single candle at 1600K in near-dark evening — barely holding the form, shadow overwhelming',
      '1700K candle barely burning in dark velvet room — minimum light, maximum gothic evening power',
      'near-total dark at 1600K — one candle barely visible, subject at edge of darkness',
      'dark evening at minimum light — single 1600K candle barely reaching across the dark room',
    ],
    night: [
      'single candle flame at 1500K as the only source in total darkness',
      'near-total dark — barely any ambient, single dying flame barely readable',
      'final candle at 1500K burning low — barely any light left, near-total private dark',
      '1500K barely burning flame — minimum warm light in complete darkness, gothic night complete',
      'near-dark at 1400K-1500K final flame — barely visible, maximum darkness everywhere',
      'one dying candle at 1500K — the last warm light in a completely private dark room',
    ],
  },

  stylingPools: {
    wardrobe: {
      wake: [
        'black silk or velvet nothing — barely visible in near-darkness with dark bedding',
        'deep black velvet sleep styling in dark sheets — the most private dark morning state',
        'minimal dark morning in black or deep charcoal linen — dark against dark in shadow',
        'black silk sleep chemise barely visible against dark velvet bedding in near-dark',
        'nothing but deep charcoal silk sheet in near-total morning darkness — bare and powerful',
        'dark velvet sleep robe barely draped — deep shadow around, barely any amber edge visible',
      ],
      morning_refresh: [
        'black silk robe or nothing in dark dramatic bathroom — the gothic morning beauty state',
        'dark feminine morning wrap at the gothic mirror — robe held loosely in dramatic light',
        'black robe barely closed at the dark vanity — skin visible and powerful in lit mirror',
        'deep charcoal silk wrap at gothic bathroom mirror in high-contrast dramatic light',
        'nothing but bare skin at the dark vanity — face lit bright, body disappearing into shadow',
        'black silk robe open at the collar in dramatic bathroom light — dark and deliberately composed',
      ],
      getting_dressed: [
        'black lace set or deep velvet lingerie in dramatic wardrobe light — lace edge in amber',
        'sheer black slip in dramatic side light — barely there and completely powerful',
        'dark velvet corset or deep lace intimate set in single amber wardrobe source',
        'black balcony lace bralette and matching brief in warm amber wardrobe glow',
        'deep charcoal velvet set with lace detail in single amber light — dark and deliberate',
        'black sheer bodysuit in amber wardrobe light — the most powerful dark dressing piece',
      ],
      breakfast: [
        'black silk robe at the dark morning window shaft — the robe and the shaft together',
        'gothic wrap in dark interior morning — dark robe, one amber shaft, deep dark room',
        'dark feminine morning interior look — black robe at amber window shaft in dark room',
        'deep charcoal wrap robe in dark kitchen morning with one dramatic light source',
        'black silk robe barely tied at the one amber shaft — dark and deliberate in morning',
        'gothic morning interior wrap — black fabric catching the single shaft in warm amber',
      ],
      late_morning: [
        'black lace or velvet in editorial dark daylight — the dark femme in controlled single source',
        'deep dramatic dark editorial daywear or lingerie in controlled single key light',
        'gothic dark feminine editorial look in controlled light — black, deliberate, and powerful',
        'black velvet bodysuit in dramatic single editorial source — the most powerful dark daytime look',
        'sheer black lace in dramatic single key — barely there and completely visible in the light',
        'deep charcoal editorial intimate piece in single 3500K source — dark and beautifully composed',
      ],
      lunch: [
        'black velvet or silk on dark velvet chair in amber candle — fabric against fabric in warm orange',
        'deep lace in dark lounge afternoon shadow — black lace catching barely any amber candle',
        'dark femme afternoon private wear in candle warmth — velvet and lace in single flame light',
        'black silk slip on the velvet throne chair — fabric against fabric in warm candle orange',
        'deep velvet robe draped over the dark chair in candle glow — dark private afternoon ease',
        'black lace set reclining in velvet chair — barely lit by single candle, dark room around',
      ],
      afternoon: [
        'dark velvet robe or black slip among candles — moving through warm orange in dark room',
        'black lace in warm candle dark afternoon — the most intimate dark femme afternoon state',
        'gothic dark feminine afternoon styling in candlelight — dark pieces catching orange warmth',
        'black silk robe open among multiple candles — dark velvet and warm flame in deep shadow',
        'nothing but black lace in the candlelit dark room — dark femininity in warm orange glow',
        'deep charcoal velvet slip in candlelit dark afternoon — fabric catching warm amber from flames',
      ],
      reset: [
        'black silk or lace at the dark vanity in lit mirror — dark preparation in warm light',
        'pre-evening dark refinement look at the gothic mirror — choosing the evening dark identity',
        'gothic preparation styling at lit mirror in darkness — dark lips, dark jewelry, dark lace',
        'black slip or robe at the lit vanity — dark and precise in warm mirror glow',
        'deep lace bralette and dark brief at the vanity in lit mirror — pre-evening dark set',
        'black velvet robe at the gothic vanity in near-dark — lit mirror, dark room, dark fabric',
      ],
      golden_hour: [
        'black lace against dramatic amber shaft of light — dark lace and amber in maximum contrast',
        'dark velvet in the one warm golden-hour beam — deep dark fabric catching amber glow',
        'the dark femme at golden hour — shadow and amber in maximum contrast, dark fabric in beam',
        'black sheer bodysuit in the amber shaft — translucent dark and warm amber simultaneously',
        'deep velvet piece in the one amber window beam — dark and warm light in dramatic tension',
        'black lace barely catching the amber shaft — dark femme in the most dramatic warm contrast',
      ],
      dinner: [
        'deep velvet corset or black evening look in candlelight — the most powerful dark dinner piece',
        'gothic candlelit dinner styling — black lace, dark velvet, and dark jewelry in warm orange',
        'black silk or velvet in warm dark candlelit dinner — elegant, dark, and completely composed',
        'black velvet column piece or corset in warm candle orange — gothic dinner at its most powerful',
        'deep lace dress or corseted dark look in candle glow — the dark femme at dinner depth',
        'gothic full dark evening look at the dinner table — black, velvet, lace, and candle warmth',
      ],
      evening: [
        'deep velvet or black lace in deep candlelit intimate evening — near-dark and powerful',
        'dark femme evening intimate wear in warm amber glow — barely visible and completely controlled',
        'gothic evening intimate styling in near-darkness — dark fabric and warm candle barely present',
        'black silk or velvet in near-dark evening — the most intimate dark femme evening state',
        'dark lace bodysuit in warm candle glow in near-total dark — barely visible, entirely powerful',
        'deep charcoal velvet robe in near-dark evening — single candle, deep shadow, dark comfort',
      ],
      night: [
        'black velvet or silk in near-darkness — barely visible, completely powerful in the dark',
        'the final dark private night look — deep shadow and barely seen in last candle light',
        'deep dark intimate night styling in last candle glow — near-invisible in near-total dark',
        'black silk chemise in final candlelight — barely any light, nearly gone into the darkness',
        'nothing but dark velvet bedding in near-total darkness — the most private dark night state',
        'deep black silk slip in last candle glow — the dark femme at her final most private night',
      ],
    },
    details: {
      wake: ['dark matte nails against velvet in shadow', 'dark makeup barely visible in the near-darkness', 'black or dark jewelry near amber candle edge', 'barely visible dark lip in near-total morning dark', 'dark mascara and liner barely readable in deep shadow', 'dark jewel catching the one barely visible amber edge'],
      morning_refresh: ['dark red or black lip being applied at lit mirror — the defining dark morning act', 'black or dark jewel detail in dramatic bathroom light', 'gothic beauty ritual at dark vanity in near-darkness', 'dark liner at the lit mirror — precise, dark, and powerful', 'garnet or obsidian earring in dramatic bathroom mirror glow', 'dark matte lip catching the 3000K mirror ring in warm close detail'],
      getting_dressed: ['dark garnet or onyx jewelry placed on skin in wardrobe light', 'black lace detail in dramatic single source light', 'dark feminine accessories in amber wardrobe light', 'obsidian ring on dark-nailed finger in amber wardrobe glow', 'dark velvet fabric detail in single amber source', 'black lace edge catching amber in dark wardrobe interior'],
      breakfast: ['black coffee cup and dark floral detail in morning light shaft', 'dark matte lips in the one morning light beam', 'gothic morning detail in dark interior with one warm shaft', 'dark ceramic coffee cup in amber shaft — the only warm detail visible', 'dark floral arrangement barely visible at edge of amber shaft', 'dark-nailed hand holding black ceramic mug in warm beam detail'],
      late_morning: ['editorial dark makeup in controlled single light', 'dark jewelry in dramatic single-source light', 'dark feminine editorial detail in controlled darkness', 'dark lace or velvet detail in editorial single key light', 'garnet or onyx earring in warm editorial key source', 'dark matte lip in dramatic controlled interior light — the editorial dark identity'],
      lunch: ['dark lip and matte finish in candle glow on velvet chair', 'velvet or dark lace fabric detail in amber candle light', 'gothic afternoon detail in warm candle', 'dark-nailed hand on velvet chair arm in single candle glow', 'dark jewel catching the candle warm on the velvet throne', 'black lace hem detail in amber candle orange on dark lounge'],
      afternoon: ['dark candle wax or dark floral near the subject in candlelight', 'black rose petal near candlelit setting', 'dark femme afternoon sensory detail in candle warmth', 'black rose close to a candle flame in dark afternoon warm', 'dark dried floral arrangement in multiple candle warm', 'dark velvet and black rose together in warm orange candle glow'],
      reset: ['dark lipstick applied at vanity in lit mirror against darkness', 'dark jewelry placed on skin at dark vanity', 'gothic pre-evening refinement detail at the lit mirror', 'dark lip being pressed in lit mirror — warm ring, dark room', 'garnet pendant placed at throat at dark vanity in lit glow', 'dark eyeliner applied at lit vanity — precise and powerful in near-dark'],
      golden_hour: ['dark makeup in dramatic amber shaft of light from window', 'onyx or garnet catching the one warm beam of light', 'dark lace in the golden-hour light shaft — high contrast maximum', 'dark velvet catching amber shaft edge in the most dramatic detail', 'dark-nailed hand in the amber beam — warm and dark simultaneously', 'black rose or dark floral at the edge of the amber shaft in warm light'],
      dinner: ['dark roses on the table in candlelight', 'black velvet and dark jewelry in warm candle orange glow', 'gothic dinner styling detail — dark and precise in candle warm', 'dark wine glass and black rose together in candle warm detail', 'garnet jewelry catching warm orange candle at dinner table', 'dark velvet tablecloth and dark roses in multiple candle orange glow'],
      evening: ['dark lip in warm candle glow in near-darkness — barely visible power', 'velvet and shadow detail in the dark evening', 'dark femme night detail in final warm candle', 'dark-nailed finger near candle flame in near-dark evening', 'dark lace barely visible in warm candle edge in near-total evening dark', 'black velvet at the edge of candle warm in the dark intimate evening'],
      night: ['dark nail barely visible in near-total darkness', 'candle and shadow only — minimal detail in the deepest dark', 'dark intimate final night detail in near-dark', 'barely visible dark lip in near-total night darkness', 'one dark-nailed hand near the final dying candle flame', 'dark velvet barely catching the last warm glow before the night ends'],
    },
    changeMoments: {
      wake: ['still in black or velvet before any light enters the dark room — the deepest private state', 'the darkest most private dark morning state in near-total darkness'],
      morning_refresh: ['dark robe at bathroom mirror in dramatic light — between dark sleep and dark day', 'between dark sleep and dark day at the gothic vanity in near-darkness'],
      getting_dressed: ['in the dark wardrobe selecting from darkness in amber light — private and powerful', 'the gothic dressing ritual in single source light — dark identity building'],
      breakfast: ['dark morning robe in dark interior morning with light shaft — controlled and dark', 'gothic wrap at the dramatic dark window — the one light and the complete dark'],
      late_morning: ['editorial dark look in morning controlled light — dark femme daytime aesthetic', 'dark femme daytime aesthetic in single key light — fully built and editorial'],
      lunch: ['dark afternoon private wear in velvet chair and candle — private ease in deep shadow', 'deep lounge dark styling in amber glow — seated in the darkest afternoon world'],
      afternoon: ['dark velvet robe or nothing in candlelit dark room — warm orange in complete dark', 'between dark afternoon and pre-evening at the vanity — refining the dark identity'],
      reset: ['dark pre-evening refinement at the gothic vanity — building the evening darkness', 'gothic preparation for the evening escalation at the lit mirror in near-darkness'],
      golden_hour: ['dark femme in the amber shaft — the most powerful styling moment of the day', 'black lace in the one warm beam of light — maximum dark and amber contrast'],
      dinner: ['full gothic dinner look — velvet, lace, dark jewelry in candlelight at maximum', 'dark candlelit dinner styling at maximum depth — the most powerful dark evening look'],
      evening: ['deep dark evening intimate styling in warm candle glow — near-total dark and composed', 'gothic low-light evening wardrobe in near-darkness — the deepest dark styling state'],
      night: ['final darkest night styling — near-invisible in shadow, completely powerful', 'the most private dark femme night state in last candle — near-total dark'],
    },
  },

  sensoryPools: {
    wake: ['velvet against skin in near-total darkness', 'the smell of extinguished candle wax in the gothic morning room', 'total private dark silence before any light is admitted'],
    morning_refresh: ['cold dark tile and warm dramatic mirror light in contrast', 'the deliberate chill of dark morning self-care', 'dark beauty ritual warmth in controlled dramatic bathroom light'],
    getting_dressed: ['velvet and lace fabric in dramatic single-light wardrobe darkness', 'cool dark jewelry placed deliberately on warm skin', 'the slow dark pleasure of gothic dressing in amber light'],
    breakfast: ['black coffee in the dramatic dark morning interior', 'the amber light shaft on skin in cold dark room', 'the controlled dark morning sensory contrast'],
    late_morning: ['the dramatic dark interior — cool shadow and warm single key light in tension', 'dark editorial depth with controlled single source warmth', 'shadow as the completely dominant sensory environment'],
    lunch: ['velvet chair fabric against skin in amber candle warmth', 'candle scent in dark lounge afternoon', 'the slow dark private afternoon in warm orange candle air'],
    afternoon: ['warm candle heat in a completely dark room', 'dark floral scent in candlelit space', 'the particular warmth of multiple candles in deep total shadow'],
    reset: ['dark lipstick and cool jewelry in the warm vanity ritual', 'the deliberate dark preparation sensory at the lit mirror', 'gothic pre-evening beauty ritual warmth in near-darkness'],
    golden_hour: ['dramatic amber light on cold dark room surfaces', 'the temperature contrast of warm shaft and completely dark room', 'the most powerful sensory dark femme moment'],
    dinner: ['candle heat and dark rose scent at the dinner table', 'velvet and warm candle air in dark dining space', 'gothic dinner sensory depth in warm orange'],
    evening: ['deep warm candle in dark room — the dominant dark femme sensory', 'velvet in near-total darkness — the deepest sensory depth', 'the warmth of a single candle flame in complete private dark'],
    night: ['candle flame as the only warmth in total darkness', 'velvet and deep private dark room silence', 'the final dark sensory depth of the night'],
  },

  socialEnergyPools: {
    wake: ['completely private — the dark femme before any performance or light', 'no outside eye in the deepest dark private morning'],
    morning_refresh: ['private dark self-care — no audience, only the dramatic mirror', 'gothic morning ritual energy — self-directed and deliberate'],
    getting_dressed: ['deliberate dark private transformation ritual', 'the dark femme building her aesthetic with no external validation needed'],
    breakfast: ['dark private controlled morning — unseen and powerful', 'gothic interior morning energy before the world'],
    late_morning: ['first editorial dark content energy of the day in controlled light', 'dramatic dark self-presentation to the camera beginning'],
    lunch: ['private dark lounge energy — unperforming, completely at ease in shadow', 'the dark femme resting in her world without audience'],
    afternoon: ['deeply private dark intimate afternoon in candlelight', 'candlelit dark room — no performance, only presence and warmth'],
    reset: ['dark controlled self-refinement before the evening escalation', 'private gothic preparation ritual at the lit mirror'],
    golden_hour: ['the dark femme most cinematically visible — in dramatic amber and shadow', 'the camera receives the most powerful dark image of the day'],
    dinner: ['dark controlled intimate evening — deliberate audience connection in candlelight', 'gothic dinner hour — mysterious and magnetic and controlled'],
    evening: ['deep dark intimate evening escalation in near-darkness', 'the dark femme at her most deliberately intense and private'],
    night: ['completely private final dark moment — the darkest most intimate end', 'the dark femme world complete in near-total shadow'],
  },

  atmospherePools: {
    wake: ['near-total dark silence in velvet morning before light', 'gothic bedroom in its deepest private morning state', 'the dark femme world before any light is admitted'],
    morning_refresh: ['dark bathroom dramatic mirror ritual atmosphere in high contrast', 'gothic controlled morning interior in near-darkness', 'dark self-care in dramatic light-versus-shadow tension'],
    getting_dressed: ['dark wardrobe ritual atmosphere — quiet, deliberate, powerful in amber', 'the gothic dressing energy in near-darkness with single warm source'],
    breakfast: ['dark dramatic morning interior with one shaft of warm light', 'gothic morning with single dramatic light source cutting through dark', 'controlled dark morning atmosphere'],
    late_morning: ['dark editorial interior atmosphere in controlled single key', 'dramatic single-light dark room editorial energy', 'gothic editorial dark ambience at maximum'],
    lunch: ['dark velvet afternoon lounge atmosphere in amber candle', 'amber candle in deep shadow — dark private ease', 'gothic private afternoon depth and warmth'],
    afternoon: ['warm candle in total darkness atmosphere — the dark femme afternoon', 'candlelit gothic room with dark florals in deep shadow', 'the dark femme afternoon — private and powerfully dark'],
    reset: ['pre-evening dark refinement atmosphere at the lit vanity', 'gothic vanity ritual energy in lit mirror darkness', 'controlled dark preparation for the evening'],
    golden_hour: ['the most dramatic light-shadow contrast of the entire day', 'amber shaft in dark room — extraordinary high-contrast atmosphere', 'the dark femme golden hour — more dramatic than warm'],
    dinner: ['gothic candlelit dinner atmosphere — dark, warm, mysterious in candle orange', 'deep shadow dinner with candle and dark roses', 'the most controlled and powerfully dark evening atmosphere'],
    evening: ['deep dark warm evening atmosphere — shadow completely dominant', 'the dark femme world at full depth in candlelight', 'warm candle in absolute darkness — intimate and gothic powerful'],
    night: ['total dark atmosphere with single candle barely holding light', 'the deepest most private dark femme night in near-total darkness', 'gothic night in complete dark with barely any visible'],
  },

  propPools: {
    wake: ['black or deep velvet bedding in shadow', 'extinguished candle stub on bedside table', 'dark jewelry on bedside in near-darkness'],
    morning_refresh: ['dark ceramic or black beauty products at the vanity', 'dramatic bathroom lit mirror in dark room', 'dark floral or dried gothic arrangement near sink'],
    getting_dressed: ['black lace and velvet hanging in dark wardrobe in amber light', 'dark jewelry box open on dressing surface', 'dark rose on the dressing detail'],
    breakfast: ['black coffee in dark ceramic cup with amber light shaft', 'dark floral arrangement near dramatic window', 'one amber shaft of window light in dark curtained room'],
    late_morning: ['dramatic interior with single key light source on subject', 'dark editorial styling detail visible in controlled light', 'deep shadow filling most of the frame'],
    lunch: ['velvet chair or dark lounge surface', 'amber candle burning in dark lounge', 'dark floral arrangement in amber candle glow'],
    afternoon: ['multiple candles burning in completely dark room', 'black roses or dark dried florals in candle warmth', 'dark aesthetic detail in warm candle orange'],
    reset: ['dark lipstick on vanity surface', 'dark jewelry and beauty products at lit mirror', 'candle burning at the dark vanity in near-darkness'],
    golden_hour: ['dark curtain with amber shaft visible cutting through', 'dark jewelry catching the one warm light beam', 'dark velvet or lace in amber shaft detail'],
    dinner: ['black roses or dark florals on dinner table in candle', 'candles as sole light on dark table', 'dark gothic dinner setting with wine glass in warm orange glow'],
    evening: ['candle burning low in dark room', 'dark velvet furniture detail in warm candle', 'dark floral near warm candle edge in near-darkness'],
    night: ['single candle nearly burned down in darkness', 'near-dark velvet bed in final flame light', 'darkness as the dominant visual prop'],
  },

  bodyLanguagePools: {
    wake: ['reclined in near-total darkness — still and powerful in shadow', 'slow controlled dark morning posture in velvet sheets', 'lying in absolute dark with composed private presence'],
    morning_refresh: ['dramatic upright posture at dark bathroom mirror in contrast light', 'controlled dark vanity ritual posture', 'composed dark self-care stance in dramatic single light'],
    getting_dressed: ['deliberate slow wardrobe selection in single-light darkness', 'composed full-mirror dark self-study posture with rim light', 'the gothic dressing — precise and powerful in amber light'],
    breakfast: ['standing in one amber shaft of light in dark morning room', 'controlled morning posture in gothic dark interior', 'deliberate dark morning body language in the single warm beam'],
    late_morning: ['editorial dark stance in controlled single key light', 'composed dark interior posture — still and powerfully present', 'dark femme editorial body language in maximum shadow'],
    lunch: ['reclining in velvet chair in amber candle glow', 'composed dark private afternoon posture', 'slow powerful dark lounge body language in near-darkness'],
    afternoon: ['seated or reclining among candles in deep shadow', 'deliberate dark afternoon posture in warm candlelight', 'dark private sensory afternoon body language'],
    reset: ['upright deliberate vanity posture in lit mirror darkness', 'precise dark beauty ritual posture at the gothic vanity', 'composed dark pre-evening preparation stance'],
    golden_hour: ['standing in the amber shaft with full controlled composure', 'the most powerful dark femme posture — still in one dramatic beam', 'composed full-body dark golden-hour stance'],
    dinner: ['seated at dark dinner table with complete controlled composure', 'slow deliberate dark dinner posture in candlelight', 'gothic controlled elegant dinner stance'],
    evening: ['reclining in velvet chair or on dark bed in candle glow', 'slow intimate dark evening body language', 'the dark femme at her most composed and private in near-darkness'],
    night: ['near-still in near-total darkness — barely visible and completely controlled', 'the final dark private still posture', 'deep dark minimal movement in dying candlelight'],
  },

  facialExpressionPools: {
    wake: ['eyes opening slowly in darkness — still, private, and powerful', 'dark morning gaze — no softness, only controlled presence', 'deep private dark waking expression'],
    morning_refresh: ['dramatic mirror gaze — direct and completely self-possessed', 'dark controlled self-study expression at the gothic mirror', 'gothic morning beauty ritual expression in dramatic light'],
    getting_dressed: ['dark deliberate dressing expression — knowing and controlled', 'composed dark self-selection expression', 'gothic dressing expression — precise and self-aware'],
    breakfast: ['dark morning controlled expression in the one amber light shaft', 'composed dark morning face in dramatic interior', 'gothic private morning expression in warm beam'],
    late_morning: ['dark editorial expression — powerful and completely composed', 'direct dark camera gaze in single key light', 'dramatic dark self-possession completely readable on the face'],
    lunch: ['relaxed but powerful dark lounge expression', 'composed dark feminine ease in afternoon candle', 'gothic afternoon private expression in amber warmth'],
    afternoon: ['sensory dark afternoon expression — eyes partially closed in candle warmth', 'warm dark candlelit expression', 'gothic private afternoon facial energy in warm orange'],
    reset: ['dark preparation expression — controlled and deliberate at the vanity', 'focused dark vanity expression at lit mirror', 'pre-evening dark composure building on the face'],
    golden_hour: ['the most powerful dark femme expression — in dramatic amber shaft', 'controlled direct gaze in the amber window beam', 'the dark femme in her most dramatic photographic expression'],
    dinner: ['dark controlled dinner expression — mysterious and magnetic in candlelight', 'slow deliberate dark dinner eye contact', 'gothic candlelit dinner composure completely held'],
    evening: ['deep dark private intimate evening expression', 'warm candle-lit dark femme gaze — powerful, slow, and private', 'the most deliberate controlled dark evening expression'],
    night: ['eyes barely visible in near-darkness — the most private dark expression', 'candle flame barely reflected in eyes in deep dark', 'final dark private night expression in last warmth'],
  },

  handDetailPools: {
    wake: ['dark nails on velvet bedding in shadow — barely visible', 'hand at bed edge in near-darkness', 'one hand near dark candle stub on bedside'],
    morning_refresh: ['dark-nailed fingers at bathroom mirror in dramatic light', 'hand applying dark lipstick at vanity in lit mirror', 'fingertips touching dark beauty product at dark vanity'],
    getting_dressed: ['dark-nailed fingers selecting black lace from wardrobe in amber light', 'hand placing dark garnet or onyx jewelry on wrist or throat', 'fingers adjusting velvet or lace detail in single source'],
    breakfast: ['dark-nailed hand around black coffee cup in amber light shaft', 'fingers near dark floral detail in morning light shaft', 'hand visible in one amber beam in dark morning room'],
    late_morning: ['dark-nailed hand in dramatic single key light', 'fingers at rest on dark surface in editorial dark room', 'hand detail in controlled dark editorial lighting'],
    lunch: ['dark-nailed hand resting on velvet chair arm in candle glow', 'fingers near amber candle flame in dark lounge', 'hand trailing on velvet in warm dark candle'],
    afternoon: ['dark-nailed hand near candle flame in darkness', 'fingers touching dark rose petal in candlelight', 'hand visible in warm candle orange against complete darkness'],
    reset: ['dark-nailed fingers applying dark lipstick at vanity', 'hand placing garnet or onyx on wrist at lit vanity', 'fingers at lit vanity mirror in deliberate ritual'],
    golden_hour: ['dark-nailed hand catching the one amber shaft of light', 'dark jewelry in the single warm beam — the most powerful hand detail', 'fingers on dark velvet in amber light shaft'],
    dinner: ['dark-nailed hand near candlelit wine glass', 'fingers touching dark rose at dinner table in candle', 'hand resting on dark table edge in warm orange glow'],
    evening: ['dark-nailed fingers in warm candle glow in near-dark evening', 'hand on velvet chair arm in candlelight barely visible', 'subtle dark hand detail in warm low candle light'],
    night: ['dark nails barely visible in near-total darkness', 'hand near the last candle flame at night', 'final dark private hand placement in near-dark'],
  },

  movementEnergyPools: {
    wake: ['still', 'dark', 'private'],
    morning_refresh: ['controlled', 'deliberate', 'dark'],
    getting_dressed: ['precise', 'gothic', 'slow'],
    breakfast: ['composed', 'dark', 'controlled'],
    late_morning: ['editorial', 'still', 'dramatic'],
    lunch: ['reclining', 'dark', 'powerful'],
    afternoon: ['slow', 'sensory', 'dark'],
    reset: ['deliberate', 'gothic', 'refining'],
    golden_hour: ['still', 'dramatic', 'powerful'],
    dinner: ['slow', 'controlled', 'mysterious'],
    evening: ['minimal', 'dark', 'intimate'],
    night: ['near-still', 'private', 'complete'],
  },

  transitionPools: {
    human: {
      wake: ['waking in near-darkness in the gothic dark morning', 'the dark femme world opening slowly in deep shadow'],
      morning_refresh: ['the dark bathroom mirror ritual beginning in dramatic contrast', 'gothic self-care in controlled dramatic light'],
      getting_dressed: ['selecting from the dark wardrobe in single amber light', 'the gothic dressing ritual in near-darkness begins'],
      breakfast: ['the dark morning interior with one amber beam cutting through', 'black coffee in the gothic dark morning'],
      late_morning: ['dark editorial presence in controlled interior light', 'the dark femme in her most editorial controlled moment'],
      lunch: ['the dark velvet chair afternoon in candle glow', 'settling into deep shadow lounge ease'],
      afternoon: ['the candlelit dark room afternoon — multiple candles in shadow', 'private dark afternoon in warm candle orange'],
      reset: ['gothic vanity refinement at the lit mirror in darkness', 'preparing for the dark evening escalation'],
      golden_hour: ['the amber shaft through dark curtains — the defining dark femme moment', 'the most dramatic dark femme light of the entire day'],
      dinner: ['the dark dinner table lit only by candles with black roses', 'gothic dinner in deep shadow and warm orange flame'],
      evening: ['the dark femme at full evening depth in near-darkness', 'deep shadow and warm candle — the most intimate dark moment'],
      night: ['the final dark private night in near-total darkness', 'near-total darkness and the last dying candle'],
    },
  },

  narrativeIntentPools: {
    wake: ['the dark femme world before any light is admitted — pure private power in shadow', 'darkness as comfort, control, and complete identity'],
    morning_refresh: ['gothic self-care as power ritual — the dark morning belongs entirely to her', 'building the dark aesthetic from the inside out in dramatic light'],
    getting_dressed: ['selecting darkness as a deliberate identity statement every morning', 'the gothic dressing ritual as the first act of dark feminine power'],
    breakfast: ['the dark controlled morning — beauty in shadow before the world ever sees', 'the gothic morning interior as private power statement'],
    late_morning: ['dark editorial presence in controlled dramatic interior light', 'the dark femme making shadow her visual language and identity'],
    lunch: ['private dark afternoon ease in velvet and candle — no performance needed', 'the dark femme resting completely in her own world'],
    afternoon: ['candlelit dark afternoon — the most intimate dark sensory depth', 'private dark warmth as power and pleasure in near-total darkness'],
    reset: ['the gothic pre-evening refinement — deliberate, controlled, powerfully dark', 'building the evening dark aesthetic at the lit vanity in darkness'],
    golden_hour: ['one dramatic amber shaft in a dark room — the most powerful image of the dark femme day', 'light as the exception in a world of shadow — maximum dramatic contrast'],
    dinner: ['the dark candlelit dinner as controlled gothic power statement', 'the most deliberately beautiful dark evening moment'],
    evening: ['the dark femme at full depth — shadow dominant, warm flame barely holding light', 'the deepest most private dark evening power'],
    night: ['the final private darkness — the dark femme complete in near-total shadow', 'candle and velvet and the deepest private dark night'],
  },

  fallbackRules: {
    pacingProfile: { wake: 'slow', morning_refresh: 'slow', getting_dressed: 'slow', breakfast: 'slow', late_morning: 'medium', lunch: 'slow', afternoon: 'slow', reset: 'slow', golden_hour: 'slow', dinner: 'slow', evening: 'slow', night: 'slow' },
    repetitionBreakers: { avoidBackToBackSameLocation: true, avoidBackToBackSameLightingStyle: true, encourageWardrobeEvolution: true },
    worldDefaults: { allowSceneGroupFallbackToPhasePools: true, allowSubLocationFallbackToWorldPools: true, preferSceneGroupsWhenPresent: true },
  },

  exclusions: {
    premium: ['bright happy outdoor settings', 'pastel or light colour palettes', 'athletic gym settings', 'corporate or office environments'],
    hard: ['natural outdoor daylight', 'beach or pool settings', 'bright high-key lighting', 'cheerful social settings'],
  },

  routeRules: {
    worldIdentity: ['the dark femme world must feel genuinely dark — deep shadow, controlled dramatic light, gothic aesthetics throughout', 'black, velvet, dark lace, candles, and shadow are the complete visual language'],
    humanFlow: ['the day moves from deep dark morning through dramatic editorial moments to candlelit evening depth and near-total-dark night', 'light is always the exception — shadow is the absolute default'],
    styling: ['black, deep velvet, dark lace, and dark jewels throughout — no pastels or light fabrics ever', 'dark makeup including dark lips is a constant defining feature'],
    atmosphere: ['candlelight, dramatic single key lights, and amber window shafts — never bright or evenly filled', 'the dark room is always darker than expected — shadow dominates'],
  },
}
