export const STORY_WORLD_DESERT_QUEEN = {
  id: 'desert-queen',
  name: 'Desert Queen',
  description: 'Sand empire luxury — Wadi Rum rose-red canyons, Saharan dune summits, Dubai desert beyond the city, Namib at dawn, Moroccan camp under starfield. The woman who commands the oldest and most silent landscape on earth.',
  compatiblePlans: ['Fanvue', 'Unrestricted', 'Premium'],
  defaultPack: 'desert-luxury-editorial',
  defaultAgeRange: '24-40',

  subLocations: {
    'wadi-rum': {
      name: 'Wadi Rum',
      label: 'Wadi Rum · Rose-Red Canyon',
      atmosphere: 'Rose-red and orange rock canyon walls rising 300 metres, ancient Bedouin carving in the stone, sand floor between the monoliths, jeep tracks the only sign of human passage, dawn pink turning the canyon walls impossible colours',
      lightingBase: 'Wadi Rum dawn — 3800-4500K rose-gold. The canyon walls themselves become the light source, reflecting warm orange downward. By noon: hard 6000K direct overhead. Blue shadow in the canyon sides. Late afternoon: the red deepens to burgundy.',
      sceneGroups: {
        canyon_floor: { name: 'Canyon Floor', description: 'Between the red rock walls, sand floor' },
        rock_summit: { name: 'Rock Summit', description: 'Climbing above the canyon, view out' },
        dawn_light: { name: 'Dawn Canyon', description: 'First light hitting the rose-red walls' },
      },
    },
    'sahara-dunes': {
      name: 'Sahara Dunes',
      label: 'Sahara · Dune Summit',
      atmosphere: 'Dune crests that vanish into sky, wind shaping the sand edge into a perfect line, no visible end to the desert in any direction, the silence that only complete absence of life produces, golden sand against blue sky as the only palette',
      lightingBase: 'Sahara dawn — cool blue transitioning to warm gold in minutes. The dune edge catches first light as a single line of gold. By 10am: harsh 6500K bleached. Golden hour: the entire desert becomes amber from edge to edge.',
      sceneGroups: {
        dune_crest: { name: 'Dune Crest', description: 'Summit of the dune, sky in all directions' },
        dune_face: { name: 'Dune Face', description: 'Steep sand face, wind line, descending' },
        vast_plain: { name: 'Dune Plain', description: 'Flat sand reaching to horizon, scale' },
      },
    },
    'luxury-desert-camp': {
      name: 'Luxury Desert Camp',
      label: 'Desert Camp · Nomadic Grand',
      atmosphere: 'Canvas tent panels with Persian rugs within, brass lanterns on low tables, silk cushions across the floor, private plunge pool behind a sand dune, the stars above at night visible from the open tent wall',
      lightingBase: 'Camp lantern warm — 2200-2800K brass. Candles supplementing at night. Dawn: soft diffused sand-reflected light. The tent filters sunlight to amber all day.',
      sceneGroups: {
        tent_interior: { name: 'Tent Interior', description: 'Rugs, cushions, brass lanterns, luxury' },
        camp_entrance: { name: 'Camp Entry', description: 'Tent approach, desert behind, arrival' },
        private_pool: { name: 'Desert Pool', description: 'Pool behind the dune, private, impossible' },
      },
    },
    'namib-dawn': {
      name: 'Namib Desert',
      label: 'Namib · Red Dune Dawn',
      atmosphere: 'Sossusvlei dead vlei — white cracked clay floor, black dead acacia trees casting long shadows, the red dunes of Namibia behind them, a landscape so alien it reads as artistic composition rather than geography',
      lightingBase: 'Namib dawn — the most dramatic light transition on earth. Dark blue pre-dawn → gold dune crests in first minute of light → full warm 4000K within ten minutes. The dead vlei floor white, the dunes deep orange, the sky every shade simultaneously.',
      sceneGroups: {
        dead_vlei: { name: 'Dead Vlei', description: 'White floor, black trees, orange dunes' },
        red_dune: { name: 'Red Dune', description: 'Climbing Dune 45, deep red sand' },
        horizon_walk: { name: 'Desert Walk', description: 'Walking into the Namib expanse' },
      },
    },
    'moroccan-camp': {
      name: 'Moroccan Desert',
      label: 'Morocco · Merzouga Camp',
      atmosphere: 'Merzouga camp near Erg Chebbi — Saharan dunes as backdrop, Berber tent decorated with saffron and indigo textiles, campfire at night, mint tea ceremony at dawn, the call to prayer from the nearest village carried on the wind',
      lightingBase: 'Morocco desert light — warmer than Sahara proper. 4000-5000K saffron-tinted days. Campfire night at 1800K. Dawn blue-grey transitioning fast to warm orange through the tent panel.',
      sceneGroups: {
        camp_fire: { name: 'Campfire', description: 'Evening fire, sparks, desert darkness' },
        tea_ceremony: { name: 'Mint Tea', description: 'Dawn tea ritual, brass pot, cushions' },
        dune_panorama: { name: 'Erg Chebbi', description: 'Facing the great dune from camp level' },
      },
    },
    'desert-oasis': {
      name: 'Desert Oasis',
      label: 'Oasis · Water in Sand',
      atmosphere: 'Wadi spring or natural pool surrounded by date palms, cool water in brutal heat, the contrast of green and blue against orange sand, the ancient promise of water in the most waterless place',
      lightingBase: 'Oasis contrast light — hard desert overhead filtered through palm canopy. Dappled 5000K through palm fronds. Water surface catching sky. Cool green shade after open desert. Noon dramatic contrast, dawn and dusk most beautiful.',
      sceneGroups: {
        water_edge: { name: 'Water Edge', description: 'Pool edge, reflection, palms behind' },
        palm_shade: { name: 'Palm Shade', description: 'Beneath palms, dappled desert light' },
        wadi_water: { name: 'Wadi Pool', description: 'Natural spring, rock walls, cool shade' },
      },
    },
  },

  pools: {
    wake: [
      'desert camp before dawn — the tent warm, the air outside cold, the dune summit still in darkness',
      'Wadi Rum camp at first light — the canyon walls beginning to turn pink outside the tent opening',
      'luxury tent waking to silence so complete it feels like the world forgot to continue',
      'Namib dawn alarm at 5am because the vlei light is gone by 7 and the drive takes thirty minutes',
      'Moroccan camp — the call to prayer before sunrise, the camp not yet stirring, the stars fading',
      'desert camp late wake — the sun already high, the tent warm, the dunes shimmering outside',
    ],
    morning_refresh: [
      'desert camp private bathroom — outdoor shower in the open air, the dunes visible above the canvas wall',
      'luxury camp al fresco morning — warm water, cold desert air, the combination unexpectedly perfect',
      'wadi rock pool morning — natural spring water so cold it is immediately transformative',
      'camp vanity by candlelight — the canvas tent turning the morning prep into something elemental',
      'oasis pool morning — cool water, palms above, the heat of the day not yet announced',
      'outdoor shower at the camp perimeter where the desert begins one step past the mat',
    ],
    getting_dressed: [
      'white kaftan chosen for the dune summit — photographed in every desert in the world and still correct',
      'saffron silk for the campfire evening — the colour already in the sand and sky, completing something',
      'light linen layers for the day — the desert demands respect for the heat and the wind',
      'barefoot decision — the sand at dawn is cool enough, the silk against the cold desert air sufficient',
      'Moroccan textile wrap from the market — worn correctly, it becomes the most precise possible costume',
      'minimal in the oasis midday — the heat requiring almost nothing, the water requiring even less',
    ],
    breakfast: [
      'camp breakfast at dawn before the dune climb — flatbread and fruit and tea, the summit the reward',
      'mint tea ceremony on the camp cushions as the sun crests the dune and the light changes everything',
      'luxury camp breakfast service — silver tray, fresh-squeezed everything, the desert already hot',
      'roadside Bedouin stop on the drive to Wadi Rum — tea poured from height, sugared, perfected',
      'oasis breakfast under the palms — dates from the tree above, water from the spring below',
      'post-dune summit breakfast at the camp — earned entirely, eaten completely',
    ],
    late_morning: [
      'dune climb completed, back at the camp, the morning already a full event and it is barely 10am',
      'jeep crossing the Wadi Rum floor at late morning — the canyon walls changing with every angle',
      'canyon exploration on foot — the sandstone hot to touch, the shadow cool, the ancient carvings found',
      'oasis late morning rest — the heat driving everyone to shade, the pool offering the only solution',
      'camel to the far dune — the slow progress of the old transport through the sand sea',
      'luxury camp late morning — the pool, the shade, the book, the desert just outside the canvas',
    ],
    lunch: [
      'shade lunch at the camp — mezze spread on low tables, bread still warm, the dunes visible',
      'wadi valley lunch stop — food from a box in the jeep, eaten against a red rock wall',
      'oasis lunch under the date palms — the coolest place within 50 kilometres and completely private',
      'camp outdoor lunch at the long table — the whole party assembled, the desert as the dining room view',
      'roadside stop at the only café for 100km — the tea, the silence, the road continuing',
      'luxury tent lunch with the tent fully open — the desert the only landscape and the food impeccable',
    ],
    afternoon: [
      'siesta at the camp as the heat peaks — the tent interior cool, the desert outside temporarily paused',
      'afternoon dune walk as the temperature falls from brutal toward merely serious',
      'canyon exploration in the late afternoon when the light begins to come from the side',
      'camel sunset ride — the animal knowing the route, the dune edge the destination, the timing perfect',
      'oasis afternoon — the water an invitation that cannot be refused in the afternoon heat',
      'dune sand boarding at 3pm when the shadows begin and the slope becomes manageable',
    ],
    reset: [
      'camp late afternoon — the day\'s exploration done, the cool breeze arriving with the shadow of the dune',
      'desert plunge pool at 5pm — the camp\'s one piece of impossible luxury, cold and perfect',
      'sunset preparation — the camp already setting the fire, the sunset position already chosen',
      'wadi late afternoon rest in a canyon shadow — the rock still warm, the air beginning to cool',
      'camp preparation — changing for the fire, the day\'s dust removed, the evening beginning',
      'oasis late afternoon — the light turning the water from blue to gold, the palms casting long shadows',
    ],
    golden_hour: [
      'dune crest at golden hour — standing at the exact summit as the sun turns the entire Sahara amber',
      'Wadi Rum canyon at sunset — the rose-red walls deepening to blood-red to burgundy in 20 minutes',
      'camp fire lit at golden hour — the first flame in the desert dusk, the stars not yet visible',
      'oasis golden hour — the water surface turning from blue to pure gold, the palms black silhouettes',
      'Namib Dune 45 at the exact moment — the orange dune against the deep blue sky at its most saturated',
      'camel silhouette on the dune crest at golden hour — the classic that is classic for a reason',
    ],
    dinner: [
      'camp fire dinner — lamb slow-cooked underground, the stars above the open-sided tent, complete',
      'luxury camp dinner — formal table in the sand with candelabra and crystal and the dunes for walls',
      'wadi camp dinner with the Bedouin guide — simple food, honest company, the canyon quiet around it',
      'rooftop dinner at the desert hotel — the sand sea visible in every direction under a full moon',
      'oasis evening dinner — the pool lit from below, the palms black against the stars, the food excellent',
      'Moroccan camp dinner — tagine, bread, fire, the Erg Chebbi dunes orange in the last light behind them',
    ],
    evening: [
      'campfire evening — the fire the only light for miles, the conversation simple, the stars enormous',
      'star-watching from the dune — lying on the warm sand, the Milky Way overhead from edge to edge',
      'desert camp evening music — a local musician, traditional instrument, the sound travelling nowhere',
      'luxury camp cocktails before dinner — the bar set up in the sand, the dunes the backdrop, the ice improbable',
      'wadi camp evening — the canyon walls still warm from the day, the fire small, the dark complete',
      'moroccan camp evening — mint tea again, blankets against the cold, the desert night beginning properly',
    ],
    night: [
      'desert night at 1am — every star visible from horizon to horizon, no other light anywhere',
      'camp tent at midnight — the desert cold outside, the rugs warm, the silence absolute',
      'sleeping under the stars in the luxury camp open-tent — the dome of the Milky Way overhead until dawn',
      'desert night cold — the temperature dropped 25 degrees from noon, the blanket earned',
      'wadi rum midnight — the canyon completely black except for the stars reflected in the sand',
      'pre-dawn wake for the Namib vlei — 4am alarm, coffee, driving into the dark for the light',
    ],
  },

  cameraPool: [
    '24mm ultrawide on the dune summit — the full Sahara in the frame, subject small in the scale of it',
    '85mm f/1.4 on the canyon floor — rose-red walls compressed behind, the desert as painting',
    '135mm telephoto from the jeep — subject on a dune crest, sand and sky compressed',
    '50mm at the camp fire — warm 1800K fire glow, everything beyond the circle pure darkness',
    '35mm on the oasis edge — water, palms, the unexpected green in the desert frame',
    '24mm on the dead vlei — the full impossible landscape including sky, white floor, and dunes',
  ],

  lightingPool: [
    'Wadi Rum dawn — rose-gold canyon walls as the light source, ambient warmth from 300m of red stone',
    'Sahara sunrise — the precise minute when the first light hits the dune crest as a single gold line',
    'desert noon — 6500K brutal overhead, hard shadow, the desert not softening for anything',
    'campfire night — 1800K single warm source, everything beyond the circle erased by darkness',
    'Namib dawn — blue-grey to warm gold in minutes, the most dramatic colour transition on earth',
    'oasis filtered — palm canopy dappling 5000K, the contrast of shade and sun across the water',
    'golden hour Sahara — the entire desert amber from edge to edge, no colour outside this range',
    'desert moonlight — cool silver on sand, dunes visible without artificial light, completely silent',
  ],

  wardrobePool: [
    'white kaftan on the dune summit — the most photographed combination in this world for correct reason',
    'saffron or burnt orange silk — the desert reflected in the clothing, matching the landscape intentionally',
    'Moroccan textile wrap — woven there, worn there, correct in a way that tourist clothing cannot replicate',
    'minimal in the heat — the desert demanding economy, the body in the landscape doing the work',
    'dark linen at night — the campfire world with rich dark fabric, gold jewellery, no compromise',
    'barefoot on the dawn sand — the sand cool, the silk against the cold air, the simplest luxury',
    'layered for desert morning — the temperature requiring everything at dawn and nothing by noon',
    'gold jewellery against sun-warm dark skin — the ancient aesthetic that the desert has always preferred',
  ],

  moodPool: [
    'ancient power — the desert is older than every human story and she belongs to it completely',
    'desert queen command — the landscape responding to her presence as if it was designed for this',
    'solitary sovereignty — the most alone any human can be and the most free',
    'golden presence — the light of the desert finding her as its natural subject',
    'silent authority — no words needed here, the desert does not require explanation',
    'elemental femininity — wind and sand and light and a woman — the oldest scene on earth',
  ],
}
