export const STORY_WORLD_GODDESS_COMPLEX = {
  id: 'goddess-complex',
  name: 'Goddess Complex',
  description:
    'Ethereal divine feminine. Gold accents, temple light, marble columns, mythic power energy. She doesn\'t believe she\'s a goddess — she simply is one, and the architecture agrees.',

  geography: { country: 'mythic antiquity', region: 'divine temple world' },

  identity: {
    archetype: 'divine goddess',
    vibe: ['warm marble and temple light', 'gold that looks like it grew there', 'divine feminine at absolute authority', 'floral offerings and sacred ritual', 'the column and the throne as natural habitat'],
    tone: ['ethereal', 'mythic', 'golden', 'serene', 'powerful', 'divine', 'cinematic'],
    persona: ['she has always been worshipped — the camera is one more form of devotion', 'completely at ease in divinity — no performance, only presence', 'the architecture was built for her and it knows it', 'sacred beauty that exists outside of time'],
  },

  phaseOrder: ['wake', 'morning_refresh', 'getting_dressed', 'breakfast', 'late_morning', 'lunch', 'afternoon', 'reset', 'golden_hour', 'dinner', 'evening', 'night'],

  phases: {
    wake:            { label: 'Sacred Dawn',       timeWindows: ['pre-dawn temple stillness', 'first light through marble columns'],     pacing: 'slow',   subLocations: ['divine-chamber', 'marble-courtyard'] },
    morning_refresh: { label: 'Sacred Bath',       timeWindows: ['morning ritual bath light', 'sacred bathing hour'],                    pacing: 'slow',   subLocations: ['sacred-bath', 'divine-chamber'] },
    getting_dressed: { label: 'Divine Preparation',timeWindows: ['temple dressing hour', 'morning column light on silk'],                pacing: 'slow',   subLocations: ['divine-chamber', 'golden-altar'] },
    breakfast:       { label: 'Morning Offering',  timeWindows: ['morning offering hour', 'altar morning light'],                        pacing: 'slow',   subLocations: ['golden-altar', 'celestial-garden'] },
    late_morning:    { label: 'Temple Column',     timeWindows: ['mid-morning column light', 'clean warm temple morning'],               pacing: 'slow',   subLocations: ['marble-courtyard', 'throne-room'] },
    lunch:           { label: 'Divine Midday',     timeWindows: ['high noon temple light', 'midday oracle clarity'],                     pacing: 'medium', subLocations: ['throne-room', 'marble-courtyard'] },
    afternoon:       { label: 'Oracle Hour',       timeWindows: ['warm afternoon oracle light', 'temple column afternoon'],              pacing: 'slow',   subLocations: ['oracle-chamber', 'celestial-garden'] },
    reset:           { label: 'Ritual Reset',      timeWindows: ['late afternoon altar hour', 'pre-evening sacred ritual'],              pacing: 'slow',   subLocations: ['golden-altar', 'divine-chamber'] },
    golden_hour:     { label: 'Golden Apotheosis', timeWindows: ['golden-hour through temple columns', 'amber divine hour'],             pacing: 'slow',   subLocations: ['marble-courtyard', 'throne-room', 'golden-altar'] },
    dinner:          { label: 'Divine Feast',      timeWindows: ['evening sacred feast hour', 'candle-lit divine evening'],              pacing: 'slow',   subLocations: ['throne-room', 'divine-chamber'] },
    evening:         { label: 'Evening Temple',    timeWindows: ['temple evening candlelight', 'divine evening warm amber'],             pacing: 'slow',   subLocations: ['divine-chamber', 'golden-altar'] },
    night:           { label: 'Celestial Night',   timeWindows: ['night temple candlelight', 'moonlit marble night'],                   pacing: 'slow',   subLocations: ['marble-courtyard', 'divine-chamber'] },
  },

  locations: [
    'marble temple with golden hour light through open columns', 'sacred bath with flower petals and warm candlelight',
    'golden altar with floral offerings in temple light', 'throne of carved marble in warm column light',
    'open marble courtyard with sky above and column arcade', 'oracle chamber with incense and warm lamp glow',
    'celestial garden with flowering trees and warm filtered light', 'divine chamber bed with silk draping',
  ],

  subLocations: {
    'divine-chamber': {
      id: 'divine-chamber', name: 'Divine Chamber', mapAnchor: 'goddess private chamber',
      category: 'sacred-private',
      bestPhases: ['wake', 'getting_dressed', 'evening', 'night'],
      overlays: ['silk draping on carved bed', 'warm lamp or candle as light source', 'gold accents on walls and furniture', 'temple privacy and sacred quiet'],
      locations: ['marble chamber with silk-draped carved bed', 'private divine chamber in warm temple light', 'goddess chamber with gold detail and silk'],
    },
    'sacred-bath': {
      id: 'sacred-bath', name: 'Sacred Bath', mapAnchor: 'temple sacred bathing pool',
      category: 'ritual-cleansing',
      bestPhases: ['morning_refresh'],
      overlays: ['flower petals on water surface', 'warm candles at pool edge', 'marble pool surround', 'sacred bathing atmosphere'],
      locations: ['marble sacred bath pool with flower petals', 'candlelit temple bathing pool with offerings', 'sacred bath in warm morning light'],
    },
    'golden-altar': {
      id: 'golden-altar', name: 'Golden Altar', mapAnchor: 'temple golden offering altar',
      category: 'sacred-offering',
      bestPhases: ['breakfast', 'reset', 'golden_hour'],
      overlays: ['flowers and fruit offering arranged', 'candles or oil lamps burning', 'gold surface and sacred objects', 'devotional altar energy'],
      locations: ['golden temple altar with flowers and candles', 'altar with fruit and floral offerings in warm light', 'sacred golden altar with lamp and offerings'],
    },
    'marble-courtyard': {
      id: 'marble-courtyard', name: 'Marble Courtyard', mapAnchor: 'open temple courtyard',
      category: 'divine-public',
      bestPhases: ['wake', 'late_morning', 'golden_hour', 'night'],
      overlays: ['marble column arcade surrounding', 'open sky above', 'warm column light', 'sacred courtyard grandeur'],
      locations: ['open marble courtyard with column arcade', 'temple courtyard with sky above and marble surround', 'marble column arcade in warm light'],
    },
    'throne-room': {
      id: 'throne-room', name: 'Throne Room', mapAnchor: 'divine throne of carved marble',
      category: 'divine-authority',
      bestPhases: ['late_morning', 'lunch', 'dinner', 'golden_hour'],
      overlays: ['carved marble throne', 'column light entering from the side', 'gold and silk draping', 'absolute divine authority energy'],
      locations: ['marble throne in column light', 'divine throne room with silk draping', 'carved marble throne with warm architectural light'],
    },
    'oracle-chamber': {
      id: 'oracle-chamber', name: 'Oracle Chamber', mapAnchor: 'temple oracle room',
      category: 'sacred-knowledge',
      bestPhases: ['afternoon'],
      overlays: ['warm smoke or incense haze', 'oil lamp as sole light source', 'carved oracle seat', 'sacred knowledge energy'],
      locations: ['oracle chamber with oil lamp and incense smoke', 'warm lamp oracle room in temple interior', 'sacred oracle setting with atmospheric smoke and light'],
    },
    'celestial-garden': {
      id: 'celestial-garden', name: 'Celestial Garden', mapAnchor: 'sacred temple garden',
      category: 'divine-nature',
      bestPhases: ['breakfast', 'afternoon'],
      overlays: ['flowering trees and sacred plants', 'warm filtered light through foliage', 'marble walkway through garden', 'divine nature sanctuary energy'],
      locations: ['sacred garden with flowering trees and marble path', 'temple garden with warm filtered light', 'celestial garden with flowers and column boundary'],
    },
  },

  sceneVariants: {
    wake:            ['lying on silk-draped carved bed as first temple light enters from the marble columns', 'pre-dawn temple courtyard — standing in white silk as the first gold light arrives on marble'],
    morning_refresh: ['in the sacred bath pool with flower petals and candle glow in warm morning temple light', 'the sacred bath ritual — anointed, still, completely divine in warm morning water'],
    getting_dressed: ['being draped in gold-accented silk in the divine chamber in warm morning column light', 'selecting the golden adornment in the divine chamber — deliberate divine preparation'],
    breakfast:       ['at the golden altar in morning — placing flowers and fruit as offering in warm light', 'in the celestial garden at morning — fruit and offerings among the flowering trees'],
    late_morning:    ['seated at the marble throne in column light — absolute divine authority', 'walking the marble column arcade in the late morning with complete divine ease'],
    lunch:           ['at the throne in noon temple light — marble, gold, column light, complete', 'standing in the open marble courtyard at noon with the sky above and columns around'],
    afternoon:       ['in the oracle chamber in warm afternoon light and incense atmosphere', 'in the celestial garden in the warm afternoon — among flowers and sacred plants'],
    reset:           ['at the golden altar in late afternoon — ritual preparation before the divine evening', 'in the divine chamber at pre-evening — ritual reset in warm temple light'],
    golden_hour:     ['at the marble columns as golden-hour light floods the courtyard in amber', 'on the throne in golden-hour column light — the most cinematic divine moment'],
    dinner:          ['divine feast at the throne in candlelight — the goddess at the most powerful evening', 'divine chamber evening — candlelit, gold, silk, completely mythic'],
    evening:         ['divine chamber in warm candlelight with gold altar burning beside', 'evening marble courtyard under the stars with column silhouettes in candlelight'],
    night:           ['moonlit marble courtyard — columns in moonlight, the goddess between them in white', 'divine chamber at full night in candlelight — the most sacred intimate moment'],
  },

  actionPools: {
    wake:            ['lying completely still on silk in the first pale temple dawn, marble cool around', 'rising slowly from the silk-draped bed as first light reaches through the column arcade', 'standing in the divine chamber doorway as dawn fills the marble courtyard beyond', 'pressing one palm flat to the cool marble floor as the morning temple light arrives', 'sitting at the edge of the silk bed in temple pre-dawn, looking toward the courtyard', 'turning slowly in the divine chamber as the first column light crosses the silk and marble'],
    morning_refresh: ['lowering into the sacred bath pool slowly, flower petals moving around', 'lying completely still in the sacred bath pool with petals floating on the surface', 'rising from the sacred bath with hands pressing water from hair in warm candle light', 'cupping sacred bath water in both hands and releasing it slowly', 'sitting at the sacred bath pool edge, feet in the flower-petal water, in morning warmth', 'anointing the arms with the sacred bath oil in warm morning temple light'],
    getting_dressed: ['being draped in silk in the divine chamber in slow ceremonial morning ritual', 'placing golden jewellery on bare skin in the divine chamber with warm column light', 'fastening a gold cuff or collar at throat in divine chamber morning light', 'selecting the flower or crown piece from the altar arrangement for morning adornment', 'adjusting gold silk draping with both hands in the warm divine chamber', 'looking into the divine chamber mirror while the morning silk is placed on each shoulder'],
    breakfast:       ['arranging fresh flowers at the golden altar in morning offering ritual', 'placing fruit at the altar with both hands in a gesture of sacred offering', 'in the celestial garden morning — reaching up to a flowering branch with one hand', 'walking the garden path in morning with the first flowers of the day in both hands', 'kneeling at the golden altar to light the morning offering candle with complete intention', 'at the altar in morning light — both hands spread over the offerings, palms down'],
    late_morning:    ['seated on the marble throne in column light with complete divine authority', 'walking the marble courtyard arcade in late morning — slow and completely owned', 'standing between two columns in late morning light with arms slightly out at sides', 'placing one hand on a marble column in the arcade in warm late morning light', 'seated at the throne with one arm extended on the throne arm — absolute command', 'looking upward through the open marble courtyard at the late morning sky above'],
    lunch:           ['at the throne at noon with both hands resting on the carved throne arms', 'standing in the marble courtyard at noon with sun at its highest through the open ceiling', 'looking directly at noon temple light coming through the column gap above in the courtyard', 'seated on the throne at noon — most direct light of the day full on the divine face', 'walking through the column arcade at noon, light and shadow alternating across skin', 'standing at the courtyard centre at noon — the highest point of divine power'],
    afternoon:       ['seated in the oracle chamber in afternoon warmth with incense smoke around', 'holding the oracle lamp with both hands in the warm afternoon oracle chamber', 'in the celestial garden afternoon — sitting among the flowering trees in warm light', 'walking the garden path in afternoon with both hands trailing through the flowering plants', 'in the oracle chamber — leaning slightly forward with eyes half-closed in the warm smoke', 'seated in the garden with flowers gathered in both hands in warm afternoon light'],
    reset:           ['ritual reset at the golden altar before the divine evening begins', 'anointing the throat with sacred oil at the altar in late afternoon', 'placing the evening adornment at the mirror in the divine chamber in warm amber light', 'relighting the altar candles for the evening in deliberate ceremonial motion', 'selecting the evening crown or floral piece at the divine chamber altar', 'pressing hands together at the golden altar in the ritual pre-evening gesture'],
    golden_hour:     ['standing between marble columns as amber light floods the courtyard around', 'on the throne as golden-hour light enters and fills the throne room in amber', 'turning slowly in the courtyard as golden-hour column shadows cross and the amber deepens', 'raising one hand into the golden-hour column light streaming through the arcade', 'at the altar in full golden-hour amber — oil lamp glowing in the warm light', 'standing in the courtyard with both arms slightly lifted as golden light fills the space'],
    dinner:          ['at the divine feast table on the throne dais in candlelight — seated with authority', 'lighting the divine chamber candles one by one in slow ceremonial evening ritual', 'at the throne in candlelight with a golden goblet held in both hands', 'walking through the candle-lit throne room with complete divine evening composure', 'seated at the throne in the deepest candlelight — the most powerful divine moment of the day', 'at the divine feast with gold goblet raised slightly in the warm candle glow'],
    evening:         ['at the evening altar in warm candlelight — gold and flame and divine evening', 'moving through the divine chamber in evening candlelight with the silk catching the flame', 'seated in the divine chamber in evening with the altar candle as the sole light source', 'at the golden altar in evening — tending the flame with both hands close to the warmth', 'reclining on the divine chamber silk in warm evening candlelight', 'standing in the divine chamber doorway at evening with candlelight from behind'],
    night:           ['in the moonlit marble courtyard between columns at full night', 'standing in the courtyard at full night with the moon directly above through the open ceiling', 'in the divine chamber at full night in the warmth of a single candle', 'lying on silk in the divine chamber at night with one candle barely burning beside', 'in the moonlit courtyard with both arms slightly raised — the night worship moment', 'at the golden altar at full night — single candle, gold, hands pressed, completely still'],
  },

  environmentPools: {
    wake:            ['silk-draped divine chamber in first pale temple dawn with marble cool around', 'open marble courtyard in pre-dawn stillness with column silhouettes against pale sky', 'divine chamber in the first warmth of temple dawn — gold barely catching the new light', 'marble floor in pre-dawn temple with the first column light arriving from the east', 'divine private chamber in the moment before the temple wakes — completely still', 'marble courtyard in the lowest pre-dawn light with stars just visible above the columns'],
    morning_refresh: ['sacred bath pool with flower petals and candles in warm morning temple light', 'marble bath pool in morning with rose petals floating and candle glow from the edges', 'sacred bathing chamber in warm morning light with incense smoke and still water', 'flower-petal bath in marble pool, candles at rim, warm temple morning filling the space', 'sacred pool in morning temple light — petals on still water, warm candles, complete devotion', 'marble bathing sanctuary at morning — warm, still, completely sacred and private'],
    getting_dressed: ['divine chamber in warm morning column light with silk and gold laid out', 'private divine chamber in morning with gold draping and marble surface and warm fill', 'divine preparation space in warm morning — gold jewellery, silk, column light entering', 'warm divine chamber in the morning dressing hour with gold catching the early sun', 'marble-walled chamber in clean morning column light — silk and gold visible throughout', 'divine chamber dressing light — the warm column morning with every gold surface active'],
    breakfast:       ['golden altar in morning temple light with flower and fruit offering arranged', 'celestial garden in morning with flowering trees and warm filtered early light', 'altar chamber in morning with candles and fresh offerings in warm ambient light', 'garden path in morning temple light with flowers and warm filtered foliage above', 'golden altar in the morning with warm candle and oil lamp beside fresh offerings', 'sacred garden in the morning — flowering trees, marble path, warm light through leaves'],
    late_morning:    ['marble throne room in clean column light — the most authoritative temple interior', 'marble column arcade in late morning with strong light-shadow alternation', 'open courtyard in late morning with column shadows on marble floor and blue sky above', 'throne room in clean late morning light — marble, gold, column light, authority', 'marble arcade in late morning with strong directional column light across the floor', 'courtyard column light in late morning — the most dramatic architectural shadow pattern'],
    lunch:           ['open marble courtyard at noon with the sun directly above through the open centre', 'throne room at noon with direct warm column light entering at highest angle', 'marble courtyard at noon — every column casting a short strong shadow, sky vivid above', 'throne in direct noon column light — the most powerful and most direct divine light', 'courtyard at midday with noon warmth on every marble surface and blue above', 'marble arcade at noon — light and shadow alternating sharply across the floor'],
    afternoon:       ['oracle chamber in warm afternoon with oil lamp and incense smoke filling the space', 'celestial garden in afternoon warmth with flowering trees filtering warm light above', 'warm oracle room with atmospheric smoke and oil lamp and carved oracle seat', 'garden afternoon with warm directional light through flowering canopy', 'oracle chamber at afternoon peak — warm, smoky, intimate, sacred', 'sacred garden in warm afternoon — every flower open, filtered light warm and soft'],
    reset:           ['golden altar in late afternoon amber light with candles and pre-evening offering', 'divine chamber in late afternoon warm — pre-evening preparation ritual atmosphere', 'altar at pre-evening in warm amber light — gold surfaces fully activated', 'divine chamber in the last afternoon warmth before evening candles are lit', 'golden altar at the day\'s golden pivot — late afternoon into pre-evening', 'altar chamber in warm amber pre-evening — candles just lit, gold warm in the ambient'],
    golden_hour:     ['marble courtyard in full golden-hour amber with column shadows long and warm', 'throne room in golden-hour column light — amber flooding every surface from the west', 'marble column arcade at golden hour — the columns casting long orange shadows', 'courtyard at golden hour with warm amber sky above and every surface in orange glow', 'golden-hour throne room — the most cinematic divine interior moment', 'marble arcade in golden hour — amber light horizontal through every column gap'],
    dinner:          ['throne room in candlelight at divine feast hour — deep warm shadow beyond the flame', 'divine chamber in candlelight evening — gold and warm orange and complete privacy', 'throne dais in candlelight with feast arrangement in warm orange pool', 'divine chamber evening with candle as the sole light — warm, intimate, mythic', 'throne room at feast hour in candlelight — the goddess and the warm dark and gold', 'candlelit divine feast setting — marble throne, gold goblet, deep warm shadow around'],
    evening:         ['divine chamber in warm evening candlelight with golden altar burning beside', 'golden altar at evening with candles in full warm glow and deep shadow around', 'temple evening candlelit interior — warm, divine, completely sacred', 'divine chamber at evening — one source of warm candle light, everything else in shadow', 'altar chamber evening — candles clustered, gold warm, deep shadow beyond', 'evening temple interior at its most intimate — candle warmth, gold, divine private'],
    night:           ['moonlit marble courtyard at full night with column silhouettes against the moon', 'divine chamber at full night in single candle warmth — completely sacred', 'marble courtyard at full moon — every surface silver and white and divine', 'night temple interior with single candle — the deepest divine private moment', 'moonlit column arcade at full night — silver moonlight through every gap', 'divine chamber at full night — one candle, gold and marble, absolute mythic stillness'],
  },

  moodPools: {
    wake:            ['first temple dawn — the goddess awakening before the world begins', 'sacred pre-dawn stillness in the temple that was built for her', 'the divine morning that precedes everything else by its nature', 'marble and first light and the total quiet of the divine private morning', 'the goddess at her most private in the first temple dawn', 'sacred dawn that acknowledges her without needing to be told'],
    morning_refresh: ['sacred bath ritual — the most devoted self-care imaginable', 'flower petal water and warm candle and complete divine private ease', 'the goddess in the sacred bath — the most beautiful form of self-devotion', 'bath ritual as the act of consecration that begins the divine day', 'warm sacred bathing ease — completely unhurried and completely divine', 'the morning bath as the goddess\'s most private and most beautiful ritual'],
    getting_dressed: ['divine preparation as sacred ceremony — each piece placed with intention', 'gold and silk being placed on divine skin in the morning ritual', 'the preparation that takes the same time it takes — not rushed, never rushed', 'dressing as devotion — each piece of gold, each fold of silk, intentional', 'the divine chamber morning as the most beautiful dressing ritual in existence', 'preparing for divinity — the silk and gold making visible what was always true'],
    breakfast:       ['morning offering as devotion — the altar ritual as the first act of power', 'sacred garden morning ease — flowering trees and warm light and divine private calm', 'the offering as the morning prayer of the goddess — flowers and warmth and intention', 'celestial garden morning — the divine world at its most naturally beautiful', 'altar morning ritual — not performance but genuine sacred intention', 'the goddess in the garden morning as the simplest and most beautiful divine moment'],
    late_morning:    ['throne in column light — divine authority in its most architectural form', 'the marble arcade as the goddess\'s most natural public environment', 'column light and marble and the specific confidence of the divine late morning', 'late morning temple ease — the world arranged correctly for the divine presence', 'throne room in late morning column light — complete and total command', 'the goddess walking the column arcade as the most natural thing in her world'],
    lunch:           ['noon temple authority — the sun at its highest through the open courtyard', 'the noon temple as the most powerful moment in the divine day', 'midday column light and marble and total divine clarity', 'the courtyard at noon as the center of the divine world', 'noon authority in the most architectural space on earth', 'the goddess at noon in full column light — the apex of divine presence'],
    afternoon:       ['oracle afternoon — wisdom given in warm incense and lamp glow', 'sacred garden afternoon as the most beautiful divine leisure', 'the oracle chamber as the private sacred knowledge space of the goddess', 'warm afternoon in the sacred garden — complete divine ease among flowers', 'oracle warmth in the incense atmosphere — sacred and slow and knowing', 'the goddess in the garden afternoon as the most human and most divine simultaneously'],
    reset:           ['pre-evening altar ritual — the pivot between divine day and sacred night', 'the altar reset as the preparation for the deepest divine hours', 'ritual candle-lighting at the altar as the gateway to the evening', 'the pre-evening divine preparation ritual — controlled and completely intentional', 'the altar at dusk as the most sacred threshold in the goddess world', 'evening ritual preparation at the golden altar — between day and the divine night'],
    golden_hour:     ['golden-hour marble courtyard as the most cinematic divine moment', 'amber column light as the temple\'s most beautiful hour', 'the throne in golden-hour light as the apex of all divine aesthetics', 'golden hour flooding the marble as if the architecture always knew this moment would come', 'the most beautiful light in the world in the most beautiful space for it', 'golden-hour divine apotheosis — the goddess in perfect amber light at perfect power'],
    dinner:          ['divine feast candlelight — the throne and the candle and the gold and the dark', 'the goddess at the divine feast as the most powerful evening presence', 'candlelit throne room at feast hour — everything warm and golden and complete', 'the divine feast as the evening\'s most mythic expression of goddess energy', 'warm candlelit divine authority — the most beautiful way to end the divine day', 'feast hour divine presence — warm, deliberate, completely golden and sacred'],
    evening:         ['temple evening candlelight — the goddess at her most intimate divine', 'divine chamber evening — gold altar burning, silk warm in candle light', 'the temple evening as the deepest and most private divine atmosphere', 'candlelit divine evening — warm, golden, completely sacred and private', 'the goddess at evening as the candle burns and the golden altar glows', 'divine evening ease in the warm candlelit sacred interior'],
    night:           ['moonlit marble courtyard — the goddess and the moon in sacred night communion', 'divine chamber at full night in single candle warmth — the most intimate divine', 'the temple at night as the goddess\'s most complete and most private world', 'moonlit marble and the goddess between the columns at the sacred night', 'the single candle at night as the divine world\'s most essential light', 'full night divine presence — moon, candle, marble, gold — completely mythic'],
  },

  cameraPools: {
    wake:            ['85mm divine chamber close at pre-dawn, silk and marble in warm low light', '50mm wide divine chamber at dawn, column light entering from courtyard beyond', '135mm tight face in first temple dawn, marble surface in foreground, light growing behind', '24mm wide marble courtyard pre-dawn, columns silhouetted, subject small and divine', '85mm low from marble floor, subject above, column light arriving from above and behind', '135mm extreme close on gold detail in first dawn light, face soft-focused beyond'],
    morning_refresh: ['85mm sacred bath bird\'s eye, petals around subject, candle bokeh at edge', '50mm wide sacred bath, full marble pool, candles and petals visible throughout', '135mm close on face in bath, flower petals in foreground focus, warm candle beyond', '85mm from pool edge at water level, reflections visible, subject above water line', '35mm wide bathing chamber, marble pool, candles, incense, divine morning all in frame', '135mm extreme close on hands releasing bath water, petals floating around'],
    getting_dressed: ['85mm divine chamber mirror medium, gold and silk in background depth', '50mm wide preparation scene, marble walls, gold, column light entering from above', '135mm close on gold jewellery being placed on bare skin, warm interior behind', '85mm over-shoulder into divine chamber mirror, gold and marble receding behind subject', '35mm wide divine dressing chamber, full room with column light and gold visible', '135mm extreme close on hands fastening gold cuff, skin warm in column light'],
    breakfast:       ['85mm golden altar morning close, flowers and candles in warm foreground bokeh', '50mm wide altar morning scene, offerings, light, subject in full devotional frame', '135mm close on hands at altar, offerings in warm focus, face soft beyond', '24mm wide celestial garden morning, flowers and light and columns framing subject', '85mm from below altar platform, subject above in morning light, offerings around', '50mm garden morning path, flowers in foreground, column arcade in distance, subject between'],
    late_morning:    ['50mm throne room lateral, throne and column light and subject in full authority', '85mm low from throne base, subject elevated in seat, column light behind above', '135mm close on face in throne room column light, marble throne arm in foreground', '24mm wide marble arcade, columns casting long shadows, subject walking through', '85mm column shadow medium, hard shadow-light alternation on subject in arcade', '35mm wide throne room, marble throne, column light, and divine late morning energy all present'],
    lunch:           ['24mm dramatic courtyard noon, subject at centre, sky above through opening', '85mm low noon angle, subject looking up at noon sky, columns framing above', '50mm throne noon medium, direct light from column gap, dramatic noon authority', '135mm close in noon light, full directional column light on face at highest point', '35mm wide noon courtyard, sun at highest point visible above, columns casting short shadows', '85mm from column shadow, subject in pool of noon light, dark column in foreground'],
    afternoon:       ['85mm oracle chamber medium, incense smoke diffusing background in warm lamp light', '50mm wide oracle scene, smoke, lamp, carved seat, subject all in atmospheric frame', '135mm close in oracle light, smoke in close foreground, face warm and partly obscured', '85mm garden afternoon side, flowers in warm foreground, subject in filtered garden light', '35mm wide garden afternoon, flowering trees above, marble path, light filtered through', '135mm extreme close on hands in garden flowers, warm afternoon light on skin detail'],
    golden_hour:     ['24mm dramatic courtyard golden hour, amber flooding the full frame from the west', '85mm backlit throne room golden, amber column light rim on subject from behind', '135mm tight backlit golden close, amber rim, marble column dissolving in gold behind', '50mm wide golden arcade, horizontal amber light crossing every column gap simultaneously', '85mm low courtyard golden angle, subject elevated, amber sky through the open ceiling', '35mm ultra-wide golden temple scene, amber on all surfaces, subject in warm golden flood'],
    dinner:          ['85mm candlelit throne portrait, candle glow key light, deep shadow beyond', '50mm wide divine feast, throne, candles, gold goblet, all in warm candle pool', '135mm close in candlelight, single candle key on face, deep gold shadow behind', '85mm low from throne base, subject in candlelight above, candle warm in foreground', '35mm wide candlelit throne room, feast setting, warm flame light throughout', '135mm extreme close on gold goblet in candlelight, face warm and soft behind'],
    evening:         ['85mm golden altar evening close, candles as key source, deep warm shadow around', '50mm wide divine chamber evening, altar burning, silk, marble all in warm amber', '135mm close on face in evening candle, altar flame visible at frame edge', '85mm from altar angle, subject before the flame, candle light defining everything', '35mm wide evening divine chamber, altar, silk bed, candle pools throughout', '135mm tight on altar flame and hands, face soft in warm flame glow above'],
    night:           ['85mm moonlit courtyard medium, column moonlight side-light, night deep around', '24mm wide courtyard night, moon through column opening above, columns in moonlight', '135mm close in moonlight on marble, silver and white and deep shadow', '50mm divine chamber night, single candle key, everything else in sacred dark', '85mm low night angle, subject between moonlit columns, night sky visible above', '135mm extreme close in moonlight, silver rim light on subject, marble dissolving in dark'],
  },

  lightingPools: {
    wake:            ['pale 5000K first temple dawn through eastern column gap — warm edge on marble', 'pre-dawn 4600K in divine chamber — warm lamp from bedside, marble cool and dark', '4800K first morning light entering temple columns — directional and barely warm', 'pre-dawn divine chamber at 4400K — single lamp warm against dark marble around', '5000K first eastern column light — long horizontal beam, marble catching the edge', 'temple pre-dawn at 4600K — barely any light, warm lamp at bedside the only source'],
    morning_refresh: ['warm 2800K candle multiple at sacred bath rim — warm orange on still water', 'candles at 1800K-2200K creating warm even orange fill on bath surface and steam', 'sacred bath candle at 2500K with 5200K morning window entering — warm-cool contrast', 'oil lamp at 2600K in bath chamber with morning fill entering from narrow window', 'warm candle 2400K in bath — dominant warm source, morning light secondary', 'multiple bath candles at 1800K creating warm equal orange across the pool surface'],
    getting_dressed: ['4800K warm morning column light in divine chamber — directional and flattering', 'clean column morning at 5000K — warm, even, flattering on gold and silk', 'warm 4600K in divine chamber morning — column light from one direction, warm fill', 'temple morning at 5200K with warm lamp fill at 3200K — beautiful mixed light', '4800K column morning light crossing the divine chamber with long warm horizontal beam', 'warm divine chamber morning at 4600K — column key, lamp fill, gold reflecting both'],
    breakfast:       ['altar morning at 3800K oil lamp and 5000K window — altar glow and morning fill', '3600K altar oil lamp in warm morning temple light — flame and window together', 'celestial garden morning at 5200K warm — filtered through flowering canopy', 'garden morning at 5000K warm — directional through trees, warm fill from marble', 'altar candle at 2800K against 5000K morning temple fill — most beautiful altar light', 'garden 4800K warm morning — filtered foliage light, soft and warm throughout'],
    late_morning:    ['column light at 5200K in late morning — strong directional, sharp shadow', 'column arcade at 5000K late morning — alternating light-dark column shadows', 'throne room at 5200K — direct column light entering from high column gap', 'late morning column key at 5400K — maximum directional contrast in the arcade', 'marble courtyard at 5200K late morning — open sky fill with column key', 'throne in column light at 5000K — the definitive architectural directive light'],
    lunch:           ['noon direct 5800K from open courtyard ceiling — the most direct and powerful', 'noon sky 6000K entering through open marble ceiling — vertical, powerful, warm', 'high noon at 5600K through courtyard opening — no shadow direction, direct and golden', 'noon sun at 5800K through column gap — the most powerful column light of the day', 'courtyard noon at 6000K — open sky as the key source, maximum warmth and power', 'marble noon at 5600K — high overhead sun warming every surface simultaneously'],
    afternoon:       ['oracle 2400K oil lamp in afternoon — warm single source in incense atmosphere', 'afternoon oracle at 2600K warm lamp — warm dominance in slightly smoky interior', '4800K garden afternoon warm — filtered foliage light, warm and atmospheric', 'oracle lamp at 2800K with 4200K window — warm oracle in afternoon light', 'garden afternoon at 4600K warm — late flowering light filtered through trees', 'oracle 2400K with incense diffusion — the smoke making the lamp glow atmospheric'],
    reset:           ['pre-evening altar at 3200K warm oil lamp and 3800K last afternoon window', 'altar candle lighting at 2800K against fading 4200K afternoon — the threshold light', '3200K warm altar at pre-evening — the candles dominating as the window fades', 'divine chamber at pre-evening 3600K — warm interior light taking over from day', 'altar preparation at 3000K candle with last 4000K ambient — the most beautiful transition', 'pre-evening temple at 3200K warm — candles lit, day fading, gold warming'],
    golden_hour:     ['2600K golden hour through western column gap — horizontal amber at maximum', '2700K deep amber column light crossing marble courtyard in the richest glow', 'golden-hour at 2800K through temple columns — amber on every surface simultaneously', '2600K horizontal golden — columns casting long orange shadow across marble floor', 'temple golden hour at 2700K — the architecture designed for exactly this light', '2600K deep amber in throne room — the most cinematic divine golden-hour light'],
    dinner:          ['1800K candle sole source in throne room at feast hour — maximum warmth', 'feast candlelight at 2000K — warm orange fire glow as the only source', 'divine chamber at 1800K candle only — the warmest and most intimate', 'candle at 1700K-1900K for feast — deep warm orange, deep dark shadow beyond', 'feast hall 1800K multiple candles — warm layered orange without any cool light', 'throne room at 1900K feast candle — warm, deliberate, completely golden intimate'],
    evening:         ['2200K warm candle in divine chamber — intimate, warm, sacred', 'altar candles at 2000K in evening — warm glow on gold surface and face', 'evening divine chamber at 2400K candle ambient — warm intimate divine', 'altar 1900K against 2600K warm room lamp — warm layers in evening temple', 'divine chamber evening at 2200K — candle primary, lamp secondary, marble warm', 'evening altar candle at 2000K with 2400K room fill — the most beautiful divine evening'],
    night:           ['5800K full moonlight through courtyard opening onto marble — silver and cold', 'moonlight at 6000K through column gaps onto marble floor — dramatic silver', '1600K single candle in divine chamber at full night — warm sole source in dark', 'moonlit courtyard at 5800K — silver moonpath through columns onto white marble', 'divine chamber night at 1800K candle only — the most intimate sacred light', 'full moon at 6000K on marble combined with 1800K candle inside — the most mythic'],
  },

  stylingPools: {
    wardrobe: {
      wake:            ['ivory silk drape barely covering bare skin in first temple dawn', 'white gossamer sleep silk barely held at one shoulder in pre-dawn', 'nothing but white silk pooled on the marble floor below in divine morning ease', 'pale gold silk slip in divine chamber pre-dawn', 'white silk wrap barely tied at the waist in the first temple light', 'cream gossamer over bare skin in the first pale divine morning'],
      morning_refresh: ['completely bare in the sacred bath with only flower petals and water', 'white silk wrap to the sacred bath — nothing beneath', 'sheer white silk transparent at the bath pool edge in morning candle light', 'nothing in the sacred bath — only petals and warm water and divine skin', 'ivory linen wrap after the bath — damp skin visible beneath', 'pale sheer before and after the bath ritual — minimal, divine, completely correct'],
      getting_dressed: ['gold-accented white silk chiton draped with golden cord at waist', 'goddess drape — white or ivory silk with gold at the waist and shoulder', 'flowing gold-belted white silk with gold cuff and laurel or floral crown', 'silk toga draping in ivory with gold leaf detail and bare shoulder', 'ivory silk with gold crown and bracelet — the complete goddess look', 'draped white silk with gold rope belt and gold earrings — divine and complete'],
      breakfast:       ['white silk robe or wrapping in morning at the altar — minimal and sacred', 'light ivory silk in morning garden — simple drape with gold detail', 'white sheer over minimal gold detail in morning offering ritual', 'pale divine morning garden look — white linen with gold at the throat', 'morning garden white silk — loose drape with single gold piece', 'offering ritual look — white or ivory with simple gold and bare feet on marble'],
      late_morning:    ['full goddess column look — draped white silk with gold cord, crown, authority', 'late morning throne look — ivory silk chiton with gold cuff and belt detail', 'column arcade look — white draped silk with laurel crown and gold sandal', 'marble throne look — full ivory and gold goddess draping with crown', 'late morning divine authority look — draped silk with gold belt and column presence', 'white draped goddess with gold collar — the throne room look complete'],
      lunch:           ['noon throne look — white silk and gold at maximum divine authority', 'courtyard noon — minimal white silk with gold — clean and powerful in noon light', 'full divine noon look — white chiton, gold cuff, crown, bare feet on marble', 'noon authority — white draped silk with gold crown and complete divine composure', 'the noon goddess look — pure white and pure gold in the full courtyard light', 'marble noon look — white silk drape with single gold piece — clean and divine'],
      afternoon:       ['oracle look — draped silk in ivory or pale gold with bare shoulders', 'garden afternoon — light silk, flowers, minimal gold — the most natural divine look', 'oracle chamber look — white drape with single gold piece, incense energy', 'garden goddess — floral crown, white silk, bare feet, afternoon ease', 'oracle afternoon look — pale silk with minimal gold, bare and knowing', 'garden afternoon divine ease — loose white silk with flowers in the hair'],
      reset:           ['pre-evening altar look — silk robe in ivory or pale gold with divine composure', 'altar reset look — white silk with additional gold adornment for the evening', 'divine chamber pre-evening — adding the evening crown or heavier gold detail', 'preparing for divine evening — white silk upgraded with gold, crown, collar', 'pre-evening ritual look at altar — adding the gold belt, the crown, the evening pieces', 'altar pre-evening — between day silk and full divine evening — transitional and sacred'],
      golden_hour:     ['golden-hour goddess — gold silk or white with full gold detail in amber light', 'full divine golden look — white with gold glowing in golden-hour column light', 'golden-hour throne look — the most cinematic divine styling moment', 'amber goddess — ivory silk with all gold completely lit in the golden-hour', 'golden-hour white silk drape with full gold crown — the definitive divine look', 'divine apotheosis styling — white and gold in golden-hour column amber'],
      dinner:          ['divine feast look — full ivory silk chiton with gold crown and goblet', 'feast goddess — draped white with all gold in the warm candlelit throne room', 'dinner divine look — full goddess draping with heavy gold crown and gold detail', 'candlelit feast styling — white silk with heavy gold — the most divine evening', 'throne dinner look — the complete goddess in white and gold at the sacred feast', 'divine feast goddess — white, gold, candlelight — the most mythic dinner look'],
      evening:         ['divine chamber evening — silk robe or slip in pale ivory with gentle gold', 'evening temple look — white silk with minimal gold in warm candle glow', 'evening altar look — pale silk with gold — between full day and night', 'candlelit evening goddess — ivory slip and minimal gold in the warm candle chamber', 'divine chamber evening ease — pale silk with single gold piece in warm amber', 'temple evening — the reduced look in candle warmth — white and simple and divine'],
      night:           ['moonlit goddess — white silk translucent in moonlight between columns', 'nothing but white silk in single candle at night — the most divine final state', 'night divine chamber — ivory silk slip in single candle warmth', 'moonlit courtyard — white silk in full moonlight between marble columns', 'night goddess — white or nothing in warm candle in the divine chamber', 'the final divine night look — white silk and the single candle — complete'],
    },
    details: {
      wake:            ['gold earring catching first temple dawn light', 'silk pooled on marble floor in first light', 'bare foot on cool marble in pre-dawn temple'],
      morning_refresh: ['flower petals floating on still bath water surface', 'candle flame reflected in sacred bath pool', 'wet hair after sacred bath in warm candle light'],
      getting_dressed: ['gold cuff being placed on bare wrist in column light', 'laurel or floral crown being placed in morning divine preparation', 'gold belt being fastened at the waist over white silk draping'],
      breakfast:       ['flowers and fruit arranged at the golden altar in morning', 'hands over altar offering in morning ritual gesture', 'flower petal held in both hands at the altar in morning light'],
      late_morning:    ['hand on marble throne arm in column light', 'gold crown catching column shadow in late morning', 'bare foot on cool marble floor at the throne'],
      lunch:           ['noon light direct on gold crown from above', 'bare feet on marble floor in courtyard noon', 'hands on marble throne arms in direct noon light'],
      afternoon:       ['incense smoke drifting through oracle lamp light', 'flower in hand in celestial garden afternoon', 'hands around oracle lamp in warm afternoon oracle light'],
      reset:           ['candle being lit at golden altar in pre-evening ritual', 'gold crown being adjusted at the altar mirror', 'new flower arrangement being placed at the altar for evening'],
      golden_hour:     ['gold crown in full golden-hour amber column light', 'bare arm with gold cuff in golden-hour column beam', 'white silk translucent in golden-hour backlight at columns'],
      dinner:          ['gold goblet catching candlelight at feast table', 'crown in warm orange candle glow at throne', 'hands around gold goblet in divine feast candlelight'],
      evening:         ['candle flame reflection in gold jewellery at altar', 'altar oil lamp warm glow on bare skin in evening', 'gold earring catching single candle glow in evening chamber'],
      night:           ['moonlight on white silk between columns at night', 'single candle flame in absolute dark divine chamber', 'gold catching moonlight in courtyard at full night'],
    },
    changeMoments: {
      wake:            ['pre-dawn divine silk in the chamber before the sacred day begins', 'the goddess in the first light before the temple rituals'],
      morning_refresh: ['in the sacred bath — undressed, divine, completely in the ritual', 'between sleep and divinity at the sacred bath pool'],
      getting_dressed: ['being draped in silk and gold in the divine chamber — the sacred dressing', 'the goddess putting on her divine form in the morning ritual'],
      breakfast:       ['at the altar in morning silk — between preparation and full divine', 'morning offering look — the transition between bath and throne'],
      late_morning:    ['full divine column look at the throne — the goddess in complete authority', 'marble arcade in full goddess styling — white, gold, column, crown'],
      lunch:           ['noon throne look — full divine at maximum power in noon light', 'courtyard noon goddess — the most direct and powerful divine presence'],
      afternoon:       ['oracle afternoon look — knowing and divine in incense warmth', 'garden goddess afternoon — the most natural and human divine moment'],
      reset:           ['pre-evening altar preparation — upgrading the divine look for the sacred night', 'adding the evening gold and crown at the altar before candlelight'],
      golden_hour:     ['golden-hour divine apotheosis — the complete goddess in amber column light', 'white and gold in the most cinematic temple light of the day'],
      dinner:          ['divine feast goddess in candlelight — the most mythic and complete', 'full candle feast look — white silk and gold crown in orange warmth'],
      evening:         ['divine chamber evening ease — reducing to silk and minimal gold', 'evening altar look in warm candle glow'],
      night:           ['night divine — white silk in moonlight or single candle in the chamber', 'the final divine state — white, still, and completely mythic'],
    },
  },

  sensoryPools: {
    wake:            ['cool marble beneath bare feet in first temple dawn', 'silk against skin in pre-dawn divine quiet', 'the specific stillness of a temple before the day begins'],
    morning_refresh: ['flower petal water warm on bare skin', 'candle warmth in the sacred bath steam', 'sacred oil scent in the morning bathing ritual'],
    getting_dressed: ['gold cool against warm bare skin in morning light', 'silk draping across shoulders in column morning', 'the weight of gold crown placed on the head'],
    breakfast:       ['flower scent at the morning altar', 'garden warmth in the morning flowering light', 'fruit at the morning offering — colour and scent and sacred intention'],
    late_morning:    ['cool marble throne under bare skin in column light', 'marble floor cool under bare feet in the arcade', 'column shadow-light alternation on skin in the arcade'],
    lunch:           ['direct noon warmth from the open courtyard above', 'the specific warmth of noon marble underfoot', 'noon temple light at its most powerful and warm'],
    afternoon:       ['incense smoke warm and aromatic in the oracle chamber', 'garden flower scent in afternoon warmth', 'warm garden light filtered through flowering trees'],
    reset:           ['candle flame warmth close at the altar in pre-evening', 'oil lamp heat at the altar ritual reset', 'gold jewellery cool placed on warm skin at the altar'],
    golden_hour:     ['golden-hour amber warmth through columns on marble and skin', 'the specific warmth of golden-hour temple light', 'gold warming in amber column light — the most beautiful tactile moment'],
    dinner:          ['candle warmth close at the feast table in marble throne room', 'gold goblet cool in both hands in candlelight', 'feast warmth in the candlelit throne room'],
    evening:         ['altar candle warmth close at the divine chamber altar', 'silk warm in candle ambient in the evening chamber', 'oil lamp heat and flower scent in divine chamber evening'],
    night:           ['moonlight silver and cool on marble in the courtyard', 'single candle warmth in absolute dark divine chamber', 'cool marble in full night with the moon above through the open ceiling'],
  },

  socialEnergyPools: {
    wake:            ['completely alone in the divine chamber at sacred dawn', 'the goddess and the marble and the first light — no audience needed'],
    morning_refresh: ['completely private sacred bath ritual — the most personal divine act', 'the sacred bath as total private communion'],
    getting_dressed: ['divine preparation as private sacred ritual', 'the dressing chamber as the most private space in the divine world'],
    breakfast:       ['alone at the altar in morning offering — the goddess and her devotion', 'garden morning as private divine leisure — alone among the flowers'],
    late_morning:    ['the throne as public divine authority — the most visible divine moment', 'the marble arcade as the goddess\'s most majestic public presence'],
    lunch:           ['noon throne as the apex of divine public power', 'the courtyard at noon as the most architecturally public divine moment'],
    afternoon:       ['oracle chamber as the most private sacred knowledge space', 'garden afternoon as divine private leisure'],
    reset:           ['altar pre-evening as private sacred preparation', 'the divine chamber at pre-evening as completely private ritual'],
    golden_hour:     ['golden-hour as the most beautiful public divine moment', 'the column arcade at golden hour as the most visible divine display'],
    dinner:          ['divine feast as the most deliberate divine public moment', 'throne candlelight dinner as intimate powerful presence'],
    evening:         ['divine chamber evening as completely private sacred', 'altar evening as the most private sacred hour of the temple day'],
    night:           ['moonlit courtyard as private and mythic simultaneously', 'divine chamber at night as the most sacred and private final state'],
  },

  atmospherePools: {
    wake:            ['sacred temple pre-dawn — the most stillness any space can hold', 'divine chamber dawn atmosphere — gold barely warm, marble barely lit, completely sacred'],
    morning_refresh: ['sacred bath atmosphere — flower petals, candle, warm water, devotional', 'the most beautiful private bathing atmosphere in any world'],
    getting_dressed: ['divine preparation atmosphere — gold and silk in column morning', 'the morning divine chamber as the most sacred dressing ritual space'],
    breakfast:       ['altar morning offering atmosphere — golden, warm, intentional', 'celestial garden morning — the most naturally beautiful divine atmosphere'],
    late_morning:    ['marble column authority atmosphere — architectural, warm, directional', 'throne room in column light — the most powerful architectural divine atmosphere'],
    lunch:           ['open courtyard noon — the most direct and powerful divine atmosphere', 'the marble throne at noon as the apex of divine atmospheric authority'],
    afternoon:       ['oracle incense atmosphere — warm, atmospheric, sacred knowledge', 'celestial garden afternoon — the most peaceful divine atmosphere'],
    reset:           ['altar candle pre-evening — the pivot threshold in the divine atmosphere', 'divine chamber pre-evening — the atmosphere of divine preparation'],
    golden_hour:     ['golden-hour temple atmosphere — the most cinematic sacred space in any world', 'amber column light flooding marble — the divine world at its most beautiful'],
    dinner:          ['candlelit throne feast — the most mythic divine evening atmosphere', 'divine chamber candlelit evening — warm, sacred, completely mythic'],
    evening:         ['divine chamber candle evening — the most intimate sacred atmosphere', 'altar evening candlelight — gold and flame and divine intimate warmth'],
    night:           ['moonlit marble courtyard — silver, vast, mythic, divine night atmosphere', 'single candle in divine chamber night — the most sacred intimate space possible'],
  },

  propPools: {
    wake:            ['silk draping on carved divine chamber bed', 'gold perfume or oil vessel on bedside', 'marble floor in first divine dawn light'],
    morning_refresh: ['flower petals on sacred bath water', 'candles at bath edge burning', 'sacred oil or vessel near the pool'],
    getting_dressed: ['gold crown or laurel on the preparation surface', 'gold cuff and jewellery being placed', 'white silk draped over the preparation chair'],
    breakfast:       ['flowers and fruit at the golden altar', 'oil lamp burning at the altar', 'gold bowl with offering detail at the altar'],
    late_morning:    ['marble throne with gold detail in column light', 'column shadow on marble floor', 'bare feet on marble floor at throne'],
    lunch:           ['noon light through open marble courtyard above', 'marble floor warm in full noon light', 'gold detail on throne catching noon light'],
    afternoon:       ['incense smoke at oil lamp in oracle chamber', 'flowers in garden afternoon', 'oracle oil lamp in warm afternoon light'],
    reset:           ['altar candle being lit in pre-evening ritual', 'new flower arrangement at the golden altar', 'oil lamp tended at the altar before evening'],
    golden_hour:     ['amber column light on marble floor in golden hour', 'gold crown in golden-hour column light', 'marble column with golden-hour horizontal beam'],
    dinner:          ['gold goblet at divine feast table in candlelight', 'multiple candles at feast in throne room', 'laurel crown in warm feast candlelight'],
    evening:         ['altar oil lamp burning in divine chamber evening', 'silk draped over divine chamber furniture in candlelight', 'gold jewellery on altar surface in evening candle glow'],
    night:           ['single candle in divine chamber at absolute night', 'full moon through open courtyard ceiling above', 'marble column in full moonlight at night'],
  },

  bodyLanguagePools: {
    wake:            ['lying completely still in silk in the divine dawn — owned by the morning', 'rising slowly from the silk-draped bed — every movement ceremonial', 'standing in the chamber doorway looking toward the courtyard — completely composed'],
    morning_refresh: ['completely still in the sacred bath — the most powerful stillness', 'lowering into the bath slowly with both hands at the edge', 'rising from the bath with one hand pressing water from hair — elemental and divine'],
    getting_dressed: ['standing still while silk is draped — allowing the preparation to happen', 'slow deliberate placement of gold jewellery — every piece with intention', 'turning once before the chamber mirror in complete divine composure'],
    breakfast:       ['both hands flat over altar offerings — the devotional gesture of the goddess', 'walking the garden path with flowers in both hands and complete slow ease', 'kneeling at the altar in pure sacred offering posture'],
    late_morning:    ['seated on marble throne with perfect upright authority — one hand on each arm', 'walking the column arcade with slow complete command — owning every step', 'standing between two columns with arms at sides — architectural confidence'],
    lunch:           ['at the throne at noon with perfect seated authority — both hands on arms', 'standing at courtyard centre at noon looking up — the most powerful noon posture', 'walking through column noon shadow-light with slow deliberate pace'],
    afternoon:       ['seated in oracle chair with slightly forward lean and eyes half-closed', 'walking garden path with hands trailing flowers and complete warm ease', 'at oracle lamp holding it with both hands in contemplative divine posture'],
    reset:           ['at the altar with hands pressed together in ritual pre-evening posture', 'lighting candles one by one with slow deliberate movement', 'placing the evening adornment with the same care as the morning'],
    golden_hour:     ['both arms slightly lifted in golden-hour column light — the divine receiving', 'turning slowly in golden-hour courtyard as amber fills the space around', 'on the throne in golden-hour column light — absolute still commanding authority'],
    dinner:          ['seated at throne feast with perfect authority, goblet held in both hands', 'walking through candlelit throne room with slow deliberate divine composure', 'standing at feast table with goblet slightly raised — the divine toast'],
    evening:         ['at altar in evening tending the flame with both hands near the warmth', 'moving through the divine chamber in candlelight with slow deliberate ease', 'reclining on silk in divine chamber in warm candle ambient'],
    night:           ['between two columns in moonlight with arms slightly out — moonlight worship posture', 'completely still in divine chamber in single candle at full night', 'lying on silk in divine chamber with one candle as the only light — the final state'],
  },

  facialExpressionPools: {
    wake:            ['divine pre-dawn expression — the goddess before any performance is required', 'first light face — serene, unhurried, completely at home in divinity', 'sacred dawn expression — still, warm, the temple knowing her'],
    morning_refresh: ['sacred bath expression — eyes half-closed, completely at peace', 'ritual bathing face — the most private and most beautiful divine expression', 'water and flower and candle expression — sensory sacred ease'],
    getting_dressed: ['divine preparation expression — deliberate, composed, becoming', 'the dressing ritual face — focused, warm, completely self-possessed', 'adorned and complete expression — the goddess fully herself'],
    breakfast:       ['offering ritual expression — devotional, warm, genuinely sacred', 'garden morning expression — open, warm, the most human divine moment', 'altar morning face — focused, intentional, present'],
    late_morning:    ['throne authority expression — the most powerful composed divine face', 'column arcade composure — knowing, still, completely commanding', 'divine authority face — serene, absolute, fully present'],
    lunch:           ['noon divine expression — direct, powerful, completely present', 'the throne at noon face — the most direct and commanding divine expression', 'courtyard noon expression — open, direct, sun-facing divine authority'],
    afternoon:       ['oracle knowing expression — the most specific divine face — wisdom and warmth', 'garden afternoon expression — the most gentle and the most human divine moment', 'incense oracle face — partly inward, partly present, completely knowing'],
    dinner:          ['divine feast expression — warm, powerful, the goddess as host of the sacred', 'candlelit throne expression — the most warm and commanding divine evening face', 'feast divine composure — the most complete divine evening expression'],
    evening:         ['divine chamber candle evening expression — intimate, warm, sacred', 'altar evening expression — focused on the flame, warmly inward', 'the most private and warm divine evening expression'],
    night:           ['moonlit divine expression — open, mythic, completely belonging to the night', 'single candle night face — the most intimate and the most sacred', 'divine full night expression — the goddess completely at peace in the dark'],
  },

  handDetailPools: {
    wake:            ['hand pressing flat on cool marble floor in dawn', 'fingers trailing along silk edge of divine chamber bed', 'hand touching the gold oil vessel on the bedside'],
    morning_refresh: ['hands at edge of sacred bath as lowering into water', 'fingers with flower petals floating around in bath', 'pressing both hands through damp hair after sacred bath'],
    getting_dressed: ['both hands fastening the gold cuff in morning light', 'fingers at the crown piece being placed in preparation', 'hands smoothing gold-silk draping over the shoulder'],
    breakfast:       ['both hands flat over altar offerings in devotional gesture', 'fingers holding flower in morning garden light', 'hands placing fruit at the altar in morning ritual'],
    late_morning:    ['one hand resting on marble throne arm in column light', 'hand touching marble column in the arcade', 'fingers trailing marble surface at the throne base'],
    lunch:           ['both hands on marble throne arms at noon authority', 'hand raised to the noon light through the courtyard opening', 'fingers on marble throne arm in direct noon column light'],
    afternoon:       ['both hands around oracle oil lamp in oracle chamber', 'hands in garden flowers in afternoon warmth', 'fingers near incense smoke in oracle chamber light'],
    reset:           ['hands together in ritual altar pre-evening gesture', 'lighting altar candle with deliberate hand movement', 'placing gold crown or piece with care at the pre-evening altar'],
    golden_hour:     ['arms and hands slightly lifted receiving golden-hour column light', 'both hands on marble throne arms in golden-hour light', 'hand raised into horizontal golden-hour column beam'],
    dinner:          ['both hands around gold goblet in candlelight at feast', 'one hand raised with goblet in divine toast gesture', 'hands on feast table in candlelit throne room'],
    evening:         ['both hands near altar flame in evening candle ritual', 'hand at gold jewellery at altar in candle evening', 'fingers trailing silk draping in divine chamber candlelight'],
    night:           ['both hands raised slightly in moonlit courtyard worship posture', 'single hand near candle flame in divine chamber night', 'fingers touching marble column in full moonlight at night'],
  },

  movementEnergyPools: {
    wake:            ['sacred-dawn', 'still', 'ceremonial'],
    morning_refresh: ['ritual', 'water', 'devotional'],
    getting_dressed: ['sacred', 'deliberate', 'adorning'],
    breakfast:       ['offering', 'garden', 'devotional'],
    late_morning:    ['authority', 'column', 'divine'],
    lunch:           ['noon-power', 'direct', 'commanding'],
    afternoon:       ['oracle', 'knowing', 'garden-ease'],
    reset:           ['ritual', 'pivot', 'preparing'],
    golden_hour:     ['amber', 'apotheosis', 'cinematic'],
    dinner:          ['feast', 'candlelit', 'sacred'],
    evening:         ['candle', 'intimate', 'divine'],
    night:           ['moonlit', 'still', 'mythic'],
  },

  transitionPools: {
    human: {
      wake:            ['the divine chamber at first temple dawn — the sacred morning beginning', 'marble and silk and the first light — the goddess waking'],
      morning_refresh: ['the sacred bath ritual — the most devoted self-care in any world', 'flower petals and candle warmth and sacred water'],
      getting_dressed: ['the divine morning preparation — silk and gold and complete becoming', 'being adorned in the divine chamber — the sacred dressing ritual'],
      breakfast:       ['morning offering at the golden altar — devotion as the first act', 'the celestial garden morning — divine nature ease'],
      late_morning:    ['on the marble throne in column light — the goddess at full authority', 'the column arcade in late morning — divine presence in motion'],
      lunch:           ['noon courtyard — the goddess at maximum divine power', 'the throne at noon in direct column light — apex of divinity'],
      afternoon:       ['oracle chamber — the goddess as the source of wisdom', 'celestial garden — the divine at ease among flowers'],
      reset:           ['golden altar pre-evening — the sacred day pivoting to the sacred night', 'candle lighting at the altar — the divine evening beginning'],
      golden_hour:     ['golden-hour column light — the most cinematic divine moment of all', 'amber flooding the marble temple — the apotheosis of divine beauty'],
      dinner:          ['divine feast by candlelight — the goddess at the sacred table', 'throne room candlelit feast — the most mythic evening in the divine world'],
      evening:         ['divine chamber evening — candle, gold, silk, intimate sacred', 'altar candle in the evening temple — the goddess in private warmth'],
      night:           ['moonlit marble courtyard — the goddess and the moon and the columns', 'single candle in divine chamber at full night — the most sacred final state'],
    },
  },

  narrativeIntentPools: {
    wake:            ['the divine morning as the sacred beginning of the mythic day', 'marble and silk and dawn — the goddess before the world requires her'],
    morning_refresh: ['the sacred bath as the most devoted ritual of the divine morning', 'flower petals and warm water — the goddess consecrating herself'],
    getting_dressed: ['adorning in silk and gold as the sacred act of becoming fully divine', 'the morning preparation that makes the invisible visible'],
    breakfast:       ['the morning offering as devotion — the goddess giving before taking', 'celestial garden morning as the divine world at its most natural'],
    late_morning:    ['the marble throne in column light as the divine authority at its most complete', 'the column arcade as the most architectural expression of goddess power'],
    lunch:           ['noon divine authority — the sun highest, the goddess most visible', 'the courtyard at noon as the centre of the divine world'],
    afternoon:       ['the oracle as the goddess in her role as sacred knowledge source', 'celestial garden as the divine in her most natural and peaceful form'],
    reset:           ['the altar pre-evening as the sacred pivot from day to the divine night', 'ritual preparation at the golden altar as the gateway to the evening'],
    golden_hour:     ['golden-hour column light as the most cinematic divine apotheosis', 'amber flooding marble as the temple acknowledging her in its most beautiful way'],
    dinner:          ['the divine feast by candlelight as the most mythic goddess evening', 'throne room candlelight as the divine world at its most warm and powerful'],
    evening:         ['divine chamber evening as the sacred intimate close of the mythic day', 'altar candle in the evening as the goddess in her most private divine'],
    night:           ['moonlit marble as the divine world\'s most complete and mythic atmosphere', 'single candle at full night as the goddess at her most sacred and most true'],
  },

  fallbackRules: {
    pacingProfile: { wake: 'slow', morning_refresh: 'slow', getting_dressed: 'slow', breakfast: 'slow', late_morning: 'slow', lunch: 'medium', afternoon: 'slow', reset: 'slow', golden_hour: 'slow', dinner: 'slow', evening: 'slow', night: 'slow' },
    repetitionBreakers: { avoidBackToBackSameLocation: true, avoidBackToBackSameLightingStyle: true, encourageWardrobeEvolution: true },
    worldDefaults: { allowSceneGroupFallbackToPhasePools: true, allowSubLocationFallbackToWorldPools: true, preferSceneGroupsWhenPresent: true },
  },

  exclusions: {
    premium: ['modern or contemporary settings', 'urban environments', 'performance or stage energy', 'casual or athletic clothing'],
    hard: ['daylight office or public settings', 'modern architecture', 'busy social settings', 'anything that breaks the mythic divine aesthetic'],
  },

  routeRules: {
    worldIdentity: ['every setting is marble, gold, silk, column light, or candlelight — always mythic, always divine, never modern', 'she does not perform divinity — she is divinity, and the temple confirms it'],
    humanFlow: ['the day moves from sacred dawn through bath ritual through divine authority through oracle knowledge to golden-hour apotheosis and candlelit feast night', 'every phase is a ceremony'],
    styling: ['white and ivory silk with gold jewellery only — no other colour palette', 'gold crown, gold cuff, gold collar, bare feet on marble — these are the signatures'],
    atmosphere: ['column light, candle, oil lamp, moonlight on marble only — always warm and architectural', 'the world is mythic antiquity — no modern element ever enters the frame'],
  },
}
