export const STORY_WORLD_LATEX_QUEEN = {
  id: 'latex-queen',
  name: 'Latex Queen',
  description:
    'A cinematic world of high-shine darkness — latex and vinyl in strong directional light, the body as both sculpture and weapon, fetish fashion elevated to art, the deliberately provocative made cinematically beautiful.',

  geography: { country: 'private interior / dark editorial', region: 'dark studio, private suite, editorial dark set, latex dressing room' },

  identity: {
    archetype: 'latex queen — fetish fashion editorial',
    vibe: ['latex and vinyl as editorial fashion art', 'the body as sculpture in high-shine material', 'deliberate provocation made cinematically beautiful', 'fashion as power and identity', 'high-shine darkness as the defining aesthetic'],
    tone: ['powerful', 'editorial', 'dark', 'deliberate', 'commanding', 'cinematic', 'high-fashion'],
    persona: ['commands every room she enters wearing latex', 'understands that high-shine darkness is the most powerful fashion statement', 'makes fetish fashion into editorial art', 'the most deliberately powerful and beautiful presence in any setting'],
  },

  phaseOrder: ['wake', 'morning_refresh', 'getting_dressed', 'breakfast', 'late_morning', 'lunch', 'afternoon', 'reset', 'golden_hour', 'dinner', 'evening', 'night'],

  phases: {
    wake:            { label: 'Wake',            timeWindows: ['dark bedroom morning before the latex world', 'private morning before the editorial day'],          pacing: 'slow',   subLocations: ['dark-latex-bedroom', 'morning-private'] },
    morning_refresh: { label: 'Morning Refresh', timeWindows: ['dark bathroom morning ritual', 'pre-latex preparation morning'],                                    pacing: 'slow',   subLocations: ['dark-bathroom-latex', 'vanity-latex'] },
    getting_dressed: { label: 'Getting Dressed', timeWindows: ['latex dressing ritual — the most deliberate transformation', 'applying the latex in the dressing room'],    pacing: 'slow',   subLocations: ['latex-dressing-room', 'full-mirror-latex'] },
    breakfast:       { label: 'Breakfast',       timeWindows: ['dark interior morning before the editorial day', 'pre-shoot morning in dark interior'],              pacing: 'slow',   subLocations: ['dark-interior-morning', 'morning-private'] },
    late_morning:    { label: 'Late Morning',    timeWindows: ['editorial studio setup in controlled light', 'the shoot beginning in dramatic studio environment'],  pacing: 'medium', subLocations: ['editorial-studio-dark', 'studio-setup'] },
    lunch:           { label: 'Lunch',           timeWindows: ['between editorial sets in the dark studio', 'studio break in controlled environment'],               pacing: 'slow',   subLocations: ['dark-studio-lounge', 'editorial-studio-dark'] },
    afternoon:       { label: 'Afternoon',       timeWindows: ['editorial peak in dramatic studio light', 'the latex editorial at full controlled power'],            pacing: 'medium', subLocations: ['editorial-studio-dark', 'dramatic-latex-set'] },
    reset:           { label: 'Reset',           timeWindows: ['latex refinement between editorial sets', 'the look being perfected between shots'],                 pacing: 'slow',   subLocations: ['vanity-latex', 'latex-dressing-room'] },
    golden_hour:     { label: 'Golden Hour',     timeWindows: ['dramatic high-contrast lighting at editorial peak', 'the most powerful latex editorial moment'],      pacing: 'slow',   subLocations: ['dramatic-latex-set', 'editorial-studio-dark'] },
    dinner:          { label: 'Dinner',          timeWindows: ['dark editorial or event evening in latex', 'the latex queen at her most visible and powerful'],      pacing: 'slow',   subLocations: ['dark-event-space', 'latex-social-evening'] },
    evening:         { label: 'Evening',         timeWindows: ['dark intimate evening in latex', 'private or semi-private latex evening'],                           pacing: 'slow',   subLocations: ['dark-interior-evening', 'dark-latex-bedroom'] },
    night:           { label: 'Night',           timeWindows: ['private dark night after the latex world', 'the queen alone after the editorial day'],               pacing: 'slow',   subLocations: ['dark-latex-bedroom', 'morning-private'] },
  },

  locations: [
    'dark private bedroom before the latex transformation', 'latex dressing room — the transformation ritual',
    'dark editorial studio in strong directional light', 'the body in latex in dramatic controlled lighting',
    'dark event space in evening in latex', 'full-length mirror in latex look',
    'dark intimate evening interior in latex', 'the editorial peak — high-shine latex in dramatic light',
  ],

  subLocations: {
    'dark-latex-bedroom': {
      id: 'dark-latex-bedroom', name: 'Dark Bedroom', mapAnchor: 'dark private bedroom before the latex world',
      category: 'private-dark',
      bestPhases: ['wake', 'evening', 'night'],
      overlays: ['dark private bedroom before the latex day', 'warm amber or dark intimate morning before the transformation', 'the queen private before the latex world'],
      locations: ['dark private bedroom in warm morning before latex', 'the queen private before the editorial latex day', 'dark intimate bedroom in warm amber morning'],
    },
    'morning-private': {
      id: 'morning-private', name: 'Private Morning', mapAnchor: 'private morning before the latex editorial',
      category: 'private-morning',
      bestPhases: ['wake', 'breakfast', 'night'],
      overlays: ['the private person before the latex editorial identity', 'warm intimate morning before the transformation', 'the real private morning before the latex power'],
      locations: ['private morning before the latex editorial world', 'the real intimate morning before the transformation', 'warm private interior before the latex aesthetic'],
    },
    'dark-bathroom-latex': {
      id: 'dark-bathroom-latex', name: 'Dark Bathroom', mapAnchor: 'dark bathroom before latex preparation',
      category: 'self-care-dark',
      bestPhases: ['morning_refresh'],
      overlays: ['dark bathroom in warm morning before latex preparation', 'the body being prepared for the latex look', 'pre-transformation morning ritual in dark bathroom'],
      locations: ['dark bathroom morning ritual before the latex transformation', 'pre-latex preparation in warm dark bathroom', 'dark bathroom self-care before the editorial'],
    },
    'vanity-latex': {
      id: 'vanity-latex', name: 'Latex Vanity', mapAnchor: 'vanity for latex preparation',
      category: 'preparation-latex',
      bestPhases: ['morning_refresh', 'reset'],
      overlays: ['vanity with latex polishing and preparation detail', 'the latex beauty ritual — polishing and dressing', 'editorial beauty preparation for the latex look'],
      locations: ['latex preparation vanity with polish and detail', 'editorial vanity ritual for the latex queen aesthetic', 'the latex polishing and beauty preparation zone'],
    },
    'latex-dressing-room': {
      id: 'latex-dressing-room', name: 'Latex Dressing Room', mapAnchor: 'dressing room for latex transformation',
      category: 'transformation',
      bestPhases: ['getting_dressed', 'reset'],
      overlays: ['the dressing room where latex is applied and transformation happens', 'the latex being put on — the most deliberate fashion ritual', 'the transformation from person to latex queen'],
      locations: ['the latex dressing room transformation', 'the application of latex — the most deliberate fashion act', 'the transformation ritual in the latex dressing room'],
    },
    'full-mirror-latex': {
      id: 'full-mirror-latex', name: 'Full Mirror Latex', mapAnchor: 'full-length mirror in latex look',
      category: 'reflection-latex',
      bestPhases: ['getting_dressed'],
      overlays: ['full-length mirror with the latex look complete', 'the latex queen at the mirror — assessment and power', 'the complete latex look reflected in full-length mirror'],
      locations: ['full-length mirror with complete latex look', 'the latex queen mirror assessment', 'high-shine latex in full-length mirror reflection'],
    },
    'dark-interior-morning': {
      id: 'dark-interior-morning', name: 'Dark Morning Interior', mapAnchor: 'dark interior morning',
      category: 'dark-morning',
      bestPhases: ['breakfast'],
      overlays: ['dark interior morning before the editorial day', 'the private morning in dark warm interior before the shoot', 'pre-editorial morning in dark intimate setting'],
      locations: ['dark interior morning before the latex editorial day', 'warm dark private morning before the transformation', 'dark intimate morning before the editorial world'],
    },
    'editorial-studio-dark': {
      id: 'editorial-studio-dark', name: 'Dark Editorial Studio', mapAnchor: 'dark editorial studio',
      category: 'editorial-latex',
      bestPhases: ['late_morning', 'lunch', 'afternoon', 'golden_hour'],
      overlays: ['dark editorial studio with dramatic directional lighting', 'the latex editorial in controlled dramatic studio light', 'high-contrast dark studio for the latex aesthetic'],
      locations: ['dark editorial studio with strong directional light', 'the latex editorial studio in dramatic controlled lighting', 'high-contrast dark studio for the high-shine latex look'],
    },
    'studio-setup': {
      id: 'studio-setup', name: 'Studio Setup', mapAnchor: 'editorial studio being set up',
      category: 'pre-shoot',
      bestPhases: ['late_morning'],
      overlays: ['the editorial studio being set up for the latex shoot', 'lights and equipment being positioned for the latex editorial', 'pre-shoot studio preparation energy'],
      locations: ['editorial studio setup for the latex shoot', 'the latex shoot being prepared in dark studio', 'pre-shoot studio energy for the latex editorial'],
    },
    'dark-studio-lounge': {
      id: 'dark-studio-lounge', name: 'Dark Studio Lounge', mapAnchor: 'lounge between editorial sets',
      category: 'between-sets',
      bestPhases: ['lunch'],
      overlays: ['the studio lounge between latex editorial sets', 'between-shot rest in dark studio lounge', 'the latex queen resting between editorial sets'],
      locations: ['dark studio lounge between latex editorial sets', 'between-shot break in the studio lounge area', 'rest between latex editorial shots in dark lounge'],
    },
    'dramatic-latex-set': {
      id: 'dramatic-latex-set', name: 'Dramatic Latex Set', mapAnchor: 'the peak latex editorial set',
      category: 'editorial-peak',
      bestPhases: ['afternoon', 'golden_hour'],
      overlays: ['the peak latex editorial moment in dramatic controlled light', 'high-shine latex in the most powerful editorial setting', 'the most cinematically powerful latex editorial moment'],
      locations: ['dramatic latex editorial set at peak lighting moment', 'the most powerful editorial moment for the latex look', 'high-shine latex in maximum editorial dramatic light'],
    },
    'dark-event-space': {
      id: 'dark-event-space', name: 'Dark Event Space', mapAnchor: 'dark event venue in latex',
      category: 'social-latex',
      bestPhases: ['dinner'],
      overlays: ['dark luxury event space with the latex queen visible', 'the latex look at a dark luxury event or opening', 'the most powerful social moment for the latex aesthetic'],
      locations: ['dark luxury event space in the latex look', 'the latex queen at a dark luxury event', 'dark social setting with the latex aesthetic at its most visible'],
    },
    'latex-social-evening': {
      id: 'latex-social-evening', name: 'Latex Evening', mapAnchor: 'social evening in latex',
      category: 'evening-latex',
      bestPhases: ['dinner'],
      overlays: ['latex at a dark social evening event', 'the queen in latex in warm dark social setting', 'latex at its most social and visible evening moment'],
      locations: ['dark social evening in latex look', 'the latex queen at a dark luxury evening event', 'warm dark social setting with complete latex aesthetic'],
    },
    'dark-interior-evening': {
      id: 'dark-interior-evening', name: 'Dark Interior Evening', mapAnchor: 'dark intimate evening in latex',
      category: 'evening-private',
      bestPhases: ['evening'],
      overlays: ['dark warm intimate evening interior in the latex look', 'the latex queen in private or semi-private evening dark interior', 'warm dark evening in the complete latex aesthetic'],
      locations: ['dark intimate evening interior in the latex look', 'warm dark private evening in latex', 'the latex queen in dark warm evening interior'],
    },
  },

  sceneVariants: {
    wake: ['the private dark morning before the latex transformation — warm and real', 'the queen before the latex world — private and still in dark bedroom warmth'],
    morning_refresh: ['dark bathroom morning ritual before the latex preparation', 'the pre-transformation self-care in dark warm bathroom'],
    getting_dressed: ['the latex application — the most deliberate fashion transformation ritual', 'applying latex in the dressing room — the defining ritual of this world'],
    breakfast: ['dark interior morning before the editorial day begins', 'the private morning in dark warm interior before the shoot'],
    late_morning: ['the editorial studio being set up for the latex shoot', 'the beginning of the latex editorial in dark studio setting'],
    lunch: ['between editorial sets in the dark studio lounge', 'the latex queen resting between shots in studio setting'],
    afternoon: ['the latex editorial at full dramatic peak in controlled studio light', 'high-shine latex in maximum editorial dramatic moment'],
    reset: ['latex refinement between sets at the editorial vanity', 'the look being perfected between shots'],
    golden_hour: ['the most powerful latex editorial moment — peak dramatic lighting', 'high-shine latex in the strongest most cinematic editorial light'],
    dinner: ['the latex queen at a dark luxury event — the most visible social moment', 'latex at a dark luxury event in the evening'],
    evening: ['dark intimate evening in the latex look', 'the queen in latex in warm dark private evening interior'],
    night: ['the private dark bedroom after the latex editorial day', 'the real person returning to private dark warmth after the power day'],
  },

  actionPools: {
    wake: ['waking in dark warm bedroom before the latex day', 'the private morning before the latex transformation begins', 'the queen private before the editorial world'],
    morning_refresh: ['dark bathroom morning ritual before the latex preparation', 'the body being prepared for the latex transformation', 'pre-latex self-care in dark warm bathroom'],
    getting_dressed: ['the deliberate application of latex in the dressing room', 'putting on the latex — the most powerful fashion transformation', 'the latex queen ritual — dressing in the most deliberate fashion act'],
    breakfast: ['dark interior morning before the editorial begins', 'the private pre-shoot morning in dark warm interior', 'the real person before the latex editorial day'],
    late_morning: ['the editorial studio being set up and prepared', 'arriving at the dark studio for the latex editorial', 'the pre-shoot studio energy building for the latex look'],
    lunch: ['resting between latex editorial sets in the studio lounge', 'the break between shots in dark studio setting', 'the latex queen between editorial sets'],
    afternoon: ['the latex editorial at dramatic peak in controlled studio light', 'high-shine latex in the most powerful editorial set', 'the defining editorial moment for the latex aesthetic'],
    reset: ['latex vanity refinement between editorial sets', 'perfecting the look between shots at the editorial vanity', 'the latex preparation being refined and polished'],
    golden_hour: ['the most powerful latex editorial moment in peak dramatic lighting', 'high-shine latex in the strongest most beautiful editorial light', 'the defining peak editorial moment in the latex world'],
    dinner: ['the latex queen visible at a dark luxury event in the complete look', 'the latex at its most social in dark luxury evening setting', 'the most visible and powerful social moment for the latex aesthetic'],
    evening: ['the dark intimate evening in the latex look', 'the queen in latex in warm dark private evening interior', 'dark warm intimate evening in the complete latex aesthetic'],
    night: ['returning to private dark bedroom warmth after the latex day', 'the private quiet after the most powerful editorial day', 'the real person in dark private warmth after the latex world'],
  },

  environmentPools: {
    wake: ['dark private bedroom in warm intimate morning before the transformation', 'the queen private in dark warm morning before the latex day', 'dark intimate bedroom before the editorial world begins'],
    morning_refresh: ['dark warm bathroom before the latex preparation', 'pre-transformation bathroom in dark intimate morning', 'the body being prepared in dark warm bathroom'],
    getting_dressed: ['the latex dressing room — the most deliberate transformation space', 'the transformation from person to latex queen in the dressing room', 'the dressing room where the latex aesthetic is assembled'],
    breakfast: ['dark warm interior before the editorial begins', 'the private pre-shoot morning in dark intimate setting', 'dark warm morning interior before the latex world'],
    late_morning: ['dark editorial studio with dramatic controlled lighting being set up', 'pre-shoot studio environment with latex world preparing', 'dark studio space being configured for the latex editorial'],
    lunch: ['dark studio lounge between editorial latex sets', 'the between-shots rest zone in dark studio', 'the studio lounge in dark setting between editorial moments'],
    afternoon: ['dark editorial studio at dramatic peak light for latex editorial', 'the most powerful editorial latex set in controlled dramatic light', 'high-contrast dark studio with latex at editorial peak'],
    reset: ['latex vanity in the studio between sets', 'the editorial refinement vanity in dark studio setting', 'the between-sets vanity for the latex look perfection'],
    golden_hour: ['the dramatic editorial peak set with maximum controlled lighting on latex', 'the most cinematic editorial latex moment in peak light', 'high-shine latex in the most powerful dramatic editorial setting'],
    dinner: ['dark luxury event space with the latex queen at her most visible', 'dark social evening venue with the complete latex aesthetic', 'dark luxury social setting for the latex queen evening'],
    evening: ['dark warm intimate evening interior in the latex look', 'the latex queen in dark warm private evening setting', 'intimate dark evening in the complete latex aesthetic'],
    night: ['dark private bedroom returning to warmth after the latex day', 'the private dark bedroom in quiet after the editorial', 'dark intimate private bedroom at the end of the latex world day'],
  },

  moodPools: {
    wake: ['private dark morning before the power — real and warm', 'the queen before the latex world — intimate and dark', 'the real private morning before the most powerful aesthetic'],
    morning_refresh: ['the body being prepared — pre-transformation ritual calm', 'the quiet deliberate morning preparation before the latex', 'pre-transformation warmth and self-care energy'],
    getting_dressed: ['the latex application — the most deliberate fashion power ritual', 'putting on power and sculpture and darkness simultaneously', 'the transformation into the latex queen — the defining ritual'],
    breakfast: ['dark private morning before the editorial — real and warm', 'the private person before the latex power begins', 'dark intimate morning energy before the transformation'],
    late_morning: ['studio setup energy — the latex editorial world assembling', 'the building editorial energy in dark studio preparation', 'pre-shoot controlled dark energy building'],
    lunch: ['between-sets editorial dark calm', 'the rest between the most powerful editorial moments', 'dark studio quiet between the latex peaks'],
    afternoon: ['the latex editorial at full dramatic cinematic peak', 'high-shine in strong directional light — the defining latex editorial', 'the most powerful editorial aesthetic of the latex queen at maximum'],
    reset: ['the refinement between peaks — polishing and perfecting the latex', 'editorial dark refinement energy between sets', 'the deliberate perfection ritual between editorial moments'],
    golden_hour: ['the most powerful latex editorial moment — maximum cinematic contrast', 'high-shine latex in the strongest most beautiful editorial light', 'the peak editorial aesthetic — the defining latex queen image'],
    dinner: ['the latex queen at maximum social power in dark luxury', 'the most visible and commanding social moment for the latex aesthetic', 'dark luxury event energy with the latex look at its most powerful'],
    evening: ['intimate dark evening in the latex aesthetic', 'the warm dark intimate evening power of the latex queen', 'dark warm evening in the complete latex identity'],
    night: ['the private quiet after the most powerful day — real and warm', 'the real person returning to dark private warmth after the latex editorial', 'dark private intimacy after the power day'],
  },

  cameraPools: {
    wake: ['85mm low angle in dark bedroom, warm amber barely visible, deep shadow around subject', '135mm dark morning close, single warm source barely defining edge in dark room'],
    morning_refresh: ['85mm dark bathroom mirror close, reflection at same focal plane in dark setting', '50mm vanity preparation mid shot, dark background with controlled warm fill'],
    getting_dressed: ['85mm latex dressing transformation close, deliberate latex application in controlled light', '50mm full-length latex mirror framing, complete look in strong directional light'],
    breakfast: ['85mm dark interior morning medium, warm private morning depth behind', '135mm dark morning close, intimate morning warmth as soft background'],
    late_morning: ['50mm wide dark studio setup, editorial preparation behind subject', '85mm studio arrival medium, dark editorial environment assembling behind'],
    lunch: ['85mm dark studio lounge between sets, controlled ambient behind subject', '135mm between-set close, dark studio quiet around subject'],
    afternoon: ['85mm latex editorial strong directional, hard single key light defining latex texture', '50mm wide dramatic latex editorial, dark studio with strong key light filling background'],
    reset: ['85mm vanity refinement close, controlled studio light on latex preparation', '135mm latex polish detail, strong light on high-shine surface'],
    golden_hour: ['135mm peak latex editorial close, maximum contrast directional key light defining shine', '85mm dramatic editorial latex, dark studio with single strong key defining every surface'],
    dinner: ['85mm dark event medium, warm dark luxury ambient behind latex look', '50mm latex social setting, dark event venue depth behind subject'],
    evening: ['85mm dark intimate evening in latex, warm dark interior depth behind', '135mm dark evening intimate close, warm lamp as sole source'],
    night: ['135mm dark bedroom night close-up, single warm source barely visible', '85mm deep dark private night, minimal ambient defining edge in darkness'],
  },

  lightingPools: {
    wake: ['warm 2000K single amber source in dark bedroom — deep shadow, barely visible edge', 'near-dark bedroom with single warm lamp barely touching the subject'],
    morning_refresh: ['warm 2800K dark bathroom with single warm source for pre-transformation ritual', 'controlled warm dark bathroom light for the pre-latex preparation'],
    getting_dressed: ['strong directional 4500K on latex dressing room — the high-shine of latex needs hard directional to show texture', 'dramatic single key light at 3500K in dressing room defining latex surface and shine'],
    breakfast: ['warm 2600K dark morning interior before the editorial', 'single warm 2800K lamp in dark intimate morning interior'],
    late_morning: ['5000K studio setup light — even overhead fill as dark studio prepares for the latex editorial', 'controlled studio setup in pre-shoot dark studio environment'],
    lunch: ['warm 3000K dark studio lounge between sets — controlled and dim', 'between-set dark studio ambient at controlled warm level'],
    afternoon: ['hard 4800K single directional key on latex surface — maximum shine and texture definition', 'strong directional at 45 degrees on latex, deep black shadow beyond, no fill — maximum contrast for shine'],
    reset: ['controlled 3200K vanity light for latex refinement between sets', 'warm editorial studio vanity light for latex preparation between shots'],
    golden_hour: ['maximum contrast editorial — hard 5000K key, no fill, black background — the peak latex aesthetic', 'single strong key light defining every millimetre of high-shine latex surface against absolute black'],
    dinner: ['warm 2800K dark luxury event lighting on latex look in social setting', 'dark warm 2600K event ambient with latex at its most visible in warm dark luxury'],
    evening: ['warm 2400K dark intimate evening — single warm source in dark interior', 'low intimate warm 2200K in dark evening interior for the latex look'],
    night: ['near-dark 1900K barely-visible single warm in deep dark bedroom', 'almost total dark with single barely-perceptible warm edge at night'],
  },

  stylingPools: {
    wardrobe: {
      wake: ['dark private morning before the latex — warm and private', 'the real person before the latex identity — minimal dark morning', 'intimate dark morning in private styling'],
      morning_refresh: ['dark robe or nothing in dark pre-latex bathroom', 'pre-transformation intimate morning styling', 'the body being prepared for the latex'],
      getting_dressed: ['the latex application — the defining fashion act', 'black latex complete look being assembled', 'latex bodysuit or latex dress being applied and polished'],
      breakfast: ['dark morning private styling before the editorial begins', 'intimate dark morning interior look', 'the real person pre-transformation in dark morning'],
      late_morning: ['partial or full latex in editorial studio setup', 'the latex world assembling in studio preparation', 'latex being prepared in dark studio light'],
      lunch: ['latex between sets or covered for the between-shot break', 'the queen resting between editorial peaks', 'between-set latex styling in studio lounge'],
      afternoon: ['complete latex at editorial peak — full high-shine look', 'the complete latex editorial look in maximum dramatic light', 'the defining latex editorial styling moment'],
      reset: ['latex being polished and refined between sets', 'the latex look being perfected at the editorial vanity', 'between-set latex refinement in controlled studio'],
      golden_hour: ['complete peak latex look in maximum editorial dramatic light', 'the most powerful latex editorial styling moment at golden peak', 'high-shine complete latex at maximum editorial power'],
      dinner: ['complete latex look at dark luxury evening event', 'the latex queen at social evening in complete high-shine look', 'the most social powerful latex styling moment'],
      evening: ['latex in dark warm intimate evening setting', 'complete latex look in dark private or semi-private evening', 'the queen in latex in dark warm evening interior'],
      night: ['private dark styling after the latex is removed', 'the real person returning to private dark morning look', 'warm dark intimate private night after the latex day'],
    },
    details: {
      wake: ['dark private intimate morning detail', 'the real person before the latex — natural and warm', 'dark bedroom private morning detail'],
      morning_refresh: ['pre-transformation body prep detail', 'the skin being prepared for the latex application', 'dark bathroom pre-latex self-care detail'],
      getting_dressed: ['the latex being applied — the most deliberately beautiful fashion detail', 'high-shine latex surface and application detail', 'the transformation detail — latex and the body becoming one'],
      breakfast: ['dark private morning detail before the editorial', 'warm intimate pre-shoot morning detail', 'the real person morning detail before the transformation'],
      late_morning: ['studio preparation detail in dark editorial environment', 'pre-shoot latex preparation in studio', 'editorial dark studio preparation detail'],
      lunch: ['between-set detail in dark studio lounge', 'the queen resting detail between editorial peaks', 'dark studio between-shot detail'],
      afternoon: ['high-shine latex surface in strong directional light — the defining detail', 'latex texture and shine in maximum editorial light', 'the most powerful visual detail — latex in dramatic studio lighting'],
      reset: ['latex polish and refinement detail at the editorial vanity', 'the latex being perfected between sets detail', 'editorial vanity refinement detail for the latex look'],
      golden_hour: ['peak editorial latex detail — maximum shine in maximum contrast', 'the most powerful latex fashion detail at editorial peak', 'high-shine latex surface at its most dramatically beautiful'],
      dinner: ['complete latex look at dark luxury event — the most social detail', 'the latex queen visible in dark luxury evening detail', 'dark luxury event latex detail'],
      evening: ['latex in dark warm evening intimate detail', 'the queen in latex in dark warm evening detail', 'intimate dark evening latex detail'],
      night: ['private quiet after the latex — warm dark intimate detail', 'the real person returning to private warmth after the latex detail', 'dark intimate private night after the editorial day'],
    },
    changeMoments: {
      wake: ['the private morning before the latex identity begins', 'the real person warm and dark before the transformation'],
      morning_refresh: ['between private and latex — in dark bathroom preparation', 'pre-transformation in dark bathroom warmth'],
      getting_dressed: ['the latex application — the most deliberate fashion transformation', 'the transformation ritual in the dressing room'],
      breakfast: ['private dark morning before the editorial latex world', 'real intimate dark morning before the power begins'],
      late_morning: ['the latex being assembled in studio preparation', 'partial or full latex in studio setup'],
      lunch: ['between editorial sets — latex maintained or partially covered', 'the between-set moment in dark studio'],
      afternoon: ['complete latex at editorial peak', 'the full high-shine editorial latex look'],
      reset: ['latex being refined between sets', 'the perfection ritual between editorial peaks'],
      golden_hour: ['complete peak latex in maximum editorial dramatic moment', 'the most powerful latex editorial styling at peak'],
      dinner: ['complete latex at dark luxury social event', 'the latex queen at maximum social power'],
      evening: ['latex in dark intimate evening setting', 'the queen in latex in warm dark evening'],
      night: ['returning to private dark warmth after the latex', 'the real person after the most powerful fashion identity'],
    },
  },

  sensoryPools: {
    wake: ['warm dark bedroom before the latex world — real and private', 'the intimate warm morning before the transformation begins', 'dark private bedroom warmth before the latex power'],
    morning_refresh: ['the body being prepared for the latex — warm water and preparation', 'the deliberate pre-transformation body preparation ritual', 'warm dark bathroom before the application begins'],
    getting_dressed: ['the latex going on — the physical sensation of the most powerful fashion material', 'the tight second-skin of latex against the prepared body', 'the transformation physical sensation — latex shaping the body into sculpture'],
    breakfast: ['dark warm interior before the editorial — intimate and real', 'the private pre-shoot morning sensory in dark warm setting', 'warm dark interior morning before the power begins'],
    late_morning: ['dark studio energy building for the latex editorial — lights and preparation', 'the studio being configured for the most powerful editorial aesthetic', 'pre-shoot dark studio sensory as the editorial world assembles'],
    lunch: ['between editorial sets — the dark studio quiet and the latex still on the body', 'the rest sensory between peaks in dark studio setting', 'dark studio lounge quiet between the most powerful moments'],
    afternoon: ['the strong directional light hitting latex surface — the defining sensory', 'high-shine in hard directional light — the most powerful visual sensory', 'the complete latex editorial sensory — material and light in maximum contrast'],
    reset: ['the latex being polished and refined — the deliberate maintenance sensory', 'between-set latex preparation — the careful maintenance of the most powerful aesthetic', 'the deliberate latex refinement between peaks'],
    golden_hour: ['maximum editorial contrast — latex in the strongest most beautiful light', 'the peak editorial sensory — high-shine in maximum dramatic light', 'the most powerful visual sensory of the latex queen world'],
    dinner: ['dark warm luxury event with the complete latex look — visibility and power', 'the latex at a dark luxury event — the social power sensory', 'the most powerful social sensory of the latex aesthetic'],
    evening: ['warm dark evening in the latex look — intimate and powerful', 'the latex in dark warm intimate evening setting', 'dark warm evening with the complete latex aesthetic'],
    night: ['returning to warm dark private bedroom after the latex day', 'the private warmth after the most powerful fashion day', 'dark private intimacy after the latex world'],
  },

  socialEnergyPools: {
    wake: ['completely private dark morning before the latex identity', 'the queen before the world — real and intimate in dark morning'],
    morning_refresh: ['private pre-transformation ritual in dark bathroom', 'alone in dark bathroom preparing the body for the latex'],
    getting_dressed: ['the deliberate private transformation ritual in the dressing room', 'the latex application — the private most deliberate fashion act'],
    breakfast: ['private dark morning before the editorial begins', 'alone in dark warm morning before the latex world'],
    late_morning: ['editorial studio setup — professional creative collaboration', 'the editorial team assembling the latex world in studio'],
    lunch: ['between-set studio break — professional but private', 'the creative team rest between editorial peaks'],
    afternoon: ['editorial shoot — focused professional creative energy', 'the latex editorial at maximum controlled creative energy'],
    reset: ['between-set refinement — professional editorial ritual', 'the latex vanity refinement in editorial professional setting'],
    golden_hour: ['editorial peak — maximum creative professional energy on the latex', 'the defining editorial moment — the creative team at maximum power'],
    dinner: ['dark luxury event — the latex queen maximally visible and social', 'the most powerful social moment — the latex queen at a dark luxury event'],
    evening: ['dark intimate evening — private or semi-private in latex', 'the queen in the latex in dark warm intimate setting'],
    night: ['completely private dark bedroom after the latex world', 'the real person alone in dark warmth after the editorial power day'],
  },

  atmospherePools: {
    wake: ['dark warm intimate morning before the latex transformation', 'the private morning atmosphere before the most powerful fashion identity', 'dark bedroom quiet before the editorial latex world begins'],
    morning_refresh: ['dark bathroom pre-transformation atmosphere', 'the quiet deliberate morning preparation atmosphere', 'warm dark bathroom before the latex application begins'],
    getting_dressed: ['the dressing room transformation atmosphere — the deliberate fashion ritual', 'the most powerful fashion transformation atmosphere — latex application', 'the dressing room energy as the latex identity is assembled'],
    breakfast: ['dark intimate morning atmosphere before the editorial', 'warm private pre-shoot atmosphere in dark interior', 'the calm dark morning before the editorial power begins'],
    late_morning: ['dark studio preparation atmosphere — the editorial world assembling', 'pre-shoot dark studio energy building for the latex look', 'controlled dark studio atmosphere in editorial preparation'],
    lunch: ['dark studio between-sets calm atmosphere', 'the rest atmosphere between the most powerful editorial moments', 'dark studio quiet in the between-set break'],
    afternoon: ['peak editorial latex atmosphere — the most powerful dark studio energy', 'the dramatic controlled studio atmosphere at full editorial latex peak', 'maximum editorial dark studio atmosphere for the defining latex moment'],
    reset: ['between-set refinement atmosphere — precise and controlled', 'the editorial dark studio refinement energy', 'deliberate precision atmosphere between the latex peaks'],
    golden_hour: ['maximum contrast editorial atmosphere — the peak latex aesthetic', 'the most powerful dark studio editorial atmosphere at the latex climax', 'dramatic controlled peak editorial atmosphere for the defining image'],
    dinner: ['dark luxury event atmosphere with the latex queen commanding', 'warm dark luxury social atmosphere in the complete latex look', 'the most powerful social atmosphere for the latex aesthetic'],
    evening: ['dark warm intimate evening atmosphere in latex', 'the intimate dark evening energy in the complete latex look', 'warm dark intimate evening atmosphere for the latex queen'],
    night: ['dark private bedroom atmosphere after the most powerful day', 'warm intimate dark night after the latex editorial world', 'the private quiet dark atmosphere after the transformation'],
  },

  propPools: {
    wake: ['dark bedroom warm intimate props before the latex', 'warm morning detail in dark bedroom before the editorial', 'the private morning props before the latex world'],
    morning_refresh: ['dark bathroom body preparation props', 'pre-latex preparation detail in dark bathroom', 'warm dark bathroom morning props before transformation'],
    getting_dressed: ['latex garment and latex polish and application tools', 'the most powerful fashion prop — the latex itself being applied', 'dressing room transformation props for the latex application'],
    breakfast: ['dark morning interior props before the editorial', 'warm intimate morning detail before the shoot', 'dark interior morning props'],
    late_morning: ['dark studio setup props — lights and equipment being positioned', 'editorial studio preparation props in dark setting', 'studio configuration props for the latex editorial'],
    lunch: ['between-set dark studio lounge props', 'studio rest props between latex editorial peaks', 'the dark studio between-shot break props'],
    afternoon: ['latex in strong directional light — the defining editorial prop', 'the latex surface in maximum dramatic light is itself the prop', 'dark studio dramatic lighting equipment and the latex body'],
    reset: ['latex polish and preparation tools at editorial vanity', 'between-set refinement props in dark studio', 'editorial vanity latex refinement props'],
    golden_hour: ['peak editorial setup — lighting and latex at maximum dramatic moment', 'the most powerful editorial props — light and latex at peak', 'dramatic studio lighting on high-shine latex surface'],
    dinner: ['dark luxury event props with the latex queen visible', 'warm dark luxury event detail around the latex look', 'dark social event props for the latex evening'],
    evening: ['dark warm intimate evening props in latex look', 'the evening latex setting props in dark warm interior', 'intimate dark evening detail props in latex'],
    night: ['warm dark bedroom after the editorial — private night props', 'the return to private dark bedroom after the latex day', 'dark intimate private night props after the editorial'],
  },

  bodyLanguagePools: {
    wake: ['private warm dark morning body language before the latex', 'the real intimate person before the transformation body language', 'dark bedroom quiet morning body ease'],
    morning_refresh: ['pre-transformation body preparation posture in dark bathroom', 'the body being prepared for the latex — private and deliberate', 'dark bathroom morning preparation body language'],
    getting_dressed: ['the deliberate latex application body language — the most powerful fashion posture', 'the transformation into latex queen body language', 'the latex going on — the body becoming sculpture body language'],
    breakfast: ['dark private morning body language before the editorial', 'intimate warm morning body ease before the transformation', 'the real person in dark morning body ease'],
    late_morning: ['editorial studio preparation body language — professional and building', 'the pre-shoot studio energy building body language', 'controlled professional body language in dark editorial setup'],
    lunch: ['between-set dark studio rest body language', 'the queen resting between editorial peaks body ease', 'dark studio between-shot break body language'],
    afternoon: ['latex editorial peak body language — the most powerful and sculptural', 'high-shine latex in strong directional light — the defining body language', 'the complete latex editorial body posture at maximum power'],
    reset: ['deliberate between-set latex refinement posture', 'the careful preparation body language at editorial vanity', 'between-peak precision refinement body language'],
    golden_hour: ['maximum editorial latex power body language at peak dramatic light', 'the most powerful defining body language — the latex queen in peak editorial', 'peak editorial latex posture at the most cinematic dramatic moment'],
    dinner: ['latex queen commanding social event body language', 'the most powerful social body language in the complete latex look', 'commanding dark event space body language in latex'],
    evening: ['dark intimate evening body language in the latex look', 'the warm dark evening intimate body ease in latex', 'dark intimate evening latex body language'],
    night: ['private quiet dark bedroom body ease after the editorial', 'the real person body language in dark private warmth after the latex', 'warm dark intimate night body ease after the most powerful day'],
  },

  facialExpressionPools: {
    wake: ['warm private dark morning expression before the transformation', 'the real intimate person expression before the latex world', 'dark quiet morning expression in warm private bedroom'],
    morning_refresh: ['deliberate pre-transformation expression in dark bathroom', 'the quiet preparation expression before the latex is applied', 'dark bathroom pre-latex preparation expression'],
    getting_dressed: ['the transformation expression — becoming the latex queen', 'the deliberate powerful expression as the latex goes on', 'the dressing room mirror expression as the latex identity assembles'],
    breakfast: ['dark intimate morning expression before the editorial', 'the real person expression in dark warm morning before the shoot', 'private dark morning expression before the editorial world'],
    late_morning: ['editorial studio professional building expression', 'the pre-shoot studio expression building toward the peak', 'controlled professional expression in dark editorial setup'],
    lunch: ['between-set quiet dark studio expression', 'the queen resting expression between editorial peaks', 'dark studio between-shot break expression'],
    afternoon: ['the peak editorial latex expression — the most powerful commanding and sculptural', 'high-shine latex in strong directional light expression at maximum', 'the most powerful editorial expression — the latex queen at peak'],
    reset: ['precise refinement expression between editorial sets', 'the between-peak latex queen refinement expression', 'deliberate precise preparation expression at editorial vanity'],
    golden_hour: ['maximum editorial peak expression — the defining latex queen image', 'the most powerful defining expression — peak editorial dramatic latex', 'the latex queen at maximum editorial power expression'],
    dinner: ['commanding social power expression in complete latex at dark event', 'the most powerful social expression — latex queen at dark luxury event', 'dark luxury event commanding expression in the latex look'],
    evening: ['dark warm intimate evening expression in the latex look', 'the warm intimate dark evening expression of the latex queen', 'dark intimate evening latex expression'],
    night: ['returning to private warm expression after the latex editorial day', 'the real person expression in dark private warmth after the power', 'warm intimate dark night expression after the most powerful fashion day'],
  },

  handDetailPools: {
    wake: ['hand on warm dark bedroom surface in morning before the latex', 'fingers near intimate morning detail before the transformation', 'dark warm bedroom morning hand detail'],
    morning_refresh: ['hand on dark bathroom counter in pre-transformation morning', 'fingers in pre-latex preparation in dark bathroom', 'dark bathroom pre-transformation hand detail'],
    getting_dressed: ['hands applying latex — the most powerful fashion hand detail in this world', 'fingers polishing and smoothing latex onto the body', 'the latex application hands — the defining transformation hand detail'],
    breakfast: ['hand near dark warm morning interior detail', 'fingers on intimate private morning prop', 'dark morning interior hand before the editorial'],
    late_morning: ['hand near studio setup equipment in dark editorial preparation', 'fingers at dark editorial studio preparation detail', 'studio setup hand in dark environment'],
    lunch: ['hand near between-set dark studio lounge detail', 'fingers on dark studio rest break detail', 'dark studio lounge hand between editorial peaks'],
    afternoon: ['hands in latex — the most powerful editorial hand detail', 'latex-covered hands in strong directional editorial light', 'the latex surface hand in maximum dramatic studio light'],
    reset: ['hands with latex polish at editorial vanity', 'fingers refining latex at the between-set vanity', 'the latex refinement hands at editorial vanity'],
    golden_hour: ['latex hands in peak editorial dramatic light — the defining visual', 'the most powerful editorial hand detail — latex in maximum dramatic contrast', 'high-shine latex on hands in peak editorial moment'],
    dinner: ['latex-gloved or uncovered hands at dark luxury event', 'the latex queen hand at dark luxury social event', 'hand detail at dark luxury event in complete latex look'],
    evening: ['dark intimate evening hand in latex look', 'hand near warm dark intimate evening detail in latex', 'dark evening warm intimate hand in the latex aesthetic'],
    night: ['hand on warm dark bedroom surface after the editorial', 'fingers near private dark night detail after the latex day', 'warm dark private night hand after the transformation'],
  },

  movementEnergyPools: {
    wake: ['private', 'warm-dark', 'before'],
    morning_refresh: ['deliberate', 'preparation', 'quiet'],
    getting_dressed: ['transforming', 'deliberate', 'powerful'],
    breakfast: ['intimate', 'dark-morning', 'real'],
    late_morning: ['building', 'professional', 'editorial'],
    lunch: ['rest', 'between', 'quiet'],
    afternoon: ['peak', 'sculptural', 'editorial'],
    reset: ['precise', 'refining', 'controlled'],
    golden_hour: ['maximum', 'dramatic', 'peak'],
    dinner: ['commanding', 'visible', 'social'],
    evening: ['intimate', 'dark-warm', 'latex'],
    night: ['private', 'returning', 'warm'],
  },

  transitionPools: {
    human: {
      wake: ['the private dark morning before the latex transformation', 'the queen waking real and warm before the power begins'],
      morning_refresh: ['dark bathroom pre-transformation ritual beginning', 'the body being prepared for the most deliberate fashion act'],
      getting_dressed: ['the latex transformation beginning — the most deliberate fashion ritual', 'applying the latex — the defining act of this world'],
      breakfast: ['dark private morning before the editorial latex world', 'the real intimate person before the transformation begins'],
      late_morning: ['the dark editorial studio being assembled for the latex shoot', 'the latex editorial world beginning in dark studio'],
      lunch: ['between editorial peaks in the dark studio', 'the queen resting between the most powerful editorial moments'],
      afternoon: ['the latex editorial at full dramatic peak', 'the defining editorial moment — latex in maximum dramatic light'],
      reset: ['latex refinement between the most powerful moments', 'perfecting the look between editorial peaks'],
      golden_hour: ['the peak editorial latex moment — maximum contrast and power', 'the defining image of the latex queen at maximum editorial'],
      dinner: ['the latex queen commanding at dark luxury event', 'the most visible and powerful social moment for the latex aesthetic'],
      evening: ['dark warm intimate evening in the complete latex look', 'the queen in latex in dark warm evening interior'],
      night: ['returning to private dark warmth after the latex world', 'the real intimate person after the most powerful fashion day'],
    },
  },

  narrativeIntentPools: {
    wake: ['the private real person before the most powerful fashion identity begins — intimate and real in dark morning', 'the transformation has not yet happened — the latex queen is still the real warm person'],
    morning_refresh: ['the body being deliberately prepared for the most intentional fashion transformation', 'the pre-transformation ritual as the foundation of the latex editorial identity'],
    getting_dressed: ['the latex application as the most deliberate and powerful fashion act in the world', 'the transformation from person to sculpture — the defining ritual of the latex queen identity'],
    breakfast: ['the private dark morning as the hidden human foundation of the most powerful fashion aesthetic', 'the real person in dark warm intimacy before the transformation'],
    late_morning: ['the dark editorial world assembling for the latex peak — controlled creative energy', 'the studio preparing for the most powerful editorial aesthetic'],
    lunch: ['the hidden between-peaks private moment of the most public editorial identity', 'the rest between the most powerful fashion moments'],
    afternoon: ['the latex in maximum editorial dramatic light — the defining visual of the entire world', 'high-shine in strong directional light — the complete expression of the latex queen identity'],
    reset: ['the deliberate perfection ritual between the peaks — the artisanal care of the most powerful fashion', 'the latex maintenance as the editorial craft of the latex queen world'],
    golden_hour: ['the peak editorial moment — the most powerful image of the latex queen world', 'maximum contrast editorial — the defining fashion image at the top of the dramatic aesthetic'],
    dinner: ['the latex queen at maximum social visibility — the fashion as the most powerful social statement', 'the complete latex aesthetic in the most powerful social context'],
    evening: ['the intimate dark warmth of the latex look in private evening — powerful and intimate simultaneously', 'the latex in warm dark intimate setting — the world at its most privately powerful'],
    night: ['the return to the real private person after the most powerful fashion identity', 'the dark private warmth after the transformation — the real human behind the latex queen'],
  },

  fallbackRules: {
    pacingProfile: { wake: 'slow', morning_refresh: 'slow', getting_dressed: 'slow', breakfast: 'slow', late_morning: 'medium', lunch: 'slow', afternoon: 'medium', reset: 'slow', golden_hour: 'slow', dinner: 'slow', evening: 'slow', night: 'slow' },
    repetitionBreakers: { avoidBackToBackSameLocation: true, avoidBackToBackSameLightingStyle: true, encourageWardrobeEvolution: true },
    worldDefaults: { allowSceneGroupFallbackToPhasePools: true, allowSubLocationFallbackToWorldPools: true, preferSceneGroupsWhenPresent: true },
  },

  exclusions: {
    premium: ['cheap or non-editorial latex settings', 'non-cinematic or poorly lit latex', 'latex without the correct preparation and polish', 'low-quality or casual latex aesthetic'],
    hard: ['outdoor daylight settings', 'wellness or clean aesthetic', 'beach or nature settings', 'corporate or office environments'],
  },

  routeRules: {
    worldIdentity: ['the latex queen world must feel dark, powerful, editorial, and cinematically deliberate — the latex is always the hero', 'strong directional light on high-shine surface and dark backgrounds are the core visual language'],
    humanFlow: ['the day moves from private dark morning through the transformation ritual into the editorial peak and social power, ending in private dark intimacy', 'the transformation is the narrative center'],
    styling: ['latex is the defining wardrobe element — applied deliberately and maintained throughout the editorial day', 'the transformation from private person to latex queen is the core narrative arc'],
    atmosphere: ['dark backgrounds with strong directional light create the defining latex aesthetic — the material needs contrast to show its power', 'the atmosphere is always dark, controlled, and deliberately cinematic'],
  },
}
