export const STORY_WORLD_LUXURY_LIFE = {
  id: 'luxury-life',
  name: 'Luxury Life',
  description: 'High-status feminine world — penthouse suites, private jets, five-star hotels, yacht decks, beach clubs. Elegance as a default state. Wealth that never needs to announce itself.',
  compatiblePlans: ['Fanvue', 'Unrestricted', 'Premium'],
  defaultPack: 'luxury-lifestyle',
  defaultAgeRange: '28-40',

  subLocations: {
    'penthouse-suite': {
      name: 'Penthouse Suite',
      label: 'Penthouse · Above the City',
      atmosphere: 'Floor-to-ceiling glass, city grid far below, silk sheets, fresh flowers, room service trolley, walk-in wardrobe light, marble bathroom, morning robe at the window',
      lightingBase: 'Soft filtered city light through glass at dawn. 3800-4500K natural window fill. Golden hour turns the entire city gold through the penthouse glass.',
      sceneGroups: {
        bedroom_morning: { name: 'Bedroom Morning', description: 'Silk sheets, morning robe, city below' },
        bathroom_ritual: { name: 'Bathroom Ritual', description: 'Marble vanity, soaking tub, mirror' },
        living_terrace: { name: 'Terrace & Living', description: 'Open terrace above the city, lounge area' },
      },
    },
    'private-jet': {
      name: 'Private Jet',
      label: 'Private Jet · In Transit',
      atmosphere: 'Cream leather seats, oval windows with cloud light, champagne on a side table, flat-bed cabin at night, silk travel set, reading with city lights far below',
      lightingBase: 'Pure natural window light — cool blue above clouds, warm amber at ground level. No artificial fill. 5500-6500K above cloud line. 2800K cabin interior at night.',
      sceneGroups: {
        cabin_daylight: { name: 'Cabin · Day', description: 'Window seat, cloud light, daytime travel' },
        cabin_night: { name: 'Cabin · Night', description: 'Night flight, city lights below, flat bed' },
        arrival_departure: { name: 'Tarmac', description: 'Steps, tarmac arrival, boarding alone' },
      },
    },
    'five-star-hotel': {
      name: 'Five Star Hotel',
      label: 'Hotel · Grand Property',
      atmosphere: 'Marble lobby, fresh white linens, oversized bath, room service under a silver dome, pool terrace at noon, concierge corridors, gold accents throughout',
      lightingBase: 'Hotel warm white — 3000-3500K throughout. Lobby grand chandeliers. Room soft bedside glow. Pool hard Mediterranean noon light.',
      sceneGroups: {
        hotel_room: { name: 'Hotel Room', description: 'Suite interior, linens, morning light' },
        hotel_pool: { name: 'Pool & Terrace', description: 'Hotel pool, sun lounger, terrace' },
        hotel_lobby: { name: 'Lobby', description: 'Grand lobby arrival, marble floor' },
      },
    },
    'yacht-deck': {
      name: 'Yacht Deck',
      label: 'Superyacht · Open Water',
      atmosphere: 'Sun deck with ocean horizon, bow lounge in Mediterranean blue, crew serving lunch, swim platform at water level, flybridge above everything, sunset from the stern',
      lightingBase: 'Open ocean light — hard direct noon, softening to warm amber by 4pm. Water reflection bounces light upward. 5500-6000K noon, 3200K sunset. No shade except under the overhang.',
      sceneGroups: {
        sun_deck: { name: 'Sun Deck', description: 'Deck lounger, open ocean, midday light' },
        swim_platform: { name: 'Water Level', description: 'Swim platform, sea entry, ocean close' },
        flybridge: { name: 'Flybridge', description: 'Highest deck, full 360 view, champagne' },
      },
    },
    'beach-club': {
      name: 'Beach Club',
      label: 'Beach Club · Côte d\'Azur',
      atmosphere: 'White-cushion sun beds, rosé on ice, crystal Mediterranean water, cabana shade, DJ from 2pm, tanned bodies and designer swimwear, private stretch of sand roped off from public',
      lightingBase: 'Hard Mediterranean summer light. 6000K at noon — bleached and direct. Cool blue sea light in late afternoon. 4200K golden from 5pm.',
      sceneGroups: {
        sun_bed: { name: 'Sun Bed', description: 'Premium sun bed, rosé, white sand' },
        water_edge: { name: 'Water Edge', description: 'Mediterranean water, shallow entry, clarity' },
        cabana: { name: 'Cabana', description: 'Private cabana shade, lounging' },
      },
    },
    'resort-spa': {
      name: 'Resort Spa',
      label: 'Spa · Private Wellness',
      atmosphere: 'Dark stone treatment rooms, warm candlelight, plunge pools, steam room tiles, rooftop hot tub with mountain or ocean view, silk robe on a warm lounger, mineral water and fruit',
      lightingBase: 'Spa dim warm — 2200-2700K throughout. Candles as primary source. Treatment room near darkness with accent glow. Outdoor hot tub in natural twilight.',
      sceneGroups: {
        treatment_room: { name: 'Treatment Room', description: 'Warm dark spa room, table, candles' },
        plunge_pool: { name: 'Plunge Pool', description: 'Cold plunge, mineral pool, stone surround' },
        rooftop_tub: { name: 'Rooftop Hot Tub', description: 'Outdoor hot tub with view at twilight' },
      },
    },
  },

  pools: {
    wake: [
      'penthouse suite at 9am — silk sheets, city already moving far below, light through sheer curtains',
      'private jet flat bed at dawn — oval window showing pink sky and nothing else below',
      'five-star hotel at late morning — white linen, fresh flowers by the bed, coffee arriving',
      'yacht master cabin waking to gentle water movement and open porthole light',
      'beach club villa at 10am — shutters open to the sound of the sea and heat already present',
      'spa resort suite in slow morning — robe on, mineral water on the table, nothing scheduled',
    ],
    morning_refresh: [
      'penthouse marble bathroom — freestanding tub filling, city visible through the window above it',
      'five-star hotel bathroom with walk-in rain shower, white towels, Acqua di Parma on the vanity',
      'yacht bathroom in teak and chrome with porthole showing ocean horizon at face height',
      'spa resort changing room in warm stone with mineral water and herbal steam',
      'hotel suite vanity with full professional lighting and magnifying mirror for morning routine',
      'private jet lavatory in white and chrome — compact luxury at 40,000 feet',
    ],
    getting_dressed: [
      'penthouse walk-in wardrobe — the entire day\'s outfit already planned and laid out the night before',
      'hotel suite bed covered in options — beach club or dinner dress or neither yet',
      'yacht cabin pulling on the white linen set that always photographs perfectly at sea',
      'five-star hotel dressing room with full-length mirror and concierge pressing service',
      'beach club villa changing for the afternoon — minimal, precise, exactly right',
      'spa resort choosing between the silk robe and actually getting dressed — choosing the robe',
    ],
    breakfast: [
      'penthouse terrace — fresh fruit and espresso above the city in morning stillness',
      'private jet breakfast service — white tablecloth, croissant, orange juice from Seville',
      'five-star hotel breakfast room with silver service and morning newspapers in four languages',
      'yacht sun deck — Greek yogurt and berries as the anchor lifts and the sea opens up',
      'beach club early before anyone arrives — sitting with a coffee watching staff set up',
      'spa resort morning — warm herbal tea and light food eaten in complete silence at the window',
    ],
    late_morning: [
      'yacht bow at 11am as the coast appears and the captain suggests anchoring near the village',
      'hotel pool at 11am — first swim, first drink, the day with no agenda',
      'designer shopping district at late morning — the stores just opening, no crowds yet',
      'beach club at late morning when the sun is strong and the first rosé appears',
      'spa terrace in late morning warmth — reading, not thinking, completely still',
      'penthouse working late morning with the city as the only view and complete silence inside',
    ],
    lunch: [
      'beach restaurant on the water with feet on warm wood and grilled fish and local wine',
      'yacht lunch at anchor — crew serving on the stern deck with the sea completely flat',
      'five-star hotel restaurant at noon with white tablecloths and unhurried service',
      'cliffside restaurant above the Mediterranean with a table at the very edge',
      'beach club prime table at 1pm when the music starts and the champagne decision is made',
      'hotel terrace lunch in direct afternoon sun with a parasol and something cold and perfect',
    ],
    afternoon: [
      'yacht sun deck at 3pm — sun at its peak, sea completely blue, no land in any direction',
      'beach club at peak afternoon — bodies, music, heat, rosé, the whole production at full volume',
      'luxury shopping with personal stylist in a private appointment in a closed boutique',
      'hotel pool at 3pm — second swim, reading abandoned, watching the light on the water',
      'spa afternoon — long treatment, full silence, the afternoon simply disappearing',
      'penthouse terrace watching the city from above as the light begins to change',
    ],
    reset: [
      'spa treatment room at 5pm — the day\'s work done and nothing left to decide',
      'yacht flybridge at 5pm as the boat heads back to port with the sun behind and the coast ahead',
      'hotel suite at 5pm — shower, lie down, the evening still to come',
      'beach club cabana as the music slows and the crowd thins and the sea turns darker blue',
      'penthouse bathroom at golden hour — long bath as the city begins to light itself below',
      'private garden at a luxury villa in the last hour of afternoon light before dressing for dinner',
    ],
    golden_hour: [
      'yacht stern at sunset — pink sky, flat sea, champagne, and every horizon available',
      'penthouse terrace at the exact moment the city glass turns gold and the lights begin',
      'clifftop hotel terrace at sunset with the sea below turning deep orange and the first stars',
      'beach club empty sun beds and long shadows and the best light of the entire day',
      'spa rooftop hot tub at golden hour — steam rising, sky turning, complete privacy',
      'hotel balcony at sunset above a square where the whole old town turns the colour of honey',
    ],
    dinner: [
      'Michelin table above a harbour with the boats below and nothing rushed and nothing predictable',
      'yacht stern dinner under stars with the anchor down in a private bay and candles on the table',
      'hotel dining room with a tasting menu and a sommelier and two hours simply disappearing',
      'private beach dinner — table on the sand, fire nearby, the sea dark and close',
      'rooftop restaurant at the highest point of the city as it lights up below the table',
      'intimate dinner at a local place nobody in the hotel would know about — discovered, not booked',
    ],
    evening: [
      'yacht moored in a harbour town — lights of restaurants, sound of the water, slow evening walk',
      'hotel bar after dinner — one cocktail, the room beginning to feel like a full life',
      'casino at 10pm — dressed exactly right, arriving exactly late, playing exactly enough',
      'rooftop bar with the whole city electric below and the night with no particular plan',
      'penthouse late evening — city glittering, champagne opened for no specific reason',
      'beach club evening party beginning as the sun-stained evening transforms into full night',
    ],
    night: [
      'penthouse bedroom at 1am — city still lit below, the day completely finished, sheets cold and clean',
      'yacht cabin at midnight — gentle rocking, porthole showing stars and nothing else',
      'hotel suite after a long dinner — everything ordered, everything exactly right, sleep inevitable',
      'casino late — playing something small, not caring either way, the night at its most honest',
      'hotel corridor at 2am — the whole property silent, key in the door, the room waiting',
      'yacht stern at 1am when everyone else has gone to bed and the sea is completely black',
    ],
  },

  cameraPool: [
    '85mm f/1.4 at the window — subject backlit, city or sea soft behind, luxury in the negative space',
    '35mm wide at deck level showing ocean to horizon and subject at centre',
    '50mm f/1.8 close in the marble bathroom — soft warm light, intimacy without intrusion',
    '24mm on the tarmac showing the full aircraft and subject walking toward it',
    '135mm telephoto compression — yacht, sea, subject stacked from the tender',
    '50mm at the dinner table — candlelight, crystal, the scene saying everything without words',
  ],

  lightingPool: [
    'Mediterranean noon — bleached, direct, shadows hard, the kind of light that shows everything',
    'Golden hour at sea — no land, no buildings, pure amber sky and flat water reflection',
    'Hotel room soft warm — bedside lamp, curtains half-drawn, 3000K private luxury',
    'Yacht flybridge at magic hour — pink sky, blue water, the best light of the day',
    'Spa candlelight — 2200K warm, darkness filling the room, just the form and the flame',
    'Penthouse window at dawn — city in silhouette below, first light catching the glass',
    'Dinner candlelight — multiple candles, no overhead, crystal scattering points across the scene',
    'Beach club afternoon — white sand reflection bouncing light upward from below',
  ],

  wardrobePool: [
    'white linen set — the universal yacht and Mediterranean language of confident wealth',
    'silk slip dress in ivory or champagne — minimal, intentional, the opposite of trying',
    'structured blazer with nothing underneath — power dressing that needs no occasion',
    'designer swimwear with pareo — the beach club uniform executed perfectly',
    'long silk robe over nothing — the hotel suite morning as its own complete aesthetic',
    'evening dress in deep navy or black — simple, expensive, unforgettable',
    'cashmere travel set — the private jet look that manages to seem effortless',
    'jewellery as the entire outfit — the minimal silk and maximum gold strategy',
    'tailored trousers and structured blouse — lunch on the yacht, nothing casual about it',
  ],

  moodPool: [
    'unhurried wealth — nothing to prove, nowhere to be, complete',
    'quiet confidence — the woman who booked the best room and never had to ask about the price',
    'effortless elevation — doing ordinary things in extraordinary places with complete ease',
    'private pleasure — the luxury that\'s only for her, not performed for anyone else',
    'slow tension — the day building toward something beautiful with complete patience',
    'sovereign calm — her world moves at her pace and not one second faster',
  ],
}
