export const STORY_WORLD_NEODECO = {
  id: 'neodeco',
  name: 'NeoDeco',
  description:
    'Art deco reimagined — sleek brass, leather banquettes, geometric luxury, 1920s meets now. The most beautiful interior design era on earth, pulled into the present with a modern edge.',

  geography: { country: 'metropolitan luxury', region: 'art deco city world' },

  identity: {
    archetype: 'deco goddess',
    vibe: ['brass and geometric pattern', 'leather banquette in jewel-toned room', 'mirrored surfaces catching warm light', 'the jazz bar that never closed', 'structured luxury with a dark edge'],
    tone: ['architectural', 'glamorous', 'geometric', 'warm-dark', 'sultry', 'editorial', 'cinematic'],
    persona: ['completely at home in the most architecturally perfect rooms on earth', 'the deco interior recognises her as the correct occupant', 'dressed like the building was designed for her specifically', 'glamour that understands its own geometry'],
  },

  phaseOrder: ['wake', 'morning_refresh', 'getting_dressed', 'breakfast', 'late_morning', 'lunch', 'afternoon', 'reset', 'golden_hour', 'dinner', 'evening', 'night'],

  phases: {
    wake:            { label: 'Deco Dawn',         timeWindows: ['morning deco suite light', 'brass and mirror morning'],                 pacing: 'slow',   subLocations: ['deco-suite', 'brass-vanity'] },
    morning_refresh: { label: 'Vanity Ritual',     timeWindows: ['morning vanity light', 'brass mirror morning'],                        pacing: 'slow',   subLocations: ['brass-vanity', 'deco-suite'] },
    getting_dressed: { label: 'Deco Dressing',     timeWindows: ['morning deco interior', 'warm geometric morning light'],               pacing: 'slow',   subLocations: ['deco-suite', 'mirrored-corridor'] },
    breakfast:       { label: 'Deco Breakfast',    timeWindows: ['art deco dining morning', 'warm geometric interior morning'],          pacing: 'slow',   subLocations: ['geometric-lounge', 'deco-suite'] },
    late_morning:    { label: 'Lounge Hour',       timeWindows: ['late morning geometric lounge', 'brass and leather late morning'],     pacing: 'slow',   subLocations: ['geometric-lounge', 'mirrored-corridor'] },
    lunch:           { label: 'Deco Dining',       timeWindows: ['deco dining room noon', 'geometric noon interior'],                    pacing: 'medium', subLocations: ['leather-banquette', 'geometric-lounge'] },
    afternoon:       { label: 'Afternoon Lounge',  timeWindows: ['afternoon geometric lounge', 'deco club car afternoon'],               pacing: 'slow',   subLocations: ['leather-banquette', 'geometric-lounge'] },
    reset:           { label: 'Mirror Reset',      timeWindows: ['pre-evening vanity', 'brass mirror preparation evening'],              pacing: 'slow',   subLocations: ['brass-vanity', 'deco-suite'] },
    golden_hour:     { label: 'Deco Golden',       timeWindows: ['golden-hour brass and mirror', 'deco golden interior'],               pacing: 'slow',   subLocations: ['art-deco-bar', 'geometric-lounge', 'mirrored-corridor'] },
    dinner:          { label: 'Jazz Dinner',       timeWindows: ['deco bar evening', 'jazz dinner hour'],                               pacing: 'slow',   subLocations: ['art-deco-bar', 'leather-banquette'] },
    evening:         { label: 'Bar Night',         timeWindows: ['deco bar night interior', 'warm dark evening in the deco bar'],       pacing: 'slow',   subLocations: ['art-deco-bar', 'leather-banquette'] },
    night:           { label: 'Deep Deco',         timeWindows: ['deep deco night interior', 'bar closing hour'],                       pacing: 'slow',   subLocations: ['art-deco-bar', 'deco-suite'] },
  },

  locations: [
    'art deco suite with brass fixtures and geometric window light', 'brass vanity mirror with warm bulb ring',
    'geometric lounge with leather chairs and patterned floor', 'leather banquette in jewel-toned dining room',
    'mirrored corridor with brass detail and warm light', 'art deco bar with backlit bottles and geometric detail',
    'deco club car or private rail carriage interior', 'grand lobby with geometric tile and brass elevator',
  ],

  subLocations: {
    'deco-suite': {
      id: 'deco-suite', name: 'Deco Suite', mapAnchor: 'art deco hotel suite',
      category: 'luxury-private',
      bestPhases: ['wake', 'getting_dressed', 'breakfast'],
      overlays: ['geometric window light on brass fixtures', 'rich jewel-tone walls', 'structured luxury furniture', 'deco pattern detail throughout'],
      locations: ['art deco suite bedroom with brass fixtures and geometric light', 'deco suite sitting area with jewel-tone walls', 'deco suite with structured furniture and morning light'],
    },
    'brass-vanity': {
      id: 'brass-vanity', name: 'Brass Vanity', mapAnchor: 'art deco vanity table with brass mirror',
      category: 'preparation-ritual',
      bestPhases: ['wake', 'morning_refresh', 'reset'],
      overlays: ['warm brass mirror ring light', 'vanity with perfume and jewellery arranged', 'geometric mirror surround', 'warm 3200K bulb vanity glow'],
      locations: ['brass-framed vanity with bulb ring and jewellery', 'deco vanity mirror with warm ring light', 'art deco preparation mirror in warm interior'],
    },
    'geometric-lounge': {
      id: 'geometric-lounge', name: 'Geometric Lounge', mapAnchor: 'art deco lounge with geometric pattern',
      category: 'social-luxury',
      bestPhases: ['breakfast', 'late_morning', 'lunch', 'afternoon'],
      overlays: ['geometric tile or carpet pattern', 'leather chairs and velvet accents', 'brass lamp and side table', 'structured deco lounge energy'],
      locations: ['geometric lounge with leather and brass', 'deco lounge with patterned floor and velvet chair', 'art deco sitting room with geometric detail throughout'],
    },
    'leather-banquette': {
      id: 'leather-banquette', name: 'Leather Banquette', mapAnchor: 'deco dining leather banquette',
      category: 'dining-luxury',
      bestPhases: ['lunch', 'afternoon', 'dinner'],
      overlays: ['deep leather banquette seating', 'jewel-tone walls behind', 'brass table lamp', 'deco dining room atmosphere'],
      locations: ['leather banquette in jewel-tone deco dining room', 'deep green or burgundy leather banquette with brass table lamp', 'deco restaurant booth in warm interior light'],
    },
    'mirrored-corridor': {
      id: 'mirrored-corridor', name: 'Mirrored Corridor', mapAnchor: 'deco mirrored hallway',
      category: 'transitional-drama',
      bestPhases: ['getting_dressed', 'late_morning', 'golden_hour'],
      overlays: ['mirrored walls reflecting infinitely', 'brass fixture detail', 'warm geometric corridor light', 'multiple reflections of subject'],
      locations: ['mirrored corridor with brass detail and warm light', 'deco hallway with infinite mirror reflection', 'mirrored hotel corridor in warm deco light'],
    },
    'art-deco-bar': {
      id: 'art-deco-bar', name: 'Art Deco Bar', mapAnchor: 'deco cocktail bar',
      category: 'glamour-social',
      bestPhases: ['golden_hour', 'dinner', 'evening', 'night'],
      overlays: ['backlit bar with amber bottle glow', 'geometric bar front detail', 'brass bar rail and stool', 'warm dark deco bar atmosphere'],
      locations: ['art deco bar with backlit bottles and geometric detail', 'deco cocktail bar with brass fixtures', 'dark warm deco bar interior with amber bottle light'],
    },
  },

  sceneVariants: {
    wake:            ['lying in the deco suite in morning light with brass and geometric pattern around', 'the brass vanity in morning — warm bulb ring and the deco world waking up'],
    morning_refresh: ['morning ritual at the brass vanity with ring light and jewellery arranged', 'the brass mirror morning — the most glamorous ordinary morning ritual'],
    getting_dressed: ['dressing in the deco suite with geometric light and brass fixtures around', 'in the mirrored corridor — the deco hall making her infinite'],
    breakfast:       ['breakfast in the geometric lounge with leather chairs and morning brass light', 'deco suite morning with room service and geometric window light'],
    late_morning:    ['in the geometric lounge in late morning — leather and brass and the deco world at rest', 'mirrored corridor in late morning light — infinite deco reflections'],
    lunch:           ['leather banquette at the deco dining room at noon — jewel tones and brass lamp', 'geometric lounge lunch — the most glamorous midday interior'],
    afternoon:       ['on the leather banquette in afternoon deco interior warmth', 'geometric lounge afternoon — leather and brass and warm deco light'],
    reset:           ['back at the brass vanity in pre-evening — the most glamorous preparation', 'deco suite pre-evening reset — getting ready for the bar hour'],
    golden_hour:     ['at the art deco bar at golden hour — bottles amber, brass glowing', 'mirrored corridor at golden hour — amber reflecting infinitely in deco glass'],
    dinner:          ['leather banquette dinner in jewel-tone deco room — the definitive deco evening', 'art deco bar at dinner — the jazz hour, the most cinematic deco moment'],
    evening:         ['deco bar at evening — warm dark, amber bottles, the night beginning', 'leather banquette in the evening deco bar — the deepest deco interior hour'],
    night:           ['deco bar at full night — the warmest darkest most glamorous moment', 'deco suite at night — brass and warm lamplight and complete deco luxury'],
  },

  actionPools: {
    wake:            ['lying in deco suite bed with morning light crossing the geometric ceiling detail', 'sitting at the deco suite window in a silk robe with brass fixtures visible around', 'reaching slowly for the perfume on the deco bedside table in morning light', 'stretching in the deco suite with the geometric window light crossing warm skin', 'looking toward the brass vanity from the suite bed in first morning light', 'pressing fingers to the cool brass bedside detail in the deco morning'],
    morning_refresh: ['seated at the brass vanity with the ring light and the morning ritual beginning', 'applying perfume at the brass vanity mirror — the most glamorous morning ritual', 'leaning close to the brass ring mirror in morning vanity light', 'arranging jewellery on the vanity surface in the warm ring light', 'running both hands through just-styled hair at the brass vanity', 'pressing lipstick to the lips at the brass vanity mirror in warm morning ring light'],
    getting_dressed: ['adjusting the deco look in the full-length deco suite mirror', 'fastening a geometric brooch or earring in the suite dressing light', 'in the mirrored corridor — adjusting the look with infinite reflections around', 'placing a structured hat or headpiece on in the deco suite preparation', 'pulling on long gloves or placing a cuff in the deco dressing ritual', 'smoothing the dress hem in the deco suite mirror before the day begins'],
    breakfast:       ['seated in the geometric lounge with breakfast tray and morning brass lamp lit', 'at the deco suite window with coffee, geometric light on the facade beyond', 'selecting from a breakfast arrangement in the geometric lounge leather chair', 'both hands around a fine cup in the deco morning lounge atmosphere', 'leaning back in the leather lounge chair with coffee in the morning deco interior', 'looking through the geometric lounge window with a cup in the warm morning light'],
    late_morning:    ['reclining in the geometric lounge leather chair in late morning', 'walking through the mirrored corridor in late morning — aware of every reflection', 'seated in the geometric lounge with a book or drink in the warm deco late morning', 'standing at the geometric lounge window looking out at the city with complete ease', 'at the brass lamp in the lounge in late morning — adjusting it and looking at the room', 'trailing one hand along the leather chair back in the geometric lounge in late morning'],
    lunch:           ['seated at the leather banquette with the jewel-tone wall behind at noon', 'at the leather banquette at lunch — glass raised in warm brass lamp light', 'leaning forward slightly at the banquette table in the warm deco dining room', 'selecting from the menu at the leather banquette in the deco restaurant', 'sitting back in the leather banquette at noon with complete deco composure', 'glass in hand at the leather banquette — jewel-tone walls, brass lamp, complete'],
    afternoon:       ['lying back on the leather banquette in afternoon deco warmth', 'in the geometric lounge in the afternoon — leather, brass, warm window light', 'sitting in the deep leather chair in the afternoon lounge with a drink', 'at the lounge window in the afternoon — looking at the city with complete ease', 'reclining in the leather banquette in the warm afternoon deco interior', 'both hands around a drink in the leather lounge chair in deco afternoon light'],
    reset:           ['back at the brass vanity for the pre-evening preparation ritual', 'applying the evening look at the brass ring mirror before going to the bar', 'placing the evening jewellery on at the vanity in warm pre-evening ring light', 'selecting the evening perfume at the brass vanity in pre-evening light', 'the pre-evening vanity ritual — adding the earring, the lip, the final piece', 'leaning into the brass mirror at pre-evening, adding precision to the look'],
    golden_hour:     ['at the art deco bar at golden hour — bottle amber behind, brass glowing warm', 'in the mirrored corridor at golden hour — amber light multiplied infinitely', 'seated at the bar at golden hour with a cocktail glass catching the amber light', 'at the bar rail at golden hour with the entire backlit display behind in warm glow', 'in the geometric lounge at golden hour — every brass surface lit amber', 'at the bar with both hands on the brass rail as golden-hour fills the room'],
    dinner:          ['seated at the leather banquette at dinner in warm deco interior', 'at the art deco bar at the jazz dinner hour with a cocktail glass', 'leaning on the brass bar rail at dinner with a glass in one hand', 'at the leather banquette dinner — jewel tone, brass lamp, deep evening deco', 'seated at the bar in the most glamorous dinner hour — the deco world at full depth', 'at the banquette dinner table with candlelight and deco interior around'],
    evening:         ['at the deco bar at evening — warm dark, slow movements, complete glamour', 'seated on the leather banquette at the bar in the warm dark evening', 'at the bar with a glass, the evening deepening in the warm deco darkness around', 'leaning against the bar in the warm deco evening with complete composed ease', 'seated at the leather banquette in the bar evening with warm lamp and dim interior', 'at the brass bar in the deepening deco evening with cocktail in hand'],
    night:           ['at the deco bar at full night — the warmest and darkest and most complete', 'seated at the banquette at night with the bar at full atmosphere behind', 'at the brass bar at full night with the backlit bottles as the primary light', 'in the deco suite at night — brass lamp, jewel tone, complete private deco', 'at the bar in the deepest deco night with a glass and the room in full depth', 'lying on the deco suite bed at night with the brass lamp as the only warm source'],
  },

  environmentPools: {
    wake:            ['art deco suite in morning with geometric window light on brass fixtures', 'deco bedroom in warm morning with jewel-tone walls and structured furniture', 'deco suite in clean morning light — brass catching first warmth, pattern on ceiling', 'geometric window light crossing the deco suite bed and floor in morning', 'art deco suite morning — every surface warm and architectural in the first light', 'deco hotel suite in morning warmth — brass, pattern, jewel-tone, beautiful'],
    morning_refresh: ['brass vanity with warm ring light and jewellery arranged in morning', 'deco vanity mirror in ring light — the most glamorous morning interior', 'brass mirror with warm bulb ring, perfume bottles visible on the vanity surface', 'art deco vanity in warm 3200K ring light with jewellery and perfume arranged', 'brass ring mirror close in warm morning vanity light — the most beautiful dressing light', 'deco vanity preparation — warm bulb ring, brass, jewellery, morning composure'],
    getting_dressed: ['deco suite mirror in warm morning with full-length dressing depth behind', 'mirrored corridor with brass detail in morning — infinite geometric reflection', 'deco suite dressing light — warm morning on geometric fabric and gold detail', 'mirrored hall in morning with warm corridor light and brass fixtures throughout', 'deco suite preparation area — warm architectural morning on structured wardrobe', 'mirrored corridor in morning light — the deco hall at its most cinematic'],
    breakfast:       ['geometric lounge in morning with leather chairs, brass lamp, and warm fill', 'deco morning lounge — leather, pattern, warm lamp, morning light through the window', 'geometric lounge in clean morning light with deco furniture visible throughout', 'deco suite sitting area at morning with room service tray and window light', 'lounge in warm morning interior light — leather and brass and pattern and warmth', 'geometric lounge morning — the deco world in its most comfortable private morning form'],
    late_morning:    ['geometric lounge in late morning warm — leather and brass and window light', 'mirrored corridor in late morning with warm interior light through', 'geometric lounge late morning — every leather surface catching warm diffuse light', 'deco lounge in the quiet of late morning — completely composed', 'mirrored corridor in late morning — the afternoon light beginning to warm the brass', 'lounge late morning ease — leather chair, brass lamp lit, pattern around'],
    lunch:           ['leather banquette in jewel-tone deco dining room at noon', 'deco restaurant leather banquette with brass table lamp in warm noon interior', 'jewel-tone deco dining room at noon — deep green or burgundy with brass detail', 'leather banquette at noon in warm deco interior — the most glamorous lunch setting', 'deco dining noon — banquette, lamp, jewel wall, warm intimate restaurant', 'geometric lounge at noon with leather and warm interior as the lunch setting'],
    afternoon:       ['leather banquette in warm deco afternoon interior', 'geometric lounge in afternoon — warm ambient lamp, leather, deco comfort', 'deco afternoon lounge — the most comfortable and beautiful afternoon interior', 'leather banquette in warm afternoon deco warmth — the afternoon at its most glamorous', 'lounge in afternoon with warm lamp lit and leather chair and geometric all present', 'deco bar in the afternoon before the evening crowd — the most private and warm'],
    reset:           ['brass vanity in warm pre-evening ring light preparing for the evening', 'deco vanity in pre-evening — ring light warm, perfume out, evening look building', 'brass mirror vanity at pre-evening — the preparation hour in warm deco light', 'deco suite pre-evening — brass vanity ring lit, jewellery being placed, evening imminent', 'brass ring mirror in warm pre-evening interior — the most glamorous preparation moment', 'vanity pre-evening ritual — warm bulb ring, jewellery, perfume, the deco evening ahead'],
    golden_hour:     ['art deco bar at golden hour — backlit bottles amber, brass glowing fully', 'mirrored corridor at golden hour — amber light multiplied in geometric mirror reflections', 'geometric lounge at golden hour — every brass surface in warm amber simultaneously', 'deco bar in golden-hour amber — the most cinematic warm deco moment', 'mirrored hall at golden hour — amber repeating in every geometric mirror surface', 'art deco bar backlit display at golden hour — the most beautiful bar lighting possible'],
    dinner:          ['leather banquette in jewel-tone deco restaurant at dinner hour', 'art deco bar at the jazz dinner hour — warm, dark, amber-lit, complete', 'deco bar at dinner — the warmest and most atmospheric point in the deco evening', 'leather banquette with candlelight and deco interior at full dinner depth', 'deco restaurant at dinner — jewel tone, brass, candle, leather banquette', 'art deco bar at dinner with the deepest amber atmosphere and complete glamour'],
    evening:         ['deco bar at evening — warm dark amber, backlit bottles, brass and glamour', 'leather banquette in the bar at evening — warm dim deco depth', 'art deco bar at evening — the warm dark moment when the deco world is at its best', 'deep warm deco bar at evening with leather banquette and amber lighting', 'the deco bar evening interior — every surface dark and warm and geometric', 'bar at evening — amber, brass, leather, the most beautiful warm deco interior'],
    night:           ['art deco bar at full night ��� maximum depth and minimum light and complete glamour', 'deco suite at night — brass lamp warm, jewel-tone wall, complete private luxury', 'deco bar at full night — the deepest warmest most atmospheric deco moment', 'deep deco bar night — backlit bottles, brass, warm dark depth completely resolved', 'deco suite night — warm lamp, brass, geometric, private and complete', 'the bar at its deepest deco night — the world outside irrelevant, the interior absolute'],
  },

  moodPools: {
    wake:            ['deco suite morning ease — the most architecturally beautiful bedroom on earth', 'waking in a room designed by someone who understood beauty completely', 'morning in the deco suite — the geometry says good morning', 'brass catching the first light and making the morning more beautiful than it had to be', 'deco morning private ease — the geometry and the warmth and the complete luxury', 'the suite that was built for this exact morning and this exact occupant'],
    morning_refresh: ['brass vanity morning glamour — the most beautiful ordinary ritual', 'ring light at the vanity as the deco world\'s most specific and beautiful morning moment', 'the vanity as the place where the deco world and the self meet every morning', 'glamorous vanity ease — ring light, perfume, jewellery, complete morning ritual', 'the brass mirror at morning as the deco world\'s most intimate offering', 'morning vanity in ring light as the ritual that begins everything correctly'],
    getting_dressed: ['deco dressing ritual — structured, geometric, deliberate', 'the mirrored corridor as the most dramatic dressing room in the world', 'assembling the deco look as an act of architectural precision', 'getting dressed in the deco world means collaborating with the interior', 'the structured deco look as a form of architectural appreciation', 'infinite mirror reflections as the most honest dressing feedback available'],
    breakfast:       ['geometric lounge morning ease — leather and brass and the most beautiful breakfast interior', 'deco morning private — the lounge as the world\'s most glamorous breakfast room', 'leather chair morning ease in the geometric lounge — the deco world at rest', 'the deco lounge morning as the most comfortable and most beautiful private morning', 'breakfast in the deco world — architecture as the dining companion', 'geometric morning calm — leather, brass, warmth, complete deco morning'],
    late_morning:    ['geometric lounge late morning — the deco world in its most comfortable afternoon approach', 'leather and brass in the late morning as the ideal luxury lounge energy', 'mirrored corridor as the most dramatic transitional space at any hour', 'the deco lounge at late morning ease — no performance, only composed glamour', 'the warmth of the brass lamp at late morning in the leather lounge', 'late morning deco composure — the most glamorous ordinary morning hour'],
    lunch:           ['leather banquette at noon as the definitive deco dining experience', 'jewel-tone walls and brass lamp at lunch — the most beautiful restaurant interior', 'the leather banquette as the most comfortable and most glamorous lunch seat', 'deco dining noon — the room is the event as much as the meal', 'leather banquette ease at lunch — the deco world at its most social and most beautiful', 'the jewel-tone deco dining room as the ideal backdrop for any midday moment'],
    afternoon:       ['leather lounge afternoon — the deco world at its most private and comfortable', 'geometric lounge afternoon ease — the warmest and most beautiful afternoon interior', 'the leather banquette in afternoon as the most decadent afternoon seat available', 'deco afternoon warmth — lamp lit, leather warm, geometry everywhere', 'afternoon in the deco lounge as the ideal transition between noon and evening', 'the brass lamp in afternoon as the deco world\'s warmest most welcoming detail'],
    reset:           ['pre-evening vanity glamour — the deco world at its most deliberate preparation', 'brass ring mirror preparation as the most cinematic pre-evening ritual', 'adding the evening adornment at the vanity as an act of complete composure', 'the vanity pre-evening as the pivot between the deco day and the deco night', 'pre-evening brass mirror — the ring light and the preparation and the complete glamour', 'the deco evening begins at the vanity — everything that follows starts here'],
    golden_hour:     ['deco bar at golden hour — the most cinematic amber bar moment possible', 'brass and amber and geometric as the deco golden-hour apotheosis', 'the mirrored corridor in golden-hour amber as the most dramatic interior moment', 'every brass surface activated simultaneously at golden hour — the deco world at its peak', 'the bar backlit in amber at golden hour — the most beautiful bar in the world', 'deco golden-hour as the moment the architecture and the light were designed for together'],
    dinner:          ['leather banquette dinner in the jewel-tone deco room — perfect', 'the deco bar at the jazz dinner hour as the most atmospheric evening available', 'leather and warm lamp and jewel tone at dinner — the most glamorous dining', 'the deco dinner as an act of collaboration with the most beautiful interior', 'jazz bar dinner energy — the warmest and most cinematic deco evening', 'the leather banquette at dinner as the ideal deco evening seat'],
    evening:         ['deco bar at evening — the most beautiful warm dark interior in the world', 'the evening bar as the deco world at full atmospheric depth', 'warm amber dark and leather at the evening bar — everything is exactly right', 'the deco evening bar as the definitive architectural glamour atmosphere', 'the bar at evening as the place where glamour and atmosphere are one thing', 'deep warm deco evening — amber, brass, leather, geometry, complete'],
    night:           ['deco bar at full night — the world at its most beautiful and most dark', 'the deepest deco moment — amber bottles, warm dark, complete glamour', 'full night in the deco bar as the most atmospheric interior in any world', 'deco suite at night — the private architectural luxury at its most complete', 'the bar at full night — the most beautiful and the most private simultaneously', 'deep deco night — the architecture and the warmth and the dark all completely right'],
  },

  cameraPools: {
    wake:            ['85mm deco suite medium close, geometric ceiling detail and brass in background', '50mm wide deco suite morning, geometric light crossing the full room behind', '135mm close on face in deco morning, brass bedside detail in warm focus beside', '85mm low from deco suite floor, subject above, geometric ceiling and brass fixtures', '35mm ultra-wide deco suite morning, full room with pattern and brass and morning light', '135mm extreme close on brass detail in morning light, subject soft beyond'],
    morning_refresh: ['85mm brass vanity close, ring light creating warm halo, reflection depth behind', '50mm vanity medium, full brass mirror and jewellery and ring light in frame', '135mm close on face in ring light, vanity reflection slightly soft behind', '85mm over-shoulder into brass mirror, ring light framing both subject and reflection', '35mm wide vanity scene, full deco interior with brass and warm light', '135mm extreme close on jewellery being placed in ring light, skin warm in foreground'],
    getting_dressed: ['85mm mirrored corridor shot, infinite reflections receding behind subject', '50mm wide mirror corridor, geometric reflections and brass detail throughout', '135mm close on face at mirror, deco reflections multiplying in background', '85mm deco suite dressing medium, structured furniture receding behind', '35mm wide deco suite dressing scene, geometric detail and mirror all in frame', '24mm dramatic mirror corridor wide, subject as one element in infinite reflection'],
    breakfast:       ['85mm geometric lounge morning medium, brass lamp and leather receding behind', '50mm wide lounge breakfast scene, leather, pattern, window light in full frame', '135mm close on hands around cup in lounge, leather chair arm in focus beside', '35mm wide deco lounge morning, full geometric interior with subject at chair', '85mm from lounge window, morning light in foreground, lounge depth behind subject', '135mm tight on face in lounge morning, warm brass lamp in bokeh beside'],
    late_morning:    ['85mm geometric lounge late morning medium, leather and lamp in warm background', '50mm wide lounge late morning, full deco lounge interior with subject', '135mm close at lounge window in late morning, city blur through deco frame beyond', '85mm mirrored corridor close in late morning, reflection depth behind', '35mm wide deco lounge late morning, all elements present in warm interior', '135mm extreme close on deco detail — brass lamp or pattern — subject beyond'],
    lunch:           ['85mm leather banquette portrait, jewel-tone wall behind in warm bokeh', '50mm wide banquette scene, full deco dining room with jewel tones and lamp', '135mm close on face at banquette, warm lamp in close foreground bokeh beside', '85mm low banquette angle, subject at seat, jewel-tone wall rising behind', '35mm wide deco dining room, banquette, lamp, wall colour all in dramatic frame', '135mm tight on hands at banquette table, lamp warm and close, wall colour behind'],
    afternoon:       ['85mm leather banquette afternoon medium, warm ambient lamp in background', '50mm wide lounge afternoon, all leather and brass elements in frame', '135mm close on face in afternoon deco warmth, lamp bokeh beside', '85mm from lounge interior, lamp in foreground, subject in leather chair behind', '35mm wide afternoon deco lounge, full warm interior with subject', '135mm extreme close at leather surface detail, warm afternoon light on texture'],
    reset:           ['85mm brass vanity pre-evening close, ring light warm, darker room behind', '50mm vanity pre-evening, ring light dominant, darker suite behind', '135mm close on face in pre-evening ring light, warm halo defining everything', '85mm over-shoulder into brass mirror at pre-evening, room darker behind', '35mm wide vanity pre-evening, ring light in dark suite, full glamour in frame', '135mm extreme close on lip application or jewellery in ring light — the most glamorous detail'],
    golden_hour:     ['24mm art deco bar wide, amber bottles backlit, subject at bar in warm glow', '85mm bar portrait at golden hour, amber backlit display behind in warm bokeh', '135mm close at bar in golden amber, bottles dissolving warmly behind', '50mm mirrored corridor golden hour, amber multiplied in reflections behind', '85mm low bar angle at golden hour, amber ceiling and fixtures above and behind', '35mm dramatic wide bar golden hour, full amber deco interior around subject'],
    dinner:          ['85mm leather banquette dinner portrait, warm lamp and jewel tone behind', '50mm wide deco bar dinner scene, full amber warm interior in frame', '135mm intimate dinner close, warm lamp in close bokeh beside subject', '85mm from bar side angle, subject at banquette, full amber bar behind', '35mm wide deco dinner, leather banquette, bar behind, all elements present', '135mm tight on glass or detail at dinner, warm deco depth behind'],
    evening:         ['85mm deco bar evening medium, dark warm amber depth behind subject', '50mm wide bar evening, full warm dark deco interior in frame', '135mm close at bar evening, amber dark behind in warm bokeh', '85mm low from bar floor, subject at stool or rail, amber bottles above and behind', '35mm wide deco bar evening, full warm dark interior with all elements', '24mm dramatic bar evening wide, dark warm depth and amber throughout'],
    night:           ['85mm deco bar full night close, maximum warm dark depth behind', '50mm wide bar full night, warm dark amber and brass throughout', '135mm extreme close at bar at night, bottles amber behind in near-dark', '85mm deco suite night, brass lamp warm, jewel-tone wall deep behind', '35mm wide deco bar night, full warm darkness with amber focal points', '24mm ultra-wide full night deco bar, the entire warm dark world in frame'],
  },

  lightingPools: {
    wake:            ['warm 4800K morning through geometric deco window — directional and patterned', 'deco suite morning at 5000K — window light warming brass fixtures and pattern', '4600K morning through geometric window grid — shadow pattern on floor and walls', 'warm deco suite at 4800K — brass picking up the warm morning window light', '5000K morning in deco suite — even warm fill from large geometric windows', 'deco morning at 4600K — directional window light casting geometric shadow pattern on surfaces'],
    morning_refresh: ['3200K brass ring vanity light — warm intimate close bulb ring', 'vanity ring at 3000K — the most flattering warm light available in any interior', '3200K warm vanity ring with 4800K morning window fill secondary', 'ring light at 3000K in warm deco interior — close, warm, complete', 'brass vanity ring at 3200K — warm halo on face, room at 4800K behind', 'warm 3200K ring on mirror with slight overexposure on close detail — the vanity at its best'],
    getting_dressed: ['4800K deco suite morning for getting dressed — warm directional window key', 'mirrored corridor at 4200K warm — multiple reflected fills from warm interior', '4600K warm morning in deco suite dressing — window key, brass secondary fills', 'mirror corridor at 4400K — warm ambient reflected in every geometric mirror surface', '5000K clean morning in deco suite — the correct light for seeing the look clearly', 'deco dressing at 4800K — every reflection warm and flattering simultaneously'],
    breakfast:       ['3800K brass lounge lamp fill with 5000K morning window key', 'geometric lounge morning at 4600K window key plus 3600K lamp secondary', '4800K lounge morning window — warm and even with lamp adding secondary warmth', 'lounge brass lamp at 3200K against 5000K morning window — beautiful mixed', '4600K warm morning lounge with 3400K lamp fill — the ideal lounge breakfast light', 'lounge at morning 4800K window with warm lamp visible at 3200K beside'],
    late_morning:    ['4400K late morning lounge — window at low angle, lamp adding warm secondary', 'geometric lounge at 4600K late morning — even warm fill with lamp detail', '4800K late morning in deco lounge — window warming, lamp competing warmly', 'late morning lounge 4400K — the warmest part of the day before the afternoon shifts', 'mirrored corridor at 4200K warm in late morning — reflections multiplying', '4600K deco lounge late morning — every brass surface catching warm indirect light'],
    lunch:           ['leather banquette 3600K brass table lamp against 4800K restaurant ambient', 'deco dining room noon at 4600K — warm interior, brass lamp as primary at table', '3800K brass table lamp with 4600K restaurant ambient — the best deco lunch light', 'jewel-tone deco dining at 4400K — warm interior, lamp dominant, rich depth', 'banquette at noon with 3600K warm lamp and 5000K window at distance', '4600K deco restaurant at noon — warm, even, lamp at table adding intimacy'],
    afternoon:       ['3800K warm lounge lamp in afternoon — the deco afternoon light', 'lounge afternoon at 3600K ambient from lamps — warm, even, completely enclosed', '4000K lounge afternoon with lamp at 3200K — warm layered afternoon', 'leather lounge at 3800K afternoon — every surface warm and comfortable', 'afternoon deco at 4000K — warm lamp dominant as the window light softens', '3600K afternoon lounge — the warmest and most comfortable deco interior light'],
    reset:           ['3200K brass vanity ring pre-evening — dominant warm close source', 'pre-evening vanity at 3000K ring light against 3600K room ambient', 'brass ring at 3200K with room at 2800K — the vanity dominant in darker pre-evening', 'ring light at 3000K in pre-evening deco — the preparation hour light', 'warm 3200K ring against 2600K room at pre-evening — glamour in the darker suite', 'pre-evening brass vanity at 3200K — ring light the key, room receding to dark warm'],
    golden_hour:     ['2800K amber backlit bar display at golden hour — bottles glowing', 'golden-hour deco bar at 2600K — amber on every brass and bottle surface', '2700K golden hour in the deco bar — the most cinematic warm amber bar light', 'mirrored corridor at 2800K golden hour — amber multiplied in every reflection', '2600K amber at the deco bar — the warmest most beautiful bar lighting moment', 'golden hour at 2800K flooding the deco bar — every surface in warm amber simultaneously'],
    dinner:          ['2800K warm bar dinner lighting — lamp plus ambient plus candle layered', '3000K deco bar at dinner — warm layered multiple sources', 'leather banquette at dinner with 3200K lamp plus 2800K ambient', 'deco dinner at 2800K — warm, deep, layered, the most glamorous dinner light', 'bar dinner at 3000K — warm structured multiple sources creating the best depth', '2600K candlelight with 3200K lamp at the banquette dinner — warm depth'],
    evening:         ['2400K warm dark deco bar at evening — the evening atmosphere developing', 'bar at evening 2200K — warm dark amber becoming dominant', '2400K warm bar evening — the most beautiful amber dark deco interior', 'deco evening bar at 2200K — low warm, amber bottles backlit, deep shadow around', '2400K bar evening — lamp, bottle, brass layering into the best warm dark', 'evening deco at 2200K — every warm source contributing to the deep warm dark'],
    night:           ['2000K deco bar full night — maximum warm dark depth', 'bar at full night 1800K-2200K — deep warm amber in near-dark', '2000K deco bar night — the warmest and darkest and most glamorous', 'deco suite night at 2200K brass lamp — warm sole source in dark suite', 'full night bar 1800K — bottles as the dominant warm light in deep dark', '2000K deco bar night — the most atmospheric warm dark interior light possible'],
  },

  stylingPools: {
    wardrobe: {
      wake:            ['black silk slip in deco suite morning — minimal, precise, architectural', 'emerald green silk robe barely tied in deco morning light', 'structured ivory silk pyjama set in deco suite morning', 'champagne satin slip in deco suite morning brass light', 'black silk chemise with thin straps in warm deco morning', 'deep burgundy silk robe in deco suite morning — the correct colour for this room'],
      morning_refresh: ['black lace bralette and structured high-waist brief at the brass vanity', 'emerald silk robe at the brass vanity — minimal beneath', 'black structured lingerie set at the vanity in ring light — precisely right', 'champagne bodysuit at the brass vanity in morning ring light', 'dark silk robe barely covering at the vanity — open over the minimal beneath', 'black lace at the brass mirror in ring light — the most deco morning look'],
      getting_dressed: ['art deco-inspired black beaded midi dress with structured shoulders', 'emerald silk bias-cut with gold geometric brooch — the correct deco look', 'midnight navy structured dress with gold art deco detail at the collar', 'black velvet with gold geometric jewellery — deeply correct for this world', 'deep green structured midi with art deco clip earrings — complete', 'black silk palazzo pants and structured top with gold deco belt — modern deco'],
      breakfast:       ['silk kimono robe in emerald or burgundy over minimal in the lounge morning', 'structured deco morning look in the geometric lounge — already dressed beautifully', 'morning deco loungewear — silk wide-leg and camisole, gold detail', 'black or emerald silk in the geometric lounge morning — minimal and correct', 'jewel-tone silk wrap in the lounge morning — the robe as the look', 'dark structured silk in the deco lounge morning — always dressed even at breakfast'],
      late_morning:    ['black structured midi in the geometric lounge late morning', 'emerald silk or velvet in the lounge late morning — the deco world at rest', 'structured deco look in deep jewel tones for late morning lounge ease', 'black velvet or silk in the geometric lounge in warm late morning', 'dark silk with gold deco detail in the mirrored corridor late morning', 'emerald or midnight navy midi in the lounge late morning — deeply correct'],
      lunch:           ['black bias-cut silk at the leather banquette — the definitive deco lunch look', 'emerald bodycon with gold deco earrings at the banquette — complete', 'structured velvet at the leather banquette in the jewel-tone dining room', 'midnight navy at the banquette — silk or velvet with gold — deeply right', 'black structured dress with art deco jewellery at the leather banquette', 'deep jewel-tone look at the deco dining banquette — every detail right'],
      afternoon:       ['emerald silk on the leather banquette in afternoon lounge ease', 'black silk on the leather lounge chair — the deco afternoon look', 'midnight or burgundy silk in the warm afternoon deco lounge', 'structured deco silk in deep jewel tones in the afternoon lounge', 'dark velvet or silk on the leather banquette in warm afternoon', 'jewel-tone deco look in the afternoon lounge — correct and complete'],
      reset:           ['pre-evening deco look being assembled at the brass vanity', 'adding the evening jewellery to the deco look at the vanity', 'the complete deco evening look being finished at the brass mirror', 'black or emerald evening dress in preparation at the vanity ring light', 'the most glamorous deco evening look being assembled piece by piece', 'adding the art deco earrings and perfume at the brass vanity pre-evening'],
      golden_hour:     ['black beaded or sequined deco look at the bar at golden hour', 'emerald silk at the bar in amber golden-hour light', 'black structured with gold deco jewellery at the amber bar', 'deep jewel-tone at the deco bar at golden hour — amber on everything', 'midnight navy with gold at the bar in golden-hour amber', 'the deco bar golden-hour look — dark fabric with gold detail in amber'],
      dinner:          ['black beaded or velvet at the deco dinner bar or banquette', 'deep emerald evening dress at the leather banquette dinner', 'the complete black deco evening look at the jazz bar dinner hour', 'midnight navy with art deco gold at the deco dinner', 'black velvet with gold deco earrings at the most glamorous dinner setting', 'the definitive deco dinner look — black or jewel-tone with complete gold detail'],
      evening:         ['black silk at the deco bar at evening — minimal and completely correct', 'emerald or midnight in the dark warm bar evening', 'the deco evening bar look — dark, structured, gold detail, complete', 'black with art deco gold at the bar in the warm dark evening', 'jewel-tone silk at the bar evening — the deco world at its most atmospheric', 'dark silk and gold at the bar in the deepest deco evening'],
      night:           ['minimal black at the deco bar at full night — the most essential deco look', 'black silk slip or bodysuit at the deco suite at night', 'the most reduced deco night look — black, gold, and complete', 'midnight silk in the deco bar at full night', 'black at the bar at night — the deco world at its most stripped and most correct', 'the deco night look — dark, warm, minimal, and precisely right'],
    },
    details: {
      wake:            ['art deco geometric ring on the bedside table in morning light', 'gold deco earring on the nightstand beside the perfume bottle', 'silk pillow with geometric detail in deco suite morning'],
      morning_refresh: ['art deco perfume bottle on brass vanity surface', 'geometric ring being placed on finger in ring light', 'gold deco earring being clipped on at the brass mirror'],
      getting_dressed: ['art deco clip earring being placed in deco suite light', 'geometric gold brooch on structured dress fabric', 'black suede glove being pulled on — the most deco detail'],
      breakfast:       ['fine cup on a geometric lounge side table', 'art deco lamp warm beside the lounge chair at breakfast', 'gold detail catching the lounge morning light'],
      late_morning:    ['art deco brass lamp lit in the lounge late morning', 'geometric pattern on lounge floor catching late morning light', 'gold deco ring on hand at the lounge window'],
      lunch:           ['brass table lamp at the leather banquette at lunch', 'jewel-tone wall colour behind the banquette at the most saturated', 'gold deco earring in warm lamp light at the banquette'],
      afternoon:       ['brass lamp lit in leather lounge afternoon warmth', 'leather texture of the lounge chair in warm afternoon light', 'art deco gold detail catching the warm afternoon lamp'],
      reset:           ['perfume bottle on brass vanity at pre-evening', 'art deco earring being placed in ring light', 'lip colour applied at the brass mirror pre-evening'],
      golden_hour:     ['amber bar bottle backlit in golden-hour glow', 'brass bar rail warm in golden-hour amber', 'gold deco jewellery catching amber bar light at golden hour'],
      dinner:          ['cocktail glass catching the amber deco bar light at dinner', 'art deco earring in warm bar lamp at dinner', 'jewel-tone wall deep and saturated in warm deco dinner light'],
      evening:         ['cocktail glass amber-lit at the bar at evening', 'brass bar fixture warm in the dark deco evening', 'gold deco jewellery in warm dark bar evening light'],
      night:           ['amber bottle at the bar at full night', 'brass detail warm in the near-dark deco bar at night', 'gold earring barely catching warm light at full deco night'],
    },
    changeMoments: {
      wake:            ['deco suite morning in silk — the most private deco moment', 'the suite in morning before the deco world begins'],
      morning_refresh: ['at the brass vanity in lingerie and morning ease — the preparation ritual', 'between sleep and the deco look at the brass ring mirror'],
      getting_dressed: ['assembling the deco look — structured, geometric, deliberate', 'the mirrored corridor as the final dressing check'],
      breakfast:       ['in the geometric lounge in silk morning ease', 'the deco morning private — silk and brass and leather and warm'],
      late_morning:    ['in the geometric lounge in the deco look', 'the mirrored corridor late morning — the full look visible infinitely'],
      lunch:           ['at the leather banquette in the full deco look at noon', 'the definitive deco noon — banquette, jewel-tone, brass, complete'],
      afternoon:       ['leather banquette afternoon ease in the deco look', 'deco afternoon lounge — the most comfortable glamour available'],
      reset:           ['back at the brass vanity for the evening update', 'adding the evening elements at the ring mirror'],
      golden_hour:     ['the complete evening deco look at the bar at golden hour', 'amber bar golden-hour — the most cinematic deco styling moment'],
      dinner:          ['the complete deco evening look at the banquette or bar', 'the deco dinner look — dark fabric, gold detail, complete'],
      evening:         ['at the bar in the dark warm deco evening', 'the deco evening bar look at full atmospheric depth'],
      night:           ['full deco night at the bar — the most essential and the most complete', 'deco suite at night — minimal, private, architecturally perfect'],
    },
  },

  sensoryPools: {
    wake:            ['brass cool under fingertips in the deco suite morning', 'geometric window light pattern on skin in morning warmth', 'the specific warmth of a deco suite in the morning'],
    morning_refresh: ['warm ring light close on skin at the brass vanity', 'perfume in the warm brass mirror morning', 'cool gold jewellery placed on warm skin in ring light'],
    getting_dressed: ['black velvet texture against skin in deco dressing light', 'geometric reflection cool in the mirrored corridor', 'gold brooch weight on the structured dress fabric'],
    breakfast:       ['warm cup in the leather lounge chair morning', 'brass lamp warmth beside the geometric lounge chair', 'leather chair surface warm under the hand in morning'],
    late_morning:    ['leather chair cool becoming warm in late morning lounge', 'geometric floor pattern underfoot in the deco lounge', 'brass lamp warmth in the late morning lounge atmosphere'],
    lunch:           ['leather banquette firm and warm beneath at lunch', 'brass lamp warmth on the banquette table surface', 'jewel-tone wall depth behind — the colour you can almost feel'],
    afternoon:       ['leather banquette warm in the afternoon lounge', 'brass lamp warmth close in the afternoon deco interior', 'the specific comfort of a deeply upholstered deco seat in afternoon'],
    reset:           ['ring light warmth close on skin at the brass vanity pre-evening', 'cool perfume glass in the warm ring light', 'gold earring cool placed on warm earlobe in ring light'],
    golden_hour:     ['amber warmth at the deco bar in golden hour', 'cool brass bar rail in the warm golden-hour amber', 'cocktail glass cool in warm golden-hour amber light'],
    dinner:          ['leather banquette warm at dinner', 'cocktail glass cool in warm amber bar dinner light', 'brass lamp warmth close at the banquette dinner table'],
    evening:         ['warm dark amber bar evening air', 'cool cocktail glass in warm dark bar evening', 'brass bar cool under hands in the warm dark evening'],
    night:           ['warm dark deco bar at full night', 'cool glass in warm dark at the full-night bar', 'brass detail warm in the deepest deco night warmth'],
  },

  socialEnergyPools: {
    wake:            ['completely private in the deco suite morning', 'the suite as total private architectural luxury'],
    morning_refresh: ['brass vanity as the most private deco ritual', 'preparation in the ring light — private and deliberate'],
    getting_dressed: ['dressing in the suite or mirrored corridor — observed only by reflections', 'the mirror as the only audience for the deco preparation'],
    breakfast:       ['private deco lounge morning — the most glamorous private breakfast', 'geometric lounge as private luxury breakfast space'],
    late_morning:    ['lounge late morning as composed private ease', 'the mirrored corridor as a dramatic private passage'],
    lunch:           ['leather banquette as the most glamorous semi-public lunch seat', 'the deco restaurant as the correct public setting'],
    afternoon:       ['lounge afternoon as private glamorous ease', 'leather banquette afternoon as composed private luxury'],
    reset:           ['brass vanity pre-evening as private preparation ritual', 'the ring light as the only audience for the evening build'],
    golden_hour:     ['deco bar at golden hour as the most glamorous public moment', 'the bar as the correct social setting for the deco world'],
    dinner:          ['leather banquette dinner as the deco world\'s most glamorous social moment', 'the deco bar at dinner as the most atmospheric social setting'],
    evening:         ['bar at evening as the deco world\'s most complete social atmosphere', 'warm dark bar as the best deco public space'],
    night:           ['full night bar as the most atmospheric deco public space', 'deco suite at night as the final private luxury'],
  },

  atmospherePools: {
    wake:            ['deco suite morning — geometric light and brass and perfect architectural warmth', 'the most beautiful morning interior in any world'],
    morning_refresh: ['brass vanity ring light morning — warm, close, glamorous, deliberate', 'the preparation ritual atmosphere in the most cinematic deco mirror'],
    getting_dressed: ['mirrored corridor deco atmosphere — infinite geometric reflection', 'the deco dressing atmosphere — structure, geometry, deliberate luxury'],
    breakfast:       ['geometric lounge morning atmosphere — leather, brass, warm, private', 'the deco lounge as the most glamorous breakfast atmosphere'],
    late_morning:    ['geometric lounge late morning atmosphere — warm, composed, unhurried', 'the mirrored corridor as dramatic transitional atmosphere'],
    lunch:           ['leather banquette deco dining atmosphere — jewel-tone, lamp, warm', 'the most glamorous midday interior atmosphere in any world'],
    afternoon:       ['leather lounge afternoon atmosphere — warm, comfortable, completely deco', 'the deco afternoon as the most glamorous private afternoon'],
    reset:           ['pre-evening vanity atmosphere — ring light, dark room, preparation', 'the brass mirror pre-evening as the most deliberate deco atmosphere'],
    golden_hour:     ['deco bar amber golden-hour atmosphere — the most cinematic interior light', 'brass and bottles and amber at golden hour — the definitive deco moment'],
    dinner:          ['warm dark deco dinner atmosphere — leather, lamp, jewel-tone, amber', 'the deco bar or banquette at dinner — the best dinner atmosphere available'],
    evening:         ['deep warm deco bar evening atmosphere — the world at its most glamorous', 'warm dark amber at the bar evening — completely and perfectly deco'],
    night:           ['full night deco bar atmosphere — warm, dark, amber, complete', 'the deepest most glamorous deco night atmosphere — maximum depth'],
  },

  propPools: {
    wake:            ['brass bedside fixture in deco suite morning', 'geometric window casting shadow pattern on floor', 'art deco perfume bottle on the nightstand'],
    morning_refresh: ['brass ring vanity mirror with jewellery arranged', 'perfume bottles on the brass vanity surface', 'art deco earring detail on the vanity'],
    getting_dressed: ['art deco geometric jewellery being placed', 'mirrored corridor with infinite deco reflections', 'black structured dress on the deco suite chair'],
    breakfast:       ['fine cup on geometric lounge side table', 'brass lamp lit in geometric lounge morning', 'leather lounge chair with morning light'],
    late_morning:    ['brass lamp warm in geometric lounge late morning', 'geometric floor pattern in late morning lounge', 'leather chair in warm lounge light'],
    lunch:           ['brass table lamp at leather banquette', 'jewel-tone wall behind the banquette deep and saturated', 'cocktail or wine glass at the banquette lunch'],
    afternoon:       ['leather banquette warm in afternoon', 'brass lamp lit in afternoon lounge warmth', 'geometric detail in warm afternoon lounge interior'],
    reset:           ['perfume bottle on brass vanity pre-evening', 'art deco jewellery being placed at the ring mirror', 'brass ring light warm pre-evening at vanity'],
    golden_hour:     ['backlit bar bottles in amber golden-hour', 'brass bar rail warm in golden-hour light', 'geometric bar front in amber golden glow'],
    dinner:          ['cocktail glass at the amber bar at dinner', 'brass table lamp at the leather banquette dinner', 'jewel-tone wall behind in warm dinner amber'],
    evening:         ['cocktail glass amber-lit at the bar evening', 'brass bar fixture in warm dark bar evening', 'backlit bottles warm in the deco bar evening'],
    night:           ['amber bottles at the full-night bar', 'brass bar detail in warm dark at full night', 'deco suite brass lamp as sole night source'],
  },

  bodyLanguagePools: {
    wake:            ['lying in deco suite with complete composed ease in morning light', 'seated at the deco window in morning with deliberate composed posture', 'reaching for bedside detail with slow deliberate morning ease'],
    morning_refresh: ['seated at the brass vanity with upright composed posture', 'leaning close to the ring mirror with deliberate focus', 'placing jewellery with slow deliberate hands in ring light'],
    getting_dressed: ['standing in the mirrored corridor with complete composed deco posture', 'adjusting the look in the deco mirror with precise deliberate movement', 'turning once in the deco mirror — the complete assessment'],
    breakfast:       ['seated in the leather chair with upright composed lounge posture', 'both hands around a cup in the lounge chair in morning ease', 'looking toward the lounge window with deliberate composed gaze'],
    late_morning:    ['reclining slightly in the leather lounge chair with composed ease', 'walking through the lounge with deliberate composed deco grace', 'trailing one hand along the leather chair back in late morning'],
    lunch:           ['seated at the banquette with upright elegant posture', 'leaning slightly forward at the banquette table with deliberate ease', 'glass raised at the banquette — the most composed lunch gesture'],
    afternoon:       ['reclining on the leather banquette with complete composed afternoon ease', 'seated in the deep leather chair in the afternoon with slow deliberate ease', 'one arm along the leather banquette back — composed and deliberate'],
    reset:           ['seated at the brass vanity with upright preparation posture', 'hands placing jewellery at the ring mirror with deliberate slow ease', 'leaning close to the ring mirror in precise pre-evening focus'],
    golden_hour:     ['at the bar rail with complete composed golden-hour ease', 'seated at the bar with upright deliberate deco posture in amber', 'one hand on the brass bar rail — the most deco golden-hour gesture'],
    dinner:          ['seated at the banquette with the most composed dinner posture', 'at the bar with a glass and deliberate composed evening ease', 'one arm on the bar or banquette with complete deco dinner composure'],
    evening:         ['at the bar with slow deliberate composed evening ease', 'seated on the bar stool with upright deliberate deco evening posture', 'leaning slightly against the bar with complete warm deco evening composure'],
    night:           ['at the bar at full night with the most deliberately composed deco posture', 'seated at the bar or banquette with deep warm deco night ease', 'one hand on the brass bar rail at full night — the final deco gesture'],
  },

  facialExpressionPools: {
    wake:            ['deco suite morning expression — composed, private, architectural', 'morning brass expression — warm, deliberate, the deco world waking', 'the suite morning face — composed and completely at home'],
    morning_refresh: ['brass ring mirror expression — the most deliberate and precise morning face', 'vanity morning composure — focused, warm, the glamour building', 'ring light preparation expression — precise, self-aware, controlled'],
    getting_dressed: ['mirrored corridor expression — the face that knows exactly what it looks like', 'deco dressing composure — architectural precision in the expression', 'the complete deco dressing expression — deliberate and completely composed'],
    breakfast:       ['lounge morning expression — warm, private, the most glamorous ordinary face', 'geometric lounge breakfast composure — unhurried, warm, completely right', 'leather chair morning expression — private ease and complete deco comfort'],
    late_morning:    ['lounge late morning expression — composed warm ease in the deco interior', 'the mirrored corridor late morning face — aware of every reflection', 'late morning deco expression — the most composed ordinary deco moment'],
    lunch:           ['leather banquette expression — the most glamorous composed lunch face', 'deco dining noon composure — warm, direct, architecturally correct', 'banquette expression at the jewel-tone wall — the most saturated composed face'],
    afternoon:       ['leather lounge afternoon expression — composed warm ease', 'deco afternoon banquette expression — reclining glamour', 'lounge afternoon face — the most comfortable composed deco expression'],
    reset:           ['brass vanity pre-evening expression — focused, precise, building', 'ring light preparation evening expression — the most deliberate deco face', 'the pre-evening vanity composure — adding precision with each step'],
    golden_hour:     ['deco bar golden-hour expression — warm, composed, amber-lit', 'the bar at golden hour face — the most cinematic composed deco expression', 'amber bar expression — warm, deliberate, completely correct'],
    dinner:          ['deco bar or banquette dinner expression — the most glamorous dinner face', 'warm amber deco dinner composure — deliberate, warm, architecturally aware', 'the deco dinner expression — the most complete and composed of the day'],
    evening:         ['warm dark bar evening expression — composed, deliberate, completely glamorous', 'the bar at evening face — warm, controlled, the deco world at full depth', 'deep deco evening expression — the most cinematic warm composed face'],
    night:           ['full night deco bar expression — the most atmospheric and composed', 'warm dark deco night face — the deepest and most glamorous expression', 'the final deco night expression — the deco world complete and completely owned'],
  },

  handDetailPools: {
    wake:            ['fingers on brass bedside fixture in deco suite morning', 'hand resting on geometric-patterned bedcover', 'reaching for perfume bottle on the deco nightstand'],
    morning_refresh: ['hands placing art deco earring at the ring mirror', 'fingers on the brass vanity edge in ring light', 'both hands at the brass mirror in warm ring morning light'],
    getting_dressed: ['art deco brooch being fastened to structured fabric', 'fingers smoothing velvet or silk at the deco mirror', 'hand adjusting glove or cuff in mirrored corridor light'],
    breakfast:       ['both hands around fine cup in the leather lounge chair', 'fingers on the lounge side table beside the brass lamp', 'hand resting on leather chair arm in morning lounge'],
    late_morning:    ['trailing hand along leather chair back in lounge', 'finger at the lounge window glass looking out', 'hand resting on the geometric floor pattern in the lounge'],
    lunch:           ['glass raised at the leather banquette in warm lamp light', 'hands on the banquette table edge at lunch', 'fingers near the brass table lamp at the banquette'],
    afternoon:       ['arm extended along the leather banquette back in afternoon', 'hand on leather banquette surface in warm afternoon', 'fingers around a glass in the afternoon leather lounge'],
    reset:           ['both hands placing art deco earrings at the ring mirror', 'finger applying lip at the brass vanity pre-evening', 'hands around the perfume bottle at the vanity pre-evening'],
    golden_hour:     ['one hand on the brass bar rail at golden hour', 'cocktail glass held in amber bar golden light', 'fingers on the geometric bar front in golden-hour amber'],
    dinner:          ['cocktail glass in hand at the amber deco bar', 'hand on the bar rail at the deco dinner hour', 'fingers near the brass table lamp at the banquette dinner'],
    evening:         ['cocktail glass held in warm dark bar evening', 'hand on brass bar rail in the deco evening', 'fingers trailing the bar surface in warm dark evening'],
    night:           ['hand on brass bar rail at full deco night', 'cocktail glass barely held in warm dark full night', 'fingers near the amber bottle at the full-night bar'],
  },

  movementEnergyPools: {
    wake:            ['suite-morning', 'composed', 'architectural'],
    morning_refresh: ['ring-light', 'vanity', 'deliberate'],
    getting_dressed: ['mirrored', 'geometric', 'precise'],
    breakfast:       ['lounge-morning', 'leather', 'warm'],
    late_morning:    ['lounge-ease', 'composed', 'unhurried'],
    lunch:           ['banquette', 'glamorous', 'deliberate'],
    afternoon:       ['leather-ease', 'warm', 'reclining'],
    reset:           ['vanity-preparation', 'ring-light', 'evening-build'],
    golden_hour:     ['bar-amber', 'golden', 'cinematic'],
    dinner:          ['jazz-bar', 'warm-dark', 'glamorous'],
    evening:         ['bar-depth', 'warm', 'atmospheric'],
    night:           ['full-night', 'amber-dark', 'complete'],
  },

  transitionPools: {
    human: {
      wake:            ['deco suite morning — the most architecturally beautiful bedroom beginning', 'brass and geometric light as the first deco greeting of the day'],
      morning_refresh: ['brass vanity morning — the most glamorous ordinary ritual', 'ring light and perfume and jewellery at the deco mirror'],
      getting_dressed: ['assembling the deco look — deliberate and architecturally correct', 'the mirrored corridor as the infinite deco dressing room'],
      breakfast:       ['geometric lounge morning — leather, brass, warm, private breakfast', 'the most glamorous private breakfast interior available'],
      late_morning:    ['lounge late morning ease — the deco world at its most comfortable', 'the mirrored corridor as dramatic late morning passage'],
      lunch:           ['leather banquette at noon — the definitive deco dining moment', 'jewel-tone and brass lamp and leather at the deco lunch'],
      afternoon:       ['leather lounge afternoon — the most glamorous comfortable afternoon', 'deco afternoon ease in the warm interior'],
      reset:           ['back to the brass vanity for the evening preparation', 'ring light and jewellery and the evening deco look building'],
      golden_hour:     ['deco bar at golden hour — amber and brass and the most cinematic bar', 'the golden-hour deco bar as the definitive architectural amber moment'],
      dinner:          ['leather banquette or deco bar at the jazz dinner hour', 'the most glamorous dinner setting — dark, warm, amber, complete'],
      evening:         ['deco bar at evening — the warmest and darkest and most glamorous', 'deep warm amber at the bar — the deco world at full evening depth'],
      night:           ['full night deco bar — the deepest most atmospheric deco moment', 'deco suite at night — the private architectural luxury fully resolved'],
    },
  },

  narrativeIntentPools: {
    wake:            ['deco suite morning as the most beautiful architectural bedroom beginning', 'brass and geometric light as the first deco greeting'],
    morning_refresh: ['brass vanity ritual as the most glamorous ordinary morning possible', 'ring light and deliberate preparation as the deco morning signature'],
    getting_dressed: ['the deco look as architectural collaboration — the building and the person', 'the mirrored corridor as the most cinematic dressing experience'],
    breakfast:       ['geometric lounge morning as the most glamorous private breakfast', 'leather and brass and warm as the ideal deco morning interior'],
    late_morning:    ['lounge late morning as composed deco glamour at rest', 'the deco lounge as the most beautiful late morning private space'],
    lunch:           ['leather banquette at noon as the definitive deco dining experience', 'jewel-tone deco dining as the most glamorous midday setting'],
    afternoon:       ['leather lounge afternoon as the most glamorous comfortable private hour', 'the deco afternoon as composed glamour at its most comfortable'],
    reset:           ['brass vanity pre-evening as the deco world\'s most deliberate preparation', 'ring light and evening jewellery as the gateway to the deco night'],
    golden_hour:     ['deco bar at golden hour as the most cinematic architectural amber moment', 'brass and bottles and geometric in golden-hour as the deco apotheosis'],
    dinner:          ['leather banquette or deco bar at dinner as the definitive deco evening', 'warm amber dark and complete — the deco world at its most glamorous'],
    evening:         ['deep warm deco bar at evening as the world\'s most beautiful bar atmosphere', 'warm dark amber at the bar as the complete deco atmospheric depth'],
    night:           ['full night deco bar as the deepest and most glamorous moment in the world', 'deco suite at night as the private architectural luxury at its most complete'],
  },

  fallbackRules: {
    pacingProfile: { wake: 'slow', morning_refresh: 'slow', getting_dressed: 'slow', breakfast: 'slow', late_morning: 'slow', lunch: 'medium', afternoon: 'slow', reset: 'slow', golden_hour: 'slow', dinner: 'slow', evening: 'slow', night: 'slow' },
    repetitionBreakers: { avoidBackToBackSameLocation: true, avoidBackToBackSameLightingStyle: true, encourageWardrobeEvolution: true },
    worldDefaults: { allowSceneGroupFallbackToPhasePools: true, allowSubLocationFallbackToWorldPools: true, preferSceneGroupsWhenPresent: true },
  },

  exclusions: {
    premium: ['casual or streetwear', 'bright modern minimalist interiors', 'natural outdoor settings', 'sporty or athletic energy'],
    hard: ['Scandinavian or industrial aesthetic', 'white minimal modern interior', 'bright daylight outdoor', 'anything without geometric or brass deco detail'],
  },

  routeRules: {
    worldIdentity: ['every interior must have geometric pattern, brass, leather, or mirror — always art deco, always architectural', 'the colour palette is jewel tones — emerald, midnight navy, burgundy, black, champagne — always rich and dark'],
    humanFlow: ['morning suite through vanity through lounge into banquette and eventually the bar for the evening — the deco world arc', 'the day builds from private suite luxury toward the glamorous bar evening'],
    styling: ['structured dark geometric looks with gold deco jewellery only — black, emerald, midnight, burgundy', 'no casual, no bright, no modern minimalist — always architectural and deliberate'],
    atmosphere: ['warm dark interior light only — brass lamps, ring light, amber bar, geometric window light', 'the world is always warm, always architectural, always jewel-toned'],
  },
}
