export const STORY_WORLD_NEON_CITY = {
  id: 'neon-city',
  name: 'Neon City',
  description: 'Electric urban night — Tokyo Shinjuku, Hong Kong Kowloon, Seoul Gangnam, Bangkok rooftops, Las Vegas strip. Neon as a styling tool. Glass towers as mirrors. The city belongs to her after dark.',
  compatiblePlans: ['Fanvue', 'Unrestricted', 'Premium'],
  defaultPack: 'neon-editorial',
  defaultAgeRange: '22-35',

  subLocations: {
    'tokyo-shinjuku': {
      name: 'Tokyo Shinjuku',
      label: 'Tokyo · Neon Labyrinth',
      atmosphere: 'Electric pink and cyan signage, narrow alleys, vending machines, pedestrian crossings, izakayas, capsule hotel corridors, glass towers at midnight',
      lightingBase: 'Mixed neon fill — magenta, cyan, white, amber. No single source. Every surface reflects. 3200-4100K ambient with electric colour overlays.',
      sceneGroups: {
        street_neon: { name: 'Street & Neon', description: 'Crossings, alleys, signage walls' },
        vertical_city: { name: 'Glass & Height', description: 'Tower lobbies, rooftops, elevators' },
        intimate_night: { name: 'Late Night Inside', description: 'Bars, booths, private rooms' },
      },
    },
    'hong-kong-kowloon': {
      name: 'Hong Kong Kowloon',
      label: 'Hong Kong · Vertical Night',
      atmosphere: 'Stacked neon signage, trams, ferry piers, rooftop pools, temple alley glow, night market movement, harbour light reflections',
      lightingBase: 'Dense layered neon — red, gold, white, blue harbour glow. 2800-3600K warm through signage. Humidity adds a diffused halo to every light source.',
      sceneGroups: {
        harbour_glow: { name: 'Harbour & Sky', description: 'Ferry pier, rooftop, city view' },
        alley_market: { name: 'Alley & Market', description: 'Night market, temple street, narrow passages' },
        vertical_hotel: { name: 'Hotel & Height', description: 'Rooftop pool, lobby, penthouse' },
      },
    },
    'seoul-gangnam': {
      name: 'Seoul Gangnam',
      label: 'Seoul · K-Fashion Night',
      atmosphere: 'Clean glass towers, K-beauty pop-up windows, COEX underground mall, Han River bridges at night, restaurant row neon, high-fashion pedestrian streets',
      lightingBase: 'Clean white neon mixed with warm amber. 4000-5500K street lights. Cooler, cleaner than Tokyo — more fashion editorial than chaos.',
      sceneGroups: {
        fashion_street: { name: 'Fashion Street', description: 'Glass storefronts, curated night blocks' },
        han_river: { name: 'Han River', description: 'Bridge glow, riverside paths, city reflection' },
        underground_mall: { name: 'Underground', description: 'COEX corridors, underground luxury' },
      },
    },
    'las-vegas-strip': {
      name: 'Las Vegas Strip',
      label: 'Las Vegas · Maximum Neon',
      atmosphere: 'Maximum neon density, casino entrance columns of light, pool areas at midnight, rooftop bars above the strip, dealer tables, hotel corridors in gold',
      lightingBase: 'Maximum artificial light — gold, white, red, blue. 2700-3200K warm casino glow. No natural light. Pure electric.',
      sceneGroups: {
        strip_entrance: { name: 'Strip & Casino', description: 'Hotel entrances, sign forests, strip movement' },
        pool_night: { name: 'Pool at Night', description: 'Infinity pool, pool deck, night swim' },
        rooftop_bar: { name: 'Rooftop Bar', description: 'Skyline bars, VIP areas above the strip' },
      },
    },
    'bangkok-rooftop': {
      name: 'Bangkok Rooftop',
      label: 'Bangkok · Sky Bar Night',
      atmosphere: 'Sky bar above 60 floors, temple lights visible from rooftops, tuk-tuk-lit streets below, Chao Phraya river gold reflections, luxury hotel pool terraces',
      lightingBase: 'Warm Thai gold and river reflection. 3000-3800K pool terrace light. Cool sky above. Warm city below. Dramatic contrast.',
      sceneGroups: {
        sky_bar: { name: 'Sky Bar', description: 'Rooftop at 60+ floors, open air, city below' },
        river_view: { name: 'River View', description: 'Chao Phraya light, terrace overlooking river' },
        temple_night: { name: 'Night Temple', description: 'Gold temple light at night, sacred glow' },
      },
    },
    'neon-corridor': {
      name: 'Neon Corridor',
      label: 'Generic City · Pure Neon',
      atmosphere: 'Anywhere with maximum neon density — reflective wet pavement, light trails, backlit signage, colour-washed face, city pulse',
      lightingBase: 'Fully art-directed neon — any combination of pink, cyan, purple, gold, red. Pure editorial light. 3200K base with full colour overlay.',
      sceneGroups: {
        neon_portrait: { name: 'Neon Portrait', description: 'Face lit purely by neon — close, editorial' },
        reflection_pavement: { name: 'Wet Pavement', description: 'Rain-reflected neon city floor' },
        light_trail: { name: 'Light Trail', description: 'Moving city with long exposure energy' },
      },
    },
  },

  pools: {
    wake: [
      'late morning in a Tokyo capsule hotel with electric signs still pulsing outside the small window',
      'penthouse suite above Shinjuku where the neon city spreads below in late morning grey',
      'Hong Kong hotel room with harbour visible through floor-to-ceiling glass in pale city morning',
      'Seoul serviced apartment in Gangnam with clean midday light and the city grid far below',
      'Las Vegas suite at 11am still in last night clothing with the strip blazing in harsh desert daylight',
      'Bangkok rooftop suite with the river gold in late morning and temple spires in warm haze',
    ],
    morning_refresh: [
      'marble hotel bathroom in Tokyo with neon signs still visible through the frosted window',
      'Hong Kong hotel vanity with harbour light and city noise filtering through glass',
      'Seoul luxury hotel bathroom with cool white tiles and clean minimal morning light',
      'Las Vegas powder room with gold mirrors and maximum lighting in boutique hotel suite',
      'Bangkok river-view bathroom with warm morning humidity and light on marble surfaces',
      'capsule hotel corridor bathroom with fluorescent white and industrial clean energy',
    ],
    getting_dressed: [
      'Tokyo hotel wardrobe with the night outfit already chosen — black, structured, electric',
      'Hong Kong boutique fashion district dressing room with neon visible through the window',
      'Seoul fashion showroom in Apgujeong with K-style editorial pieces hanging in clean light',
      'Las Vegas hotel wardrobe with sequins and dramatic night choices catching afternoon light',
      'Bangkok luxury suite with silk and tropical night dressing in warm late-afternoon air',
      'neon-lit dressing area in a boutique hotel where every mirror reflects coloured light',
    ],
    breakfast: [
      'Tokyo convenience store standing eat at 7am — Lawson window seat watching the city wake',
      'Hong Kong dim sum teahouse in early Kowloon morning with bamboo steamers and old tile',
      'Seoul rooftop café with Han River view in pale city morning light',
      'Las Vegas 24-hour diner where breakfast happens at 2pm after a long night',
      'Bangkok riverside café with Chao Phraya in gold morning haze and temple sounds',
      'ramen counter in Shinjuku underground at 8am with steam and soy and city noise',
    ],
    late_morning: [
      'Shibuya crossing at 11am with full daytime energy and the city at maximum human density',
      'Hong Kong IFC mall interior in midday with shopping and city glass above',
      'Seoul street style on Garosu-gil in warm midday fashion energy',
      'Las Vegas Fashion Show Mall interior in desert midday bright',
      'Bangkok luxury shopping mall interior in Siam Paragon with cool air and high ceilings',
      'Tokyo vintage arcade corridor in Akihabara with daylight mixed with machine glow',
    ],
    lunch: [
      'Tokyo sushi counter at noon — chef facing, clean precision, soft wood and quiet conversation',
      'Hong Kong rooftop restaurant with glass walls and harbour panorama at midday',
      'Seoul modern Korean restaurant with minimalist interior and natural afternoon light',
      'Las Vegas celebrity chef restaurant in afternoon pre-service light',
      'Bangkok luxury rooftop restaurant with city view and warm afternoon gold',
      'Shinjuku ramen counter at peak lunch where every surface steams and every face focuses',
    ],
    afternoon: [
      'Tokyo Harajuku street in peak afternoon with electric youth fashion and maximum colour',
      'Hong Kong harbour promenade in warm golden afternoon with Victoria Harbour light',
      'Seoul Olympic Park in soft afternoon Korean light with city towers behind',
      'Las Vegas pool deck in brutal desert afternoon — water, heat, luxury',
      'Bangkok rooftop pool in warm afternoon humidity with city shimmer below',
      'Tokyo department store upper floor in afternoon with city visible through every window',
    ],
    reset: [
      'Tokyo luxury hotel spa in afternoon — dark room, warm light, city pressure dissolved',
      'Hong Kong hotel room reset in golden late afternoon with harbour turning warm',
      'Seoul jimjilbang sauna in clean minimalist rest before the night begins',
      'Las Vegas suite private reset before the night — gold light, room service, preparation',
      'Bangkok rooftop pool at 5pm as the light begins to shift to gold over the river',
      'Shinjuku golden hour on a high-rise terrace as the city transitions from day to neon',
    ],
    golden_hour: [
      'Shibuya crossing at golden hour — amber light across ten thousand faces and electric signage',
      'Hong Kong Peak at sunset with Victoria Harbour turning gold far below',
      'Seoul Namsan Tower at golden hour with the entire city grid in warm orange',
      'Las Vegas strip at sunset when the natural gold competes with the first neon glow',
      'Bangkok sky bar at golden hour with the river turning pure gold below',
      'Tokyo skyscraper observation deck at the exact moment the city lights begin and the sky hasn\'t decided yet',
    ],
    dinner: [
      'Tokyo omakase at a Michelin counter where each piece arrives with ceremony and silence',
      'Hong Kong rooftop restaurant where the harbour glitters far below and the food is sculptural',
      'Seoul private dining room with contemporary Korean cuisine and warm editorial lighting',
      'Las Vegas high-roller restaurant with maximum drama — the city visible through every wall',
      'Bangkok floating restaurant on the Chao Phraya with temple lights and gold water',
      'Shinjuku Kabukicho bar street at dinner hour — the neon just firing at full intensity',
    ],
    evening: [
      'Tokyo Shinjuku Golden Gai alley at 9pm — narrow wooden bars spilling light into the lane',
      'Hong Kong rooftop bar at peak evening with harbour and city below in full electric glow',
      'Seoul Itaewon night district as the night reaches full energy — electric, international',
      'Las Vegas casino floor at 10pm — maximum neon, maximum energy, maximum presence',
      'Bangkok rooftop sky bar with the full city electric below and warm night air',
      'Shibuya crossing at 10pm where the scale of the neon makes the human body dramatic',
    ],
    night: [
      'Tokyo 2am in a private karaoke room with neon through the glass and the city sleeping outside',
      'Hong Kong 1am ferry crossing — water black and gold and the city towers reflected',
      'Seoul 3am in a 24-hour diner with the only light being fluorescent and the mood completely real',
      'Las Vegas 4am at the tables where the casino never acknowledges the time',
      'Bangkok midnight rooftop with just city glow and warm air and the river far below',
      'Shinjuku 3am alley bar — two people remaining, neon through glass, perfect silence inside',
    ],
  },

  cameraPool: [
    '35mm f/1.4 wide with neon bokeh flooding foreground and background equally',
    '85mm f/1.2 with neon source directly in frame creating lens flare across portrait',
    '50mm f/1.8 at eye level on rain-reflective pavement with city mirrored below',
    '24mm wide capturing the full scale of the neon cityscape with subject small and central',
    '135mm telephoto compression making the neon layers stack behind the subject',
    '28mm reportage lens for authentic street energy and environmental truth',
  ],

  lightingPool: [
    'primary neon fill from magenta shop signage at 3200K mixed with cyan LED from building face',
    'single pink neon tube as key light directly above — brutal, editorial, electric',
    'Hong Kong street — gold warm below from restaurant light, cool blue above from tower glass',
    'Las Vegas maximum output — seven competing light sources across every colour temperature',
    'Seoul clean white neon at 4500K with minimal colour contamination — fashion editorial',
    'Bangkok temple gold spill mixed with modern hotel blue pool glow',
    'Tokyo rain reflection — every light source doubled in wet asphalt below',
    'neon through fog or steam creating diffused haloed electric atmosphere',
  ],

  wardrobePool: [
    'black latex or PVC reflecting every neon colour simultaneously',
    'structured black blazer with nothing underneath — city power dressing',
    'sequined mini in silver or gold that multiplies every light source across its surface',
    'fishnet or mesh layered over dark base — letting the neon through the texture',
    'sleek leather trench at knee — commanding the city at midnight',
    'architectural avant-garde fashion piece — Tokyo Harajuku scale ambition',
    'minimal slip dress in white or nude that becomes the screen for coloured neon projection',
    'K-fashion oversize suit with precise tailoring — Seoul editorial energy',
    'holographic or iridescent fabric that shifts colour with every neon source',
  ],

  moodPool: [
    'electric and magnetic — she owns the city at night and the city knows it',
    'nocturnal power — moving through neon like it was designed for her specifically',
    'cyberpunk editorial — fashion-forward, provocative, completely in control',
    'urban solitude — alone in ten million people and completely untouchable',
    'charged and dangerous — the city is a stage and she is the only performance that matters',
    'late-night luxury — the city at its most expensive hour and she belongs here',
  ],
}
