export const STORY_WORLD_POWER_CEO = {
  id: 'power-ceo',
  name: 'Power CEO',
  description:
    'A cinematic world of executive feminine power — glass-tower offices, tailored boardroom presence, private jet ritual, luxury hotel suites, and the rare quality of a woman who runs the room without raising her voice. Elegant, controlled, lethal.',

  geography: { country: 'global corporate / luxury interior', region: 'glass tower, boardroom, executive suite, private jet, luxury hotel' },

  identity: {
    archetype: 'executive power woman',
    vibe: ['tailored boardroom authority', 'glass tower elegance', 'private jet ritual', 'running the room without effort', 'power through composure'],
    tone: ['powerful', 'composed', 'precise', 'elegant', 'controlled', 'cinematic', 'executive'],
    persona: ['the most powerful woman in any room she enters', 'composure as a weapon', 'beautiful and lethal in equal measure', 'the kind of presence that makes every other person adjust'],
  },

  phaseOrder: ['wake', 'morning_refresh', 'getting_dressed', 'breakfast', 'late_morning', 'lunch', 'afternoon', 'reset', 'golden_hour', 'dinner', 'evening', 'night'],

  phases: {
    wake:            { label: 'Wake',            timeWindows: ['early executive morning in hotel suite', 'pre-dawn precision luxury morning'],                   pacing: 'slow',   subLocations: ['executive-suite', 'home-bedroom'] },
    morning_refresh: { label: 'Morning Refresh', timeWindows: ['executive bathroom morning ritual', 'precision self-care before the day'],                        pacing: 'slow',   subLocations: ['executive-bathroom', 'vanity-power'] },
    getting_dressed: { label: 'Getting Dressed', timeWindows: ['tailored dressing morning', 'the power suit selection'],                                          pacing: 'slow',   subLocations: ['wardrobe-power', 'mirror-executive'] },
    breakfast:       { label: 'Breakfast',       timeWindows: ['executive breakfast in hotel or home', 'power breakfast before the day'],                         pacing: 'slow',   subLocations: ['executive-suite', 'hotel-dining'] },
    late_morning:    { label: 'Late Morning',    timeWindows: ['boardroom or glass office morning', 'executive presence in the corporate interior'],               pacing: 'medium', subLocations: ['boardroom', 'glass-office'] },
    lunch:           { label: 'Lunch',           timeWindows: ['power lunch at executive restaurant', 'private dining in executive setting'],                      pacing: 'slow',   subLocations: ['power-lunch', 'executive-dining'] },
    afternoon:       { label: 'Afternoon',       timeWindows: ['afternoon board or glass office executive presence', 'glass tower afternoon in power'],            pacing: 'medium', subLocations: ['glass-office', 'boardroom'] },
    reset:           { label: 'Reset',           timeWindows: ['private executive reset between day and evening', 'hotel suite private reset'],                    pacing: 'slow',   subLocations: ['executive-suite', 'vanity-power'] },
    golden_hour:     { label: 'Golden Hour',     timeWindows: ['glass tower golden-hour with city below', 'executive view at sunset from height'],                pacing: 'slow',   subLocations: ['glass-tower-view', 'executive-suite'] },
    dinner:          { label: 'Dinner',          timeWindows: ['power dinner at private restaurant or suite', 'the executive evening meal'],                       pacing: 'slow',   subLocations: ['executive-dinner', 'hotel-suite-dinner'] },
    evening:         { label: 'Evening',         timeWindows: ['private jet or executive evening transit', 'post-dinner executive suite calm'],                   pacing: 'slow',   subLocations: ['private-jet', 'executive-suite'] },
    night:           { label: 'Night',           timeWindows: ['hotel or executive suite private night', 'the executive world at rest'],                           pacing: 'slow',   subLocations: ['executive-suite', 'home-bedroom'] },
  },

  locations: [
    'executive hotel suite above the city', 'boardroom at glass table with city view', 'glass tower private office with city panorama',
    'power lunch at private restaurant', 'private jet interior in executive leather', 'glass tower at golden hour with city below',
    'executive dinner table in warm private setting', 'executive suite bathroom in clean morning', 'tailored wardrobe dressing ritual',
  ],

  subLocations: {
    'executive-suite': {
      id: 'executive-suite', name: 'Executive Suite', mapAnchor: 'luxury hotel executive suite',
      category: 'private-executive',
      bestPhases: ['wake', 'breakfast', 'reset', 'golden_hour', 'night'],
      overlays: ['luxury executive suite interior', 'city view through tall windows', 'clean precise executive private morning', 'power interior in clean luxury'],
      locations: ['executive hotel suite with city view', 'luxury suite in clean morning light', 'private executive interior in warm morning'],
    },
    'home-bedroom': {
      id: 'home-bedroom', name: 'Executive Home Bedroom', mapAnchor: 'private executive home',
      category: 'private-home',
      bestPhases: ['wake', 'night'],
      overlays: ['sleek luxury home bedroom', 'clean precise interior', 'executive private morning', 'modern luxury home aesthetic'],
      locations: ['executive home bedroom in clean morning light', 'private luxury home in executive morning', 'modern sleek bedroom before the corporate day'],
    },
    'executive-bathroom': {
      id: 'executive-bathroom', name: 'Executive Bathroom', mapAnchor: 'luxury executive bathroom',
      category: 'self-care-power',
      bestPhases: ['morning_refresh'],
      overlays: ['luxury marble bathroom', 'clean precise executive morning light', 'power self-care ritual', 'executive morning routine precision'],
      locations: ['executive marble bathroom in morning', 'clean luxury executive bathroom ritual', 'precise power morning self-care setting'],
    },
    'vanity-power': {
      id: 'vanity-power', name: 'Power Vanity', mapAnchor: 'executive vanity preparation',
      category: 'preparation-executive',
      bestPhases: ['morning_refresh', 'reset'],
      overlays: ['clean lit vanity with executive precision', 'power makeup ritual', 'executive pre-day or pre-evening preparation', 'precise beauty ritual'],
      locations: ['executive vanity in clean morning or evening light', 'power preparation vanity', 'precise executive beauty ritual setting'],
    },
    'wardrobe-power': {
      id: 'wardrobe-power', name: 'Power Wardrobe', mapAnchor: 'tailored executive wardrobe',
      category: 'dressing-executive',
      bestPhases: ['getting_dressed'],
      overlays: ['tailored suits and power pieces organized', 'executive dressing ritual', 'the selection of power through clothing', 'clean luxury wardrobe interior'],
      locations: ['tailored executive wardrobe interior', 'power suit selection zone', 'executive dressing ritual in clean morning'],
    },
    'mirror-executive': {
      id: 'mirror-executive', name: 'Executive Mirror', mapAnchor: 'executive full-length mirror',
      category: 'reflection-power',
      bestPhases: ['getting_dressed'],
      overlays: ['full-length mirror in executive interior', 'precision self-assessment', 'tailored look in executive morning light', 'power mirror check'],
      locations: ['executive full-length mirror in morning light', 'power self-assessment mirror', 'tailored look mirror check in clean interior'],
    },
    'hotel-dining': {
      id: 'hotel-dining', name: 'Hotel Dining', mapAnchor: 'executive hotel breakfast setting',
      category: 'power-breakfast',
      bestPhases: ['breakfast'],
      overlays: ['hotel executive breakfast table', 'clean morning executive dining', 'power breakfast before the corporate day', 'precise luxury morning dining'],
      locations: ['hotel executive breakfast setting', 'power breakfast table in clean morning', 'executive dining in luxury hotel interior'],
    },
    'boardroom': {
      id: 'boardroom', name: 'Boardroom', mapAnchor: 'executive glass boardroom table',
      category: 'corporate-power',
      bestPhases: ['late_morning', 'afternoon'],
      overlays: ['glass boardroom table with city view', 'executive corporate presence', 'power in the most decisive room', 'clean corporate precision'],
      locations: ['glass boardroom table with city panorama', 'executive corporate boardroom interior', 'the most powerful room with a view'],
    },
    'glass-office': {
      id: 'glass-office', name: 'Glass Office', mapAnchor: 'executive glass tower office',
      category: 'office-power',
      bestPhases: ['late_morning', 'afternoon'],
      overlays: ['private glass office with city view', 'executive presence at desk or at glass', 'power in the most elevated office setting', 'city visible behind'],
      locations: ['private executive glass office with city view', 'glass tower office interior', 'executive desk with panoramic city view'],
    },
    'power-lunch': {
      id: 'power-lunch', name: 'Power Lunch', mapAnchor: 'private restaurant power lunch',
      category: 'executive-dining',
      bestPhases: ['lunch'],
      overlays: ['private restaurant or club booth', 'executive power lunch setting', 'white tablecloth and composed power dining', 'the most decisive lunch table'],
      locations: ['private restaurant executive lunch booth', 'power lunch in exclusive restaurant setting', 'executive dining at the most strategic table'],
    },
    'executive-dining': {
      id: 'executive-dining', name: 'Executive Dining', mapAnchor: 'corporate executive dining room',
      category: 'corporate-dining',
      bestPhases: ['lunch'],
      overlays: ['executive corporate dining room', 'white linen and precise corporate table', 'power lunch interior', 'the executive meal setting'],
      locations: ['executive corporate dining in clean precise interior', 'corporate power dining room', 'the executive lunch table'],
    },
    'glass-tower-view': {
      id: 'glass-tower-view', name: 'Glass Tower View', mapAnchor: 'glass tower panoramic view',
      category: 'power-view',
      bestPhases: ['golden_hour'],
      overlays: ['panoramic city view from glass tower', 'executive above the city at golden hour', 'city turning amber from height', 'the most powerful view of the day'],
      locations: ['glass tower floor with panoramic city view at golden hour', 'executive above the city in amber light', 'the most powerful vantage point at dusk'],
    },
    'executive-dinner': {
      id: 'executive-dinner', name: 'Executive Dinner', mapAnchor: 'private executive dinner',
      category: 'power-evening',
      bestPhases: ['dinner'],
      overlays: ['private restaurant dinner table', 'warm executive evening dining', 'the most strategic dinner', 'power and elegance in the evening meal'],
      locations: ['private executive dinner in warm restaurant', 'the most strategic dinner table', 'executive evening dining in warm private setting'],
    },
    'hotel-suite-dinner': {
      id: 'hotel-suite-dinner', name: 'Suite Dinner', mapAnchor: 'hotel suite dinner',
      category: 'private-executive-evening',
      bestPhases: ['dinner'],
      overlays: ['in-suite dining with city view', 'executive private dinner', 'room service in executive luxury', 'private evening dinner above the city'],
      locations: ['executive suite dinner with city view', 'private hotel suite evening dining', 'room service dinner in executive interior'],
    },
    'private-jet': {
      id: 'private-jet', name: 'Private Jet', mapAnchor: 'private jet interior',
      category: 'travel-executive',
      bestPhases: ['evening'],
      overlays: ['private jet interior in executive leather', 'executive travel between power destinations', 'the jet as executive office in transit', 'power in motion'],
      locations: ['private jet leather interior in flight', 'executive in-flight in power transit', 'the jet as the most exclusive executive setting'],
    },
  },

  sceneVariants: {
    wake: ['early executive morning in a hotel suite with clean city light before anyone else', 'the power CEO morning — precise, controlled, and ahead of the world'],
    morning_refresh: ['executive bathroom morning ritual in clean luxury light', 'the power preparation before the corporate day — precise and deliberate'],
    getting_dressed: ['tailored suit selection in the executive wardrobe in clean morning light', 'the power dressing ritual — the suit that commands the boardroom'],
    breakfast: ['executive breakfast with coffee and city view before the day begins', 'hotel power breakfast in clean luxury morning setting'],
    late_morning: ['the boardroom — glass table, city view, and complete executive control', 'standing at the glass office wall with the city panorama below'],
    lunch: ['power lunch at a private restaurant — the most strategic table in the city', 'executive dining with complete composure and authority over white linen'],
    afternoon: ['the glass office in the afternoon — executive presence and complete control', 'the boardroom afternoon — decisions, authority, and complete power'],
    reset: ['executive suite reset between day and evening — the private recalibration moment', 'changing from corporate to evening look in the hotel suite'],
    golden_hour: ['the glass tower at golden hour — city turning amber below from executive height', 'the most powerful moment of the executive day'],
    dinner: ['power dinner at a private restaurant with complete executive elegance', 'the most strategic evening meal with composed authority'],
    evening: ['private jet in the executive evening — in-flight above the world between destinations', 'executive suite calm after the corporate day is complete'],
    night: ['the executive at rest in private hotel suite quiet', 'the power CEO in private luxury night — the day is won'],
  },

  actionPools: {
    wake: [
      'early executive morning rise in luxury suite before the world',
      'checking the morning brief before leaving the executive bed',
      'the CEO morning — precise and private before anyone else begins',
      'standing at the hotel suite window in the early quiet, city still dark below',
      'reaching for the phone on the bedside — the first executive decision of the day',
      'sitting upright at the edge of the executive bed, composure already in place before rising',
    ],
    morning_refresh: [
      'precise executive bathroom morning ritual at the marble mirror',
      'applying executive beauty in clean luxury bathroom light',
      'the power morning preparation at the executive vanity',
      'standing at the marble sink in clean morning light, the CEO assembling herself before the world',
      'executive skincare ritual applied with deliberate precision in clean bathroom light',
      'blowdrying in the executive bathroom — each movement measured, no wasted motion',
    ],
    getting_dressed: [
      'selecting the tailored suit for the boardroom with precision',
      'executive mirror assessment of the complete power look',
      'the precise executive dressing ritual — every detail deliberately controlled',
      'fastening the single button of a structured blazer at the executive mirror',
      'sliding on the power watch — the last detail before the CEO is complete',
      'standing at the full-length mirror with both hands adjusting the jacket collar in clean morning light',
    ],
    breakfast: [
      'executive breakfast with coffee and city view in hotel suite',
      'the power breakfast — fuel and precision before the corporate world',
      'hotel executive dining in clean morning luxury before the day',
      'seated at the hotel breakfast table with espresso and the morning brief open beside it',
      'standing at the executive suite window with black coffee, reviewing the day before leaving',
      'hotel breakfast — one precise movement: lifting the espresso, reviewing the agenda, deciding',
    ],
    late_morning: [
      'standing at the boardroom head position with full city panorama behind',
      'the glass office — at the desk or standing at floor-to-ceiling window above the city',
      'executive corporate presence in the most powerful room',
      'standing at the boardroom window with both hands resting on the glass, looking down at the city with composure',
      'seated at the head of the glass table, device closed, the room entirely hers',
      'walking slowly through the boardroom interior toward the window — the room adjusts as she moves',
    ],
    lunch: [
      'the power lunch — at the most strategic table in the city restaurant',
      'executive composed dining with complete authority and grace at white linen',
      'the lunch that runs the world from the most important table',
      'arriving at the private restaurant booth — the room notes her entrance before she sits',
      'seated at the power lunch — wine untouched, every word calculated, the table working',
      'finishing the power lunch with composed precision — nothing left unresolved',
    ],
    afternoon: [
      'executive boardroom afternoon — decisions and full corporate authority',
      'glass office in the afternoon — work, authority, and complete controlled power',
      'the CEO afternoon in full corporate executive presence',
      'standing at the floor-to-ceiling office glass in afternoon light, one hand on the frame, city below',
      'leaning against the boardroom table edge — listening, deciding, the room still',
      'returning to the executive desk in afternoon light, the second act of power in full motion',
    ],
    reset: [
      'hotel suite private reset between the corporate day and evening',
      'executive vanity reset — changing from corporate to evening look in privacy',
      'the power recalibration in private executive interior',
      'removing the blazer in the hotel suite — the first moment of the transition',
      'seated at the vanity in the soft late-afternoon suite light, rebuilding the evening look',
      'standing in the executive suite in the shift between corporate and dinner — the quiet between two versions of herself',
    ],
    golden_hour: [
      'standing at the glass tower window as the city turns amber below',
      'the golden hour above the city — the most powerful executive view of the day',
      'the CEO in the most cinematic moment at height above the city',
      'one hand resting on the glass tower wall, the city amber-lit forty floors below, composure absolute',
      'turning slowly from the glass as the light shifts — the most deliberate executive pause of the day',
      'standing still at the panoramic glass as golden light fills the executive interior, the city transforming below',
    ],
    dinner: [
      'power dinner at private restaurant with complete composure and elegance',
      'the strategic executive evening meal — precise and beautiful',
      'the CEO at dinner — the most powerful table in the room',
      'arriving at the private restaurant with the particular calm that makes the maitre d move faster',
      'seated at dinner — candle lit, wine poured, every detail of the evening in her control',
      'the executive dinner — one hand on the stem of the wine glass, the conversation completely hers',
    ],
    evening: [
      'private jet in-flight between power destinations in executive leather',
      'executive suite after the corporate day — private calm after a full day of power',
      'the CEO in the most private executive evening interior',
      'settled into the private jet leather seat, the city receding below through the oval window',
      'the executive suite after the day — blazer off, the city quiet through the glass, day done',
      'private jet above the clouds between power destinations — the world below, work complete',
    ],
    night: [
      'the executive night in luxury hotel or home — private and complete',
      'the CEO at rest in private suite after the day is won',
      'the power woman in private night luxury at the end of the corporate day',
      'sitting at the edge of the executive suite bed, the city glow faint through the glass, composure finally at ease',
      'the hotel suite at night — watch removed, the day filed away, the CEO briefly simply herself',
      'lying in the executive suite bed in the warm city-glow dark — tomorrow already planned',
    ],
  },

  environmentPools: {
    wake: [
      'executive hotel suite in clean early morning light with city view through tall windows',
      'sleek luxury home bedroom before the corporate day begins',
      'private executive suite in precise early morning interior',
      'executive hotel suite above the 40th floor, city grid visible through floor-to-ceiling glass in morning',
      'luxury corporate hotel bedroom with clean white linen and the city barely lit below in pre-dawn quiet',
      'executive home master bedroom in modern luxury interior, city visible beyond the terrace glass in early morning',
    ],
    morning_refresh: [
      'luxury marble executive bathroom in clean morning light',
      'executive vanity in precise morning light',
      'clean power morning self-care setting in luxury executive interior',
      'executive marble bathroom with double-height mirror and clean 6000K morning light from above',
      'white marble executive vanity with professional light bar, every surface precise and clean',
      'executive hotel suite bathroom in full clean morning — the most precise private self-care setting',
    ],
    getting_dressed: [
      'tailored executive wardrobe interior in clean morning light',
      'full-length mirror in executive morning interior',
      'power dressing zone in clean precise morning light',
      'walk-in executive wardrobe with suits organized by color, clean white interior light, the power selection made deliberately',
      'executive mirror in clean side-lit morning interior, the complete tailored look being assessed from head to toe',
      'hotel suite dressing area in clean morning — the tailored pieces laid out, every accessory in position',
    ],
    breakfast: [
      'hotel executive breakfast table in clean luxury morning',
      'suite breakfast with city view and executive precision',
      'power breakfast setting in clean luxury hotel interior',
      'hotel executive suite breakfast corner — small table, white linen, espresso, city visible through tall glass',
      'private executive hotel dining room in clean morning light with white tablecloth and no noise',
      'executive suite with breakfast tray on the table and the full city panorama behind in morning clarity',
    ],
    late_morning: [
      'glass boardroom table with city panorama visible behind through floor-to-ceiling glass',
      'private glass office with floor-to-ceiling city view at executive height',
      'the most powerful corporate interior in clean morning light',
      'glass boardroom table reflecting the sky, city panorama forty floors below through full-wall glass panels',
      'executive private office — desk facing the city, glass floor-to-ceiling on three sides, authority in every surface',
      'boardroom in clean late-morning corporate light — the city below, the table long, the room hers',
    ],
    lunch: [
      'private restaurant power lunch booth or table in elegant setting',
      'executive corporate dining room with white linen and precision',
      'the most strategic and elegant lunch setting',
      'private members club booth with deep leather, white tablecloth, and one discreet window overlooking the city',
      'executive restaurant private room — no noise except what she allows, the most important table precisely set',
      'corner power table at the city\'s most strategic restaurant, city view at angle, white linen, the setting says everything',
    ],
    afternoon: [
      'glass office in afternoon executive light with city panorama behind',
      'boardroom in afternoon corporate executive energy and authority',
      'the CEO in full afternoon corporate authority at executive interior',
      'executive glass office in afternoon westward sun — the city in direct light behind the seated CEO',
      'boardroom in post-lunch afternoon clarity — the city visible, the table cleared, authority at full',
      'glass tower office in late-afternoon slant light, the CEO at her desk in the room that belongs entirely to her',
    ],
    reset: [
      'executive hotel suite in warm private afternoon reset',
      'executive vanity in soft late-afternoon light for the wardrobe change',
      'private corporate suite between the day and the evening',
      'hotel executive suite in warm 4000K late-afternoon — the corporate day physically left at the door',
      'private executive bathroom in the transitional hour, warm interior as the evening look is assembled',
      'suite dressing area in warm golden-late-afternoon hotel light — blazer on the chair, evening look in progress',
    ],
    golden_hour: [
      'glass tower floor with city panorama turning amber at golden hour',
      'executive suite window with city golden through the glass in the evening',
      'the most powerful vantage point at golden hour above the city',
      'glass tower executive floor at golden hour — the city dissolving in amber from forty floors up',
      'executive glass office with the western city panorama turning orange-gold, the light entering low and warm',
      'floor-to-ceiling corporate glass at the highest executive point, the entire cityscape amber and still below',
    ],
    dinner: [
      'private restaurant in warm executive evening setting',
      'executive hotel suite dinner with city view through the glass',
      'the most strategic dinner table in warm executive lighting',
      'private restaurant — corner table, warm 2800K ambient, the room quiet enough to hear the executive conversation only',
      'exclusive private dining room at the city\'s most prestigious address, candlelit and composed',
      'executive suite in-room dining with white tablecloth and the full city golden through the tall windows',
    ],
    evening: [
      'private jet leather interior in executive travel above the world',
      'executive hotel suite in private calm after the corporate day',
      'the CEO in the most private and elevated evening setting',
      'private jet cabin in executive leather — oval windows dark, interior amber, the world far below',
      'executive suite with the city night-lit through the glass, the day at rest, the evening interior warm',
      'corporate aviation lounge before boarding — clean, private, the CEO between two power cities',
    ],
    night: [
      'executive hotel suite in warm private night',
      'luxury home bedroom in clean precise night interior',
      'the power CEO at private rest in luxury executive interior',
      'executive suite with the city glow soft through the glass, the interior warm and private at night',
      'luxury home master bedroom in clean night light — the corporate world complete, the private world restored',
      'hotel suite at night — city visible as ambient light only, the CEO at the most private point of the day',
    ],
  },

  moodPools: {
    wake: [
      'precise executive morning before the world begins',
      'the CEO morning — controlled, alone, and powerful',
      'early executive luxury quiet before the corporate world opens',
      'controlled authority — the room was hers before she spoke',
      'pre-dawn executive stillness — the day already decided before it begins',
      'the quiet before the most powerful version of herself begins',
    ],
    morning_refresh: [
      'power self-care ritual — precise, controlled, efficient',
      'executive preparation energy in clean morning luxury',
      'the morning that creates the day before the boardroom',
      'the private assembly of authority — no audience, no performance, only precision',
      'executive beauty as competitive preparation — every detail a decision',
      'clean sharp morning focus — the CEO building her armor in private',
    ],
    getting_dressed: [
      'tailored authority selection — choosing power through fabric',
      'the executive dressing ritual — precise and completely controlled',
      'the suit as weapon, the look as strategy',
      'deliberate assembly of identity — the suit is the first boardroom move',
      'the controlled pleasure of dressing with intent — every detail a message',
      'power through precision — the tailored look as a complete statement of authority',
    ],
    breakfast: [
      'executive precision and fuel before the corporate day',
      'power breakfast energy — clean, controlled, ahead of everyone',
      'hotel morning luxury with executive authority',
      'the quiet confidence of being first — breakfast before the city wakes',
      'fueling with discipline — the CEO at the table is already in the boardroom',
      'executive morning composure at the breakfast table — the agenda already in her head',
    ],
    late_morning: [
      'complete boardroom authority — the room responds to her',
      'glass office executive power at maximum corporate presence',
      'the most controlled and powerful presence in any corporate space',
      'absolute authority — no movement in the room that she did not allow',
      'boardroom command so complete it reads as effortless',
      'the glass office in full executive morning — the city below, the power absolute',
    ],
    lunch: [
      'power lunch ease — strategic and composed over the most important table',
      'executive dining authority with elegance at white linen',
      'the CEO at lunch — composed, strategic, and in complete control',
      'the strategic table — every word placed like a chess piece',
      'composed power dining — the lunch is the meeting and she is winning',
      'executive elegance that makes the other side of the table careful',
    ],
    afternoon: [
      'executive authority in full afternoon corporate flow',
      'the boardroom afternoon — decisions and complete power',
      'the glass office in full executive afternoon energy and presence',
      'afternoon authority — the CEO in the second wave of peak corporate power',
      'decisive afternoon energy — the glass office belongs to her completely',
      'the corporate afternoon at maximum — decisions made, authority unquestioned',
    ],
    reset: [
      'private executive recalibration — from corporate to evening',
      'the CEO between worlds — transitioning in private luxury',
      'executive composure in private reset mode',
      'the armour softening — the CEO private and briefly fully human',
      'controlled transition — the corporate day exhaled in the suite before the evening',
      'the quiet shift from power suit to evening elegance in private',
    ],
    golden_hour: [
      'the most powerful executive view — above the city at golden hour',
      'the CEO above everything at the most cinematic executive moment',
      'glass tower golden hour — authority and beauty simultaneously',
      'the city turning amber below her — the most beautiful executive pause of the day',
      'elevated composure at golden hour — power through stillness, the city as backdrop',
      'the defining executive moment — above the city she runs, in the most beautiful light of the day',
    ],
    dinner: [
      'the strategic power dinner — composed, precise, and elegant',
      'executive evening authority at the most prestigious table',
      'the CEO at dinner — the most controlled and beautiful version',
      'power dinner elegance — the evening version of the executive at maximum',
      'dinner as strategy — composed, warm on the surface, entirely in control beneath',
      'the most beautiful executive moment of the evening — authority in the most elegant setting',
    ],
    evening: [
      'private jet executive peace — above the world in transit',
      'executive suite calm after the corporate day is complete',
      'the CEO in private luxury after maximum power day',
      'the private jet above the clouds — the most exclusive executive peace',
      'executive evening composure in transit — the world below, the next destination already planned',
      'the hotel suite at rest after the full day — the CEO in private calm, authority at ease',
    ],
    night: [
      'executive private luxury at rest — the day won completely',
      'the power CEO in private night warmth',
      'the most private and calm version of the executive after the corporate world is done',
      'the CEO at night — authority at ease in warm private suite quiet',
      'the day complete and filed — the executive at rest in warm luxury',
      'private night ease after maximum corporate day — the power woman fully herself',
    ],
  },

  cameraPools: {
    wake: [
      '85mm low angle in executive suite, city window dissolved behind in morning bokeh',
      '135mm close-up at face height, clean early morning executive light defining edge of subject',
      '50mm executive suite medium, tall city windows behind with first light entering clean',
      '85mm f/1.4 — executive eye level from pillow height, glass tower compression, city dissolved in distance bokeh',
      '135mm f/2 — tight face close-up, early executive morning, single edge-lit window giving precise definition',
      '50mm f/2 — three-quarter executive suite wide, the city window as environmental anchor behind subject',
    ],
    morning_refresh: [
      '85mm executive bathroom mirror close, precise reflection at same focal plane',
      '50mm executive vanity mid shot, clean morning light compressing behind subject',
      '135mm f/2 — clean bathroom close-up, marble surface sharp, background compressed to soft luxury',
      '85mm f/1.8 — executive vanity medium, subject at precise focal plane, mirror depth behind',
      '50mm f/2.8 — vanity wide, both subject and reflection in frame, clean symmetry of the power preparation',
      '35mm f/2 — executive bathroom environmental, marble architecture visible, clean directional morning fill',
    ],
    getting_dressed: [
      '50mm power wardrobe or executive mirror framed shot, tailored pieces visible behind',
      '85mm mid-length executive dressing angle, clean executive interior depth behind subject',
      '135mm f/2 — blazer detail close-up, the tailored fabric sharp, executive interior dissolved behind',
      '85mm f/1.4 — full-length mirror shot with subject and reflection both in frame, executive wardrobe behind',
      '50mm f/2 — executive dressing wide, the organised wardrobe behind as architecture of power',
      '35mm f/2.8 — environmental executive wardrobe, subject dressing at left, tailored pieces filling right background',
    ],
    breakfast: [
      '24mm wide executive suite breakfast, city view filling background beyond the table',
      '85mm soft executive breakfast framing, city panorama dissolved in background behind',
      '50mm f/2 — executive hotel breakfast table, white linen sharp, city window at background right',
      '85mm f/1.4 — breakfast close, espresso cup in foreground, CEO face at mid-ground, city glass behind dissolved',
      '35mm f/2 — wide executive suite breakfast, full city panorama visible through tall windows behind',
      '135mm f/2.5 — tight executive morning close, the espresso and clean hands precise, suite depth behind',
    ],
    late_morning: [
      '85mm boardroom executive medium, city panorama behind through glass behind subject',
      '50mm glass office corporate framing, city visible through floor-to-ceiling glass behind subject',
      '135mm f/2 — boardroom tight, city bokeh visible through glass wall behind, CEO sharp at center',
      '85mm f/1.8 — glass office standing at window, city compression visible behind, executive silhouette defined',
      '24mm f/4 — wide boardroom, full glass wall and city panorama as environment, CEO at table center',
      '50mm f/2.8 — corporate executive desk framing, city in full clarity through glass behind subject',
    ],
    lunch: [
      '85mm power lunch seated portrait, restaurant depth compressed behind subject',
      '50mm executive dining side, white linen and restaurant interior depth behind subject',
      '135mm f/2 — power lunch close-up, white linen and candlelight sharp, restaurant ambient behind',
      '85mm f/1.8 — executive lunch three-quarter, restaurant booth depth dissolved, subject precise',
      '50mm f/2 — executive dining wide, private room interior and white tablecloth as clean environment',
      '35mm f/2.8 — power restaurant environmental, CEO at table with full private dining room behind',
    ],
    afternoon: [
      '85mm glass office afternoon, city panorama behind in afternoon light',
      '50mm boardroom afternoon, corporate interior depth behind subject in power',
      '135mm f/2 — executive desk afternoon close, city glass behind in westward sun, CEO sharp',
      '85mm f/1.4 — boardroom window standing shot, afternoon city light coming through glass behind subject',
      '50mm f/2 — glass office wide in afternoon, city panorama as full-wall background behind desk',
      '35mm f/2.8 — executive afternoon environmental, slant corporate light from glass walls, CEO at authority',
    ],
    reset: [
      '85mm executive suite vanity reset, warm interior depth dissolved behind subject',
      '135mm close executive reset, warm late-afternoon hotel interior behind subject',
      '85mm f/1.4 — suite reset close, warm 3800K hotel interior dissolving behind, subject in transition',
      '135mm f/2 — vanity mirror tight, warm amber hotel suite light, CEO in the moment between looks',
      '50mm f/2 — executive suite reset medium, warm interior with city window soft behind subject',
      '35mm f/2 — suite environmental reset, the full private executive interior visible as she transitions',
    ],
    golden_hour: [
      '135mm glass tower golden-hour close, amber city rim light from below defining edge',
      '24mm wide glass tower shot, entire city turning gold in background below through glass',
      '85mm f/1.4 — executive golden-hour portrait, warm amber rim from city below, background dissolving',
      '135mm f/2 — tight CEO close at the glass tower, amber city light as backlight defining jaw and shoulder',
      '50mm f/2 — glass tower medium at golden hour, CEO at window with full amber city panorama behind',
      '24mm f/4 — wide glass tower floor, CEO standing at glass, full city visible and gold in background',
    ],
    dinner: [
      '85mm executive dinner candlelit portrait, warm restaurant ambient compressed behind',
      '50mm power dinner side, executive restaurant interior depth compressed behind subject',
      '135mm f/2 — executive dinner close, candle as key light, warm restaurant ambient behind',
      '85mm f/1.4 — power dinner portrait, single candle key with warm bokeh restaurant behind',
      '50mm f/2 — executive dinner wide, private dining room as warm composed environment behind',
      '35mm f/2 — executive dinner environmental, the full restaurant private room in warm 2800K behind',
    ],
    evening: [
      '85mm private jet interior, leather seat depth behind subject in executive travel',
      '135mm intimate executive evening close in jet or suite interior',
      '85mm f/1.4 — private jet close-up, warm leather interior as background, oval window dark beyond',
      '135mm f/2 — executive suite evening tight, warm city glow through window behind subject',
      '50mm f/2 — jet cabin medium, executive leather environment, oval window as background element',
      '35mm f/2.8 — private jet environmental wide, full cabin interior, CEO settled in leather seat',
    ],
    night: [
      '135mm executive suite night close-up, city glow through window as background behind',
      '85mm soft side angle, warm executive suite night, luxury room dissolved behind subject',
      '135mm f/2 — executive night close, single warm bedside lamp as sole source, city glow faint beyond',
      '85mm f/1.4 — suite night portrait, warm 2400K interior, city through glass as ambient background',
      '50mm f/2 — executive bedroom night medium, warm private interior, city glow through window',
      '35mm f/1.8 — executive suite night environmental, the full private room visible in warm low ambient',
    ],
  },

  lightingPools: {
    wake: [
      'clean 6000K executive morning light entering through hotel suite glass, precise and controlled',
      'pale early morning through executive curtains, clean and directional',
      '5800K pre-dawn executive suite light — blue-white precision entering through floor-to-ceiling glass',
      '6200K clean corporate morning, the first light entering the executive suite from the city below',
      'cool 5500K morning entering the hotel glass — hard directional, the city still dark outside, precision in the room',
      'pale executive dawn, single window source at 6000K, clean edge on the subject, room in clean shadow',
    ],
    morning_refresh: [
      '5800K clean executive bathroom light, precise and flattering on marble',
      'clean morning executive vanity light — bright and precise',
      '6000K executive bathroom overhead — clean and controlled on marble, no fill bleed',
      'precise 5600K vanity bar light — even, flattering, professional, no warmth or romanticism',
      '5800K clean corporate morning — even, precise, professional, no warm romanticism',
      'bright 5500K executive bathroom with clean bilateral marble fill, precise enough to see every detail',
    ],
    getting_dressed: [
      'clean 5600K executive interior morning, fabric textures sharp, no soft ambient fill',
      'bright precise executive morning through wardrobe window, clean color rendering',
      '5400K executive wardrobe morning — clean side-window light, tailored textures in sharp definition',
      'directional 5600K morning light entering the dressing area, the suit fabric reading precisely',
      'clean corporate morning at 5500K — even and bright, the entire tailored look rendered without flattery or distortion',
      'precise 5800K executive dressing light, the mirror giving clean bilateral definition on the complete look',
    ],
    breakfast: [
      'clean 5400K hotel executive breakfast, morning sun on white linen and porcelain',
      'executive suite morning breakfast light — clean, precise, powerful',
      '5200K clean hotel executive breakfast morning, secondary fill from white tablecloth below',
      'directional 5400K entering the hotel suite breakfast area through glass, the white linen creating clean fill',
      'clean breakfast morning at 5000K — the espresso black, the linen white, the light even and corporate',
      'early corporate breakfast at 5600K — clean, controlled, professional, the city behind in matching morning clarity',
    ],
    late_morning: [
      '5000K glass tower daylight through floor-to-ceiling glass, hard directional on corporate surfaces',
      'clean corporate noon light, maximum clarity and precision',
      '4800K clean corporate late-morning through glass wall — hard, even, precise on the boardroom table',
      'directional glass tower 5000K — the city behind in sharp clarity, the executive surfaces in controlled light',
      'maximum corporate clarity at 5200K — glass tower daylight with secondary fill from the reflective table surface',
      'clean 5000K corporate morning, the glass walls creating even fill across the boardroom from multiple directions',
    ],
    lunch: [
      'warm 4600K private restaurant lunch, shaded table with window brightness as backlight',
      'clean elegant restaurant midday, precise fill on white linen',
      '4400K warm private restaurant lunch — controlled interior with directional window backlight',
      'elegant 4200K restaurant midday, the white linen creating fill below the subject',
      'warm executive lunch at 4600K — rich enough to feel intimate, precise enough to feel controlled',
      'private restaurant 4400K with warm side fill from interior sconces, the window creating clean backlight',
    ],
    afternoon: [
      'clean 4800K glass office afternoon, hard directional sun through glass on corporate interior',
      'precise corporate afternoon light — bright and completely controlled',
      'westward glass tower afternoon at 4600K — the city in direct sun behind, the CEO in controlled interior light',
      '4800K corporate afternoon, the glass wall behind the executive creating dramatic separation',
      'strong 4600K afternoon through floor-to-ceiling glass, the corporate interior surfaces lit hard and precise',
      'afternoon glass tower light at 4800K — the city at maximum brightness behind, the CEO at maximum corporate authority',
    ],
    reset: [
      'warm 3800K executive suite reset, late afternoon soft through hotel curtains',
      'soft 4000K executive hotel interior in private late-afternoon reset',
      '3600K warm hotel suite in reset — single curtained window source, warm amber fill in private interior',
      'warm 3800K executive suite, the corporate day softening in private hotel light',
      '4000K hotel suite in transitional late-afternoon, warm and controlled for the evening preparation',
      'soft 3500K executive reset light — warm interior, curtains drawn, the private space between corporate and evening',
    ],
    golden_hour: [
      'rich 2900K golden city light entering glass tower windows from below at angle',
      'warm amber city golden-hour through floor-to-ceiling glass — most powerful executive light',
      '2700K amber city light entering the glass tower at a low angle, everything gold',
      'warm 3000K golden hour through executive glass — city amber below, the room turning gold',
      '2800K rich amber entering from below through the tower glass, the executive face lit from the city itself',
      'golden city hour at 2900K — the most cinematic executive light, amber rim and warm fill from the glass',
    ],
    dinner: [
      'warm 2800K private restaurant evening, intimate but elegant and controlled',
      'executive dinner at 2600K — warm, precise, and composed',
      'warm 2800K private restaurant, single candle as key light, warm sconce fill creating precision',
      'candlelit executive dinner at 2400K — intimate and composed, warm on white linen',
      '2600K warm restaurant evening — the ambient precise, the candlelight creating elegant fill',
      'warm 2800K executive dinner, the candle key and warm ambient working in complete control',
    ],
    evening: [
      'warm 3000K private jet interior leather ambient',
      'executive suite 2800K evening warm ambient in private calm',
      '2800K jet interior warm leather ambient — soft, private, composed',
      'private jet at 3000K — warm cabin ceiling ambient and reading light, oval window dark beyond',
      '2600K executive suite evening warm ambient — city glow through the glass as secondary source',
      'warm 2800K private jet leather interior, single overhead as key with warm leather ambient filling',
    ],
    night: [
      'warm 2400K executive suite night — single warm source, city glow visible through glass',
      'clean warm 2600K executive bedroom night — precise and warm',
      '2200K single bedside lamp in executive suite — warm precise point source, city glow faint beyond',
      'warm 2400K executive night, city ambient through the glass as secondary fill at the edge',
      '2600K executive bedroom night — warm single source, the precision maintained even in rest',
      'executive suite night at 2200K — warm, private, the city a soft glow visible through the dark glass',
    ],
  },

  stylingPools: {
    wardrobe: {
      wake: [
        'silk or minimal in executive suite morning',
        'clean private executive morning before the suit',
        'luxury hotel sleep styling in executive interior',
        'white silk slip or nothing — the CEO before the armour in clean luxury hotel morning',
        'luxury modal nightwear in executive suite — minimal and precisely chosen even at rest',
        'the CEO waking in clean hotel white — before any choice has been made, before the suit',
      ],
      morning_refresh: [
        'executive morning robe or nothing in marble bathroom',
        'white towel in clean executive morning ritual',
        'pre-suit executive self-care interior look',
        'white hotel robe open at the vanity — the CEO assembling herself before the corporate world',
        'nothing and a white towel in the executive bathroom — the most private version before the armour',
        'structured hotel robe at the executive vanity, no makeup yet, the morning ritual in progress',
      ],
      getting_dressed: [
        'tailored power suit — structured jacket, precise trouser or skirt',
        'executive blazer with minimal clean interior look',
        'the CEO power look — every detail serving authority',
        'charcoal tailored blazer, single button, nothing underneath — the power suit as its own complete statement',
        'bone white structured jacket over a clean silk blouse, the precision saying everything without speaking',
        'black tailored trousers and a precisely structured blazer — the boardroom look assembled with deliberate intent',
      ],
      breakfast: [
        'executive morning look — blazer or structured jacket before the day fully begins',
        'clean precise morning executive styling for hotel breakfast',
        'power morning look in luxury hotel interior',
        'tailored trousers and silk blouse for the hotel breakfast — fully assembled before the corporate world begins',
        'structured blazer worn over the breakfast table — the CEO never undressed for the day',
        'clean executive morning look at the breakfast table — precise, composed, ready before the boardroom calls',
      ],
      late_morning: [
        'full boardroom power look — tailored jacket, precise accessories at maximum authority',
        'executive corporate interior look at peak authority in the boardroom',
        'the most powerful tailored look of the executive day',
        'dark structured blazer and tailored trousers — the boardroom look at full authority',
        'ivory structured jacket with clean accessories — executive precision from collar to watch to shoe',
        'the complete power CEO look at the glass table — tailored, precise, nothing casual in any detail',
      ],
      lunch: [
        'power lunch look — elevated but efficient and strategic',
        'executive dining styling — tailored and precise',
        'the CEO at lunch — composed corporate elegance',
        'tailored blazer at the power lunch table — still fully in corporate authority over white linen',
        'structured jacket slightly softened for lunch — the same precision, fractionally more composed',
        'the executive at the strategic table — full corporate look, the suit saying as much as the conversation',
      ],
      afternoon: [
        'executive afternoon corporate look — still fully in authority at the glass office',
        'boardroom afternoon tailored precision',
        'corporate power afternoon in complete executive styling',
        'structured corporate afternoon — blazer on, the afternoon as the second act of full executive presence',
        'dark tailored afternoon look — the CEO at the glass office desk in complete authority',
        'full corporate styling at afternoon peak — nothing relaxed, the glass office as the CEO\'s most controlled space',
      ],
      reset: [
        'transitioning from corporate to evening — the reset moment in hotel suite',
        'from power suit to executive evening look in private suite',
        'the executive between two power versions of herself',
        'blazer off in the hotel suite, the day suspended — the transition beginning',
        'evening look laid out beside the corporate suit — the CEO choosing between two versions of authority',
        'the suite reset — the corporate armour removed, the evening look being assembled with equal precision',
      ],
      golden_hour: [
        'executive evening look at golden-hour height — elevated from corporate look',
        'the CEO at golden hour — more elegant version of executive authority',
        'executive evening presence above the city at golden hour',
        'silk executive dress or elevated blazer-dress at golden hour — the corporate precision softer, the authority stronger',
        'the evening CEO at the glass tower — structured and beautiful in the amber light above the city',
        'elevated executive evening at golden hour — the second look, more elegant, equally precise',
      ],
      dinner: [
        'executive evening look — tailored but sensual and elegant at the dinner table',
        'power dinner styling — precise, elevated, and composed',
        'the CEO at dinner — the most powerful evening look',
        'the power dinner look — clean structured dress, statement jewelry, composed from every angle',
        'executive evening at the dinner table — the evening suit or structured dress, elevated and controlled',
        'dinner CEO styling — the most elegant authority, warm but precise, beautiful and deliberate',
      ],
      evening: [
        'private jet executive travel look — composed and above comfort',
        'executive evening suite look — private but precisely styled',
        'the CEO in the most private exclusive evening mode',
        'private jet travel look — structured but comfortable, the CEO in transit between power versions',
        'executive suite evening look — silk trouser and clean blouse, the evening after the suit',
        'the jet in-flight look — composed executive travel styling, still precise even above the clouds',
      ],
      night: [
        'executive luxury nightwear in private suite',
        'the CEO at rest — clean minimal luxury night styling',
        'private luxury executive night look',
        'white silk slip or luxury nightwear — the CEO at the most private end of the day',
        'clean modal or silk in the executive suite at night — minimal and precise even in rest',
        'private luxury hotel nightwear — the power woman at rest, the day stripped back to the private human',
      ],
    },
    details: {
      wake: ['clean face before the executive world begins', 'minimal morning executive detail', 'luxury morning private executive detail'],
      morning_refresh: ['executive beauty precision being applied at the vanity', 'clean power makeup beginning at the mirror', 'precise executive self-care in clean bathroom light'],
      getting_dressed: ['watch — the executive power accessory being fastened', 'diamond or gold stud earring being placed on', 'tailored jacket collar precisely set in mirror check'],
      breakfast: ['watch visible at executive breakfast table', 'executive brief or phone on clean morning table', 'coffee and clean executive detail at the breakfast setting'],
      late_morning: ['power watch and structured accessory at the boardroom table', 'executive pen or device in hand at the glass table', 'the most powerful accessory detail in the corporate interior'],
      lunch: ['watch and clean executive jewelry at the power lunch table', 'the strategic glass of wine or water at the executive table', 'executive composed detail at the most strategic lunch setting'],
      afternoon: ['executive device or glass at desk or boardroom in afternoon', 'watch and clean corporate accessory in glass office', 'the executive afternoon detail in glass tower office'],
      reset: ['executive jewelry changing from corporate to evening look', 'the shift in accessories from boardroom to dinner', 'executive beauty detail in hotel suite reset at vanity'],
      golden_hour: ['elevated evening jewelry at the glass tower golden hour', 'the CEO above the city — watch and elevated accessory in amber light', 'executive golden-hour accessory detail'],
      dinner: ['executive dinner jewelry — elevated and composed at the dinner table', 'the CEO at dinner — watch, earrings, and precise detail', 'power dinner styling detail at the most strategic table'],
      evening: ['executive travel watch in the private jet interior', 'the CEO in transit — clean precise private jet detail', 'executive evening in private mode'],
      night: ['executive relaxing — watch removed, clean detail', 'private luxury hotel night detail', 'the CEO at rest — minimal clean private luxury night'],
    },
    changeMoments: {
      wake: ['in luxury hotel or home sleep state — before the CEO begins', 'the private pre-executive morning moment'],
      morning_refresh: ['between sleep and the power suit — in the executive bathroom ritual', 'the CEO before the armour is on'],
      getting_dressed: ['the power suit selection — the armour being assembled deliberately', 'in the executive wardrobe becoming the CEO'],
      breakfast: ['in the executive morning look before the boardroom', 'the CEO assembled and ready for the corporate day'],
      late_morning: ['in full corporate authority look — the boardroom CEO', 'the most tailored and powerful version in full corporate setting'],
      lunch: ['still in corporate authority look at the power lunch', 'the CEO at the strategic table in full executive styling'],
      afternoon: ['full corporate afternoon — the CEO at maximum authority', 'tailored executive look in the glass office and boardroom'],
      reset: ['transitioning from corporate to evening in the private suite', 'between the CEO and the executive evening woman'],
      golden_hour: ['elevated executive evening look at golden hour above the city', 'the CEO above the city in the more elegant evening version'],
      dinner: ['executive evening look — the CEO at dinner in the most powerful table', 'fully transitioned to the most elegant executive version'],
      evening: ['private jet or suite executive evening private mode', 'the CEO in transit or private — still composed but at ease'],
      night: ['the executive at private rest — CEO unwound in luxury', 'the most private version of the power woman at night'],
    },
  },

  sensoryPools: {
    wake: ['clean precise hotel suite morning with city below barely visible yet', 'the scent of power morning in luxury executive interior', 'total private executive morning before the corporate world'],
    morning_refresh: ['clean marble and luxury executive beauty in morning precision', 'the ritual of executive self-care in clean powerful morning light', 'precise cold morning bathroom and warm vanity light'],
    getting_dressed: ['tailored fabric against skin — the feel of authority in clothing', 'cool watch clasp on the wrist — the executive accessory', 'the luxury of the most perfectly tailored clothing in the world'],
    breakfast: ['executive breakfast coffee in clean morning hotel luxury', 'the precision of hotel executive service in clean morning', 'clean powerful morning before the corporate world begins'],
    late_morning: ['the boardroom — glass table, clean air, city panorama below', 'the glass office with floor-to-ceiling view and executive quiet', 'the sensory precision of the most powerful corporate space'],
    lunch: ['white linen and executive restaurant air at the power lunch', 'the composed pleasure of executive dining with strategic intent', 'the most elegant strategic lunch setting in the city'],
    afternoon: ['glass tower afternoon — clean corporate air and city below through glass', 'the executive afternoon sensory — authority and precision', 'corporate glass and clean executive afternoon air'],
    reset: ['the private executive suite after the corporate day — warmth replacing precision', 'the sensory shift from corporate to private in the hotel suite', 'clean warm executive reset in private luxury'],
    golden_hour: ['amber city light entering the glass tower from below — warm and powerful', 'the executive above the city in the most beautiful corporate light', 'glass tower golden-hour — the most powerful sensory executive moment'],
    dinner: ['warm executive restaurant air and the most strategic table in the room', 'composed executive evening dining with elegance and authority', 'the power dinner sensory — warm, precise, and controlled'],
    evening: ['private jet leather interior and clean executive travel air above the world', 'executive suite warm private calm after the corporate day', 'the CEO in transit or at rest — the most private executive sensory'],
    night: ['warm executive suite night — the corporate world behind, privacy ahead', 'clean luxury executive night — the CEO at rest', 'private executive luxury at night — composed and complete'],
  },

  socialEnergyPools: {
    wake: ['completely private pre-executive morning', 'the CEO before anyone else exists — alone and precise'],
    morning_refresh: ['private executive self-care ritual', 'the CEO preparing alone — no audience at the executive vanity'],
    getting_dressed: ['private executive transformation — the suit as identity ritual', 'alone becoming the CEO in the wardrobe'],
    breakfast: ['private executive breakfast before the corporate world', 'the CEO alone in luxury before the day begins'],
    late_morning: ['the boardroom — maximally visible and in complete authority', 'executive corporate social energy at peak — the room responds to her'],
    lunch: ['strategic power lunch social energy — visible and in command', 'the CEO at the most important social table of the day'],
    afternoon: ['executive corporate authority social energy at full afternoon peak', 'the glass office and boardroom — powerful and seen'],
    reset: ['private executive reset — withdrawn from corporate energy', 'the CEO between public authority and private self'],
    golden_hour: ['subtly visible above the city — the most powerful executive view', 'the CEO above everyone at the most cinematic corporate moment'],
    dinner: ['executive power dinner social energy — strategic and composed', 'the most important dinner table and the CEO is at it'],
    evening: ['private jet or suite — the CEO in exclusive private executive travel mode', 'withdrawn from social energy into private executive calm'],
    night: ['fully private executive night — completely away from corporate world', 'the CEO alone in private luxury night'],
  },

  atmospherePools: {
    wake: ['clean precise executive morning before the city wakes', 'the private luxury executive world before the corporate day', 'clean quiet authority in hotel suite before everything begins'],
    morning_refresh: ['executive precision self-care morning atmosphere', 'clean powerful morning ritual in luxury executive setting', 'the CEO preparing — private and precise'],
    getting_dressed: ['executive wardrobe — clean precise authority building ritual', 'the power suit atmosphere — deliberate and controlled'],
    breakfast: ['executive hotel morning precision atmosphere', 'clean luxury executive breakfast before the corporate world', 'the CEO beginning the day in private luxury order'],
    late_morning: ['boardroom glass tower atmosphere — the most powerful corporate interior', 'executive glass office above the city atmosphere', 'clean precise corporate authority at maximum'],
    lunch: ['private restaurant power lunch atmosphere — elegant and strategic', 'executive dining composure and authority at the table', 'the most important lunch atmosphere in the city'],
    afternoon: ['glass tower afternoon corporate authority atmosphere', 'executive boardroom and office in full afternoon power', 'clean precise corporate executive afternoon flow'],
    reset: ['executive private suite warm reset atmosphere', 'the CEO between corporate and evening — private recalibration', 'warm corporate-to-evening transition in private luxury'],
    golden_hour: ['glass tower golden-hour above the city — the most powerful corporate atmosphere', 'executive above everything at the most cinematic corporate moment', 'amber city light through executive glass at golden hour'],
    dinner: ['private restaurant executive dinner atmosphere — warm, strategic, controlled', 'the CEO at dinner — the most elegant corporate social setting', 'executive evening dining precision and warmth'],
    evening: ['private jet executive travel atmosphere', 'executive suite warm private calm after corporate peak', 'the CEO in the most exclusive private executive evening'],
    night: ['executive private luxury night atmosphere', 'the CEO at rest in warm private suite after the day', 'clean warm executive luxury night — authority at rest'],
  },

  propPools: {
    wake: ['executive briefing or phone on bedside in suite', 'clean luxury hotel or home bedding', 'watch on bedside table in executive suite'],
    morning_refresh: ['executive vanity with power beauty products', 'clean luxury executive bathroom morning detail', 'marble executive bathroom surface in morning light'],
    getting_dressed: ['tailored power suit on wardrobe hanger being selected', 'executive watch being fastened', 'diamond or gold stud detail at executive mirror'],
    breakfast: ['hotel executive breakfast service detail', 'black coffee or espresso in precise porcelain', 'executive portfolio or device on clean breakfast table'],
    late_morning: ['glass boardroom table with executive device or portfolio', 'city panorama visible through the boardroom glass', 'executive pen or device at the corporate table'],
    lunch: ['white linen executive lunch table with wine or water', 'executive portfolio or device at the power lunch', 'strategic lunch detail — clean and composed'],
    afternoon: ['executive device or portfolio at glass desk in afternoon', 'city visible through floor-to-ceiling glass behind the desk', 'corporate executive afternoon detail'],
    reset: ['executive beauty products at hotel suite vanity', 'changing executive accessories from corporate to evening', 'warm hotel suite interior with evening outfit being selected'],
    golden_hour: ['glass tower window with city turning amber below', 'executive at the glass with city panorama in golden light', 'champagne or executive drink at the glass tower golden hour'],
    dinner: ['executive dinner table with wine and white linen', 'the CEO at the most strategic table in the restaurant', 'executive dinner detail — clean, precise, composed'],
    evening: ['private jet leather seat and executive travel interior', 'executive briefing or portfolio in jet interior in flight', 'suite private executive evening with device or journal'],
    night: ['executive watch removed on suite bedside', 'luxury hotel suite night detail in warm light', 'the CEO at rest — clean precise luxury night props'],
  },

  bodyLanguagePools: {
    wake: ['precise executive morning posture before the suit — private and at ease', 'the CEO before performance — quiet and composed in private luxury', 'executive morning stretch in luxury private interior'],
    morning_refresh: ['upright precise executive bathroom posture at the mirror', 'controlled executive self-care stance in clean morning light', 'the CEO making herself in precise executive morning light'],
    getting_dressed: ['deliberate precise dressing posture — the CEO assembling authority', 'executive mirror assessment of the tailored look — precise and composed', 'composed upright executive posture with precision detail check'],
    breakfast: ['executive breakfast posture — composed and ahead of everyone else', 'the CEO at breakfast — seated with clean precision', 'executive morning body language with authority and composure'],
    late_morning: ['standing at the boardroom head with complete executive authority — the room responds', 'glass office posture — standing at the window or seated with complete power and control', 'the CEO in the boardroom — no movement is wasted'],
    lunch: ['executive power lunch posture — seated with composed elegance and authority', 'the CEO at the most strategic table — relaxed authority', 'executive dining body language — precise and controlled'],
    afternoon: ['executive afternoon at the desk or in the boardroom — authority at full power', 'corporate glass office afternoon posture — deliberate and composed', 'the CEO in complete afternoon executive authority posture'],
    reset: ['the CEO transitioning in private — the armour coming off in luxury', 'executive hotel suite private reset posture', 'the CEO becoming private after the corporate day'],
    golden_hour: ['standing at the glass tower with city below — the most powerful executive posture', 'the CEO above the city at golden hour — the defining executive stance', 'executive composure at the glass tower at golden hour'],
    dinner: ['executive power dinner posture — composed, elegant, and in complete control', 'the CEO at dinner — the most authoritative and elegant body language of the evening', 'composed strategic dinner posture with executive grace'],
    evening: ['private jet executive in-flight posture — still precisely composed even in transit', 'executive suite evening posture — private and at ease after the corporate day', 'the CEO in private executive evening mode — still composed'],
    night: ['executive at private rest — composed even in luxury night ease', 'the CEO unwinding in private luxury night posture', 'private executive night body language — authority in rest'],
  },

  facialExpressionPools: {
    wake: ['precise executive morning expression — composed even before the day begins', 'the CEO before the world — private and calm in luxury suite', 'early morning executive quiet expression in luxury interior'],
    morning_refresh: ['focused executive preparation expression at the mirror', 'the CEO building the day\'s authority in the mirror expression', 'precise executive morning beauty ritual expression'],
    getting_dressed: ['the CEO expression during the power dressing ritual', 'composed authority building expression at the executive mirror', 'deliberate executive self-selection expression'],
    breakfast: ['executive breakfast expression — composed and ahead of schedule', 'the CEO at breakfast — calm, alert, and precisely in control', 'executive morning authority expression at the table'],
    late_morning: ['boardroom CEO expression — the most powerful face in the room', 'direct executive authority expression at the glass table', 'the CEO expression that makes the room quiet'],
    lunch: ['composed strategic power lunch expression — warm but completely controlled', 'executive dining expression — elegant authority at white linen', 'the CEO at lunch — the most composed face at the table'],
    afternoon: ['executive authority afternoon expression at full corporate power', 'glass office CEO expression — decisive and precise', 'the CEO in the boardroom afternoon — the most authoritative expression'],
    reset: ['the CEO expression in private reset — the armour softening slightly', 'executive composure in private hotel suite reset', 'transitioning expression from corporate to private evening CEO'],
    golden_hour: ['the CEO expression above the city at golden hour — authority and beauty', 'executive golden-hour glass tower expression — powerful and cinematically beautiful', 'the CEO above everything at the most cinematic executive moment'],
    dinner: ['executive power dinner expression — composed, warm, and deliberately strategic', 'the CEO at the most important dinner — complete authority with elegance', 'executive evening expression at the dinner table'],
    evening: ['executive private jet expression — composed and above it all in transit', 'the CEO in private evening suite — authority at ease', 'executive private evening expression after the corporate day'],
    night: ['the CEO at private rest — the most human and private expression', 'executive luxury night expression — composed even in rest', 'the power woman at night — authority at ease in private luxury'],
  },

  handDetailPools: {
    wake: ['hand on luxury executive bedside near the morning brief', 'watch on the bedside table near the CEO\'s hand', 'executive morning hand near the phone or brief before rising'],
    morning_refresh: ['hand at the executive bathroom counter in morning precision', 'fingers applying executive beauty product at vanity', 'executive hand detail in clean morning bathroom light'],
    getting_dressed: ['hand fastening the executive watch — the most important executive gesture', 'fingers adjusting tailored jacket collar with precision in mirror', 'hand selecting earring or executive accessory at mirror'],
    breakfast: ['hand around executive espresso cup at hotel breakfast', 'fingers near executive device or portfolio at the breakfast table', 'composed executive hand at the clean breakfast table'],
    late_morning: ['hand on glass boardroom table — the CEO at her most powerful', 'executive hand at pen or device on the corporate table', 'fingers indicating authority at the boardroom glass table'],
    lunch: ['hand near wine or water glass at power lunch', 'fingers on white linen at the executive lunch table', 'the CEO hand at the most strategic lunch in the city'],
    afternoon: ['hand on executive device or desk in the glass office', 'fingers at the floor-to-ceiling window overlooking the city', 'executive hand on the corporate surface at authority peak'],
    reset: ['hand removing executive watch in hotel suite reset', 'fingers selecting evening jewelry from executive case', 'executive hand detail at vanity in warm suite reset'],
    golden_hour: ['hand at the glass tower window — the CEO above the city in amber light', 'executive hand on the glass with city amber below at golden hour', 'the most powerful executive hand detail — above the city'],
    dinner: ['hand near wine or water glass at executive power dinner', 'fingers on white linen at the most strategic dinner table', 'the CEO hand detail at the executive dinner — composed and precise'],
    evening: ['executive hand in the private jet interior on the armrest', 'the CEO hand on the jet armrest or with a document in-flight', 'executive evening hand detail in private transit or suite'],
    night: ['executive watch removed — the CEO hand at private night rest', 'fingers near luxury suite detail at night', 'the CEO at private luxury rest — hand in quiet ease'],
  },

  movementEnergyPools: {
    wake: ['precise', 'executive', 'private'],
    morning_refresh: ['controlled', 'deliberate', 'precise'],
    getting_dressed: ['measured', 'deliberate', 'composed'],
    breakfast: ['efficient', 'executive', 'composed'],
    late_morning: ['authoritative', 'controlled', 'decisive'],
    lunch: ['composed', 'strategic', 'elegant'],
    afternoon: ['decisive', 'authoritative', 'precise'],
    reset: ['transitioning', 'private', 'composed'],
    golden_hour: ['still', 'powerful', 'elevated'],
    dinner: ['composed', 'strategic', 'elegant'],
    evening: ['private', 'executive', 'elevated'],
    night: ['quiet', 'private', 'at-rest'],
  },

  transitionPools: {
    human: {
      wake: ['the CEO waking before the world in executive luxury', 'the executive morning — precise and private'],
      morning_refresh: ['the executive morning self-care ritual beginning', 'the CEO building the day\'s authority in private'],
      getting_dressed: ['assembling the CEO — tailored authority ritual', 'the power suit going on — the executive becoming'],
      breakfast: ['the executive breakfast before the corporate world', 'the CEO fueling before the day begins'],
      late_morning: ['the boardroom — the CEO at maximum corporate authority', 'the most powerful room with the city panorama below'],
      lunch: ['the power lunch — the most strategic table of the day', 'the CEO dining with complete authority and grace'],
      afternoon: ['the executive afternoon at full corporate power', 'the glass office and boardroom in the CEO afternoon'],
      reset: ['the private executive reset between corporate and evening', 'the CEO transitioning from power suit to dinner elegance'],
      golden_hour: ['the glass tower at golden hour — the CEO above the city', 'the most powerful executive moment of the day'],
      dinner: ['the power dinner — the CEO at the most strategic evening table', 'executive elegance in the most important dinner of the night'],
      evening: ['the private jet or suite — the CEO in exclusive private mode', 'executive private evening in luxury transit or suite'],
      night: ['the executive at private luxury rest — the day is won', 'the CEO in private luxury night — authority at rest'],
    },
  },

  narrativeIntentPools: {
    wake: ['the CEO before the world begins — the private human behind the authority', 'power at rest before the corporate day'],
    morning_refresh: ['building the executive identity through precise self-care ritual in luxury', 'the CEO becoming in private before the corporate world sees her'],
    getting_dressed: ['the tailored suit as the physical embodiment of executive authority', 'assembling the CEO through deliberate power styling ritual'],
    breakfast: ['the executive starting the day ahead of everyone — precision and fuel', 'the CEO in private luxury morning before the corporate world opens'],
    late_morning: ['the boardroom — the CEO at the apex of corporate feminine power', 'authority, composure, and control in the glass tower at maximum'],
    lunch: ['the power lunch as the most strategic social moment of the corporate day', 'the CEO turning dining into corporate authority with elegance'],
    afternoon: ['executive authority at full afternoon corporate power in the glass tower', 'the CEO and the corporate world in complete alignment and control'],
    reset: ['the private executive transition — from corporate to evening authority', 'the CEO becoming the most elegant version of executive power'],
    golden_hour: ['the CEO above the city at the most cinematic executive moment', 'glass tower golden hour — authority and beauty at maximum simultaneously'],
    dinner: ['the power dinner as the most strategic and elegant executive social moment', 'the CEO at dinner — composure, elegance, and complete authority'],
    evening: ['the exclusive private executive world in transit or at rest', 'the CEO in the most private and elevated executive evening'],
    night: ['the most human and private version of the executive at rest in luxury', 'the CEO complete — authority at rest in warm private luxury'],
  },

  fallbackRules: {
    pacingProfile: { wake: 'slow', morning_refresh: 'slow', getting_dressed: 'slow', breakfast: 'slow', late_morning: 'medium', lunch: 'slow', afternoon: 'medium', reset: 'slow', golden_hour: 'slow', dinner: 'slow', evening: 'slow', night: 'slow' },
    repetitionBreakers: { avoidBackToBackSameLocation: true, avoidBackToBackSameLightingStyle: true, encourageWardrobeEvolution: true },
    worldDefaults: { allowSceneGroupFallbackToPhasePools: true, allowSubLocationFallbackToWorldPools: true, preferSceneGroupsWhenPresent: true },
  },

  exclusions: {
    premium: ['casual or relaxed settings unrelated to executive world', 'beach or pool without corporate context', 'cluttered or uncontrolled backgrounds', 'informal non-executive styling'],
    hard: ['bikini or revealing swimwear in corporate contexts', 'nightclub chaos', 'athletic gym settings unrelated to executive world', 'low-status environments'],
  },

  routeRules: {
    worldIdentity: ['the power CEO world must feel clean, precise, authoritative, and beautiful — never casual or out of control', 'tailored suits, glass towers, executive interiors, and strategic elegance are the core visual language'],
    humanFlow: ['the day begins with a precise private executive morning, builds through corporate authority to the boardroom peak, transitions through a private reset to an elevated executive evening, and closes in private luxury night'],
    styling: ['tailored power suits, executive dresses, precise accessories including the watch, and elevated evening wear', 'wardrobe evolves from clean luxury morning through corporate authority to executive evening elegance'],
    atmosphere: ['glass towers, boardrooms, private restaurants, executive suites, and private jets', 'clean precise lighting and city panoramas are the defining environmental characteristics'],
  },
}
