export const STORY_WORLD_SUPERMODEL_LIFE = {
  id: 'supermodel-life',
  name: 'Supermodel Life',
  description:
    'A cinematic world of elite fashion mythology — runway backstage chaos, couture fittings, casting rooms, editorial studio intensity, fashion week arrivals, luxury hotel suites between shows, and the private silence behind a woman whose face, body, walk, and presence are treated like global currency.',

  geography: {
    country: 'global fashion capitals',
    region: 'Paris, Milan, New York, London — runway backstage, atelier, casting room, editorial studio, luxury hotel suite, fashion week streets',
  },

  identity: {
    archetype: 'elite international supermodel',
    vibe: [
      'runway composure inside backstage chaos',
      'the body as luxury fashion architecture',
      'fashion week pressure and private hotel silence',
      'couture fittings and editorial transformation',
      'being watched professionally by the most selective industry in the world',
    ],
    tone: [
      'editorial',
      'controlled',
      'fierce',
      'high-fashion',
      'cinematic',
      'disciplined',
      'occasionally raw',
    ],
    persona: [
      'the woman every room evaluates and every camera follows',
      'completely composed while the industry moves chaotically around her',
      'turning clothing into power without needing to perform',
      'the face of a campaign, the body of a runway, and the private human behind the image',
    ],
  },

  phaseOrder: [
    'wake',
    'morning_refresh',
    'getting_dressed',
    'breakfast',
    'late_morning',
    'lunch',
    'afternoon',
    'reset',
    'golden_hour',
    'dinner',
    'evening',
    'night',
  ],

  phases: {
    wake: {
      label: 'Wake',
      timeWindows: ['early fashion week hotel morning', 'private luxury suite before the first call time'],
      pacing: 'slow',
      subLocations: ['fashion-hotel-suite', 'model-bedroom'],
    },
    morning_refresh: {
      label: 'Morning Refresh',
      timeWindows: ['hotel bathroom before glam', 'clean morning ritual before the fashion day'],
      pacing: 'slow',
      subLocations: ['hotel-bathroom-fashion', 'model-vanity'],
    },
    getting_dressed: {
      label: 'Getting Dressed',
      timeWindows: ['off-duty model look before call time', 'hotel dressing before castings or shows'],
      pacing: 'slow',
      subLocations: ['hotel-wardrobe', 'model-mirror'],
    },
    breakfast: {
      label: 'Breakfast',
      timeWindows: ['quiet hotel breakfast before the fashion day', 'coffee and call sheet morning'],
      pacing: 'slow',
      subLocations: ['hotel-breakfast', 'fashion-hotel-suite'],
    },
    late_morning: {
      label: 'Late Morning',
      timeWindows: ['casting room or agency appointment', 'first fashion appointment of the day'],
      pacing: 'medium',
      subLocations: ['casting-room', 'agency-office'],
    },
    lunch: {
      label: 'Lunch',
      timeWindows: ['model lunch between appointments', 'off-duty café between castings and fittings'],
      pacing: 'slow',
      subLocations: ['off-duty-café', 'fashion-street'],
    },
    afternoon: {
      label: 'Afternoon',
      timeWindows: ['atelier fitting or editorial studio work', 'couture fitting in fashion capital'],
      pacing: 'medium',
      subLocations: ['atelier-fitting', 'editorial-studio'],
    },
    reset: {
      label: 'Reset',
      timeWindows: ['backstage hair and makeup transformation', 'pre-runway backstage preparation'],
      pacing: 'slow',
      subLocations: ['runway-backstage', 'makeup-chair'],
    },
    golden_hour: {
      label: 'Golden Hour',
      timeWindows: ['fashion week arrival in golden city light', 'street-style arrival before the show'],
      pacing: 'slow',
      subLocations: ['fashion-week-arrival', 'street-style-arrival'],
    },
    dinner: {
      label: 'Dinner',
      timeWindows: ['runway show at full power', 'catwalk under show lighting'],
      pacing: 'slow',
      subLocations: ['runway-catwalk', 'show-finale'],
    },
    evening: {
      label: 'Evening',
      timeWindows: ['post-show after-party or brand dinner', 'fashion week evening visibility'],
      pacing: 'medium',
      subLocations: ['after-party-fashion', 'brand-dinner'],
    },
    night: {
      label: 'Night',
      timeWindows: ['hotel suite decompression after the show', 'private model night after fashion week pressure'],
      pacing: 'slow',
      subLocations: ['fashion-hotel-suite', 'model-bedroom'],
    },
  },

  locations: [
    'luxury hotel suite in Paris, Milan, or New York during fashion week',
    'runway backstage with mirrors, racks, makeup lights, and controlled chaos',
    'catwalk under full fashion show lighting',
    'couture atelier fitting room with pinned fabric and designer detail',
    'white cyclorama editorial studio',
    'casting room with clean walls and industry tension',
    'fashion week street arrival with photographers outside',
    'post-show after-party in dark luxury venue',
    'hotel bathroom and vanity before glam begins',
  ],

  subLocations: {
    'fashion-hotel-suite': {
      id: 'fashion-hotel-suite',
      name: 'Fashion Hotel Suite',
      mapAnchor: 'luxury hotel suite during fashion week',
      category: 'private-fashion',
      bestPhases: ['wake', 'breakfast', 'night'],
      overlays: [
        'luxury hotel suite in fashion capital',
        'private model morning before public visibility',
        'cream and gold hotel light with city view',
        'the private human behind the fashion image',
      ],
      locations: [
        'luxury hotel suite in Paris or Milan fashion week morning',
        'private fashion week hotel room with city view',
        'model hotel suite between shows and appointments',
      ],
    },

    'model-bedroom': {
      id: 'model-bedroom',
      name: 'Model Bedroom',
      mapAnchor: 'private model hotel bedroom',
      category: 'private-model',
      bestPhases: ['wake', 'night'],
      overlays: [
        'soft hotel bedding after fashion week pressure',
        'private silence behind public beauty',
        'model off-duty morning or night',
      ],
      locations: [
        'private hotel bedroom during fashion week',
        'model bedroom in warm hotel light',
        'quiet luxury bedroom after runway and cameras',
      ],
    },

    'hotel-bathroom-fashion': {
      id: 'hotel-bathroom-fashion',
      name: 'Hotel Bathroom',
      mapAnchor: 'fashion week hotel bathroom',
      category: 'self-care-fashion',
      bestPhases: ['morning_refresh'],
      overlays: [
        'clean hotel bathroom before glam',
        'skin preparation before makeup chair',
        'private morning ritual before the industry sees her',
      ],
      locations: [
        'luxury hotel bathroom before fashion week call time',
        'clean marble bathroom with morning model self-care',
        'hotel bathroom ritual before runway preparation',
      ],
    },

    'model-vanity': {
      id: 'model-vanity',
      name: 'Model Vanity',
      mapAnchor: 'model hotel vanity',
      category: 'preparation-fashion',
      bestPhases: ['morning_refresh', 'getting_dressed'],
      overlays: [
        'model vanity with beauty products and call sheet nearby',
        'pre-glam preparation in clean hotel light',
        'the face before the industry transforms it',
      ],
      locations: [
        'hotel vanity before fashion week glam',
        'model preparation vanity in clean morning light',
        'private beauty ritual before backstage transformation',
      ],
    },

    'hotel-wardrobe': {
      id: 'hotel-wardrobe',
      name: 'Hotel Wardrobe',
      mapAnchor: 'hotel wardrobe with off-duty model clothes',
      category: 'dressing-fashion',
      bestPhases: ['getting_dressed'],
      overlays: [
        'off-duty model styling selection',
        'designer pieces and simple basics arranged with intention',
        'the model dressing before castings and shows',
      ],
      locations: [
        'hotel wardrobe with off-duty model street style',
        'fashion week dressing area with designer pieces',
        'model hotel styling zone before appointments',
      ],
    },

    'model-mirror': {
      id: 'model-mirror',
      name: 'Model Mirror',
      mapAnchor: 'full-length hotel mirror',
      category: 'reflection-fashion',
      bestPhases: ['getting_dressed'],
      overlays: [
        'full-length mirror self-assessment',
        'off-duty model silhouette in clean hotel light',
        'the body and clothes evaluated before entering the fashion world',
      ],
      locations: [
        'full-length hotel mirror with model street style check',
        'private mirror moment before fashion appointments',
        'off-duty model mirror in luxury suite',
      ],
    },

    'hotel-breakfast': {
      id: 'hotel-breakfast',
      name: 'Hotel Breakfast',
      mapAnchor: 'model hotel breakfast',
      category: 'morning-fashion',
      bestPhases: ['breakfast'],
      overlays: [
        'coffee, water, fruit, and call sheet',
        'quiet breakfast before public scrutiny',
        'fashion week morning discipline',
      ],
      locations: [
        'hotel breakfast table before fashion week appointments',
        'room service breakfast in model hotel suite',
        'coffee and call sheet in luxury hotel morning',
      ],
    },

    'casting-room': {
      id: 'casting-room',
      name: 'Casting Room',
      mapAnchor: 'fashion casting room',
      category: 'industry-judgment',
      bestPhases: ['late_morning'],
      overlays: [
        'clean casting room with intense evaluation',
        'the walk, the face, the body, and the silence',
        'industry judgment contained by total composure',
      ],
      locations: [
        'minimal fashion casting room with clean walls',
        'model casting room with white floor and industry tension',
        'high-fashion casting appointment space',
      ],
    },

    'agency-office': {
      id: 'agency-office',
      name: 'Agency Office',
      mapAnchor: 'top model agency office',
      category: 'industry-power',
      bestPhases: ['late_morning'],
      overlays: [
        'top agency meeting room',
        'portfolio, comp cards, and schedule tension',
        'the business side of beauty',
      ],
      locations: [
        'top model agency office with portfolio table',
        'fashion agency meeting room in clean daylight',
        'agency appointment space with industry precision',
      ],
    },

    'off-duty-café': {
      id: 'off-duty-café',
      name: 'Off-Duty Café',
      mapAnchor: 'fashion week café between appointments',
      category: 'off-duty-fashion',
      bestPhases: ['lunch'],
      overlays: [
        'off-duty model lunch between appointments',
        'coffee, sunglasses, and city movement',
        'fashion week life between public moments',
      ],
      locations: [
        'Paris or Milan café between fashion appointments',
        'off-duty model café with natural city light',
        'fashion week lunch table with street energy outside',
      ],
    },

    'fashion-street': {
      id: 'fashion-street',
      name: 'Fashion Street',
      mapAnchor: 'fashion week street',
      category: 'street-style',
      bestPhases: ['lunch', 'golden_hour'],
      overlays: [
        'off-duty street style in fashion capital',
        'photographers and city movement nearby',
        'the sidewalk as an unofficial runway',
      ],
      locations: [
        'Paris fashion week street outside venue',
        'Milan street style moment between shows',
        'New York fashion week sidewalk arrival',
      ],
    },

    'atelier-fitting': {
      id: 'atelier-fitting',
      name: 'Atelier Fitting',
      mapAnchor: 'couture atelier fitting room',
      category: 'couture-transformation',
      bestPhases: ['afternoon'],
      overlays: [
        'half-pinned couture fitting',
        'designer hands, fabric, pins, and mirror',
        'the body becoming the architecture for couture',
      ],
      locations: [
        'Paris couture atelier fitting room',
        'Milan designer fitting space with pinned fabric',
        'atelier mirror with unfinished couture look',
      ],
    },

    'editorial-studio': {
      id: 'editorial-studio',
      name: 'Editorial Studio',
      mapAnchor: 'high-fashion editorial studio',
      category: 'editorial-fashion',
      bestPhases: ['afternoon'],
      overlays: [
        'white cyclorama or high-contrast editorial studio',
        'magazine cover shoot atmosphere',
        'the model transformed into image and concept',
      ],
      locations: [
        'white cyclorama editorial fashion studio',
        'high-contrast magazine cover shoot setup',
        'fashion editorial studio with lighting rigs and backdrop',
      ],
    },

    'runway-backstage': {
      id: 'runway-backstage',
      name: 'Runway Backstage',
      mapAnchor: 'fashion show backstage',
      category: 'runway-preparation',
      bestPhases: ['reset'],
      overlays: [
        'backstage mirrors, racks, makeup chairs, and controlled chaos',
        'hair and makeup transformation before the show',
        'the runway machine surrounding total model composure',
      ],
      locations: [
        'runway backstage before fashion show',
        'fashion week backstage with racks and makeup lights',
        'designer show backstage in controlled chaos',
      ],
    },

    'makeup-chair': {
      id: 'makeup-chair',
      name: 'Makeup Chair',
      mapAnchor: 'backstage makeup chair',
      category: 'glam-transformation',
      bestPhases: ['reset'],
      overlays: [
        'makeup chair under bright backstage mirror bulbs',
        'hair pulled, face painted, identity transformed',
        'the model becoming the show image',
      ],
      locations: [
        'backstage makeup chair before runway',
        'hair and makeup station under mirror lights',
        'model glam transformation backstage',
      ],
    },

    'fashion-week-arrival': {
      id: 'fashion-week-arrival',
      name: 'Fashion Week Arrival',
      mapAnchor: 'fashion week show arrival',
      category: 'public-arrival',
      bestPhases: ['golden_hour'],
      overlays: [
        'photographers outside the venue',
        'golden-hour arrival before the show',
        'the sidewalk turning into runway before the runway',
      ],
      locations: [
        'fashion week venue arrival in golden city light',
        'Paris show arrival with photographers nearby',
        'Milan venue entrance in warm street-style light',
      ],
    },

    'street-style-arrival': {
      id: 'street-style-arrival',
      name: 'Street Style Arrival',
      mapAnchor: 'street style outside fashion show',
      category: 'public-fashion',
      bestPhases: ['golden_hour'],
      overlays: [
        'off-duty editorial street style',
        'camera flashes and controlled public visibility',
        'model presence in the city before the show',
      ],
      locations: [
        'street-style arrival outside fashion week show',
        'model walking into venue in full street-style moment',
        'fashion week sidewalk with camera attention',
      ],
    },

    'runway-catwalk': {
      id: 'runway-catwalk',
      name: 'Runway Catwalk',
      mapAnchor: 'catwalk under show lighting',
      category: 'runway-peak',
      bestPhases: ['dinner'],
      overlays: [
        'catwalk under full fashion show lighting',
        'the runway walk at maximum public visibility',
        'total composure under industry eyes',
      ],
      locations: [
        'fashion show catwalk under spotlight',
        'runway in full show lighting with audience in darkness',
        'designer catwalk at fashion week peak',
      ],
    },

    'show-finale': {
      id: 'show-finale',
      name: 'Show Finale',
      mapAnchor: 'fashion show finale',
      category: 'runway-finale',
      bestPhases: ['dinner'],
      overlays: [
        'final runway pass',
        'designer show finale energy',
        'the public image completed under full lights',
      ],
      locations: [
        'fashion show finale catwalk moment',
        'runway finale under full audience attention',
        'designer show closing walk',
      ],
    },

    'after-party-fashion': {
      id: 'after-party-fashion',
      name: 'Fashion After-Party',
      mapAnchor: 'fashion week after-party',
      category: 'fashion-evening',
      bestPhases: ['evening'],
      overlays: [
        'dark luxury fashion week after-party',
        'models, designers, editors, and private visibility',
        'the post-show social world in warm low light',
      ],
      locations: [
        'fashion week after-party in dark luxury venue',
        'post-show party with warm editorial light',
        'model after-party after runway show',
      ],
    },

    'brand-dinner': {
      id: 'brand-dinner',
      name: 'Brand Dinner',
      mapAnchor: 'private fashion brand dinner',
      category: 'fashion-dining',
      bestPhases: ['evening'],
      overlays: [
        'private designer dinner after show',
        'brand table with editors and models',
        'fashion power disguised as dinner',
      ],
      locations: [
        'private fashion brand dinner in warm luxury restaurant',
        'designer dinner table after runway show',
        'fashion week dinner with editors and creative directors',
      ],
    },
  },

  sceneVariants: {
    wake: [
      'luxury hotel morning during fashion week — private before the industry sees her',
      'the supermodel waking before call time in a quiet fashion capital suite',
      'first light through heavy hotel drapes onto white bedding before the schedule begins',
      'the model lying still in the early silence of a Milan or Paris hotel — call sheet on the nightstand',
      'private morning in a high-floor fashion suite, city waking below, the runway still hours away',
      'waking to the soft press of white linen before the fashion world demands anything',
    ],
    morning_refresh: [
      'hotel bathroom morning ritual before hair and makeup',
      'the face before the industry transforms it — clean, private, and real',
      'standing at the marble sink in early morning hotel light, product-free and fully herself',
      'bathroom mirror ritual in the quiet before call time — the only unobserved moment',
      'steam and clean skin and the faint smell of hotel soap before the glam chair claims her',
      'the face the camera never sees — real, rested, and privately composed at the hotel vanity',
    ],
    getting_dressed: [
      'off-duty model dressing in the hotel mirror before appointments',
      'the street-style look being assembled before entering fashion week visibility',
      'selecting from a curated rail of off-duty pieces before the first casting of the morning',
      'the hotel mirror silhouette check — body, proportion, and intentional simplicity before public movement',
      'layering the off-duty editorial look with the same precision the runway demands',
      'the private dressing ritual before she becomes a public fashion image for the day',
    ],
    breakfast: [
      'coffee, water, fruit, and call sheet before the fashion day begins',
      'quiet hotel breakfast before castings, fittings, and runway pressure',
      'room service tray in fashion week silence — espresso and half a schedule before anyone calls',
      'the hotel breakfast table as the one calm moment before the industry claims the day',
      'croissant, black coffee, and a phone full of fitting confirmations before the car arrives',
      'the model eating alone at the window table, city visible behind glass, fashion day beginning',
    ],
    late_morning: [
      'casting room judgment — the walk, the silence, the body, the face',
      'agency appointment in clean daylight where beauty becomes business',
      'the casting walk — minimal steps, maximum presence, the room deciding in ten seconds',
      'standing in agency light while bookers discuss her measurements like architecture specifications',
      'comp card on the table, the model composed as the room evaluates everything she is',
      'the quiet casting room walk where a season can be won in a single turn',
    ],
    lunch: [
      'off-duty café between appointments in Paris or Milan',
      'fashion week lunch with sunglasses, phone, coffee, and city movement nearby',
      'the brief café break between a casting and a fitting — sunglasses on, posture unchanged',
      'eating alone at a small Paris terrace table, unrecognized until someone looks twice',
      'fashion week lunch as the only unhurried hour — the city moving, she still',
      'off-duty street-style moment crossing to the café, photographers catching what they can',
    ],
    afternoon: [
      'couture atelier fitting — pinned fabric and designer hands around the body',
      'editorial studio transformation — the model becoming the image',
      'standing on the atelier platform while the dress is built around her — pin by pin',
      'the white studio shoot where the body becomes the concept — blank walls, full lights, no props',
      'editorial transformation under six reflectors — the model found between direction and instinct',
      'the atelier visit where the designer adjusts the collar personally and the fabric becomes architecture',
    ],
    reset: [
      'runway backstage preparation — racks, mirrors, hair, makeup, and controlled chaos',
      'makeup chair transformation before the catwalk',
      'the backstage ritual — thirty people moving, she the only still point in the storm',
      'sitting in the glam chair while hands work her hair, her face, her identity into the show look',
      'racks of couture at her back, the mirror showing a face becoming more than a face',
      'the makeup transformation complete — the private woman fully replaced by the runway image',
    ],
    golden_hour: [
      'fashion week arrival at golden hour with photographers outside the venue',
      'street-style moment before the show — the sidewalk becoming a runway',
      'stepping from the car in warm late-afternoon light — the city going quiet for a second',
      'the golden-hour arrival where natural light makes even the sidewalk feel editorial',
      'photographers outside the venue door, the model moving through them without breaking stride',
      'the last warm light of the day catching the coat, the walk, and the face simultaneously',
    ],
    dinner: [
      'the catwalk under full fashion show lighting — total composure under public scrutiny',
      'runway walk at the peak of the show with audience dissolved into darkness',
      'the full runway moment — every light in the room following her walk',
      "the show finale pass where the designer's vision reaches its peak through her movement",
      'standing at the end of the catwalk before the turn — silence before the flash',
      'the runway entry where the audience sees the look and the look is her',
    ],
    evening: [
      'fashion week after-party in dark luxury light after the show',
      'brand dinner where fashion power hides behind elegance and conversation',
      'the after-party where the show continues in a different dress under amber light',
      'sitting at the brand dinner table between a creative director and an editor-in-chief',
      'the post-show venue — dark, warm, and full of industry conversation she navigates effortlessly',
      'the evening where fashion week visibility shifts from the catwalk to the dinner table',
    ],
    night: [
      'hotel suite decompression after runway, cameras, and industry pressure',
      'the private model at night — the public armor finally removed',
      'makeup coming off at the bathroom mirror — the industry image dissolving into quiet skin',
      'the model alone in the suite after the show, call sheet discarded, city lights outside',
      'the night silence of the fashion week hotel — the performance finally, privately over',
      'last light of the luxury suite as fashion week exhaustion and private relief meet',
    ],
  },

  environmentPools: {
    wake: [
      'luxury fashion week hotel suite in cream and gold morning light',
      'high-floor Paris hotel room with city rooftops visible through sheer drapes',
      'Milan fashion week suite in still early morning — schedule on the nightstand, city quiet below',
      'New York hotel bedroom before call time — soft white linen and first grey daylight',
      'private model suite with heavy blackout curtains just beginning to let morning in',
      'the fashion capital hotel room between shows — quiet, expensive, and temporarily hers',
    ],
    morning_refresh: [
      'marble hotel bathroom in clean 6 AM light before the glam machine starts',
      'luxury vanity alcove with skincare products arranged before backstage makeup',
      'hotel bathroom mirror in soft warm light — the face before the industry takes it',
      'the private model vanity — call sheet beside the mirror, coffee cooling nearby',
      'white marble and brushed chrome bathroom in a fashion capital hotel, morning quiet',
      'hotel sink and mirror in pre-dawn light — the only moment of private self-possession',
    ],
    getting_dressed: [
      'hotel wardrobe rail of curated off-duty pieces in clean suite daylight',
      'full-length suite mirror with the street-style look being assembled piece by piece',
      'the hotel dressing corner — oversized coat, simple trouser, perfect shoe laid out',
      'model room with open luggage, designer basics, and the intentional off-duty silhouette forming',
      'luxury suite getting-dressed light — flat, clean, and editorial without trying',
      'the full-length mirror moment where the off-duty look becomes as studied as the runway one',
    ],
    breakfast: [
      'hotel suite breakfast table — espresso, mineral water, fruit, and a printed schedule',
      'room service tray in morning light with the call sheet beside a single croissant',
      'quiet hotel breakfast room before the fashion industry crowd arrives',
      'fashion week suite window table — black coffee and city light before the first appointment',
      'private suite morning setup — tray, phone, flat light, and the day ahead already fully planned',
      'the hotel breakfast moment between the private night and the public fashion day',
    ],
    late_morning: [
      'stark white casting room with clean overhead light and a single strip of tape on the floor',
      'top agency office — portfolio table, booker desks, and the quiet tension of professional evaluation',
      'casting space with bare walls, folding chairs, and decision-makers watching from the far end',
      'Paris casting room — minimal, bright, and silent except for the click of heels on the floor',
      'model agency corridor before the meeting — portfolio under her arm, composure immovable',
      'the casting appointment space where the body and face become a professional conversation',
    ],
    lunch: [
      'small Paris café terrace between appointments — canopy shade, cobblestone, and city noise',
      'Milan street-level café table near a fashion week venue — the model slightly visible, not trying to be',
      'fashion week sidewalk between castings — the city moving fast around one still, composed figure',
      'off-duty café interior with marble tables, espresso, and a phone full of confirmation messages',
      'the lunch café where off-duty becomes its own editorial — sunglasses on, posture unchanged',
      'New York deli near a casting address — the model eating alone with architectural ease',
    ],
    afternoon: [
      'Paris couture atelier fitting room — full-length mirrors, half-finished garments, and designer precision',
      'white cyclorama editorial studio with six lighting rigs and a photographer directing at low volume',
      'Milan atelier platform — the dress being built around her body while she holds completely still',
      'magazine cover studio in midtown — the concept is her face against white, nothing else',
      'couture fitting room where three people work simultaneously on fabric that costs more than most cars',
      'editorial studio with coloured gel lighting and a creative director explaining the mood in two words',
    ],
    reset: [
      'fashion show backstage — fifty people in a space built for twenty, controlled chaos everywhere',
      'the makeup chair under a row of vanity bulbs — the face transformation fully underway',
      'backstage corridor lined with clothing racks, hanging looks, and final alterations in progress',
      'the glam station at a major designer show — brushes, pins, and runway pressure in the air',
      'backstage with the show ten minutes out — every station occupied, every model at a different stage',
      'the mirror moment backstage when the makeup is complete and the runway image is fully assembled',
    ],
    golden_hour: [
      'fashion week venue arrival in late amber light — photographers lining both sides of the entrance',
      'Paris cobblestone street in golden hour with the show venue doors visible ahead',
      'the fashion week sidewalk moment when warm light hits the street-style look perfectly',
      'Milan venue entrance in last-hour sun — the look made twice as powerful by natural light',
      'the car door opening at golden hour outside a marquee show — the moment before the walk',
      'fashion week street with warm late light — the sidewalk as editorial location, the model aware',
    ],
    dinner: [
      'the runway under full show lighting — audience in darkness, every light on the catwalk',
      'the catwalk at peak show energy — designer look, full lights, and the walk that earns the season',
      'runway entry from backstage into the full roar of show lighting and silent watching',
      'fashion show finale — models returning in sequence, the space charged with last-pass energy',
      'the catwalk turn at the end — the moment of stillness before walking back through the light',
      'the designer show runway at its most cinematic — light, look, and walk in complete alignment',
    ],
    evening: [
      'fashion week after-party in a converted warehouse with low warm light and industry faces',
      'brand dinner in a private Michelin-starred Paris room — candlelight, dark wood, and power',
      'the post-show party venue — dark, warm, expensive, and full of people who saw the runway',
      'designer dinner table in a Milan restaurant reserved entirely for the brand — editors left and right',
      'after-party space where the show energy carries into champagne and conversation',
      'the fashion week evening transition from catwalk to dinner table — the look still perfect',
    ],
    night: [
      'the fashion week hotel suite at night — makeup removed, room service tray, city lights outside',
      'private model bedroom after the show — the public armor fully off, the suite finally still',
      'late-night hotel mirror moment — the runway face washing away, the real face reappearing',
      'the suite sitting area at midnight — call sheet on the floor, phone finally silent',
      'fashion capital hotel room at night — the city still lit below, the model finally alone',
      'the final quiet of the fashion week hotel room — the industry finished with her for the day',
    ],
  },

  actionPools: {
    wake: [
      'waking in luxury hotel suite before the fashion day begins',
      'checking call time in bed before castings and shows',
      'the private supermodel morning in Paris or Milan before the industry sees her',
      'lying still in the quiet suite while the city below begins and the schedule waits',
      'sitting up slowly in hotel linen, phone face-up, first light coming through the drapes',
      'the unhurried waking moment before the day becomes a sequence of professional obligations',
    ],
    morning_refresh: [
      'hotel bathroom morning ritual before glam begins',
      'preparing skin at the hotel vanity before backstage makeup',
      'the face being kept clean before the fashion machine transforms it',
      'standing at the marble sink applying toner in early hotel light, no makeup, fully herself',
      'the slow pre-glam ritual — cleanser, serum, sunscreen — the private preparation before transformation',
      'brushing teeth at the hotel mirror, face bare, the industry not yet present in the room',
    ],
    getting_dressed: [
      'selecting the off-duty model look before call time',
      'checking street-style silhouette in the full-length hotel mirror',
      'assembling the model-off-duty look before entering the public fashion day',
      'stepping into tailored wide-leg trousers and a structured overcoat before the first appointment',
      'the precise, unhurried act of dressing — each piece chosen with editorial consideration',
      'turning once in the full-length mirror before leaving the suite — the look complete and deliberate',
    ],
    breakfast: [
      'coffee and call sheet in a luxury hotel suite',
      'quiet breakfast before the first casting or fitting',
      'the disciplined fashion week morning meal before the day begins',
      'sitting at the window table with an espresso and a typed schedule — the city already moving below',
      "eating methodically through fruit and protein while reviewing the day's appointment sequence",
      'the room service breakfast ritual — the only slow moment before the industry takes the hours',
    ],
    late_morning: [
      'walking into the casting room with complete composure',
      'standing in front of industry decision-makers under clean evaluation light',
      'agency appointment where the body, face, and walk become business',
      'executing the casting walk — controlled, measured, precisely unhurried — then stopping to turn',
      'handing the comp card across the table and holding eye contact without requiring the moment back',
      'standing at the agency window while bookers discuss her next season in the third person',
    ],
    lunch: [
      'off-duty café lunch between appointments',
      'walking through the fashion capital street between shows',
      'the model in sunglasses and street style moving between industry moments',
      'sitting at a Paris terrace table with an espresso and her phone — the city in peripheral vision',
      'crossing a Milan cobblestone street in an overcoat, a photographer catching three frames from a café',
      'the brief unhurried lunch where the off-duty look does the work without any effort applied',
    ],
    afternoon: [
      'standing in couture fitting while fabric is pinned to the body',
      'working the editorial studio under high-fashion lighting',
      'the body becoming architecture inside the atelier or studio',
      'holding the atelier pose for fifteen minutes while the designer adjusts a single seam',
      'moving through editorial directions in the studio — each frame a new version of the same power',
      'the couture fitting moment where the designer drapes the final version and steps back to look',
    ],
    reset: [
      'sitting in the makeup chair as backstage chaos moves around her',
      'hair and makeup transformation before the runway',
      'the show image being built around her face and body',
      'holding completely still in the makeup chair while two artists work simultaneously on the look',
      'watching in the backstage mirror as the runway version of her face appears layer by layer',
      'the final runway walk-through backstage — heels, posture, count, turn — the show seven minutes out',
    ],
    golden_hour: [
      'arriving at the fashion week venue as photographers gather outside',
      'walking the street-style entrance in warm city light',
      'turning the sidewalk into a runway before the actual runway',
      'stepping from the car into golden light and moving toward the venue without breaking stride',
      'the arrival walk where the overcoat catches the late sun and the photographers move to follow',
      'pausing at the venue steps for three seconds of eye contact with the press line — then inside',
    ],
    dinner: [
      'walking the runway under full show lighting',
      'standing in the catwalk lineup before the final pass',
      'the full runway moment — total composure in maximum visibility',
      'the runway walk from the curtain edge to the catwalk end — every step counted and clean',
      'the catwalk turn — stopping, weight shifting, the dress moving as it was built to move',
      'the finale pass where the whole show becomes a single composed movement in full light',
    ],
    evening: [
      'moving through the fashion week after-party in dark luxury light',
      'sitting at the brand dinner with editors, designers, and models nearby',
      'the social fashion world after the runway is complete',
      'holding a champagne flute without drinking it and making the conversation look effortless',
      'arriving at the brand dinner last and finding the room already assembled, chairs turning',
      'navigating the after-party crowd with the same composure the runway requires — different room, same walk',
    ],
    night: [
      'returning to the hotel suite after the show',
      'removing makeup and public armor in private hotel silence',
      'the model alone after the industry has finished looking',
      'sitting at the hotel vanity removing the runway face — each cotton round a layer closer to herself',
      'standing at the suite window in a robe, city lit below, the show finally fully behind her',
      'lying in the dark hotel room with the phone on the nightstand, the schedule blank until morning',
    ],
  },

  cameraPools: {
    wake: [
      '85mm f/1.4 low-angle bedroom framing, soft hotel linen filling the foreground, morning light dissolving behind',
      '135mm f/2 pillow-level close, natural window diffusion tracing the jaw and shoulder edge',
      '50mm f/1.8 mid shot from the suite doorway, white bedding and grey city light in the frame',
      '85mm f/1.4 looking down from above the bed, face turned toward window light, sheets pulled close',
      '135mm f/2 tight on hands and face detail, hotel linen texture compressed in soft morning glow',
      '50mm f/2 wide hotel suite morning — room architecture visible, figure still and private in the bed',
    ],
    morning_refresh: [
      '85mm f/1.4 straight-on hotel mirror framing, face and reflection at equal depth, marble behind',
      '50mm f/2 warm bathroom mid-shot with vanity bulbs softened by distance',
      '135mm f/2 tight on skin texture in clean morning light, brush or product hand in lower frame',
      '85mm f/1.8 side-angle bathroom shot, mirror edge at left, warm marble wall behind',
      '50mm f/1.8 low vanity level looking up, bulb reflections in mirror, face being prepared above',
      '35mm f/2.8 environmental bathroom frame showing the full ritual — counter, mirror, morning light, figure',
    ],
    getting_dressed: [
      '85mm f/1.4 full-length mirror portrait, hotel room depth compressed warmly behind the reflection',
      '50mm f/2 dressing-area frame with hanging rail of pieces visible to one side',
      '135mm f/2 tight on hand and fabric detail — fingers adjusting a lapel or heel strap',
      '85mm f/2 straight-on suite mirror shot, the off-duty silhouette sharp and the room soft behind',
      '50mm f/1.8 three-quarter suite shot from behind as she checks the look in the full mirror',
      '85mm f/1.4 close editorial frame on the face in the mirror — expression composed, look complete',
    ],
    breakfast: [
      '50mm f/2 table-level suite breakfast frame — tray, coffee, schedule, and hands in the foreground',
      '85mm f/1.4 window-side portrait, coffee cup at lower frame, Paris or Milan light outside behind',
      '135mm f/2 tight on the hands around the espresso cup, suite interior falling soft behind',
      '50mm f/2.8 wide room-service breakfast setup with the figure composed at the window table',
      '85mm f/1.8 straight-on breakfast portrait — clean face, natural light, fashion week quiet visible',
      '35mm f/2 hotel breakfast table establishing shot — tray architecture, city window, still morning',
    ],
    late_morning: [
      '50mm f/2 casting room wide — clean walls, overhead light, the model entering from the far end',
      '85mm f/1.4 casting close portrait — composure fully visible, evaluating eyes across from her out of frame',
      '135mm f/2 agency-room medium shot, portfolio on the table, industry light flat and honest',
      '85mm f/2 casting walk side-angle — the body in motion through clean white space',
      '50mm f/1.8 agency office environmental frame — daylight from one side, the model standing at the window',
      '135mm f/2.8 tight on the face during the casting walk — the expression that won the season',
    ],
    lunch: [
      '85mm f/1.4 café terrace portrait, Paris street compressed beautifully in the background',
      '50mm f/2 street-level moving frame — overcoat, pavement, motion, and city depth behind',
      '135mm f/2 tight editorial café shot — sunglasses, coffee, and the composed off-duty face',
      '85mm f/1.8 from across the café — the model at the table, street visible through the glass behind',
      '50mm f/2 Milan cobblestone crossing — wide enough to feel the street, tight enough to feel the composure',
      '85mm f/1.4 half-profile café frame — jaw line, coat collar, and the city out of focus behind',
    ],
    afternoon: [
      '85mm f/1.4 atelier portrait with pinned fabric in foreground and mirror behind — depth layered',
      '50mm f/2 editorial studio wide — cyclorama bright, lighting rigs visible at edges, figure centred',
      '135mm f/2 couture fitting detail — designer hands on fabric, model face upright and still',
      '85mm f/2 studio editorial frame — high-contrast lighting, clean background, model and concept aligned',
      '50mm f/1.8 atelier three-quarter shot — the dress half-finished on her body, mirror reflecting the work',
      '35mm f/2.8 editorial studio establishing frame — all the light, the look, and the space visible',
    ],
    reset: [
      '85mm f/1.4 backstage makeup chair portrait — vanity bulbs as warm backlight, chaos falling soft behind',
      '50mm f/2 backstage environmental frame — racks, mirrors, movement, and the model still at centre',
      '135mm f/2 tight on the face mid-transformation — brush held near cheekbone, expression unchanged',
      '85mm f/2 backstage mirror moment — the runway look complete, the model seeing herself for the first time',
      '50mm f/1.8 wide backstage ten-minutes-to-show frame — controlled urgency around a single still figure',
      '135mm f/2.8 close on the dressed look from the collarbone up — the show image fully assembled',
    ],
    golden_hour: [
      '135mm f/2 venue arrival close — amber light wrapping the face, photographers out of focus behind',
      '85mm f/1.4 street-style golden-hour frame, warm rim light on the coat, cobblestones glowing below',
      '50mm f/2 wide arrival shot — venue doors ahead, photographers to the side, model moving through light',
      '135mm f/2.8 tight on the walk — pavement and warm light below, face three-quarter to camera',
      '85mm f/2 car-door emergence — golden city light flooding into the frame as she steps out',
      '50mm f/1.8 street editorial frame in last sun — the overcoat catching warm light from two directions',
    ],
    dinner: [
      '50mm f/2 runway wide — full catwalk length visible, show lighting overhead, audience darkness each side',
      '135mm f/2 tight runway portrait — the designer look and the face that carries it, mid-walk',
      '85mm f/1.4 runway end close — the turn, the pause, the look held for the back row',
      '50mm f/1.8 finale pass wide — all models in motion, the full show light filling the frame',
      '135mm f/2.8 backstage-to-catwalk entry moment — the curtain edge, the step forward, the light arriving',
      '85mm f/2 catwalk silhouette frame — show lighting from above, the look in perfect motion',
    ],
    evening: [
      '85mm f/1.4 after-party low-light portrait — warm bokeh behind, face in one practicals beam',
      '50mm f/2 brand dinner table frame — candlelight, composed posture, fashion industry context visible',
      '135mm f/2 after-party close — the look still perfect, the room dark and warm behind',
      '85mm f/1.8 dinner table portrait — face three-quarter lit by candlelight, wine glass in lower frame',
      '50mm f/1.8 after-party environmental frame — the venue, the crowd, and the model composure visible',
      '35mm f/2 wide after-party shot — luxury space, warm light, and the model at the natural centre',
    ],
    night: [
      '85mm f/1.4 hotel suite night portrait — bedside lamp as the single warm key, city window behind',
      '135mm f/2 bathroom vanity mirror night close — makeup being removed, real face reappearing',
      '50mm f/2 suite window frame — the model in a robe, city lights below, the room quiet',
      '85mm f/1.8 low bedside angle — the model lying still, one lamp warm, the schedule no longer visible',
      '135mm f/2.8 close on the face with makeup half removed — the private and public face at the same moment',
      '50mm f/1.8 suite establishing night shot — room architecture, soft lamp, city beyond the glass',
    ],
  },

  lightingPools: {
    wake: [
      'soft 4500K hotel morning light filtering through blackout curtain edges onto white bedding',
      'warm 3800K table lamp still on from last night, mixed with first grey city light through the window',
      'clean diffused daylight at 5000K entering the suite from above sheer curtains, no hard shadows',
      'warm cream hotel ambient at 3500K in the suite — the room its own light source in early morning',
      'natural 5200K urban morning light coming through the high window, catching only the far pillow',
      'low warm 3200K bedside lamp as the single source, face in soft shadow, city beginning outside',
    ],
    morning_refresh: [
      'clean 5500K vanity bulb light softened by the distance to the mirror — even, honest, flattering',
      'warm marble reflection mixing with 4000K overhead bathroom light to create soft fill',
      '5200K mirror light with warm secondary bounce off cream-tiled wall — no harsh shadows',
      'pre-glam bathroom in clean white light at 5800K — the truth before the fashion transforms it',
      'warm 4200K hotel bathroom ambient with single vanity strip as the primary source',
      'natural morning window light at 5000K entering the bathroom — the cleanest light of the day',
    ],
    getting_dressed: [
      'clean 5000K suite daylight through large windows — flat, fashion-editorial, and honest',
      'warm 4200K room light with one daylight window creating soft side shadow on the look',
      'mirror-reflected natural light bouncing warm and diffused across the outfit and face',
      'suite overhead at 4500K with daylight window supplement — the getting-dressed light that reveals everything',
      'flat 5200K natural daylight that strips all mood and shows the look exactly as it will read outside',
      'warm 3800K suite ambient mixed with neutral window daylight — a gentle editorial getting-dressed glow',
    ],
    breakfast: [
      'soft 5200K natural window light across the breakfast table — the cleanest morning light available',
      'warm hotel ambient at 3800K with one daylight window creating gentle table-level fill',
      '4500K mixed morning light — window diffusion plus hotel warm ambient — quiet and real',
      'direct early morning sun at 5500K hitting the espresso cup and hands in horizontal low angle',
      'overcast 6000K daylight diffused through sheer hotel curtains — flat, clean, and slightly mournful',
      'room-service breakfast in warm 4000K suite light, city light just visible through curtain edge',
    ],
    late_morning: [
      'casting room overhead at 5500K — flat, institutional, and completely unforgiving',
      'agency daylight through large windows at 5800K — honest professional evaluation light',
      'clean 6000K casting room fluorescent with soft window supplement — no shadows, no mercy',
      'overcast city daylight pouring into the agency space at 5600K — the truest light in fashion',
      'single overhead 5200K in the casting room — the body and face exactly as they are',
      'agency window light at 5000K with slight warm bounce off interior walls — precision without warmth',
    ],
    lunch: [
      'dappled Paris café terrace light at 5800K with awning shadow creating soft natural contrast',
      'warm street midday light at 5500K on the model between cafés — full sun softened by the coat',
      'café interior 4000K ambient with warm city street light coming through the glass window',
      'Milan noon light at 6000K — high, flat, and editorial when the styling is strong enough to carry it',
      'open shade city light at 5200K on the café terrace — even, beautiful, and unplanned',
      'warm 4500K outdoor café light in late morning — the sun still low enough to be kind',
    ],
    afternoon: [
      'atelier daylight through north-facing windows at 5600K — the couture fitting light of Paris studios',
      'editorial studio at 5500K softbox overhead with two kicker lights — three-dimensional and controlled',
      'couture fitting room in diffused 5200K window light with a single warm practical on the far wall',
      'editorial high-contrast setup — 5800K key at forty-five degrees, no fill, stark and intentional',
      'atelier mirror light — natural diffusion bouncing off cream walls at 5000K, even and honest',
      'fashion editorial studio mixed light — 5500K key, 4000K warm ambient fill — the published look',
    ],
    reset: [
      'backstage vanity strip bulbs at 3200K — warm, close, and completely specific to the transformation',
      'makeup station under 5000K daylight-corrected bulbs built to show true colour before the runway',
      'backstage overhead fluorescent at 5500K mixed with warm mirror bulbs — the glam chair reality',
      'runway backstage in flat 5800K work light — every imperfection visible, every correction deliberate',
      'warm 4000K backstage mirror glow with cool overhead supplement — the becoming-the-show moment',
      'pre-runway makeup complete under mixed 5200K and 3800K — the look checked in both lights before the walk',
    ],
    golden_hour: [
      'warm 3000K sunset side-light catching the coat, face, and cobblestones in horizontal amber',
      'rich golden-hour light at 2800K wrapping the fashion week arrival from the west',
      'warm 3200K late-afternoon sun as a hard side key, city buildings creating secondary fill',
      'soft 3500K golden diffusion in the last hour of sun — the arrival lit as if by intention',
      'amber 2900K street light at the venue entrance — warm, directional, and cinematic without setup',
      'golden-hour backlight at 2800K creating a warm rim on the coat silhouette and dissolving the background',
    ],
    dinner: [
      'full runway show lighting — 6000K overhead spots with warm fill from ground-level strips',
      'catwalk in high-contrast 5500K spotlight, audience area in designed darkness beside it',
      'designer show lighting at 5800K key with 4000K warm fill creating dimension on the look',
      'runway at full show power — hard overhead light at 6000K, zero fill, maximum drama',
      'fashion show finale lighting — all channels open at 5500K, the catwalk fully exposed',
      'single tight runway spotlight at 4800K — the model and the look only, everything else black',
    ],
    evening: [
      'after-party in low 2600K warm practicals and candlelight — dark luxury and editorial shadow',
      'brand dinner in 2800K candlelit space with warm low ceiling pendants — power disguised as intimacy',
      'post-show party under 3000K warm amber bar lighting — expensive and deliberately low',
      'fashion week dinner in 2500K candlelight with one architectural 4000K fixture above the table',
      'after-party venue in mixed 2800K practicals and candles — editorial darkness with warm fill',
      'luxury dinner room at 3200K table-lamp level — the face lit from below by candle, above by warmth',
    ],
    night: [
      'single 3000K bedside lamp in the hotel suite — warm, private, and the only source',
      'bathroom vanity in 4500K after-dark with makeup removal — honest and intimate',
      'city light at mixed 4000K-6000K through the suite window — blue and white and distant',
      'suite sitting area in 2800K table lamp and city glow — warm interior against cold urban outside',
      'late-night hotel room with one 3200K floor lamp and blue city light crossing the ceiling',
      'hotel bedroom darkness with only the 4000K bathroom light spilling under the door',
    ],
  },

  moodPools: {
    wake: [
      'private luxury before public exposure — the fashion week silence that belongs only to her',
      'the model before the industry claims her — soft, unhurried, and entirely herself',
      'quiet pre-dawn composure in a room that costs more than most people earn in a month',
      'early morning stillness that belongs only to the person behind the image',
      'the rare unhurried hour before the fashion machine begins its demands',
      'the luxury hotel morning as the only honest moment in a day built around performance',
    ],
    morning_refresh: [
      'the face before the industry transforms it — clean, real, and privately powerful',
      'quiet pre-glam ritual energy — methodical, private, and entirely unobserved',
      'skin-deep composure before the makeup chair turns her into someone the world will study',
      'the still bathroom morning — the ritual that prepares the body to be looked at all day',
      'private feminine precision before the backstage circus begins',
      'the honest pre-performance moment where the real face and the fashion face briefly coexist',
    ],
    getting_dressed: [
      'off-duty editorial precision — every piece chosen with the same attention as the runway look',
      'the quiet authority of a woman assembling herself before entering a world that will evaluate her',
      'street-style confidence that requires no camera to validate it',
      'the deliberate off-duty look built with the eye of someone who has been dressed by the best',
      'the model dressing privately — no photographer, no direction, and still completely editorial',
      'controlled personal elegance before the fashion world demands professional perfection',
    ],
    breakfast: [
      'fashion week morning discipline — the quiet focus before a day of professional scrutiny',
      'the private breakfast energy before public visibility resumes',
      'unhurried professional calm before the casting-atelier-runway sequence begins',
      'the single unscheduled hour of the fashion day — coffee and the call sheet and no one watching',
      'quiet self-possession at the breakfast table before the industry takes the rest of the day',
      "the early-morning model focus — eating with intention before the body becomes the day's instrument",
    ],
    late_morning: [
      'total professional composure under industry evaluation — nothing given away, nothing needed back',
      'the casting room stillness — beauty and body meeting business without flinching',
      'quiet confidence in the face of judgment — the walk executed, the look held, the moment complete',
      'the controlled energy of a woman who has been evaluated by the best rooms and never looked away',
      'industry tension absorbed and neutralised by complete professional composure',
      'the agency appointment mood — precise, professional, and worth every second of the evaluation',
    ],
    lunch: [
      'the off-duty model composure — present in the city but untouched by its ordinary pace',
      'fashion week lunch energy — brief, intentional, and editorial even without trying',
      'the in-between calm of a model who moves between worlds with complete ease',
      'the quiet between appointments — coffee, street movement, and the preserved off-duty energy',
      'Paris or Milan off-duty confidence — the look doing the work while the model simply moves',
      'the editorial ease of a woman for whom the city is always a backdrop and never an obstacle',
    ],
    afternoon: [
      'couture precision energy — the body as architecture, the fitting as the most serious creative act',
      'editorial studio focus — the model and photographer finding the image between direction and instinct',
      'the atelier transformation mood — fabric and pins and the slow emergence of the show look',
      'magazine-cover intensity — clean, directed, and entirely sure of its own power',
      'the studio editorial focus that makes the difference between a beautiful picture and a great one',
      'couture fitting presence — the model completely still, completely professional, completely the point',
    ],
    reset: [
      'pre-show backstage composure — the only still point in a space full of urgent movement',
      'the transformation energy — the private face becoming the public image, step by controlled step',
      'backstage focus that holds through chaos, noise, pins, brushes, and show-countdown pressure',
      'the glam chair mood — passive on the outside, entirely present on the inside',
      'runway preparation energy — the body and face being made into the show, ten minutes from the catwalk',
      'the backstage moment when the transformation is complete and the runway image is fully real',
    ],
    golden_hour: [
      'fashion week arrival power — the look meeting the best light of the day at the right moment',
      'golden-hour editorial energy — the city and the styling and the natural light briefly perfect together',
      'the arrival composure that makes the photographers move instead of waiting',
      'warm pre-show energy — the last natural light before the venue swallows everything',
      'street-style authority at golden hour — unforced, editorial, and completely aware',
      'the sidewalk-to-runway transition energy — public movement that carries the same weight as the catwalk',
    ],
    dinner: [
      'runway composure at maximum exposure — the world watching and nothing needing to be performed',
      'catwalk energy — focused, disciplined, and entirely built around the look and the walk',
      'the fashion show moment — total professional presence under complete public scrutiny',
      'peak runway power — the walk, the turn, the pause, and the return, all executed without a missed beat',
      'the controlled intensity of the catwalk — no room for doubt, hesitation, or self-consciousness',
      'show energy at full expression — the model and the look and the runway light all at once',
    ],
    evening: [
      'post-runway social grace — the composure carrying from the catwalk into the room',
      'fashion after-party energy — visible, controlled, and still entirely on her own terms',
      'brand dinner power — the same authority the runway demands, now applied to conversation',
      'the post-show evening mood — the performance technically over, but the presence still required',
      'fashion week social ease — the model in the room that evaluates her and completely at ease in it',
      'the evening transition from public image to private person — beginning but not yet complete',
    ],
    night: [
      'post-show private decompression — the public armor dissolving back into the private person',
      'hotel suite solitude after the fashion day — the luxury and the exhaustion in the same room',
      'the late-night private energy when the runway face is finally gone and the real face returns',
      'quiet relief in the still suite — the world finished with her for today, the night finally hers',
      'the honest model night — expensive room, difficult day, and the private human finally alone in it',
      'fashion week decompression in the dark hotel suite — the performance over, the person present',
    ],
  },

  stylingPools: {
    wardrobe: {
      wake: [
        'white hotel robe over minimal underwear in the suite morning',
        'oversized vintage fashion week t-shirt and bare legs in rumpled luxury bedding',
        'silk slip in ivory or cream against white hotel linen — private and expensive',
        'cashmere bed-sock and robe layering in the cool hotel suite morning',
        'the model in nothing but the robe she pulled from the bathroom hook — private and unhurried',
        'soft modal lounge set in neutral tones worn in the quiet of the hotel morning',
      ],
      morning_refresh: [
        'hotel robe open over skin-toned underwear at the vanity mirror',
        'white fluffy towel wrap at the vanity, skincare laid out in sequence',
        'the luxury robe fully on while products are applied — private preparation before the glam chair',
        'bare face and silk robe at the bathroom mirror — the anti-fashion moment inside the fashion world',
        'barely dressed at the hotel vanity — underwear and robe, products, and the pre-glam ritual',
        'the hotel towel worn with the precision of someone who knows every camera angle',
      ],
      getting_dressed: [
        'wide-leg tailored trouser in black or camel, structured blazer, clean white shirt — off-duty editorial',
        'oversized camel coat over a simple slip dress and white sneakers — the model-off-duty archetype',
        'slim dark denim, Saint Laurent boots, and a perfectly oversized wool coat',
        'tailored black wide-leg suit worn as a full look — the off-duty editorial that requires no styling',
        'minimal fitted turtleneck in oatmeal with sharp trousers and heeled ankle boots',
        'the luxury basics uniform — cashmere top, slim trouser, tote, sneakers, no jewellery needed',
      ],
      breakfast: [
        'hotel robe or soft lounge set at the breakfast table — private and unhurried',
        'the oversized t-shirt and silk shorts look at the room service table',
        'casual trouser and thin knit in a neutral tone — dressed enough for the corridor, private enough for the suite',
        'slip dress and bare feet at the suite window table — the off-schedule breakfast look',
        'simple ribbed modal set in cream — the breakfast outfit that requires no decision at all',
        'the fashion week hotel robe worn fully at the breakfast table — call sheet nearby, industry still distant',
      ],
      late_morning: [
        'clean casting look — minimal, fitted, and specifically designed to show the body without distraction',
        'slim black trouser, fitted white t-shirt, black leather loafer — the casting classic',
        'body-conscious midi dress in solid tone — neutral, precise, and framing',
        'tailored jacket over a fitted bodysuit and straight trouser — the agency appointment uniform',
        'the casting skin-tight basis — nude tones, body-con cut, and complete clarity of silhouette',
        'fitted pencil skirt and a thin-knit top in a neutral palette — showing the body, showing the walk',
      ],
      lunch: [
        'oversized leather coat over slim jeans and ankle boots — the off-duty Paris lunch look',
        'camel trench cinched at the waist over a simple black trouser and clean boot',
        'street-style moment in a printed silk scarf, oversized blazer, and wide-leg trouser',
        'luxury off-duty in a simple ribbed dress with an oversized coat thrown over — effortless and expensive',
        'dark denim, clean white shirt, and a designer tote — the lunch look that requires no effort',
        'slim silk slip dress under an oversized leather jacket — the Milan lunch wardrobe in two pieces',
      ],
      afternoon: [
        'fitted nude or body-tone unitard for the atelier fitting — the body as the canvas',
        'editorial studio look in high-fashion concept — structured, styled, and intentionally striking',
        'the couture fitting underpinning — seamless nude underwear and heels beneath the half-built dress',
        'editorial studio look in full magazine concept — coat, cut, colour, and styling at maximum',
        'the atelier look in progress — a partially pinned couture piece over minimal foundation garments',
        'the studio editorial wardrobe — bold cut, intentional colour, and the precise accessories the look demands',
      ],
      reset: [
        'the show look being applied over the fitting foundation — the final backstage dress already on',
        'dressing gown worn until the last minute before the show outfit goes on',
        'backstage ready in the runway look — the final styling still being completed around her',
        'the runway look fully on — hair and makeup complete, the show image assembled and waiting',
        'the designer look from the show lineup — bold, couture, and completely the point',
        'the backstage uniform in transition — silk robe over the runway foundation until five minutes to show',
      ],
      golden_hour: [
        'fashion week arrival look — oversized structured coat, heeled boots, minimal base layer, tote',
        'street-style editorial in a dramatic overcoat over a simple look — the coat doing the work',
        'fashion week statement look — printed or textured coat, sharp trouser, editorial footwear',
        'the arrival oversized blazer over a bodysuit and fitted trouser — street-style perfection',
        'camel maxi coat over black and white base — the fashion week arrival uniform at its best',
        'the editorial street-style moment — oversized wool check coat, bucket hat, slim boots, no jewellery',
      ],
      dinner: [
        'the full designer runway look — the garment the season has been building toward',
        'show finale couture — the most technically demanding piece of the collection on the body',
        'the runway look for the high-profile show — a major designer piece worn exactly as it was built',
        'catwalk closing look — architectural, sculptural, and specifically requiring her body to carry it',
        'the headline-making runway piece — colour, cut, and concept at their most complete',
        'the show look at its peak — the fabric moving exactly as the designer intended under full light',
      ],
      evening: [
        'post-show after-party look — the runway sophistication restaged for dark luxury social visibility',
        'brand dinner in a clean editorial evening look — tailored, dark, and quietly dominant',
        'the after-party transition — the show look replaced by a sleek dark fashion week evening piece',
        'fashion week after-party in a black minimal silk dress and single designer earring — perfect',
        'brand dinner in a sharp designer suit — the fashion world social look that means business',
        'the evening statement in a luxury fabric — a single great piece, the body, and nothing else needed',
      ],
      night: [
        'hotel robe again — the opening and closing of the day in the same private luxury uniform',
        'silk pyjama top and minimal shorts in the suite night',
        'the model in underwear and an oversized vintage tee at the hotel mirror removing her makeup',
        'soft modal lounge set in the suite at night — the fashion day fully closed',
        'the luxury hotel night look — cashmere socks, robe, and the private face finally showing',
        'bare-faced in a silk slip in the dark suite — the furthest point from the runway the day allows',
      ],
    },
  },

  fallbackRules: {
    pacingProfile: {
      wake: 'slow',
      morning_refresh: 'slow',
      getting_dressed: 'slow',
      breakfast: 'slow',
      late_morning: 'medium',
      lunch: 'slow',
      afternoon: 'medium',
      reset: 'slow',
      golden_hour: 'slow',
      dinner: 'slow',
      evening: 'medium',
      night: 'slow',
    },
    repetitionBreakers: {
      avoidBackToBackSameLocation: true,
      avoidBackToBackSameLightingStyle: true,
      encourageWardrobeEvolution: true,
    },
    worldDefaults: {
      allowSceneGroupFallbackToPhasePools: true,
      allowSubLocationFallbackToWorldPools: true,
      preferSceneGroupsWhenPresent: true,
    },
  },

  exclusions: {
    premium: [
      'generic influencer posing',
      'cheap fashion cliché',
      'non-editorial glamour',
      'messy non-fashion environments',
      'ordinary shopping mall fashion energy',
    ],
    hard: [
      'gym or wellness settings',
      'corporate office unrelated to fashion',
      'beach vacation without editorial context',
      'nightclub chaos without fashion week relevance',
      'low-status fast-fashion aesthetic',
    ],
  },

  routeRules: {
    worldIdentity: [
      'the Supermodel Life world must feel like elite fashion mythology — runway, casting, atelier, editorial studio, hotel suite, and after-party all connected by professional composure',
      'the model is not simply beautiful; she is evaluated, transformed, styled, lit, watched, booked, and remembered',
    ],
    humanFlow: [
      'the day begins in private hotel silence, moves through casting judgment and atelier or editorial transformation, peaks at runway visibility, then collapses back into private hotel decompression',
      'every phase should preserve the contrast between public image and private human reality',
    ],
    styling: [
      'wardrobe evolves from private hotel softness to off-duty street style, then couture fitting or editorial concept, then runway look, after-party statement, and finally private hotel night',
      'fashion must feel high-end, intentional, fitted, styled, and editorial — never random clothing',
    ],
    atmosphere: [
      'fashion week pressure, backstage chaos, casting silence, atelier precision, runway light, and hotel-room quiet are the defining atmospheres',
      'the world should always feel expensive, selective, image-conscious, and emotionally controlled',
    ],
  },
}
