export const STORY_WORLD_SWIM_MODEL = {
  id: 'swim-model',
  name: 'Swim Model',
  description:
    'A cinematic world of sun, water, and the body at its most beautiful — luxury pool and ocean locations, editorial swimwear, the particular power of water on skin, sun-drenched confidence from Mykonos to Malibu to Bali.',

  geography: { country: 'global luxury beach / pool', region: 'Mykonos, Malibu, Bali, Tulum, Capri, Maldives — luxury pool and ocean locations' },

  identity: {
    archetype: 'swim model — editorial ocean and pool creator',
    vibe: ['sun and salt water on the most beautiful body', 'editorial swimwear in the best light in the world', 'the ocean as the most beautiful backdrop', 'water on skin as the most cinematic element', 'sun-drenched Mediterranean or tropical confidence'],
    tone: ['radiant', 'sun-soaked', 'editorial', 'confident', 'free', 'beautiful', 'cinematic', 'water-alive'],
    persona: ['the most beautiful person at every pool and beach on earth', 'completely at ease in swimwear in the strongest sun', 'the body as editorial subject in the most beautiful water', 'natural and deliberate simultaneously in ocean or pool light'],
  },

  phaseOrder: ['wake', 'morning_refresh', 'getting_dressed', 'breakfast', 'late_morning', 'lunch', 'afternoon', 'reset', 'golden_hour', 'dinner', 'evening', 'night'],

  phases: {
    wake:            { label: 'Wake',            timeWindows: ['tropical or Mediterranean morning in villa or hotel room', 'warm sunrise in beach destination bedroom'],              pacing: 'slow',   subLocations: ['beach-villa-bedroom', 'luxury-hotel-room'] },
    morning_refresh: { label: 'Morning Refresh', timeWindows: ['warm tropical bathroom morning', 'post-swim or shower bathroom in warm destination'],                               pacing: 'slow',   subLocations: ['tropical-bathroom', 'suite-vanity'] },
    getting_dressed: { label: 'Getting Dressed', timeWindows: ['swimwear selection in warm destination morning', 'choosing the editorial swimwear look'],                           pacing: 'slow',   subLocations: ['beach-villa-bedroom', 'tropical-bathroom'] },
    breakfast:       { label: 'Breakfast',       timeWindows: ['tropical breakfast on villa terrace or hotel', 'ocean-view morning meal in warm destination'],                      pacing: 'slow',   subLocations: ['villa-terrace', 'hotel-pool-terrace'] },
    late_morning:    { label: 'Late Morning',    timeWindows: ['luxury pool or beach arrival in warm late-morning', 'editorial swim moment in morning light'],                      pacing: 'medium', subLocations: ['luxury-pool', 'ocean-beach'] },
    lunch:           { label: 'Lunch',           timeWindows: ['beach club or pool terrace lunch in full sun', 'ocean-view lunch at the most beautiful setting'],                  pacing: 'slow',   subLocations: ['beach-club-lunch', 'pool-terrace-lunch'] },
    afternoon:       { label: 'Afternoon',       timeWindows: ['afternoon at the pool or ocean in the strongest sun', 'editorial afternoon swim or beach moment'],                  pacing: 'medium', subLocations: ['luxury-pool', 'ocean-beach'] },
    reset:           { label: 'Reset',           timeWindows: ['post-beach or pool villa reset', 'showering off salt or chlorine before evening'],                                  pacing: 'slow',   subLocations: ['beach-villa-bedroom', 'tropical-bathroom'] },
    golden_hour:     { label: 'Golden Hour',     timeWindows: ['golden hour at the pool or ocean — the most beautiful swim model light', 'sunset water moment'],                   pacing: 'slow',   subLocations: ['pool-golden-hour', 'ocean-sunset'] },
    dinner:          { label: 'Dinner',          timeWindows: ['beach club or villa dinner in warm evening', 'dinner above the ocean in warm destination evening'],                pacing: 'slow',   subLocations: ['beach-dinner', 'villa-terrace'] },
    evening:         { label: 'Evening',         timeWindows: ['warm evening at the beach club or hotel', 'post-dinner destination evening in beach luxury'],                       pacing: 'slow',   subLocations: ['beach-club-evening', 'villa-terrace'] },
    night:           { label: 'Night',           timeWindows: ['private villa or hotel night in warm tropical destination', 'the swim model at rest in warm night'],               pacing: 'slow',   subLocations: ['beach-villa-bedroom', 'luxury-hotel-room'] },
  },

  locations: [
    'villa bedroom in warm tropical or Mediterranean morning', 'luxury pool in editorial swim morning light',
    'open ocean at the most beautiful beach', 'villa terrace breakfast with ocean view',
    'beach club lunch table in full sun', 'golden hour at the pool or ocean edge',
    'beach club dinner in warm tropical evening', 'ocean-view villa terrace at night',
  ],

  subLocations: {
    'beach-villa-bedroom': {
      id: 'beach-villa-bedroom', name: 'Beach Villa Bedroom', mapAnchor: 'beach villa bedroom morning',
      category: 'private-beach',
      bestPhases: ['wake', 'getting_dressed', 'reset', 'night'],
      overlays: ['white linen in warm tropical bedroom', 'ocean air from open shutters or curtains', 'warm tropical or Mediterranean morning interior', 'swim destination private morning'],
      locations: ['villa bedroom in warm tropical morning', 'Mediterranean or tropical beach villa interior', 'private beach destination morning bedroom'],
    },
    'luxury-hotel-room': {
      id: 'luxury-hotel-room', name: 'Luxury Hotel Room', mapAnchor: 'luxury beach hotel room',
      category: 'private-hotel-beach',
      bestPhases: ['wake', 'night'],
      overlays: ['luxury hotel bed with ocean air', 'warm tropical hotel morning interior', 'beach luxury hotel bedroom'],
      locations: ['luxury hotel room in warm beach destination morning', 'tropical beach hotel interior', 'warm hotel bedroom with ocean beyond'],
    },
    'tropical-bathroom': {
      id: 'tropical-bathroom', name: 'Tropical Bathroom', mapAnchor: 'warm tropical bathroom',
      category: 'self-care-beach',
      bestPhases: ['morning_refresh', 'getting_dressed', 'reset'],
      overlays: ['warm tropical bathroom in beach destination', 'outdoor shower or warm interior bath', 'post-swim or post-sea rinse setting'],
      locations: ['warm tropical bathroom in beach destination', 'outdoor shower after the sea', 'pool or beach post-swim bathroom ritual'],
    },
    'suite-vanity': {
      id: 'suite-vanity', name: 'Suite Vanity', mapAnchor: 'beach hotel suite vanity',
      category: 'preparation-beach',
      bestPhases: ['morning_refresh'],
      overlays: ['warm tropical vanity in beach hotel', 'light beach destination makeup ritual', 'sun-ready preparation in warm morning'],
      locations: ['beach hotel suite vanity in morning', 'warm tropical preparation setting', 'beach destination morning preparation'],
    },
    'villa-terrace': {
      id: 'villa-terrace', name: 'Villa Terrace', mapAnchor: 'ocean-view villa terrace',
      category: 'breakfast-view',
      bestPhases: ['breakfast', 'dinner', 'evening', 'night'],
      overlays: ['ocean or pool view from villa terrace', 'warm tropical morning or evening light', 'villa terrace breakfast or dinner setting'],
      locations: ['villa terrace with ocean view in morning', 'tropical villa terrace with pool or sea', 'warm evening villa terrace above the ocean'],
    },
    'hotel-pool-terrace': {
      id: 'hotel-pool-terrace', name: 'Hotel Pool Terrace', mapAnchor: 'luxury beach hotel pool terrace',
      category: 'breakfast-pool',
      bestPhases: ['breakfast'],
      overlays: ['luxury hotel pool terrace in morning', 'ocean or pool view at breakfast', 'warm tropical hotel morning'],
      locations: ['luxury hotel pool terrace breakfast', 'beach hotel morning with ocean or pool', 'tropical hotel breakfast setting'],
    },
    'luxury-pool': {
      id: 'luxury-pool', name: 'Luxury Pool', mapAnchor: 'editorial luxury pool',
      category: 'swim-editorial',
      bestPhases: ['late_morning', 'afternoon', 'golden_hour'],
      overlays: ['infinity or editorial luxury pool in destination sun', 'pool water surface in strong tropical light', 'swim model in or beside the pool in editorial setting'],
      locations: ['infinity pool in strong tropical or Mediterranean sun', 'editorial luxury pool in the best light', 'pool edge or water surface in destination sun'],
    },
    'ocean-beach': {
      id: 'ocean-beach', name: 'Ocean Beach', mapAnchor: 'open ocean or beach',
      category: 'ocean-editorial',
      bestPhases: ['late_morning', 'afternoon'],
      overlays: ['open ocean or beach in strong destination sun', 'waves or turquoise water behind', 'beach editorial in the most beautiful water setting'],
      locations: ['open ocean beach in strong tropical sun', 'waves at the shore in editorial beach light', 'turquoise ocean in destination afternoon sun'],
    },
    'beach-club-lunch': {
      id: 'beach-club-lunch', name: 'Beach Club Lunch', mapAnchor: 'luxury beach club lunch table',
      category: 'beach-dining',
      bestPhases: ['lunch'],
      overlays: ['luxury beach club lunch table in sun or shade', 'ocean or pool view at lunch', 'swim model at beach club table'],
      locations: ['luxury beach club lunch setting in full sun', 'beach club terrace table with ocean', 'warm destination beach club lunch'],
    },
    'pool-terrace-lunch': {
      id: 'pool-terrace-lunch', name: 'Pool Terrace Lunch', mapAnchor: 'pool terrace lunch',
      category: 'pool-dining',
      bestPhases: ['lunch'],
      overlays: ['pool terrace lunch in warm destination sun', 'ocean or pool visible beyond the table', 'tropical or Mediterranean poolside lunch'],
      locations: ['pool terrace or villa lunch in warm destination', 'ocean-view terrace lunch setting', 'tropical poolside lunch table'],
    },
    'pool-golden-hour': {
      id: 'pool-golden-hour', name: 'Pool Golden Hour', mapAnchor: 'pool at golden hour',
      category: 'golden-swim',
      bestPhases: ['golden_hour'],
      overlays: ['pool at golden hour — water turning amber', 'swim model in amber pool light', 'the most beautiful pool moment of the day'],
      locations: ['infinity pool at golden hour in amber light', 'pool edge in warm amber golden-hour water', 'pool surface turning gold at sunset'],
    },
    'ocean-sunset': {
      id: 'ocean-sunset', name: 'Ocean Sunset', mapAnchor: 'ocean at golden hour',
      category: 'ocean-golden',
      bestPhases: ['golden_hour'],
      overlays: ['ocean at golden hour with amber water', 'the most beautiful ocean moment of the day', 'swim model at ocean edge in amber light'],
      locations: ['ocean edge at golden hour with amber water', 'swim model silhouetted at ocean sunset', 'open sea turning amber at the golden hour'],
    },
    'beach-dinner': {
      id: 'beach-dinner', name: 'Beach Dinner', mapAnchor: 'beach or ocean dinner setting',
      category: 'beach-evening',
      bestPhases: ['dinner'],
      overlays: ['warm beach club or ocean-view dinner', 'elevated beach destination evening dining', 'the swim model at beach dinner — elevated and warm'],
      locations: ['beach club dinner in warm evening', 'ocean-view restaurant in warm destination', 'warm tropical beach dinner setting'],
    },
    'beach-club-evening': {
      id: 'beach-club-evening', name: 'Beach Club Evening', mapAnchor: 'beach club after dinner',
      category: 'beach-night',
      bestPhases: ['evening'],
      overlays: ['warm beach club evening energy', 'ocean air and warm ambient in beach evening', 'swim model at beach club after dinner'],
      locations: ['beach club in warm destination evening', 'tropical or Mediterranean warm beach evening', 'warm beach destination after-dinner setting'],
    },
  },

  sceneVariants: {
    wake: ['waking in a villa bedroom with warm ocean air through open shutters', 'tropical morning wake in white linen before the swim day begins'],
    morning_refresh: ['outdoor shower or warm tropical bathroom after morning swim', 'beach destination morning ritual in warm tropical setting'],
    getting_dressed: ['choosing the editorial swimwear in warm villa morning light', 'the swim model dressing ritual — the swimwear that will face the ocean'],
    breakfast: ['villa terrace breakfast with ocean view in warm tropical morning', 'beach hotel breakfast with pool or sea and warm destination sun'],
    late_morning: ['editorial luxury pool moment in strong late-morning light', 'arriving at the ocean beach in warm late-morning destination sun'],
    lunch: ['beach club lunch in full tropical or Mediterranean sun', 'pool terrace or villa ocean-view lunch in warm destination'],
    afternoon: ['editorial afternoon swim at the pool or ocean in the strongest sun', 'pool or ocean swim in the hottest most photographic afternoon light'],
    reset: ['post-sea or pool villa shower — salt water washing off in warm tropical', 'the swim model after the ocean — natural skin and sun-touched in warm setting'],
    golden_hour: ['golden hour at the pool — water turning amber in the most beautiful light', 'ocean edge at golden hour — the most cinematic swim model moment'],
    dinner: ['beach club or villa dinner in warm tropical or Mediterranean evening', 'ocean-view dinner in warm destination evening'],
    evening: ['warm beach club evening after dinner in tropical or Mediterranean air', 'villa terrace in warm destination evening with the ocean below'],
    night: ['villa or hotel private night in warm tropical destination', 'the swim model at rest in warm private beach destination night'],
  },

  actionPools: {
    wake: ['waking in villa bedroom with warm ocean air', 'slow warm tropical morning before the swim day begins', 'the swim model morning — warm, sun-ready, and at ease'],
    morning_refresh: ['outdoor shower or warm tropical bathroom morning ritual', 'beach destination morning self-care in warm setting', 'getting ready for the editorial swim day'],
    getting_dressed: ['choosing the editorial swimwear in warm villa morning light', 'the swimwear selection for the ocean or pool shoot', 'the swim model dressing — every piece chosen for water and light'],
    breakfast: ['villa terrace breakfast with coffee and ocean air in warm morning', 'hotel pool terrace breakfast with the sea beyond', 'slow tropical morning before the beach or pool'],
    late_morning: ['arriving at the luxury pool or ocean in warm late-morning light', 'the first editorial swim moment in late-morning light', 'the swim model at the pool or ocean — arriving and beginning'],
    lunch: ['beach club lunch with ocean view in full warm sun', 'pool terrace lunch in warm destination midday', 'the swim model at lunch — at ease in the most beautiful setting'],
    afternoon: ['editorial swim in the pool or ocean in the strongest afternoon light', 'in the water or at the pool edge in the most photographic afternoon moment', 'the swim model in full afternoon editorial presence'],
    reset: ['showering off the sea or pool in warm tropical bathroom', 'the post-swim private reset in villa or hotel', 'the swim model after the water — natural and warm before evening'],
    golden_hour: ['the golden hour at the pool — water amber and the most beautiful light of the day', 'ocean edge at golden hour — the most cinematic swim model moment', 'the swim model in the most beautiful water light on earth'],
    dinner: ['beach club or villa dinner in warm tropical or Mediterranean evening', 'elevated dinner above the ocean in warm destination evening', 'the swim model at beach dinner — elevated and composed'],
    evening: ['warm beach club evening after dinner in tropical or Mediterranean air', 'villa terrace above the ocean in warm destination evening', 'the swim model in warm destination evening ease'],
    night: ['villa or hotel private night in warm tropical destination', 'warm private night in beach destination after a full swim day', 'the swim model at rest in warm private beach luxury'],
  },

  environmentPools: {
    wake: ['villa bedroom in warm tropical morning with ocean air through open shutters', 'luxury hotel bedroom in warm beach destination morning', 'white linen in warm beach villa before the swim day'],
    morning_refresh: ['warm tropical bathroom in destination setting', 'outdoor shower or warm interior bath in beach villa', 'post-swim or sea rinse in warm tropical destination'],
    getting_dressed: ['beach villa bedroom in warm morning with swimwear selection', 'warm tropical interior in editorial swim morning', 'villa dressing in warm destination morning light'],
    breakfast: ['villa terrace with ocean or pool view in warm morning', 'beach hotel pool terrace breakfast in morning sun', 'warm destination breakfast above the ocean or pool'],
    late_morning: ['editorial luxury pool in warm late-morning destination light', 'open ocean or beach in warm tropical late morning', 'the swim model arriving at the water in late-morning light'],
    lunch: ['luxury beach club lunch table in full destination sun', 'pool terrace or villa ocean-view lunch in midday warm', 'the most beautiful lunch setting in the water world'],
    afternoon: ['infinity pool in the strongest tropical or Mediterranean afternoon sun', 'open ocean or beach in full afternoon editorial light', 'pool water surface and swim model in afternoon sun editorial'],
    reset: ['warm tropical bathroom or outdoor shower post-sea', 'villa bedroom in warm tropical late afternoon after the water', 'beach destination reset in warm private interior'],
    golden_hour: ['infinity pool at golden hour — water turning amber', 'ocean edge in amber golden-hour light at most beautiful moment', 'the swim model and the water at the most cinematic light of day'],
    dinner: ['beach club dinner in warm destination evening', 'villa terrace above the ocean in warm dinner light', 'warm tropical ocean-view dinner setting'],
    evening: ['beach club in warm destination evening air', 'villa terrace in warm Mediterranean or tropical evening', 'beach destination evening with warm ocean air'],
    night: ['beach villa bedroom in warm tropical night', 'luxury hotel in warm destination at night', 'private beach destination night in warm interior'],
  },

  moodPools: {
    wake: ['warm tropical morning ease before the swim day', 'the swim model morning — sun-ready and at ease in destination warmth', 'unhurried beach destination morning luxury'],
    morning_refresh: ['fresh post-swim or pre-swim destination morning', 'warm beach self-care ritual energy', 'getting ready for the most beautiful day in water'],
    getting_dressed: ['editorial swimwear anticipation — choosing for water and light', 'the swim model dressing for the ocean or pool', 'warm destination dressing ritual energy'],
    breakfast: ['slow warm tropical breakfast ease above the ocean', 'beach destination morning luxury and ease', 'the swim model morning before the water opens'],
    late_morning: ['arriving at the water — the editorial moment begins', 'the pool or ocean in warm late-morning destination light', 'swim model energy building in morning sun'],
    lunch: ['beach club ease in full sun with ocean beyond', 'warm destination midday swim model ease at the table', 'relaxed editorial energy at the best beach club lunch'],
    afternoon: ['full sun editorial swim energy — the most alive and radiant moment', 'the swim model in water at maximum photographic power', 'the body at its most beautiful in the strongest destination light'],
    reset: ['post-water natural warmth and ease — sun-touched and beautiful', 'the swim model after the sea — warm and private and natural', 'warm tropical post-swim ease before evening'],
    golden_hour: ['the most beautiful water light on earth — golden hour at pool or ocean', 'swim model amber-water golden-hour energy at peak', 'the most cinematic swim model moment of the day'],
    dinner: ['warm beach destination evening ease at the dinner table', 'the swim model at evening — elevated from the beach day', 'warm tropical dinner energy in the most beautiful destination'],
    evening: ['warm beach club evening ease after the full swim day', 'Mediterranean or tropical evening in warm destination air', 'the swim model at ease in warm destination evening'],
    night: ['warm private beach destination night ease', 'the swim model at rest after the most beautiful water day', 'tropical or Mediterranean private night warmth'],
  },

  cameraPools: {
    wake: ['85mm low angle in villa bedroom, ocean window dissolved behind in morning bokeh', '135mm close-up at face height, warm tropical morning light defining edge'],
    morning_refresh: ['85mm outdoor shower or tropical bathroom, warm setting behind', '50mm warm tropical bathroom mid shot, setting compressing behind'],
    getting_dressed: ['50mm villa mirror-framed dressing shot, swimwear and villa depth behind', '85mm editorial swimwear selection, warm tropical depth behind subject'],
    breakfast: ['24mm wide villa terrace, ocean or pool filling background beyond table', '85mm soft breakfast framing, ocean or pool dissolved in warm background'],
    late_morning: ['85mm pool or beach arrival medium, water and destination behind subject', '135mm water close-up, pool or ocean surface dissolving in warm bokeh'],
    lunch: ['85mm beach club seated lunch, ocean or pool depth behind subject', '50mm pool terrace lunch framing, warm destination depth behind'],
    afternoon: ['24mm wide editorial pool or ocean, sun flattening water geometry behind', '50mm editorial pool low angle, water surface in foreground, destination dissolved beyond', '85mm ocean swim medium, waves or turquoise water behind editorial subject'],
    reset: ['85mm tropical bathroom post-swim, warm setting behind subject', '135mm close post-swim natural skin detail in warm tropical setting'],
    golden_hour: ['135mm golden-hour pool or ocean close, amber rim light defining edge of subject', '24mm wide golden-hour water shot, entire ocean or pool turning amber in background'],
    dinner: ['85mm beach club dinner candlelit portrait, warm evening ambient behind', '50mm villa terrace dinner medium, ocean visible in warm evening background'],
    evening: ['85mm beach club evening medium, warm destination ambient behind subject', '50mm villa terrace evening, warm ocean or sky behind subject'],
    night: ['135mm villa night close-up, warm lamp as sole source', '85mm soft tropical night, warm villa bedroom dissolved behind subject'],
  },

  lightingPools: {
    wake: ['pale 5400K tropical morning light through villa shutters, warm long shadows across white linen', 'soft diffused warm sunrise through beach destination curtains, warm edge on pillow'],
    morning_refresh: ['clean 5600K tropical bathroom or outdoor shower morning, fresh and bright', 'warm outdoor shower natural light in tropical destination — most beautiful skin light'],
    getting_dressed: ['warm 5200K villa morning interior, swimwear textures and skin in warm natural light', 'bright tropical morning through villa window, clean warm color rendering'],
    breakfast: ['warm 5000K tropical morning on villa terrace, ocean reflections in secondary fill', 'clean beach destination breakfast light — warm and natural'],
    late_morning: ['5200K tropical sun strong in late morning, pool or ocean surface creating secondary fill below', 'clear warm destination water-reflected light in late morning — specular on water'],
    lunch: ['high tropical noon with beach club shade, ocean brightness as warm backlight', 'warm 5600K beach club midday, secondary fill from water below'],
    afternoon: ['strong 4800K tropical afternoon sun on pool or ocean, maximum specular on water surface', 'hard westward tropical sun, high saturation color, water as secondary reflector below'],
    reset: ['warm 4200K tropical interior post-swim, soft and flattering after the sun', 'outdoor shower warm natural reset light in tropical afternoon'],
    golden_hour: ['rich 2700K golden tropical sunset on pool or ocean — water turning amber at near-zero angle', 'warm amber pool or ocean light at golden hour — the most beautiful swim model light'],
    dinner: ['warm 2800K beach club or villa dinner, candlelit warm ambient in destination evening', 'beach destination dinner light — warm and golden with ocean beyond'],
    evening: ['warm 2600K beach club evening, warm destination ambient with ocean air', 'villa terrace warm 2800K evening, destination warmth and ocean glow'],
    night: ['single warm 2200K lamp in villa, warm private tropical night interior', 'low 2400K beach destination hotel night — warm and private'],
  },

  stylingPools: {
    wardrobe: {
      wake: ['white linen or nothing in villa bedroom morning', 'warm tropical morning sleepwear in beach destination', 'barely dressed tropical morning in white or light linen'],
      morning_refresh: ['towel wrap after outdoor shower in warm setting', 'white bath towel in tropical destination bathroom', 'pre-swimwear tropical morning in warm setting'],
      getting_dressed: ['editorial swimwear selection — the piece that faces the ocean', 'luxury bikini or one-piece for the swim editorial day', 'the swim model swimwear choice — every detail for water and light'],
      breakfast: ['silk or linen wrap over swimwear at villa terrace', 'linen cover at beach hotel terrace breakfast', 'tropical morning breakfast styling — swimwear and casual cover'],
      late_morning: ['editorial swimwear arriving at pool or ocean', 'the swim model at the water — swimwear at its most editorial', 'luxury bikini or editorial swim piece in late-morning destination light'],
      lunch: ['elevated swimwear or linen beach wrap at the beach club', 'beach club styling — elevated cover-up or linen with swimwear', 'the swim model at lunch — casual editorial beach ease'],
      afternoon: ['editorial swimwear in the strongest afternoon light and water', 'the bikini or swim piece at its most editorial — full sun afternoon', 'the swim model at full editorial power in afternoon water'],
      reset: ['linen wrap or nothing post-swim in warm tropical', 'post-sea towel or cover in warm tropical bathroom reset', 'natural warm post-water styling in beach destination'],
      golden_hour: ['the most editorial swim look in the golden-hour light', 'swimwear or nothing at the pool or ocean at golden hour', 'the swim model in the most beautiful light — the most editorial swim moment'],
      dinner: ['elevated beach destination dinner look — silk dress or linen elegance', 'elevated from swimwear to dinner look in warm destination', 'beach club dinner styling above the swimwear day'],
      evening: ['warm tropical or Mediterranean evening look at the beach club', 'villa terrace evening ease above the ocean', 'warm destination evening beach editorial'],
      night: ['warm tropical private night styling in villa or hotel', 'light sleepwear in warm destination night', 'private warm beach destination night look'],
    },
    details: {
      wake: ['warm tropical morning hair on white linen', 'bare sun-warm skin in tropical morning', 'natural destination morning detail'],
      morning_refresh: ['natural fresh skin after tropical outdoor shower', 'wet hair in warm tropical morning bathroom', 'post-swim or pre-swim natural skin detail'],
      getting_dressed: ['the swimwear piece — the editorial main detail', 'minimal gold jewelry with swimwear', 'sun oil or SPF detail in editorial swim preparation'],
      breakfast: ['linen wrap and minimal gold at breakfast terrace', 'warm tropical morning hair in villa breakfast light', 'natural editorial breakfast detail in destination'],
      late_morning: ['editorial swimwear at the water in late-morning light', 'sunglasses and natural destination detail at pool or ocean', 'the swim model detail in warm destination water light'],
      lunch: ['beach club elevated styling detail — linen or cover with swimwear', 'warm destination lunch jewelry or accessory', 'editorial beach club lunch detail'],
      afternoon: ['water on skin — the defining editorial detail of the swim world', 'wet hair in afternoon pool or ocean light', 'sun on skin in the strongest editorial afternoon light'],
      reset: ['sun-touched natural skin post-swim', 'salt water or chlorine in hair — natural post-swim detail', 'warm tropical natural reset detail'],
      golden_hour: ['water drops on skin in amber golden-hour light', 'wet or dry hair in amber pool or ocean light', 'the swim model in the most beautiful water-skin detail of the day'],
      dinner: ['elevated dinner jewelry above the swimwear day', 'beach destination dinner hair — natural and elevated', 'warm tropical dinner styling detail'],
      evening: ['warm beach club or villa evening accessory detail', 'tropical destination evening styling ease', 'natural destination evening beauty'],
      night: ['natural warm destination night detail', 'tropical private night ease detail', 'the swim model at rest — warm and natural'],
    },
    changeMoments: {
      wake: ['in warm tropical morning before the swimwear begins', 'villa morning linen state before the swim day'],
      morning_refresh: ['between linen and swimwear in tropical morning', 'towel wrap in warm tropical bathroom'],
      getting_dressed: ['the editorial swimwear selection — this is the defining moment', 'putting on the piece that will face the ocean'],
      breakfast: ['swimwear with linen or cover for the villa breakfast', 'casual breakfast styling before the editorial swim day'],
      late_morning: ['fully in editorial swimwear at the water', 'the swim model arrived and in the editorial setting'],
      lunch: ['elevated beach club styling over swimwear', 'covered-up or elevated at the beach club lunch'],
      afternoon: ['fully in editorial swimwear at full afternoon power', 'the swim model in water or at water edge — editorial peak'],
      reset: ['transitioning from swimwear to evening look post-swim', 'the post-water natural state before evening'],
      golden_hour: ['in the most editorial swimwear at the golden-hour moment', 'the defining swim model golden-hour editorial look'],
      dinner: ['fully transitioned from swim day to beach dinner evening', 'silk or linen dinner look above the swimwear day'],
      evening: ['warm tropical or Mediterranean evening styling at beach club', 'the swim day winding into warm destination evening'],
      night: ['private warm tropical night styling at rest', 'the swim model at the end of the most beautiful water day'],
    },
  },

  sensoryPools: {
    wake: ['warm tropical air through open villa shutters on skin in morning', 'ocean scent in the warm tropical bedroom morning', 'the warm private ease of a beach villa morning before the swim'],
    morning_refresh: ['warm water in tropical shower or outdoor setting', 'the fresh clean feeling before the swim day editorial begins', 'warm destination morning skin and hair in tropical bathroom'],
    getting_dressed: ['swimwear fabric against warm destination morning skin', 'sun oil applied to skin in warm tropical morning', 'the anticipation of water and light in the editorial morning'],
    breakfast: ['ocean air and tropical fruit at the villa terrace breakfast', 'warm destination morning above the sea or pool', 'the swim model morning — fruit, coffee, and ocean air'],
    late_morning: ['warm water on skin in the first pool or ocean entry', 'sun on skin and water around — the swim world beginning', 'the pool or ocean in warm late-morning destination light'],
    lunch: ['salt air and warm sun at the beach club lunch', 'the warm water world at midday — chilled drinks and sun', 'the most beautiful lunch sensory — ocean and warmth'],
    afternoon: ['warm water on skin in the strongest sun — the core swim model sensory', 'sun and water and warm destination air in the editorial afternoon', 'the body in water and light — the definitive swim world moment'],
    reset: ['warm tropical shower washing off salt or chlorine', 'sun-touched natural skin after the editorial swim afternoon', 'warm private destination reset after the water'],
    golden_hour: ['warm amber water on skin at golden-hour pool or ocean edge', 'the golden light on water-touched skin — the most beautiful sensory moment', 'warm amber air as the destination day turns to gold'],
    dinner: ['warm tropical evening air at the beach club or villa dinner', 'the scent of ocean in warm destination dinner air', 'warm beach destination dinner sensory ease'],
    evening: ['warm destination evening air with ocean in the distance', 'the warm beach club or villa terrace evening ease', 'tropical or Mediterranean warm evening sensory at rest'],
    night: ['warm tropical night air in villa or hotel private rest', 'the warm private beach destination night sensory', 'the swim model at rest — warm, sun-touched, and complete'],
  },

  socialEnergyPools: {
    wake: ['completely private beach destination morning', 'the swim model before the editorial day — warm and private'],
    morning_refresh: ['private tropical bathroom morning self-care', 'alone in warm destination before the swim editorial'],
    getting_dressed: ['private swimwear selection ritual', 'the swim model choosing the editorial look alone in villa morning'],
    breakfast: ['private villa terrace morning ease', 'warm private destination breakfast before the water'],
    late_morning: ['editorial visible at pool or ocean — the swim model in public beautiful light', 'seen at the most beautiful water setting in the world'],
    lunch: ['beach club social ease — visible and beautiful at the table', 'the swim model at the social water world peak'],
    afternoon: ['editorial visible in water or at pool — the most photographable swim model moment', 'sun and water and editorial presence at full afternoon'],
    reset: ['private post-swim villa reset — the editorial world at rest', 'the swim model in private after the water'],
    golden_hour: ['the most cinematically visible swim model moment — golden hour at pool or ocean', 'the golden-hour editorial presence — seen and beautiful at peak'],
    dinner: ['beach club social dinner ease — elevated and warm', 'the swim model at dinner — beautiful and elevated from the swim day'],
    evening: ['warm beach club or villa terrace evening ease', 'the swim world in warm destination evening social ease'],
    night: ['private warm beach destination night', 'the swim model at private rest after the editorial day'],
  },

  atmospherePools: {
    wake: ['warm tropical morning in beach villa — calm before the editorial water day', 'the swim world beginning in warm private destination morning', 'beach villa morning atmosphere — ocean air and white linen'],
    morning_refresh: ['warm tropical bathroom or outdoor shower morning atmosphere', 'fresh destination morning self-care before the editorial swim', 'the swim model preparing for the water in warm morning setting'],
    getting_dressed: ['editorial swimwear selection atmosphere — the right piece for light and water', 'warm villa morning dressing atmosphere in beach destination'],
    breakfast: ['villa terrace breakfast atmosphere above the ocean or pool', 'warm tropical morning ease before the swim day', 'the most beautiful breakfast atmosphere in the water world'],
    late_morning: ['pool or ocean arrival atmosphere — the editorial moment beginning', 'warm destination water energy in late morning', 'the swim model world opening in full late-morning sun'],
    lunch: ['beach club lunch atmosphere — full sun, ocean air, and ease', 'warm destination editorial water world at midday ease', 'the swim model at the most beautiful lunch atmosphere'],
    afternoon: ['full editorial afternoon swim atmosphere — sun, water, and the body at peak', 'the strongest destination sun on pool or ocean — maximum editorial atmosphere', 'warm water and full afternoon tropical light — the swim world at maximum'],
    reset: ['post-swim warm tropical reset atmosphere', 'the swim model after the water — warm and natural', 'warm private destination afternoon after editorial peak'],
    golden_hour: ['golden-hour pool or ocean atmosphere — the most beautiful water world moment', 'amber light on water — the swim model at the most cinematic editorial', 'the golden-hour water world atmosphere at full beauty'],
    dinner: ['beach club or villa dinner atmosphere in warm destination evening', 'the swim world transitioning to warm evening social ease', 'warm tropical evening at the most beautiful beach destination dinner'],
    evening: ['warm beach destination evening atmosphere — ocean air and evening ease', 'beach club or villa terrace warm destination evening', 'the swim model world in warm evening destination'],
    night: ['warm private beach destination night atmosphere', 'the swim model at rest in warm private tropical or Mediterranean night', 'the water world complete and private in warm destination night'],
  },

  propPools: {
    wake: ['white villa linen in warm tropical morning', 'ocean air through open shutters or curtains', 'tropical flower or destination morning detail'],
    morning_refresh: ['warm tropical outdoor shower or bathroom detail', 'sun oil or SPF in warm morning destination', 'towel in warm tropical bathroom setting'],
    getting_dressed: ['editorial swimwear laid out for selection in villa morning', 'sun oil, hat, and minimal accessories', 'the editorial swim piece — the defining prop'],
    breakfast: ['tropical fruit and coffee at villa terrace in warm morning', 'ocean view beyond the breakfast table', 'warm tropical destination morning breakfast detail'],
    late_morning: ['pool or ocean edge with water visible', 'sun hat and sunglasses at the water', 'the editorial swim setting — pool or beach with water'],
    lunch: ['chilled drink and beach club lunch setting', 'ocean or pool visible beyond the lunch table', 'warm destination beach club lunch props'],
    afternoon: ['pool or ocean water surface and the swim model in it', 'sun-touched skin and water around the editorial afternoon', 'the most beautiful prop — warm water in full afternoon sun'],
    reset: ['warm outdoor shower or tropical bathroom post-swim', 'towel and sun oil in warm destination reset', 'natural post-swim prop detail in warm tropical setting'],
    golden_hour: ['amber pool or ocean water edge at golden hour', 'the swim model at the water in amber light', 'golden-hour pool or ocean water surface — the defining prop'],
    dinner: ['beach club dinner props — wine glass, warm setting, ocean in distance', 'villa terrace dinner with ocean view in warm evening', 'elevated beach destination dinner props'],
    evening: ['warm beach club or villa terrace in destination evening', 'ocean air and warm evening destination detail', 'tropical or Mediterranean evening ambience props'],
    night: ['warm villa bedroom tropical night detail', 'private beach destination night warm interior props', 'the swim model at rest — white linen and warm tropical night'],
  },

  bodyLanguagePools: {
    wake: ['warm relaxed tropical morning body language in villa linen', 'slow warm tropical wake in beach destination morning', 'the swim model morning ease before the editorial day'],
    morning_refresh: ['relaxed tropical bathroom or outdoor shower posture', 'natural easy post-swim morning body language', 'warm destination morning self-care ease'],
    getting_dressed: ['deliberate editorial swimwear selection posture', 'the swim model dressing for the water — confident and deliberate', 'warm tropical morning dressing body language'],
    breakfast: ['relaxed villa terrace posture in tropical morning', 'easy warm destination breakfast body language', 'the swim model at breakfast — natural and warm'],
    late_morning: ['confident editorial body language at the pool or ocean', 'the swim model arriving at the water — natural and confident', 'easy sun-confidence at the editorial water setting'],
    lunch: ['relaxed beach club editorial body language at lunch', 'warm destination ease at the beach club table', 'the swim model at lunch — natural editorial ease'],
    afternoon: ['editorial swim body language in pool or ocean — free and alive in water', 'sun-confident full-body editorial in afternoon water light', 'the swim model in water — the most alive and free body language'],
    reset: ['warm natural post-swim body language in destination', 'relaxed beach destination reset posture', 'the swim model after the water — warm and natural'],
    golden_hour: ['golden-hour pool or ocean body language — the most editorial and beautiful', 'amber water and editorial posture at the golden-hour edge', 'the swim model at the pool or ocean golden-hour — the peak moment'],
    dinner: ['elevated beach destination dinner body language', 'the swim model at beach dinner — composed and natural', 'warm destination evening ease at the dinner table'],
    evening: ['warm beach club or villa terrace evening ease', 'the swim model at warm destination evening — natural and at ease', 'tropical warm evening body language after the swim day'],
    night: ['private warm tropical night body language at rest', 'the swim model at rest after the editorial day — warm and complete', 'warm private beach destination night ease'],
  },

  facialExpressionPools: {
    wake: ['warm tropical morning softness in the face', 'natural beach destination morning expression', 'the swim model waking in warm destination ease'],
    morning_refresh: ['fresh natural destination morning expression', 'warm outdoor shower or tropical bathroom morning face', 'the swim model before the editorial water day'],
    getting_dressed: ['editorial anticipation expression — ready for the water and light', 'the swim model choosing her editorial look expression', 'warm destination morning swimwear selection expression'],
    breakfast: ['warm tropical breakfast ease expression', 'natural morning ease expression at the villa terrace', 'the swim model before the water day — warm and easy'],
    late_morning: ['confident editorial expression arriving at pool or ocean', 'the swim model at the water — natural sun confidence', 'warm water world editorial expression in late morning'],
    lunch: ['warm beach club ease expression at lunch', 'editorial beach ease at the most beautiful lunch table', 'the swim model at lunch — warm and naturally confident'],
    afternoon: ['the most alive and sun-confident expression in the editorial afternoon', 'the swim model in water — free, radiant, and editorial at peak', 'full afternoon sun editorial expression — the defining swim world face'],
    reset: ['natural warm post-swim expression — sun-touched and beautiful', 'the swim model after the water — natural and warm', 'warm tropical destination reset expression'],
    golden_hour: ['the golden-hour swim model expression — the most beautiful of the editorial day', 'amber water light on the swim model face — peak editorial expression', 'warm amber golden-hour pool or ocean expression at maximum beauty'],
    dinner: ['warm elevated beach destination dinner expression', 'the swim model at dinner — natural elegance elevated from the swim day', 'warm destination dinner expression'],
    evening: ['warm beach destination evening ease expression', 'the swim model in warm destination evening — natural and complete', 'warm tropical or Mediterranean evening editorial expression'],
    night: ['warm private beach destination night expression', 'the swim model at rest after the editorial day — warm and natural', 'private warm tropical night expression at ease'],
  },

  handDetailPools: {
    wake: ['hand on warm linen in villa tropical morning', 'fingers near tropical flower or destination morning detail', 'warm morning tropical hand placement in villa'],
    morning_refresh: ['hand under warm tropical outdoor shower in morning', 'fingers touching sun oil or SPF in morning prep', 'hand in warm tropical bathroom morning detail'],
    getting_dressed: ['fingers touching editorial swimwear fabric in selection', 'hand applying sun oil to skin in warm editorial preparation', 'the swimwear selection — hands on the most important editorial prop'],
    breakfast: ['hand around tropical coffee or juice cup at villa terrace', 'fingers on tropical fruit at warm destination breakfast', 'resting hand on villa terrace table with ocean beyond'],
    late_morning: ['hand touching pool or ocean water edge in late morning', 'fingers at pool surface or sand in warm editorial beginning', 'hand detail at water arrival in editorial morning setting'],
    lunch: ['hand near chilled drink at beach club lunch', 'fingers on the beach club table with ocean beyond', 'warm destination beach club lunch hand placement'],
    afternoon: ['hand through water surface in editorial afternoon pool', 'fingers in warm ocean or pool water in afternoon editorial', 'water on hand and arm in full afternoon editorial detail'],
    reset: ['hand under warm tropical outdoor shower post-swim', 'fingers through wet hair in warm destination post-swim', 'warm destination post-water hand detail'],
    golden_hour: ['hand at amber pool or ocean edge at golden hour', 'fingers trailing in golden water at the most cinematic moment', 'the golden-hour swim model hand in water — defining editorial prop'],
    dinner: ['hand near wine or drink at beach club dinner', 'fingers at warm destination dinner table', 'warm beach dinner hand placement in evening'],
    evening: ['hand on warm beach club or villa terrace surface in evening', 'fingers trailing in warm destination evening air', 'warm beach destination evening hand placement'],
    night: ['hand on white villa linen in warm tropical private night', 'fingers near warm tropical night detail', 'warm private destination night hand placement'],
  },

  movementEnergyPools: {
    wake: ['slow', 'warm', 'tropical'],
    morning_refresh: ['easy', 'natural', 'fresh'],
    getting_dressed: ['deliberate', 'editorial', 'anticipating'],
    breakfast: ['relaxed', 'warm', 'destination'],
    late_morning: ['confident', 'editorial', 'water-ready'],
    lunch: ['easy', 'warm', 'beach-club'],
    afternoon: ['alive', 'free', 'water'],
    reset: ['natural', 'warm', 'post-swim'],
    golden_hour: ['cinematic', 'amber', 'editorial'],
    dinner: ['elevated', 'warm', 'destination'],
    evening: ['easy', 'warm', 'tropical'],
    night: ['slow', 'private', 'warm'],
  },

  transitionPools: {
    human: {
      wake: ['the swim model waking in warm tropical villa morning', 'beach destination beginning slowly in white linen'],
      morning_refresh: ['the tropical morning bathroom ritual', 'getting ready for the editorial swim day'],
      getting_dressed: ['choosing the editorial swimwear for the day', 'the swim model dressing for the water and light'],
      breakfast: ['villa terrace breakfast before the editorial swim day', 'warm tropical morning above the ocean before the water'],
      late_morning: ['arriving at the pool or ocean for the editorial beginning', 'the editorial swim day starting in late-morning light'],
      lunch: ['beach club lunch in the water world at midday', 'the swim model at lunch ease in warm destination sun'],
      afternoon: ['full editorial afternoon in pool or ocean in strongest sun', 'the swim model in water at editorial peak'],
      reset: ['post-swim villa reset before the destination evening', 'transitioning from the editorial water day to the warm evening'],
      golden_hour: ['the golden hour at pool or ocean — the most cinematic swim moment', 'amber water and editorial presence at maximum beauty'],
      dinner: ['beach club or villa dinner as the swim day elevates to evening', 'the editorial day transitioning to warm destination dinner'],
      evening: ['warm beach destination evening after the swim day', 'villa terrace or beach club in warm tropical evening ease'],
      night: ['the swim model at private rest after the editorial water day', 'warm private beach destination night after the most beautiful day'],
    },
  },

  narrativeIntentPools: {
    wake: ['the editorial swim day beginning in warm private tropical morning ease', 'the swim model before the water — private and warm in villa luxury'],
    morning_refresh: ['preparing for the editorial swim day in warm tropical destination', 'the swim model readying for the most beautiful water and light'],
    getting_dressed: ['the editorial swimwear selection — the piece that will face the ocean and the sun', 'choosing for light and water — the core ritual of the swim model editorial'],
    breakfast: ['warm destination morning ease before the editorial swim world opens', 'the swim model morning — natural luxury before the water day'],
    late_morning: ['the editorial swim beginning — the most beautiful body in the most beautiful water', 'the swim model arriving at the editorial water world'],
    lunch: ['beach club ease in the water world — natural social luxury', 'the swim model at the most beautiful midday setting in the editorial world'],
    afternoon: ['the editorial peak — the swim model in water in the strongest most beautiful afternoon light', 'the body and the water and the sun at maximum editorial beauty'],
    reset: ['the natural post-swim warmth before the destination evening begins', 'the swim model after the water — warm, touched by sun and sea'],
    golden_hour: ['the most cinematic swim model moment — amber water and golden light', 'the editorial peak of the swim world — the golden-hour water scene'],
    dinner: ['the swim day elevating into warm destination evening with elegance', 'the swim model transitioning from editorial water to warm destination dinner'],
    evening: ['the swim world at warm destination evening ease — natural and beautiful', 'the most natural elegant version of the swim model in warm tropical evening'],
    night: ['the swim model complete and private in warm destination night — the editorial day done', 'the most beautiful water day ending in warm private tropical luxury'],
  },

  fallbackRules: {
    pacingProfile: { wake: 'slow', morning_refresh: 'slow', getting_dressed: 'slow', breakfast: 'slow', late_morning: 'medium', lunch: 'slow', afternoon: 'medium', reset: 'slow', golden_hour: 'slow', dinner: 'slow', evening: 'slow', night: 'slow' },
    repetitionBreakers: { avoidBackToBackSameLocation: true, avoidBackToBackSameLightingStyle: true, encourageWardrobeEvolution: true },
    worldDefaults: { allowSceneGroupFallbackToPhasePools: true, allowSubLocationFallbackToWorldPools: true, preferSceneGroupsWhenPresent: true },
  },

  exclusions: {
    premium: ['cold water or cold destinations', 'non-luxury pool or beach settings', 'crowded public beach tourism energy', 'athletic competition settings'],
    hard: ['cold weather', 'indoor office settings', 'non-swimwear dominant styling', 'dark interior settings'],
  },

  routeRules: {
    worldIdentity: ['the swim model world must feel sun-drenched, warm, editorial, and located at the most beautiful water destinations on earth', 'swimwear, water, and sun are the core visual language'],
    humanFlow: ['the day begins in warm tropical villa morning and moves to the pool or ocean editorial peak, through afternoon water, and into warm destination golden-hour, dinner, and evening'],
    styling: ['editorial swimwear throughout — bikinis, one-pieces, and beach cover-ups', 'wardrobe evolves from villa linen morning through editorial swimwear to warm destination evening'],
    atmosphere: ['warm tropical or Mediterranean destination throughout — pool, ocean, beach club, villa terrace', 'sun and water are the defining environmental elements'],
  },
}
