export const STORY_WORLD_TRAVEL_GODDESS = {
  id: 'travel-goddess',
  name: 'Travel Goddess',
  description:
    'First-class lounges, jet bridges, rooftop hotels, private transfers. The creator who moves through the world with the ease of someone who has always been here. Day-to-night travel arc — departure through arrival through penthouse.',

  geography: { country: 'global transit', region: 'first class world' },

  identity: {
    archetype: 'travel goddess',
    vibe: ['first class as a natural state', 'jet bridge golden hour', 'rooftop hotel at arrival city', 'private transfer through new streets', 'the luxury traveller at total ease'],
    tone: ['effortless', 'elevated', 'global', 'chic', 'aspirational', 'warm', 'cinematic'],
    persona: ['moves through airports like she owns them', 'the world is her itinerary — she has no tourist energy', 'every transit moment is content', 'arrives somewhere new and immediately makes it hers'],
  },

  phaseOrder: ['wake', 'morning_refresh', 'getting_dressed', 'breakfast', 'late_morning', 'lunch', 'afternoon', 'reset', 'golden_hour', 'dinner', 'evening', 'night'],

  phases: {
    wake:            { label: 'Early Departure',   timeWindows: ['pre-dawn departure morning', 'early airport morning light'],             pacing: 'slow',   subLocations: ['hotel-suite-morning', 'private-terminal'] },
    morning_refresh: { label: 'Transit Ritual',    timeWindows: ['airport morning', 'first class lounge morning'],                        pacing: 'slow',   subLocations: ['first-class-lounge', 'private-terminal'] },
    getting_dressed: { label: 'Lounge Prep',       timeWindows: ['first class lounge late morning', 'pre-boarding preparation'],          pacing: 'slow',   subLocations: ['first-class-lounge', 'hotel-suite-morning'] },
    breakfast:       { label: 'Lounge Breakfast',  timeWindows: ['first class lounge breakfast', 'private terminal morning'],             pacing: 'slow',   subLocations: ['first-class-lounge', 'private-terminal'] },
    late_morning:    { label: 'Departure Gate',    timeWindows: ['late morning airport light', 'glass terminal morning'],                 pacing: 'medium', subLocations: ['jet-bridge', 'private-terminal'] },
    lunch:           { label: 'In-Flight Luxury',  timeWindows: ['in-flight noon', 'above-clouds midday light'],                         pacing: 'slow',   subLocations: ['inflight-suite', 'inflight-suite'] },
    afternoon:       { label: 'Descent View',      timeWindows: ['in-flight afternoon above destination', 'approach descent light'],     pacing: 'slow',   subLocations: ['inflight-suite', 'jet-bridge'] },
    reset:           { label: 'Arrival Transfer',  timeWindows: ['new city afternoon', 'private transfer through destination streets'],   pacing: 'medium', subLocations: ['private-transfer', 'hotel-lobby'] },
    golden_hour:     { label: 'Hotel Arrival',     timeWindows: ['golden-hour hotel check-in', 'afternoon rooftop arrival'],              pacing: 'slow',   subLocations: ['hotel-rooftop', 'hotel-suite-arrival'] },
    dinner:          { label: 'Rooftop Dinner',    timeWindows: ['rooftop golden evening', 'hotel rooftop dinner hour'],                  pacing: 'slow',   subLocations: ['hotel-rooftop', 'hotel-suite-arrival'] },
    evening:         { label: 'Suite Evening',     timeWindows: ['hotel suite evening', 'city view at night'],                           pacing: 'slow',   subLocations: ['hotel-suite-arrival', 'hotel-rooftop'] },
    night:           { label: 'Private Night',     timeWindows: ['penthouse night', 'city lights from suite'],                           pacing: 'slow',   subLocations: ['hotel-suite-arrival', 'hotel-rooftop'] },
  },

  locations: [
    'first class airport lounge with floor-to-ceiling windows', 'private jet terminal departure area',
    'jet bridge with warm directional light', 'first class cabin flatbed suite above clouds',
    'private transfer car through destination city streets', 'hotel lobby grand entrance',
    'rooftop hotel pool and terrace at golden hour', 'penthouse suite with city skyline view',
  ],

  subLocations: {
    'hotel-suite-morning': {
      id: 'hotel-suite-morning', name: 'Hotel Suite Morning', mapAnchor: 'luxury hotel suite at departure',
      category: 'luxury-interior',
      bestPhases: ['wake', 'getting_dressed'],
      overlays: ['crisp white hotel linen', 'morning light through floor-to-ceiling windows', 'city view beyond glass', 'room service tray detail'],
      locations: ['penthouse suite bed in morning hotel light', 'hotel suite window with city morning beyond', 'hotel bathroom vanity in luxury morning light'],
    },
    'first-class-lounge': {
      id: 'first-class-lounge', name: 'First Class Lounge', mapAnchor: 'airport first class lounge',
      category: 'transit-luxury',
      bestPhases: ['morning_refresh', 'getting_dressed', 'breakfast'],
      overlays: ['designer lounge interior', 'floor-to-ceiling tarmac view windows', 'marble and leather lounge surfaces', 'champagne and curated food presentation'],
      locations: ['first class lounge window seat with tarmac view', 'lounge dining area in luxury airport interior', 'lounge bar with premium service setting'],
    },
    'private-terminal': {
      id: 'private-terminal', name: 'Private Terminal', mapAnchor: 'private aviation terminal',
      category: 'exclusive-transit',
      bestPhases: ['wake', 'breakfast', 'late_morning'],
      overlays: ['private terminal interior', 'direct tarmac access', 'minimal other passengers', 'luxury transit ease'],
      locations: ['private aviation terminal interior', 'private departure gate with direct tarmac view', 'VIP terminal check-in area'],
    },
    'jet-bridge': {
      id: 'jet-bridge', name: 'Jet Bridge', mapAnchor: 'airport jet bridge to aircraft',
      category: 'threshold-moment',
      bestPhases: ['late_morning', 'afternoon'],
      overlays: ['jet bridge tunnel light', 'warm directional airport light at windows', 'tarmac visible beyond', 'that specific jet bridge atmosphere'],
      locations: ['jet bridge approaching aircraft with tarmac light beyond', 'jet bridge window with aircraft wing visible', 'boarding corridor in warm airport light'],
    },
    'inflight-suite': {
      id: 'inflight-suite', name: 'In-Flight Suite', mapAnchor: 'first class cabin flatbed suite',
      category: 'in-flight-luxury',
      bestPhases: ['lunch', 'afternoon'],
      overlays: ['first class flatbed suite', 'oval window with cloud or horizon light', 'premium in-flight service', 'above-cloud brightness'],
      locations: ['first class flatbed suite with oval window', 'in-flight premium suite with cloud view outside', 'first class cabin with champagne and white linen'],
    },
    'private-transfer': {
      id: 'private-transfer', name: 'Private Transfer', mapAnchor: 'private car transfer',
      category: 'city-arrival',
      bestPhases: ['reset'],
      overlays: ['luxury vehicle interior', 'new city streets visible through window', 'warm transfer light', 'arrival energy through glass'],
      locations: ['private car with city streets through window', 'transfer vehicle with destination city outside', 'luxury car interior with city view behind'],
    },
    'hotel-lobby': {
      id: 'hotel-lobby', name: 'Hotel Lobby', mapAnchor: 'luxury hotel grand lobby',
      category: 'arrival-statement',
      bestPhases: ['reset'],
      overlays: ['grand hotel lobby', 'marble and architectural luxury', 'warm lobby ambient light', 'arrival energy'],
      locations: ['grand hotel lobby at arrival', 'luxury hotel check-in with statement architecture', 'hotel lobby with high ceilings and warm ambient light'],
    },
    'hotel-rooftop': {
      id: 'hotel-rooftop', name: 'Hotel Rooftop', mapAnchor: 'rooftop pool and terrace',
      category: 'elevated-destination',
      bestPhases: ['golden_hour', 'dinner', 'evening', 'night'],
      overlays: ['rooftop pool reflecting golden hour sky', 'city skyline panorama', 'outdoor dining and lounge furniture', 'rooftop terrace bar setting'],
      locations: ['rooftop pool with city skyline behind', 'rooftop terrace lounge at golden hour', 'hotel rooftop bar with panoramic city view'],
    },
    'hotel-suite-arrival': {
      id: 'hotel-suite-arrival', name: 'Arrival Suite', mapAnchor: 'penthouse hotel suite',
      category: 'destination-luxury',
      bestPhases: ['golden_hour', 'dinner', 'evening', 'night'],
      overlays: ['floor-to-ceiling city view windows', 'luxury suite interior', 'city lights at distance', 'penthouse elevation'],
      locations: ['penthouse suite with city skyline through floor-to-ceiling windows', 'luxury hotel suite evening with city view', 'suite terrace or window at city golden hour'],
    },
  },

  sceneVariants: {
    wake:            ['in white hotel linen in the last luxury morning before departure, city just waking outside', 'pre-dawn hotel suite — bags almost packed, one last hotel morning moment'],
    morning_refresh: ['in the first class lounge at morning — champagne, floor-to-ceiling windows, tarmac below', 'morning ritual at the private terminal before the flight — curated and unhurried'],
    getting_dressed: ['getting ready in the first class lounge before boarding — the most elevated dressing room', 'hotel suite morning preparation — travel outfit selected in luxury light'],
    breakfast:       ['first class lounge breakfast with tarmac view — the world about to open up', 'private terminal morning with a cup and the aircraft visible through the window'],
    late_morning:    ['walking the jet bridge in late morning airport light — that specific threshold moment', 'private terminal departure area in late morning — fully prepared and effortlessly ready'],
    lunch:           ['first class flatbed suite above the clouds at noon — white linen, champagne, cloud view', 'in-flight luxury at lunch altitude — the world below, everything elevated'],
    afternoon:       ['descent view through first class oval window in afternoon — new city coming into view', 'jet bridge at arrival airport in afternoon light — one foot in each world'],
    reset:           ['private transfer through the new city streets — looking out the window at the destination', 'hotel lobby arrival — the moment the new city officially begins'],
    golden_hour:     ['rooftop hotel terrace at golden hour — city panorama, champagne, arrival complete', 'penthouse suite at golden hour — luggage barely touched, window too good to leave'],
    dinner:          ['rooftop dinner above the city at golden-to-evening — the definitive travel dinner', 'suite terrace at dinner with city skyline going from amber to deep blue'],
    evening:         ['hotel suite evening — city lights below, champagne, the day fully unpacked', 'rooftop terrace at evening with the full city lit below'],
    night:           ['penthouse suite at night with full city lights — the most beautiful travel night moment', 'rooftop at night with the city fully lit below — the destination completely arrived'],
  },

  actionPools: {
    wake:            ['lying in white hotel linen in morning hotel light with city barely visible through the window', 'stretching in hotel bed before the departure day begins in early morning light', 'sitting at hotel suite window in a robe with the city just waking below', 'reaching for the phone on a hotel bedside table in white linen pre-departure morning', 'lying with the white hotel duvet pulled high while the city light begins outside the window', 'sitting at the hotel suite window edge looking at the city in pre-departure quiet'],
    morning_refresh: ['walking through the first class lounge to the window seat with champagne in hand', 'seated at first class lounge window overlooking the tarmac in the morning light', 'applying touch-up at the lounge bathroom mirror in elegant morning lounge light', 'selecting something from the lounge breakfast spread with complete ease', 'sitting in the lounge designer chair with both hands around a coffee cup, tarmac beyond', 'standing at the lounge floor-to-ceiling window looking at the aircraft being prepared below'],
    getting_dressed: ['choosing the travel outfit in the first class lounge or hotel suite mirror', 'adjusting a tailored travel look in the lounge mirror before boarding', 'fastening a watch or piece of jewellery in the lounge before the flight', 'pulling a silk travel scarf around the shoulders in the lounge before departure', 'smoothing a silk blazer lapel in the lounge mirror — fully travel-ready', 'placing sunglasses on in the lounge before heading toward the gate'],
    breakfast:       ['eating at the lounge dining area with tarmac visible through the window behind', 'croissant and champagne at the lounge with the morning airport world below', 'both hands around a lounge cup at the floor-to-ceiling window with aircraft below', 'sitting at the private terminal table in morning with the whole tarmac as the view', 'standing at the lounge food display selecting something with unhurried morning ease', 'lounge morning beverage moment — champagne flute, tarmac behind, total composure'],
    late_morning:    ['walking the jet bridge toward the aircraft in late morning airport light', 'standing at the jet bridge window looking at the tarmac one last time before boarding', 'moving through the private terminal in late morning with carry-on and complete ease', 'at the departure gate looking through the glass at the aircraft with morning sun behind it', 'pulling the passport from a designer bag at the gate with total composure', 'pausing at the jet bridge window mid-way — the last moment between the city and the air'],
    lunch:           ['lying in the first class flatbed suite above the clouds in white linen at noon', 'sipping champagne at the first class window with cloud formations below', 'accepting the in-flight lunch service with white-gloved ease in the cabin', 'lying back in the first class suite looking at the oval window and the cloud horizon', 'sitting up in the flatbed suite with the meal tray and cloud view beyond', 'looking out the first class oval window at the infinite cloud horizon at noon altitude'],
    afternoon:       ['at the first class oval window as the destination coast comes into view below', 'leaning forward slightly in the seat to see the new city appearing in the descent view', 'adjusting the window shade in the first class suite to see the descending landscape', 'sitting up in the first class suite as the altitude changes and the destination comes into focus', 'looking out the jet bridge window at the arrival airport as the afternoon sun comes in', 'walking off the jet bridge into the arrival terminal in afternoon airport light — arrived'],
    reset:           ['looking out the private transfer window as the new city streets pass', 'seated in the back of the transfer car with the city passing in the window behind', 'arriving at the hotel lobby — pulling sunglasses off and looking up at the architecture', 'checking in at the hotel front desk with the lobby grandeur surrounding', 'riding up in the hotel elevator with the key card and carry-on beside', 'opening the suite door for the first time and seeing the city view appear through the window'],
    golden_hour:     ['standing at the rooftop pool edge with city panorama in golden-hour amber behind', 'rooftop lounge with champagne as the city glows in golden-hour below', 'at the suite floor-to-ceiling window at golden hour — city amber, complete arrival feeling', 'rooftop terrace seated with the city skyline in full golden hour behind', 'champagne glass at the rooftop terrace edge as golden light crosses the city below', 'standing at the rooftop bar at golden hour with the city panorama spreading behind'],
    dinner:          ['rooftop dinner at a table with city skyline as the backdrop going amber to blue', 'seated at rooftop dinner with champagne and the city transitioning to evening below', 'rooftop terrace with dinner and the city lit amber behind in the most travel-perfect scene', 'suite terrace at dinner with the city skyline going from gold to deep blue beyond', 'sitting at the rooftop with a glass as the dinner hour turns the city lights on below', 'the rooftop table set for dinner with the city panorama at the most cinematic light'],
    evening:         ['suite balcony or window at evening with full city lights beginning below', 'lying on the suite bed or chaise looking at the city through the floor-to-ceiling window', 'rooftop at evening — city fully lit, the travel day complete and perfect', 'suite evening — champagne and city view and the complete arrival feeling', 'sitting on the suite bed looking at the city lights through the window in evening', 'standing at the suite window in the evening with the full city illuminated below'],
    night:           ['suite at night with full city lights below through floor-to-ceiling glass', 'rooftop terrace at night — the city completely lit, destination fully arrived', 'penthouse window in the night with hands on the glass looking at the city below', 'suite bed in night hotel luxury with the city glowing through the window', 'rooftop pool terrace at night — city lights in the water, the destination complete', 'standing at the penthouse window at full night looking at the city spread below'],
  },

  environmentPools: {
    wake:            ['luxury hotel suite in morning with floor-to-ceiling city window and white linen', 'penthouse morning interior with pre-departure light and city just waking beyond the glass', 'hotel suite in pre-dawn departure light — bags near the door, city still quiet outside', 'white linen hotel bed in morning with the city skyline visible through large windows', 'hotel suite morning with golden light on marble surfaces and city view beyond', 'luxury hotel bedroom in early morning — the last beautiful morning before travel begins'],
    morning_refresh: ['first class lounge interior with tarmac view through floor-to-ceiling windows', 'airport lounge morning with champagne, marble surfaces, and aircraft being prepared below', 'first class lounge at morning with leather chairs, fresh flowers, and full tarmac panorama', 'luxury airport lounge in morning light — the world\'s best waiting room', 'private terminal interior in morning — clean, minimal, exclusive', 'first class lounge bar in morning with lounge architecture and airport world outside'],
    getting_dressed: ['first class lounge mirror area in morning — elegant and private', 'hotel suite dressing area in pre-travel morning light', 'lounge bathroom in luxury airport interior — marble, good light, complete calm', 'hotel suite wardrobe area in morning with city light through the window', 'first class lounge preparation corner in warm morning lounge light', 'hotel suite dressing in golden morning light with the city beyond the window'],
    breakfast:       ['first class lounge dining area with tarmac panorama through the windows', 'lounge breakfast table with champagne and tarmac view below', 'private terminal morning with the full apron visible through large clean windows', 'airport lounge marble breakfast bar in morning with aircraft preparation beyond', 'first class lounge seated breakfast — curated food, elegant setting, aircraft visible', 'lounge floor-to-ceiling window at morning breakfast with the whole airport world below'],
    late_morning:    ['jet bridge at late morning — warm directional light, tarmac visible through porthole windows', 'private terminal departure zone in late morning with aircraft in full sun beyond', 'jet bridge corridor with directional window light and aircraft outside', 'private terminal in late morning — minimal, elegant, just about to board', 'airport departure gate glass with full aircraft in late morning sun behind', 'jet bridge window light — the transitional threshold moment in late morning airport light'],
    lunch:           ['first class flatbed suite at noon altitude — white linen, champagne, oval window', 'in-flight first class suite above clouds in the absolute brightness of noon altitude', 'first class cabin at noon with cloud cover visible through the oval window', 'first class suite interior with white service, champagne, and cloud view beyond', 'above-cloud first class interior at noon — the brightest whitest most elevated lunch', 'first class flatbed at noon — white linen, cloud horizon, the world completely below'],
    afternoon:       ['first class window in descent afternoon — the destination coastline coming into view below', 'first class suite in afternoon descent light with the arrival city visible far below', 'jet bridge at arrival airport in afternoon sun with tarmac and aircraft outside', 'arrival first class cabin in afternoon with the new country visible through the oval window', 'arrival airport jet bridge in afternoon light — between flight and the new city', 'in-flight afternoon with the destination visible through the window as descent begins'],
    reset:           ['private transfer car interior with new city streets passing through the window', 'luxury vehicle interior looking out at the destination city streets in afternoon', 'hotel lobby at arrival — grand architecture, marble, warm lobby ambient light', 'hotel check-in lobby in afternoon with grand interior and warm architectural light', 'hotel corridor approaching the suite door in warm corridor light', 'private transfer window framing the new city — first impressions through glass'],
    golden_hour:     ['rooftop hotel terrace in golden-hour amber with city skyline panorama', 'hotel rooftop pool edge at golden hour — city reflected in water, amber on every surface', 'penthouse suite floor-to-ceiling window at golden hour with city in full amber below', 'rooftop terrace bar at golden hour — city gold behind, champagne in hand, arrived', 'hotel rooftop at the best golden moment — city, pool, amber sky, complete arrival', 'suite terrace or window in full golden-hour with city panorama at its most cinematic'],
    dinner:          ['rooftop terrace dinner table with city transitioning from amber to dark blue behind', 'rooftop restaurant at dinner with panoramic city skyline as the backdrop', 'hotel rooftop in dinner hour with city fully lit in the deep blue evening behind', 'suite terrace dinner setup with city going to evening lights below', 'rooftop lounge with dinner service and city in the full transition from golden to night', 'hotel rooftop bar at dinner hour with the city skyline in magical blue evening behind'],
    evening:         ['penthouse suite with city lights beginning through floor-to-ceiling windows at evening', 'hotel rooftop at evening with city fully lit below and sky deep blue above', 'suite balcony or window at evening — city glowing, the travel day completely arrived', 'rooftop terrace at evening with the full panoramic city light beginning below', 'hotel suite at evening — champagne on the room service tray, city lights outside', 'penthouse floor-to-ceiling window at evening with the city waking to night below'],
    night:           ['penthouse suite at full night — city spread below in complete illumination through the glass', 'rooftop terrace at night with city entirely lit below in the deepest most complete travel moment', 'hotel rooftop pool at night — city reflected in still pool water below the night sky', 'penthouse window at night — hands on glass, full city spread in lights below', 'suite night interior with the city as the living wallpaper through the full window', 'rooftop night with the destination city completely lit — the perfect end to the travel day'],
  },

  moodPools: {
    wake:            ['pre-departure luxury morning — the beautiful in-between before the world opens', 'hotel morning ease before the travel day takes over', 'the last quiet hotel morning before the itinerary begins', 'pre-travel hotel luxury — everything packed, this moment still private', 'departure morning anticipation — the city outside, the trip ahead', 'the hotel morning that belongs entirely to the traveller before it belongs to transit'],
    morning_refresh: ['first class lounge morning ease — the world\'s most elevated waiting', 'lounge morning composure — champagne at 8am is perfectly normal here', 'the first class lounge as the most refined transit ritual available', 'airport morning in the only space that feels completely separate from the airport', 'lounge ease in the morning — curated, warm, completely effortless', 'the morning lounge ritual as the proper preparation for the travel day'],
    getting_dressed: ['lounge preparation with complete travel-goddess composure', 'the lounge as the most elevated dressing room in the world', 'travel look preparation in first class lounge light — effortless and precise', 'getting dressed for the destination in the lounge before boarding', 'the deliberate travel outfit selection in lounge light — every detail right', 'travel goddess preparation — chic, considered, completely prepared'],
    breakfast:       ['first class lounge breakfast ease — the most refined way to start a travel day', 'tarmac view with champagne at breakfast — the travel goddess morning signature', 'lounge breakfast without hurry — the world can wait, the champagne is cold', 'morning lounge dining as the best part of the departure ritual', 'pre-flight breakfast in the most beautiful airport room in the world', 'lounge morning ease before the flight — calm, elegant, fully in control'],
    late_morning:    ['jet bridge threshold energy — about to leave one world and enter another', 'the anticipation of the jet bridge — between airport and aircraft', 'late morning departure energy — every detail ready, the flight about to begin', 'the private terminal departure ease — no crowd, no rush, complete grace', 'jet bridge moment — the most cinematic transition point in travel', 'departure energy building in the late morning — the world about to become very small below'],
    lunch:           ['first class in-flight ease at noon altitude — the most elevated lunch possible', 'above-cloud lunch energy — the world completely below and completely irrelevant', 'in-flight first class noon luxury — white linen, champagne, everything right', 'noon altitude first class ease — the travel goddess in her most elevated element', 'above the clouds at noon with nothing to do except exist beautifully', 'first class flatbed noon energy — the most private and most elevated lunch hour'],
    afternoon:       ['descent arrival anticipation — the new city coming into view below', 'in-flight afternoon with the destination just becoming visible through the oval window', 'arrival afternoon energy building — the new city appearing in the window', 'the descent as the most cinematic travel moment — anticipation at its peak', 'afternoon arrival energy — the flight ending, the destination beginning', 'first look at the destination from the air — the most beautiful travel afternoon moment'],
    reset:           ['private transfer city arrival ease — looking out at the new destination', 'the transfer as the first real contact with the destination city', 'hotel lobby arrival energy — the travel day transitioning into the stay', 'arriving at the hotel as the completion of the travel day\'s first chapter', 'new city first impression through the transfer window — everything is possible', 'hotel check-in composure — the travel goddess arriving exactly as expected'],
    golden_hour:     ['rooftop arrival golden hour — the destination is perfect, the champagne is cold', 'hotel golden-hour rooftop ease — the most beautiful arrival moment', 'penthouse golden hour with city below — the travel day completely validated', 'rooftop champagne at golden hour with city panorama — the definitive travel moment', 'arrival golden hour ease — the suite is perfect, the view is better', 'the golden-hour arrival rooftop as the travel day\'s most cinematic payoff'],
    dinner:          ['rooftop dinner above the destination city — the travel goddess at her most complete', 'dinner with a city skyline as the backdrop — nowhere else has this energy', 'rooftop city dinner ease — the destination city performing for the table', 'the most aspirational dinner setting — rooftop, city, golden-to-blue transition', 'dinner at altitude above the city — the travel day\'s most beautiful conclusion', 'rooftop dinner ease — the city below is the table decoration'],
    evening:         ['suite evening above the city — the travel day complete, the destination fully arrived', 'hotel evening with city lights below — the most beautiful unpacking atmosphere', 'rooftop evening ease — the city transitioning to night below the terrace', 'suite floor-to-ceiling city window at evening — the travel goddess completely arrived', 'hotel evening luxury — champagne, city, and the beautiful completion of the journey', 'penthouse evening with the city fully lit below — the destination completely delivered'],
    night:           ['penthouse suite night — the city below as the most beautiful view in the world', 'rooftop terrace at full night with the city completely illuminated below', 'suite night with full city lights — the travel destination at its most cinematic', 'the city at night seen from the penthouse as the ultimate travel reward', 'full night rooftop — the city light, the pool reflection, the travel day perfect', 'hotel suite night luxury — city lights, champagne, the journey fully complete'],
  },

  cameraPools: {
    wake:            ['85mm hotel suite medium close, city window glowing behind in morning light', '135mm close on face in white hotel linen, window city blur behind', '50mm wide hotel suite morning, bed and window and city all in frame', '85mm low from bed level, city window elevated in background behind subject', '135mm extreme close on hands in white linen, city window warmly blurred beyond', '50mm hotel window seat close, city morning just visible through glass behind subject'],
    morning_refresh: ['85mm first class lounge window seat, tarmac compressing behind in lounge interior', '50mm wide lounge scene, window panorama and lounge design all in frame with subject', '135mm close on face at lounge window, aircraft preparation softly dissolved behind', '85mm lounge bar angle, tarmac view through window behind, lounge architecture around', '35mm wide first class lounge, full interior with subject at window seat or bar', '135mm champagne flute close in lounge light, subject soft-focused behind'],
    getting_dressed: ['85mm lounge or hotel suite mirror shot, reflection and depth in elegant light', '135mm close on detail — travel outfit, jewellery, accessory in good light', '50mm lounge preparation mid shot, lounge architecture softly behind', '85mm over-shoulder into lounge mirror, tarmac or city window visible in background', '135mm extreme close on jewellery or accessory being placed on in lounge light', '85mm wide lounge dressing scene, full lounge interior with tarmac beyond'],
    breakfast:       ['85mm lounge window breakfast, tarmac view dissolving in lounge bokeh behind', '50mm wide lounge morning, food service and window panorama all in frame', '135mm close on champagne flute or cup in lounge light with tarmac receding behind', '85mm lounge table angle, city/tarmac visible through window at a dramatic distance', '35mm ultra-wide lounge breakfast scene with floor-to-ceiling tarmac window behind', '135mm tight on hands at lounge breakfast table, tarmac warm-blurred beyond'],
    late_morning:    ['50mm jet bridge corridor shot, porthole windows behind with tarmac visible', '85mm jet bridge window close, tarmac and aircraft visible through porthole behind subject', '135mm close on face in jet bridge light, aircraft wing visible through window behind', '35mm wide jet bridge tunnel shot, light at aircraft end, subject mid-bridge', '85mm low jet bridge angle, subject elevated, tarmac and plane behind in light', '24mm dramatic jet bridge perspective, tarmac world beyond, subject in frame'],
    lunch:           ['85mm first class window seat close, oval window with clouds behind', '135mm tight on face in first class suite with cloud horizon visible through oval', '50mm first class suite mid, white linen, champagne, clouds in oval window behind', '85mm low from suite floor, subject in first class seat with oval cloud window above', '135mm extreme close on champagne flute, first class suite and oval window behind', '50mm wide first class cabin scene with oval windows and cloud view throughout'],
    afternoon:       ['85mm first class descent window close, destination coast visible below and behind', '135mm tight on face at oval window with new city visible far below', '50mm first class window seat as coastline appears below, subject and view together', '85mm jet bridge arrival shot, new tarmac world beyond the porthole windows', '35mm wide first class cabin in descent, oval windows with destination below', '135mm close on face in arrival jet bridge light — the moment of landing'],
    reset:           ['85mm transfer car interior medium, city streets passing through window behind', '135mm close in transfer car, city destination visible through rear window', '50mm wide transfer car scene, luxury interior and city beyond the glass', '85mm hotel lobby dramatic angle, grand architecture receding behind subject', '50mm hotel lobby arrival, grand interior and check-in in full frame', '135mm close on face at hotel lobby arrival, architecture dissolving behind'],
    golden_hour:     ['135mm rooftop backlit close, city amber behind, champagne in hand', '24mm ultra-wide rooftop panorama, subject and full city golden panorama in frame', '85mm low rooftop angle, subject elevated, city skyline amber behind', '135mm tight backlit golden-hour rooftop close — amber rim, city dissolved', '50mm wide rooftop golden scene, pool reflection, city gold, subject in frame', '85mm from pool edge at rooftop, city golden behind, champagne catching the light'],
    dinner:          ['85mm rooftop dinner table medium, city transitioning gold-to-blue behind', '135mm intimate rooftop dinner close, city as warm background bokeh', '50mm wide rooftop dinner scene, table, city, sky at the transition hour', '85mm from below rooftop terrace, subject elevated, city panorama behind', '24mm dramatic rooftop wide, city in full transition behind and around', '135mm close on champagne flute at dinner, city lights beginning behind'],
    evening:         ['85mm suite window medium, city lights beginning through floor-to-ceiling glass', '135mm close at suite window, city lights in warm background bokeh behind', '50mm suite evening wide, full floor-to-ceiling window with city beyond', '85mm low suite angle, subject elevated, city window dominant behind', '35mm ultra-wide suite evening, full window with entire city spread behind', '135mm tight face at suite window, city lights warm-dissolved behind'],
    night:           ['85mm rooftop night medium, city completely lit behind subject', '135mm close at rooftop night, city lights as warm bokeh behind', '24mm ultra-wide penthouse window night shot, city spread in full illumination behind', '50mm wide suite night, floor-to-ceiling window with city lights dominant', '85mm from pool edge at night, city lights reflected in pool behind subject', '135mm extreme close at window, city light detail and subject together at night'],
  },

  lightingPools: {
    wake:            ['warm 5000K hotel suite morning light through large windows, city softly lit beyond', 'hotel suite at 4800K morning — even warm fill from city-facing windows', 'early 5200K hotel morning — clean window light on white linen and marble', 'pre-departure hotel morning at 4800K — golden window light just beginning', 'hotel suite at 5000K morning — large windows providing even warm morning fill', 'pre-dawn departure hotel at 4200K — warm interior light against dark city still waking'],
    morning_refresh: ['first class lounge at 3800K interior ambient with 5200K daylight tarmac window', 'lounge mixed lighting — 3500K warm interior against 5400K tarmac daylight beyond', 'airport lounge at 3800K interior warm with morning window fill from outside', 'lounge morning at 4200K mixed — warm indoor ambient plus clean morning exterior', 'first class lounge interior 3600K warm against 5200K tarmac morning beyond', 'lounge design lighting at 3800K — precise, warm, architectural, with morning tarmac behind'],
    getting_dressed: ['lounge bathroom or hotel suite at 3800K warm vanity with window fill', '4000K lounge interior morning prep light — warm and even and elevating', 'hotel suite dressing at 4800K morning window — the cleanest honest flattering light', 'lounge mirror light at 3600K — warm and well-designed for preparation', '4000K hotel suite morning with 5000K window fill — best of both', 'lounge dressing corner at 3800K warm ambient with clean morning at the window'],
    breakfast:       ['lounge 3600K warm interior against 5400K morning tarmac window light', 'lounge breakfast lighting — 3800K warm interior, morning tarmac daylight through glass', 'champagne and croissant in 3600K lounge interior warm light', 'first class lounge morning at 4200K warm — the most beautiful airport morning light', 'lounge morning at 3800K — warm architectural lighting with daylight compression through glass', 'private terminal morning at 5000K daylight from large windows, warm interior fill'],
    late_morning:    ['jet bridge at 5200K directional from porthole windows — warm late morning diagonal', 'jet bridge warm side light at 5000K from external porthole windows', '5200K late morning airport light through jet bridge windows, tarmac warmth outside', 'jet bridge at 5000K — honest clean late morning light entering from outside', 'airport terminal at 5400K clean daylight from floor-to-ceiling glass', 'late morning airport departure at 5200K — the cleanest most architectural travel light'],
    lunch:           ['first class cabin at noon altitude — 6500K+ ultra-bright clear sky through oval window', 'above-cloud first class at 6200K — the brightest natural light available anywhere', 'noon altitude first class at 6000K — pure white light from above the clouds', 'first class oval window at noon with 6500K sky brightness flooding the cabin', 'in-flight at altitude at 6000K — cloud brightness as the defining light character', 'first class noon altitude — 6200K pure sky light, white linen, complete brightness'],
    afternoon:       ['descent afternoon through first class window at 4800K — destination light arriving', 'first class afternoon at 5000K as the destination coast appears in warm afternoon light', 'arrival jet bridge at 5200K afternoon — new country light entering the bridge', '4800K arrival airport afternoon light through jet bridge porthole windows', 'first class window seat at 4600K afternoon descent — warm directional from destination sun', 'arrival afternoon at 5000K — clean new destination light through the aircraft window'],
    reset:           ['private transfer car at 4800K afternoon with destination city visible through tinted glass', 'hotel lobby at 3800K warm architectural ambient — the most beautiful arrival lighting', 'private car interior at 3600K warm with city visible through glass at 5000K outside', 'hotel lobby arrival at 4000K — warm grand architectural light filling the space', 'transfer car at 4200K warm interior with city afternoon 5000K beyond the windows', 'hotel lobby 3800K warm ambient — premium lighting for the arrival moment'],
    golden_hour:     ['rooftop at 2600K-2800K golden hour — amber on every city surface and the pool below', 'golden-hour hotel rooftop at 2700K — amber city light and warm sky above', 'penthouse window at 2800K golden — warm horizontal amber light filling the entire suite', 'rooftop golden hour at 2600K — the city in the deepest warmest light of the day', 'hotel rooftop at 2700K amber — champagne glowing, pool amber, city gold', 'golden-hour suite window at 2800K — amber light through floor-to-ceiling glass filling the room'],
    dinner:          ['rooftop at dinner — 2200K warm LED terrace lights against 3200K deep blue ambient sky', 'rooftop dinner at 3000K warm — transition from golden to deep blue overhead', 'rooftop terrace dinner at 2800K warm against the darkening city below beginning to light', 'hotel rooftop at 2400K dinner ambient — warm terrace light, city going to full illumination', 'suite terrace dinner at 2800K warm with city ambient 2200K coming on below', 'rooftop dinner at 3200K — warm architectural light against deep blue evening sky'],
    evening:         ['suite floor-to-ceiling window at evening — city lights 2200K warm against 2800K suite interior', 'hotel suite at 2400K warm evening ambient with city lights visible through glass', 'penthouse evening at 2600K warm interior, city lights 2000K warm behind the window', 'rooftop at 2200K warm terrace ambient against city lights beginning below', 'suite evening at 2800K — warm architectural interior with city warm glow beyond the glass', 'hotel evening at 2400K interior light — warm and golden with city visible'],
    night:           ['penthouse at full night — 2200K warm suite interior against full city illumination through glass', 'rooftop at night — 2000K warm terrace lights against full city light below', 'hotel suite night at 2400K warm with city at full illumination beyond the window', 'full night hotel rooftop at 2200K against city 2000K below — layered warm night lighting', 'penthouse night at 2600K interior with city lights as the dominant visual element through glass', 'suite night at 2200K — warm interior against city-as-light-art through floor-to-ceiling glass'],
  },

  stylingPools: {
    wardrobe: {
      wake:            ['white hotel bathrobe in morning hotel suite light — classic departure morning', 'silk pyjamas in hotel white linen — luxury travel morning before dressing', 'white hotel cotton robe, loosely tied at the suite window in morning', 'cream or white silk sleep set in hotel suite pre-departure morning', 'white hotel bathrobe with nothing beneath — the pre-departure suite morning', 'pale silk pyjama top and short in white hotel linen — departure morning ease'],
      morning_refresh: ['elevated travel look: tailored wide-leg and silk camisole in lounge', 'first class lounge outfit — silk blazer, satin trousers, complete chic', 'lounge morning look: structured camel or cream blazer with minimal beneath', 'airport lounge chic — understated luxury coordinates in neutral palette', 'first class lounge: silk blouse, tailored trouser, designer bag — effortless', 'lounge morning editorial — structured jacket, minimal, designer jewellery detail'],
      getting_dressed: ['the travel outfit being assembled in the lounge — final touches', 'silk travel blazer and elevated basics in lounge light — curated travel goddess', 'lounge dressing: adding the designer bag, the watch, the final travel detail', 'travel outfit complete — silk, structure, designer accessory, complete composure', 'the lounge preparation look — between casual and dressed in the best possible way', 'lounge getting-ready: adding the scarf, the sunglasses, the polish — fully travel-ready'],
      breakfast:       ['lounge morning: silk blouse and tailored trouser in lounge breakfast ease', 'first class lounge breakfast look — elevated casual, champagne-appropriate', 'lounge breakfast: structured blazer and silk beneath — the correct lounge morning look', 'travel chic lounge morning — everything right, nothing overstated, champagne hand', 'lounge morning ease: neutral silk coordinate and designer bag at the breakfast table', 'first class lounge champagne breakfast look — understated and completely polished'],
      late_morning:    ['jet bridge transition look: full travel outfit, carry-on, sunglasses ready', 'boarding look: the complete travel goddess outfit at the threshold', 'late morning departure: structured coat or blazer with complete travel composure', 'jet bridge moment: tailored travel look with designer bag in late morning light', 'boarding outfit: silk and structure and the specific confidence of first class travel', 'full travel-ready look at the jet bridge — the most aspirational departure visual'],
      lunch:           ['first class in-flight: changed into travel comfort but elevated — silk travel set', 'in-flight: cashmere or silk in first class flatbed — the in-flight luxury look', 'first class travel comfort: elevated loungewear, silk, cashmere — above-cloud ease', 'in-flight silk travel pyjamas in the first class suite — the signature move', 'above-cloud look: first class travel comfort elevated — everything soft and right', 'in-flight elevated comfort: silk jogger and cashmere — the proper first class altitude look'],
      afternoon:       ['arrival transition: back to the travel outfit or fresh arrival look for descent', 'descent arrival look: travel goddess arriving into the new destination', 'jet bridge arrival: the travel outfit arriving into new destination light', 'first class arrival: putting the blazer back on, composing for arrival city', 'arrival look: the travel outfit assembled for the first impression of the new city', 'descent and arrival: the full travel goddess look ready for the destination'],
      reset:           ['transfer car look: travel outfit in private car — sunglasses on, city outside', 'hotel arrival: the travel outfit arriving at the destination hotel lobby', 'transfer chic: the travel look through the new city streets — sunglasses, composure', 'hotel lobby arrival look: complete travel goddess composure arriving at the hotel', 'transfer and check-in: the travel outfit at its most complete and effortless', 'new city arrival: the travel look in the private car — chic, effortless, arrived'],
      golden_hour:     ['rooftop golden hour: elevated off-duty — silk slip dress or minimal chic for the rooftop', 'hotel rooftop golden: the first change into destination clothing — silk, minimal, perfect', 'rooftop arrival golden: slip dress or minimal silk — the destination look begins', 'penthouse golden hour: changed into the destination look — silk, minimal, rooftop-ready', 'golden-hour rooftop: silk cami and wide-leg or minimal dress — the travel goddess arrived', 'suite to rooftop golden: first destination outfit — silk, sunglasses, champagne-ready'],
      dinner:          ['rooftop dinner: elevated silk dress or coordinated dinner look with the city behind', 'destination dinner look: chic, silk, elevated — the travel goddess at the rooftop table', 'rooftop dinner styling: silk midi, heels or elevated sandal, destination chic', 'dinner on the rooftop: the best outfit of the trip on the most cinematic backdrop', 'destination dinner look: silk slip or structured dress — the city as backdrop', 'rooftop dinner: the travel goddess in the most editorial dinner look of the trip'],
      evening:         ['suite evening: silk robe or elevated lounge over minimal — city view as backdrop', 'hotel suite evening: silk in the window light — minimal, beautiful, city-framed', 'rooftop evening: elevated silk cover or minimal look in the evening city light', 'suite evening ease: silk cami and wide-leg or robe at the city window', 'penthouse evening: the minimal beautiful silk look at the floor-to-ceiling window', 'suite evening: between travel and destination — silk and city view'],
      night:           ['suite night: silk slip or minimal look at the city window at full night', 'penthouse night: minimal silk at the floor-to-ceiling glass with city lights behind', 'rooftop night look: elevated minimal silk for the complete night city view', 'suite night ease: silk slip against the full city light window — the final travel look', 'night suite: minimal and silk and the city completely lit below', 'penthouse night: the most minimal beautiful look at the window — the travel day complete'],
    },
    details: {
      wake:            ['white hotel slippers on polished hotel floor', 'designer bag packed and near the door', 'boarding pass or phone on white hotel linen'],
      morning_refresh: ['champagne flute in first class lounge morning', 'designer watch catching lounge light', 'lounge pastry beside the champagne on marble surface'],
      getting_dressed: ['sunglasses placed on in lounge before boarding', 'designer bag at the lounge seat during preparation', 'silk scarf tied loosely at the throat before departure'],
      breakfast:       ['champagne flute on lounge marble breakfast surface', 'designer bag at the lounge seat during breakfast', 'lounge morning cup with tarmac view behind through the glass'],
      late_morning:    ['boarding pass and phone in hand at jet bridge', 'designer carry-on in jet bridge late morning light', 'sunglasses on as the jet bridge brightens toward the aircraft'],
      lunch:           ['champagne flute in first class suite at altitude', 'white linen napkin in first class service', 'oval window light behind the in-flight lunch setting'],
      afternoon:       ['window shade adjusted in first class for the descent view', 'passport visible in designer bag for arrival', 'sunglasses on as the destination city comes into view below'],
      reset:           ['sunglasses on in private transfer car through new city', 'key card in designer bag at hotel check-in', 'designer bag detail in hotel lobby marble light'],
      golden_hour:     ['champagne flute at rooftop golden hour', 'designer sunglasses on rooftop at golden hour', 'city panorama behind at the golden-hour rooftop moment'],
      dinner:          ['champagne at rooftop dinner table with city behind', 'silk detail in rooftop dinner light', 'destination city skyline behind the rooftop dinner table'],
      evening:         ['wine or champagne at suite window in evening', 'city lights visible through floor-to-ceiling window', 'silk detail at suite window in evening city light'],
      night:           ['champagne or wine glass at penthouse window at night', 'city lights full behind the suite window at night', 'minimal jewellery detail in penthouse night window light'],
    },
    changeMoments: {
      wake:            ['hotel suite morning — between sleep and the travel day in white linen', 'pre-departure hotel morning — the last private moment before transit begins'],
      morning_refresh: ['in the first class lounge — the travel day beginning in the best waiting room', 'lounge morning — between departure and the flight, in total luxury'],
      getting_dressed: ['assembling the travel look in the lounge — fully prepared for the journey', 'the final lounge preparation before boarding — everything in place'],
      breakfast:       ['lounge morning ease — travel ready, champagne in hand, world ahead', 'the lounge breakfast as the transition from ground to flight'],
      late_morning:    ['jet bridge — the threshold moment between the departure city and the air', 'boarding in the full travel outfit — the definitive departure moment'],
      lunch:           ['first class in-flight ease — the transition to above-cloud comfort', 'changed into in-flight luxury in the flatbed suite — the air travel comfort ritual'],
      afternoon:       ['back to arrival travel look as the destination comes into view', 'jet bridge arrival — the threshold into the new destination world'],
      reset:           ['transfer car arrival look — the travel outfit arriving at the destination', 'hotel lobby arrival — the complete travel goddess entering the destination'],
      golden_hour:     ['changed into the first destination look at golden hour for the rooftop', 'rooftop arrival — the first destination outfit at golden hour'],
      dinner:          ['rooftop dinner look — the best outfit of the trip on the most beautiful backdrop', 'destination dinner styling on the rooftop above the city'],
      evening:         ['suite evening silk — minimal and perfect at the city window', 'rooftop to suite transition — settling into the destination evening'],
      night:           ['suite night minimal — silk at the city window at full night', 'the final travel look — minimal, beautiful, city lights behind'],
    },
  },

  sensoryPools: {
    wake:            ['white hotel linen against skin in morning warmth', 'city sounds barely audible through the hotel window', 'the specific calm of a luxury hotel morning before departure'],
    morning_refresh: ['champagne bubbles in the first class lounge morning', 'lounge coffee warmth and the specific smell of a premium airport lounge', 'tarmac view through floor-to-ceiling glass in the morning light'],
    getting_dressed: ['silk blazer weight on shoulders in lounge preparation', 'designer watch cool on the wrist in lounge light', 'the specific feeling of being completely travel-ready in the lounge'],
    breakfast:       ['champagne cool and fine in the lounge morning', 'lounge croissant and the specific luxury of airport lounge breakfast', 'tarmac view through glass while eating — the world about to open'],
    late_morning:    ['jet bridge tunnel warm air before boarding', 'the specific light and temperature of the jet bridge', 'the threshold feeling of crossing from airport to aircraft'],
    lunch:           ['first class flatbed linen soft and white above the clouds', 'champagne at altitude — the specific elevation sensation', 'above-cloud brightness through the oval window at noon'],
    afternoon:       ['descent pressure change in the first class cabin', 'first sight of the destination city through the oval window', 'arrival airport air through the jet bridge — new country smell'],
    reset:           ['private transfer car leather cool in afternoon', 'new city sounds beginning through the transfer window', 'hotel lobby air-conditioned grand arrival sensation'],
    golden_hour:     ['rooftop warm amber air at golden hour', 'champagne cool against warm rooftop golden light', 'city spread below at golden hour — the complete arrival sensation'],
    dinner:          ['warm rooftop evening air at dinner', 'city sounds from the rooftop dinner height', 'champagne at the rooftop dinner with the city panorama'],
    evening:         ['suite air-conditioned cool against city-warm view through glass', 'floor-to-ceiling glass cool against the hands at the suite window', 'city ambient sound through the suite window in the evening'],
    night:           ['penthouse night quiet above the city', 'city lights through floor-to-ceiling glass at full night', 'champagne at the suite window at full city-lit night'],
  },

  socialEnergyPools: {
    wake:            ['private hotel suite morning — alone before the travel day begins', 'the hotel pre-departure morning as the most private travel moment'],
    morning_refresh: ['first class lounge — surrounded by luxury, appropriately separate', 'lounge morning ease — other travellers present but irrelevant'],
    getting_dressed: ['lounge preparation — personal ritual in the world\'s best waiting room', 'the travel look assembled privately in the lounge space'],
    breakfast:       ['lounge morning — elegant public-private breakfast with tarmac view', 'champagne breakfast in the first class lounge — visible ease'],
    late_morning:    ['jet bridge transition — liminal between worlds, briefly alone', 'the boarding moment — through the threshold and into the next chapter'],
    lunch:           ['first class suite — the most private public space in travel', 'in-flight first class — the other cabin a world away'],
    afternoon:       ['descent arrival — anticipation building, the new world approaching', 'arrival jet bridge — alone in the threshold between flight and destination'],
    reset:           ['private transfer — alone in the car with the new city outside', 'hotel lobby arrival — public arrival, completely composed'],
    golden_hour:     ['rooftop arrival — the destination presenting itself at its best', 'champagne on the rooftop — the travel goddess arrived and seen'],
    dinner:          ['rooftop dinner — the destination city as the social backdrop', 'the most elevated public dinner setting — rooftop above the city'],
    evening:         ['suite evening — private above the city, composed and complete', 'rooftop evening — between private and public above the city lights'],
    night:           ['penthouse night — completely private above the full lit city', 'suite full night — the travel day complete and private'],
  },

  atmospherePools: {
    wake:            ['luxury hotel morning atmosphere — white linen and pre-departure calm', 'the hotel suite pre-departure as the most beautiful ordinary travel morning'],
    morning_refresh: ['first class lounge atmosphere — the world\'s most refined transit space', 'lounge morning atmosphere — elevated, warm, completely curated'],
    getting_dressed: ['lounge preparation atmosphere — chic, elevated, completely composed', 'the travel outfit assembled in the most beautiful waiting room on earth'],
    breakfast:       ['first class lounge breakfast atmosphere — tarmac view, champagne, morning ease', 'the lounge as the best breakfast room available to travel'],
    late_morning:    ['jet bridge atmosphere — transitional, warm, threshold moment', 'the departure energy atmosphere — everything about to begin'],
    lunch:           ['first class above-cloud atmosphere — the most elevated lunch environment', 'in-flight first class noon — white linen, cloud view, complete elevation'],
    afternoon:       ['descent atmosphere — anticipation, new city, arrival energy', 'the arrival jet bridge as the destination\'s first real atmosphere'],
    reset:           ['private transfer atmosphere — new city outside, private inside', 'hotel lobby arrival atmosphere — grand, warm, complete destination arrival'],
    golden_hour:     ['rooftop golden-hour atmosphere — the destination at its most beautiful', 'hotel golden-hour arrival atmosphere — champagne, city, complete arrival'],
    dinner:          ['rooftop dinner atmosphere — the destination city as backdrop', 'the most aspirational dinner atmosphere — above the city at golden-to-night'],
    evening:         ['suite city-window evening atmosphere — private, elevated, completely arrived', 'hotel evening atmosphere — city below, suite above, the day complete'],
    night:           ['penthouse city night atmosphere — the most complete travel destination feeling', 'full city-lit night atmosphere from above — the travel day perfectly resolved'],
  },

  propPools: {
    wake:            ['white hotel linen and pillow arrangement', 'designer bag packed near the door', 'hotel bedside table with passport and boarding pass'],
    morning_refresh: ['champagne flute in first class lounge', 'lounge morning coffee on marble surface', 'floor-to-ceiling tarmac window in lounge morning'],
    getting_dressed: ['designer sunglasses on lounge table', 'silk scarf being tied in lounge', 'designer watch being fastened in good lounge light'],
    breakfast:       ['champagne flute at lounge breakfast', 'croissant on lounge marble surface', 'tarmac view through the lounge glass at breakfast'],
    late_morning:    ['boarding pass in hand at jet bridge', 'designer carry-on in jet bridge light', 'jet bridge porthole window with tarmac and aircraft outside'],
    lunch:           ['first class champagne flute at altitude', 'white first class service linen', 'oval window with clouds below in first class suite'],
    afternoon:       ['first class oval window with destination below', 'in-flight service tray in first class', 'sunglasses being put on for arrival city'],
    reset:           ['private car interior with city through tinted window', 'key card in designer bag', 'hotel lobby architecture at arrival'],
    golden_hour:     ['champagne on rooftop at golden hour', 'city skyline panorama at rooftop golden hour', 'rooftop pool reflecting golden-hour sky'],
    dinner:          ['wine or champagne at rooftop dinner table', 'city skyline behind the rooftop dinner', 'rooftop table set against city panorama'],
    evening:         ['suite window with city lights beginning', 'champagne at the floor-to-ceiling suite window', 'city lights through glass in suite evening'],
    night:           ['penthouse window with full city lights', 'champagne at the penthouse night window', 'city illumination through floor-to-ceiling glass'],
  },

  bodyLanguagePools: {
    wake:            ['stretched in white hotel linen — effortless luxury morning ease', 'sitting at the hotel window with complete composure before the day', 'lying in hotel white linen with one arm extended — composed morning ease'],
    morning_refresh: ['seated at first class lounge window with champagne — owned ease', 'standing at lounge floor-to-ceiling window looking at tarmac — complete composure', 'walking through the lounge to the window with champagne — the goddess stroll'],
    getting_dressed: ['adjusting the travel look in the lounge mirror — precise and effortless', 'fastening a watch or accessory in lounge light — deliberate ease', 'placing sunglasses on in the lounge — the signature travel goddess movement'],
    breakfast:       ['both hands around lounge cup at window — completely at ease', 'seated at lounge breakfast with complete ease — the tarmac irrelevant below', 'standing at lounge food display selecting with total composure'],
    late_morning:    ['walking the jet bridge with complete purpose and ease', 'pausing at jet bridge window — the composed threshold pause', 'pulling carry-on through the private terminal with effortless grace'],
    lunch:           ['lying in first class flatbed with complete ease — above it all', 'sitting up in first class suite with champagne — elevated ease', 'looking out the oval window with complete absorption — the cloud-world'],
    afternoon:       ['leaning toward the first class window to see the destination below', 'sitting up in the first class suite as arrival energy builds', 'walking through the arrival jet bridge with ease — arrived'],
    reset:           ['seated in transfer car looking out — quiet composed observation', 'arriving at hotel lobby and looking up — genuine wonder with complete composure', 'hotel check-in with complete ease — the travel goddess arriving as expected'],
    golden_hour:     ['standing at rooftop edge with champagne and city behind — the signature pose', 'seated at rooftop lounge with the city at golden hour spreading behind', 'rooftop pool edge stance — the definitive travel goddess arrival visual'],
    dinner:          ['seated at rooftop dinner with city behind — the most aspirational dinner posture', 'standing at rooftop terrace with wine — the city at dinner as the background', 'rooftop dinner ease — the city below performing for the table'],
    evening:         ['at suite floor-to-ceiling window in evening — one hand on glass, city below', 'seated in suite with city lights through the window — completely arrived', 'rooftop evening ease — looking at the city with complete satisfaction'],
    night:           ['standing at penthouse window at full night — hands on glass, city spread below', 'suite night ease on the bed — city lights as the only light needed', 'rooftop at night looking at the city — the most complete travel arrival posture'],
  },

  facialExpressionPools: {
    wake:            ['hotel morning ease — soft, private, the day not yet begun', 'pre-departure composure — present, warm, unhurried', 'hotel suite window morning expression — quiet anticipation'],
    morning_refresh: ['first class lounge composure — at ease, elevated, belonging', 'lounge morning expression — warm, composed, champagne-appropriate', 'the lounge look — effortlessly present, elevated without effort'],
    getting_dressed: ['lounge preparation expression — focused, precise, completely self-possessed', 'travel look assembled expression — the composed travel goddess ready to board', 'the lounge mirror expression — satisfied, precise, completely right'],
    breakfast:       ['lounge breakfast ease — warm, unhurried, completely at home here', 'champagne breakfast expression — the most elevated ordinary morning face', 'lounge tarmac-view expression — calm, warm, the world about to begin'],
    late_morning:    ['jet bridge expression — purposeful, anticipatory, completely composed', 'departure expression — the travel goddess at the threshold, completely ready', 'boarding composure — the most effortless departure expression'],
    lunch:           ['first class above-cloud expression — elevated ease, cloud-world calm', 'in-flight first class expression — the most composed the traveller ever looks', 'oval window cloud expression — absorbed, peaceful, elevated'],
    afternoon:       ['descent anticipation expression — the new city below, quiet excitement', 'arrival expression — composed, warm, ready for the new destination', 'jet bridge arrival expression — the journey transitioning to destination'],
    reset:           ['transfer car expression — looking at the new city with warm quiet observation', 'hotel lobby arrival expression — genuine appreciation with complete composure', 'the new city arrival expression — present, warm, completely composed'],
    golden_hour:     ['rooftop golden-hour expression — warm, arrived, champagne in hand', 'the arrival golden-hour expression — the most beautiful face of the trip', 'rooftop champagne expression — the travel goddess at complete arrival'],
    dinner:          ['rooftop dinner expression — warm, elegant, city as backdrop', 'destination dinner composure — the most elevated dinner expression', 'city-behind dinner expression — appreciative, warm, completely at home'],
    evening:         ['suite evening expression — quiet satisfaction, city below, completely arrived', 'penthouse city-window evening expression — warm, private, complete', 'the travel arrived expression — composed, warm, the journey complete'],
    night:           ['penthouse night expression — the most complete travel arrival composure', 'city-at-night expression — appreciative, warm, completely resolved', 'full night suite expression — the travel goddess at the end of the perfect day'],
  },

  handDetailPools: {
    wake:            ['hand on white hotel linen in morning light', 'reaching for the phone on the hotel bedside table', 'fingers touching the hotel window glass in pre-departure morning'],
    morning_refresh: ['champagne flute held in first class lounge morning', 'fingers on lounge marble surface at breakfast', 'hand at the lounge window glass looking at tarmac'],
    getting_dressed: ['fastening designer watch in lounge morning light', 'placing sunglasses on in lounge', 'adjusting silk scarf in lounge before boarding'],
    breakfast:       ['both hands around lounge cup at window', 'champagne flute held by the lounge window', 'lounge croissant held in morning lounge light'],
    late_morning:    ['boarding pass held in jet bridge light', 'hand on jet bridge window glass looking at tarmac', 'carry-on handle in hand in jet bridge light'],
    lunch:           ['champagne flute in first class suite at noon altitude', 'hand resting on first class linen while looking out oval window', 'fingers at first class window frame looking at clouds below'],
    afternoon:       ['finger touching oval window frame as destination comes into view', 'passport or phone in designer bag at arrival', 'hand on first class seat arm as descent continues'],
    reset:           ['fingers on private car window glass as new city passes', 'key card being placed in designer bag at hotel', 'hand at hotel lobby counter during check-in'],
    golden_hour:     ['champagne flute at rooftop golden hour', 'hand on rooftop terrace railing with city behind', 'fingers trailing rooftop pool edge at golden hour'],
    dinner:          ['wine glass at rooftop dinner table', 'hand resting on rooftop dinner table with city behind', 'fingers at rooftop terrace railing at dinner'],
    evening:         ['hand on suite floor-to-ceiling glass at evening', 'champagne glass at suite window in evening city light', 'fingers touching the window frame at the suite evening city view'],
    night:           ['both hands on penthouse window glass at full night city view', 'champagne at the penthouse window at city night', 'fingers touching the suite glass as city lights spread below'],
  },

  movementEnergyPools: {
    wake:            ['hotel-morning', 'pre-departure', 'unhurried'],
    morning_refresh: ['lounge-ease', 'champagne-morning', 'elevated'],
    getting_dressed: ['composed', 'travel-ready', 'precise'],
    breakfast:       ['lounge-ease', 'tarmac-view', 'warm'],
    late_morning:    ['purposeful', 'threshold', 'departure'],
    lunch:           ['above-cloud', 'elevated', 'still'],
    afternoon:       ['descent', 'anticipatory', 'arrival'],
    reset:           ['new-city', 'transfer', 'arriving'],
    golden_hour:     ['rooftop', 'arrived', 'golden'],
    dinner:          ['city-above', 'rooftop-ease', 'warm'],
    evening:         ['suite', 'city-window', 'arrived'],
    night:           ['penthouse', 'city-lit', 'complete'],
  },

  transitionPools: {
    human: {
      wake:            ['hotel suite pre-departure morning — one last beautiful morning', 'white linen and the city waking below before the travel day begins'],
      morning_refresh: ['first class lounge morning — champagne and tarmac view before the flight', 'the lounge as the best start to the travel day'],
      getting_dressed: ['assembling the travel look in the lounge — departure composure', 'the lounge preparation before the flight'],
      breakfast:       ['lounge breakfast before the journey — tarmac view, champagne, ease', 'the first class lounge as the travel goddess morning ritual'],
      late_morning:    ['the jet bridge threshold — between the departure city and the air', 'boarding — the travel day beginning in earnest'],
      lunch:           ['first class above the clouds at noon — the most elevated lunch', 'in-flight first class — the world below and irrelevant'],
      afternoon:       ['descent — the new city appearing below', 'arrival — the destination becoming real through the window'],
      reset:           ['private transfer through the new city streets — arrival beginning', 'hotel lobby arrival — the destination delivering on its promise'],
      golden_hour:     ['rooftop golden hour — the destination at its most cinematic', 'the golden-hour arrival moment — champagne, city, arrived'],
      dinner:          ['rooftop dinner with the city behind — the definitive travel evening', 'above the destination city at dinner — the most beautiful table in the world'],
      evening:         ['suite evening above the city — the travel day complete', 'city lights below the penthouse — completely arrived'],
      night:           ['penthouse at full city night — the travel goddess completely delivered', 'the city lit below at full night — the perfect end to the travel day'],
    },
  },

  narrativeIntentPools: {
    wake:            ['hotel suite pre-departure as the most beautiful ordinary travel morning', 'white linen and the city waking — the travel day about to begin'],
    morning_refresh: ['first class lounge morning as the most elevated transit ritual', 'champagne at 8am at the tarmac window — the correct way to start a travel day'],
    getting_dressed: ['the lounge preparation as the travel goddess ritual before flight', 'assembling the perfect travel look in the world\'s best dressing room'],
    breakfast:       ['lounge breakfast as the definitive travel goddess morning moment', 'the first class lounge as the world\'s most aspirational breakfast setting'],
    late_morning:    ['the jet bridge as the most cinematic transit threshold', 'departure — the travel goddess crossing from the city to the sky'],
    lunch:           ['first class above the clouds as the most elevated lunch in the world', 'in-flight noon at altitude — the most private and luxurious midday'],
    afternoon:       ['descent and arrival — the new destination emerging from below', 'the first sight of the destination city from the first class oval window'],
    reset:           ['private transfer as the first real contact with the destination', 'hotel lobby arrival — the travel day\'s first chapter complete'],
    golden_hour:     ['rooftop arrival at golden hour as the travel day\'s most cinematic payoff', 'champagne above the destination city at the best light of the day'],
    dinner:          ['rooftop dinner above the destination — the travel goddess at her most aspirational', 'the city skyline as the dinner backdrop — the definitive travel evening'],
    evening:         ['suite above the city at evening — completely arrived, completely beautiful', 'city lights below the penthouse — the travel day fully delivered'],
    night:           ['penthouse at full city night — the most complete travel destination feeling', 'the city spread in lights below the suite — the journey complete and perfect'],
  },

  fallbackRules: {
    pacingProfile: { wake: 'slow', morning_refresh: 'slow', getting_dressed: 'slow', breakfast: 'slow', late_morning: 'medium', lunch: 'slow', afternoon: 'slow', reset: 'medium', golden_hour: 'slow', dinner: 'slow', evening: 'slow', night: 'slow' },
    repetitionBreakers: { avoidBackToBackSameLocation: true, avoidBackToBackSameLightingStyle: true, encourageWardrobeEvolution: true },
    worldDefaults: { allowSceneGroupFallbackToPhasePools: true, allowSubLocationFallbackToWorldPools: true, preferSceneGroupsWhenPresent: true },
  },

  exclusions: {
    premium: ['economy or budget travel settings', 'crowded airport gates', 'visible stress or rushing', 'tourist energy or sightseeing'],
    hard: ['budget accommodation', 'economy cabin', 'crowded public spaces', 'visible price tags or branding', 'non-luxury vehicles'],
  },

  routeRules: {
    worldIdentity: ['every moment feels effortlessly elevated — this is first class, rooftop, penthouse, always', 'the traveller moves through the world with complete ease — no stress, no rush, no tourist energy'],
    humanFlow: ['the day follows a complete travel arc: hotel morning → lounge → flight → arrival → rooftop → suite', 'each phase moves the story through a real travel day at the highest level of luxury'],
    styling: ['travel chic only — silk, tailored, designer accessories, sunglasses, nothing casual or sporty', 'the wardrobe evolves from hotel morning ease through travel outfit through arrival destination look'],
    atmosphere: ['every setting is first class, private, elevated — lounge, flatbed, rooftop, penthouse', 'the world responds to her with effortless upgrade energy'],
  },
}
