export const STORY_WORLD_VICTORIAS_ANGEL = {
  id: 'victorias-angel',
  name: "Victoria's Angel",
  description:
    'A cinematic world of high-fashion lingerie editorial — the dressing room before the show, backstage wings and diamonds, the runway walk itself, and intimate luxury aftermath. The body as the ultimate luxury product.',

  geography: { country: 'fashion world / private interior', region: 'backstage dressing room, runway, penthouse suite, editorial studio' },

  identity: {
    archetype: 'luxury lingerie angel — runway editorial creator',
    vibe: ['wings and diamonds and silk', 'the backstage before the most famous lingerie show', 'the runway as the most powerful stage', 'intimate luxury editorial', 'the body as the ultimate fashion product'],
    tone: ['theatrical', 'glamorous', 'intimate', 'editorial', 'powerful', 'beautiful', 'deliberate'],
    persona: ['the most beautiful woman on the most famous runway', 'completely at ease in wings and diamonds and nothing else', 'the editorial lingerie moment as art and power', 'the Victoria\'s Angel as the cultural ideal of feminine luxury beauty'],
  },

  phaseOrder: ['wake', 'morning_refresh', 'getting_dressed', 'breakfast', 'late_morning', 'lunch', 'afternoon', 'reset', 'golden_hour', 'dinner', 'evening', 'night'],

  phases: {
    wake:            { label: 'Wake',            timeWindows: ['model morning in hotel or suite before the show', 'the angel morning — private luxury before the runway'],    pacing: 'slow',   subLocations: ['angel-suite', 'model-hotel'] },
    morning_refresh: { label: 'Morning Refresh', timeWindows: ['pre-show beauty morning ritual', 'hotel bathroom morning before the show'],                                    pacing: 'slow',   subLocations: ['hotel-bathroom', 'angel-vanity'] },
    getting_dressed: { label: 'Getting Dressed', timeWindows: ['the fitting ritual', 'trying on the angel look for the shoot or show'],                                       pacing: 'slow',   subLocations: ['dressing-room', 'angel-vanity'] },
    breakfast:       { label: 'Breakfast',       timeWindows: ['model morning breakfast in hotel suite', 'angel morning before the show'],                                     pacing: 'slow',   subLocations: ['angel-suite', 'model-hotel'] },
    late_morning:    { label: 'Late Morning',    timeWindows: ['backstage preparation morning', 'editorial beauty preparation in backstage or studio'],                         pacing: 'medium', subLocations: ['backstage', 'editorial-studio'] },
    lunch:           { label: 'Lunch',           timeWindows: ['backstage or hotel pre-show midday', 'model lunch before the editorial or show'],                              pacing: 'slow',   subLocations: ['backstage', 'angel-suite'] },
    afternoon:       { label: 'Afternoon',       timeWindows: ['full hair and makeup and fitting afternoon', 'the transformation into the angel look'],                         pacing: 'slow',   subLocations: ['backstage', 'dressing-room'] },
    reset:           { label: 'Reset',           timeWindows: ['the final preparation hour before the show or editorial', 'wings fitting and diamond styling'],                pacing: 'slow',   subLocations: ['dressing-room', 'angel-vanity'] },
    golden_hour:     { label: 'Golden Hour',     timeWindows: ['the pre-show golden moment', 'the angel before the runway or editorial camera in warm light'],                pacing: 'slow',   subLocations: ['pre-show-corridor', 'dressing-room'] },
    dinner:          { label: 'Dinner',          timeWindows: ['the runway or editorial show moment', 'the angel on the runway or in the editorial frame'],                    pacing: 'slow',   subLocations: ['runway', 'editorial-studio'] },
    evening:         { label: 'Evening',         timeWindows: ['post-show luxury — the after party or suite', 'angel after the runway in private luxury'],                     pacing: 'slow',   subLocations: ['after-party', 'angel-suite'] },
    night:           { label: 'Night',           timeWindows: ['private suite after the show', 'the angel at private rest after the runway'],                                  pacing: 'slow',   subLocations: ['angel-suite', 'model-hotel'] },
  },

  locations: [
    'hotel suite before the show', 'backstage dressing room with wings and diamonds', 'editorial studio with angel look',
    'the runway in wings and luxury lingerie', 'pre-show corridor in complete angel styling', 'after-party luxury suite',
    'angel vanity with beauty and diamond styling', 'model hotel room in morning',
  ],

  subLocations: {
    'angel-suite': {
      id: 'angel-suite', name: 'Angel Suite', mapAnchor: 'luxury hotel suite before the show',
      category: 'private-angel',
      bestPhases: ['wake', 'breakfast', 'lunch', 'evening', 'night'],
      overlays: ['luxury hotel suite in show-city morning', 'white linen and private luxury before the runway', 'the angel at private rest or preparation'],
      locations: ['luxury hotel suite in show morning', 'angel private suite before the runway', 'private hotel luxury in show-world setting'],
    },
    'model-hotel': {
      id: 'model-hotel', name: 'Model Hotel Room', mapAnchor: 'model hotel room',
      category: 'private-model',
      bestPhases: ['wake', 'night'],
      overlays: ['model morning hotel room before the show', 'private hotel interior before the runway', 'the angel at rest in hotel luxury'],
      locations: ['model hotel room before the show in morning', 'private hotel interior in show setting', 'model morning private hotel luxury'],
    },
    'hotel-bathroom': {
      id: 'hotel-bathroom', name: 'Hotel Bathroom', mapAnchor: 'hotel bathroom morning',
      category: 'self-care-angel',
      bestPhases: ['morning_refresh'],
      overlays: ['hotel bathroom morning ritual before the show', 'luxury bathroom in pre-show morning', 'model morning self-care ritual'],
      locations: ['hotel bathroom morning ritual pre-show', 'luxury model morning bathroom', 'pre-runway morning self-care setting'],
    },
    'angel-vanity': {
      id: 'angel-vanity', name: 'Angel Vanity', mapAnchor: 'angel preparation vanity',
      category: 'preparation-angel',
      bestPhases: ['morning_refresh', 'getting_dressed', 'reset'],
      overlays: ['vanity with diamond and beauty products', 'angel transformation preparation', 'the vanity where the angel look is built'],
      locations: ['angel preparation vanity with diamonds', 'the transformation vanity in show setting', 'luxury preparation with angel beauty and jewelry'],
    },
    'dressing-room': {
      id: 'dressing-room', name: 'Dressing Room', mapAnchor: 'backstage angel dressing room',
      category: 'transformation',
      bestPhases: ['getting_dressed', 'afternoon', 'reset'],
      overlays: ['backstage dressing room with wings and lingerie', 'the transformation space before the angel walk', 'diamond fantasy dressing room energy'],
      locations: ['backstage dressing room with wings hanging', 'angel lingerie and diamond fitting room', 'the transformation space backstage'],
    },
    'backstage': {
      id: 'backstage', name: 'Backstage', mapAnchor: 'backstage before the show',
      category: 'pre-show',
      bestPhases: ['late_morning', 'lunch', 'afternoon'],
      overlays: ['backstage before the most famous lingerie show', 'angels getting ready around her', 'backstage beauty and editorial energy'],
      locations: ['backstage with other angels in preparation', 'backstage mirror and beauty area', 'pre-show backstage energy in full preparation'],
    },
    'editorial-studio': {
      id: 'editorial-studio', name: 'Editorial Studio', mapAnchor: 'luxury editorial lingerie studio',
      category: 'editorial-shoot',
      bestPhases: ['late_morning', 'dinner'],
      overlays: ['luxury editorial studio with angel look', 'fashion photography studio with wings and lingerie', 'editorial angel in professional studio light'],
      locations: ['luxury editorial studio with angel styling', 'fashion studio in angel lingerie editorial', 'professional editorial studio with wings and diamond'],
    },
    'pre-show-corridor': {
      id: 'pre-show-corridor', name: 'Pre-Show Corridor', mapAnchor: 'backstage corridor before runway',
      category: 'pre-runway',
      bestPhases: ['golden_hour'],
      overlays: ['backstage corridor before the runway walk', 'the angel in full look before the cameras', 'pre-show corridor energy with wings and diamonds'],
      locations: ['backstage corridor in full angel look before runway', 'the moment before the runway walk', 'pre-show corridor in wings and complete angel styling'],
    },
    'runway': {
      id: 'runway', name: 'Runway', mapAnchor: 'the runway walk',
      category: 'runway-moment',
      bestPhases: ['dinner'],
      overlays: ['the runway in wings and luxury lingerie', 'the most famous walk in fashion', 'the angel on the runway at full presence'],
      locations: ['the runway in wings and diamond lingerie', 'the most powerful walk — angel on the runway', 'the complete angel moment on the fashion runway'],
    },
    'after-party': {
      id: 'after-party', name: 'After Party', mapAnchor: 'show after-party',
      category: 'post-show',
      bestPhases: ['evening'],
      overlays: ['show after-party in luxury venue', 'the angel post-show in glamour', 'celebration after the runway walk'],
      locations: ['luxury after-party post-show venue', 'angel at after-party in glamorous setting', 'post-runway celebrity after-party'],
    },
  },

  sceneVariants: {
    wake: ['the angel morning — hotel luxury before the most famous lingerie runway', 'waking in a hotel suite in show city in warm private morning'],
    morning_refresh: ['hotel bathroom morning ritual before the show', 'the angel self-care in luxury hotel bathroom before the runway'],
    getting_dressed: ['the fitting ritual — wings and diamonds in the dressing room', 'trying on the angel look in the backstage dressing room'],
    breakfast: ['model breakfast in hotel suite before the show day begins', 'the angel morning meal before the backstage preparation'],
    late_morning: ['backstage preparation beginning — hair, makeup, and wings', 'editorial studio angel look being assembled in professional light'],
    lunch: ['backstage model lunch in preparation energy', 'the angel midday before the full transformation into the runway look'],
    afternoon: ['the full angel transformation — wings fitted, diamonds on, lingerie complete', 'hair and makeup and wings in the backstage dressing room'],
    reset: ['the final moments before the runway — wings perfect, look complete', 'the angel in the dressing room before the walk begins'],
    golden_hour: ['the pre-show corridor — the angel in full look before the cameras', 'the most powerful pre-runway moment — wings and diamonds complete'],
    dinner: ['the runway walk — the angel in wings and luxury lingerie on the world\'s most famous stage', 'the editorial studio moment — the angel in the most beautiful editorial light'],
    evening: ['post-show luxury at the after-party — the angel after the runway', 'the celebration after the most famous lingerie walk'],
    night: ['private suite after the show — the angel at rest', 'the runway world complete in private hotel luxury at night'],
  },

  actionPools: {
    wake: [
      'waking in hotel suite before the show in morning luxury',
      'the angel morning — private and composed before the most famous walk',
      'hotel morning ease before the backstage world begins',
      'slow private wake in luxury hotel suite in show city — the runway still hours ahead but already felt',
      'lying in hotel white linen in private morning before the day that will be entirely about the wings and the walk',
      'the model before the angel — private hotel morning ease, the show world not yet entered',
    ],
    morning_refresh: [
      'hotel bathroom morning ritual in luxury pre-show setting',
      'the angel self-care in warm bathroom before backstage',
      'beauty preparation beginning in private hotel morning',
      'hotel bathroom morning ritual — clean skin before the transformation, the private face before the show face',
      'standing at the hotel mirror in the pre-show morning, applying the first layer of the angel preparation',
      'the private self-care before the theatrical self begins — hotel bathroom ritual in show morning',
    ],
    getting_dressed: [
      'fitting the wings in the backstage dressing room',
      'trying on the complete angel look with diamonds and lingerie',
      'the transformation ritual — wings, diamonds, and the complete angel style',
      'wings being placed on the back in the dressing room — the most theatrical fashion gesture in the world',
      'the diamond bra being fastened in the dressing room — the weight of it precise and extraordinary',
      'standing in the dressing room as the complete angel look assembles around her — wings, diamonds, silk',
    ],
    breakfast: [
      'hotel suite breakfast before the show day begins',
      'model morning meal in private hotel luxury',
      'the angel eating before the backstage preparation',
      'calm hotel suite breakfast in show morning — fruit, coffee, the runway still ahead',
      'the model private morning meal before the backstage world — fuel and quiet before the theatrical day',
      'hotel suite breakfast table in show city morning — the wings and diamonds waiting, the meal calm and private',
    ],
    late_morning: [
      'backstage preparation — hair and makeup beginning',
      'editorial studio preparation with the full angel look',
      'the angel transformation beginning in professional backstage setting',
      'seated in the backstage beauty chair as hair begins — the transformation from model to angel starting',
      'editorial studio in the angel look under professional preparation light — every detail being assembled',
      'backstage preparation morning — the professional team building the angel around her with precision',
    ],
    lunch: [
      'backstage model lunch in full preparation energy',
      'the angel midday meal before the complete transformation',
      'eating well backstage before the runway energy builds',
      'backstage midday — the model eating between preparation stages, the wings not yet on',
      'the angel midday in partial backstage look, the full transformation still ahead',
      'quiet model lunch in the backstage or suite before the afternoon transformation peak begins',
    ],
    afternoon: [
      'the full angel transformation — wings, diamonds, and lingerie',
      'complete hair and makeup in backstage dressing room',
      'the dressing room ritual — every detail of the angel look being perfected',
      'wings being fitted fully in the afternoon dressing room — the angel assembling in real time',
      'the complete transformation — the diamond bra on, the wings fitted, the hair done, the angel ready',
      'the afternoon backstage at peak theatrical intensity — every detail of the complete angel look in progress',
    ],
    reset: [
      'the final dressing room moment — look complete, ready for the walk',
      'wings being adjusted one final time before the corridor',
      'the angel at the mirror in complete look before the runway',
      'standing at the dressing room mirror in complete angel look — the final self-assessment before the walk',
      'the wings adjusted one last time, the diamond check complete, the angel ready for the corridor',
      'the final pre-runway moment in the dressing room — complete, composed, the walk imminent',
    ],
    golden_hour: [
      'the pre-show corridor in complete angel look — the most powerful pre-runway moment',
      'standing in wings and diamonds before the cameras in the corridor',
      'the angel the moment before the walk begins',
      'wings spread in the pre-show corridor — the most theatrical pre-runway fashion moment on earth',
      'the corridor — the angel in complete look, the runway doors ahead, the cameras already present',
      'standing in the pre-show corridor in wings and diamonds, the show beginning beyond the doors',
    ],
    dinner: [
      'the runway walk in wings and luxury lingerie on the world\'s most famous stage',
      'the editorial studio moment — the angel in perfect light with wings',
      'the most powerful fashion moment — angel on the runway or in editorial frame',
      'walking the runway in full angel look — wings, diamond lingerie, the walk the most iconic in fashion',
      'the editorial studio moment — in complete angel look under professional dramatic light, the wings at full span',
      'the runway at full power — the angel in motion, the wings and diamonds and the walk the only thing that exists',
    ],
    evening: [
      'the after-party celebration post-show in luxury setting',
      'the angel post-runway in glamorous evening',
      'celebrating after the most famous walk in luxury after-party',
      'arriving at the after-party — still in show glamour, the runway walk complete, the celebration beginning',
      'the after-party post-show in luxury venue — the angel in the evening version of the theatrical look',
      'celebrating at the after-party after the most famous lingerie walk on earth — champagne and luxury and relief',
    ],
    night: [
      'private suite after the show — the wings off and at rest',
      'the angel at private luxury rest after the runway',
      'hotel suite night after the most powerful fashion day',
      'removing the wings in the hotel suite after the show — the most private moment of the theatrical day',
      'the hotel suite at night after the runway — the angel identity at rest, the model herself again in private',
      'private luxury hotel night after the show — the theatrical world complete, the private person restored',
    ],
  },

  environmentPools: {
    wake: [
      'luxury hotel suite in show city in morning light',
      'model hotel room before the backstage preparation',
      'private hotel interior in warm morning before the angel world begins',
      'luxury hotel suite in show city — white linen, warm morning light, the runway still many hours ahead',
      'model hotel room in the quiet before the theatrical day — private and warm before the backstage world opens',
      'hotel suite morning in show-city — the wings and diamonds not yet present, the private morning complete',
    ],
    morning_refresh: [
      'luxury hotel bathroom in pre-show morning',
      'warm hotel bathroom ritual before the backstage world',
      'private hotel bathroom before the angel transformation',
      'hotel bathroom in clean pre-show morning — luxury surfaces, warm light, the model before the angel',
      'luxury hotel bathroom ritual in show morning — the private preparation before the theatrical preparation',
      'warm hotel bathroom in show city — the last private self-care before the backstage team takes over',
    ],
    getting_dressed: [
      'backstage dressing room with wings and diamonds being assembled',
      'angel lingerie and diamond fitting room with runway energy',
      'the transformation space where the complete angel look is created',
      'backstage dressing room with wings hanging above and diamonds on the dressing table — the transformation space',
      'the dressing room at full theatrical energy — wings, diamond bra, luxury lingerie, the team working',
      'the angel fitting room — wings spread for adjustment, diamonds being placed, the most theatrical fashion space',
    ],
    breakfast: [
      'hotel suite breakfast setting in show morning',
      'model hotel room meal before the backstage preparation',
      'private hotel luxury before the angel runway day',
      'hotel suite breakfast corner in show morning — clean, private, warm before the theatrical day',
      'model morning hotel room breakfast — the calm private space before backstage and the transformation',
      'luxury hotel suite in show city at breakfast — the private morning before the most theatrical fashion day',
    ],
    late_morning: [
      'backstage preparation area with other angels getting ready',
      'editorial studio with professional lighting and angel look',
      'pre-show backstage environment in full preparation energy',
      'backstage with other angels — hair, makeup, preparation energy building around her in the most theatrical space',
      'editorial studio under professional light with the angel look assembling piece by piece',
      'pre-show backstage preparation environment — the most beautiful transformation factory before the runway',
    ],
    lunch: [
      'backstage area in midday preparation energy',
      'angel suite or hotel room lunch before the full transformation',
      'backstage or model suite midday in show preparation',
      'backstage midday — calm between preparation stages, the dressing room ahead',
      'hotel suite or backstage area at midday in show day — the transformation not yet complete',
      'the angel midday environment — backstage or suite, between the morning preparation and the afternoon peak',
    ],
    afternoon: [
      'backstage dressing room in full transformation — wings, diamonds, complete',
      'the most theatrical transformation space before the show',
      'complete angel dressing room in full preparation',
      'backstage dressing room at full afternoon transformation — wings on, diamonds fastened, look complete assembling',
      'the dressing room in the most theatrical fashion afternoon on earth — wings everywhere, diamonds on surfaces, angels',
      'complete transformation environment — wings fitting, diamond bra on skin, hair done, the full angel assembling',
    ],
    reset: [
      'dressing room in complete angel look one final time before the corridor',
      'wings and diamonds and the mirror before the walk',
      'the final pre-runway dressing room moment',
      'the dressing room with the complete angel look — the mirror showing the full wings and diamond look ready',
      'final dressing room moment — the look complete, the mirror check done, the corridor waiting',
      'the pre-corridor dressing room in full angel look — the most charged fashion space before the walk',
    ],
    golden_hour: [
      'pre-show corridor in complete wings and diamond angel look',
      'the backstage corridor before the runway cameras',
      'the angel at the threshold between backstage and runway in full look',
      'the pre-show corridor with the angel in complete look — wings spread, diamonds on, the runway ahead',
      'backstage corridor in warm pre-show light — the most theatrical pre-runway fashion environment on earth',
      'the corridor between backstage and runway — complete angel look, warm theatrical light, the walk imminent',
    ],
    dinner: [
      'the runway in wings and luxury lingerie under the most dramatic show lighting',
      'editorial studio in wings and diamonds in professional editorial light',
      'the most powerful fashion environment — angel on the runway or in the studio',
      'the runway — stage light, the most famous walk in fashion, wings in motion, diamonds in show light',
      'editorial studio in complete angel look under dramatic professional light — the most theatrical fashion photograph',
      'the runway at full show energy — dramatic lighting, the angel in wings and diamond lingerie at peak walk',
    ],
    evening: [
      'luxury after-party venue post-show in glamorous setting',
      'the celebration space after the most famous lingerie walk',
      'post-runway luxury social setting in show city evening',
      'luxury after-party venue in show city evening — the angel post-runway in the glamorous celebration space',
      'the most exclusive after-party — warm, golden, the show complete, the celebration in full momentum',
      'post-show luxury venue in show city — the angel at the after-party in the most glamorous evening setting',
    ],
    night: [
      'private hotel suite after the show — wings removed, at rest',
      'luxury hotel night after the runway day',
      'private hotel interior in warm night after the angel world is complete',
      'hotel suite private night after the show — the wings off, the model restored, warm and private',
      'luxury hotel at night after the runway — the theatrical world complete, the private person in quiet ease',
      'private show-city hotel suite at night — the most theatrical fashion day complete, the angel at rest',
    ],
  },

  moodPools: {
    wake: [
      'private luxury model morning before the show',
      'the angel at private rest before the most powerful day',
      'hotel suite morning ease before everything begins',
      'the private human before the theatrical identity — warm hotel morning before the show world takes over',
      'the model in quiet luxury before the angel begins — the most private and calm moment of the show day',
      'hotel morning ease before the backstage transformation — the angel identity not yet activated',
    ],
    morning_refresh: [
      'preparation beginning — the angel building toward the runway',
      'pre-show morning self-care ritual energy',
      'the private beauty ritual before the public transformation',
      'the private self-care energy before the theatrical day — building the face before the show face begins',
      'clean morning preparation energy — the model in private before the team and the backstage world',
      'the morning ritual that precedes the transformation — precise, private, the angel not yet present',
    ],
    getting_dressed: [
      'the theatrical transformation — wings and diamonds being assembled',
      'the most powerful dressing ritual in fashion',
      'the angel becoming in the backstage dressing room',
      'wings being placed — the most theatrical physical fashion transformation in the world',
      'the diamond weight on skin in the dressing room — the angel identity assembling piece by piece',
      'the transformation energy — from model to angel in the dressing room with wings and diamonds and silk',
    ],
    breakfast: [
      'model morning fuel before the show energy builds',
      'private luxury model morning ease before backstage',
      'the angel before the show — private and composed',
      'the calm model morning before the theatrical day — private ease in hotel luxury before backstage begins',
      'fuel and composure before the runway — the angel private and warm in the morning hotel setting',
      'the show morning private energy — collected and quiet before the theatrical world takes over',
    ],
    late_morning: [
      'backstage building energy — preparation and beauty',
      'the angel transformation building in professional backstage',
      'editorial studio energy with wings and editorial preparation',
      'the backstage energy building — preparation becoming theatrical, the angel identity assembling in real time',
      'professional backstage preparation energy — controlled, focused, the transformation in progress',
      'editorial studio preparation building — the angel look assembling under professional light with intent',
    ],
    lunch: [
      'midday calm before the complete angel transformation',
      'backstage ease before the full preparation peak',
      'the angel gathering energy before the runway moment',
      'the midday calm in the backstage world — between preparation stages, the wings still ahead',
      'pre-transformation midday ease — the model collecting before the most theatrical afternoon in fashion',
      'the angel midday energy — composed and gathering before the wings and the complete look',
    ],
    afternoon: [
      'the complete transformation — the most theatrical beautiful moment',
      'wings, diamonds, and the complete angel look assembled',
      'the dressing room at its most powerful — the angel complete',
      'the transformation energy at peak — the wings on, the diamonds fastened, the complete angel identity real',
      'the most theatrical fashion afternoon energy — the dressing room at full transformation power',
      'the angel complete and standing — wings, diamond lingerie, the most theatrical fashion identity fully assembled',
    ],
    reset: [
      'the final pre-runway moment — composed, complete, ready',
      'the angel before the walk in wings and full look',
      'the most powerful pre-show dressing room energy',
      'the final composure before the most famous walk — complete, ready, the dressing room behind',
      'the pre-corridor complete angel energy — the most charged fashion moment before the runway',
      'composed and complete in the final dressing room moment — the walk imminent, the look perfect',
    ],
    golden_hour: [
      'the pre-show corridor — the angel at maximum power before the cameras',
      'wings and diamonds and the walk ahead — the most theatrical moment',
      'the corridor before the runway — the most electric fashion energy',
      'the corridor energy — wings spread, complete, the runway doors ahead, the most electric pre-show moment',
      'the angel in the corridor at peak theatrical power — the show is beginning and she is about to walk',
      'the most electric fashion energy in the world — the pre-show corridor with the complete angel about to walk',
    ],
    dinner: [
      'the runway — the most powerful fashion energy on earth',
      'the angel on the runway or in editorial — the complete theatrical peak',
      'wings, diamonds, and the walk — the defining fashion editorial moment',
      'the runway at full theatrical power — the walk, the wings, the light, the most iconic fashion moment',
      'the editorial studio angel at peak — the complete theatrical fashion identity under the most beautiful light',
      'the defining fashion moment — the angel on the runway or in editorial at the most complete theatrical power',
    ],
    evening: [
      'post-show luxury celebration — the angel after the runway',
      'glamorous after-party energy after the most famous walk',
      'the fashion night continuing in luxury after the runway',
      'post-show glamour energy — the walk complete, the celebration beginning, still beautiful and alive',
      'the after-party luxury energy — champagne and warmth and the glow of the runway still present',
      'post-runway celebration — the angel in glamorous ease after the most powerful fashion moment',
    ],
    night: [
      'private hotel suite after the show — the angel at private rest',
      'the luxury private night after the most powerful fashion day',
      'the angel complete and private after the runway world',
      'the most private moment of the show day — the wings off, the angel identity at rest in hotel luxury',
      'private hotel quiet after the theatrical world is complete — the model before the angel returned',
      'the warm private hotel night after the runway — the show day complete, the private person restored',
    ],
  },

  cameraPools: {
    wake: [
      '85mm low angle in hotel suite, warm morning window dissolved behind',
      '135mm close-up at face height, warm hotel morning light defining edge',
      '85mm f/1.4 — hotel suite morning low angle, warm window light dissolved behind in warm bokeh',
      '135mm f/2 — tight morning face close, warm hotel curtain light defining the edge in soft warmth',
      '50mm f/2 — hotel suite medium, white linen sharp, warm morning window as background light source',
      '35mm f/2 — hotel suite environmental morning, full room visible with warm window light behind subject',
    ],
    morning_refresh: [
      '85mm hotel bathroom mirror close, reflection at same focal plane',
      '50mm hotel bathroom mid shot, warm morning light compressing behind',
      '135mm f/2 — hotel bathroom tight, subject and reflection both sharp at same focal plane',
      '85mm f/1.8 — hotel bathroom medium, warm morning light from window compressing behind subject',
      '50mm f/2.8 — hotel bathroom wide, the full luxury bathroom visible as clean private morning setting',
      '35mm f/2 — hotel bathroom environmental, warm pre-show morning light defining the private self-care space',
    ],
    getting_dressed: [
      '50mm dressing room framing, wings and diamonds visible behind in warm light',
      '85mm transformation mid-length angle, dressing room depth behind',
      '135mm f/2 — diamond detail close-up in dressing room, warm theatrical light on the detail',
      '85mm f/1.4 — transformation medium, wings visible behind and in peripheral frame, diamonds on skin',
      '50mm f/2 — dressing room wide, full wings and diamonds visible as theatrical background environment',
      '35mm f/2 — dressing room environmental, the full transformation space with wings and team visible around',
    ],
    breakfast: [
      '24mm wide hotel suite breakfast, show-city morning window in background',
      '85mm hotel suite breakfast framing, morning dissolved behind',
      '85mm f/1.4 — hotel suite breakfast portrait, warm morning dissolved behind, clean hotel interior around',
      '135mm f/2 — breakfast close-up, hotel interior compressed, warm morning light as background source',
      '50mm f/2 — hotel suite breakfast medium, show-city morning window visible as background element',
      '35mm f/2.8 — hotel suite wide breakfast, full private morning interior visible before the show world',
    ],
    late_morning: [
      '85mm backstage medium, preparation energy behind subject',
      '50mm editorial studio with professional light and angel editorial detail',
      '85mm f/1.8 — backstage preparation medium, other angels visible blurred behind in preparation energy',
      '135mm f/2 — editorial studio close in partial angel look, professional light on beauty detail',
      '50mm f/2 — backstage wide, the full preparation environment visible with team working around her',
      '35mm f/2.8 — editorial studio environmental, professional lighting and angel look assembling visible',
    ],
    lunch: [
      '85mm backstage or suite lunch, preparation energy soft behind subject',
      '50mm angel suite lunch framing, hotel or backstage depth behind',
      '85mm f/1.4 — backstage lunch portrait, preparation environment dissolved behind in warm backstage light',
      '135mm f/2 — quiet backstage lunch close, the transformation space soft behind the midday meal',
      '50mm f/2 — hotel suite lunch medium, warm private interior before backstage returns',
      '35mm f/2 — backstage or suite lunch wide, the midday calm in the preparation environment visible',
    ],
    afternoon: [
      '85mm dressing room transformation, wings visible in full background',
      '50mm complete angel look framing, dressing room detail behind subject',
      '135mm f/2 — complete transformation close, diamonds and lingerie at full detail, wings visible at edges',
      '85mm f/1.4 — full angel look medium, wings in background, diamonds sharp on skin in warm dressing room light',
      '50mm f/2 — dressing room wide in full transformation, the complete angel look visible against the theatrical space',
      '35mm f/2 — transformation environmental, the full dressing room with wings fitted and angel complete visible',
    ],
    reset: [
      '135mm dressing room close in complete angel look, wings in warm background',
      '85mm final pre-runway look — wings and diamonds at full editorial beauty',
      '135mm f/2 — complete angel look tight close, diamonds sharp, wings visible at warm background',
      '85mm f/1.4 — final dressing room portrait in complete look, wings dissolved behind in warm theatrical bokeh',
      '50mm f/2 — final look medium, the complete angel at the mirror in warm pre-corridor light',
      '35mm f/2 — final dressing room wide, the complete angel look in full theatrical space before the corridor',
    ],
    golden_hour: [
      '135mm corridor pre-show close, warm backlight defining edge in wings and diamond',
      '85mm dramatic corridor angel medium, show light behind in warm glow',
      '135mm f/2 — corridor close-up, warm pre-show light as backlight, wings at edge of frame defining angel look',
      '85mm f/1.4 — corridor medium, dramatic warm show light from behind, wings and diamonds at maximum editorial',
      '50mm f/2 — corridor wide, full wings spread visible in pre-show warm light, runway doors in soft background',
      '35mm f/2 — corridor environmental, the complete angel look in full theatrical pre-show space',
    ],
    dinner: [
      '85mm runway dramatic medium, runway lights creating epic glow behind',
      '50mm editorial studio angel, professional editorial light filling background',
      '135mm f/2 — runway close, dramatic show lighting as backlight, wings and diamonds at full editorial power',
      '85mm f/1.4 — runway medium, the walk in full light, wings spread, show lighting creating epic background',
      '50mm f/2 — editorial studio medium, professional fill and dramatic key on complete angel look',
      '35mm f/2.8 — runway wide, full show environment, the angel walking in complete look under show lights',
    ],
    evening: [
      '85mm after-party medium, warm luxury venue ambient behind subject',
      '50mm after-party interior, warm golden post-show ambient depth behind',
      '85mm f/1.4 — after-party portrait, warm luxury venue ambient dissolved behind in golden bokeh',
      '135mm f/2 — after-party close, warm post-show glow as background, champagne visible in frame',
      '50mm f/2 — after-party medium, warm luxury venue visible as post-show celebration environment',
      '35mm f/2 — after-party wide, the full luxury post-show venue visible in warm golden ambient',
    ],
    night: [
      '135mm hotel suite night close, warm private lamp as sole source',
      '85mm soft side angle, warm hotel room dissolved behind subject',
      '135mm f/2 — hotel suite night tight, single warm lamp key, the most private post-show moment',
      '85mm f/1.4 — hotel night portrait, warm single lamp, private suite dissolved behind in soft warmth',
      '50mm f/2 — hotel suite night medium, warm private interior, the theatrical world complete and quiet',
      '35mm f/1.8 — hotel suite night wide, full warm private room visible after the theatrical day is done',
    ],
  },

  lightingPools: {
    wake: [
      'warm 4800K hotel morning through curtains, soft shadows across white linen',
      'pale warm hotel morning entering through hotel glass — soft and private',
      '4600K warm hotel suite morning — the curtained window giving soft directional fill on white linen',
      'pale 5000K hotel morning entering the show city suite — clean and private, the theatrical day not yet begun',
      'warm diffuse 4800K through hotel curtains — the most private pre-show morning light on the angel at rest',
      'soft 4600K hotel morning — warm and flattering on the model face before the transformation begins',
    ],
    morning_refresh: [
      'clean 5400K hotel bathroom mirror light, precise and warm',
      'hotel bathroom warm morning light — flattering and clean',
      '5200K clean hotel bathroom morning — bilateral mirror light, precise and flattering on clean skin',
      'warm 5400K hotel bathroom in pre-show morning — bright and clean, the private ritual in professional light',
      'precise 5600K hotel mirror light — clean and flattering, the pre-show preparation in the best morning light',
      'clean bilateral 5200K hotel bathroom light — even and warm, the model face in private pre-show ritual',
    ],
    getting_dressed: [
      'warm 4000K dressing room light — flattering and theatrical',
      'backstage warm dressing room lighting on wings and diamond detail',
      '3800K warm backstage dressing room — the most flattering transformation light on diamonds and skin',
      'warm theatrical 4000K in the dressing room — the wings and diamonds lit at their most beautiful',
      'backstage dressing room warm amber 3800K — the transformation light, the most flattering for lingerie and diamonds',
      '4200K warm dressing room key — the theatrical transformation light that makes the angel look complete',
    ],
    breakfast: [
      'warm 5000K hotel suite morning, clean city light beyond window',
      'warm hotel morning breakfast light — private and clean',
      '4800K warm hotel suite breakfast morning — the city light beyond the window as backlight',
      'clean 5000K hotel morning at the suite breakfast table — the private pre-show fuel in warm hotel light',
      'warm 4800K hotel suite — clean morning fill from the window, the breakfast table in private pre-show light',
      'hotel suite breakfast at 5000K — warm, private, the theatrical day not yet present in the room',
    ],
    late_morning: [
      '5000K professional backstage or studio preparation light — controlled and precise',
      'editorial studio professional fill light in preparation',
      '5200K professional backstage preparation light — controlled and even, the transformation in precision light',
      'editorial studio 5000K professional fill — the angel look being assembled in the best editorial preparation light',
      'backstage professional 5000K — clean and controlled, the transformation visible in precise professional light',
      '5400K editorial studio preparation — professional fill on the angel look assembling, precise and editorial',
    ],
    lunch: [
      'warm 4200K backstage or suite midday, soft ambient fill',
      'midday preparation ambient in backstage or hotel suite',
      '4000K warm backstage midday — the preparation space in soft ambient before the transformation peak',
      'hotel suite 4400K midday — warm private interior before returning to backstage preparation',
      'soft 4200K backstage midday ambient — the calm between preparation stages in warm theatrical space',
      'warm 4000K suite or backstage midday — the preparation day paused in warm ambient ease',
    ],
    afternoon: [
      'warm 3800K dressing room transformation — theatrical and flattering on wings and diamonds',
      'backstage warm amber transformation light in dressing room',
      '3600K warm amber dressing room — the most theatrical and flattering light for wings and diamonds',
      'warm backstage 3800K — the transformation light at peak, the diamonds and wings in the most beautiful warmth',
      'theatrical amber 3600K in the dressing room at transformation peak — the angel look in the most beautiful light',
      'warm 4000K dressing room transformation at peak — flattering, theatrical, and powerful on the complete angel',
    ],
    reset: [
      'warm 3500K dressing room before the walk — most flattering final preparation light',
      'warm amber dressing room in complete angel look before the corridor',
      '3400K warm dressing room final light — the most flattering pre-runway light on the complete angel look',
      'warm 3500K before the corridor — amber dressing room in the final moment, the look complete in the best light',
      'theatrical 3400K final dressing room — warm, flattering, the wings and diamonds in the best possible light',
      'pre-corridor amber 3600K — the final dressing room light on the complete angel before the walk',
    ],
    golden_hour: [
      'dramatic 2800K corridor warm light before the runway — the most powerful pre-show light',
      'amber backstage corridor at pre-show — warm and theatrical',
      '2600K warm amber corridor light — the pre-show theatrical atmosphere at its most dramatic before the walk',
      'dramatic backstage corridor 2800K — the warm amber light that precedes the runway, theatrical and powerful',
      'warm 2800K pre-show corridor — the most charged pre-runway light in fashion, amber and theatrical',
      '2600K amber corridor before the runway — the defining pre-show light, warm and electrifying',
    ],
    dinner: [
      'dramatic show lighting — 4000K front fill with 2800K warm side, full runway theatrical',
      'editorial studio professional key light with warm dramatic fill on angel look',
      'runway show lighting — dramatic front fill at 4000K with warm amber side from show rigs, full theatrical',
      '5000K professional key with warm 2800K fill on wings and diamonds — the most editorial angel lighting',
      'show lighting full theatrical — the runway lights creating the most powerful fashion light on the angel',
      'editorial studio dramatic key with warm fill — the complete angel look under the most beautiful editorial light',
    ],
    evening: [
      'warm 2800K after-party luxury venue ambient — celebration and gold',
      'post-show after-party warm low ambient with celebration energy',
      '2600K warm after-party ambient — the luxury venue in golden low light, the celebration warm and golden',
      'warm 2800K after-party low key — golden luxury venue light in the post-show celebration',
      '2600K post-show celebration warm — golden amber at the after-party, the most warm and beautiful',
      'after-party luxury venue 2800K — warm golden ambient in the post-runway celebration, intimate and beautiful',
    ],
    night: [
      'single warm 2200K hotel lamp, soft private suite after the show',
      'low warm 2400K hotel room night — private and quiet after the runway',
      '2200K single hotel lamp — the most private post-show light, warm and quiet in the suite',
      'warm 2400K hotel suite night — single source, the theatrical world complete, the private person in warm ease',
      '2200K warm private suite — single warm lamp, the most private and quiet light after the most theatrical day',
      'hotel suite private night at 2200K — warm, single, the show done and the private person in warm light',
    ],
  },

  stylingPools: {
    wardrobe: {
      wake: [
        'hotel silk or minimal in suite morning',
        'model morning hotel luxury before the show',
        'private silk or nothing in warm hotel morning',
        'white hotel linen or silk slip in suite morning — the angel before the look, the most private version',
        'minimal warm hotel morning wear — the model private before the wings and diamonds arrive',
        'nothing or white silk in the hotel suite morning — the human before the theatrical identity',
      ],
      morning_refresh: [
        'hotel robe or towel in morning bathroom',
        'pre-show white towel and minimal morning styling',
        'model morning private before backstage',
        'white luxury hotel robe in the bathroom morning — the pre-show private self-care ritual',
        'white towel wrap after hotel shower — the model bare and private before the transformation begins',
        'hotel robe or nothing in the luxury bathroom — the most private pre-show morning styling',
      ],
      getting_dressed: [
        'first fitting — the angel lingerie and bra being placed on',
        'the initial trying-on of the complete angel look in dressing room',
        'wings being adjusted in dressing room fitting',
        'the luxury lingerie bra on skin for the first fitting — the angel look beginning in the dressing room',
        'wings placed on back in the dressing room fitting — the most theatrical fashion accessory being assembled',
        'the complete fitting — silk lingerie, diamond bra, wings fitted — the angel look coming together',
      ],
      breakfast: [
        'hotel robe or minimal model morning at suite table',
        'model morning suit or casual pre-show at hotel',
        'the angel private morning look before backstage',
        'casual minimal at the hotel breakfast — the model private before backstage in simple hotel morning',
        'hotel robe or simple morning at the suite table — the angel private before the theatrical day',
        'the most private breakfast styling — before the show, before the makeup, before the wings',
      ],
      late_morning: [
        'editorial or show prep look — beginning the transformation in backstage',
        'backstage robe or partial styling during preparation',
        'beginning to assemble the complete angel look in preparation',
        'backstage robe during hair and makeup — the transformation in progress, partial angel',
        'partial preparation look — the angel in assembly, the wings and diamonds not yet on',
        'the backstage preparation look — between model and angel, the transformation building',
      ],
      lunch: [
        'backstage model midday — partial preparation or hotel casual',
        'the angel midday between preparation stages',
        'backstage or hotel midday comfort before the transformation peak',
        'backstage midday partial look — between preparation stages, still becoming the angel',
        'the model at midday in backstage — casual comfort before the full transformation peak begins',
        'hotel or backstage casual at lunch — the theatrical transformation still ahead',
      ],
      afternoon: [
        'complete angel look assembling — wings, diamonds, luxury lingerie',
        'the angel transformation at peak — wings on, complete',
        'full editorial angel look in backstage dressing room',
        'the complete angel look — wings fully fitted, diamond bra on, silk lingerie, the transformation done',
        'wings, diamond bra, luxury lingerie, and heels — the complete angel editorial look in the dressing room',
        'the most theatrical fashion look assembled — wings on, diamonds on, the angel complete and standing',
      ],
      reset: [
        'complete angel look — wings, diamond bra or lingerie, complete',
        'the final angel look before the corridor and runway',
        'the most complete and theatrical angel styling moment',
        'the complete final angel look at the dressing room mirror — wings adjusted, diamonds checked, ready',
        'wings at full span, diamond bra fastened, silk lingerie complete — the angel before the walk',
        'the most theatrical fashion look on earth — complete, standing, ready for the corridor and the cameras',
      ],
      golden_hour: [
        'complete angel look in the corridor — wings, diamonds, full runway ready',
        'the angel at maximum editorial beauty before the walk',
        'wings, diamond lingerie, and the complete angel styling in the corridor',
        'the corridor angel look — wings spread, diamonds at full detail, the most complete theatrical fashion moment',
        'wings, diamond bra, luxury lingerie — the complete angel in the corridor before the runway',
        'the pre-walk corridor look at full theatrical peak — wings, diamonds, and the angel complete',
      ],
      dinner: [
        'the runway angel look — wings, diamond bra, fantasy lingerie, complete show styling',
        'editorial studio complete angel look — the most theatrical and beautiful fashion moment',
        'the angel on the runway or in studio — the most complete editorial moment',
        'the full show look — wings spread on the runway, diamond bra, silk lingerie, the complete angel in motion',
        'the editorial studio complete angel — wings at full span, diamonds on skin, the most beautiful fashion editorial',
        'the runway angel at peak — the most theatrical and complete fashion look on the most famous stage',
      ],
      evening: [
        'post-show after-party look — transitioned from runway to evening glamour',
        'the angel after the show — slightly softened but still glamorous',
        'after-party fashion look after the runway',
        'after-party transition look — wings removed, the glamour maintained, the show evening in full warmth',
        'post-runway after-party styling — still theatrical but softened, the angel in celebration mode',
        'the show evening look at the after-party — beautiful and warm, the runway complete',
      ],
      night: [
        'private hotel suite night — the wings are off, private silk or nothing',
        'the angel private after-show look in hotel suite',
        'private night after the runway — the most private state',
        'white silk or nothing in the hotel suite after the show — the wings off, the private person restored',
        'hotel night minimal — the angel identity at rest, the model in private warm luxury',
        'the most private post-show styling — warm hotel night, the theatrical world complete',
      ],
    },
    details: {
      wake: ['hotel pillow hair in morning', 'bare natural model skin in morning', 'private morning before the glamour begins'],
      morning_refresh: ['clean face being prepared for the show transformation', 'model natural morning before backstage begins', 'pre-show clean skin and natural hair'],
      getting_dressed: ['diamond detail being placed', 'wings being adjusted — the most theatrical dressing detail', 'the complete angel look detail being assembled piece by piece'],
      breakfast: ['natural model morning detail at hotel table', 'casual pre-show hotel morning accessory detail', 'model morning before backstage preparation'],
      late_morning: ['backstage beauty transformation beginning — hair, lashes, body detail', 'editorial preparation building beauty detail', 'early beauty preparation in backstage environment'],
      lunch: ['backstage partial preparation detail', 'model midday between preparation stages', 'preparation building in backstage or suite midday'],
      afternoon: ['wings fitted — the most theatrical preparation detail', 'diamond lingerie and bra on skin in dressing room', 'complete angel transformation detail — wings, diamonds, complete'],
      reset: ['final wings adjustment — the most important final detail', 'complete angel look check at the dressing room mirror', 'the last detail check before the corridor'],
      golden_hour: ['wings spread in the corridor — the most powerful fashion editorial detail', 'diamonds and wings in warm pre-show light', 'complete angel look at maximum theatrical detail'],
      dinner: ['the runway angel look at full theatrical detail — wings, diamonds, fantasy lingerie', 'editorial studio angel detail in professional light', 'the most complete theatrical fashion detail — on the runway or in editorial'],
      evening: ['after-party glamour detail transition from runway', 'post-show celebration styling detail', 'the angel after the runway — glamorous and elevated'],
      night: ['wings removed — the most private detail', 'hotel private night silk or nothing detail', 'the angel at rest — no wings, private and warm'],
    },
    changeMoments: {
      wake: ['hotel morning private state — before the angel begins', 'private model morning before the show'],
      morning_refresh: ['between hotel and backstage — in the morning transition', 'pre-backstage model morning ritual'],
      getting_dressed: ['the first fitting — becoming the angel', 'the dressing room transformation beginning'],
      breakfast: ['model hotel morning casual before the show world', 'private morning ease before the runway day'],
      late_morning: ['backstage partial preparation — between model and angel', 'the transformation building in backstage'],
      lunch: ['midday between preparation stages', 'the angel midday in partial backstage look'],
      afternoon: ['complete angel transformation — the moment of becoming fully', 'wings on and complete — the angel is ready'],
      reset: ['the final complete look check — angel at maximum', 'the complete angel before the corridor'],
      golden_hour: ['the complete angel in the corridor — the defining transition moment', 'wings and diamonds in the pre-show corridor'],
      dinner: ['the runway angel — the most complete editorial fashion moment', 'fully the angel on the runway or in studio'],
      evening: ['transitioning from runway angel to after-party glamour', 'the angel after the show in post-runway setting'],
      night: ['the angel private after the show — wings off, private again', 'private hotel night — the model beneath the angel'],
    },
  },

  sensoryPools: {
    wake: ['warm hotel silk in private morning before the show', 'the quiet luxury of a model hotel before the show world begins', 'private warm hotel before the most theatrical day'],
    morning_refresh: ['warm hotel bathroom morning ritual pre-show', 'clean skin and fresh energy before the backstage world', 'the private morning self-care before the theatrical transformation'],
    getting_dressed: ['wings being placed on — the physical sensation of the most theatrical fashion accessory', 'diamond weight on skin in the dressing room', 'silk and lace and diamond in the dressing room transformation'],
    breakfast: ['hotel morning meal — calm fuel before the runway energy', 'private model hotel suite in the morning before everything', 'warm hotel breakfast before backstage begins'],
    late_morning: ['backstage energy building around her — beauty, preparation, angel energy', 'the editorial studio professional light on the angel look', 'backstage sound and movement as the preparation builds'],
    lunch: ['backstage midday calm before the peak preparation', 'the angel gathering before the transformation peak', 'model midday in backstage or suite before the wings'],
    afternoon: ['the weight and drama of wings being fitted', 'diamonds on skin in the warm dressing room', 'the complete theatrical transformation — the most sensory intense fashion moment'],
    reset: ['the complete angel look — wings spread, diamonds on, the final sensory check', 'the mirror check in complete angel look before the walk', 'the corridor anticipation before the most famous walk in fashion'],
    golden_hour: ['the corridor — the sound of the show about to begin beyond the doors', 'wings spread in the warm pre-show corridor light', 'the most theatrical pre-runway sensory moment in fashion'],
    dinner: ['the runway — stage light, sound, the walk, wings in motion', 'the editorial studio — professional light, direction, and the angel look at peak', 'the most theatrical and alive sensory moment of the fashion day'],
    evening: ['after-party celebration — champagne, music, and the warm glow post-runway', 'the angel post-show in luxury celebration setting', 'after-party luxury sensory after the runway'],
    night: ['private hotel suite after — wings off, warm silk, total private quiet', 'the model private after the angel world — warm and at rest', 'hotel night after the most theatrical day — warm and complete'],
  },

  socialEnergyPools: {
    wake: ['completely private hotel model morning', 'the angel before the show — private and composed'],
    morning_refresh: ['private morning self-care before the backstage', 'the model alone in bathroom before the transformation'],
    getting_dressed: ['backstage social energy — angels and beauty team together', 'the transformation in the social backstage environment'],
    breakfast: ['private hotel morning before the backstage world begins', 'the model private before the show energy'],
    late_morning: ['backstage social preparation energy — controlled and building', 'editorial studio professional energy with team'],
    lunch: ['midday ease in backstage or suite social energy', 'the model before the peak preparation in social ease'],
    afternoon: ['backstage transformation energy — focused professional creative social', 'the dressing room at full theatrical social energy'],
    reset: ['focused solo final preparation in the dressing room', 'the angel alone with the mirror before the corridor'],
    golden_hour: ['the corridor — the most theatrical charged social energy before the walk', 'the angel visible to all before the runway begins'],
    dinner: ['the runway — fully public, the most visible moment in fashion', 'editorial studio professional focused creative social energy'],
    evening: ['after-party luxury social celebration energy post-show', 'the angel socializing in luxury after the runway'],
    night: ['private hotel quiet after the show', 'the model alone again after the theatrical public day'],
  },

  atmospherePools: {
    wake: ['warm private hotel model morning before the show', 'the angel world beginning slowly in luxury morning', 'hotel suite quiet before the theatrical day'],
    morning_refresh: ['pre-show morning ritual atmosphere in warm hotel', 'private self-care atmosphere before backstage begins', 'model morning private before the transformation'],
    getting_dressed: ['backstage dressing room atmosphere — theatrical, warm, creative', 'the transformation space atmosphere — wings and diamonds and beauty', 'the most theatrical fashion atmosphere — angel dressing room'],
    breakfast: ['hotel suite model morning atmosphere before the show', 'private luxury hotel morning before backstage', 'warm hotel morning atmosphere before the angel world'],
    late_morning: ['backstage preparation atmosphere building toward the show', 'editorial studio professional creative atmosphere', 'backstage growing energy before the runway'],
    lunch: ['backstage midday ease before the theatrical peak', 'midday model atmosphere between preparation stages', 'calm before the storm of the complete angel preparation'],
    afternoon: ['backstage dressing room at full theatrical transformation atmosphere', 'the complete angel transformation atmosphere — the most theatrical fashion moment', 'wings, diamonds, and beauty — the peak dressing room atmosphere'],
    reset: ['final pre-runway dressing room atmosphere — complete and powerful', 'the angel at maximum theatrical beauty before the corridor', 'the most charged pre-show dressing room atmosphere'],
    golden_hour: ['pre-show corridor atmosphere — the most electric pre-runway fashion energy', 'wings spread in the corridor before the show — the most theatrical atmosphere', 'the show about to begin atmosphere — maximum theatrical tension and beauty'],
    dinner: ['the runway show atmosphere — the most theatrical fashion environment on earth', 'editorial studio professional creative atmosphere with angel complete', 'the defining fashion theatrical atmosphere — runway lights and angel wings'],
    evening: ['post-show luxury celebration atmosphere in after-party', 'the angel after the runway in luxury social celebration', 'after-party glamorous fashion atmosphere'],
    night: ['private hotel quiet after the theatrical day', 'warm hotel luxury private night after the show', 'the angel at private rest — the theatrical world complete'],
  },

  propPools: {
    wake: ['luxury hotel bedding and white linen in morning', 'hotel suite morning light detail', 'model private hotel morning props'],
    morning_refresh: ['hotel bathroom products and warm morning ritual', 'luxury pre-show hotel bathroom detail', 'model morning hotel bathroom props'],
    getting_dressed: ['wings being assembled in dressing room', 'diamond bra and lingerie in dressing room fitting', 'dressing room mirror and beauty team detail'],
    breakfast: ['hotel suite breakfast tray in model morning', 'coffee or juice in hotel suite before backstage', 'model hotel morning meal props'],
    late_morning: ['backstage beauty chairs and preparation tools', 'editorial studio lighting equipment and angel styling', 'backstage preparation detail props'],
    lunch: ['backstage or hotel suite meal props', 'model midday in preparation environment', 'angel preparation midday props'],
    afternoon: ['wings in full fitting in dressing room', 'diamond lingerie on skin in dressing room fitting', 'complete transformation dressing room props'],
    reset: ['wings fully fitted at dressing room mirror', 'the angel in complete look at the mirror', 'final pre-runway dressing room props'],
    golden_hour: ['wings spread in the pre-show corridor', 'diamonds in warm corridor pre-show light', 'the complete angel look in the corridor before the walk'],
    dinner: ['runway stage lighting and the angel walk', 'editorial studio professional equipment and angel complete look', 'the defining fashion prop — wings on the runway or in studio'],
    evening: ['after-party champagne and luxury venue detail', 'post-show celebration props in luxury setting', 'angel after-party glamour props'],
    night: ['hotel suite after the show — wings removed, private', 'luxury hotel night detail after the runway', 'the angel private hotel night props'],
  },

  bodyLanguagePools: {
    wake: ['slow warm hotel morning posture in luxury bed', 'model morning hotel ease before the theatrical day', 'private morning body language before the show'],
    morning_refresh: ['composed hotel bathroom morning ritual posture', 'pre-show morning self-care body language', 'the model private morning in hotel bathroom'],
    getting_dressed: ['the theatrical fitting posture — wings being placed and adjusted', 'deliberate angel transformation body language in dressing room', 'the most theatrical fashion body language — wings and diamond fitting'],
    breakfast: ['relaxed hotel suite morning body language before the show', 'model hotel breakfast posture — calm and composed', 'private hotel morning body ease before backstage'],
    late_morning: ['backstage preparation posture — beauty team at work around her', 'editorial studio preparation posture — composed and ready', 'building toward the complete angel transformation body language'],
    lunch: ['midday backstage ease in preparation body language', 'the model between transformation stages — at ease', 'angel midday calm before the theatrical peak'],
    afternoon: ['the transformation body language — wings on, standing, the angel fully', 'theatrical full angel complete posture in dressing room', 'wings spread in dressing room — the most theatrical posture'],
    reset: ['complete angel posture — full look, composed, the walk ahead', 'the angel before the runway — the most composed theatrical posture', 'final dressing room mirror assessment in complete angel look'],
    golden_hour: ['wings spread in the corridor — the most powerful angel posture', 'the complete angel in the corridor before the cameras', 'the runway walk posture beginning — wings, diamonds, ready'],
    dinner: ['the runway walk — the most iconic fashion posture on earth', 'editorial studio angel posture — theatrical and editorial in professional light', 'the angel on the runway — wings, walk, complete body language'],
    evening: ['post-show after-party relaxed glamour posture', 'the angel after the runway — slightly softened, still glamorous', 'after-party fashion body language in luxury celebration'],
    night: ['private hotel suite after the show — the most natural quiet body language', 'the model at private rest after the theatrical day — composed and warm', 'hotel private night body language — quiet and complete'],
  },

  facialExpressionPools: {
    wake: ['warm private hotel morning face before the show', 'model morning natural expression in hotel luxury', 'private before-show face — calm and at ease'],
    morning_refresh: ['focused pre-show morning expression at the mirror', 'model morning self-care expression before backstage', 'the angel building herself in private morning expression'],
    getting_dressed: ['the transformation expression — becoming the angel in the dressing room', 'focused theatrical dressing room expression', 'the angel being assembled — deliberate and theatrical expression'],
    breakfast: ['relaxed hotel morning model expression before the show', 'calm composed hotel breakfast expression', 'the angel before the show — private and warm expression'],
    late_morning: ['backstage preparation building expression', 'editorial beauty transformation expression in professional setting', 'the angel becoming in backstage expression'],
    lunch: ['midday calm model expression in backstage ease', 'the angel between transformation stages expression', 'composed midday model expression before the theatrical peak'],
    afternoon: ['the complete transformation expression — the angel full', 'wings on and the theatrical expression of complete angel power', 'the most theatrical fashion expression — the complete angel look'],
    reset: ['the final dressing room expression — composed, complete, the walk ahead', 'the angel at maximum beauty before the corridor — the most powerful expression', 'pre-runway complete angel expression — confident and theatrical'],
    golden_hour: ['the corridor angel expression — wings spread, the walk imminent', 'the most electric pre-runway fashion expression', 'complete angel theatrical confidence before the cameras'],
    dinner: ['the runway expression — the angel walk at full theatrical power', 'editorial studio angel expression in professional dramatic light', 'the defining fashion expression — the angel on the runway or in editorial'],
    evening: ['post-show glamorous after-party expression', 'the angel after the runway — relieved and beautiful and alive', 'after-party glamour expression in luxury celebration'],
    night: ['private hotel quiet expression after the show', 'the model at private rest after the theatrical day', 'warm private hotel expression after the complete angel world'],
  },

  handDetailPools: {
    wake: ['hand on hotel white linen in morning', 'fingers near hotel morning detail', 'warm private hotel morning hand placement'],
    morning_refresh: ['hand at hotel bathroom counter in morning', 'fingers in hotel morning beauty routine', 'model morning hotel bathroom hand detail'],
    getting_dressed: ['hand adjusting wing strap in dressing room fitting', 'fingers touching diamond detail in transformation', 'the wing adjustment hand — the most theatrical fashion hand detail'],
    breakfast: ['hand around hotel coffee cup in morning', 'fingers on hotel suite table at model breakfast', 'hotel morning hand at the breakfast table'],
    late_morning: ['hand in backstage beauty preparation', 'fingers in editorial studio preparation detail', 'hands in backstage beauty transformation'],
    lunch: ['hand near model meal in backstage or suite', 'fingers in midday preparation detail', 'backstage midday hand placement'],
    afternoon: ['hand under wing in dressing room — the transformation hand detail', 'fingers on diamond detail in complete fitting', 'the most theatrical hand detail — touching wings or diamonds in transformation'],
    reset: ['hand on wing in final dressing room check', 'fingers adjusting complete angel look at the mirror', 'the final dressing room hand detail before the corridor'],
    golden_hour: ['wings spread — the hand beneath the wing in the corridor', 'fingers touching diamond detail in warm corridor pre-show light', 'the complete angel corridor hand detail'],
    dinner: ['the runway walk hands — composed and editorial in motion', 'editorial studio hand in complete angel look in dramatic light', 'the defining fashion hand — the angel on the runway'],
    evening: ['after-party hand with champagne in luxury celebration', 'fingers in post-show glamour detail', 'after-party luxury hand placement'],
    night: ['hand on hotel pillow after the show', 'fingers near hotel private night detail', 'the angel at rest — the most private hotel hand placement'],
  },

  movementEnergyPools: {
    wake: ['slow', 'private', 'model-morning'],
    morning_refresh: ['composed', 'deliberate', 'pre-show'],
    getting_dressed: ['theatrical', 'deliberate', 'transformation'],
    breakfast: ['relaxed', 'warm', 'private'],
    late_morning: ['building', 'professional', 'preparation'],
    lunch: ['calm', 'midday', 'gathering'],
    afternoon: ['theatrical', 'transforming', 'peak'],
    reset: ['composed', 'complete', 'ready'],
    golden_hour: ['electric', 'theatrical', 'imminent'],
    dinner: ['iconic', 'editorial', 'walking'],
    evening: ['glamorous', 'celebratory', 'post-show'],
    night: ['quiet', 'private', 'model-night'],
  },

  transitionPools: {
    human: {
      wake: ['the model morning in hotel before the show world', 'private luxury morning before the angel transformation'],
      morning_refresh: ['hotel bathroom morning ritual before backstage', 'the angel self-care beginning privately'],
      getting_dressed: ['the dressing room transformation beginning', 'wings and diamonds assembling — becoming the angel'],
      breakfast: ['model hotel morning before the show day begins', 'private morning ease in hotel before backstage'],
      late_morning: ['backstage preparation building — the transformation beginning', 'editorial studio angel look assembling'],
      lunch: ['midday in backstage ease before the transformation peak', 'the angel gathering before the wings'],
      afternoon: ['the complete transformation — wings on, angel complete', 'the backstage dressing room at theatrical peak'],
      reset: ['the final look complete — the corridor is next', 'the angel before the most famous walk in fashion'],
      golden_hour: ['the corridor — wings spread, the walk about to begin', 'the most electric pre-runway fashion moment'],
      dinner: ['the runway walk — the most iconic moment in fashion', 'the editorial studio complete angel editorial shoot'],
      evening: ['the after-party celebration after the runway', 'the angel post-show in luxury celebration'],
      night: ['private hotel after the show — the model beneath the angel', 'the theatrical world complete and private night'],
    },
  },

  narrativeIntentPools: {
    wake: ['the private human beginning of the most theatrical fashion day', 'the model before the angel — private and warm'],
    morning_refresh: ['building the angel identity from private morning through self-care ritual', 'the private preparation before the theatrical transformation begins'],
    getting_dressed: ['the theatrical transformation from model to angel — wings, diamonds, lingerie', 'the most powerful dressing ritual in fashion becoming the complete editorial identity'],
    breakfast: ['the model private morning ease before the show world takes over', 'fuel and calm before the theatrical transformation day'],
    late_morning: ['the transformation building in the backstage professional environment', 'the angel editorial look assembling piece by piece'],
    lunch: ['midday ease before the theatrical peak of the transformation', 'gathering before the wings and the complete angel look'],
    afternoon: ['the complete angel transformation — the most theatrical fashion moment', 'wings, diamonds, and the complete editorial identity fully assembled'],
    reset: ['the final complete angel look at the mirror — ready for the most famous walk', 'the corridor is next — the angel at maximum theatrical beauty'],
    golden_hour: ['the pre-show corridor — the most electric pre-runway fashion energy', 'wings spread before the cameras — the defining angel moment'],
    dinner: ['the runway walk or editorial shoot — the angel at full theatrical editorial power', 'the most iconic fashion moment — the angel on the runway in wings and diamonds'],
    evening: ['post-show luxury celebration — the angel after the runway in glamorous ease', 'the fashion world celebrating the most beautiful walk'],
    night: ['the model returning from the angel — private hotel quiet after the theatrical day', 'the most private moment — the angel identity at rest in the hotel suite'],
  },

  fallbackRules: {
    pacingProfile: { wake: 'slow', morning_refresh: 'slow', getting_dressed: 'slow', breakfast: 'slow', late_morning: 'medium', lunch: 'slow', afternoon: 'slow', reset: 'slow', golden_hour: 'slow', dinner: 'slow', evening: 'slow', night: 'slow' },
    repetitionBreakers: { avoidBackToBackSameLocation: true, avoidBackToBackSameLightingStyle: true, encourageWardrobeEvolution: true },
    worldDefaults: { allowSceneGroupFallbackToPhasePools: true, allowSubLocationFallbackToWorldPools: true, preferSceneGroupsWhenPresent: true },
  },

  exclusions: {
    premium: ['cheap or non-luxury lingerie settings', 'non-theatrical or editorial environments', 'casual everyday settings unrelated to runway', 'non-model non-editorial energy'],
    hard: ['corporate settings', 'beach swimwear without runway context', 'outdoor non-editorial public spaces', 'non-fashion environments'],
  },

  routeRules: {
    worldIdentity: ['the angel world must feel theatrical, beautiful, luxury, and editorial — the most famous lingerie runway world elevated to editorial art', 'wings, diamonds, luxury lingerie, and the runway are the core visual language'],
    humanFlow: ['the day begins in private hotel morning, builds through backstage preparation and transformation, peaks on the runway or in editorial, and closes in post-show luxury and private hotel night'],
    styling: ['luxury lingerie and the iconic wings — the angel editorial identity is the defining styling language', 'the transformation from model to angel is the core styling narrative'],
    atmosphere: ['backstage theatrical atmosphere, runway drama, editorial studio professional light, and luxury hotel private ease', 'the theatrical fashion world is always present'],
  },
}
