export const STORY_WORLD_WILD_NATURE = {
  id: 'wild-nature',
  name: 'Wild Nature',
  description:
    'A cinematic world of earth-scale mythology — waterfalls loud enough to erase thought, fjord cliffs disappearing into white fog, volcanic beaches beneath dead northern skies, glacier storms swallowing human scale whole, and desert dunes glowing gold before darkness consumes them. The beauty is not that she dominates nature. The beauty is that nature is too ancient to notice her, and she belongs there anyway.',

  geography: { country: 'Iceland, Norway, Patagonia, Scotland, Faroe Islands, Sahara, New Zealand, remote wilderness', region: 'waterfall, fjord, glacier, storm coast, volcanic beach, desert dune, highland, forest, geothermal pool' },

  identity: {
    archetype: 'elemental woman — softness inside earth-scale violence',
    vibe: ['the earth as the most powerful room on earth', 'water louder than thought', 'fog swallowing human scale', 'wind turning fabric into survival', 'beauty made fragile by landscapes older than civilization'],
    tone: ['raw', 'windswept', 'ancient', 'spiritual', 'cinematic', 'elemental', 'free'],
    persona: ['beautiful because she is small against something enormous', 'completely at ease where the earth is violent and indifferent', 'softness surviving inside wind, water, stone, fog, and storm', 'the particular power of a woman who does not conquer nature — she disappears into it'],
  },

  phaseOrder: ['wake', 'morning_refresh', 'getting_dressed', 'breakfast', 'late_morning', 'lunch', 'afternoon', 'reset', 'golden_hour', 'dinner', 'evening', 'night'],

  phases: {
    wake:            { label: 'Wake',            timeWindows: ['remote cabin morning before weather moves in', 'cold dawn before the landscape fully appears'],                         pacing: 'slow',   subLocations: ['mountain-cabin', 'fjord-cabin'] },
    morning_refresh: { label: 'Morning Refresh', timeWindows: ['geothermal water against freezing air', 'waterfall mist morning ritual'],                                      pacing: 'slow',   subLocations: ['geothermal-pool', 'waterfall-edge'] },
    getting_dressed: { label: 'Getting Dressed', timeWindows: ['layering fabric against wind and rain', 'preparing for the cold landscape'],                                    pacing: 'slow',   subLocations: ['mountain-cabin', 'cliff-shelter'] },
    breakfast:       { label: 'Breakfast',       timeWindows: ['warm cabin breakfast before entering the landscape', 'quiet food before geological silence'],                  pacing: 'slow',   subLocations: ['fjord-cabin', 'remote-lodge'] },
    late_morning:    { label: 'Late Morning',    timeWindows: ['first walk into fog and cliffs', 'the landscape beginning to overpower the body'],                             pacing: 'medium', subLocations: ['fjord-edge', 'forest-path'] },
    lunch:           { label: 'Lunch',           timeWindows: ['rest beside glacier water', 'temporary warmth inside hostile landscape'],                                    pacing: 'slow',   subLocations: ['glacial-lake', 'highland-field'] },
    afternoon:       { label: 'Afternoon',       timeWindows: ['the landscape at full force', 'waterfall, storm, glacier wind, ocean impact'],                                pacing: 'medium', subLocations: ['waterfall-edge', 'storm-coastline'] },
    reset:           { label: 'Reset',           timeWindows: ['warmth returning after exposure', 'the body recovering from the earth'],                                      pacing: 'slow',   subLocations: ['geothermal-pool', 'remote-lodge'] },
    golden_hour:     { label: 'Golden Hour',     timeWindows: ['desert amber light before darkness', 'cold northern sunset across cliffs and fog'],                         pacing: 'slow',   subLocations: ['desert-dunes', 'fjord-edge'] },
    dinner:          { label: 'Dinner',          timeWindows: ['firelight against wilderness darkness', 'human warmth after storm and exposure'],                            pacing: 'slow',   subLocations: ['remote-lodge', 'forest-fire'] },
    evening:         { label: 'Evening',         timeWindows: ['northern lights or storm clouds after sunset', 'the landscape becoming emotionally infinite'],                 pacing: 'slow',   subLocations: ['northern-sky', 'storm-cliff'] },
    night:           { label: 'Night',           timeWindows: ['complete silence after weather stops', 'alone beneath stars, cliffs, snow, and ancient darkness'],          pacing: 'slow',   subLocations: ['open-landscape', 'mountain-cabin'] },
  },

  locations: [
    'remote cabin before storm weather', 'geothermal pool in freezing volcanic terrain',
    'waterfall edge swallowed by white mist', 'fjord cliff disappearing into fog',
    'glacial lake under mountain silence', 'storm coastline with violent ocean below',
    'desert dune summit in dying amber light', 'hotel-free wilderness under northern lights',
  ],

  subLocations: {
    'mountain-cabin': {
      id: 'mountain-cabin', name: 'Mountain Cabin', mapAnchor: 'remote cabin in wilderness',
      category: 'private-wilderness',
      bestPhases: ['wake', 'getting_dressed', 'night'],
      overlays: ['the small human shelter before the earth takes over', 'warmth inside a landscape too large to care', 'the silence before weather moves through the valley'],
      locations: ['remote mountain cabin before dawn', 'small warm cabin beneath storm sky', 'wilderness cabin surrounded by cliffs and cold silence'],
    },
    'fjord-cabin': {
      id: 'fjord-cabin', name: 'Fjord Cabin', mapAnchor: 'fjord cabin in fog',
      category: 'fjord-isolation',
      bestPhases: ['wake', 'breakfast'],
      overlays: ['fog pressing against the windows', 'the fjord hidden but emotionally present', 'human warmth beside invisible ocean depth'],
      locations: ['fjord cabin under white northern fog', 'remote cabin beside invisible water', 'small wooden shelter beneath enormous cliffs'],
    },
    'geothermal-pool': {
      id: 'geothermal-pool', name: 'Geothermal Pool', mapAnchor: 'natural geothermal pool',
      category: 'warmth-against-cold',
      bestPhases: ['morning_refresh', 'reset'],
      overlays: ['warm water against freezing air', 'steam rising into volcanic silence', 'the body recovering from the violence of the landscape'],
      locations: ['geothermal pool inside frozen volcanic terrain', 'warm natural water beneath cold northern sky', 'steam and black stone in freezing wilderness'],
    },
    'waterfall-edge': {
      id: 'waterfall-edge', name: 'Waterfall Edge', mapAnchor: 'wild waterfall edge',
      category: 'water-force',
      bestPhases: ['morning_refresh', 'afternoon'],
      overlays: ['water loud enough to erase thought', 'white mist swallowing body and fabric', 'the waterfall as the most powerful voice in the world'],
      locations: ['waterfall edge lost inside cold mist', 'wild waterfall pool in freezing landscape', 'stone and spray beneath violent falling water'],
    },
    'fjord-edge': {
      id: 'fjord-edge', name: 'Fjord Edge', mapAnchor: 'cliff above fjord',
      category: 'geological-scale',
      bestPhases: ['late_morning', 'golden_hour'],
      overlays: ['cliffs disappearing into white fog', 'the body becoming tiny against geological permanence', 'wind strong enough to reshape posture'],
      locations: ['fjord cliff above invisible ocean depth', 'northern cliff edge swallowed by fog', 'high cliff over dark water and white atmosphere'],
    },
    'cliff-shelter': {
      id: 'cliff-shelter', name: 'Cliff Shelter', mapAnchor: 'shelter before cliff exposure',
      category: 'pre-exposure',
      bestPhases: ['getting_dressed'],
      overlays: ['the last sheltered moment before wind takes over', 'fabric prepared for weather instead of beauty', 'the body dressing for survival inside cinematic earth'],
      locations: ['small shelter before the cliff path', 'rock shelter beside cold wind', 'covered edge before exposed landscape'],
    },
    'forest-path': {
      id: 'forest-path', name: 'Forest Path', mapAnchor: 'ancient wet forest path',
      category: 'forest-depth',
      bestPhases: ['late_morning'],
      overlays: ['wet moss and old trees absorbing sound', 'the forest as a quieter kind of ancient power', 'green darkness before the open landscape returns'],
      locations: ['ancient forest path covered in wet moss', 'dark green forest after rain', 'narrow wilderness path beneath heavy trees'],
    },
    'glacial-lake': {
      id: 'glacial-lake', name: 'Glacial Lake', mapAnchor: 'glacial lake under mountains',
      category: 'ice-silence',
      bestPhases: ['lunch'],
      overlays: ['water so still it makes the body feel temporary', 'mountains reflected like another world beneath her', 'cold blue silence around human warmth'],
      locations: ['glacial lake beneath mountain silence', 'ice-blue lake under storm sky', 'remote lake surrounded by stone and snow'],
    },
    'highland-field': {
      id: 'highland-field', name: 'Highland Field', mapAnchor: 'rain-soaked highland field',
      category: 'rain-and-moor',
      bestPhases: ['lunch'],
      overlays: ['rain soaking the field until color becomes emotion', 'purple-grey distance and wet grass', 'softness inside endless open moorland'],
      locations: ['Scottish highland field in rain and fog', 'open moorland under grey sky', 'wet grass and distant mountain shadow'],
    },
    'storm-coastline': {
      id: 'storm-coastline', name: 'Storm Coastline', mapAnchor: 'violent northern coastline',
      category: 'storm-impact',
      bestPhases: ['afternoon'],
      overlays: ['the ocean attacking the rocks below', 'black water and white foam as emotional force', 'storm wind making stillness impossible'],
      locations: ['storm coastline with violent ocean below', 'black cliff above breaking waves', 'cold sea impact under moving storm clouds'],
    },
    'desert-dunes': {
      id: 'desert-dunes', name: 'Desert Dunes', mapAnchor: 'desert dune at sunset',
      category: 'desert-silence',
      bestPhases: ['golden_hour'],
      overlays: ['the earth turning gold before disappearing', 'desert silence as the opposite of waterfall noise', 'the body becoming small beneath endless amber sky'],
      locations: ['desert dune summit in dying amber light', 'Saharan ridge at sunset', 'warm sand before night consumes the horizon'],
    },
    'remote-lodge': {
      id: 'remote-lodge', name: 'Remote Lodge', mapAnchor: 'remote lodge after exposure',
      category: 'return-to-warmth',
      bestPhases: ['breakfast', 'reset', 'dinner'],
      overlays: ['human warmth after the earth has emptied her out', 'firelight as the only luxury against wilderness', 'the return from exposure into quiet shelter'],
      locations: ['remote lodge after storm exposure', 'warm interior beneath wilderness darkness', 'wooden lodge surrounded by rain and cliff silence'],
    },
    'forest-fire': {
      id: 'forest-fire', name: 'Forest Fire', mapAnchor: 'small fire in wilderness',
      category: 'firelight-wilderness',
      bestPhases: ['dinner'],
      overlays: ['firelight against ancient dark', 'the smallest warmth inside the largest silence', 'human heat surrounded by wilderness night'],
      locations: ['small fire in wet forest darkness', 'firelight beside remote wilderness shelter', 'warm flame under cold open sky'],
    },
    'northern-sky': {
      id: 'northern-sky', name: 'Northern Sky', mapAnchor: 'northern lights above wilderness',
      category: 'sky-mythology',
      bestPhases: ['evening'],
      overlays: ['the sky becoming larger than the body can understand', 'northern light moving above silent earth', 'beauty happening without needing the human figure'],
      locations: ['northern lights over dark landscape', 'green sky above snow and black stone', 'open northern field beneath aurora'],
    },
    'storm-cliff': {
      id: 'storm-cliff', name: 'Storm Cliff', mapAnchor: 'cliff under evening storm',
      category: 'evening-storm',
      bestPhases: ['evening'],
      overlays: ['the edge of the world after sunset', 'black ocean and moving clouds below', 'evening storm making the landscape feel infinite'],
      locations: ['storm cliff after sunset', 'dark cliff above ocean weather', 'evening fog and storm above the sea'],
    },
    'open-landscape': {
      id: 'open-landscape', name: 'Open Landscape', mapAnchor: 'open wilderness at night',
      category: 'absolute-night',
      bestPhases: ['night'],
      overlays: ['the body alone against ancient darkness', 'the earth after all movement stops', 'the final silence where human scale disappears completely'],
      locations: ['open wilderness beneath stars', 'dark landscape after weather movement', 'snow, stone, cliff, and sky in complete silence'],
    },
  },

  sceneVariants: {
    wake: ['remote morning before the storm reaches the valley', 'waking in a small shelter against enormous earth'],
    morning_refresh: ['geothermal warmth against freezing air', 'waterfall mist as the first contact with the landscape'],
    getting_dressed: ['layering fabric against wind, rain, and cold', 'the body preparing to enter weather instead of comfort'],
    breakfast: ['warm food before geological silence', 'quiet shelter before the earth takes over again'],
    late_morning: ['walking toward fog, cliffs, and distance', 'the first confrontation with landscape scale'],
    lunch: ['resting beside glacier water beneath dark sky', 'temporary warmth inside hostile natural silence'],
    afternoon: ['the landscape at full emotional violence', 'waterfall force, ocean impact, and glacier wind'],
    reset: ['warmth returning after the body has been exposed', 'the recovery after weather and stone'],
    golden_hour: ['desert light turning the earth gold before darkness', 'cold northern sunset across cliffs and fog'],
    dinner: ['firelight against wilderness darkness', 'human warmth surviving after exposure'],
    evening: ['northern lights above silent earth', 'storm clouds and black water after sunset'],
    night: ['the body alone after weather movement stops', 'human scale disappearing beneath stars and ancient darkness'],
  },

  actionPools: {
    wake: ['waking in a remote cabin before the landscape moves', 'watching storm light slowly enter the valley', 'remaining still while the earth outside feels older than thought'],
    morning_refresh: ['stepping into geothermal water while freezing air surrounds the body', 'letting waterfall mist cover skin and fabric', 'standing in steam while volcanic stone stays black and cold'],
    getting_dressed: ['pulling fabric close against cold wind', 'layering for weather instead of beauty', 'preparing to let the landscape change posture naturally'],
    breakfast: ['holding warmth before entering the wilderness again', 'eating quietly while fog consumes the view outside', 'sitting near firelight before the earth takes over the day'],
    late_morning: ['walking toward cliffs disappearing into fog', 'moving deeper into landscapes too large for human scale', 'standing at the first edge where distance disappears'],
    lunch: ['resting beside glacial water beneath mountain silence', 'holding temporary warmth inside cold open space', 'pausing while the landscape stays indifferent and enormous'],
    afternoon: ['standing against waterfall noise and violent spray', 'letting storm wind reshape fabric and hair', 'facing ocean impact from the cliff edge'],
    reset: ['returning warmth to the body after exposure', 'sitting in geothermal steam after wind and rain', 'recovering quietly while the landscape remains outside'],
    golden_hour: ['standing on the dune as the earth turns gold', 'watching the last warmth disappear behind cliffs', 'becoming small beneath amber sky and endless distance'],
    dinner: ['sitting near firelight while wilderness darkness gathers', 'holding warmth against rain and storm outside', 'resting after the earth has emptied the body out'],
    evening: ['watching northern lights move over dark land', 'standing near cliffs as black water disappears below', 'remaining still while the sky becomes emotionally impossible'],
    night: ['standing alone beneath stars and ancient darkness', 'lying in quiet after weather movement stops', 'becoming almost invisible inside the final landscape silence'],
  },

  environmentPools: {
    wake: ['remote cabin morning beneath storm-colored sky', 'cold valley silence before weather movement', 'small shelter surrounded by wilderness scale'],
    morning_refresh: ['geothermal steam against freezing volcanic air', 'waterfall mist over black stone', 'warm water inside hostile earth conditions'],
    getting_dressed: ['cold cabin fabric and wet boots before exposure', 'shelter at the edge of wind and rain', 'the last controlled interior before nature takes control'],
    breakfast: ['warm cabin against fog and cliffs outside', 'remote lodge with wilderness pressing at the windows', 'firelight and breakfast inside geological silence'],
    late_morning: ['fjord cliff disappearing into white fog', 'wet forest path before the open landscape', 'the first edge where human scale starts to collapse'],
    lunch: ['glacial lake beneath mountain silence', 'highland field soaked in rain', 'cold open earth with brief human pause'],
    afternoon: ['waterfall force, storm coastline, and glacier wind', 'the earth at maximum movement and violence', 'black water, white foam, cold spray, and storm clouds'],
    reset: ['steam and warmth after environmental exposure', 'remote shelter after weather impact', 'the body returning slowly from cold and wind'],
    golden_hour: ['amber dunes before darkness', 'fjord cliffs briefly warmed by dying sun', 'the earth becoming mythological for one final hour'],
    dinner: ['firelight surrounded by rain and wilderness', 'remote lodge in total environmental darkness', 'human warmth inside the oldest silence'],
    evening: ['northern sky moving above frozen land', 'storm cliff after sunset', 'fog and black ocean turning distance into nothing'],
    night: ['open wilderness beneath stars', 'mountain cabin after weather stops', 'ancient darkness where the body becomes almost irrelevant'],
  },

  moodPools: {
    wake: ['the private morning before the earth becomes overwhelming', 'small human warmth inside enormous silence', 'the beginning of a day where the landscape will decide everything'],
    morning_refresh: ['warmth against cold — the first physical contrast of the day', 'the body meeting water before the landscape takes over', 'steam and mist as the morning ritual of survival'],
    getting_dressed: ['preparation for weather as identity', 'fabric becoming protection instead of decoration', 'the quiet seriousness of entering nature at full force'],
    breakfast: ['human softness before geological scale', 'quiet fuel before storm and distance', 'the comfort that only matters because the outside is brutal'],
    late_morning: ['the first emotional surrender to scale', 'the body beginning to look temporary beside cliffs and fog', 'distance becoming stronger than identity'],
    lunch: ['a small pause inside an enormous world', 'temporary warmth against cold ancient silence', 'rest without ever escaping the landscape'],
    afternoon: ['nature at full violence and beauty', 'the earth emotionally overpowering the body', 'wind and water becoming the dominant character'],
    reset: ['the return from exposure', 'warmth after being reduced by the landscape', 'the body remembering itself after weather'],
    golden_hour: ['the earth becoming briefly merciful', 'golden light as the final softness before darkness', 'the last beautiful hour before the landscape disappears'],
    dinner: ['firelight as human resistance', 'warmth surrounded by enormous wilderness dark', 'the quiet after the earth has taken everything loud away'],
    evening: ['the sky becoming larger than the body can understand', 'storm and aurora as emotional weather', 'the landscape turning infinite after sunset'],
    night: ['complete private insignificance beneath ancient earth', 'the final silence after all weather movement', 'the body alone inside darkness older than memory'],
  },

  cameraPools: {
    wake: ['85mm low angle in remote cabin, storm morning light dissolved behind', '135mm close-up at face height, cold window light defining edge'],
    morning_refresh: ['85mm geothermal steam close, cold landscape dissolved behind', '50mm waterfall mist mid-shot, spray and stone compressing behind'],
    getting_dressed: ['50mm cabin dressing frame, wet fabric and cold window behind', '85mm mirrorless preparation angle, wind light entering from doorway'],
    breakfast: ['24mm wide lodge breakfast, fogged window and wilderness beyond', '85mm warm cabin table framing, landscape dissolved behind'],
    late_morning: ['85mm cliff medium, fog and fjord depth disappearing behind', '50mm forest path wide, wet trees and atmosphere surrounding subject'],
    lunch: ['85mm glacial lake seated frame, mountain silence compressed behind', '50mm highland field wide, rain and open distance behind'],
    afternoon: ['85mm waterfall medium, mist and violent spray behind subject', '50mm storm coastline wide, ocean impact and cliff scale filling background'],
    reset: ['135mm geothermal recovery close, steam as soft veil behind', '85mm lodge interior medium, post-exposure warmth behind subject'],
    golden_hour: ['135mm dune sunset close, amber sky dissolved behind', '85mm fjord golden-hour medium, cliff and fog lit at edge'],
    dinner: ['85mm firelight medium, wilderness darkness behind subject', '50mm lodge wide, warm interior surrounded by black exterior'],
    evening: ['135mm northern-sky close, aurora glow and dark land behind', '85mm storm-cliff profile, black ocean dissolved beneath'],
    night: ['135mm night close, single fire or lamp as sole source', '85mm wide open-landscape shot, body small beneath stars'],
  },

  lightingPools: {
    wake: ['cold 5200K dawn through cabin glass, storm light soft across skin', 'pale northern morning light before weather movement'],
    morning_refresh: ['warm geothermal steam against cold 6000K blue air', 'white waterfall mist diffusing harsh natural light'],
    getting_dressed: ['cold 5000K cabin window light on layered fabric', 'grey storm daylight entering shelter before exposure'],
    breakfast: ['warm 3200K firelight mixed with cold window fog', 'soft morning lodge light against wilderness shadow'],
    late_morning: ['flat white fog light across cliff and body', 'green forest shade with wet reflective moss'],
    lunch: ['cold 5600K glacier light bouncing from water', 'grey highland rain light with soft atmospheric falloff'],
    afternoon: ['high-contrast storm light with violent water reflection', 'cold directional coastal light under moving black clouds'],
    reset: ['warm 2800K lodge or pool light after exposure', 'steam-diffused warmth against cold volcanic surroundings'],
    golden_hour: ['rich amber desert light at low angle', 'cold northern sunset with brief golden rim on fog and cliff'],
    dinner: ['single warm 2200K firelight against wilderness darkness', 'low lodge practicals surrounded by black exterior silence'],
    evening: ['green-blue aurora glow over dark land', 'deep blue storm evening light with black ocean falloff'],
    night: ['single warm 1900K cabin lamp or fire source', 'moonless wilderness darkness with minimal sky illumination'],
  },

  stylingPools: {
    wardrobe: {
      wake: ['warm cabin morning layer before exposure', 'soft private wilderness morning styling', 'the human before the landscape takes over'],
      morning_refresh: ['minimal geothermal water styling', 'wet fabric and skin under waterfall mist', 'warmth against cold morning water'],
      getting_dressed: ['earth-tone layers against rain and wind', 'heavy coat or knitwear for cliff exposure', 'fabric chosen for survival inside cinematic weather'],
      breakfast: ['warm cabin layers before entering the landscape', 'soft lodge morning styling against cold windows', 'wilderness morning warmth'],
      late_morning: ['flowing ivory fabric or coat in fog and cliff wind', 'earth-tone layers moving through forest or fjord', 'the first outdoor styling claimed by weather'],
      lunch: ['knitwear or coat beside glacier water', 'rain-softened highland layers', 'temporary warmth styling in cold open space'],
      afternoon: ['wet fabric against skin in waterfall spray', 'coat or flowing fabric destroyed beautifully by storm wind', 'the landscape visibly altering the styling'],
      reset: ['soft post-exposure wrap or robe by geothermal steam', 'warm recovery styling after wind and rain', 'the body returned from weather'],
      golden_hour: ['flowing fabric against amber dunes', 'warm earth tones in dying light', 'the final cinematic silhouette before darkness'],
      dinner: ['warm lodge layers beside firelight', 'soft wilderness evening clothing after exposure', 'human warmth styling against black environmental night'],
      evening: ['dark coat or minimal silhouette under northern sky', 'wind-shaped fabric beneath aurora or storm cloud', 'evening wilderness styling absorbed by darkness'],
      night: ['private warm layer in cabin darkness', 'minimal firelit night styling after the landscape', 'the body at rest after earth-scale exposure'],
    },
    details: {
      wake: ['cold window light on natural morning skin', 'messy hair before wind takes over', 'private wilderness morning detail'],
      morning_refresh: ['steam on skin against cold air', 'waterfall spray on hair and fabric', 'warm water detail before the day turns brutal'],
      getting_dressed: ['wet boots, heavy fabric, cold hands', 'coat collar pulled against wind', 'layering detail before exposure'],
      breakfast: ['hands around warm cup before cold landscape', 'firelight on face while fog moves outside', 'morning warmth detail against wilderness'],
      late_morning: ['fog in hair and fabric', 'wind pulling cloth toward the cliff edge', 'wet moss or stone beneath bare feet or boots'],
      lunch: ['cold water reflection on skin', 'rain beads on coat and hair', 'glacier-blue light on fabric'],
      afternoon: ['spray, wet fabric, storm hair, cold skin', 'fabric moving violently in ocean wind', 'water and weather taking over all styling detail'],
      reset: ['steam-softened skin after exposure', 'warm towel or robe after cold water and wind', 'the body recovering visibly from the landscape'],
      golden_hour: ['amber light on fabric edge', 'sand on skin and feet', 'wind lifting cloth across desert silence'],
      dinner: ['firelight on hands and face', 'warm fabric after cold exposure', 'rain still visible in hair or clothing'],
      evening: ['aurora glow on face edge', 'dark fabric disappearing into night', 'storm moisture catching minimal light'],
      night: ['warm lamp on tired skin', 'hair and fabric finally still', 'the private detail after the earth has gone quiet'],
    },
    changeMoments: {
      wake: ['private human warmth before the landscape', 'the body still sheltered before exposure'],
      morning_refresh: ['between warmth and cold — water as first transformation', 'steam before weather'],
      getting_dressed: ['the body preparing to be changed by wind and rain', 'fabric becoming survival'],
      breakfast: ['last warm interior before wilderness', 'human comfort before geological scale'],
      late_morning: ['entering the landscape fully', 'the first loss of human scale'],
      lunch: ['brief rest without escaping the earth', 'temporary softness inside cold distance'],
      afternoon: ['the landscape takes over completely', 'weather becomes the styling force'],
      reset: ['returning from exposure', 'the body reclaiming warmth'],
      golden_hour: ['earth softens briefly before darkness', 'light becomes mythology for one hour'],
      dinner: ['firelight replaces sun', 'human warmth after landscape violence'],
      evening: ['the sky becomes the new landscape', 'aurora or storm replaces daylight'],
      night: ['the body becomes private again', 'the earth returns to silence'],
    },
  },

  sensoryPools: {
    wake: ['cold air behind warm cabin glass', 'the silence before wind begins', 'the feeling of waking where the world outside is older than thought'],
    morning_refresh: ['steam rising around skin in freezing air', 'waterfall mist hitting face and fabric', 'warm water surrounded by black volcanic cold'],
    getting_dressed: ['heavy fabric against cold hands', 'wet boots and wool before the wind', 'the body preparing for weather instead of comfort'],
    breakfast: ['warm cup, firelight, fog outside', 'quiet food before the earth becomes loud', 'human warmth inside a wilderness morning'],
    late_morning: ['fog damp on skin, cliff wind in fabric', 'wet moss underfoot and white distance ahead', 'the first feeling of being small'],
    lunch: ['cold glacial water still enough to feel unreal', 'rain against fabric in open highland air', 'brief rest under dark mountain light'],
    afternoon: ['waterfall roar, ocean impact, storm wind, cold spray', 'the landscape loud enough to remove thought', 'weather forcing the body into honesty'],
    reset: ['warm steam after cold exposure', 'skin thawing after wind and rain', 'the silence after the landscape has emptied the body'],
    golden_hour: ['warm sand cooling under sunset', 'amber light touching skin after cold distance', 'the last warmth before the world turns dark'],
    dinner: ['fire crackle, wet clothes drying, storm outside', 'warmth in the smallest circle against enormous darkness', 'the smell of rain, wood, and cold air'],
    evening: ['aurora light moving silently above black land', 'storm clouds swallowing the last horizon', 'cold night air and emotional sky scale'],
    night: ['absolute silence after weather stops', 'stars above stone and snow', 'the body alone inside darkness older than memory'],
  },

  socialEnergyPools: {
    wake: ['completely private wilderness morning', 'the woman alone before the landscape takes over'],
    morning_refresh: ['private water ritual inside raw earth', 'alone with steam, cold air, and water'],
    getting_dressed: ['private preparation before exposure', 'the body alone preparing for the earth'],
    breakfast: ['private or intimate shelter warmth', 'human quiet before wilderness'],
    late_morning: ['alone or nearly alone inside enormous landscape', 'the world becoming larger than any social presence'],
    lunch: ['private rest beside cold water or open field', 'small human pause in wilderness'],
    afternoon: ['no social energy — only body and earth force', 'the landscape as the only presence that matters'],
    reset: ['private recovery after exposure', 'quiet return to human warmth'],
    golden_hour: ['alone against sunset and distance', 'the body visible only to the earth'],
    dinner: ['small human warmth after the wild day', 'private shelter against wilderness night'],
    evening: ['alone beneath sky and storm', 'the earth becoming the only witness'],
    night: ['complete private insignificance', 'alone after everything becomes silent'],
  },

  atmospherePools: {
    wake: ['remote wilderness morning before storm movement', 'small shelter inside overwhelming earth silence', 'the beginning of an elemental day'],
    morning_refresh: ['steam, cold air, volcanic stone, and water ritual', 'warmth against freezing earth atmosphere'],
    getting_dressed: ['pre-exposure seriousness — fabric, weather, and silence', 'the atmosphere before stepping into raw nature'],
    breakfast: ['firelight and fog before the landscape takes over', 'warm interior against geological exterior'],
    late_morning: ['fog, cliffs, moss, distance, and the first loss of scale', 'the landscape beginning to dominate every frame'],
    lunch: ['glacial stillness and temporary human warmth', 'rain field, mountain silence, and cold distance'],
    afternoon: ['the earth at maximum violence — water, storm, wind, ocean', 'weather as the dominant emotional atmosphere'],
    reset: ['steam and recovery after exposure', 'the body returning from the landscape quietly'],
    golden_hour: ['the earth briefly turning gold and merciful', 'desert or cliff sunset becoming mythological'],
    dinner: ['firelight after the earth has taken over the day', 'small warmth against wilderness darkness'],
    evening: ['northern sky, storm cliff, black water, and infinite scale', 'after-sunset earth becoming emotionally overwhelming'],
    night: ['absolute silence after weather', 'ancient darkness, stars, stone, snow, and the smallest human presence'],
  },

  propPools: {
    wake: ['wool blanket, cold window, firewood, storm light', 'remote cabin bedding and fogged glass'],
    morning_refresh: ['steam, wet stone, towel, natural water', 'geothermal pool edge and volcanic rock'],
    getting_dressed: ['heavy coat, wet boots, wool layers, weathered bag', 'fabric and protection before exposure'],
    breakfast: ['warm cup, wooden table, firelight, fogged window', 'simple food against wilderness morning'],
    late_morning: ['wet moss, cliff stone, wind-pulled fabric', 'walking path, rain, and fog'],
    lunch: ['glacial water, stone, rain-covered field', 'small meal beside immense silence'],
    afternoon: ['waterfall spray, storm wind, ocean foam, black rock', 'the environment itself as the prop'],
    reset: ['steam, warm towel, lodge fire, wet fabric drying', 'the recovery props after exposure'],
    golden_hour: ['sand, cliff edge, sunset light, wind-shaped fabric', 'amber horizon and empty earth'],
    dinner: ['fire, wool, wet boots, warm cup, dark window', 'small shelter objects against wilderness darkness'],
    evening: ['aurora sky, storm cloud, black water, cliff edge', 'night sky as the only prop large enough'],
    night: ['single lamp, fire ember, cold window, stars beyond', 'the last warm object in the wilderness'],
  },

  bodyLanguagePools: {
    wake: ['slow sheltered morning posture before the weather', 'the body still soft before the earth changes it', 'private warmth body language in remote silence'],
    morning_refresh: ['relaxed but exposed posture in warm water and freezing air', 'body softened by steam but surrounded by cold', 'the first physical surrender to the environment'],
    getting_dressed: ['protective body language against wind and rain', 'collar pulled close, fabric held against the body', 'preparing posture for weather'],
    breakfast: ['quiet seated warmth before exposure', 'hands close to heat, shoulders relaxed but aware of the cold outside', 'small human posture inside huge landscape'],
    late_morning: ['upright against wind at the cliff edge', 'body slightly turned from fog and weather', 'walking posture reduced by environmental scale'],
    lunch: ['resting posture beside cold water', 'body folded into temporary warmth', 'stillness beneath mountain silence'],
    afternoon: ['braced body language against storm and water force', 'fabric and hair pulled by wind naturally', 'softness holding against violent landscape'],
    reset: ['body recovering from exposure', 'posture softening back into warmth', 'quiet exhaustion after weather'],
    golden_hour: ['still silhouette against endless light', 'fabric lifted by wind in slow controlled posture', 'body small beneath enormous sunset'],
    dinner: ['closed warm body language beside fire', 'the body returning to human scale after the earth', 'rest after exposure'],
    evening: ['still posture beneath sky movement', 'head tilted toward northern lights or storm cloud', 'body quiet while the environment becomes infinite'],
    night: ['nearly motionless in darkness', 'body small and private beneath stars', 'complete quiet after the landscape'],
  },

  facialExpressionPools: {
    wake: ['quiet morning face before the weather begins', 'private expression inside remote cabin warmth', 'soft face before the earth takes over'],
    morning_refresh: ['calm expression inside steam and cold air', 'fresh face against water and volcanic silence', 'quiet focus before entering the landscape'],
    getting_dressed: ['serious weather-ready expression', 'focused face while preparing for exposure', 'calm before environmental force'],
    breakfast: ['soft warm expression before the day turns cold and vast', 'quiet human face against fog outside', 'rested but aware of the wilderness'],
    late_morning: ['awed expression at the first full landscape scale', 'calm face inside fog and distance', 'the expression of being made smaller'],
    lunch: ['quiet reflective expression beside glacial water', 'soft face under rain and open sky', 'temporary calm inside vast cold'],
    afternoon: ['focused expression against storm and spray', 'face softened by exposure and wind', 'the look of surviving beauty inside weather'],
    reset: ['relieved expression as warmth returns', 'post-exposure softness', 'quiet exhaustion after the landscape'],
    golden_hour: ['still expression beneath amber light', 'the face softened by the last warmth of the earth', 'sunset calm before darkness'],
    dinner: ['warm firelit expression after exposure', 'quiet face after the day has emptied her', 'human softness returning beside firelight'],
    evening: ['expression lifted toward impossible sky', 'still face under aurora or storm', 'awe without performance'],
    night: ['private quiet expression after weather stops', 'the face almost disappearing into darkness', 'human stillness beneath ancient night'],
  },

  handDetailPools: {
    wake: ['hand on wool blanket in cold cabin morning', 'fingers near fogged glass', 'hand resting beside warm cup before storm'],
    morning_refresh: ['hand touching geothermal water surface', 'fingers in waterfall mist', 'hand against black volcanic stone'],
    getting_dressed: ['hand pulling coat collar against wind', 'fingers fastening heavy fabric', 'hand holding wet boots or wool layer'],
    breakfast: ['hand around warm cup near window fog', 'fingers on wooden breakfast table', 'hand near firelight before exposure'],
    late_morning: ['hand touching wet moss or cliff stone', 'fingers extended into fog', 'hand holding fabric against wind'],
    lunch: ['hand near glacial water', 'fingers resting on rain-soaked fabric', 'hand against cold stone beside lake'],
    afternoon: ['hand against waterfall-slick rock', 'fingers in ocean spray and wind', 'hand gripping fabric as storm moves through'],
    reset: ['hand holding warm towel after exposure', 'fingers through steam', 'hand near fire after cold landscape'],
    golden_hour: ['hand lifting fabric into amber wind', 'fingers trailing through sand', 'hand against cliff edge in sunset light'],
    dinner: ['hand near firelight', 'fingers around warm cup after weather', 'hand on drying fabric beside lodge fire'],
    evening: ['hand lifted slightly beneath aurora', 'fingers touching cold cliff stone after dark', 'hand resting still as storm passes'],
    night: ['hand on blanket in cabin darkness', 'fingers near single lamp', 'hand almost invisible beneath star-lit wilderness'],
  },

  movementEnergyPools: {
    wake: ['slow', 'sheltered', 'pre-weather'],
    morning_refresh: ['warm-cold', 'ritual', 'private'],
    getting_dressed: ['protective', 'deliberate', 'pre-exposure'],
    breakfast: ['warm', 'quiet', 'before-landscape'],
    late_morning: ['building', 'exposed', 'scale-loss'],
    lunch: ['resting', 'temporary', 'cold-still'],
    afternoon: ['violent', 'weather-driven', 'elemental'],
    reset: ['recovering', 'warmth-returning', 'quiet'],
    golden_hour: ['mythic', 'slow', 'last-light'],
    dinner: ['warm', 'sheltered', 'after-exposure'],
    evening: ['infinite', 'still', 'sky-led'],
    night: ['private', 'ancient', 'silent'],
  },

  transitionPools: {
    human: {
      wake: ['the small human morning before the landscape moves', 'waking in shelter before the earth becomes the day'],
      morning_refresh: ['warm water before cold exposure', 'the body meeting water before weather'],
      getting_dressed: ['fabric becoming survival before entering the landscape', 'preparing the body for earth-scale force'],
      breakfast: ['warmth before geological silence', 'quiet food before the wilderness takes over'],
      late_morning: ['entering fog and cliffs — the first loss of scale', 'the landscape beginning to dominate the body'],
      lunch: ['temporary rest inside cold enormous space', 'human warmth briefly held beside glacial silence'],
      afternoon: ['the earth at full force — water, wind, storm, ocean', 'the body reduced by weather and scale'],
      reset: ['returning warmth after exposure', 'the body recovering from the earth'],
      golden_hour: ['the earth softening into amber mythology', 'the final warm light before darkness'],
      dinner: ['firelight after landscape violence', 'human warmth surviving the day'],
      evening: ['the sky replacing the landscape after sunset', 'the earth becoming infinite after dark'],
      night: ['the final silence after weather stops', 'the body alone beneath ancient darkness'],
    },
  },

  narrativeIntentPools: {
    wake: ['the private beginning before the earth becomes larger than the body', 'the small human shelter before weather and scale take over'],
    morning_refresh: ['warmth against freezing air — the first ritual of survival', 'water as the private threshold before the wild day'],
    getting_dressed: ['preparing not for appearance but for exposure', 'the wardrobe as protection against wind, rain, and geological force'],
    breakfast: ['the last human warmth before the landscape becomes the main character', 'quiet fuel before fog, stone, and water overpower the day'],
    late_morning: ['the first confrontation with scale — cliffs, fog, and distance reducing the body', 'entering the landscape as the emotional center of the world'],
    lunch: ['temporary warmth inside hostile beauty', 'a small pause that proves the wilderness never stops surrounding her'],
    afternoon: ['the peak of environmental force — nature no longer background but absolute presence', 'water, wind, storm, and cliff becoming the world’s dominant identity'],
    reset: ['the return from exposure — warmth after being emptied out by the earth', 'the body becoming human again after the landscape takes over'],
    golden_hour: ['the earth briefly becoming beautiful in a softer way before darkness', 'amber light as the final mercy of the landscape'],
    dinner: ['firelight as the smallest human resistance against wilderness darkness', 'the after-exposure chapter where warmth becomes luxury'],
    evening: ['the sky becoming the new landscape — aurora, storm, fog, black ocean', 'after sunset, nature becomes emotionally infinite'],
    night: ['the final truth of the world — human scale disappears completely', 'the body alone in ancient darkness after the earth has finished moving'],
  },

  fallbackRules: {
    pacingProfile: { wake: 'slow', morning_refresh: 'slow', getting_dressed: 'slow', breakfast: 'slow', late_morning: 'medium', lunch: 'slow', afternoon: 'medium', reset: 'slow', golden_hour: 'slow', dinner: 'slow', evening: 'slow', night: 'slow' },
    repetitionBreakers: { avoidBackToBackSameLocation: true, avoidBackToBackSameLightingStyle: true, encourageWardrobeEvolution: true },
    worldDefaults: { allowSceneGroupFallbackToPhasePools: true, allowSubLocationFallbackToWorldPools: true, preferSceneGroupsWhenPresent: true },
  },

  exclusions: {
    premium: ['generic hiking content', 'tourist nature photography', 'fitness outdoors aesthetic', 'cheap adventure influencer energy', 'ordinary travel blog scenery'],
    hard: ['urban interiors unrelated to wilderness', 'corporate settings', 'gym or wellness studio environments', 'beach vacation energy without elemental force', 'theme-park nature fantasy'],
  },

  routeRules: {
    worldIdentity: ['the Wild Nature world must feel elemental, ancient, cinematic, and spiritually raw — the earth is the dominant character, not the background', 'water, wind, fog, stone, storm, glacier, and desert silence are the core visual language'],
    humanFlow: ['the day moves from small human shelter into full exposure, through environmental violence, then back into warmth, firelight, sky, and final silence', 'the landscape is the narrative center of every phase'],
    styling: ['wardrobe evolves from warm shelter layers to weather-shaped fabric, wet skin, wind-destroyed cloth, post-exposure warmth, and private night stillness', 'styling must look changed by the environment — wind, water, rain, sand, fog, and cold'],
    atmosphere: ['remote shelter warmth, waterfall force, fjord fog, glacier silence, storm coastline, amber dunes, firelight, aurora, and ancient night are the defining atmospheres'],
  },
}