// 12-moment cinematic day structure for Perfect Day™

export const DAY_MOMENTS = [
  {
    id: 'waking_up',
    time: '06:00',
    label: 'Waking Up',
    sceneBase: 'Bedroom. First light through windows. Creator stirs in bed.',
    mood: 'soft, still, intimate, vulnerable',
    lighting: 'golden morning glow, diffused, low angle through curtains',
    creatorEnergy: 'natural, unguarded, real, no performance',
    contentType: 'intimate',
    hookArchetype: 'stillness',
    defaultHook: 'The morning belongs to no one but you.',
    captionTone: 'quiet, reflective, inviting',
    sceneDirection: 'Slow wide shot. Sheets. Light shifting. No urgency. Time suspended.',
    videoInstruction: 'Slow push-in from window. Creator stirs. Sheet movement. Ambient morning sound only.',
    brandLink: 'identity over achievement — this is who they are, not what they do',
  },
  {
    id: 'morning_routine',
    time: '07:00',
    label: 'Morning Routine',
    sceneBase: 'Bathroom. Mirror. Skincare ritual. Water. Quiet intentionality.',
    mood: 'intentional, calm, premium, self-invested',
    lighting: 'warm bathroom light, steam diffusion, soft shadows',
    creatorEnergy: 'slow, deliberate, confident, self-aware',
    contentType: 'ritual',
    hookArchetype: 'ritual',
    defaultHook: 'The ritual that sets everything else.',
    captionTone: 'grounded, purposeful, personal',
    sceneDirection: 'Close-up on hands, product textures, mirror reflection, water. Unhurried.',
    videoInstruction: 'Close-ups in sequence. Hands on face. Water drops. Mirror eye contact. No rushing.',
    brandLink: 'discipline and self-investment — premium positioning without words',
  },
  {
    id: 'breakfast',
    time: '08:00',
    label: 'Breakfast',
    sceneBase: 'Kitchen or terrace. Coffee or tea. Fresh food. Looking outward.',
    mood: 'peaceful, nourishing, present, lifestyle-forward',
    lighting: 'soft natural morning light, warm table glow, no harsh shadows',
    creatorEnergy: 'present, slow, satisfied, grateful',
    contentType: 'lifestyle',
    hookArchetype: 'presence',
    defaultHook: 'This is what a slow morning actually looks like.',
    captionTone: 'warm, inviting, sensory',
    sceneDirection: 'Wide shot of space. Close-up of cup steam. Creator at window or table, calm.',
    videoInstruction: 'Steam rising from cup. Creator looking out. Soft ambient sound — birds, city, or silence.',
    brandLink: 'abundance and ease — the life they aspire to',
  },
  {
    id: 'work_planning',
    time: '09:00',
    label: 'Work / Planning',
    sceneBase: 'Desk, laptop, notebook. Or phone call on balcony. Focused and purposeful.',
    mood: 'focused, purposeful, intelligent, in control',
    lighting: 'clean natural light, minimal, no distraction, window light on work surface',
    creatorEnergy: 'sharp, determined, calm authority',
    contentType: 'authority',
    hookArchetype: 'control',
    defaultHook: 'This is where the work gets done.',
    captionTone: 'direct, authoritative, aspirational',
    sceneDirection: 'Clean desk setup. Hands typing or writing. Purposeful movement. Environment minimal.',
    videoInstruction: 'Focus pull from notebook to laptop to face. Creator in deep work. No distractions visible.',
    brandLink: 'intelligence and agency — they control their world',
  },
  {
    id: 'outdoor_walk',
    time: '11:00',
    label: 'Walk / Outdoor',
    sceneBase: 'Street, park, coastal path, rooftop, or garden. Movement and air.',
    mood: 'free, alive, exploratory, unhurried',
    lighting: 'midday natural, warm, motion blur on movement, outdoor clarity',
    creatorEnergy: 'light, open, energetic, unbothered',
    contentType: 'freedom',
    hookArchetype: 'freedom',
    defaultHook: 'Movement is the answer.',
    captionTone: 'light, energetic, free',
    sceneDirection: 'Motion shots. Creator walking toward camera or away. Environment wide and breathing.',
    videoInstruction: 'Walking shot from behind, then from front. Environment in motion. Natural sound.',
    brandLink: 'freedom and mobility — their life is not confined',
  },
  {
    id: 'lunch',
    time: '13:00',
    label: 'Lunch',
    sceneBase: 'Restaurant, rooftop table, terrace, or home kitchen. Social or luxuriously solitary.',
    mood: 'social or quiet indulgence, reward, midday celebration',
    lighting: 'bright midday outdoor or warm restaurant interior, food-flattering light',
    creatorEnergy: 'relaxed, present, enjoying, generous',
    contentType: 'pleasure',
    hookArchetype: 'pleasure',
    defaultHook: 'A meal that actually deserves a moment.',
    captionTone: 'sensory, warm, celebratory',
    sceneDirection: 'Overhead food shot. Creator with food or drink. Beautiful environment. No rush.',
    videoInstruction: 'Food arriving or being plated. Creator first bite or first sip. Smile or satisfaction.',
    brandLink: 'enjoyment and quality — they do not skip the good moments',
  },
  {
    id: 'gym_fitness',
    time: '15:00',
    label: 'Gym / Fitness',
    sceneBase: 'Gym floor, outdoor training, yoga studio, or pool. Physical investment.',
    mood: 'disciplined, physical, transformative, driven',
    lighting: 'harsh gym overhead or bright outdoor, contrast-heavy, sweat-visible',
    creatorEnergy: 'driven, focused, powerful, in the process',
    contentType: 'discipline',
    hookArchetype: 'transformation',
    defaultHook: 'The version of you that shows up anyway.',
    captionTone: 'motivational, honest, direct',
    sceneDirection: 'Mid-movement shots. Weights in hand or body in motion. No posing — actual effort.',
    videoInstruction: 'Motion during rep or set. Quick cut pace. Creator focused not performing. Sweat real.',
    brandLink: 'investment in self — discipline equals premium positioning',
  },
  {
    id: 'home_transition',
    time: '17:00',
    label: 'Home / Transition',
    sceneBase: 'Returning home. Changing. Dropping the public face. Decompressing.',
    mood: 'shift from external to internal, release, private ease',
    lighting: 'late afternoon warm, golden hour through windows, softer than midday',
    creatorEnergy: 'soft, returning to self, honest, private',
    contentType: 'authenticity',
    hookArchetype: 'vulnerability',
    defaultHook: 'The part nobody shows.',
    captionTone: 'honest, warm, relatable',
    sceneDirection: 'Keys on table. Shoes off. Jacket dropped. Creator exhales. Home absorbs them.',
    videoInstruction: 'Transition sequence. Outside → inside. Public energy dissolving into private ease.',
    brandLink: 'realness behind the brand — trust-building moment',
  },
  {
    id: 'cooking',
    time: '19:00',
    label: 'Cooking / Preparing',
    sceneBase: 'Kitchen. Cooking with intention. Preparing for next day. Mise en place.',
    mood: 'grounded, ritual, domestic luxury, creative, nourishing',
    lighting: 'warm evening kitchen light, overhead warm, surfaces glowing',
    creatorEnergy: 'calm, creative, nourishing, in flow',
    contentType: 'ritual',
    hookArchetype: 'ritual',
    defaultHook: 'This is how you actually invest in tomorrow.',
    captionTone: 'warm, grounded, sensory',
    sceneDirection: 'Hands chopping, stirring, plating. Steam. Color. Kitchen alive with activity.',
    videoInstruction: 'Hands-only cooking sequence. Color and texture close-ups. Warm ambient sound.',
    brandLink: 'intentionality and self-care — they prepare, they invest, they do not rush',
  },
  {
    id: 'evening_rest',
    time: '20:30',
    label: 'Movies / Evening',
    sceneBase: 'Living room, sofa, screen, candles, or reading. Earned rest.',
    mood: 'ease, reward, indulgent rest, fully off, human',
    lighting: 'low warm interior light, candle or lamp, television glow optional',
    creatorEnergy: 'fully off, human, restful, present',
    contentType: 'reward',
    hookArchetype: 'ease',
    defaultHook: 'The evening you actually earned.',
    captionTone: 'cozy, warm, earned, real',
    sceneDirection: 'Creator settled into sofa. Blanket. Warm light. Nothing performative. Just being.',
    videoInstruction: 'Wide of room with creator settled. Warm light. Silence or soft ambient. No motion needed.',
    brandLink: 'the reward after discipline — balance and enjoyment as part of the brand',
  },
  {
    id: 'shower_winddown',
    time: '21:30',
    label: 'Shower / Wind Down',
    sceneBase: 'Bathroom. Shower or bath. End-of-day ritual. Washing off the day.',
    mood: 'cleansing, closing, transitional, private luxury',
    lighting: 'soft steamy bathroom, intimate, warm, slightly dim',
    creatorEnergy: 'letting go, cleaning slate, transitional',
    contentType: 'ritual',
    hookArchetype: 'reset',
    defaultHook: 'Wash off the day. Reset for tomorrow.',
    captionTone: 'intimate, sensory, transitional',
    sceneDirection: 'Steam. Water on tile or skin (tasteful). Quiet. Products on shelf. Nothing rushed.',
    videoInstruction: 'Steam rising. Water sounds. Close-up product textures. No face needed — atmosphere only.',
    brandLink: 'the close of the premium day — signals completeness and care',
  },
  {
    id: 'bed_preparation',
    time: '22:30',
    label: 'Getting Ready for Bed',
    sceneBase: 'Bedroom. Skincare. Journal. Single lamp. The quietest moment.',
    mood: 'complete, still, at peace, closed, satisfied',
    lighting: 'single warm lamp, very low, outside dark, intimate pool of light',
    creatorEnergy: 'closed, rested, satisfied, full',
    contentType: 'completion',
    hookArchetype: 'completion',
    defaultHook: 'A full day. A full life.',
    captionTone: 'reflective, peaceful, complete',
    sceneDirection: 'Lamp lit room. Bed turned down. Skincare last step. Journal or phone down. Eyes closing.',
    videoInstruction: 'Lamp glow. Hand on journal. Creator settling. Final slow zoom out. Fade.',
    brandLink: 'the full arc — from waking to sleeping in their world, their life, their brand',
  },
]

export function getMomentById(id) {
  return DAY_MOMENTS.find(m => m.id === id) || null
}

export function getMomentsByIds(ids) {
  return ids.map(id => getMomentById(id)).filter(Boolean)
}

export function getDefaultDaySelection() {
  // Default: 6 key moments for a balanced day story
  return ['waking_up', 'breakfast', 'work_planning', 'gym_fitness', 'cooking', 'bed_preparation']
}

export function getFullDay() {
  return DAY_MOMENTS.map(m => m.id)
}
