export const WORLD_FANVUE_CREATOR = {
  id: 'fanvue_creator',
  name: 'Fanvue Creator Life',

  phases: {
    morning: [
      {
        action: 'waking up slowly in a softly lit bedroom and reaching for the phone before fully getting out of bed',
        environment: 'soft sheets, bedside table, muted luxury bedroom, quiet private atmosphere',
        mood: 'playful, relaxed, softly aware of the viewer',
        camera: 'soft over-bed candid angle',
        lighting: 'soft diffused morning light',
      },
      {
        action: 'scrolling through overnight messages and smiling at selected comments before starting the day',
        environment: 'bedroom, phone in hand, quiet creator morning setting',
        mood: 'engaged, warm, subtly inviting',
        camera: 'close candid phone interaction framing',
        lighting: 'natural indoor morning light',
      },
      {
        action: 'walking to the mirror in an oversized shirt and checking hair, posture, and expression',
        environment: 'mirror corner, soft bedroom textures, tidy private interior',
        mood: 'self-aware, feminine, gently teasing',
        camera: 'mirror-side medium shot',
        lighting: 'window-lit morning contrast',
      },
      {
        action: 'making coffee and moving through the kitchen with an easy, unforced rhythm',
        environment: 'modern kitchen, mug, coffee machine, quiet apartment atmosphere',
        mood: 'casual, intimate, lifestyle-driven',
        camera: 'lifestyle kitchen candid shot',
        lighting: 'clean morning daylight',
      },
      {
        action: 'standing by the window with coffee and checking content ideas before the day begins',
        environment: 'window light, private apartment, creator morning calm',
        mood: 'soft confidence, personal, slightly magnetic',
        camera: 'window-side editorial framing',
        lighting: 'bright soft morning glow',
      },
      {
        action: 'changing into a more intentional but still relaxed look before filming the first content of the day',
        environment: 'bedroom, chair with clothing options, mirror, phone tripod nearby',
        mood: 'prepared, composed, lightly provocative without forcing it',
        camera: 'getting-ready full-body composition',
        lighting: 'soft neutral indoor daylight',
      },
    ],

    day: [
      {
        action: 'setting up the phone and testing angles for a casual daytime content set',
        environment: 'bedroom or living room, tripod, natural room styling, polished private interior',
        mood: 'intentional, playful, creator-focused',
        camera: 'behind-the-scenes setup shot',
        lighting: 'clean midday natural light',
      },
      {
        action: 'moving through the room naturally while filming short audience-facing clips',
        environment: 'private interior, soft décor, minimal luxury details, content creation space',
        mood: 'flirty, engaged, socially aware',
        camera: 'medium creator lifestyle framing',
        lighting: 'bright natural daylight',
      },
      {
        action: 'checking footage immediately after recording and smiling at what worked',
        environment: 'phone screen, mirror, private apartment atmosphere',
        mood: 'confident, satisfied, lightly playful',
        camera: 'over-shoulder review angle',
        lighting: 'soft indoor daylight',
      },
      {
        action: 'replying to audience messages while seated casually with controlled body language',
        environment: 'sofa, bed edge, or lounge chair, phone in hand, creator home setting',
        mood: 'connected, inviting, warm attention',
        camera: 'seated candid medium shot',
        lighting: 'soft afternoon room light',
      },
      {
        action: 'filming a second set with more intentional pacing and stronger eye contact',
        environment: 'mirror zone, bed area, or styled content corner, polished creator environment',
        mood: 'more deliberate, teasing, visually aware',
        camera: 'mirror or side-profile creator angle',
        lighting: 'warm indoor daylight blend',
      },
      {
        action: 'taking a break after filming and walking through the apartment with calm confidence',
        environment: 'private hallway, bedroom-to-lounge transition, clean luxury home setting',
        mood: 'self-possessed, relaxed, magnetic without effort',
        camera: 'walking lifestyle tracking shot',
        lighting: 'soft late afternoon interior light',
      },
      {
        action: 'editing clips, choosing thumbnails, and planning what part stays public versus private',
        environment: 'desk, laptop, phone, content workflow setup, creator apartment atmosphere',
        mood: 'strategic, modern, self-directed',
        camera: 'over-shoulder editing shot',
        lighting: 'neutral creative workspace light',
      },
      {
        action: 'posting a daytime update and watching the first reactions come in',
        environment: 'phone screen glow, bed or sofa, creator interior, subtle private setting',
        mood: 'pleased, engaged, quietly in control',
        camera: 'close audience-interaction framing',
        lighting: 'soft ambient daylight fading slightly warmer',
      },
      {
        action: 'slowing down for a private reset before shifting into a more elevated evening creator mood',
        environment: 'quiet apartment, mirror, soft fabrics, private creator calm',
        mood: 'measured, feminine, transitioning from casual to intentional',
        camera: 'quiet transition portrait angle',
        lighting: 'golden late afternoon light',
      },
    ],

    private: [
      {
        action: 'taking time alone to reset, touch up hair and makeup, and refine the mood for the evening content set',
        environment: 'vanity mirror, beauty products, low private room noise, polished home interior',
        mood: 'controlled, elevated, self-aware',
        camera: 'mirror-side preparation framing',
        lighting: 'soft warm vanity glow',
      },
      {
        action: 'choosing between looks while standing in front of the mirror and testing how each one reads on camera',
        environment: 'bedroom mirror, clothing options, private creator setup',
        mood: 'intentional, selective, slightly more provocative',
        camera: 'full-body mirror composition',
        lighting: 'warm flattering indoor light',
      },
      {
        action: 'adjusting posture, expression, and pacing before starting the evening content run',
        environment: 'private room, mirror, tripod already in place, calm controlled environment',
        mood: 'focused, teasing, emotionally aware',
        camera: 'close prep shot',
        lighting: 'soft ambient room light',
      },
      {
        action: 'recording slower more intimate clips with stronger eye contact and more deliberate movement',
        environment: 'bedroom, chair, or soft private corner, minimal distractions, creator-controlled atmosphere',
        mood: 'tension-building, intimate, composed',
        camera: 'cinematic medium-close framing',
        lighting: 'warm low-key shadows',
      },
      {
        action: 'pausing between takes and checking the emotional effect of the footage before continuing',
        environment: 'phone screen, bed edge, dim room styling, creator private set',
        mood: 'self-directed, calculated, quietly seductive',
        camera: 'over-shoulder preview angle',
        lighting: 'soft moody interior glow',
      },
      {
        action: 'sending selective previews or replying to top audience messages with calm creator confidence',
        environment: 'private apartment, phone in hand, low-lit creator space',
        mood: 'exclusive, responsive, in control of access',
        camera: 'seated private interaction shot',
        lighting: 'subtle evening lamp light',
      },
      {
        action: 'moving through the room with slower body language, letting the atmosphere carry more than the action',
        environment: 'private bedroom, soft shadows, minimal luxury textures',
        mood: 'controlled tension, soft authority, emotionally magnetic',
        camera: 'slow cinematic tracking angle',
        lighting: 'warm intimate room lighting',
      },
      {
        action: 'holding still after filming, reviewing the energy of the set before deciding what to release',
        environment: 'quiet private room, tripod, phone, subtle creator-afterglow',
        mood: 'calm, selective, high-value creator presence',
        camera: 'still after-set portrait shot',
        lighting: 'low ambient evening glow',
      },
    ],

    night: [
      {
        action: 'posting the evening content and watching audience engagement rise in real time',
        environment: 'dark room, phone glow, private bedroom or lounge area',
        mood: 'satisfied, powerful, quietly thrilled by the response',
        camera: 'phone-lit close-up framing',
        lighting: 'screen glow with soft low room light',
      },
      {
        action: 'replying selectively to the strongest reactions while maintaining emotional distance and control',
        environment: 'bed edge or lounge chair, phone in hand, intimate private interior',
        mood: 'exclusive, magnetic, controlled access',
        camera: 'seated night interaction angle',
        lighting: 'low-key intimate lighting',
      },
      {
        action: 'recording a final low-energy late-night clip with calm eye contact and minimal movement',
        environment: 'soft private room, quiet bedroom atmosphere, minimal styling distractions',
        mood: 'after-dark, intimate, emotionally direct',
        camera: 'tight cinematic close framing',
        lighting: 'soft moody night light',
      },
      {
        action: 'closing the content workflow and leaning back into the quiet after the audience rush',
        environment: 'private bedroom, laptop closed, phone lowered, calm end-of-day setting',
        mood: 'fulfilled, reflective, self-possessed',
        camera: 'quiet after-post wide shot',
        lighting: 'warm bedside glow',
      },
      {
        action: 'removing the performance layer and settling back into a softer private state',
        environment: 'bedroom, mirror or bedside area, low-lit creator interior',
        mood: 'private, calm, emotionally settled',
        camera: 'gentle end-of-night portrait angle',
        lighting: 'very soft warm night light',
      },
      {
        action: 'lying back in silence after the final interaction, letting the day close slowly',
        environment: 'soft bedding, dim room, phone set aside, quiet apartment',
        mood: 'complete, peaceful, quietly powerful',
        camera: 'wide still night composition',
        lighting: 'low night ambient light',
      },
      {
        action: 'drifting into rest after a full creator day built on attention, pacing, and control',
        environment: 'darkened bedroom, calm luxury textures, room at rest',
        mood: 'spent, fulfilled, soft afterglow',
        camera: 'final end-of-day still frame',
        lighting: 'very soft fading bedside light',
      },
    ],
  },
}