export const WORLD_FITNESS_LIFE = {
  id: 'fitness_life',
  name: 'Fitness Life',
  phases: {
    morning: [
      {
        action: 'waking up in an athlete apartment, stretching slowly before the day starts',
        environment: 'minimal luxury bedroom, soft sheets, water bottle on bedside table, training clothes prepared nearby',
        mood: 'disciplined, calm, focused, fresh start energy',
        camera: 'soft over-bed editorial angle',
        lighting: 'soft diffused early morning light',
      },
      {
        action: 'walking to the kitchen in oversized hoodie, preparing lemon water and morning supplements',
        environment: 'clean modern kitchen, supplement containers, shaker bottle, marble counter',
        mood: 'routine-driven, healthy, self-respecting, composed',
        camera: 'lifestyle candid medium shot',
        lighting: 'clean natural kitchen daylight',
      },
      {
        action: 'standing by the mirror checking physique and posture before training',
        environment: 'bedroom mirror corner, minimal apartment interior, gym bag nearby',
        mood: 'self-aware, intentional, quietly confident',
        camera: 'mirror-side body composition angle',
        lighting: 'window-lit soft morning contrast',
      },
      {
        action: 'making a high-protein breakfast and coffee before the gym',
        environment: 'modern kitchen island, egg whites, oats, fruit, black coffee, meal prep feel',
        mood: 'structured, healthy, elite daily rhythm',
        camera: 'editorial breakfast preparation framing',
        lighting: 'bright morning daylight',
      },
      {
        action: 'sitting with coffee and reviewing training plan on the phone',
        environment: 'breakfast table, notebook, phone with training notes, tidy apartment',
        mood: 'locked in, motivated, mentally prepared',
        camera: 'over-shoulder planning shot',
        lighting: 'soft clean daylight through windows',
      },
      {
        action: 'putting on gym outfit and adjusting straps before leaving',
        environment: 'dressing mirror, fitted activewear, gym bag, headphones, sneakers lined up',
        mood: 'confident, athletic, ready to perform',
        camera: 'full-body dressing room composition',
        lighting: 'soft neutral indoor daylight',
      },
    ],

    day: [
      {
        action: 'walking into the gym with composed athlete energy',
        environment: 'premium gym entrance, front desk glow, industrial-modern training facility',
        mood: 'focused, admired, performance-ready',
        camera: 'wide establishing gym entrance shot',
        lighting: 'bright clean indoor architectural light',
      },
      {
        action: 'beginning warm-up on treadmill with controlled posture and serious intent',
        environment: 'cardio zone, polished machines, gym floor reflection, premium health club feel',
        mood: 'disciplined, switched on, physically awake',
        camera: 'side profile motion shot',
        lighting: 'clear overhead gym lighting',
      },
      {
        action: 'performing first heavy lower-body movement with full concentration',
        environment: 'strength floor, squat rack or smith machine, plates, mirrored wall, clean training zone',
        mood: 'strong, determined, elite training intensity',
        camera: 'low angle strength framing',
        lighting: 'high-contrast gym performance light',
      },
      {
        action: 'pausing between sets, catching breath, adjusting gloves and focus',
        environment: 'weight room, bench, dumbbells, chalk traces, serious gym atmosphere',
        mood: 'locked in, controlled fatigue, mentally sharp',
        camera: 'cinematic rest-between-sets close mid-shot',
        lighting: 'cool-toned training light',
      },
      {
        action: 'hitting glute-focused movement with slow controlled form',
        environment: 'hip thrust station, cable area, premium gym setup, strong bodyline in frame',
        mood: 'powerful, intentional, body-aware confidence',
        camera: 'editorial training side angle',
        lighting: 'clean directional gym lighting',
      },
      {
        action: 'checking pump in the mirror after a hard working set',
        environment: 'mirror wall, dumbbells, serious athlete environment, clean luxury fitness club',
        mood: 'satisfied, sharp, confident without forcing it',
        camera: 'mirror-adjacent physique check composition',
        lighting: 'bright mirror-facing gym light',
      },
      {
        action: 'cooling down with stretching and slower breath after the workout',
        environment: 'functional area, mat, foam roller, calm premium recovery corner',
        mood: 'accomplished, grounded, physically open',
        camera: 'soft wide recovery shot',
        lighting: 'gentle neutral recovery lighting',
      },
      {
        action: 'walking out of the gym with post-workout confidence and visible pump',
        environment: 'gym exit corridor, water bottle, gym bag over shoulder, modern club interior',
        mood: 'earned confidence, composed power, elevated self-respect',
        camera: 'tracking exit shot from behind and slightly side-on',
        lighting: 'clean polished indoor daylight blend',
      },
      {
        action: 'stopping for a healthy post-workout meal and iced coffee',
        environment: 'wellness café, protein meal bowl, iced coffee, polished fitness lifestyle setting',
        mood: 'healthy luxury, balanced discipline, socially magnetic presence',
        camera: 'lifestyle café editorial framing',
        lighting: 'bright midday café light',
      },
    ],

    private: [
      {
        action: 'arriving home and placing keys, headphones, and gym bag down after training',
        environment: 'luxury apartment entrance, clean interior styling, calm private space',
        mood: 'relieved, accomplished, quietly proud',
        camera: 'entryway lifestyle shot',
        lighting: 'soft afternoon interior light',
      },
      {
        action: 'opening the fridge and preparing a recovery meal with practiced routine',
        environment: 'designer kitchen, meal prep containers, fresh ingredients, premium apartment setting',
        mood: 'nourished, intentional, stable energy',
        camera: 'kitchen candid side framing',
        lighting: 'natural indoor afternoon light',
      },
      {
        action: 'sitting near the window eating post-workout meal in calm silence',
        environment: 'window table, city or residential view, minimal high-end apartment details',
        mood: 'peaceful, reflective, satisfied',
        camera: 'quiet seated profile composition',
        lighting: 'soft late afternoon window light',
      },
      {
        action: 'taking a long shower and washing off the workout day',
        environment: 'modern bathroom, rainfall shower, stone textures, premium self-care environment',
        mood: 'resetting, feminine, restored, private calm',
        camera: 'tasteful bathroom editorial angle',
        lighting: 'soft warm bathroom glow',
      },
      {
        action: 'applying skincare and tying hair back in the bathroom mirror',
        environment: 'clean luxury vanity, skincare products, towel, soft elegant apartment bathroom',
        mood: 'self-caring, radiant, composed',
        camera: 'mirror-side close composition',
        lighting: 'warm flattering mirror light',
      },
      {
        action: 'changing into soft fitted homewear and moving slowly through the apartment',
        environment: 'bedroom suite, neutral fabrics, calm modern interior, elevated private lifestyle feel',
        mood: 'soft, feminine, unwinding, subtly confident',
        camera: 'quiet indoor lifestyle framing',
        lighting: 'golden late afternoon interior light',
      },
      {
        action: 'editing content, checking gym clips, and planning the next post',
        environment: 'sofa or desk setup, laptop, phone, tripod nearby, creator-athlete apartment environment',
        mood: 'productive, modern, self-directed, aspirational',
        camera: 'over-shoulder creator workflow shot',
        lighting: 'soft ambient evening-prep light',
      },
      {
        action: 'standing on the balcony after the shower and reset, breathing in the evening air',
        environment: 'private balcony, city lights beginning to appear, luxury apartment exterior view',
        mood: 'reflective, elevated, calm control',
        camera: 'balcony silhouette medium-wide shot',
        lighting: 'golden hour fading into evening',
      },
    ],

    night: [
      {
        action: 'getting ready for an evening dinner in a fitted elegant look',
        environment: 'bedroom mirror, evening outfit, jewelry, perfume, refined private preparation',
        mood: 'high-value, feminine, composed, intentional',
        camera: 'editorial getting-ready full-body shot',
        lighting: 'soft evening room glow',
      },
      {
        action: 'walking into a stylish restaurant or lounge with quiet confidence',
        environment: 'luxury dining venue, warm architecture, polished tables, premium nightlife scene',
        mood: 'socially magnetic, refined, admired presence',
        camera: 'arrival tracking shot',
        lighting: 'warm candlelit evening lighting',
      },
      {
        action: 'seated at dinner with elegant posture and calm eye contact',
        environment: 'fine dining table, wine glass, polished cutlery, intimate upscale restaurant atmosphere',
        mood: 'poised, feminine, sophisticated control',
        camera: 'refined seated portrait angle',
        lighting: 'candlelit warm shadows',
      },
      {
        action: 'walking home or entering the apartment after the evening out',
        environment: 'night hallway, apartment entrance, city lights outside, calm late-evening transition',
        mood: 'fulfilled, calm, private afterglow',
        camera: 'quiet cinematic return shot',
        lighting: 'dim architectural night light',
      },
      {
        action: 'making a final tea or nighttime recovery drink before bed',
        environment: 'dark quiet kitchen, mug, low apartment light, peaceful luxury routine',
        mood: 'restorative, slow, grounded',
        camera: 'night routine candid framing',
        lighting: 'low warm kitchen light',
      },
      {
        action: 'sitting on the bed answering messages or reviewing the day before sleep',
        environment: 'soft bedroom, lamp glow, phone in hand, sheets turned down, calm end-of-day feel',
        mood: 'thoughtful, soft, emotionally settled',
        camera: 'bedside documentary-style shot',
        lighting: 'soft bedside lamp glow',
      },
      {
        action: 'lying down to sleep after a full fitness-focused day',
        environment: 'minimal luxury bedroom, dark calm atmosphere, phone off, room at rest',
        mood: 'complete, peaceful, quietly proud, deeply reset',
        camera: 'wide still end-of-day composition',
        lighting: 'very soft low night light',
      },
    ],
  },
}