export const WORLD_GYM_INFLUENCER = {
  id: 'gym_influencer',
  name: 'Gym Influencer Life',

  phases: {
    morning: [
      {
        action: 'waking up early and sitting at the edge of the bed, mentally preparing for the training session ahead',
        environment: 'minimal bedroom, soft morning light, calm focused atmosphere',
        mood: 'disciplined, focused, grounded',
        camera: 'side profile calm morning shot',
        lighting: 'soft diffused morning light',
      },
      {
        action: 'checking physique in the mirror before eating, observing small changes with a critical but calm mindset',
        environment: 'mirror, bedroom or bathroom, natural light hitting the body',
        mood: 'self-aware, analytical, controlled',
        camera: 'mirror front-facing physique check',
        lighting: 'natural window light',
      },
      {
        action: 'preparing a simple high-protein breakfast while moving slowly and deliberately',
        environment: 'clean kitchen, meal prep setup, minimal distractions',
        mood: 'routine-driven, focused, calm',
        camera: 'lifestyle kitchen angle',
        lighting: 'bright morning daylight',
      },
      {
        action: 'sitting with food and briefly checking messages or comments before the gym',
        environment: 'table, phone, quiet morning interior',
        mood: 'engaged but not distracted, controlled attention',
        camera: 'over-shoulder casual interaction shot',
        lighting: 'soft indoor daylight',
      },
      {
        action: 'putting on gym outfit and adjusting posture in the mirror with intent',
        environment: 'bedroom, mirror, gym clothes prepared nearby',
        mood: 'ready, focused, slightly elevated energy',
        camera: 'full-body mirror shot',
        lighting: 'clean neutral indoor light',
      },
      {
        action: 'walking out the door with headphones on, fully mentally locked into training mode',
        environment: 'apartment hallway or outdoor entrance, early quiet surroundings',
        mood: 'locked in, disciplined, purposeful',
        camera: 'walking tracking shot from behind',
        lighting: 'cool morning outdoor light',
      },
    ],

    day: [
      {
        action: 'entering the gym and scanning the environment before starting the workout',
        environment: 'gym floor, weights, machines, low morning crowd',
        mood: 'focused, aware, controlled intensity',
        camera: 'wide gym entrance shot',
        lighting: 'neutral indoor gym lighting',
      },
      {
        action: 'setting up the camera or phone before the first set',
        environment: 'gym corner, tripod, equipment nearby',
        mood: 'intentional, content-aware, focused',
        camera: 'behind-the-scenes setup angle',
        lighting: 'bright gym lighting',
      },
      {
        action: 'performing the first working set with controlled movement and strong form',
        environment: 'machine or free weights, gym background',
        mood: 'intense, focused, disciplined',
        camera: 'mid-set action shot',
        lighting: 'high-contrast gym lighting',
      },
      {
        action: 'resting between sets while watching previous footage and adjusting angles',
        environment: 'bench, weights around, phone in hand',
        mood: 'analytical, calm under intensity',
        camera: 'seated candid shot',
        lighting: 'neutral gym light',
      },
      {
        action: 'performing heavier sets with visible strain and controlled breathing',
        environment: 'main gym area, machines or barbells',
        mood: 'high effort, controlled aggression, focused intensity',
        camera: 'low angle strength shot',
        lighting: 'sharp directional gym lighting',
      },
      {
        action: 'walking between exercises with confident posture and awareness of the environment',
        environment: 'gym floor, passing equipment and mirrors',
        mood: 'confident, composed, self-assured',
        camera: 'walking lifestyle gym shot',
        lighting: 'mixed gym lighting',
      },
      {
        action: 'filming short clips specifically for social media with clean execution',
        environment: 'gym area, minimal background clutter, controlled setup',
        mood: 'professional, engaging, visually aware',
        camera: 'direct content framing',
        lighting: 'balanced gym lighting',
      },
      {
        action: 'finishing the workout with a final pump-focused set',
        environment: 'mirror or machine area, sweat visible, gym atmosphere',
        mood: 'intense, satisfied, physically charged',
        camera: 'mirror pump shot',
        lighting: 'high contrast lighting',
      },
      {
        action: 'standing in front of the mirror post-workout, checking physique and muscle fullness',
        environment: 'gym mirror, post-training environment',
        mood: 'satisfied, proud, quietly confident',
        camera: 'mirror physique shot',
        lighting: 'harsh gym lighting emphasizing definition',
      },
    ],

    private: [
      {
        action: 'leaving the gym and walking home or to the car in a calm post-training state',
        environment: 'outside gym, street, or parking area',
        mood: 'relaxed, satisfied, grounded',
        camera: 'walking exit shot',
        lighting: 'natural daylight',
      },
      {
        action: 'showering and letting the body relax after the intensity of training',
        environment: 'bathroom, shower steam, private space',
        mood: 'resetting, calm, physical relief',
        camera: 'soft silhouette or indirect framing',
        lighting: 'soft warm bathroom light',
      },
      {
        action: 'getting dressed in clean clothes and transitioning into a more relaxed state',
        environment: 'bedroom or bathroom mirror',
        mood: 'calm, composed, post-workout ease',
        camera: 'mirror dressing shot',
        lighting: 'soft indoor lighting',
      },
      {
        action: 'preparing a post-workout meal with focus on nutrition and recovery',
        environment: 'kitchen, meal prep setup, clean surfaces',
        mood: 'intentional, disciplined, recovery-focused',
        camera: 'kitchen lifestyle shot',
        lighting: 'neutral daylight',
      },
      {
        action: 'eating slowly and checking content performance or engagement',
        environment: 'table, phone, relaxed environment',
        mood: 'calm, reflective, slightly engaged',
        camera: 'seated casual shot',
        lighting: 'soft indoor light',
      },
      {
        action: 'editing gym clips and selecting the best moments for posting',
        environment: 'desk, laptop or phone, quiet room',
        mood: 'focused, strategic, creator mindset',
        camera: 'over-shoulder editing shot',
        lighting: 'neutral workspace light',
      },
      {
        action: 'posting content and observing audience reactions carefully',
        environment: 'phone screen glow, quiet environment',
        mood: 'aware, slightly anticipatory, controlled',
        camera: 'close interaction shot',
        lighting: 'soft ambient light',
      },
      {
        action: 'resting physically while maintaining a composed and confident presence',
        environment: 'sofa, bed, or relaxed interior',
        mood: 'calm, grounded, quietly confident',
        camera: 'relaxed lifestyle shot',
        lighting: 'warm soft light',
      },
    ],

    night: [
      {
        action: 'going for a light walk or stretching session to unwind the body',
        environment: 'outdoor night or quiet indoor space',
        mood: 'calm, reflective, balanced',
        camera: 'slow movement shot',
        lighting: 'soft night lighting',
      },
      {
        action: 'replying to messages or comments with a calm, controlled tone',
        environment: 'phone in hand, dim environment',
        mood: 'engaged, composed, intentional',
        camera: 'close interaction framing',
        lighting: 'screen glow',
      },
      {
        action: 'preparing for sleep while mentally reviewing the day and progress',
        environment: 'bedroom, low light, quiet atmosphere',
        mood: 'reflective, disciplined, focused on growth',
        camera: 'soft bedroom shot',
        lighting: 'warm night light',
      },
      {
        action: 'lying down and letting the body fully recover from the day',
        environment: 'bed, calm room, no distractions',
        mood: 'restful, complete, grounded',
        camera: 'wide still shot',
        lighting: 'very low soft light',
      },
      {
        action: 'closing the day with a sense of progress and quiet confidence',
        environment: 'darkened room, stillness',
        mood: 'fulfilled, calm, strong internal confidence',
        camera: 'final still frame',
        lighting: 'minimal ambient light',
      },
      {
        action: 'checking the final post performance one last time before putting the phone away for the night',
        environment: 'bedside, dim bedroom, phone glow, quiet late-night atmosphere',
        mood: 'calm, satisfied, slightly reflective',
        camera: 'bedside close interaction shot',
        lighting: 'soft screen glow with low warm room light',
      },
      {
        action: 'settling fully into sleep after a disciplined day of training, content, and recovery',
        environment: 'dark bedroom, soft bedding, still private space',
        mood: 'complete, peaceful, physically restored',
        camera: 'wide end-of-day sleeping composition',
        lighting: 'very soft fading night light',
      },
    ],
  },
}