export const WORLD_ONLYFANS_CREATOR = {
  id: 'onlyfans_creator',
  name: 'OnlyFans Creator Life',

  phases: {
    morning: [
      {
        action: 'waking slowly in a private bedroom and reaching for the phone before fully opening the day',
        environment: 'soft bed, quiet room, personal private space, low morning noise',
        mood: 'soft, intimate, just-awake calm',
        camera: 'over-bed candid morning angle',
        lighting: 'soft natural morning light',
      },
      {
        action: 'checking overnight messages and deciding which attention deserves a reply',
        environment: 'bedroom, phone in hand, private creator setting',
        mood: 'aware, selective, quietly in control',
        camera: 'close candid interaction framing',
        lighting: 'window-lit bedroom glow',
      },
      {
        action: 'standing in front of the mirror and reading posture, expression, and mood before the day begins',
        environment: 'mirror, soft bedroom textures, private apartment atmosphere',
        mood: 'self-aware, calm, subtly provocative',
        camera: 'mirror-side full-body framing',
        lighting: 'soft morning contrast',
      },
      {
        action: 'moving through the apartment in an unhurried rhythm while thinking through the tone of the day',
        environment: 'private home interior, kitchen or hallway, personal lived-in space',
        mood: 'private, measured, naturally magnetic',
        camera: 'lifestyle movement shot',
        lighting: 'clean indoor daylight',
      },
      {
        action: 'making coffee or a light breakfast while still half inside the quiet of the morning',
        environment: 'small luxury kitchen, mug, breakfast details, intimate home environment',
        mood: 'personal, slow, real, emotionally accessible',
        camera: 'kitchen candid medium shot',
        lighting: 'bright natural daylight',
      },
      {
        action: 'changing into a more intentional daytime look and preparing the room for filming',
        environment: 'bedroom, tripod, mirror, clothing choices, private creator setup',
        mood: 'ready, deliberate, lightly escalating',
        camera: 'getting-ready editorial framing',
        lighting: 'soft neutral room light',
      },
    ],

    day: [
      {
        action: 'setting the room and testing early daytime angles before recording',
        environment: 'bedroom, mirror corner, chair or bed setup, controlled private environment',
        mood: 'focused, creator-minded, quietly charged',
        camera: 'behind-the-scenes setup angle',
        lighting: 'clean midday natural light',
      },
      {
        action: 'recording casual clips that feel personal, close, and viewer-aware without being rushed',
        environment: 'private room, soft textures, intentional interior framing',
        mood: 'inviting, intimate, controlled',
        camera: 'medium-close creator framing',
        lighting: 'soft daylight with gentle shadows',
      },
      {
        action: 'watching the footage back immediately to judge what feels real enough to keep',
        environment: 'phone screen, bed edge, mirror nearby, calm private space',
        mood: 'selective, emotionally aware, quietly exacting',
        camera: 'over-shoulder playback angle',
        lighting: 'soft indoor daylight',
      },
      {
        action: 'replying to certain audience messages while holding a measured distance',
        environment: 'private apartment, phone in hand, seated personal setting',
        mood: 'engaged, exclusive, carefully responsive',
        camera: 'seated candid interaction shot',
        lighting: 'light afternoon room glow',
      },
      {
        action: 'filming a second set with slower movement and more intentional eye contact',
        environment: 'private room, mirror or bed area, minimal creator setup',
        mood: 'stronger tension, deliberate intimacy, calm control',
        camera: 'mirror or direct medium framing',
        lighting: 'warmer interior-afternoon blend',
      },
      {
        action: 'pausing after filming and moving through the room with the energy still present',
        environment: 'quiet apartment, hallway or window zone, private creator atmosphere',
        mood: 'lingering tension, self-possession, subtle authority',
        camera: 'slow transition tracking angle',
        lighting: 'soft late afternoon light',
      },
      {
        action: 'editing content, trimming moments, and deciding what remains exclusive',
        environment: 'desk or bed setup, laptop, phone, creator workflow space',
        mood: 'strategic, high-control, modern',
        camera: 'over-shoulder editing composition',
        lighting: 'neutral workspace light',
      },
      {
        action: 'holding back some content and saving stronger material for later release',
        environment: 'private interior, phone and laptop nearby, low-distraction creator setting',
        mood: 'calculated, exclusive, in control of access',
        camera: 'quiet creator planning shot',
        lighting: 'soft ambient afternoon light',
      },
      {
        action: 'resetting the room and herself before the evening takes on a more intense tone',
        environment: 'bedroom, mirror, tidy private surroundings, content set in transition',
        mood: 'measured, intimate, preparing for escalation',
        camera: 'pre-evening reset portrait angle',
        lighting: 'golden hour moving into warm indoor light',
      },
    ],

    private: [
      {
        action: 'touching up hair, expression, and body language with more purpose before the evening set',
        environment: 'mirror, vanity, low private room sound, softly styled personal space',
        mood: 'intentional, controlled, more provocative',
        camera: 'mirror-side preparation shot',
        lighting: 'warm flattering vanity light',
      },
      {
        action: 'choosing the stronger evening look and testing how it reads in motion and stillness',
        environment: 'bedroom, outfit choices, mirror, tripod, private creator atmosphere',
        mood: 'selective, self-aware, emotionally charged',
        camera: 'full-body mirror framing',
        lighting: 'soft warm indoor glow',
      },
      {
        action: 'recording slower clips built around presence, pacing, and direct viewer awareness',
        environment: 'private room, soft bed or chair area, minimal distractions, intimate content zone',
        mood: 'deliberate, intimate, tension-forward',
        camera: 'cinematic medium-close shot',
        lighting: 'low-key warm shadows',
      },
      {
        action: 'pausing between takes and deciding how far the mood should go without losing control',
        environment: 'phone screen, room stillness, private filming environment',
        mood: 'measured, exclusive, creator-led tension',
        camera: 'over-shoulder private review shot',
        lighting: 'soft moody room light',
      },
      {
        action: 'replying privately to selected audience messages while the room remains quiet and charged',
        environment: 'bed edge, chair, or window seat, darkening room, phone glow',
        mood: 'exclusive, intimate, highly controlled',
        camera: 'night interaction medium shot',
        lighting: 'screen glow and soft lamp light',
      },
      {
        action: 'holding still in front of the camera long enough to let expression do more than movement',
        environment: 'private room, controlled set, minimal styling distractions',
        mood: 'intense, emotionally direct, quietly dominant',
        camera: 'tight direct framing',
        lighting: 'soft low dramatic light',
      },
      {
        action: 'letting the room settle after filming while deciding what remains private and what gets released',
        environment: 'tripod, bed, low-lit private room, creator-after-set calm',
        mood: 'fulfilled, selective, powerful in restraint',
        camera: 'wide after-set composition',
        lighting: 'low warm ambient glow',
      },
      {
        action: 'sitting in stillness after the strongest content has been captured, fully aware of its effect',
        environment: 'quiet bedroom, dark private interior, soft textures, low external noise',
        mood: 'private authority, emotional control, after-intensity calm',
        camera: 'still intimate portrait shot',
        lighting: 'subtle night-room glow',
      },
    ],

    night: [
      {
        action: 'releasing the strongest evening content and watching reactions arrive almost instantly',
        environment: 'dark bedroom or lounge, phone in hand, low-lit private atmosphere',
        mood: 'powerful, selective, emotionally in command',
        camera: 'phone-lit night close-up',
        lighting: 'screen glow with low room light',
      },
      {
        action: 'responding only where she wants to, keeping the strongest sense of access controlled',
        environment: 'bed edge, dark room, quiet creator night setting',
        mood: 'exclusive, magnetic, controlled intimacy',
        camera: 'night seated interaction framing',
        lighting: 'low-key intimate light',
      },
      {
        action: 'recording one final late-night clip with minimal movement and direct emotional presence',
        environment: 'private room, soft darkness, intimate controlled environment',
        mood: 'after-dark intensity, intimate focus, quiet dominance',
        camera: 'tight cinematic close framing',
        lighting: 'soft moody night light',
      },
      {
        action: 'leaning back after the final post and letting the performance layer drop away slowly',
        environment: 'bedroom, dim room, phone lowered, private silence returning',
        mood: 'drained, fulfilled, deeply private',
        camera: 'quiet end-of-session wide shot',
        lighting: 'warm bedside glow',
      },
      {
        action: 'removing the creator mindset piece by piece and settling back into herself',
        environment: 'mirror corner or bedside space, calm room, intimate night environment',
        mood: 'softened, personal, emotionally settled',
        camera: 'gentle unwinding portrait angle',
        lighting: 'very soft warm night light',
      },
      {
        action: 'lying down after the final interaction and letting the attention of the day fade out',
        environment: 'soft bed, dark room, phone off to the side, room at rest',
        mood: 'quiet afterglow, complete, intimate calm',
        camera: 'wide still bedtime composition',
        lighting: 'low fading bedside light',
      },
      {
        action: 'ending the day in full privacy after controlling the pace, mood, and access from start to finish',
        environment: 'dark private bedroom, minimal sound, soft luxury textures',
        mood: 'resolved, powerful, emotionally closed for the night',
        camera: 'final end-of-day still frame',
        lighting: 'very soft near-dark night light',
      },
    ],
  },
}