export const STORY_WORLD_BOUDOIR = {
  id: 'boudoir',
  name: 'Boudoir',
  description:
    'A cinematic boudoir world of intimate luxury — silk sheets, mirror rituals, vanity candlelight, lace and satin, the private feminine world at its most beautiful and intentional. Sensual, elegant, personal, powerful.',

  geography: { country: 'private interior', region: 'intimate boudoir suite' },

  identity: {
    archetype: 'intimate luxury creator',
    vibe: ['silk and satin in candlelight', 'private feminine power', 'mirror honesty', 'sensual self-possession', 'the bedroom as the most powerful room'],
    tone: ['sensual', 'intimate', 'candlelit', 'silk-soft', 'mirror-honest', 'quietly powerful', 'warm'],
    persona: ['completely at ease in her most intimate and private world', 'fully in control of the image she creates', 'beautiful without trying and powerful because of it', 'the camera as intimate witness not audience'],
  },

  phaseOrder: ['wake', 'morning_refresh', 'getting_dressed', 'breakfast', 'late_morning', 'lunch', 'afternoon', 'reset', 'golden_hour', 'dinner', 'evening', 'night'],

  phases: {
    wake:            { label: 'Wake',            timeWindows: ['soft morning light on silk sheets', 'pale bedroom dawn'],              pacing: 'slow',   subLocations: ['bedroom-suite', 'bedside-zone'] },
    morning_refresh: { label: 'Morning Refresh', timeWindows: ['warm bathroom morning', 'vanity daylight'],                           pacing: 'slow',   subLocations: ['bathroom-vanity', 'mirror-corner'] },
    getting_dressed: { label: 'Getting Dressed', timeWindows: ['morning dressing light', 'wardrobe soft interior'],                   pacing: 'slow',   subLocations: ['mirror-corner', 'wardrobe-zone'] },
    breakfast:       { label: 'Breakfast',       timeWindows: ['kitchen morning light', 'window glow'],                               pacing: 'slow',   subLocations: ['kitchen-zone', 'window-zone'] },
    late_morning:    { label: 'Late Morning',    timeWindows: ['clean indoor natural light', 'morning content window'],               pacing: 'medium', subLocations: ['mirror-corner', 'bedroom-suite'] },
    lunch:           { label: 'Lunch',           timeWindows: ['soft afternoon room light', 'midday lounge'],                         pacing: 'slow',   subLocations: ['lounge-zone', 'chaise-longue'] },
    afternoon:       { label: 'Afternoon',       timeWindows: ['warm afternoon interior', 'bath or window light'],                    pacing: 'slow',   subLocations: ['bath-zone', 'window-zone', 'chaise-longue'] },
    reset:           { label: 'Reset',           timeWindows: ['late afternoon vanity light', 'golden pre-evening'],                  pacing: 'slow',   subLocations: ['vanity-zone', 'mirror-corner'] },
    golden_hour:     { label: 'Golden Hour',     timeWindows: ['warm amber interior glow', 'window golden hour light'],               pacing: 'slow',   subLocations: ['window-zone', 'vanity-zone', 'bedroom-suite'] },
    dinner:          { label: 'Dinner',          timeWindows: ['candlelit room', 'early evening warm interior'],                      pacing: 'slow',   subLocations: ['bedroom-suite', 'vanity-zone', 'chaise-longue'] },
    evening:         { label: 'Evening',         timeWindows: ['low warm evening ambient', 'intimate evening light'],                 pacing: 'slow',   subLocations: ['bedroom-suite', 'mirror-corner', 'chaise-longue'] },
    night:           { label: 'Night',           timeWindows: ['candlelight only', 'very soft warm night light'],                     pacing: 'slow',   subLocations: ['bedroom-suite', 'bedside-zone'] },
  },

  locations: [
    'silk-sheeted bed in morning or candlelight', 'full-length bedroom mirror', 'vanity table with jewelry and perfume',
    'window with sheer curtain in warm light', 'deep bathtub with candles and rose petals', 'walk-in wardrobe with lace and silk',
    'chaise longue in warm interior light', 'penthouse bedroom with city view', 'candle-lit intimate room',
  ],

  subLocations: {
    'bedroom-suite': {
      id: 'bedroom-suite', name: 'Bedroom Suite', mapAnchor: 'private boudoir bedroom',
      category: 'private-core',
      bestPhases: ['wake', 'late_morning', 'dinner', 'evening', 'night'],
      overlays: ['silk bedding', 'warm ambient light', 'private intimate atmosphere', 'velvet or linen textures'],
      locations: ['silk-sheeted bed', 'soft pillow arrangement', 'private bedroom interior', 'warm bedroom corner'],
    },
    'bedside-zone': {
      id: 'bedside-zone', name: 'Bedside Zone', mapAnchor: 'bedside table area',
      category: 'wake-detail',
      bestPhases: ['wake', 'night'],
      overlays: ['bedside candle or lamp', 'perfume bottle nearby', 'silk sheets', 'quiet intimate detail'],
      locations: ['bedside table with candle and perfume', 'soft sheets edge', 'intimate morning detail'],
    },
    'bathroom-vanity': {
      id: 'bathroom-vanity', name: 'Bathroom Vanity', mapAnchor: 'private boudoir bathroom',
      category: 'self-care',
      bestPhases: ['morning_refresh'],
      overlays: ['bathroom mirror lit', 'beauty products arranged', 'steam or warm light', 'private ritual atmosphere'],
      locations: ['bathroom vanity mirror', 'beauty ritual setting', 'warm private bathroom', 'skincare ritual corner'],
    },
    'mirror-corner': {
      id: 'mirror-corner', name: 'Mirror Corner', mapAnchor: 'full-length bedroom mirror',
      category: 'reflection-styling',
      bestPhases: ['morning_refresh', 'getting_dressed', 'late_morning', 'reset', 'evening'],
      overlays: ['full-length mirror', 'warm interior light', 'reflection framing', 'intimate self-study'],
      locations: ['full-length mirror', 'mirror reflection zone', 'private styling mirror', 'bedroom mirror corner'],
    },
    'wardrobe-zone': {
      id: 'wardrobe-zone', name: 'Wardrobe Zone', mapAnchor: 'walk-in wardrobe',
      category: 'dressing',
      bestPhases: ['getting_dressed'],
      overlays: ['lace and silk hanging', 'warm wardrobe interior light', 'lingerie and robes arranged', 'intimate dressing energy'],
      locations: ['walk-in wardrobe with lace and silk', 'lingerie selection corner', 'private dressing zone'],
    },
    'kitchen-zone': {
      id: 'kitchen-zone', name: 'Kitchen Zone', mapAnchor: 'boudoir apartment kitchen',
      category: 'lifestyle-morning',
      bestPhases: ['morning_refresh', 'breakfast'],
      overlays: ['morning coffee setup', 'soft interior daylight', 'rose or candle on counter', 'intimate morning atmosphere'],
      locations: ['kitchen with morning coffee', 'intimate apartment kitchen morning'],
    },
    'window-zone': {
      id: 'window-zone', name: 'Window Zone', mapAnchor: 'sheer-curtain window light',
      category: 'light-mood',
      bestPhases: ['breakfast', 'afternoon', 'golden_hour'],
      overlays: ['sheer curtain moving in light', 'soft directional daylight', 'warm window glow', 'private intimate frame'],
      locations: ['window with sheer curtain', 'golden window light corner', 'soft window morning light'],
    },
    'lounge-zone': {
      id: 'lounge-zone', name: 'Lounge Zone', mapAnchor: 'intimate lounge area',
      category: 'leisure',
      bestPhases: ['lunch', 'afternoon'],
      overlays: ['soft lounge interior', 'warm ambient light', 'plush textures', 'private afternoon ease'],
      locations: ['private lounge with soft lighting', 'intimate sofa area', 'boudoir lounge corner'],
    },
    'chaise-longue': {
      id: 'chaise-longue', name: 'Chaise Longue', mapAnchor: 'bedroom chaise or daybed',
      category: 'reclining-luxury',
      bestPhases: ['lunch', 'afternoon', 'dinner', 'evening'],
      overlays: ['velvet or silk chaise', 'warm ambient lamp beside', 'private reclining luxury', 'intimate afternoon or evening'],
      locations: ['velvet chaise longue', 'silk daybed in warm light', 'private reclining corner'],
    },
    'bath-zone': {
      id: 'bath-zone', name: 'Bath Zone', mapAnchor: 'deep bathtub with candles',
      category: 'sensory-ritual',
      bestPhases: ['afternoon'],
      overlays: ['deep bathtub with candles', 'rose petals on water', 'steam and warm light', 'private ritual bathing'],
      locations: ['deep bathtub with rose petals and candles', 'candlelit bath ritual', 'warm private bath setting'],
    },
    'vanity-zone': {
      id: 'vanity-zone', name: 'Vanity Zone', mapAnchor: 'vanity table with mirror and lights',
      category: 'preparation-ritual',
      bestPhases: ['reset', 'golden_hour', 'dinner'],
      overlays: ['lit vanity mirror', 'perfume and jewelry laid out', 'warm vanity bulb glow', 'private beauty ritual energy'],
      locations: ['vanity table with mirror and perfume', 'jewelry and beauty ritual zone', 'lit vanity mirror corner'],
    },
  },

  sceneVariants: {
    wake: ['waking slowly in silk sheets with soft light crossing the bedroom floor', 'lying still in warm boudoir morning before rising', 'first light entering through sheer curtains across white linen'],
    morning_refresh: ['morning skincare ritual at the vanity in soft daylight', 'wrapped in a silk robe at the bathroom mirror after showering', 'applying perfume and touching jewelry in the morning routine'],
    getting_dressed: ['choosing lace lingerie in front of the full-length mirror', 'stepping into silk and making small adjustments in the mirror', 'the slow ritual of selecting what to wear in warm wardrobe light'],
    breakfast: ['morning coffee at the window in a silk robe with sheer curtains behind', 'light breakfast with a rose beside it in warm boudoir morning light'],
    late_morning: ['mirror study in deliberate morning light — full-length, intimate, honest', 'candid bed-side moment in lace in natural late-morning light'],
    lunch: ['reclining on the chaise longue in soft afternoon light', 'slow midday in a private boudoir lounge in warm interior calm'],
    afternoon: ['long candlelit bath with rose petals and complete privacy', 'afternoon chaise recline in silk in warm room light', 'lying by the sheer window in warm afternoon glow'],
    reset: ['vanity ritual reset before the evening — perfume, jewelry, and deliberate presence', 'retouching at the lit vanity in warm late-afternoon indoor light'],
    golden_hour: ['golden window light falling across silk and skin in the most cinematic boudoir moment', 'standing at the golden-hour window in lace with warm amber light behind'],
    dinner: ['candlelit chaise or bedroom sitting in intimate warm evening', 'slow intimate dinner moment in a private boudoir room lit only by candles'],
    evening: ['lying across the bed in candlelight — the most intimate boudoir evening energy', 'mirror evening moment in low ambient intimate boudoir light'],
    night: ['candlelit bedside moment before sleep — silk, perfume, private calm', 'the final private boudoir moment — deep warm night light and silk sheets'],
  },

  actionPools: {
    wake: ['lying still in silk sheets before fully waking', 'reaching for perfume or phone beside the bed', 'stretching slowly in warm private morning'],
    morning_refresh: ['applying skincare at the vanity mirror', 'wrapping in a silk robe after showering', 'touching perfume and jewelry in the morning ritual'],
    getting_dressed: ['selecting lace or silk lingerie from the wardrobe', 'stepping in front of the mirror to check the look', 'adjusting small details with slow deliberate attention'],
    breakfast: ['making coffee in a silk robe in soft morning light', 'standing at the window with coffee and warm quiet around', 'placing a rose beside the breakfast cup'],
    late_morning: ['studying the full-length mirror with honest attention', 'lying on the bed in lace in clean natural light', 'moving slowly through the boudoir interior'],
    lunch: ['reclining on the chaise in warm afternoon light', 'lying on soft lounge furniture in private boudoir ease', 'slow idle private afternoon in silk'],
    afternoon: ['lying in a candlelit bath with rose petals and steam', 'reclining on the chaise by the window', 'slowly adjusting position in warm afternoon interior light'],
    reset: ['touching up at the lit vanity before the evening', 'applying perfume at the vanity mirror', 'placing jewelry on at the vanity in deliberate slow ritual'],
    golden_hour: ['standing in warm window light as it falls across silk and skin', 'turning slowly in golden-hour light in front of the mirror', 'the most cinematic boudoir window moment'],
    dinner: ['reclining on the chaise in candlelight', 'sitting at the bedroom edge in warm intimate evening', 'slow movement through the candlelit boudoir room'],
    evening: ['lying across the bed in warm intimate candlelight', 'touching perfume or fabric in low ambient boudoir evening', 'mirror moment in intimate low evening light'],
    night: ['the final candlelit bedside moment in silk', 'lying back in deep private boudoir calm', 'closing the day in the warmth of silk and candle'],
  },

  environmentPools: {
    wake: ['silk-sheeted bed in pale morning boudoir light', 'soft pillow and linen in warm pale first-light', 'private bedroom interior in early morning stillness'],
    morning_refresh: ['bathroom vanity with soft daylight and beauty products', 'bathroom mirror in clean natural morning light', 'warm private bathroom with steam and soft light'],
    getting_dressed: ['walk-in wardrobe with lace and silk in warm interior', 'full-length mirror corner in morning dressing light', 'private wardrobe zone with lingerie arranged'],
    breakfast: ['kitchen with rose and coffee in soft morning window light', 'window seat with sheer curtain and morning light', 'intimate apartment morning with coffee and calm'],
    late_morning: ['full-length mirror in clean natural late-morning light', 'silk-sheeted bed in natural daylight', 'private bedroom in honest clean morning interior'],
    lunch: ['chaise longue in soft warm afternoon boudoir light', 'private lounge with plush textures and warm ambient', 'intimate afternoon in soft interior glow'],
    afternoon: ['deep bathtub with candles, rose petals, and steam', 'chaise longue by the window in warm afternoon', 'soft boudoir interior in warm afternoon intimate light'],
    reset: ['lit vanity mirror with perfume and jewelry in late afternoon', 'vanity table in warm pre-evening indoor glow', 'intimate vanity ritual corner'],
    golden_hour: ['sheer-curtain window in full golden-hour amber light', 'bedroom with amber window light and silk catching gold', 'vanity in warm golden-hour indoor glow'],
    dinner: ['candlelit bedroom or chaise in intimate evening warm', 'warm boudoir interior lit only by candles', 'private dinner-hour candlelit intimate room'],
    evening: ['low ambient candlelit bedroom in evening warmth', 'mirror corner in intimate low evening light', 'soft private boudoir evening with warm textures'],
    night: ['candlelit bedside in deep private warm night', 'silk sheets in single warm night lamp glow', 'deep private boudoir night in warm darkness'],
  },

  moodPools: {
    wake: ['soft private intimate waking calm', 'silk-warm morning ease', 'unhurried boudoir morning luxury'],
    morning_refresh: ['clean private self-care ritual energy', 'warm fresh boudoir morning composure', 'private morning elegance in candlelit warmth'],
    getting_dressed: ['deliberate feminine preparation', 'slow beautiful dressing ritual', 'intimate self-aware morning transformation'],
    breakfast: ['quiet private morning ease', 'warm window-light boudoir calm', 'slow private luxury morning'],
    late_morning: ['honest intimate confidence', 'self-possessed boudoir natural presence', 'warm private editorial energy'],
    lunch: ['slow private afternoon indulgence', 'warm intimate leisure ease', 'reclining private boudoir calm'],
    afternoon: ['deep sensory bathing ritual pleasure', 'warm private boudoir afternoon luxury', 'slow intimate self-indulgence'],
    reset: ['deliberate vanity ritual composure', 'warm pre-evening feminine refinement', 'controlled private preparation energy'],
    golden_hour: ['the most cinematic boudoir moment — golden light on silk', 'warm intimate golden anticipation', 'beautiful private presence in perfect light'],
    dinner: ['warm candlelit intimate evening', 'slow private boudoir evening sensuality', 'deliberately intimate controlled warmth'],
    evening: ['deep private intimate warmth', 'low light boudoir feminine power', 'slow deliberate intimate evening'],
    night: ['the deepest most private boudoir calm', 'soft warm intimate night energy', 'completely private silk and candlelight stillness'],
  },

  cameraPools: {
    wake: ['85mm low angle from bed edge, shallow focus, window dissolved behind in morning light', '135mm close-up at face height, pale morning light defining skin edge against silk linen'],
    morning_refresh: ['85mm bathroom mirror close, reflection at same focal plane as subject', '50mm vanity mid shot, beauty products compressing behind in soft light'],
    getting_dressed: ['50mm mirror-framed full-length shot, wardrobe depth receding behind', '85mm mid-length dressing angle, soft room depth behind subject'],
    breakfast: ['85mm window-side seated, sheer curtain dissolving in morning bokeh', '50mm kitchen medium, morning light compressing behind subject'],
    late_morning: ['85mm mirror study, full-length honest framing', '135mm close-up at face or chest height, natural light defining detail'],
    lunch: ['85mm chaise long angle, warm room depth behind subject', '135mm reclining close, silk texture in sharp foreground'],
    afternoon: ['85mm bath bird\'s eye, candles creating warm secondary bokeh', '135mm close bath detail, steam diffusing background into warmth'],
    reset: ['85mm lit vanity close, vanity mirror creating double-image depth', '50mm vanity mid shot, warm interior depth behind'],
    golden_hour: ['135mm window backlit close, golden rim light defining edge of subject', '24mm wide window shot, golden light flooding the full room background'],
    dinner: ['85mm candlelit seated portrait, candle glow as key light source', '135mm intimate evening close, candle dissolved in warm background bokeh'],
    evening: ['85mm low ambient bedroom medium, warm glow filling soft background', '135mm intimate evening close, single lamp as sole source'],
    night: ['135mm candlelit bedside close-up, single candle as warm sole source', '85mm soft side angle, deep warm shadow framing subject'],
  },

  lightingPools: {
    wake: ['pale 5200K morning light entering through sheer curtains, long warm shadows across silk linen', 'soft diffused white morning entering through sheer fabric, warm edge on pillow and sheet'],
    morning_refresh: ['clean 5500K vanity daylight on bare skin and mirror, no harsh shadows', 'reflected morning light bouncing off white bathroom surfaces into the vanity interior'],
    getting_dressed: ['warm 4800K interior morning light on fabric and skin, gold catching detail', 'soft directional window light through curtains, even warm fill across the dressing area'],
    breakfast: ['warm 5000K morning window light, sheer curtain diffusing direct source to soft fill', 'kitchen morning light at shallow angle, coffee steam catching light'],
    late_morning: ['clean 5600K natural daylight through window, honest and direct, no artificial fill', 'soft interior noon light, even and flattering, natural color rendering'],
    lunch: ['warm 4000K afternoon room ambient, no direct source, even fill across lounge surfaces', 'soft filtered afternoon light through curtains, warm stripe across chaise fabric'],
    afternoon: ['candlelight at 1700K as primary source in bath, warm orange glow on steam and water', 'warm afternoon window at 4200K, soft and flattering across the chaise'],
    reset: ['warm 3200K vanity bulb ring, intimate close flattering light, no harsh shadow', 'warm vanity interior at 3000K, soft fill bouncing from mirror back'],
    golden_hour: ['rich 2800K golden window light entering at low angle, amber across silk and skin', 'warm golden backlight from window, rim lighting subject edge, room interior dissolved in glow'],
    dinner: ['candlelight at 1800K as sole key source, intimate warm fill, deep shadow beyond', 'warm 2500K single candle, flickering orange edge on skin and fabric'],
    evening: ['low 2400K ambient room lamp, soft warm fill, all surfaces in soft golden shadow', 'single bedside or chaise lamp at 2200K, intimate pool of warm light'],
    night: ['single candle at 1600K, deep warm orange light in total room darkness', 'bedside lamp at 2100K, soft warm pool in dark boudoir room'],
  },

  stylingPools: {
    wardrobe: {
      wake: ['silk nightgown or nothing in silk sheets', 'soft oversized sleep shirt', 'barely-there morning warmth'],
      morning_refresh: ['silk robe barely tied after shower', 'white towel wrapped after bath', 'skin-forward bare morning before dressing'],
      getting_dressed: ['lace bralette and matching set', 'sheer silk slip', 'intimate luxury lingerie in warm light'],
      breakfast: ['silk robe at kitchen window', 'soft morning wrap', 'barely dressed morning luxury at window'],
      late_morning: ['lace set in natural honest light', 'silk slip or bralette in morning bedroom', 'intimate daytime lingerie in clean light'],
      lunch: ['silk slip on chaise', 'lace cami and shorts on lounge furniture', 'soft feminine midday private wear'],
      afternoon: ['nothing in the bath — rose petals and steam', 'sheer wrap by the afternoon window', 'silk or lace on the chaise in afternoon light'],
      reset: ['dressing robe half-tied at vanity', 'silk slip at the lit mirror', 'pre-evening lingerie selection at vanity'],
      golden_hour: ['sheer lace against golden window light', 'silk against warm amber glow', 'the most photographic intimate look in golden-hour light'],
      dinner: ['silk corset or boned lingerie in candlelight', 'deep velvet robe in intimate evening', 'lace-and-silk evening intimate styling'],
      evening: ['low-cut silk or lace in warm ambient', 'intimate evening lingerie in deep warm glow', 'barely-there evening in low private light'],
      night: ['silk nightgown or body in candlelight', 'nothing but sheets in the final private night moment', 'soft night intimate luxury'],
    },
    details: {
      wake: ['undone morning hair on silk pillow', 'bare skin in early light', 'perfume bottle visible on bedside'],
      morning_refresh: ['damp skin after shower', 'hair pinned or loose after bathing', 'minimal bare skin in bathroom light'],
      getting_dressed: ['pearl or gold jewelry being placed on bare skin', 'slow deliberate hands on lace detail', 'perfume applied to throat or wrist'],
      breakfast: ['coffee cup against silk robe', 'rose petal on kitchen counter', 'morning hair loose in window light'],
      late_morning: ['honest bare-face or minimal makeup in natural light', 'gold detail catching natural light', 'soft deliberate posture at the mirror'],
      lunch: ['hair down on chaise', 'bare leg on velvet fabric', 'silk against skin on afternoon lounge'],
      afternoon: ['rose petals on bathwater surface', 'steam and damp skin in candlelight', 'wet hair after bath in warm light'],
      reset: ['perfume applied at the vanity', 'jewelry placed slowly in vanity light', 'hair pinned or finished at lit mirror'],
      golden_hour: ['golden light catching lace detail on skin', 'hair loose in amber backlight', 'jewelry glowing in warm window light'],
      dinner: ['candle-lit jewelry detail', 'deep lace or silk against candleflame', 'perfume and intimate styling in warm evening'],
      evening: ['hair loose in low ambient', 'bare skin in warm evening glow', 'silk and skin in intimate low light'],
      night: ['final perfume or candle detail', 'hair down in night private calm', 'silk against skin in candlelight'],
    },
    changeMoments: {
      wake: ['still in silk nightgown or nothing in sheets', 'pre-dressing private morning state'],
      morning_refresh: ['wrapped in a towel or robe after showering', 'between sleep and dressing in warm bathroom'],
      getting_dressed: ['mid-change in lace in front of the full mirror', 'choosing and placing intimate pieces in wardrobe light'],
      breakfast: ['already in morning robe or wrap at the window', 'dressed for the private morning not the world'],
      late_morning: ['in intimate daywear for the private morning', 'lace set in natural honest light'],
      lunch: ['relaxed silk on the chaise — soft afternoon private styling', 'barely changed from morning in warm midday ease'],
      afternoon: ['undressed for the bath or post-bath in a robe or nothing', 'between afternoon and evening in damp skin and warmth'],
      reset: ['between afternoon and evening at the vanity — refining and elevating', 'choosing the evening intimate look at the vanity mirror'],
      golden_hour: ['golden-hour intimate styling at its most photographic', 'wearing the elevated intimate evening look in amber light'],
      dinner: ['fully in the intimate evening look — silk, lace, candle warmth', 'candlelit boudoir intimate at its most beautiful'],
      evening: ['low-light intimate evening styling in warm ambient', 'deep private intimate evening wardrobe'],
      night: ['final private night styling — silk or nothing in candlelight', 'the most private and intimate end-of-night boudoir state'],
    },
  },

  sensoryPools: {
    wake: ['silk against bare skin in warm morning quiet', 'the scent of perfume in the still morning room', 'soft warm light and total privacy'],
    morning_refresh: ['warm water on skin in a private bathroom', 'perfume applied after shower — the ritual warmth', 'clean bare skin and morning light on the mirror'],
    getting_dressed: ['lace fabric against warm skin', 'cool gold jewelry placed on bare skin', 'the slow pleasure of intimate dressing in private'],
    breakfast: ['warm coffee in a silk-robe morning', 'light coming through sheer curtains on the face', 'rose scent and morning warmth'],
    late_morning: ['honest morning light on bare skin at the mirror', 'silk fabric and natural light together', 'the warm private intimacy of a natural boudoir morning'],
    lunch: ['velvet chaise against bare skin in warm afternoon', 'silk slip in afternoon indoor light', 'private slow afternoon warmth and ease'],
    afternoon: ['rose petal-scented bath water', 'candle warmth in a private steamy room', 'the deep pleasure of a long private bath'],
    reset: ['perfume being applied at the warm vanity', 'cool jewelry touching warm skin', 'lit vanity warmth and the ritual of preparation'],
    golden_hour: ['golden window light on silk and skin', 'warm amber air as the afternoon light changes', 'the most beautiful light in the boudoir world'],
    dinner: ['candle warmth in a private intimate room', 'silk fabric in warm flickering light', 'intimate darkness and warm candle air'],
    evening: ['low warm glow on skin and fabric', 'private intimate air in a dark warm room', 'the slow sensory warmth of a boudoir evening'],
    night: ['candlelight in total private darkness', 'silk sheets and warm candleflame scent', 'the deepest private boudoir warmth at night'],
  },

  socialEnergyPools: {
    wake: ['entirely private — no external presence, no performance', 'the most personal unwatched moment of the boudoir day'],
    morning_refresh: ['completely personal self-care, no outside eye', 'private ritual energy in warm intimate space'],
    getting_dressed: ['private transformation ritual — intimate and intentional', 'self-directed without audience in the wardrobe'],
    breakfast: ['private morning ease — silk and coffee and no one watching', 'soft private breakfast before any performance begins'],
    late_morning: ['first private intimate content energy of the day', 'honest self-study in natural light'],
    lunch: ['private lounge ease — intimate and unperforming', 'warm midday private boudoir rest'],
    afternoon: ['deeply private bath ritual — no performance, only sensation', 'slow intimate private afternoon'],
    reset: ['private preparation ritual at the vanity', 'controlled personal refinement before the evening'],
    golden_hour: ['the boudoir creator in full golden-hour photographic presence', 'slightly more visible — golden-hour is for the camera'],
    dinner: ['intimate candlelit warmth — controlled audience connection', 'slow deliberate intimate evening energy for the viewer'],
    evening: ['deepening intimacy — the boudoir evening begins its private escalation', 'warm low-light intimate presence'],
    night: ['the most intimate private moment of the boudoir day', 'final private warm boudoir night'],
  },

  atmospherePools: {
    wake: ['total private morning silence in a warm silk room', 'the boudoir at its most peaceful and unwatched', 'soft pale light and complete intimacy'],
    morning_refresh: ['private bathroom warm ritual atmosphere', 'steam, light, and self-care calm', 'the most personal intimate room at morning'],
    getting_dressed: ['warm wardrobe intimacy — the private dressing ritual', 'quiet selection and transformation energy'],
    breakfast: ['morning window light and coffee and silk — the best private morning atmosphere', 'gentle boudoir morning before the world'],
    late_morning: ['honest natural-light intimate atmosphere', 'boudoir in clean honest morning energy'],
    lunch: ['warm private afternoon indulgence on soft furniture', 'slow intimate midday boudoir ease'],
    afternoon: ['deep candlelit bath ritual atmosphere', 'the most private sensory intimate afternoon energy'],
    reset: ['warm vanity refinement atmosphere — deliberate and controlled', 'private preparation energy in warm indoor glow'],
    golden_hour: ['the golden-hour boudoir — the most cinematic private intimate moment', 'amber light and silk and total feminine presence'],
    dinner: ['candlelit intimate private evening atmosphere', 'warm boudoir dinner-hour private energy'],
    evening: ['deep warm intimate evening — the boudoir at its most deliberately intimate', 'low ambient warm private ease'],
    night: ['the deepest private boudoir night atmosphere — candle, silk, and total calm', 'complete private warm feminine power'],
  },

  propPools: {
    wake: ['silk pillows and white linen', 'perfume bottle on bedside table', 'sheer curtain barely moving in morning light'],
    morning_refresh: ['beauty products on vanity', 'white towel on hook or chair', 'candle beside bathroom mirror'],
    getting_dressed: ['lace bralette laid on wardrobe shelf', 'pearl or gold jewelry on the dressing table', 'silk robe on chair near mirror'],
    breakfast: ['coffee cup and rose on kitchen counter', 'white morning window light', 'sheer curtain framing the window'],
    late_morning: ['full-length mirror', 'silk sheets in natural light', 'scattered lace detail near the bed'],
    lunch: ['silk cushion on velvet chaise', 'afternoon glass of water or wine on lounge table', 'sheer fabric draped on chaise'],
    afternoon: ['rose petals on bath water surface', 'candles at bath edge', 'glass of wine or champagne near the bath'],
    reset: ['perfume bottle at lit vanity', 'jewelry box open on vanity table', 'lipstick and mirror detail at vanity'],
    golden_hour: ['sheer curtain in full amber window light', 'golden jewelry catching warm light', 'single rose in warm window glow'],
    dinner: ['candle as sole light source', 'champagne glass in candlelight', 'lace fabric against warm candle glow'],
    evening: ['ambient candle or lamp on side table', 'silk fabric in low warm light', 'perfume visible on bedside in low ambient'],
    night: ['single candle burning in darkness', 'silk sheets in warm candle glow', 'perfume and jewelry in quiet candlelit detail'],
  },

  bodyLanguagePools: {
    wake: ['soft reclined posture in silk sheets', 'half-awake slow stretch with relaxed limbs', 'rested private posture toward morning light'],
    morning_refresh: ['calm upright posture at vanity mirror', 'relaxed post-shower wrap posture', 'gentle self-care stance in private morning'],
    getting_dressed: ['deliberate slow movement while dressing', 'one-arm lift fastening jewelry', 'composed mirror assessment posture'],
    breakfast: ['relaxed robe posture at kitchen window', 'standing at window with cup — easy private stance', 'unhurried morning kitchen body language'],
    late_morning: ['composed self-study posture at full mirror', 'relaxed seated or standing morning intimate presence', 'easy natural body language in private space'],
    lunch: ['reclining chaise posture — fully private and at ease', 'slow comfortable afternoon body language', 'soft lounging intimate body ease'],
    afternoon: ['submerged bath posture — private sensory ease', 'reclining chaise afternoon body language', 'slow deliberate stretch in warm afternoon light'],
    reset: ['upright deliberate vanity posture', 'slow jewelry placement — hands and neck focused', 'composed pre-evening mirror assessment'],
    golden_hour: ['slow turn in golden window light', 'cinematic still posture in amber warmth', 'soft elevated body language in best light of the day'],
    dinner: ['slow deliberate candle-lit posture', 'reclining on chaise in candlelight with controlled ease', 'intimate seated body language in warm evening'],
    evening: ['soft reclining intimate evening body language', 'low slow movement in private intimate warm light', 'private composed feminine ease in warm glow'],
    night: ['fully reclined private bedside posture', 'slow intimate body language in candlelight', 'the most private still posture of the boudoir day'],
  },

  facialExpressionPools: {
    wake: ['just-awake softness — bare and private', 'rested morning gaze toward the light', 'slow waking private expression'],
    morning_refresh: ['focused self-study expression at the mirror', 'fresh bare-face morning calm', 'composed post-shower intimate expression'],
    getting_dressed: ['soft confident dressing-room gaze', 'deliberate self-aware mirror expression', 'light intimate composure while dressing'],
    breakfast: ['peaceful window-morning private expression', 'soft contentment with coffee in hand', 'unhurried warm morning ease on the face'],
    late_morning: ['honest natural-light expression — no performance', 'soft confident boudoir self-awareness', 'warm private morning self-study expression'],
    lunch: ['relaxed private afternoon expression', 'soft reclining boudoir ease', 'warm midday private feminine calm'],
    afternoon: ['eyes closed or half-open in bath sensory pleasure', 'slow private bath expression', 'deep sensory afternoon facial ease'],
    reset: ['deliberate focused vanity mirror expression', 'pre-evening composure building on the face', 'calm controlled preparation expression'],
    golden_hour: ['the most beautiful face of the day — in perfect golden light', 'soft warm cinematic expression in amber', 'quiet intimate magnetism in golden-hour glow'],
    dinner: ['warm candlelit intimate expression', 'slow deliberate evening eye contact', 'intimate private warm evening facial composure'],
    evening: ['deep private warm intimate expression', 'slow low-light boudoir evening gaze', 'soft intimate private evening calm'],
    night: ['the most private intimate night expression', 'warm eyes in candlelight — fully private', 'deep intimate nighttime stillness in the face'],
  },

  handDetailPools: {
    wake: ['hand resting on silk pillow edge', 'fingers lightly touching the linen beside', 'one hand near perfume bottle on bedside'],
    morning_refresh: ['hand on bathroom counter edge', 'fingers touching face in morning skincare', 'hand holding brush or product at vanity'],
    getting_dressed: ['fingers adjusting lace bralette strap', 'hand fastening jewelry at throat or wrist', 'fingers trailing over wardrobe fabric while selecting'],
    breakfast: ['hand around morning coffee cup', 'fingers touching the stem of the rose on the counter', 'resting hand on kitchen window ledge'],
    late_morning: ['hand touching mirror edge during self-study', 'fingers adjusting fabric or strap in mirror', 'one hand resting on hip at mirror'],
    lunch: ['hand trailing over velvet chaise fabric', 'fingers resting loosely on the lounge surface', 'hand near a glass of water or wine'],
    afternoon: ['hand resting on bath edge with rose petals', 'fingers in water with rose petals around', 'hand on the bath rim in candlelight'],
    reset: ['fingers holding perfume bottle at vanity', 'hand placing jewelry on at the lit mirror', 'fingertips applying lipstick or product'],
    golden_hour: ['hand holding sheer curtain edge in golden light', 'fingers trailing across silk in amber window glow', 'one hand touching jewelry in warm backlight'],
    dinner: ['hand near champagne glass in candlelight', 'fingers touching lace fabric in warm evening', 'slow hand placement on chaise or bed edge'],
    evening: ['hand resting against soft intimate surface in warm ambient', 'fingers touching fabric or skin in low evening light', 'deliberate slow hand movement in warm intimate glow'],
    night: ['hand near the candle in night darkness', 'fingers on silk sheet edge in candlelight', 'one hand resting near the face in deep intimate night warmth'],
  },

  movementEnergyPools: {
    wake: ['slow', 'private', 'waking'],
    morning_refresh: ['ritual', 'deliberate', 'intimate'],
    getting_dressed: ['slow', 'intentional', 'precise'],
    breakfast: ['unhurried', 'private', 'warm'],
    late_morning: ['composed', 'self-aware', 'intimate'],
    lunch: ['reclining', 'slow', 'private'],
    afternoon: ['sensory', 'still', 'warm'],
    reset: ['deliberate', 'composed', 'refining'],
    golden_hour: ['cinematic', 'slow', 'golden'],
    dinner: ['intimate', 'controlled', 'warm'],
    evening: ['slow', 'private', 'deliberate'],
    night: ['minimal', 'intimate', 'still'],
  },

  transitionPools: {
    human: {
      wake: ['waking slowly in the private boudoir morning', 'coming into the silk-soft first light'],
      morning_refresh: ['moving into the bathroom ritual', 'beginning the private morning self-care'],
      getting_dressed: ['choosing the intimate look of the day', 'the private dressing ritual begins'],
      breakfast: ['moving to the kitchen in a silk robe', 'the quiet morning coffee ritual'],
      late_morning: ['the natural light boudoir moment', 'honest private intimate morning presence'],
      lunch: ['settling into afternoon private ease', 'the slow midday boudoir rest'],
      afternoon: ['moving into the bath ritual', 'the private afternoon sensory moment'],
      reset: ['the vanity ritual reset before evening', 'refining for the intimate evening ahead'],
      golden_hour: ['the golden light boudoir moment — the most cinematic', 'amber window light on silk and skin'],
      dinner: ['candles lit, evening intimate energy begins', 'the warm boudoir evening moment'],
      evening: ['the intimate boudoir evening deepens', 'low light and warm private presence'],
      night: ['the final private boudoir candlelit night', 'the deepest warm intimate close of the day'],
    },
  },

  narrativeIntentPools: {
    wake: ['the private unwatched beginning of the most intimate day', 'silk and quiet before the world'],
    morning_refresh: ['turning sleep into feminine ritual through private self-care', 'the private morning that creates the day'],
    getting_dressed: ['choosing the intimate identity of the day in private warmth', 'the dressing ritual as the first act of self-possession'],
    breakfast: ['private morning ease before the boudoir world opens', 'silk and coffee and no performance required'],
    late_morning: ['honest intimate presence in natural morning light', 'the boudoir in its most truthful daytime form'],
    lunch: ['slow private feminine indulgence in warm afternoon light', 'the boudoir afternoon as pure private pleasure'],
    afternoon: ['deep sensory private ritual in candlelit warmth', 'the bath as the most intimate act of self-care'],
    reset: ['deliberate preparation for the evening escalation', 'the vanity as the threshold between day and night'],
    golden_hour: ['the most cinematic moment of the boudoir world — gold light on intimate beauty', 'amber warmth turning private luxury into art'],
    dinner: ['intimate controlled warm evening energy — the boudoir at dusk', 'candle and silk and deliberate intimate presence'],
    evening: ['the boudoir deepening into its most intimate evening form', 'warm low light and completely private feminine power'],
    night: ['the final intimate private night — the boudoir world complete', 'candle, silk, and total feminine calm'],
  },

  fallbackRules: {
    pacingProfile: { wake: 'slow', morning_refresh: 'slow', getting_dressed: 'slow', breakfast: 'slow', late_morning: 'slow', lunch: 'slow', afternoon: 'slow', reset: 'slow', golden_hour: 'slow', dinner: 'slow', evening: 'slow', night: 'slow' },
    repetitionBreakers: { avoidBackToBackSameLocation: true, avoidBackToBackSameLightingStyle: true, encourageWardrobeEvolution: true },
    worldDefaults: { allowSceneGroupFallbackToPhasePools: true, allowSubLocationFallbackToWorldPools: true, preferSceneGroupsWhenPresent: true },
  },

  exclusions: {
    premium: ['clinical or harsh lighting', 'gym or athletic settings', 'outdoor public spaces', 'busy backgrounds'],
    hard: ['daylight outdoor scenes', 'group social settings', 'office or corporate environments', 'cold or blue-toned lighting'],
  },

  routeRules: {
    worldIdentity: ['the boudoir world must feel deeply private, warm, intimate, and feminine — never performative or cold', 'silk, lace, candlelight, and mirrors are the core visual language'],
    humanFlow: ['the day moves from private morning waking through self-care ritual into afternoon sensory pleasure and evening escalating intimate warmth', 'every phase should feel like an invitation deeper into privacy'],
    styling: ['intimate apparel only — silk, lace, satin, robes, nightgowns, nothing public or athletic', 'jewelry and perfume are signature accessories'],
    atmosphere: ['candlelight, warm interior lamps, and golden-hour window light only — never harsh or cold', 'the boudoir is always warm, private, and beautiful'],
  },
}
