export const STORY_WORLD_DARK_FEMME = {
  id: 'dark-femme',
  name: 'Dark Femme',
  description:
    'A cinematic dark femme world of gothic glamour — velvet and black lace, deep shadow, dramatic candlelight, mysterious interior spaces, dark florals, red lips, and the particular power of a woman who owns the darkness completely.',

  geography: { country: 'private interior', region: 'dark luxury interior — gothic glamour suite' },

  identity: {
    archetype: 'dark femme — gothic luxury creator',
    vibe: ['velvet in candlelight', 'shadow as power', 'dark florals and black lace', 'mysterious interior depth', 'gothic feminine control'],
    tone: ['dark', 'dramatic', 'mysterious', 'powerful', 'elegant', 'gothic', 'controlled'],
    persona: ['completely at home in the darkness she creates', 'using shadow as eloquently as light', 'beautiful in a way that unsettles and magnetizes at once', 'the most powerful person in any dark room'],
  },

  phaseOrder: ['wake', 'morning_refresh', 'getting_dressed', 'breakfast', 'late_morning', 'lunch', 'afternoon', 'reset', 'golden_hour', 'dinner', 'evening', 'night'],

  phases: {
    wake:            { label: 'Wake',            timeWindows: ['first dark morning before curtains open', 'dim morning in a darkened room'],                pacing: 'slow',   subLocations: ['dark-bedroom', 'velvet-bed'] },
    morning_refresh: { label: 'Morning Refresh', timeWindows: ['dark bathroom in morning interior light', 'mirror in dim moody morning'],                   pacing: 'slow',   subLocations: ['dark-bathroom', 'vanity-dark'] },
    getting_dressed: { label: 'Getting Dressed', timeWindows: ['dim wardrobe morning light', 'dark dressing interior'],                                     pacing: 'slow',   subLocations: ['dark-wardrobe', 'full-mirror-dark'] },
    breakfast:       { label: 'Breakfast',       timeWindows: ['dark interior morning with dramatic window light', 'moody morning interior'],               pacing: 'slow',   subLocations: ['dark-interior-morning', 'window-dramatic'] },
    late_morning:    { label: 'Late Morning',    timeWindows: ['dramatic afternoon shadow interior', 'moody filtered indoor light'],                         pacing: 'medium', subLocations: ['dramatic-interior', 'full-mirror-dark'] },
    lunch:           { label: 'Lunch',           timeWindows: ['deep interior afternoon shadow', 'dark lounge midday'],                                      pacing: 'slow',   subLocations: ['dark-lounge', 'velvet-chair'] },
    afternoon:       { label: 'Afternoon',       timeWindows: ['deep shadow afternoon interior', 'candlelit afternoon room'],                                pacing: 'slow',   subLocations: ['dark-lounge', 'candle-room'] },
    reset:           { label: 'Reset',           timeWindows: ['pre-evening dark refinement', 'dim vanity preparation'],                                     pacing: 'slow',   subLocations: ['vanity-dark', 'full-mirror-dark'] },
    golden_hour:     { label: 'Golden Hour',     timeWindows: ['low amber dramatic window light', 'dark interior with warm amber edge'],                     pacing: 'slow',   subLocations: ['window-dramatic', 'dark-bedroom'] },
    dinner:          { label: 'Dinner',          timeWindows: ['candlelit dark dinner interior', 'deep warm evening shadow'],                                pacing: 'slow',   subLocations: ['candle-room', 'dark-dining'] },
    evening:         { label: 'Evening',         timeWindows: ['very low dark ambient evening', 'shadow-dominant intimate evening'],                         pacing: 'slow',   subLocations: ['dark-bedroom', 'velvet-chair', 'candle-room'] },
    night:           { label: 'Night',           timeWindows: ['near-total darkness with single candle or lamp', 'deep private dark night'],                 pacing: 'slow',   subLocations: ['dark-bedroom', 'velvet-bed'] },
  },

  locations: [
    'velvet-sheeted bed in deep dark interior', 'full-length mirror in dramatic shadow and light', 'dark wardrobe with black lace and velvet',
    'candlelit private room with dark florals', 'dramatic window with dark curtains partly open', 'velvet armchair in deep shadow',
    'dark lounge with warm amber candle glow', 'gothic vanity with lit mirror in darkness', 'dark dining space with candles and black roses',
  ],

  subLocations: {
    'dark-bedroom': {
      id: 'dark-bedroom', name: 'Dark Bedroom', mapAnchor: 'gothic luxury bedroom',
      category: 'private-core-dark',
      bestPhases: ['wake', 'golden_hour', 'evening', 'night'],
      overlays: ['dark velvet or black linen', 'deep shadow dominant', 'warm amber edge light only', 'gothic private atmosphere'],
      locations: ['dark velvet bed in shadow', 'deep gothic bedroom interior', 'private dark bedroom with amber edge light'],
    },
    'velvet-bed': {
      id: 'velvet-bed', name: 'Velvet Bed', mapAnchor: 'velvet bedding zone',
      category: 'intimate-dark',
      bestPhases: ['wake', 'night'],
      overlays: ['black or deep velvet bedding', 'near-total darkness with single warm source', 'intimate dark private morning or night'],
      locations: ['velvet black bedding in darkness', 'deep dark intimate bed', 'gothic morning bed zone'],
    },
    'dark-bathroom': {
      id: 'dark-bathroom', name: 'Dark Bathroom', mapAnchor: 'moody gothic bathroom',
      category: 'self-care-dark',
      bestPhases: ['morning_refresh'],
      overlays: ['dramatic mirror light', 'dark tiles or surfaces', 'moody warm bath interior', 'gothic bathroom atmosphere'],
      locations: ['dark bathroom with dramatic mirror light', 'gothic bathroom vanity', 'moody warm bath interior'],
    },
    'vanity-dark': {
      id: 'vanity-dark', name: 'Dark Vanity', mapAnchor: 'gothic lit vanity',
      category: 'preparation-dark',
      bestPhases: ['morning_refresh', 'reset'],
      overlays: ['lit vanity mirror against dark background', 'beauty products in dramatic light', 'dark glamour preparation ritual'],
      locations: ['gothic lit vanity mirror', 'dark vanity ritual zone', 'dramatic beauty preparation setting'],
    },
    'dark-wardrobe': {
      id: 'dark-wardrobe', name: 'Dark Wardrobe', mapAnchor: 'gothic wardrobe',
      category: 'dressing-dark',
      bestPhases: ['getting_dressed'],
      overlays: ['black and deep velvet pieces hanging', 'dark wardrobe interior with single amber light', 'gothic dressing ritual'],
      locations: ['dark wardrobe with black lace and velvet', 'gothic dressing zone', 'dramatic wardrobe interior'],
    },
    'full-mirror-dark': {
      id: 'full-mirror-dark', name: 'Full Mirror Dark', mapAnchor: 'dramatic full-length mirror',
      category: 'reflection-dark',
      bestPhases: ['getting_dressed', 'late_morning', 'reset'],
      overlays: ['full-length mirror against dark background', 'dramatic side or rim light on subject', 'gothic self-study framing'],
      locations: ['full-length mirror in dramatic shadow', 'dark mirror corner with rim light', 'gothic reflection zone'],
    },
    'dark-interior-morning': {
      id: 'dark-interior-morning', name: 'Dark Morning Interior', mapAnchor: 'dark morning kitchen or lounge',
      category: 'lifestyle-dark',
      bestPhases: ['breakfast'],
      overlays: ['dark interior with morning light at window edge', 'black coffee in dramatic morning light', 'gothic morning atmosphere'],
      locations: ['dark kitchen with dramatic window edge', 'gothic morning interior with coffee', 'moody dark morning lounge'],
    },
    'window-dramatic': {
      id: 'window-dramatic', name: 'Dramatic Window', mapAnchor: 'dramatic dark curtain window',
      category: 'light-dark-contrast',
      bestPhases: ['breakfast', 'golden_hour'],
      overlays: ['dark curtain partially open', 'dramatic shaft of light on subject', 'high contrast dark and light window framing'],
      locations: ['dark curtain with dramatic shaft of light', 'gothic window dramatic contrast', 'amber light shaft through dark room'],
    },
    'dramatic-interior': {
      id: 'dramatic-interior', name: 'Dramatic Interior', mapAnchor: 'gothic dramatic room',
      category: 'editorial-dark',
      bestPhases: ['late_morning'],
      overlays: ['deep shadow interior', 'single directional key light', 'dramatic editorial dark atmosphere'],
      locations: ['dramatic gothic interior with single key light', 'dark editorial room setting', 'high contrast dark lounge'],
    },
    'dark-lounge': {
      id: 'dark-lounge', name: 'Dark Lounge', mapAnchor: 'gothic lounge area',
      category: 'leisure-dark',
      bestPhases: ['lunch', 'afternoon'],
      overlays: ['dark velvet lounge furniture', 'amber candle or lamp only', 'deep shadow lounge atmosphere'],
      locations: ['dark velvet lounge in amber light', 'gothic lounge interior', 'dark private afternoon lounge'],
    },
    'velvet-chair': {
      id: 'velvet-chair', name: 'Velvet Chair', mapAnchor: 'velvet throne chair',
      category: 'power-seat',
      bestPhases: ['lunch', 'evening'],
      overlays: ['dark velvet or throne-like chair', 'deep shadow behind', 'single warm key light on subject', 'gothic power seating'],
      locations: ['dark velvet throne chair in dramatic light', 'gothic power seat in deep shadow', 'dark velvet seated corner'],
    },
    'candle-room': {
      id: 'candle-room', name: 'Candle Room', mapAnchor: 'candlelit dark interior',
      category: 'intimate-dark-evening',
      bestPhases: ['afternoon', 'dinner', 'evening'],
      overlays: ['multiple candles as sole light source', 'deep warm orange glow in darkness', 'dark florals visible in candle warmth', 'gothic intimate atmosphere'],
      locations: ['candlelit dark room with dark florals', 'gothic candle interior', 'warm candle-only dark space'],
    },
    'dark-dining': {
      id: 'dark-dining', name: 'Dark Dining', mapAnchor: 'gothic candlelit dinner space',
      category: 'dining-dark',
      bestPhases: ['dinner'],
      overlays: ['dark table with candles', 'black roses or dark florals on table', 'gothic dinner atmosphere', 'deep shadow behind the table'],
      locations: ['dark candlelit dinner table with black roses', 'gothic dining interior', 'dramatic candlelit dinner setting'],
    },
  },

  sceneVariants: {
    wake: ['waking in dark velvet bedding with barely any light in the gothic morning', 'eyes opening slowly in near-darkness before any light is admitted', 'the dark femme morning — still and private in deep shadow'],
    morning_refresh: ['gothic bathroom mirror ritual in high-contrast dramatic light', 'dark vanity beauty ritual applying dark makeup in controlled interior light'],
    getting_dressed: ['choosing black lace or velvet from the dark wardrobe in single amber light', 'full-mirror dark study in dramatic rim light — the gothic self-possession ritual'],
    breakfast: ['black coffee in a dark moody morning interior with a single amber shaft of light', 'standing in the one warm beam in the dark morning room'],
    late_morning: ['full-length mirror in dramatic shadow — the dark editorial self-study', 'dark room editorial content in single directional key light'],
    lunch: ['reclining in the velvet chair in deep shadow and amber candle glow', 'the dark lounge afternoon — velvet, candle, and complete controlled ease'],
    afternoon: ['candlelit dark room with dark florals and warm orange glow in the afternoon', 'sitting among candles in deep shadow — private dark femme afternoon'],
    reset: ['gothic vanity ritual in dramatic lit mirror against darkness — dark lips being applied', 'the pre-evening dark femme refinement at the lit mirror'],
    golden_hour: ['amber shaft of light through dark curtains — the most dramatic moment in the dark femme day', 'golden-hour amber in a dark room — light as power rather than warmth'],
    dinner: ['candlelit dark dinner table with black roses and wine in warm orange glow', 'the dark femme dinner — deep shadow, candle, and complete control'],
    evening: ['deep in the dark velvet chair or on the dark bed with candle as the only light', 'the dark interior at full evening depth — velvet and shadow and warm flame'],
    night: ['near-total darkness with single candle barely burning — the dark femme at her most powerful', 'the final private dark moment in velvet and fading candlelight'],
  },

  actionPools: {
    wake: ['opening eyes slowly in near-darkness in velvet bedding', 'lying completely still in the dark before admitting any light', 'reaching for a dark candle or lamp at the bedside'],
    morning_refresh: ['applying dark makeup in dramatic bathroom mirror high-contrast light', 'dark lip ritual at the gothic lit vanity against darkness', 'the controlled dark beauty morning ritual in single warm light'],
    getting_dressed: ['selecting black lace or velvet from the dark wardrobe in amber light', 'slow deliberate dark dressing ritual in dramatic interior', 'placing dark garnet or onyx jewelry on in single-light wardrobe'],
    breakfast: ['drinking black coffee in a dark interior with one amber window light shaft', 'standing in the one warm beam in the dark morning room with coffee', 'the controlled dark morning before the day begins'],
    late_morning: ['the full-mirror dark study — dramatic rim light and deep shadow self-possession', 'moving through dark interior with complete control', 'filming in dramatic single-light dark editorial framing'],
    lunch: ['reclining in the dark velvet chair with amber candle as sole light', 'slow private dark afternoon in the deep lounge shadow', 'the dark femme at ease in complete shadow'],
    afternoon: ['sitting among candles and dark florals in a private dark afternoon', 'lying in the dark interior in warm candle orange', 'the slow dramatic dark afternoon ritual'],
    reset: ['dark lipstick application at gothic vanity in lit mirror', 'placing dark jewelry and completing dark makeup before evening', 'the deliberate dark preparation ritual at the vanity'],
    golden_hour: ['the amber shaft of light through dark curtains falling on skin and velvet', 'standing in the one dramatic ray of warm light in the dark room', 'the dark femme in her most cinematically powerful golden-hour moment'],
    dinner: ['sitting at the dark candlelit dinner table with black roses in warm orange glow', 'the dramatic dark dinner — controlled, mysterious, powerful', 'slow candle-lit dark meal with complete composed dark control'],
    evening: ['deep in the dark velvet chair in candle glow', 'the dark femme evening — shadow dominant with candle edge only', 'moving slowly through the dark room with warm candle barely holding'],
    night: ['the final dark femme night — near-total darkness with single dying flame', 'lying in velvet in the darkest most private interior at night', 'candle burning very low in near-darkness as the dark day ends'],
  },

  environmentPools: {
    wake: ['dark velvet bed in near-total morning darkness', 'gothic bedroom interior before any curtains open', 'deep shadow bedroom with warm amber edge barely visible at one side'],
    morning_refresh: ['gothic bathroom with high-contrast dramatic mirror light', 'dark vanity with lit mirror ring against dark background', 'moody warm dark bathroom morning interior'],
    getting_dressed: ['dark wardrobe interior with single amber light on black lace and velvet', 'full-length mirror in dramatic shadow with rim light only', 'gothic dressing ritual zone in dark interior'],
    breakfast: ['dark morning interior with amber shaft of window light cutting through', 'gothic kitchen or lounge with black coffee and dramatic morning contrast', 'moody dark apartment morning with one warm source'],
    late_morning: ['dramatic gothic interior with single directional key light on subject', 'full-length mirror in dark room with deep shadow behind', 'dark editorial interior controlled for drama'],
    lunch: ['dark velvet lounge with amber candle glow and deep shadow behind', 'velvet throne chair in dramatic dark afternoon candlelight', 'dark interior lounge lit only by amber candle'],
    afternoon: ['candlelit dark room with dark florals and warm orange light in deep shadow', 'dark interior in warm orange candle glow only', 'gothic afternoon — multiple candles in complete darkness'],
    reset: ['gothic lit vanity mirror in near-darkness — face lit, background dark', 'dark vanity ritual preparation zone at lit mirror', 'dramatic lit mirror face against deep dark room behind'],
    golden_hour: ['dark curtain partially open with amber shaft of light falling on subject', 'dark bedroom interior with one amber window beam entering', 'the most dramatic high-contrast golden-hour interior moment'],
    dinner: ['dark candlelit dinner table with black roses and deep shadow behind', 'gothic dining interior with candles as sole light source', 'dark dinner setting — controlled, mysterious, powerfully warm'],
    evening: ['deep dark velvet interior with candle as the sole source', 'dark velvet chair in dramatic candle glow', 'the dark room at full evening depth — shadow and warm flame barely holding'],
    night: ['near-total darkness with single low candle only', 'deep dark gothic bedroom in final candlelight', 'the darkest most private interior moment of the dark femme day'],
  },

  moodPools: {
    wake: ['dark private power before any light is admitted', 'the dark femme at her most private — in velvet darkness', 'mysterious morning control in deep shadow'],
    morning_refresh: ['gothic self-care ritual power in controlled dramatic light', 'dark bathroom composition and intensity energy', 'dark controlled morning composure at the lit mirror'],
    getting_dressed: ['the dark dressing ritual — deliberate, precise, and powerful', 'selecting darkness as the day\'s identity statement', 'gothic feminine preparation in single warm wardrobe light'],
    breakfast: ['dark controlled morning energy in the gothic interior', 'the dramatic dark morning with one warm beam', 'gothic private morning composure at the dark window'],
    late_morning: ['dramatic dark editorial presence in controlled interior', 'shadow as editorial visual language', 'the dark femme in controlled daylight — still dark by design'],
    lunch: ['private dark afternoon power in velvet and candle', 'deep shadow lounge ease in the dark femme world', 'the dark velvet afternoon — private and completely controlled'],
    afternoon: ['candlelit gothic afternoon intimacy', 'private dark sensory depth in warm candle orange', 'warm dark flame afternoon energy in deep shadow'],
    reset: ['the gothic refinement ritual at the lit vanity', 'dark pre-evening controlled preparation energy', 'deliberate dark feminine composure building for the evening'],
    golden_hour: ['the amber shaft in darkness — the most cinematically powerful dark femme moment', 'dramatic dark golden-hour contrast at maximum', 'the dark femme in the light that proves she owns the dark'],
    dinner: ['gothic candlelit dinner power — the most controlled beautiful dark moment', 'dark controlled mysterious elegance at the dinner table', 'the most deliberately powerful dark evening energy'],
    evening: ['deep dark intimate evening control — shadow everywhere', 'the dark femme at full shadow depth in candlelight', 'warm candle in total darkness — ultimate feminine gothic power'],
    night: ['the deepest darkest most private night of the dark femme world', 'candlelight in near-total darkness — maximum gothic intimate power', 'the dark femme complete and fully private in her world'],
  },

  cameraPools: {
    wake: ['85mm low angle from velvet bed edge, near-total shadow, single warm edge barely visible at one side', '135mm close-up in near-darkness — one warm amber source defining the edge of subject against black'],
    morning_refresh: ['85mm dramatic bathroom mirror, dark background, lit face in high contrast against darkness', '50mm vanity mid shot — lit face and dark background, beauty portrait in near-dark'],
    getting_dressed: ['50mm dark wardrobe framing, single amber light, deep black shadow behind subject', '85mm full-mirror dark study, dramatic rim light only from one side'],
    breakfast: ['85mm dark interior with amber light shaft from window, subject in high-contrast light versus dark', '35mm wide dark morning room with one warm shaft of window light cutting through'],
    late_morning: ['85mm single key light editorial in dark room, deep shadow behind subject throughout', '135mm close-up in controlled dramatic single key light against near-black background'],
    lunch: ['85mm velvet chair in amber candle glow, deep black shadow behind and around', '135mm dark lounge close, candle as the sole warm source for the frame'],
    afternoon: ['85mm candlelit dark room, multiple candles creating warm bokeh in dark background', '50mm dark interior with candle key light — warm orange fill in complete darkness'],
    reset: ['85mm lit vanity close, dark background behind, warm mirror light on face only', '50mm vanity shot — face lit by mirror ring against total darkness behind subject'],
    golden_hour: ['135mm dramatic amber shaft backlit close — warm rim light from window beam in dark room', '24mm wide dark room shot — one amber shaft of light crossing the dark background'],
    dinner: ['85mm dark candlelit table close, candle key source, deep shadow beyond and behind', '135mm dramatic dark dinner close-up, single candle in warm bokeh background'],
    evening: ['85mm velvet chair or dark bed in candle glow, shadow dominant frame throughout', '135mm dark intimate close in single warm candle source against deep dark'],
    night: ['135mm single candle close-up in near-total darkness — flame as sole warm source', '85mm very low light dark bedroom — minimal warm amber rim defining one edge only'],
  },

  lightingPools: {
    wake: ['near-total darkness with 1700K single warm amber edge from one side — no fill light, maximum shadow everywhere', 'deep dark morning — barely any light, velvet and skin in near-complete shadow'],
    morning_refresh: ['high-contrast bathroom mirror light at 3000K — harsh directional on face, complete darkness behind', 'lit vanity ring at 3200K against near-black background — studio portrait in darkness'],
    getting_dressed: ['1800K single amber source in dark wardrobe — deep shadow, warm edge on lace and velvet fabric and skin', 'single side key light at 2800K in dark interior — rim light defining subject against total darkness'],
    breakfast: ['one amber shaft of window light at 2700K cutting through dark curtained interior, all else in deep shadow', 'dark morning interior with 2500K single warm lamp as sole visible source'],
    late_morning: ['single directional key light at 3500K against dark room interior — editorial dark portrait lighting', 'controlled 4000K spot in dark room — intentional dark studio aesthetic throughout'],
    lunch: ['candle at 1700K as sole source in dark lounge — maximum orange warmth in near-darkness', 'warm 2200K single lamp in dark lounge, all background in deep shadow beyond visible'],
    afternoon: ['multiple candles at 1600K-1800K — warm orange fill from several directions in total darkness', 'candlelit dark room — no other source, warm orange on dark florals and skin throughout'],
    reset: ['vanity ring at 3000K against dark background — beauty portrait lighting in darkness', 'warm 2800K lit mirror against near-total dark background — face lit, all else dark'],
    golden_hour: ['amber 2600K shaft of directional light through dark curtain — highest contrast moment of day', 'warm backlight at 2700K through dark room — rim light only, deep shadow everywhere else'],
    dinner: ['candlelight at 1700K as sole key source — deep warm orange on dark table and dark roses', 'two candles at 1600K creating warm cross-light in dark dining space in total darkness'],
    evening: ['1600K deep orange candle in near-total darkness — velvet and shadow completely dominant', 'very low 2000K ambient from single lamp — maximum shadow depth throughout'],
    night: ['single candle flame at 1500K as the only source in total darkness', 'near-total dark — barely any ambient, single dying flame barely readable'],
  },

  stylingPools: {
    wardrobe: {
      wake: ['black silk or velvet nothing in darkness', 'deep black velvet sleep styling in dark sheets', 'minimal dark morning in black or deep charcoal linen'],
      morning_refresh: ['black silk robe or nothing in dark dramatic bathroom', 'dark feminine morning wrap at the gothic mirror', 'black robe barely closed at the dark vanity'],
      getting_dressed: ['black lace set or deep velvet lingerie in dramatic wardrobe light', 'sheer black slip in dramatic side light', 'dark velvet corset or deep lace intimate set'],
      breakfast: ['black silk robe at the dark morning window shaft', 'gothic wrap in dark interior morning', 'dark feminine morning interior look with dramatic shadow'],
      late_morning: ['black lace or velvet in editorial dark daylight', 'deep dramatic dark editorial daywear or lingerie', 'gothic dark feminine editorial look in controlled light'],
      lunch: ['black velvet or silk on dark velvet chair in amber candle', 'deep lace in dark lounge afternoon shadow', 'dark femme afternoon private wear in candle warmth'],
      afternoon: ['dark velvet robe or black slip among candles', 'black lace in warm candle dark afternoon', 'gothic dark feminine afternoon styling in candlelight'],
      reset: ['black silk or lace at the dark vanity in lit mirror', 'pre-evening dark refinement look at the gothic mirror', 'gothic preparation styling at lit mirror in darkness'],
      golden_hour: ['black lace against dramatic amber shaft of light', 'dark velvet in the one warm golden-hour beam', 'the dark femme at golden hour — shadow and amber in maximum contrast'],
      dinner: ['deep velvet corset or black evening look in candlelight', 'gothic candlelit dinner styling — lace, velvet, dark drama', 'black silk or velvet in warm dark candlelit dinner'],
      evening: ['deep velvet or black lace in deep candlelit intimate evening', 'dark femme evening intimate wear in warm amber glow', 'gothic evening intimate styling in near-darkness'],
      night: ['black velvet or silk in near-darkness — barely visible', 'the final dark private night look — deep shadow and barely seen', 'deep dark intimate night styling in last candle glow'],
    },
    details: {
      wake: ['dark matte nails against velvet in shadow', 'dark makeup barely visible in the near-darkness', 'black or dark jewelry near amber candle edge'],
      morning_refresh: ['dark red or black lip being applied at lit mirror', 'black or dark jewel detail in dramatic bathroom light', 'gothic beauty ritual at dark vanity in near-darkness'],
      getting_dressed: ['dark garnet or onyx jewelry placed on skin in wardrobe light', 'black lace detail in dramatic single source light', 'dark feminine accessories in amber wardrobe light'],
      breakfast: ['black coffee cup and dark floral detail in morning light shaft', 'dark matte lips in the one morning light beam', 'gothic morning detail in dark interior with one warm shaft'],
      late_morning: ['editorial dark makeup in controlled single light', 'dark jewelry in dramatic single-source light', 'dark feminine editorial detail in controlled darkness'],
      lunch: ['dark lip and matte finish in candle glow on velvet chair', 'velvet or dark lace fabric detail in amber candle light', 'gothic afternoon detail in warm candle'],
      afternoon: ['dark candle wax or dark floral near the subject in candlelight', 'black rose petal near candlelit setting', 'dark femme afternoon sensory detail in candle warmth'],
      reset: ['dark lipstick applied at vanity in lit mirror against darkness', 'dark jewelry placed on skin at dark vanity', 'gothic pre-evening refinement detail at the lit mirror'],
      golden_hour: ['dark makeup in dramatic amber shaft of light from window', 'onyx or garnet catching the one warm beam of light', 'dark lace in the golden-hour light shaft — high contrast'],
      dinner: ['dark roses on the table in candlelight', 'black velvet and dark jewelry in warm candle orange glow', 'gothic dinner styling detail — dark and precise'],
      evening: ['dark lip in warm candle glow in near-darkness', 'velvet and shadow detail in the dark evening', 'dark femme night detail in final warm candle'],
      night: ['dark nail barely visible in near-total darkness', 'candle and shadow only — minimal detail in the dark', 'dark intimate final night detail in near-dark'],
    },
    changeMoments: {
      wake: ['still in black or velvet before any light enters the dark room', 'the deepest private dark morning state'],
      morning_refresh: ['dark robe at bathroom mirror in dramatic light', 'between dark sleep and dark day at the gothic vanity'],
      getting_dressed: ['in the dark wardrobe selecting from darkness in amber light', 'the gothic dressing ritual in single source light'],
      breakfast: ['dark morning robe in dark interior morning with light shaft', 'gothic wrap at the dramatic dark window'],
      late_morning: ['editorial dark look in morning controlled light', 'dark femme daytime aesthetic in single key light'],
      lunch: ['dark afternoon private wear in velvet chair and candle', 'deep lounge dark styling in amber glow'],
      afternoon: ['dark velvet robe or nothing in candlelit dark room', 'between dark afternoon and pre-evening at the vanity'],
      reset: ['dark pre-evening refinement at the gothic vanity', 'gothic preparation for the evening escalation at the lit mirror'],
      golden_hour: ['dark femme in the amber shaft — the most powerful styling moment of the day', 'black lace in the one warm beam of light'],
      dinner: ['full gothic dinner look — velvet, lace, dark jewelry in candlelight', 'dark candlelit dinner styling at maximum depth'],
      evening: ['deep dark evening intimate styling in warm candle glow', 'gothic low-light evening wardrobe in near-darkness'],
      night: ['final darkest night styling — near-invisible in shadow', 'the most private dark femme night state in last candle'],
    },
  },

  sensoryPools: {
    wake: ['velvet against skin in near-total darkness', 'the smell of extinguished candle wax in the gothic morning room', 'total private dark silence before any light is admitted'],
    morning_refresh: ['cold dark tile and warm dramatic mirror light in contrast', 'the deliberate chill of dark morning self-care', 'dark beauty ritual warmth in controlled dramatic bathroom light'],
    getting_dressed: ['velvet and lace fabric in dramatic single-light wardrobe darkness', 'cool dark jewelry placed deliberately on warm skin', 'the slow dark pleasure of gothic dressing in amber light'],
    breakfast: ['black coffee in the dramatic dark morning interior', 'the amber light shaft on skin in cold dark room', 'the controlled dark morning sensory contrast'],
    late_morning: ['the dramatic dark interior — cool shadow and warm single key light in tension', 'dark editorial depth with controlled single source warmth', 'shadow as the completely dominant sensory environment'],
    lunch: ['velvet chair fabric against skin in amber candle warmth', 'candle scent in dark lounge afternoon', 'the slow dark private afternoon in warm orange candle air'],
    afternoon: ['warm candle heat in a completely dark room', 'dark floral scent in candlelit space', 'the particular warmth of multiple candles in deep total shadow'],
    reset: ['dark lipstick and cool jewelry in the warm vanity ritual', 'the deliberate dark preparation sensory at the lit mirror', 'gothic pre-evening beauty ritual warmth in near-darkness'],
    golden_hour: ['dramatic amber light on cold dark room surfaces', 'the temperature contrast of warm shaft and completely dark room', 'the most powerful sensory dark femme moment'],
    dinner: ['candle heat and dark rose scent at the dinner table', 'velvet and warm candle air in dark dining space', 'gothic dinner sensory depth in warm orange'],
    evening: ['deep warm candle in dark room — the dominant dark femme sensory', 'velvet in near-total darkness — the deepest sensory depth', 'the warmth of a single candle flame in complete private dark'],
    night: ['candle flame as the only warmth in total darkness', 'velvet and deep private dark room silence', 'the final dark sensory depth of the night'],
  },

  socialEnergyPools: {
    wake: ['completely private — the dark femme before any performance or light', 'no outside eye in the deepest dark private morning'],
    morning_refresh: ['private dark self-care — no audience, only the dramatic mirror', 'gothic morning ritual energy — self-directed and deliberate'],
    getting_dressed: ['deliberate dark private transformation ritual', 'the dark femme building her aesthetic with no external validation needed'],
    breakfast: ['dark private controlled morning — unseen and powerful', 'gothic interior morning energy before the world'],
    late_morning: ['first editorial dark content energy of the day in controlled light', 'dramatic dark self-presentation to the camera beginning'],
    lunch: ['private dark lounge energy — unperforming, completely at ease in shadow', 'the dark femme resting in her world without audience'],
    afternoon: ['deeply private dark intimate afternoon in candlelight', 'candlelit dark room — no performance, only presence and warmth'],
    reset: ['dark controlled self-refinement before the evening escalation', 'private gothic preparation ritual at the lit mirror'],
    golden_hour: ['the dark femme most cinematically visible — in dramatic amber and shadow', 'the camera receives the most powerful dark image of the day'],
    dinner: ['dark controlled intimate evening — deliberate audience connection in candlelight', 'gothic dinner hour — mysterious and magnetic and controlled'],
    evening: ['deep dark intimate evening escalation in near-darkness', 'the dark femme at her most deliberately intense and private'],
    night: ['completely private final dark moment — the darkest most intimate end', 'the dark femme world complete in near-total shadow'],
  },

  atmospherePools: {
    wake: ['near-total dark silence in velvet morning before light', 'gothic bedroom in its deepest private morning state', 'the dark femme world before any light is admitted'],
    morning_refresh: ['dark bathroom dramatic mirror ritual atmosphere in high contrast', 'gothic controlled morning interior in near-darkness', 'dark self-care in dramatic light-versus-shadow tension'],
    getting_dressed: ['dark wardrobe ritual atmosphere — quiet, deliberate, powerful in amber', 'the gothic dressing energy in near-darkness with single warm source'],
    breakfast: ['dark dramatic morning interior with one shaft of warm light', 'gothic morning with single dramatic light source cutting through dark', 'controlled dark morning atmosphere'],
    late_morning: ['dark editorial interior atmosphere in controlled single key', 'dramatic single-light dark room editorial energy', 'gothic editorial dark ambience at maximum'],
    lunch: ['dark velvet afternoon lounge atmosphere in amber candle', 'amber candle in deep shadow — dark private ease', 'gothic private afternoon depth and warmth'],
    afternoon: ['warm candle in total darkness atmosphere — the dark femme afternoon', 'candlelit gothic room with dark florals in deep shadow', 'the dark femme afternoon — private and powerfully dark'],
    reset: ['pre-evening dark refinement atmosphere at the lit vanity', 'gothic vanity ritual energy in lit mirror darkness', 'controlled dark preparation for the evening'],
    golden_hour: ['the most dramatic light-shadow contrast of the entire day', 'amber shaft in dark room — extraordinary high-contrast atmosphere', 'the dark femme golden hour — more dramatic than warm'],
    dinner: ['gothic candlelit dinner atmosphere — dark, warm, mysterious in candle orange', 'deep shadow dinner with candle and dark roses', 'the most controlled and powerfully dark evening atmosphere'],
    evening: ['deep dark warm evening atmosphere — shadow completely dominant', 'the dark femme world at full depth in candlelight', 'warm candle in absolute darkness — intimate and gothic powerful'],
    night: ['total dark atmosphere with single candle barely holding light', 'the deepest most private dark femme night in near-total darkness', 'gothic night in complete dark with barely any visible'],
  },

  propPools: {
    wake: ['black or deep velvet bedding in shadow', 'extinguished candle stub on bedside table', 'dark jewelry on bedside in near-darkness'],
    morning_refresh: ['dark ceramic or black beauty products at the vanity', 'dramatic bathroom lit mirror in dark room', 'dark floral or dried gothic arrangement near sink'],
    getting_dressed: ['black lace and velvet hanging in dark wardrobe in amber light', 'dark jewelry box open on dressing surface', 'dark rose on the dressing detail'],
    breakfast: ['black coffee in dark ceramic cup with amber light shaft', 'dark floral arrangement near dramatic window', 'one amber shaft of window light in dark curtained room'],
    late_morning: ['dramatic interior with single key light source on subject', 'dark editorial styling detail visible in controlled light', 'deep shadow filling most of the frame'],
    lunch: ['velvet chair or dark lounge surface', 'amber candle burning in dark lounge', 'dark floral arrangement in amber candle glow'],
    afternoon: ['multiple candles burning in completely dark room', 'black roses or dark dried florals in candle warmth', 'dark aesthetic detail in warm candle orange'],
    reset: ['dark lipstick on vanity surface', 'dark jewelry and beauty products at lit mirror', 'candle burning at the dark vanity in near-darkness'],
    golden_hour: ['dark curtain with amber shaft visible cutting through', 'dark jewelry catching the one warm light beam', 'dark velvet or lace in amber shaft detail'],
    dinner: ['black roses or dark florals on dinner table in candle', 'candles as sole light on dark table', 'dark gothic dinner setting with wine glass in warm orange glow'],
    evening: ['candle burning low in dark room', 'dark velvet furniture detail in warm candle', 'dark floral near warm candle edge in near-darkness'],
    night: ['single candle nearly burned down in darkness', 'near-dark velvet bed in final flame light', 'darkness as the dominant visual prop'],
  },

  bodyLanguagePools: {
    wake: ['reclined in near-total darkness — still and powerful in shadow', 'slow controlled dark morning posture in velvet sheets', 'lying in absolute dark with composed private presence'],
    morning_refresh: ['dramatic upright posture at dark bathroom mirror in contrast light', 'controlled dark vanity ritual posture', 'composed dark self-care stance in dramatic single light'],
    getting_dressed: ['deliberate slow wardrobe selection in single-light darkness', 'composed full-mirror dark self-study posture with rim light', 'the gothic dressing — precise and powerful in amber light'],
    breakfast: ['standing in one amber shaft of light in dark morning room', 'controlled morning posture in gothic dark interior', 'deliberate dark morning body language in the single warm beam'],
    late_morning: ['editorial dark stance in controlled single key light', 'composed dark interior posture — still and powerfully present', 'dark femme editorial body language in maximum shadow'],
    lunch: ['reclining in velvet chair in amber candle glow', 'composed dark private afternoon posture', 'slow powerful dark lounge body language in near-darkness'],
    afternoon: ['seated or reclining among candles in deep shadow', 'deliberate dark afternoon posture in warm candlelight', 'dark private sensory afternoon body language'],
    reset: ['upright deliberate vanity posture in lit mirror darkness', 'precise dark beauty ritual posture at the gothic vanity', 'composed dark pre-evening preparation stance'],
    golden_hour: ['standing in the amber shaft with full controlled composure', 'the most powerful dark femme posture — still in one dramatic beam', 'composed full-body dark golden-hour stance'],
    dinner: ['seated at dark dinner table with complete controlled composure', 'slow deliberate dark dinner posture in candlelight', 'gothic controlled elegant dinner stance'],
    evening: ['reclining in velvet chair or on dark bed in candle glow', 'slow intimate dark evening body language', 'the dark femme at her most composed and private in near-darkness'],
    night: ['near-still in near-total darkness — barely visible and completely controlled', 'the final dark private still posture', 'deep dark minimal movement in dying candlelight'],
  },

  facialExpressionPools: {
    wake: ['eyes opening slowly in darkness — still, private, and powerful', 'dark morning gaze — no softness, only controlled presence', 'deep private dark waking expression'],
    morning_refresh: ['dramatic mirror gaze — direct and completely self-possessed', 'dark controlled self-study expression at the gothic mirror', 'gothic morning beauty ritual expression in dramatic light'],
    getting_dressed: ['dark deliberate dressing expression — knowing and controlled', 'composed dark self-selection expression', 'gothic dressing expression — precise and self-aware'],
    breakfast: ['dark morning controlled expression in the one amber light shaft', 'composed dark morning face in dramatic interior', 'gothic private morning expression in warm beam'],
    late_morning: ['dark editorial expression — powerful and completely composed', 'direct dark camera gaze in single key light', 'dramatic dark self-possession completely readable on the face'],
    lunch: ['relaxed but powerful dark lounge expression', 'composed dark feminine ease in afternoon candle', 'gothic afternoon private expression in amber warmth'],
    afternoon: ['sensory dark afternoon expression — eyes partially closed in candle warmth', 'warm dark candlelit expression', 'gothic private afternoon facial energy in warm orange'],
    reset: ['dark preparation expression — controlled and deliberate at the vanity', 'focused dark vanity expression at lit mirror', 'pre-evening dark composure building on the face'],
    golden_hour: ['the most powerful dark femme expression — in dramatic amber shaft', 'controlled direct gaze in the amber window beam', 'the dark femme in her most dramatic photographic expression'],
    dinner: ['dark controlled dinner expression — mysterious and magnetic in candlelight', 'slow deliberate dark dinner eye contact', 'gothic candlelit dinner composure completely held'],
    evening: ['deep dark private intimate evening expression', 'warm candle-lit dark femme gaze — powerful, slow, and private', 'the most deliberate controlled dark evening expression'],
    night: ['eyes barely visible in near-darkness — the most private dark expression', 'candle flame barely reflected in eyes in deep dark', 'final dark private night expression in last warmth'],
  },

  handDetailPools: {
    wake: ['dark nails on velvet bedding in shadow — barely visible', 'hand at bed edge in near-darkness', 'one hand near dark candle stub on bedside'],
    morning_refresh: ['dark-nailed fingers at bathroom mirror in dramatic light', 'hand applying dark lipstick at vanity in lit mirror', 'fingertips touching dark beauty product at dark vanity'],
    getting_dressed: ['dark-nailed fingers selecting black lace from wardrobe in amber light', 'hand placing dark garnet or onyx jewelry on wrist or throat', 'fingers adjusting velvet or lace detail in single source'],
    breakfast: ['dark-nailed hand around black coffee cup in amber light shaft', 'fingers near dark floral detail in morning light shaft', 'hand visible in one amber beam in dark morning room'],
    late_morning: ['dark-nailed hand in dramatic single key light', 'fingers at rest on dark surface in editorial dark room', 'hand detail in controlled dark editorial lighting'],
    lunch: ['dark-nailed hand resting on velvet chair arm in candle glow', 'fingers near amber candle flame in dark lounge', 'hand trailing on velvet in warm dark candle'],
    afternoon: ['dark-nailed hand near candle flame in darkness', 'fingers touching dark rose petal in candlelight', 'hand visible in warm candle orange against complete darkness'],
    reset: ['dark-nailed fingers applying dark lipstick at vanity', 'hand placing garnet or onyx on wrist at lit vanity', 'fingers at lit vanity mirror in deliberate ritual'],
    golden_hour: ['dark-nailed hand catching the one amber shaft of light', 'dark jewelry in the single warm beam — the most powerful hand detail', 'fingers on dark velvet in amber light shaft'],
    dinner: ['dark-nailed hand near candlelit wine glass', 'fingers touching dark rose at dinner table in candle', 'hand resting on dark table edge in warm orange glow'],
    evening: ['dark-nailed fingers in warm candle glow in near-dark evening', 'hand on velvet chair arm in candlelight barely visible', 'subtle dark hand detail in warm low candle light'],
    night: ['dark nails barely visible in near-total darkness', 'hand near the last candle flame at night', 'final dark private hand placement in near-dark'],
  },

  movementEnergyPools: {
    wake: ['still', 'dark', 'private'],
    morning_refresh: ['controlled', 'deliberate', 'dark'],
    getting_dressed: ['precise', 'gothic', 'slow'],
    breakfast: ['composed', 'dark', 'controlled'],
    late_morning: ['editorial', 'still', 'dramatic'],
    lunch: ['reclining', 'dark', 'powerful'],
    afternoon: ['slow', 'sensory', 'dark'],
    reset: ['deliberate', 'gothic', 'refining'],
    golden_hour: ['still', 'dramatic', 'powerful'],
    dinner: ['slow', 'controlled', 'mysterious'],
    evening: ['minimal', 'dark', 'intimate'],
    night: ['near-still', 'private', 'complete'],
  },

  transitionPools: {
    human: {
      wake: ['waking in near-darkness in the gothic dark morning', 'the dark femme world opening slowly in deep shadow'],
      morning_refresh: ['the dark bathroom mirror ritual beginning in dramatic contrast', 'gothic self-care in controlled dramatic light'],
      getting_dressed: ['selecting from the dark wardrobe in single amber light', 'the gothic dressing ritual in near-darkness begins'],
      breakfast: ['the dark morning interior with one amber beam cutting through', 'black coffee in the gothic dark morning'],
      late_morning: ['dark editorial presence in controlled interior light', 'the dark femme in her most editorial controlled moment'],
      lunch: ['the dark velvet chair afternoon in candle glow', 'settling into deep shadow lounge ease'],
      afternoon: ['the candlelit dark room afternoon — multiple candles in shadow', 'private dark afternoon in warm candle orange'],
      reset: ['gothic vanity refinement at the lit mirror in darkness', 'preparing for the dark evening escalation'],
      golden_hour: ['the amber shaft through dark curtains — the defining dark femme moment', 'the most dramatic dark femme light of the entire day'],
      dinner: ['the dark dinner table lit only by candles with black roses', 'gothic dinner in deep shadow and warm orange flame'],
      evening: ['the dark femme at full evening depth in near-darkness', 'deep shadow and warm candle — the most intimate dark moment'],
      night: ['the final dark private night in near-total darkness', 'near-total darkness and the last dying candle'],
    },
  },

  narrativeIntentPools: {
    wake: ['the dark femme world before any light is admitted — pure private power in shadow', 'darkness as comfort, control, and complete identity'],
    morning_refresh: ['gothic self-care as power ritual — the dark morning belongs entirely to her', 'building the dark aesthetic from the inside out in dramatic light'],
    getting_dressed: ['selecting darkness as a deliberate identity statement every morning', 'the gothic dressing ritual as the first act of dark feminine power'],
    breakfast: ['the dark controlled morning — beauty in shadow before the world ever sees', 'the gothic morning interior as private power statement'],
    late_morning: ['dark editorial presence in controlled dramatic interior light', 'the dark femme making shadow her visual language and identity'],
    lunch: ['private dark afternoon ease in velvet and candle — no performance needed', 'the dark femme resting completely in her own world'],
    afternoon: ['candlelit dark afternoon — the most intimate dark sensory depth', 'private dark warmth as power and pleasure in near-total darkness'],
    reset: ['the gothic pre-evening refinement — deliberate, controlled, powerfully dark', 'building the evening dark aesthetic at the lit vanity in darkness'],
    golden_hour: ['one dramatic amber shaft in a dark room — the most powerful image of the dark femme day', 'light as the exception in a world of shadow — maximum dramatic contrast'],
    dinner: ['the dark candlelit dinner as controlled gothic power statement', 'the most deliberately beautiful dark evening moment'],
    evening: ['the dark femme at full depth — shadow dominant, warm flame barely holding light', 'the deepest most private dark evening power'],
    night: ['the final private darkness — the dark femme complete in near-total shadow', 'candle and velvet and the deepest private dark night'],
  },

  fallbackRules: {
    pacingProfile: { wake: 'slow', morning_refresh: 'slow', getting_dressed: 'slow', breakfast: 'slow', late_morning: 'medium', lunch: 'slow', afternoon: 'slow', reset: 'slow', golden_hour: 'slow', dinner: 'slow', evening: 'slow', night: 'slow' },
    repetitionBreakers: { avoidBackToBackSameLocation: true, avoidBackToBackSameLightingStyle: true, encourageWardrobeEvolution: true },
    worldDefaults: { allowSceneGroupFallbackToPhasePools: true, allowSubLocationFallbackToWorldPools: true, preferSceneGroupsWhenPresent: true },
  },

  exclusions: {
    premium: ['bright happy outdoor settings', 'pastel or light colour palettes', 'athletic gym settings', 'corporate or office environments'],
    hard: ['natural outdoor daylight', 'beach or pool settings', 'bright high-key lighting', 'cheerful social settings'],
  },

  routeRules: {
    worldIdentity: ['the dark femme world must feel genuinely dark — deep shadow, controlled dramatic light, gothic aesthetics throughout', 'black, velvet, dark lace, candles, and shadow are the complete visual language'],
    humanFlow: ['the day moves from deep dark morning through dramatic editorial moments to candlelit evening depth and near-total-dark night', 'light is always the exception — shadow is the absolute default'],
    styling: ['black, deep velvet, dark lace, and dark jewels throughout — no pastels or light fabrics ever', 'dark makeup including dark lips is a constant defining feature'],
    atmosphere: ['candlelight, dramatic single key lights, and amber window shafts — never bright or evenly filled', 'the dark room is always darker than expected — shadow dominates'],
  },
}
