export const STORY_WORLD_FITNESS_LIFE = {
  id: 'fitness-life',
  name: 'Fitness Life',
  description: 'Premium feminine fitness world — training floors, mirror zones, outdoor tracks, wellness cafés. Discipline as identity. The body as the ongoing project. Confidence earned in the 5am dark.',
  compatiblePlans: ['Soft', 'Fanvue', 'Premium'],
  defaultPack: 'fitness-influencer',
  defaultAgeRange: '22-35',

  subLocations: {
    'premium-gym': {
      name: 'Premium Gym',
      label: 'Gym · Training Floor',
      atmosphere: 'Black rubber floors, rack weight walls, cable machines in rows, chalk dust in the air, competition plates loaded, mirror walls reflecting effort, the hum of treadmills and serious focus',
      lightingBase: 'High-bay LED — 5000-6000K cold overhead. Harsh, direct, no flattery. Every muscle visible. Mirror bounces the light back. The gym does not soften anything.',
      sceneGroups: {
        weight_floor: { name: 'Weight Floor', description: 'Racks, plates, cables, training heavy' },
        cardio_zone: { name: 'Cardio Zone', description: 'Treadmill row, stairmaster, incline' },
        stretching_mat: { name: 'Mat Zone', description: 'Floor work, stretching, mobility' },
      },
    },
    'mirror-zone': {
      name: 'Mirror Zone',
      label: 'Mirror · Check-In',
      atmosphere: 'Full-length mirror wall, soft fill light, gymwear fitting perfectly, post-set pump, the half-second pause before the next set, the body honest and visible',
      lightingBase: 'Soft front fill — ring light or window beside the mirror. 4000-4500K neutral. The mirror doubles the light. Every detail shows.',
      sceneGroups: {
        mirror_solo: { name: 'Mirror Solo', description: 'Full body check, crop top, post-set' },
        mirror_content: { name: 'Content Shot', description: 'Phone angled, capturing form' },
        mirror_focus: { name: 'Focus Close', description: 'Face-level, intense, mid-workout' },
      },
    },
    'outdoor-track': {
      name: 'Outdoor Track',
      label: 'Outdoor · Run & Sprint',
      atmosphere: 'Dawn track empty except for her, sprint finish, sweat catching the first light, running shoes on asphalt, park with early morning mist, coastal path above the water',
      lightingBase: 'Dawn natural — 5500-6500K cool blue to warm gold transition. First 20 minutes of light. Long shadows. The world empty and cold and perfect.',
      sceneGroups: {
        track_sprint: { name: 'Track Sprint', description: 'Speed work, empty lanes, early light' },
        park_run: { name: 'Park Run', description: 'Morning park, trees, mist, first hour' },
        coastal_path: { name: 'Coastal Path', description: 'Sea view, elevated, wind, freedom' },
      },
    },
    'wellness-cafe': {
      name: 'Wellness Café',
      label: 'Café · Post-Workout',
      atmosphere: 'Green smoothie on white marble, protein bowl photographed before eaten, laptop open with training notes, high stools and floor-to-ceiling windows, fellow gym people recognising the effort',
      lightingBase: 'Window-lit café — 4500-5500K natural fill. Bright, clean, modern. White surfaces bouncing light. The kind of café designed to look good in photos.',
      sceneGroups: {
        marble_counter: { name: 'Counter', description: 'Marble surface, smoothie, post-workout' },
        window_seat: { name: 'Window Seat', description: 'Natural light, notebook, recovery' },
        outdoor_terrace: { name: 'Terrace', description: 'Outside seating, morning sun, content' },
      },
    },
    'home-kitchen': {
      name: 'Home Kitchen',
      label: 'Home · Meal Prep',
      atmosphere: 'Clean white kitchen, meal prep containers lined up, food scale, blender ready, ingredients fresh and arranged, the discipline behind the physique made visible and domestic',
      lightingBase: 'Kitchen overhead warm-white 3000-3500K with window side light. Clean, domestic, honest. The kind of light that makes food look good and effort look real.',
      sceneGroups: {
        meal_prep: { name: 'Meal Prep', description: 'Containers, scale, prep ritual in full' },
        blender_moment: { name: 'Smoothie', description: 'Blender, protein, morning ritual' },
        recipe_check: { name: 'Recipe', description: 'Phone propped, cooking, focused' },
      },
    },
    'recovery-space': {
      name: 'Recovery Space',
      label: 'Recovery · Rest Day',
      atmosphere: 'Ice bath in the corner, foam roller on the mat, compression gear, dim apartment light, rest day energy — quiet, slower, still disciplined but letting the body catch up',
      lightingBase: '2800-3200K home warm. Evening or morning dim. The opposite of the gym. Soft, slow, recovery-focused. Candles optional.',
      sceneGroups: {
        ice_bath: { name: 'Ice Bath', description: 'Cold plunge, breath work, recovery' },
        foam_roll: { name: 'Floor Recovery', description: 'Mat, foam roller, stretching' },
        rest_day_home: { name: 'Rest Day', description: 'Couch, robe, recovery intentional' },
      },
    },
  },

  pools: {
    wake: [
      '5am alarm — dark apartment, training kit already on the chair, protein shake ingredients ready',
      'waking before the gym opens because the discipline is internal, not scheduled by hours',
      '6am natural light through the curtain — body already awake before the alarm, trained into rhythm',
      'rest day morning — later, slower, the body reminding her why recovery is also training',
      'Sunday morning in training kit by 7am, the week\'s programme planned and already started',
      'waking sore from yesterday, assessing the body, deciding what today\'s session will be',
    ],
    morning_refresh: [
      'post-run shower — cold to warm, sweat rinsed, muscles starting to recover',
      'gym locker room after the early session — quick change, out before the morning crowd arrives',
      'home bathroom mirror post-workout — pump still showing, documenting before it fades',
      'cold shower at 6am as part of the morning discipline, not because it\'s comfortable',
      'recovery morning routine — foam roller first, then shower, then food, in that order always',
      'gym bathroom between sets — splash water, regroup, back out for the second half',
    ],
    getting_dressed: [
      'laying out the training kit the night before — the discipline starts before the alarm',
      'choosing between the scrunch leggings and the compression shorts based on what\'s training today',
      'post-gym getting dressed for the day — the workout done, the rest of the world beginning',
      'gym bag packed with extra kit for the double session — the commitment visible before she leaves',
      'rest day outfit — still fitted, still intentional, still the same body underneath',
      'pre-competition outfit choice — what photographs best under the lights, what fits the brand',
    ],
    breakfast: [
      'post-workout protein and carbs — the meal that earned itself, eaten with complete focus',
      'overnight oats prepared the night before — opened at 6am, eaten in two minutes, already moving',
      'smoothie bowl photographed and then immediately eaten — the content done, the food next',
      'wellness café post-run — green juice, egg whites, the weekly treat that still hits macros',
      'meal prep breakfast from the fridge — everything weighed Sunday, eaten without thinking Monday',
      'coffee first, food second — the only concession to not being a complete machine before 7am',
    ],
    late_morning: [
      'second session at the gym — accessory work while the weight room fills with less serious people',
      'wellness café late morning with the laptop open and the training log written up',
      'rest day errands in full post-workout glow that she did nothing to achieve and knows it',
      'stretching at home watching training content, noting what to try in the next session',
      'grocery run at late morning — the trolley telling the whole story of the week ahead',
      'coaching a client late morning — her own discipline visible in how she explains it to others',
    ],
    lunch: [
      'meal prep container eaten at the desk — no drama, hits macros, keeps the programme on track',
      'wellness café at noon with the post-workout meal that deserved more ceremony than it\'s getting',
      'cooking something from scratch because Sunday prep was ambitious and Wednesday is busy',
      'salad that is genuinely satisfying because the training makes everything taste like it earned it',
      'lunch with a training partner at the gym café — the conversation entirely about training',
      'protein bowl photographed for content, then eaten in three minutes because she is actually hungry',
    ],
    afternoon: [
      'afternoon session — the second gym visit that separates serious from casual',
      'outdoor run at 3pm when the sun is low and the park is quiet and the pace is honest',
      'foam rolling and mobility work in the apartment while watching technique videos',
      'taking content photos in the mirror zone while the gym is quiet in the afternoon dip',
      'grocery delivery at 3pm — the fridge restocked for the second half of the training week',
      'rest day afternoon walk — still moving, still intentional, still her, just slower',
    ],
    reset: [
      'post-second-session — protein shake, legs up, the day\'s training complete and logged',
      'ice bath at 5pm — the most uncomfortable part of the day and the most necessary',
      'sauna at the gym after the last set — sitting in heat, everything loosening, nothing left',
      'afternoon nap that the body demanded and the programme allows — not lazy, strategic',
      'rest day afternoon reset — the apartment clean, food prepped, tomorrow\'s session loaded',
      'evening stretching ritual — the same sequence every night, the body knowing what\'s coming',
    ],
    golden_hour: [
      'outdoor track at golden hour — long shadow, warm light on skin, the city going home behind her',
      'apartment balcony post-training — body tired and warm and satisfied in the last hour of light',
      'gym window golden light catching the mirror zone — the best photos happen at this hour',
      'park jog at golden hour when the light makes everything look like it means something',
      'beach run at golden hour — feet on sand, light on water, the body doing what it was built for',
      'rooftop at golden hour after training — city below, the session behind her, everything soft',
    ],
    dinner: [
      'meal prep dinner eaten with complete intention — this meal belongs to tomorrow\'s session',
      'restaurant with a training partner where ordering feels like a second discipline',
      'cooking at home with music on — the training done, the evening slow, the food actually enjoyed',
      'high-protein dinner that is also genuinely delicious because discipline and pleasure overlap more than people think',
      'post-event dinner after a competition — eating everything, earning everything',
      'Sunday meal prep dinner — the only one that arrives directly to the mouth instead of a container',
    ],
    evening: [
      'evening session at the empty gym — 8pm, weights, full focus with the room mostly to herself',
      'content editing at home after dinner — sorting through the day\'s mirror shots',
      'planning tomorrow\'s session with the same care other people plan a holiday',
      'recovery yoga in the apartment as the evening winds down and the body finally releases',
      'supplement protocol done — the last ritual before sleep, everything in order for tomorrow',
      'watching technique breakdowns at 9pm and immediately wanting to go back to the gym',
    ],
    night: [
      'early sleep because 5am training requires it — the discipline extends backward into the night',
      'protein before bed — the final meal of the day, the muscle fed, the work continuing while she sleeps',
      'training log closed for the day — every set recorded, the week taking shape on the page',
      'midnight foam rolling because the evening session left something tight that won\'t wait until morning',
      'reviewing tomorrow\'s programme at 10pm — knowing exactly what\'s coming, almost looking forward to it',
      'rest day night — sleeping later, the body grateful, the alarm set for a reasonable hour',
    ],
  },

  cameraPool: [
    '24mm wide on the training floor — full gym environment, subject at centre in her element',
    '85mm at mirror level — face, pump, the honest close-up after a set',
    '50mm outdoors at dawn — track light, long shadow, motion or stillness both working',
    '35mm handheld at the café — authentic, documentary, the post-workout glow real and unposed',
    '135mm telephoto on the outdoor path — compressed distance, body against landscape, speed visible',
    '50mm f/1.4 in the kitchen — close, warm, the discipline of food as intimate as training',
  ],

  lightingPool: [
    'gym LED 6000K — harsh, honest, every muscle defined, no softening and no apology',
    'dawn outdoor — cool blue turning to gold, long shadow, the world empty and the effort pure',
    'mirror fill — front light doubling itself, the body complete and documented',
    'window café — natural side light, 4500K clean, post-workout glow needs nothing added',
    'home kitchen warm 3200K — the domestic side of the discipline, honest and unglamorous',
    'golden hour outdoor — warm amber on skin, the athlete in natural light at its best',
    'gym afternoon slant — late day light through high windows crossing the training floor',
    'recovery dim — 2800K home evening, the body resting, the discipline temporarily invisible',
  ],

  wardrobePool: [
    'scrunch leggings and matching crop top — the gym uniform executed with full commitment',
    'oversized hoodie over training kit — pre-workout or post-workout, the intention visible either way',
    'compression set in black — no colour, no distraction, just the work',
    'sports bra only for mirror content — earned, documented, moved on from',
    'premium matching set in earth tones — the content creation version of training kit',
    'running shorts and performance top — outdoor training, functional, body-aware',
    'post-gym casual — the fitted everyday look that still looks like she just came from the gym',
    'meal prep home outfit — comfort set, still fitted, the discipline extending into the domestic',
  ],

  moodPool: [
    'disciplined and proud — she built this with no shortcuts and the body shows every session',
    'focused and in flow — mid-session, nothing exists outside the set, completely present',
    'post-workout confidence — the glow that only training produces, earned and unmistakable',
    'patient ambition — the programme is long and the progress is real and there is no rush',
    'quiet intensity — she doesn\'t need to explain the work to anyone who can see the results',
    'athletic femininity — strength and beauty as the same thing, not opposites',
  ],
}
