export const STORY_WORLD_FORBIDDEN = {
  id: 'forbidden',
  name: 'Forbidden',
  description:
    'A cinematic world of seduction and desire — candlelit private rooms, silk against skin, the tension between showing and concealing, the kind of beauty that makes everything else in the frame irrelevant. Intentionally provocative, cinematically beautiful, completely deliberate.',

  geography: { country: 'private interior', region: 'intimate private suite — seduction world' },

  identity: {
    archetype: 'seduction creator — forbidden luxury world',
    vibe: ['the tension between revealing and concealing', 'silk and candlelight as visual language', 'deliberate desire', 'the camera as willing accomplice', 'beauty that commands without asking'],
    tone: ['seductive', 'deliberate', 'controlled', 'warm', 'intimate', 'cinematic', 'intentionally provocative'],
    persona: ['completely at ease with the power she holds', 'understanding that restraint creates more tension than exposure', 'making the camera want to stay in every frame', 'the most desirable woman in her own private world'],
  },

  phaseOrder: ['wake', 'morning_refresh', 'getting_dressed', 'breakfast', 'late_morning', 'lunch', 'afternoon', 'reset', 'golden_hour', 'dinner', 'evening', 'night'],

  phases: {
    wake:            { label: 'Wake',            timeWindows: ['first morning light on silk sheets', 'pale soft intimate morning'],                   pacing: 'slow',   subLocations: ['silk-bedroom', 'bedside-intimate'] },
    morning_refresh: { label: 'Morning Refresh', timeWindows: ['warm private bathroom morning', 'mirror in morning intimate light'],                  pacing: 'slow',   subLocations: ['intimate-bathroom', 'mirror-seduction'] },
    getting_dressed: { label: 'Getting Dressed', timeWindows: ['morning dressing ritual', 'wardrobe intimate light'],                                 pacing: 'slow',   subLocations: ['mirror-seduction', 'wardrobe-intimate'] },
    breakfast:       { label: 'Breakfast',       timeWindows: ['window morning light on silk robe', 'kitchen in morning intimate warmth'],            pacing: 'slow',   subLocations: ['window-morning', 'kitchen-intimate'] },
    late_morning:    { label: 'Late Morning',    timeWindows: ['natural light intimate content moment', 'morning bedroom in honest light'],            pacing: 'medium', subLocations: ['mirror-seduction', 'silk-bedroom'] },
    lunch:           { label: 'Lunch',           timeWindows: ['afternoon warm interior', 'chaise or lounge in warm midday'],                         pacing: 'slow',   subLocations: ['chaise-seduction', 'lounge-warm'] },
    afternoon:       { label: 'Afternoon',       timeWindows: ['warm afternoon intimate room', 'bath or window afternoon light'],                     pacing: 'slow',   subLocations: ['bath-seduction', 'window-afternoon'] },
    reset:           { label: 'Reset',           timeWindows: ['pre-evening intimate preparation', 'vanity in warm late afternoon'],                   pacing: 'slow',   subLocations: ['vanity-seduction', 'mirror-seduction'] },
    golden_hour:     { label: 'Golden Hour',     timeWindows: ['amber window light on skin and silk', 'golden-hour intimate room warmth'],             pacing: 'slow',   subLocations: ['window-golden', 'silk-bedroom'] },
    dinner:          { label: 'Dinner',          timeWindows: ['candlelit intimate room', 'warm early evening private interior'],                     pacing: 'slow',   subLocations: ['candle-intimate', 'chaise-seduction'] },
    evening:         { label: 'Evening',         timeWindows: ['low warm evening ambient', 'intimate dark warm evening light'],                        pacing: 'slow',   subLocations: ['silk-bedroom', 'mirror-seduction', 'candle-intimate'] },
    night:           { label: 'Night',           timeWindows: ['deep warm night — candle or lamp only', 'the most intimate low-light night'],          pacing: 'slow',   subLocations: ['silk-bedroom', 'bedside-intimate'] },
  },

  locations: [
    'silk-sheeted bed in morning or candlelight', 'full-length mirror in seductive warm light', 'intimate bathroom with warm mirror and steam',
    'window with sheer curtain in morning or golden light', 'chaise longue in warm intimate interior', 'candlelit private room',
    'vanity with warm light and beauty detail', 'bath with candles and steam', 'warm intimate kitchen in morning robe',
  ],

  subLocations: {
    'silk-bedroom': {
      id: 'silk-bedroom', name: 'Silk Bedroom', mapAnchor: 'forbidden intimate bedroom',
      category: 'private-seduction-core',
      bestPhases: ['wake', 'late_morning', 'golden_hour', 'evening', 'night'],
      overlays: ['silk or satin bedding', 'warm intimate light', 'private seductive atmosphere', 'the most intimate room in the world'],
      locations: ['silk-sheeted bed in warm intimate light', 'private seductive bedroom interior', 'warm intimate bedroom scene'],
    },
    'bedside-intimate': {
      id: 'bedside-intimate', name: 'Bedside Intimate', mapAnchor: 'bedside zone',
      category: 'intimate-wake-night',
      bestPhases: ['wake', 'night'],
      overlays: ['candle or lamp on bedside', 'perfume or intimate detail near bed', 'silk sheets edge visible', 'private intimate morning or night'],
      locations: ['bedside with candle and perfume in silk', 'intimate bedside morning or night moment', 'warm private bedside zone'],
    },
    'intimate-bathroom': {
      id: 'intimate-bathroom', name: 'Intimate Bathroom', mapAnchor: 'private seductive bathroom',
      category: 'self-care-seduction',
      bestPhases: ['morning_refresh'],
      overlays: ['warm bathroom mirror light', 'steam or skin detail', 'intimate private morning', 'seductive self-care atmosphere'],
      locations: ['warm intimate bathroom mirror ritual', 'seductive morning bathroom setting', 'private warm bathroom in morning light'],
    },
    'mirror-seduction': {
      id: 'mirror-seduction', name: 'Seduction Mirror', mapAnchor: 'full-length intimate mirror',
      category: 'reflection-seduction',
      bestPhases: ['morning_refresh', 'getting_dressed', 'late_morning', 'reset', 'evening'],
      overlays: ['full-length mirror with warm intimate light', 'seductive self-study', 'private reflection framing', 'deliberate intimate mirror energy'],
      locations: ['full-length mirror in warm seductive light', 'intimate mirror reflection zone', 'seductive self-study mirror corner'],
    },
    'wardrobe-intimate': {
      id: 'wardrobe-intimate', name: 'Intimate Wardrobe', mapAnchor: 'intimate wardrobe zone',
      category: 'dressing-seduction',
      bestPhases: ['getting_dressed'],
      overlays: ['silk and intimate pieces hanging', 'warm wardrobe interior', 'intimate dressing selection ritual', 'the deliberate choice of what to reveal'],
      locations: ['intimate wardrobe with silk and lace', 'seductive dressing selection zone', 'private wardrobe in warm morning light'],
    },
    'window-morning': {
      id: 'window-morning', name: 'Morning Window', mapAnchor: 'sheer curtain morning window',
      category: 'light-seduction',
      bestPhases: ['breakfast'],
      overlays: ['sheer curtain in morning light', 'warm window glow on skin', 'silk robe at morning window', 'intimate morning private frame'],
      locations: ['morning window with sheer curtain in silk robe', 'warm morning window seduction frame', 'intimate breakfast window moment'],
    },
    'kitchen-intimate': {
      id: 'kitchen-intimate', name: 'Intimate Kitchen', mapAnchor: 'kitchen in morning silk robe',
      category: 'lifestyle-intimate',
      bestPhases: ['breakfast'],
      overlays: ['kitchen in silk robe morning', 'coffee or tea in intimate morning light', 'private seductive morning kitchen atmosphere'],
      locations: ['kitchen in silk robe with coffee in morning', 'intimate kitchen morning private scene', 'seductive morning kitchen interior'],
    },
    'chaise-seduction': {
      id: 'chaise-seduction', name: 'Seduction Chaise', mapAnchor: 'chaise longue in seductive lighting',
      category: 'reclining-seduction',
      bestPhases: ['lunch', 'dinner'],
      overlays: ['silk or velvet chaise in warm intimate light', 'deliberate reclining seductive energy', 'private intimate afternoon or evening'],
      locations: ['silk chaise in warm intimate afternoon', 'seductive reclining chaise setting', 'private intimate chaise in warm light'],
    },
    'lounge-warm': {
      id: 'lounge-warm', name: 'Warm Lounge', mapAnchor: 'intimate warm lounge',
      category: 'leisure-intimate',
      bestPhases: ['lunch', 'afternoon'],
      overlays: ['warm lounge interior', 'soft plush seductive furniture', 'intimate afternoon ease in private warmth'],
      locations: ['warm intimate lounge setting', 'private seductive afternoon lounge', 'soft warm lounge interior'],
    },
    'bath-seduction': {
      id: 'bath-seduction', name: 'Seduction Bath', mapAnchor: 'candlelit intimate bath',
      category: 'sensory-seduction',
      bestPhases: ['afternoon'],
      overlays: ['deep bath with candles and rose petals', 'intimate steam and warm light', 'private sensory seductive bathing', 'the most deliberately intimate bathing setting'],
      locations: ['deep bath with rose petals and candles in warm light', 'intimate seductive bath ritual', 'private warm candlelit bath setting'],
    },
    'window-afternoon': {
      id: 'window-afternoon', name: 'Afternoon Window', mapAnchor: 'afternoon sheer window',
      category: 'light-afternoon',
      bestPhases: ['afternoon'],
      overlays: ['warm afternoon window light', 'sheer curtain in afternoon', 'skin in warm afternoon window frame', 'intimate afternoon light framing'],
      locations: ['afternoon window with warm light on skin', 'intimate afternoon window frame', 'warm sheer curtain afternoon setting'],
    },
    'vanity-seduction': {
      id: 'vanity-seduction', name: 'Seduction Vanity', mapAnchor: 'intimate vanity ritual',
      category: 'preparation-seduction',
      bestPhases: ['reset'],
      overlays: ['lit vanity in warm private light', 'perfume and intimate beauty ritual', 'seductive pre-evening preparation', 'warm deliberate vanity setting'],
      locations: ['warm lit vanity with perfume and beauty ritual', 'seductive preparation vanity', 'intimate pre-evening vanity setting'],
    },
    'window-golden': {
      id: 'window-golden', name: 'Golden Window', mapAnchor: 'golden-hour window on skin',
      category: 'golden-seduction',
      bestPhases: ['golden_hour'],
      overlays: ['warm amber golden-hour light through sheer curtain', 'skin and silk in amber glow', 'the most seductive light in the day', 'intimate golden-hour private frame'],
      locations: ['golden window light on skin and silk', 'amber intimate window moment', 'the most beautiful seductive light of the day'],
    },
    'candle-intimate': {
      id: 'candle-intimate', name: 'Intimate Candle Room', mapAnchor: 'candlelit intimate interior',
      category: 'intimate-evening',
      bestPhases: ['dinner', 'evening'],
      overlays: ['candle as sole intimate light source', 'warm orange intimate glow', 'private seductive evening in candlelight', 'the most deliberately intimate atmosphere'],
      locations: ['candlelit intimate room in warm orange', 'private seductive candlelit space', 'warm intimate candle room'],
    },
  },

  sceneVariants: {
    wake: ['waking in silk sheets with morning light barely entering through sheer curtains', 'the first intimate morning moment — silk, warmth, and complete privacy'],
    morning_refresh: ['warm intimate bathroom mirror ritual in morning light', 'the seductive morning self-care in private bathroom warmth'],
    getting_dressed: ['slow deliberate intimate dressing in front of the mirror', 'choosing what to reveal and what to conceal in the wardrobe ritual'],
    breakfast: ['silk robe at the morning window with coffee and sheer curtain light', 'the intimate kitchen morning in warm light before the day'],
    late_morning: ['mirror study in morning light — honest and seductive simultaneously', 'natural light intimate content in the bedroom in the morning'],
    lunch: ['reclining on the silk chaise in warm afternoon intimate light', 'slow seductive afternoon ease in warm private interior'],
    afternoon: ['long candlelit bath with rose petals and complete intimate privacy', 'lying by the afternoon window in warm seductive light with sheer curtains'],
    reset: ['vanity ritual pre-evening — perfume, beauty, deliberate preparation for the intimate evening', 'the seduction preparation ritual at the warm vanity'],
    golden_hour: ['golden-hour amber light on silk and bare skin — the most cinematic intimate moment', 'the window golden hour falling across silk in the seduction world'],
    dinner: ['candlelit intimate private room — deliberate, warm, and completely controlled', 'reclining on the chaise in candlelight with complete seductive composure'],
    evening: ['low warm intimate evening in the private seduction world', 'the evening deepening into warmth and intimate deliberate presence'],
    night: ['candlelit bedside moment — silk, perfume, the most intimate private night', 'the final intimate warm forbidden night in private luxury'],
  },

  actionPools: {
    wake: ['lying in silk sheets as morning light enters through sheer curtains', 'reaching for perfume or rolling slowly in silk in private morning', 'the slow seductive wake in warm intimate private space'],
    morning_refresh: ['intimate bathroom mirror ritual in warm morning light', 'applying beauty in private warm bathroom with deliberate care', 'the seductive morning self-care ritual beginning'],
    getting_dressed: ['choosing what to reveal in the wardrobe — the deliberate intimate selection', 'standing at the mirror making small adjustments to the intimate look', 'the slow ritual of seductive dressing in private warm light'],
    breakfast: ['coffee or tea at the window in a silk robe with morning light', 'the intimate kitchen morning ritual in warm private light', 'standing at the morning window with warm drink and sheer curtain'],
    late_morning: ['mirror study in natural morning light — seductive and honest', 'moving through the intimate bedroom in natural content light', 'the deliberate intimate presence in morning natural light'],
    lunch: ['reclining on the silk chaise with warm intimate afternoon light', 'slow deliberate afternoon in warm private seductive interior', 'the intimate forbidden afternoon ease on silk furniture'],
    afternoon: ['lying in a long bath with candles and rose petals in intimate privacy', 'slow intimate afternoon by the sheer window in warm afternoon light', 'the most private sensory seductive afternoon moment'],
    reset: ['applying perfume at the warm vanity in the pre-evening ritual', 'the deliberate seductive preparation before the intimate evening', 'placing intimate beauty detail at the vanity in warm light'],
    golden_hour: ['golden-hour amber window light falling on skin and silk', 'standing in the most seductive light of the day — amber and warm', 'the most cinematic intimate moment of the day in golden light'],
    dinner: ['candlelit intimate private room — the forbidden dinner hour', 'reclining on the chaise in candlelight with complete seductive control', 'the most deliberately intimate evening moment'],
    evening: ['the intimate seduction world deepening in warm low evening light', 'moving through the warm private space with deliberate seductive ease', 'the forbidden evening at full intimate depth'],
    night: ['the final candlelit intimate night — silk and warmth and deliberate private calm', 'lying in silk in candlelight as the night deepens completely', 'the most private forbidden night moment'],
  },

  environmentPools: {
    wake: ['silk-sheeted bed in pale morning intimate light through sheer curtains', 'warm private bedroom in early morning seductive quiet', 'intimate bedroom in soft first-light warmth'],
    morning_refresh: ['warm intimate bathroom mirror in morning light', 'private bathroom with warm mirror and morning detail', 'seductive bathroom morning ritual interior'],
    getting_dressed: ['warm wardrobe interior with silk and intimate pieces', 'full-length mirror in warm morning seductive light', 'intimate dressing zone in private warm morning'],
    breakfast: ['silk robe at morning window with sheer curtain light', 'warm intimate kitchen in morning private light', 'window with sheer curtain in seductive morning light'],
    late_morning: ['full-length mirror in natural morning light — honest and seductive', 'intimate bedroom in clean natural morning light', 'private bedroom in honest natural late-morning light'],
    lunch: ['silk chaise in warm afternoon intimate interior', 'warm private lounge in intimate afternoon ease', 'seductive reclining afternoon setting in warm light'],
    afternoon: ['deep bath with rose petals and candles in intimate privacy', 'afternoon window with warm light and sheer curtain on skin', 'intimate afternoon warm interior in seductive setting'],
    reset: ['warm lit vanity with perfume and intimate beauty ritual', 'seductive pre-evening preparation vanity', 'warm intimate vanity setting in late afternoon light'],
    golden_hour: ['amber window light on silk and skin — the golden intimate moment', 'warm golden-hour interior with silk detail catching amber', 'the most seductive intimate light of the entire day'],
    dinner: ['candlelit intimate private room — warm orange and deep shadow', 'silk chaise in candlelight warm intimate evening', 'private seductive candlelit room'],
    evening: ['warm intimate evening in the forbidden private space', 'low warm ambient intimate evening with deliberate atmosphere', 'the private seduction world in warm evening depth'],
    night: ['candlelit bedside in warm intimate final night', 'silk sheets in single warm night source', 'deep private intimate forbidden night in warm light'],
  },

  moodPools: {
    wake: ['warm private intimate morning ease — complete self-possession', 'silk-soft seductive morning quiet', 'the forbidden world at its most private and beautiful morning'],
    morning_refresh: ['intimate self-care morning calm — private and deliberate', 'warm seductive bathroom ritual energy', 'the morning that belongs only to her'],
    getting_dressed: ['the deliberate intimate dressing ritual — choosing power through what is shown', 'slow seductive transformation in the morning wardrobe', 'private and intentional intimate preparation'],
    breakfast: ['warm silk-robe morning ease at the window', 'intimate morning before the world', 'the private forbidden world in its most human morning moment'],
    late_morning: ['honest intimate morning presence in natural light', 'the seduction world in clean honest morning light', 'natural and seductive simultaneously in morning bedroom light'],
    lunch: ['warm intimate private afternoon indulgence on silk', 'slow seductive afternoon ease', 'the forbidden world in soft warm afternoon private depth'],
    afternoon: ['deep sensory intimate bathing pleasure', 'warm private seductive afternoon in candlelit bath or window light', 'the most private and deliberately intimate afternoon energy'],
    reset: ['pre-evening deliberate intimate preparation', 'the seductive vanity ritual — deliberate and controlled', 'warm intimate pre-evening beauty composure'],
    golden_hour: ['the most seductive light in the world on silk and skin', 'golden-hour intimate warmth at its most cinematic', 'the forbidden world in its most beautiful and photographic moment'],
    dinner: ['warm intimate candlelit seductive evening', 'the forbidden dinner hour — deliberate and warm', 'candlelit intimate evening at full deliberate depth'],
    evening: ['the forbidden world deepening into warm intimate evening', 'low warm light and complete intimate seductive presence', 'the most deliberately private and seductive evening energy'],
    night: ['the deepest most private intimate night — candle, silk, and complete calm', 'warm seductive final night moment', 'the forbidden world complete in silk and candlelight'],
  },

  cameraPools: {
    wake: ['85mm low angle from silk bed edge, warm morning window dissolved behind in soft bokeh', '135mm intimate close-up at face height, pale warm morning light defining edge on silk linen'],
    morning_refresh: ['85mm bathroom mirror close, seductive reflection at same focal plane as subject', '50mm intimate bathroom mid shot, warm morning light compressing behind'],
    getting_dressed: ['50mm full-length mirror framed shot, wardrobe depth receding in warm light behind', '85mm intimate mid-length dressing angle, warm room depth soft behind subject'],
    breakfast: ['85mm window-side morning intimate, sheer curtain in warm morning bokeh behind', '50mm kitchen morning medium, sheer light compressing warm behind subject'],
    late_morning: ['85mm full-length mirror study in natural morning light', '135mm close-up in honest natural light defining intimate detail'],
    lunch: ['85mm chaise long angle, warm intimate afternoon depth behind subject', '135mm reclining silk close, fabric texture in sharp intimate foreground'],
    afternoon: ['85mm bath intimate bird\'s eye, candles creating warm secondary bokeh', '135mm close bath or window detail, steam or sheer diffusing background into warmth'],
    reset: ['85mm lit vanity close, warm vanity light on face in intimate preparation', '50mm vanity mid shot in warm intimate light'],
    golden_hour: ['135mm golden window backlit close, amber rim light defining edge of subject', '24mm wide golden-hour window shot, amber light flooding the intimate room'],
    dinner: ['85mm candlelit intimate portrait, candle glow as sole key source', '135mm intimate evening close, candle dissolved in warm background bokeh'],
    evening: ['85mm low warm evening ambient, warm intimate glow filling the soft background', '135mm intimate evening close, single lamp or candle as the sole source'],
    night: ['135mm candlelit bedside close-up, single candle as warm sole light source', '85mm soft side angle, deep warm shadow framing subject in intimate night'],
  },

  lightingPools: {
    wake: ['pale 5000K morning light entering through sheer curtains, long warm shadows across silk linen', 'soft diffused warm morning entering through sheer fabric, intimate edge on pillow and skin'],
    morning_refresh: ['clean 5200K bathroom mirror daylight on bare skin, warm and intimate', 'reflected morning warmth bouncing off white surfaces into intimate bathroom interior'],
    getting_dressed: ['warm 4800K interior morning light on fabric and skin, intimate and flattering', 'soft window light through sheer curtains, even warm fill across intimate dressing area'],
    breakfast: ['warm 4800K morning window light, sheer curtain diffusing to soft intimate fill', 'kitchen morning light at shallow angle, robe catching warm intimate detail'],
    late_morning: ['clean 5600K natural daylight in intimate bedroom — honest and warm', 'soft interior noon light, even and intimate, natural warm color rendering'],
    lunch: ['warm 4000K afternoon room ambient, no direct source, even intimate fill', 'soft filtered afternoon light through sheer curtains, warm intimate stripe'],
    afternoon: ['candlelight at 1700K as primary source in bath, warm orange seductive glow', 'warm afternoon window at 4200K, soft and deliberately intimate'],
    reset: ['warm 3200K vanity bulb intimate close light, flattering and deliberate', 'warm vanity interior at 3000K, intimate fill bouncing from mirror back'],
    golden_hour: ['rich 2800K golden window light at low angle, amber across silk and skin — the most seductive light', 'warm golden backlight from window, rim lighting subject edge, room interior dissolved in amber warmth'],
    dinner: ['candlelight at 1800K as sole key source, intimate warm fill, deep shadow beyond', 'warm 2500K single candle, intimate orange edge on skin and silk'],
    evening: ['low 2400K ambient room lamp, soft warm intimate fill, warm golden shadow everywhere', 'single bedside or chaise lamp at 2200K, intimate pool of warm seductive light'],
    night: ['single candle at 1600K, deep warm orange intimate light in near-darkness', 'bedside lamp at 2100K, soft intimate warm pool in dark private night'],
  },

  stylingPools: {
    wardrobe: {
      wake: ['silk or nothing in silk sheets', 'intimate sleep styling barely visible', 'the most private morning skin-forward look'],
      morning_refresh: ['silk robe barely tied after intimate shower', 'white or silk towel wrapped after bathing', 'skin-forward bare morning before dressing'],
      getting_dressed: ['lace set or sheer lingerie in warm morning light', 'silk slip in intimate morning dressing', 'intimate selection at the mirror in warm interior'],
      breakfast: ['silk robe at morning window — barely tied, morning intimate look', 'soft morning wrap at kitchen window in warm light', 'barely dressed seductive morning luxury'],
      late_morning: ['lace or sheer set in natural morning light', 'intimate daytime lingerie in clean honest morning', 'seductive morning presence in natural light'],
      lunch: ['silk slip or intimate set on chaise in afternoon', 'lace cami and intimate wear on warm lounge furniture', 'soft seductive private midday interior wear'],
      afternoon: ['nothing in the bath — rose petals and warm candle', 'sheer wrap by the afternoon window in warm light', 'silk or lace on the afternoon chaise in warm light'],
      reset: ['dressing robe half-tied at vanity preparing for evening', 'silk slip at the warm mirror in preparation', 'pre-evening intimate selection at the vanity'],
      golden_hour: ['sheer or lace against golden window light — the most seductive', 'silk against warm amber glow in golden-hour intimate', 'the most photographic intimate look in the most seductive light'],
      dinner: ['silk corset or intimate boned piece in candlelight', 'deep intimate evening robe or slip in warm candle', 'lace-and-silk deliberate intimate evening styling'],
      evening: ['low-cut silk or lace in warm intimate ambient', 'intimate evening wear in deep warm glow', 'barely-there evening in low private warm light'],
      night: ['silk nightgown or skin in candlelight at the intimate night end', 'nothing but silk in the final most private night moment', 'soft seductive intimate night luxury'],
    },
    details: {
      wake: ['undone intimate morning hair on silk pillow', 'bare warm skin in early intimate light', 'perfume visible on bedside in morning light'],
      morning_refresh: ['damp glowing skin after intimate shower', 'hair pinned or loose after bathing in warm bathroom', 'minimal bare skin in warm intimate bathroom light'],
      getting_dressed: ['gold or pearl jewelry placed on bare warm skin', 'slow deliberate hands on lace or silk detail', 'perfume applied to throat in dressing ritual'],
      breakfast: ['coffee cup against silk robe in morning window light', 'single rose or warm detail on kitchen surface', 'morning hair loose in warm window intimate light'],
      late_morning: ['honest natural face in clean morning light — bare and seductive', 'gold detail catching natural morning light', 'deliberate intimate morning posture at the mirror'],
      lunch: ['hair down loose on silk chaise', 'bare leg on silk or velvet fabric in afternoon', 'intimate wear against skin on afternoon lounge'],
      afternoon: ['rose petals on bathwater surface in warm light', 'steam and damp skin in warm candle intimate', 'wet hair after intimate bath in warm afternoon light'],
      reset: ['perfume applied at the warm vanity mirror', 'jewelry placed slowly in intimate warm vanity light', 'hair finished at warm vanity in deliberate ritual'],
      golden_hour: ['golden light catching lace or silk detail on skin', 'hair loose in amber backlight at the golden window', 'jewelry glowing in warm golden window intimate light'],
      dinner: ['candle-lit jewelry detail on skin in warm orange', 'deep lace or silk against intimate candleflame', 'perfume and intimate styling in warm evening candle'],
      evening: ['hair loose in low warm intimate ambient', 'bare skin in warm seductive evening glow', 'silk and skin in intimate low warm light'],
      night: ['final perfume or candle detail at night end', 'hair down in deepest intimate private calm', 'silk against skin in final intimate candlelight'],
    },
    changeMoments: {
      wake: ['still in silk or nothing in sheets — the most intimate morning state', 'pre-dressing private morning in silk warmth'],
      morning_refresh: ['wrapped in towel or robe after intimate bathing', 'between sleep and dressing in warm bathroom'],
      getting_dressed: ['mid-change in intimate wear in front of the mirror', 'choosing and placing intimate pieces in warm morning light'],
      breakfast: ['already in morning robe or wrap at the window', 'dressed for private morning ease only'],
      late_morning: ['in intimate daywear for the private morning content moment', 'lace or sheer set in natural honest morning light'],
      lunch: ['relaxed silk on the chaise — soft afternoon private intimate ease', 'barely changed from morning in warm midday'],
      afternoon: ['undressed for the intimate bath or post-bath in robe', 'between afternoon intimate ease and evening preparation'],
      reset: ['between afternoon and evening at the vanity — intimate refinement', 'choosing the evening intimate look at the vanity mirror'],
      golden_hour: ['golden-hour intimate styling — the most seductive and photographic', 'wearing the elevated intimate evening look in amber light'],
      dinner: ['fully in the intimate evening look — silk, lace, candle warmth', 'candlelit forbidden intimate at its most deliberately beautiful'],
      evening: ['low-light intimate evening styling in warm ambient', 'deep private intimate evening wardrobe in warm glow'],
      night: ['final private night styling — silk or skin in candlelight', 'the most private intimate end-of-forbidden-night state'],
    },
  },

  sensoryPools: {
    wake: ['silk against bare skin in warm intimate morning quiet', 'the scent of perfume in the still intimate morning room', 'soft warm light and complete private seductive calm'],
    morning_refresh: ['warm water on skin in a private intimate bathroom', 'perfume applied after shower — the intimate ritual warmth', 'clean bare skin and morning light on the warm mirror'],
    getting_dressed: ['lace fabric against warm skin in intimate morning', 'cool gold jewelry placed on warm bare skin', 'the slow intimate pleasure of seductive dressing in private warmth'],
    breakfast: ['warm coffee in a silk-robe intimate morning', 'light coming through sheer curtains in warm intimate framing', 'perfume and warm morning intimate quiet'],
    late_morning: ['honest morning light on bare skin at the mirror', 'silk fabric and natural light together in intimate bedroom', 'the warm private intimacy of a natural seduction morning'],
    lunch: ['silk chaise against bare skin in warm afternoon intimate', 'slip or lace in afternoon indoor intimate light', 'private slow afternoon warmth and seductive ease'],
    afternoon: ['rose petal-scented bath water in warm candle intimate', 'candle warmth in a private steamy intimate room', 'the deep pleasure of a long private intimate bath'],
    reset: ['perfume being applied at the warm intimate vanity', 'cool jewelry touching warm skin in preparation', 'lit vanity warmth and the intimate ritual of seductive preparation'],
    golden_hour: ['golden window light on silk and skin — the most seductive sensory of the day', 'warm amber air as the light changes in the intimate room', 'the most beautiful seductive light in the forbidden world'],
    dinner: ['candle warmth in a private intimate forbidden room', 'silk fabric in warm intimate flickering candlelight', 'intimate darkness and warm candle air in the evening'],
    evening: ['low warm glow on skin and fabric in intimate evening', 'private intimate warm air in a warm seductive room', 'the slow sensory warmth of the forbidden evening'],
    night: ['candlelight in total intimate private darkness', 'silk sheets and warm intimate candleflame scent', 'the deepest private intimate forbidden warmth at night'],
  },

  socialEnergyPools: {
    wake: ['entirely private — no external eye, no performance', 'the most personal unwatched intimate morning'],
    morning_refresh: ['completely personal intimate self-care', 'private ritual in warm intimate space before any audience'],
    getting_dressed: ['private intimate transformation ritual — deliberate and seductive', 'self-directed intimate choice without audience'],
    breakfast: ['private intimate morning ease — silk and coffee and no one watching', 'warm intimate breakfast before any performance begins'],
    late_morning: ['the first intimate content energy — natural light and honest presence', 'deliberate intimate self-study in honest morning light'],
    lunch: ['private intimate lounge ease — completely unperforming', 'warm midday private forbidden rest'],
    afternoon: ['deeply private intimate bath — no performance, pure sensation', 'slow intimate private seductive afternoon'],
    reset: ['private preparation ritual at the intimate vanity', 'controlled personal seductive refinement before the evening'],
    golden_hour: ['the forbidden world in full golden-hour photographic presence', 'slightly more visible — golden hour is for the deliberate seductive camera'],
    dinner: ['intimate candlelit warmth — controlled deliberate audience connection', 'slow intimate forbidden evening for the viewer'],
    evening: ['deepening intimacy — the forbidden evening at its most deliberately seductive', 'warm low-light intimate presence for the audience'],
    night: ['the most intimate private moment of the forbidden day', 'final warm private forbidden night intimacy'],
  },

  atmospherePools: {
    wake: ['total private intimate morning silence in warm silk room', 'the forbidden world at its most peaceful and unwatched', 'soft pale light and complete intimate private calm'],
    morning_refresh: ['private bathroom warm ritual intimate atmosphere', 'warm steam, light, and deliberate self-care calm', 'the most private intimate room at morning'],
    getting_dressed: ['warm wardrobe intimate seductive atmosphere — the private dressing ritual', 'quiet intimate selection and transformation energy'],
    breakfast: ['morning window light and coffee and silk — the most private intimate morning atmosphere', 'gentle seductive morning before the world enters'],
    late_morning: ['honest natural-light intimate atmosphere', 'the forbidden world in clean honest morning energy'],
    lunch: ['warm private afternoon indulgence on silk furniture', 'slow intimate midday seductive ease'],
    afternoon: ['deep candlelit intimate bath ritual atmosphere', 'the most private sensory seductive afternoon energy'],
    reset: ['warm intimate vanity refinement atmosphere — deliberate and seductive', 'private seductive preparation energy in warm indoor glow'],
    golden_hour: ['the golden-hour forbidden world — the most cinematic private intimate moment', 'amber light and silk and total seductive feminine presence'],
    dinner: ['candlelit intimate forbidden evening atmosphere', 'warm intimate forbidden dinner-hour private energy'],
    evening: ['deep warm intimate forbidden evening — the world at its most deliberately intimate', 'low ambient warm private seductive ease'],
    night: ['the deepest private forbidden night atmosphere — candle, silk, and total calm', 'complete private warm seductive intimate power'],
  },

  propPools: {
    wake: ['silk pillows and warm intimate linen', 'perfume bottle on bedside in morning light', 'sheer curtain barely moving in warm morning'],
    morning_refresh: ['intimate beauty products on warm vanity', 'white towel on hook or chair in bathroom', 'candle beside bathroom intimate mirror'],
    getting_dressed: ['lace or silk laid on intimate wardrobe shelf', 'pearl or gold jewelry on the dressing detail', 'silk robe on chair near intimate mirror'],
    breakfast: ['coffee cup and intimate warm detail at kitchen window', 'white morning window light with sheer curtain', 'silk robe and morning intimate detail'],
    late_morning: ['full-length mirror in natural honest light', 'silk sheets or intimate detail visible in natural morning', 'scattered intimate detail near the bed in natural light'],
    lunch: ['silk cushion on chaise in warm afternoon', 'afternoon glass of water or wine on lounge table', 'sheer fabric draped on intimate chaise'],
    afternoon: ['rose petals on bath water surface in warm candle light', 'candles at bath edge in intimate privacy', 'glass of wine near the intimate bath detail'],
    reset: ['perfume bottle at warm lit vanity', 'jewelry box open on intimate vanity table', 'lipstick and warm mirror detail at seductive vanity'],
    golden_hour: ['sheer curtain in full amber golden window light', 'gold jewelry catching warm amber light', 'single rose in warm golden-hour window glow'],
    dinner: ['candle as sole intimate light source in warm orange', 'champagne or wine glass in warm candlelight', 'silk or lace fabric against warm candle glow'],
    evening: ['ambient candle or lamp on side table in intimate evening', 'silk fabric in low warm intimate light', 'perfume visible on bedside in low ambient evening'],
    night: ['single candle burning in warm intimate darkness', 'silk sheets in warm candle glow', 'perfume and intimate detail in quiet candlelit night'],
  },

  bodyLanguagePools: {
    wake: ['soft reclined posture in silk in warm intimate morning', 'half-awake slow stretch with relaxed limbs in silk', 'rested private seductive posture toward morning light'],
    morning_refresh: ['calm upright posture at intimate bathroom mirror', 'relaxed post-shower intimate wrap posture', 'gentle self-care seductive stance in private morning'],
    getting_dressed: ['deliberate slow intimate dressing movement', 'one-arm lift fastening jewelry in warm light', 'composed intimate mirror assessment posture'],
    breakfast: ['relaxed robe posture at intimate kitchen window', 'standing at warm window with cup — easy private seductive stance', 'unhurried intimate kitchen morning body language'],
    late_morning: ['composed intimate self-study posture at full mirror in morning', 'relaxed natural intimate body language in honest morning light', 'easy natural seductive body ease in private bedroom'],
    lunch: ['reclining chaise posture — fully private and intimately at ease', 'slow comfortable seductive afternoon body language', 'soft lounging intimate seductive ease'],
    afternoon: ['submerged intimate bath posture — private sensory seductive ease', 'reclining chaise intimate afternoon body language', 'slow deliberate stretch in warm afternoon intimate light'],
    reset: ['upright deliberate intimate vanity posture', 'slow jewelry placement — hands and neck focused at vanity', 'composed pre-evening intimate mirror assessment'],
    golden_hour: ['slow turn in golden window light — the most seductive', 'cinematic still intimate posture in amber warmth at the window', 'soft elevated seductive body language in the best light'],
    dinner: ['slow deliberate candle-lit intimate posture', 'reclining on silk chaise in candlelight with seductive ease', 'intimate seated body language in warm intimate evening'],
    evening: ['soft reclining intimate evening body language in warm glow', 'low slow movement in private intimate warm light', 'private composed seductive feminine ease in warm evening'],
    night: ['fully reclined private bedside posture in silk', 'slow intimate body language in warm candlelight', 'the most private still posture of the forbidden day'],
  },

  facialExpressionPools: {
    wake: ['just-awake intimate softness — bare and private and warm', 'rested morning gaze toward the warm light', 'slow waking intimate private expression'],
    morning_refresh: ['focused self-study intimate expression at the mirror', 'fresh bare-face morning warm calm', 'composed post-shower intimate seductive expression'],
    getting_dressed: ['soft confident intimate dressing-room gaze', 'deliberate seductive self-aware mirror expression', 'light intimate composure while dressing in warm light'],
    breakfast: ['peaceful warm window-morning private intimate expression', 'soft contentment with coffee at the window', 'unhurried warm morning intimate ease on the face'],
    late_morning: ['honest natural-light intimate expression — no performance', 'soft confident seductive self-awareness in morning', 'warm private seductive morning study expression'],
    lunch: ['relaxed private seductive afternoon expression', 'soft reclining intimate ease on chaise', 'warm midday private intimate seductive calm'],
    afternoon: ['eyes half-closed in intimate bath sensory pleasure', 'slow private seductive bath expression', 'deep sensory intimate afternoon facial ease'],
    reset: ['deliberate focused intimate vanity mirror expression', 'pre-evening seductive composure building on the face', 'calm controlled intimate preparation expression'],
    golden_hour: ['the most seductive expression of the day — in perfect golden light', 'soft warm cinematic intimate expression in amber', 'quiet intimate magnetism in golden-hour glow'],
    dinner: ['warm candlelit intimate seductive expression', 'slow deliberate evening intimate eye contact', 'warm private intimate forbidden evening facial composure'],
    evening: ['deep private warm intimate seductive expression', 'slow low-light intimate seductive gaze', 'soft intimate private seductive evening calm'],
    night: ['the most private intimate night expression', 'warm eyes in candlelight — fully private and seductive', 'deep intimate forbidden nighttime stillness on the face'],
  },

  handDetailPools: {
    wake: ['hand resting on silk pillow edge in warm morning', 'fingers lightly touching warm linen beside', 'one hand near perfume bottle on bedside'],
    morning_refresh: ['hand on warm bathroom counter edge', 'fingers touching face in morning intimate skincare', 'hand holding intimate product at warm vanity'],
    getting_dressed: ['fingers adjusting lace or silk strap at the mirror', 'hand fastening jewelry at throat or wrist in warm light', 'fingers trailing over intimate wardrobe fabric'],
    breakfast: ['hand around warm morning coffee cup in silk robe', 'fingers touching rose or intimate detail on kitchen surface', 'resting hand on warm window ledge in morning'],
    late_morning: ['hand touching intimate mirror edge in natural light', 'fingers adjusting strap in mirror in natural morning', 'one hand resting on hip at mirror in honest light'],
    lunch: ['hand trailing over silk chaise fabric in warm afternoon', 'fingers resting loosely on warm lounge surface', 'hand near a glass on the intimate afternoon table'],
    afternoon: ['hand resting on bath edge with rose petals in warm candle', 'fingers in warm water with petals around in intimate bath', 'hand on the intimate bath rim in candlelight'],
    reset: ['fingers holding perfume bottle at warm vanity', 'hand placing intimate jewelry on at the lit vanity mirror', 'fingertips applying lipstick or intimate beauty product'],
    golden_hour: ['hand holding sheer curtain edge in golden intimate light', 'fingers trailing across silk in amber window intimate glow', 'one hand touching jewelry in warm amber backlight'],
    dinner: ['hand near champagne or wine glass in intimate candlelight', 'fingers touching silk fabric in warm evening intimate', 'slow hand placement on intimate chaise or bed edge'],
    evening: ['hand resting against warm intimate surface in low ambient', 'fingers touching fabric or skin in low intimate evening light', 'deliberate slow hand movement in warm intimate evening glow'],
    night: ['hand near the intimate candle in warm night darkness', 'fingers on silk sheet edge in intimate candlelight', 'one hand resting near the face in deep intimate night warmth'],
  },

  movementEnergyPools: {
    wake: ['slow', 'intimate', 'waking'],
    morning_refresh: ['ritual', 'deliberate', 'warm'],
    getting_dressed: ['slow', 'intentional', 'seductive'],
    breakfast: ['unhurried', 'private', 'intimate'],
    late_morning: ['composed', 'natural', 'honest'],
    lunch: ['reclining', 'seductive', 'slow'],
    afternoon: ['sensory', 'still', 'intimate'],
    reset: ['deliberate', 'refining', 'seductive'],
    golden_hour: ['cinematic', 'slow', 'golden'],
    dinner: ['intimate', 'controlled', 'warm'],
    evening: ['slow', 'private', 'deliberate'],
    night: ['minimal', 'intimate', 'still'],
  },

  transitionPools: {
    human: {
      wake: ['waking slowly in the forbidden intimate morning', 'silk and quiet in warm private light'],
      morning_refresh: ['moving into the warm intimate bathroom ritual', 'the seductive morning self-care beginning'],
      getting_dressed: ['choosing the intimate look of the day deliberately', 'the private seductive dressing ritual begins'],
      breakfast: ['moving to the kitchen window in a silk robe', 'the quiet intimate morning coffee ritual'],
      late_morning: ['the natural light intimate moment', 'honest private seductive morning presence'],
      lunch: ['settling into afternoon intimate ease on the chaise', 'the slow midday forbidden rest'],
      afternoon: ['moving into the intimate bath ritual', 'the private seductive afternoon sensory moment'],
      reset: ['the vanity ritual reset before the intimate evening', 'refining for the intimate forbidden evening ahead'],
      golden_hour: ['the golden light intimate moment — the most cinematic seductive', 'amber window light on silk and skin in the most beautiful frame'],
      dinner: ['candles lit, forbidden evening intimate energy begins', 'the warm intimate evening moment deepens'],
      evening: ['the intimate forbidden evening deepens in warm light', 'low warm light and completely private seductive presence'],
      night: ['the final private forbidden candlelit night', 'the deepest warm intimate forbidden close of the day'],
    },
  },

  narrativeIntentPools: {
    wake: ['the most private and intimate beginning of the forbidden day — silk and quiet', 'warmth and total private intimacy before any performance begins'],
    morning_refresh: ['turning sleep into intimate feminine ritual through private seductive self-care', 'the private morning that creates the forbidden day'],
    getting_dressed: ['choosing the intimate identity of the day in private warmth', 'the seductive dressing ritual as the first act of deliberate self-possession'],
    breakfast: ['private intimate morning ease before the forbidden world opens', 'silk and coffee and warm window — no performance required'],
    late_morning: ['honest intimate seductive presence in natural morning light', 'the forbidden world in its most truthful beautiful daytime form'],
    lunch: ['slow private intimate indulgence in warm afternoon light', 'the forbidden afternoon as deliberate seductive pleasure'],
    afternoon: ['deep sensory private seductive ritual in warm intimate light', 'the intimate bath as the most deliberately beautiful act of self-care'],
    reset: ['deliberate intimate preparation for the evening escalation', 'the warm vanity as the threshold between afternoon and night in the forbidden world'],
    golden_hour: ['the most cinematic moment of the forbidden world — golden amber light on intimate beauty', 'the window amber turning private luxury into deliberate art'],
    dinner: ['intimate controlled warm evening energy — the forbidden world at dusk', 'candle and silk and deliberate seductive intimate presence'],
    evening: ['the forbidden world deepening into its most deliberately intimate evening form', 'warm low light and completely private seductive feminine power'],
    night: ['the final intimate private forbidden night — the world complete', 'candle, silk, and total seductive warm private calm'],
  },

  fallbackRules: {
    pacingProfile: { wake: 'slow', morning_refresh: 'slow', getting_dressed: 'slow', breakfast: 'slow', late_morning: 'slow', lunch: 'slow', afternoon: 'slow', reset: 'slow', golden_hour: 'slow', dinner: 'slow', evening: 'slow', night: 'slow' },
    repetitionBreakers: { avoidBackToBackSameLocation: true, avoidBackToBackSameLightingStyle: true, encourageWardrobeEvolution: true },
    worldDefaults: { allowSceneGroupFallbackToPhasePools: true, allowSubLocationFallbackToWorldPools: true, preferSceneGroupsWhenPresent: true },
  },

  exclusions: {
    premium: ['clinical or harsh lighting', 'gym or athletic settings', 'outdoor public spaces', 'busy distracting backgrounds'],
    hard: ['daylight outdoor scenes', 'group social settings', 'office environments', 'cold or blue-toned lighting'],
  },

  routeRules: {
    worldIdentity: ['the forbidden world must feel warm, intimate, seductive, and deliberately beautiful — never crude or cold', 'silk, lace, candlelight, and warm windows are the core visual language'],
    humanFlow: ['the day moves from warm intimate private morning through self-care ritual into seductive afternoon depth and deliberate intimate evening warmth', 'every phase should feel like a deeper invitation into seductive private beauty'],
    styling: ['intimate apparel only — silk, lace, sheer, robes — the tension of revealing and concealing is the key', 'perfume and intimate jewelry are the defining accessories'],
    atmosphere: ['warm intimate light always — candlelight, warm interior lamps, and golden-hour windows', 'the forbidden world is always warm, private, deliberately beautiful'],
  },
}
