export const STORY_WORLD_LACE_ERA = {
  id: 'lace-era',
  name: 'Lace Era',
  description: 'Ultra-feminine maximalism. Doily fashion, candlelit rooms, vintage-romantic meets high fashion. Lace, ruffles, ribbons, and blooms — all day, every scene.',
  tags: ['feminine', 'romantic', 'vintage', 'maximalist', 'lace', 'luxury'],

  phaseOrder: [
    'wake',
    'morning_refresh',
    'getting_dressed',
    'breakfast',
    'late_morning',
    'lunch',
    'afternoon',
    'reset',
    'golden_hour',
    'dinner',
    'evening',
    'night',
  ],

  phases: {
    wake: {
      label: 'Wake',
      subLocation: 'lace-bedroom',
      time: '07:00–08:30',
      light: 'soft morning diffusion through lace curtains, dust motes visible, blush-pink glow',
      mood: 'dreamy, still, romantic languor',
      action: 'waking slowly, stretching in lace-trimmed sheets, hair loose on pillow',
    },
    morning_refresh: {
      label: 'Morning Refresh',
      subLocation: 'vintage-bathroom',
      time: '08:30–09:30',
      light: 'frosted window glow, candles lit on vanity shelf, warm diffused white',
      mood: 'intimate, soft ritual, unhurried',
      action: 'washing face, tying hair ribbon, applying soft scent from crystal bottle',
    },
    getting_dressed: {
      label: 'Getting Dressed',
      subLocation: 'dressing-room',
      time: '09:30–10:30',
      light: 'natural window light bouncing off ivory walls and mirror',
      mood: 'ceremony of dressing, slow reverence for femininity',
      action: 'selecting lace pieces, layering delicate fabrics, clasping pearl buttons',
    },
    breakfast: {
      label: 'Breakfast',
      subLocation: 'floral-kitchen',
      time: '10:30–11:30',
      light: 'warm morning side-light, lace tablecloth diffusing sun, golden hour warmth',
      mood: 'abundance, cottagecore opulence, domestic beauty',
      action: 'arranging fruit, pouring tea from a china pot, fresh flowers on the table',
    },
    late_morning: {
      label: 'Late Morning',
      subLocation: 'garden-terrace',
      time: '11:30–13:00',
      light: 'dappled garden light through rose arch, soft overcast or warm spring sun',
      mood: 'romantic, unhurried, blooming femininity',
      action: 'reading in a garden chair, cutting roses, writing in a journal',
    },
    lunch: {
      label: 'Lunch',
      subLocation: 'salon-dining',
      time: '13:00–14:30',
      light: 'soft overhead chandelier, candlelight even at midday, lace tablecloth glow',
      mood: 'indulgent, feminine, curated excess',
      action: 'plating a delicate meal, arranging the table, sipping elderflower cordial',
    },
    afternoon: {
      label: 'Afternoon',
      subLocation: 'boudoir-studio',
      time: '14:30–16:30',
      light: 'afternoon window light, cream-filtered diffusion, warm white balance',
      mood: 'creative, expressive, layered femininity',
      action: 'sketching, arranging dried flowers, pinning lace swatches, crafting',
    },
    reset: {
      label: 'Reset',
      subLocation: 'lace-bedroom',
      time: '16:30–17:30',
      light: 'low amber afternoon, candles beginning to glow, golden diffuse',
      mood: 'soft pause, restoration, tender solitude',
      action: 'lying on bed, rereading a letter, braiding hair, quiet stretching',
    },
    golden_hour: {
      label: 'Golden Hour',
      subLocation: 'garden-terrace',
      time: '17:30–19:00',
      light: 'rich golden backlight, long shadows across grass, rose-peach warmth',
      mood: 'nostalgic beauty, peak romanticism, light catching lace',
      action: 'walking in the garden, holding flowers, turning in soft wind',
    },
    dinner: {
      label: 'Dinner',
      subLocation: 'salon-dining',
      time: '19:00–21:00',
      light: 'full candlelight, crystal glasses refracting flame, 2600K amber warmth',
      mood: 'formal romance, evening abundance, soft glowing excess',
      action: 'serving a candlelit dinner, raising a crystal glass, touching pearl necklace',
    },
    evening: {
      label: 'Evening',
      subLocation: 'parlour-lounge',
      time: '21:00–23:00',
      light: 'dim candles and fairy lights, very warm 2400K, deep amber shadows',
      mood: 'intimate, languid, world softened to candlelight',
      action: 'curled on a chaise, reading poetry, gazing into candle flame',
    },
    night: {
      label: 'Night',
      subLocation: 'lace-bedroom',
      time: '23:00–01:00',
      light: 'single candle, moonlight through lace curtain, chiaroscuro soft',
      mood: 'dreaming, feminine mystery, last tender moments',
      action: 'brushing hair at mirror, writing in diary, blowing out candles',
    },
  },

  subLocations: {
    'lace-bedroom': {
      label: 'Lace Bedroom',
      description: 'Canopied bed with lace drapes, embroidered pillowcases, vintage lamp, dried rose bundles, lace curtain at window',
      surfaces: ['linen sheets with lace trim', 'embroidered pillow', 'vintage wooden bedframe', 'soft rug'],
      props: ['dried rose bouquet', 'taper candle', 'glass perfume bottle', 'lace gloves on bedside table'],
    },
    'vintage-bathroom': {
      label: 'Vintage Bathroom',
      description: 'Clawfoot tub with lace edge, frosted window, botanical prints, crystal vanity bottles, linen hand towels with lace borders',
      surfaces: ['clawfoot tub enamel', 'marble shelf', 'mosaic tile floor', 'frosted glass window'],
      props: ['crystal perfume bottles', 'dried lavender tied in ribbon', 'lace-edged hand towel', 'candle on shelf'],
    },
    'dressing-room': {
      label: 'Dressing Room',
      description: 'Open wardrobe with lace and tulle visible, full-length mirror with ornate frame, silk ribbons hanging, pearl and flower hair accessories on display',
      surfaces: ['ivory painted wood wardrobe', 'gilded mirror frame', 'velvet stool', 'printed wallpaper'],
      props: ['pearl hair clip on mirror edge', 'silk ribbon hanging', 'lace gloves', 'small flower posy in glass'],
    },
    'floral-kitchen': {
      label: 'Floral Kitchen',
      description: 'Cottagecore kitchen with fresh blooms in every corner, lace tablecloth on wooden table, china teacups, morning light through window',
      surfaces: ['white lace tablecloth', 'farmhouse wooden table', 'hand-painted china', 'stone counter'],
      props: ['fresh flower arrangement', 'china teapot', 'fruit bowl with peaches and roses', 'linen napkin with lace edge'],
    },
    'garden-terrace': {
      label: 'Garden Terrace',
      description: 'Romantic English garden, rose arch, garden chair with cushion, stone path, tall grass, blooming roses, ivy on stone wall',
      surfaces: ['stone paving', 'iron garden chair with cushion', 'rose arch', 'grass lawn'],
      props: ['cut rose stems', 'wicker basket', 'open book face-down on chair', 'tea tray on stone table'],
    },
    'salon-dining': {
      label: 'Salon Dining Room',
      description: 'Vintage dining room with crystal chandelier, lace tablecloth, gold-edged china, candlesticks, floral centrepiece, dark rich wallpaper',
      surfaces: ['long lace-covered dining table', 'dark wood chairs with velvet cushion', 'crystal chandelier', 'dark floral wallpaper'],
      props: ['tall candlesticks', 'crystal wine glasses', 'silver cutlery', 'peony centrepiece'],
    },
    'boudoir-studio': {
      label: 'Boudoir Studio',
      description: 'Creative feminine space — lace swatches pinned to board, dried flowers in vases, vintage desk, open sketchbook, velvet chair, ribbons and thread',
      surfaces: ['cream wallpaper', 'velvet armchair', 'wooden writing desk', 'cork pinboard with lace swatches'],
      props: ['dried flower bundles', 'open sketchbook', 'spool of silk ribbon', 'wax seal and candle'],
    },
    'parlour-lounge': {
      label: 'Parlour Lounge',
      description: 'Victorian-inspired sitting room — chaise longue, fireplace, bookshelves, candelabra, velvet curtains, lace anti-macassars on armrests',
      surfaces: ['chaise longue in dusty rose velvet', 'marble fireplace', 'dark wood bookshelf', 'Persian rug'],
      props: ['candelabra with burning tapers', 'stack of poetry books', 'glass of cordial', 'lace fan'],
    },
  },

  sceneVariants: {
    romantic_solitude: {
      label: 'Romantic Solitude',
      energy: 'quiet, internal, dreaming',
      framing: 'close portrait or medium with atmospheric depth',
    },
    feminine_ceremony: {
      label: 'Feminine Ceremony',
      energy: 'deliberate, ritualistic, absorbed in detail',
      framing: 'medium-close with props in frame',
    },
    garden_reverie: {
      label: 'Garden Reverie',
      energy: 'expansive, light-filled, nostalgic',
      framing: 'medium-wide with full lace outfit and garden surroundings',
    },
    candlelit_intimacy: {
      label: 'Candlelit Intimacy',
      energy: 'warm, low-light, soft glow on skin and fabric',
      framing: 'tight portrait or half-body with candle in frame',
    },
  },

  actionPools: {
    wake: [
      'waking slowly in a lace-canopied bed, hair spread across embroidered pillow',
      'stretching arms above head into lace-draped canopy, soft morning light entering',
      'lying on side facing window, lace curtain billowing gently in morning air',
      'sitting up in bed, pulling knees to chest in lace-trimmed nightgown',
      'tracing fingers along embroidered pillowcase edge, eyes half-open',
    ],
    morning_refresh: [
      'standing at vintage vanity, tying a silk ribbon into hair',
      'pouring water from ceramic pitcher over hands, face turned down',
      'misting face from crystal atomiser, eyes closed, chin lifted',
      'pressing a lace-edged hand towel to face with both hands',
      'placing dried lavender to nose, eyes softly closed',
    ],
    getting_dressed: [
      'buttoning delicate pearl buttons on lace blouse, fingers careful and slow',
      'stepping into a full lace skirt, fabric settling around feet',
      'pinning a fresh flower into braided hair in front of the mirror',
      'holding lace gloves thoughtfully, deciding whether to wear them',
      'clasping a pearl necklace at nape, head bowed slightly',
    ],
    breakfast: [
      'arranging fresh roses into a small vase on the breakfast table',
      'pouring tea from a painted china teapot, steam rising',
      'placing halved figs beside bread on a lace-covered table',
      'holding a china cup with both hands, looking out the window',
      'slicing cake with a small silver knife on a floral plate',
    ],
    late_morning: [
      'seated in garden chair, reading a hardback book, one leg crossed',
      'cutting roses from the garden arch with a small pair of scissors',
      'walking slowly along a stone garden path, lace hem brushing stones',
      'writing in a leather journal resting on a wicker garden table',
      'holding a stem of roses close to face, studying the petals',
    ],
    lunch: [
      'arranging a delicate table setting with folded lace napkins',
      'plating poached pear on fine china with a silver spoon',
      'raising a crystal glass toward the light, examining it',
      'placing a small flower on a white plate as garnish, then stepping back',
      'seated at table, elbow resting lightly on lace tablecloth, chin in hand',
    ],
    afternoon: [
      'arranging dried flowers into a ceramic vase, selecting stems carefully',
      'sketching in a large open notebook at the wooden desk',
      'pinning lace swatches to a fabric board, stepping back to view',
      'winding a spool of silk ribbon between hands',
      'pressing a flower between the pages of a heavy book',
    ],
    reset: [
      'lying across the bed reading a handwritten letter',
      'sitting on the edge of the bed braiding hair loosely',
      'lying on stomach, chin resting on crossed forearms, gazing out',
      'resting against embroidered pillow, one knee bent, half-daydreaming',
      'slowly stretching arms on bed, lace cuffs catching light',
    ],
    golden_hour: [
      'walking through the garden in golden light, lace hem in motion',
      'turning slowly in the rose arch, one arm extended, looking back over shoulder',
      'holding a large bunch of roses at waist, golden light behind',
      'standing in tall grass near stone wall, letting lace fabric catch the wind',
      'reaching up to touch a rose on the arch overhead, face tilted up in light',
    ],
    dinner: [
      'lighting the last taper candle at a fully set candlelit dining table',
      'raising a crystal wine glass in toast, candlelight refracting through it',
      'seated at head of table, hands clasped, smiling softly at the setting',
      'placing a peony centrepiece with care, stepping back to check it',
      'touching a pearl necklace lightly while gazing at the candlelight',
    ],
    evening: [
      'curled sideways on the chaise longue, open book resting on chest',
      'gazing into a candle flame from armchair, cheek resting on one hand',
      'picking up a lace fan and slowly opening it',
      'running a finger along a bookshelf spine, searching for a title',
      'sitting with legs tucked under, a glass of cordial in hand, listening to silence',
    ],
    night: [
      'brushing long hair at a candlelit vanity mirror, slow and rhythmic',
      'writing in a diary by taper candle, quill or fine pen in hand',
      'blowing out a row of candles, face bathed briefly in warm light',
      'kneeling on the bed, pinning up lace curtain to look out at moonlight',
      'reading last lines of poetry before marking the page and closing the book',
    ],
  },

  environmentPools: {
    indoor: [
      'lace-trimmed bedroom with canopied bed and embroidered linen',
      'vintage clawfoot bathroom with frosted glass and crystal vanity shelf',
      'dressing room with open wardrobe and ornate gilt-framed mirror',
      'cottagecore kitchen with floral tablecloth and fresh bloom arrangements',
      'Victorian parlour with velvet chaise and marble fireplace',
      'candlelit dining room with crystal chandelier and full lace tablecloth',
      'boudoir studio with lace swatches, dried flowers, and velvet writing chair',
    ],
    outdoor: [
      'walled English garden with rose arch and stone path',
      'terrace with iron garden furniture and trailing ivy on stone wall',
      'meadow with tall wildflowers and soft overcast light',
      'cottage doorway framed by climbing roses',
      'stone garden bench beside a blooming hedge',
    ],
  },

  moodPools: [
    'ultra-feminine, maximalist romanticism, soft excess',
    'vintage-romantic, nostalgic, lace-filtered beauty',
    'dreamy languor, gentle solitude, feminine ritual',
    'candlelit intimacy, warm amber glow, tender femininity',
    'garden reverie, floral abundance, light-filled nostalgia',
    'deliberate elegance, ceremony of dressing, devotion to detail',
    'cottagecore opulence, domestic beauty, natural abundance',
    'Victorian drawing-room softness, quiet poetry, still life grace',
  ],

  cameraPools: [
    'close portrait, f/1.8, lace fabric slightly soft in near foreground, face sharp',
    'medium-close half-body, f/2.2, lace curtain framing subject naturally',
    'medium full-body, f/2.8, showing full lace skirt against room or garden backdrop',
    'editorial overhead table detail, f/4.0, china and lace tablecloth in frame',
    'tight detail: lace cuff against skin or pearl button being fastened, f/1.4',
    'medium garden shot, f/2.5, rose arch or hedge as soft background, natural frame',
    'environmental wide, f/4.0, entire dining room or bedroom in low candlelight',
    'low angle garden, f/2.8, looking up at figure in arch, sky or roses behind',
    'candle close-up with subject face softly blurred behind, f/1.8, dual focus story',
    'mirror reflection — subject brushing hair, reflection occupies right third, f/2.2',
  ],

  lightingPools: [
    'soft morning lace-filtered window light, warm 4800K, diffuse and wrapping',
    'golden hour backlight through rose arch, 3400K, light catching lace fabric',
    'overcast English garden light, even diffuse daylight 5500K, no hard shadows',
    'full candlelight interior, 2400–2600K amber, deep warm shadows, glowing skin',
    'chandelier plus candlelight, 2800K mixed warm, crystal refracting spots',
    'single taper candle night scene, 2200K, chiaroscuro soft against dark room',
    'afternoon side window light, 4200K, cream walls bouncing fill into shadows',
    'dappled garden shade with light breaks, 5000K, soft natural variation',
    'frosted bathroom window, even diffuse white 5000K, very soft shadowless',
    'fairy lights and candelabra evening, 2600K, layered warm multiple sources',
  ],

  stylingPools: {
    wardrobe: [
      'floor-length ivory lace gown with fitted bodice and full skirt',
      'white cotton lace blouse with puff sleeves and pearl button closure',
      'delicate lace-overlay midi dress in blush pink over silk slip',
      'cream lace-trim nightgown with ribbon ties at collar',
      'white broderie anglaise sundress, full skirt, lace hem',
      'layered lace petticoat skirt with vintage velvet corset top',
      'black lace fitted dress with high neck and long sleeves — contrast elegance',
      'dusty rose taffeta gown with lace overlay and ribbon waist bow',
      'sheer lace robe over silk chemise, barely-dressed morning look',
      'floral jacquard tea dress with lace collar and cuffs',
      'ivory crochet knit co-ord — shorts and bralette, oversized lace texture',
      'vintage bridal-style blazer in ivory lace with matching wide-leg trousers',
    ],
    details: [
      'pearl button earrings and layered pearl necklace',
      'silk ribbon tied as headband through loose waves',
      'lace gloves reaching to mid-forearm, ivory or white',
      'fresh rose tucked into braided updo',
      'vintage cameo brooch at collar or chest',
      'thin gold chain anklet visible at hem of long dress',
      'embroidered floral handkerchief tucked into pocket or held loosely',
      'crystal hairpin in side part',
      'dried flower wrist corsage — lavender and baby\'s breath',
      'strappy ivory kitten-heel mule or flat sandal with ankle ribbon',
      'square-toe mary jane in cream or dusty rose',
      'bare feet on stone or wooden floor — delicate nail art, lace nail design',
    ],
    changeMoments: [
      'removing lace gloves finger by finger',
      'loosening ribbon at collar and letting fabric fall open',
      'stepping out of floor-length skirt pooled on floor',
      'draping sheer lace robe over shoulders',
      'letting hair down from braided updo, ribbon falling',
      'reaching behind to unfasten pearl button row at back of blouse',
    ],
  },

  sensoryPools: [
    'scent of fresh roses and jasmine from garden through open window',
    'faint candle wax and dried lavender throughout the room',
    'silk and lace cool against fingertips, intricate texture',
    'sound of a china cup placed softly on a saucer',
    'faint rustle of lace petticoat with each step on stone floor',
    'warmth of candlelight felt on face and hands across the table',
    'sound of ribbon being pulled slowly through a lace eyelet',
    'cool touch of pearl jewellery against warm collarbone',
    'taste of elderflower cordial, floral and barely sweet',
    'scent of old books and warm wax in the parlour evening',
  ],

  socialEnergyPools: [
    'fully alone — a world built entirely for one woman\'s private femininity',
    'quiet solitude with awareness of being observed by the space itself',
    'absorbed in ritual — no audience needed, the action is the event',
    'intimate with the objects around her — flowers, books, lace, candles',
    'the kind of aloneness that feels like luxury, not loneliness',
  ],

  atmospherePools: [
    'time has slowed to the speed of lace being lifted by wind',
    'every object in the room has been chosen with devotion',
    'the whole world has been filtered through ivory and rose',
    'femininity as architecture — the room is an extension of her interiority',
    'it is always slightly earlier than you think — always one candle before dark',
    'the maximalism is tender, not loud — abundance without aggression',
    'every surface has a texture worth touching',
    'beauty is the only agenda here',
  ],

  propPools: [
    'fresh-cut garden roses in a crystal vase',
    'taper candles in brass or silver candlestick holders',
    'china teacup and saucer with hand-painted flowers',
    'handwritten letter or open poetry book',
    'crystal perfume atomiser on a tray',
    'embroidered linen hand towel',
    'dried lavender tied with a silk ribbon',
    'pearl necklace or earrings laid on fabric',
    'open lace fan',
    'small round mirror with ornate frame',
    'wax seal set and envelope',
    'silver hairbrush with engraved handle',
    'pressed flower inside an open book',
    'wicker picnic basket with linen cloth',
    'lace parasol',
  ],

  bodyLanguagePools: [
    'hands held lightly at waist, fingers loosely interlocked',
    'one hand pressed flat to chest, the other holding a prop loosely',
    'arms slightly extended at sides, inviting, open posture',
    'one hand raised to touch hair or neck, elbow lifted softly',
    'seated with ankles crossed, hands folded in lap, upright and composed',
    'standing side-on, one shoulder dropped, chin tilted toward light source',
    'both hands cupped around a teacup or glass',
    'leaning gently forward over a table, both palms pressed to surface',
    'arms crossed loosely at chest, shoulders slightly rounded inward',
    'reaching upward — to a shelf, to a rose on the arch, to a curtain pull',
  ],

  facialExpressionPools: [
    'soft downcast eyes, lips parted very slightly, absorbed in thought',
    'direct gaze with full composure — owns the frame',
    'gentle closed-mouth smile, inner warmth rather than performance',
    'eyes raised to the side as if recalling a poem or a feeling',
    'chin slightly lowered, gaze upward — soft and knowing',
    'serene and still — not blank, just deeply at peace',
    'the hint of a smile just arriving — joy at a private thought',
    'eyes closed, face turned up — receiving light or scent',
  ],

  handDetailPools: [
    'fingers trailing along the spine of a row of books',
    'both hands cradling a china teacup, thumbs resting on the rim',
    'one hand lifting a strand of pearls from a tray',
    'fingertips pinching a silk ribbon and letting it slowly unwind',
    'pressing a dried flower petal between index finger and thumb',
    'hand resting on an open book page, holding it flat',
    'one hand reaching into a bowl of rose petals, lifting them',
    'two hands carefully buttoning a lace cuff with pearl buttons',
    'fingertip drawing a slow line along a lace tablecloth edge',
    'holding a lit match or taper to a candle wick',
  ],

  movementEnergyPools: [
    'unhurried — each gesture takes the full time it deserves',
    'slow, deliberate, as if moving through warm water',
    'small precise movements — fingers, not arms',
    'minimal — stillness punctuated by single soft gestures',
    'fluid without being dramatic — natural feminine movement',
    'turning slowly, lace fabric following a half-beat behind',
  ],

  transitionPools: [
    'moving from bedroom to garden via dressing room — the ritual of becoming',
    'from kitchen breakfast to garden late morning — cup in hand, stepping outside',
    'from afternoon boudoir to golden hour garden — stepping through French doors',
    'from dinner table to parlour evening — candle carried between rooms',
    'from parlour to bedroom — single candle, footsteps on wooden floor',
    'blowing out one candle and moving to the next room with the warmth',
  ],

  narrativeIntentPools: [
    'a woman who has built her world exactly as she imagined it',
    'femininity not as performance but as private devotion',
    'the day as a series of beautiful decisions',
    'lace is not fragility — it is the most intricate form of strength',
    'she has nothing to prove and everything to savour',
    'the maximalism of a woman who has stopped apologising for her taste',
    'every object has a story; she is the one who chose them all',
    'beauty as practice, not outcome — the doing is the point',
  ],

  fallbackRules: {
    missingSubLocation: 'lace-bedroom',
    missingLight: 'soft warm diffused window light, 4500K, ivory walls bouncing fill',
    missingAction: 'standing softly in full lace outfit, hands resting at waist, gaze forward or downcast',
    missingMood: 'romantic, ultra-feminine, unhurried maximalism',
  },

  exclusions: [
    'no dark gothic tones (this is romantic, not gothic)',
    'no masculinised styling or minimalism',
    'no stark clinical light or modern interiors',
    'no fast or high-energy movement',
    'no ironic or subversive framing — this world takes its femininity seriously',
    'no sports, athleisure, or casual streetwear',
    'no digital or screen elements',
  ],

  routeRules: {
    default_world_id: 'lace-era',
    preferredAspectRatio: '4:5',
    imageStyle: 'editorial fashion photography, film grain optional, natural colour grading warm ivory-pink',
    cameraProfile: 'Canon EOS R5 or medium format film, 85mm portrait lens preferred',
  },
}
