export const STORY_WORLD_MEGA_YACHT = {
  id: 'mega-yacht',
  name: 'Mega Yacht',
  description:
    'A cinematic world of ultra-luxury on open water — superyacht decks above the Mediterranean or Caribbean, swim platforms at sea, helicopter pads and sunbathing above the open water, the particular prestige of international waters with no horizon but yours.',

  geography: { country: 'international waters / Mediterranean / Caribbean', region: 'superyacht deck, swim platform, master cabin, sky lounge, bow and stern, open Mediterranean or Caribbean sea' },

  identity: {
    archetype: 'superyacht luxury woman',
    vibe: ['50m+ superyacht above open water', 'the most exclusive deck in the world', 'Mediterranean or Caribbean prestige on water', 'the horizon belongs to her', 'ultra-luxury at sea'],
    tone: ['ultra-luxury', 'exclusive', 'sea-breeze', 'cinematic', 'open-water-free', 'composed', 'elevated'],
    persona: ['completely at home on the most exclusive vessel in the ocean', 'moving through superyacht space with complete ownership', 'the most beautiful person above the open water', 'belonging to the rarefied world of superyacht luxury'],
  },

  phaseOrder: ['wake', 'morning_refresh', 'getting_dressed', 'breakfast', 'late_morning', 'lunch', 'afternoon', 'reset', 'golden_hour', 'dinner', 'evening', 'night'],

  phases: {
    wake:            { label: 'Wake',            timeWindows: ['master cabin wake with ocean horizon visible', 'first Mediterranean or Caribbean morning on the yacht'],  pacing: 'slow',   subLocations: ['master-cabin', 'yacht-bedroom'] },
    morning_refresh: { label: 'Morning Refresh', timeWindows: ['yacht master bathroom morning ritual', 'cabin bathroom above open water in morning'],                      pacing: 'slow',   subLocations: ['yacht-bathroom', 'vanity-yacht'] },
    getting_dressed: { label: 'Getting Dressed', timeWindows: ['yacht morning dressing in master cabin', 'choosing the yacht day look in open water morning'],             pacing: 'slow',   subLocations: ['master-cabin', 'yacht-bathroom'] },
    breakfast:       { label: 'Breakfast',       timeWindows: ['breakfast on yacht deck with ocean horizon', 'open water morning meal above the sea'],                     pacing: 'slow',   subLocations: ['main-deck', 'sky-lounge'] },
    late_morning:    { label: 'Late Morning',    timeWindows: ['bow or deck in strong late-morning open water sun', 'yacht movement through open water in morning'],        pacing: 'medium', subLocations: ['yacht-bow', 'main-deck'] },
    lunch:           { label: 'Lunch',           timeWindows: ['yacht deck lunch in full open water sun', 'al-fresco superyacht lunch above the sea'],                     pacing: 'slow',   subLocations: ['main-deck', 'sky-lounge'] },
    afternoon:       { label: 'Afternoon',       timeWindows: ['swim platform or deck in strongest afternoon open water sun', 'anchored at sea — afternoon swim'],          pacing: 'medium', subLocations: ['swim-platform', 'yacht-deck-afternoon'] },
    reset:           { label: 'Reset',           timeWindows: ['cabin or sky lounge reset before the yacht evening', 'below deck private reset after the sun'],            pacing: 'slow',   subLocations: ['master-cabin', 'vanity-yacht'] },
    golden_hour:     { label: 'Golden Hour',     timeWindows: ['yacht deck at golden hour above the open sea', 'Mediterranean or Caribbean sunset from the yacht stern'],   pacing: 'slow',   subLocations: ['yacht-stern', 'main-deck'] },
    dinner:          { label: 'Dinner',          timeWindows: ['superyacht candlelit deck dinner above the sea', 'yacht sky lounge or main deck dinner'],                   pacing: 'slow',   subLocations: ['yacht-dinner-deck', 'sky-lounge'] },
    evening:         { label: 'Evening',         timeWindows: ['yacht evening at anchor or underway', 'sky lounge after dinner above the dark sea'],                       pacing: 'slow',   subLocations: ['sky-lounge', 'yacht-stern'] },
    night:           { label: 'Night',           timeWindows: ['master cabin private night above the open sea', 'yacht private night in cabin with ocean outside'],        pacing: 'slow',   subLocations: ['master-cabin', 'yacht-bedroom'] },
  },

  locations: [
    'superyacht master cabin with ocean horizon visible', 'main deck breakfast above open water', 'yacht bow in strong late-morning sun',
    'swim platform at anchor in open Mediterranean or Caribbean', 'yacht deck at golden hour above the sea', 'superyacht stern at sunset',
    'sky lounge dinner above the sea', 'yacht candlelit dinner deck in warm night', 'master cabin private night above the ocean',
  ],

  subLocations: {
    'master-cabin': {
      id: 'master-cabin', name: 'Master Cabin', mapAnchor: 'superyacht master cabin',
      category: 'private-yacht',
      bestPhases: ['wake', 'getting_dressed', 'reset', 'night'],
      overlays: ['luxury master cabin with ocean horizon windows', 'private yacht interior in warm morning', 'superyacht master suite in sea light'],
      locations: ['master cabin with ocean horizon visible through porthole windows', 'superyacht master suite in morning sea light', 'private yacht master cabin interior'],
    },
    'yacht-bedroom': {
      id: 'yacht-bedroom', name: 'Yacht Bedroom', mapAnchor: 'private yacht cabin bedroom',
      category: 'private-cabin',
      bestPhases: ['wake', 'night'],
      overlays: ['private yacht cabin bedroom', 'open sea barely visible through porthole', 'yacht private sleeping cabin in warm interior'],
      locations: ['private yacht cabin in morning sea light', 'yacht bedroom above the open water', 'private superyacht sleeping interior'],
    },
    'yacht-bathroom': {
      id: 'yacht-bathroom', name: 'Yacht Bathroom', mapAnchor: 'superyacht master bathroom',
      category: 'self-care-yacht',
      bestPhases: ['morning_refresh'],
      overlays: ['luxury yacht bathroom with ocean through porthole', 'superyacht master bathroom in morning light', 'yacht morning self-care ritual at sea'],
      locations: ['superyacht master bathroom in morning sea light', 'yacht bathroom ritual above the ocean', 'luxury marine bathroom interior'],
    },
    'vanity-yacht': {
      id: 'vanity-yacht', name: 'Yacht Vanity', mapAnchor: 'yacht cabin vanity',
      category: 'preparation-yacht',
      bestPhases: ['morning_refresh', 'reset'],
      overlays: ['yacht vanity in cabin interior', 'sea light through porthole at the vanity', 'yacht preparation ritual in marine interior'],
      locations: ['yacht vanity in cabin with sea light', 'preparation vanity at superyacht master cabin', 'yacht beauty ritual in marine interior'],
    },
    'main-deck': {
      id: 'main-deck', name: 'Main Deck', mapAnchor: 'superyacht main deck above the sea',
      category: 'outdoor-luxury-yacht',
      bestPhases: ['breakfast', 'late_morning', 'lunch'],
      overlays: ['superyacht main deck with full ocean horizon', 'outdoor luxury above open water', 'yacht deck in warm Mediterranean or Caribbean light'],
      locations: ['superyacht main deck above open water', 'yacht outdoor deck with full ocean panorama', 'main deck in warm sea-breeze luxury'],
    },
    'sky-lounge': {
      id: 'sky-lounge', name: 'Sky Lounge', mapAnchor: 'superyacht sky lounge upper deck',
      category: 'luxury-interior-yacht',
      bestPhases: ['breakfast', 'lunch', 'dinner', 'evening'],
      overlays: ['sky lounge with panoramic ocean glass walls', 'interior luxury above the sea', 'superyacht sky lounge in warm interior light'],
      locations: ['superyacht sky lounge above the sea with panoramic glass', 'yacht sky lounge interior in warm luxury', 'upper deck sky lounge with ocean panorama'],
    },
    'yacht-bow': {
      id: 'yacht-bow', name: 'Yacht Bow', mapAnchor: 'superyacht bow in open water',
      category: 'editorial-bow',
      bestPhases: ['late_morning'],
      overlays: ['yacht bow above open water in late-morning sun', 'bow in motion or at anchor above the sea', 'editorial bow moment in strong sea light'],
      locations: ['superyacht bow in open sea in late-morning light', 'yacht bow with ocean panorama behind', 'editorial bow pose above the Mediterranean or Caribbean'],
    },
    'swim-platform': {
      id: 'swim-platform', name: 'Swim Platform', mapAnchor: 'yacht swim platform at stern',
      category: 'water-luxury',
      bestPhases: ['afternoon'],
      overlays: ['yacht swim platform at sea — water visible all around', 'swimming off the yacht into open sea', 'swim platform with ladder and open ocean behind'],
      locations: ['superyacht swim platform above the Mediterranean or Caribbean', 'swim platform at anchor in open water', 'the swim off the superyacht into the sea'],
    },
    'yacht-deck-afternoon': {
      id: 'yacht-deck-afternoon', name: 'Yacht Afternoon Deck', mapAnchor: 'superyacht afternoon deck lounging',
      category: 'sunbathing-yacht',
      bestPhases: ['afternoon'],
      overlays: ['superyacht deck in strongest afternoon sun', 'loungers above the open sea in afternoon heat', 'yacht sunbathing above the ocean'],
      locations: ['superyacht loungers on deck in afternoon sea light', 'sunbathing above the Mediterranean or Caribbean', 'yacht deck sunbathing in strongest afternoon sun'],
    },
    'yacht-stern': {
      id: 'yacht-stern', name: 'Yacht Stern', mapAnchor: 'superyacht stern above the sea',
      category: 'golden-hour-view',
      bestPhases: ['golden_hour', 'evening'],
      overlays: ['superyacht stern with ocean horizon behind', 'golden hour or evening from the stern above the sea', 'the most cinematic yacht location at sunset'],
      locations: ['superyacht stern at golden hour with sea horizon', 'yacht stern in amber sea sunset', 'the most cinematic view from the superyacht stern'],
    },
    'yacht-dinner-deck': {
      id: 'yacht-dinner-deck', name: 'Dinner Deck', mapAnchor: 'superyacht candlelit dinner deck',
      category: 'dining-yacht',
      bestPhases: ['dinner'],
      overlays: ['superyacht candlelit dinner deck above the sea at night', 'luxury al-fresco dinner above open water', 'yacht dinner setting with candles and ocean'],
      locations: ['superyacht candlelit dinner above the sea', 'al-fresco yacht dinner deck in warm evening', 'luxury dinner on the yacht in warm sea air'],
    },
  },

  sceneVariants: {
    wake: ['waking in the superyacht master cabin with ocean visible through the porthole windows', 'the yacht morning — private and exclusive above the open sea'],
    morning_refresh: ['yacht master bathroom morning ritual above the ocean', 'the superyacht morning self-care in warm marine interior'],
    getting_dressed: ['choosing the yacht day look in the master cabin morning', 'dressing for the deck in superyacht interior light'],
    breakfast: ['deck breakfast above the sea with full ocean horizon in warm morning', 'sky lounge breakfast above the Mediterranean or Caribbean'],
    late_morning: ['yacht bow in open sea in late-morning sun — the editorial sea moment', 'the main deck in strong late-morning sea-breeze light'],
    lunch: ['al-fresco deck lunch above the open sea in full sun', 'sky lounge lunch above the sea in warm superyacht interior'],
    afternoon: ['swim platform at anchor — diving into the open Mediterranean or Caribbean sea', 'deck sunbathing in the strongest afternoon sea light'],
    reset: ['master cabin private reset below deck before the yacht evening', 'the superyacht private cabin reset between day sun and golden-hour deck'],
    golden_hour: ['the stern at golden hour — the sea turning amber all around the superyacht', 'deck golden hour above the open sea — the most cinematic yacht moment'],
    dinner: ['candlelit dinner on the superyacht deck above the dark sea', 'sky lounge dinner above the sea in warm yacht evening'],
    evening: ['sky lounge after dinner above the sea at night', 'stern at night above the dark Mediterranean or Caribbean'],
    night: ['master cabin above the dark open sea at night', 'private cabin night in the superyacht above the ocean'],
  },

  actionPools: {
    wake: ['waking in the master cabin with ocean visible through the porthole', 'the superyacht morning — private and exclusive above the sea', 'the yacht beginning its day from the private master cabin'],
    morning_refresh: ['yacht master bathroom morning ritual above the ocean', 'marine interior self-care in warm superyacht morning', 'the yacht morning preparation beginning in luxury marine setting'],
    getting_dressed: ['choosing the yacht day look — swimwear, cover, or linen — in the master cabin', 'the superyacht morning dressing ritual in master cabin interior', 'dressing for the deck in warm yacht morning interior light'],
    breakfast: ['breakfast on the deck above the sea with coffee and ocean panorama', 'sky lounge breakfast with panoramic ocean glass walls around', 'the morning yacht meal above the open water'],
    late_morning: ['standing at the bow above the open sea in strong late-morning light', 'the main deck in sea-breeze and strong late-morning Mediterranean or Caribbean sun', 'the editorial yacht bow moment above open water'],
    lunch: ['al-fresco lunch on the superyacht deck above the sea in full noon sun', 'sky lounge lunch in warm superyacht interior with ocean panorama', 'the yacht lunch — the most exclusive lunch setting on earth'],
    afternoon: ['diving off the swim platform into the open sea', 'sunbathing on the superyacht deck in the strongest afternoon sea light', 'swimming off the yacht in open Mediterranean or Caribbean water'],
    reset: ['returning below deck to master cabin after afternoon at sea and sun', 'the superyacht private reset in cabin before the golden-hour deck', 'yacht cabin reset between day sun and the evening'],
    golden_hour: ['the stern at golden hour — the sea turning amber all around', 'deck at golden hour above the open sea — the most cinematic yacht moment', 'the superyacht at its most beautiful — golden hour above open water'],
    dinner: ['candlelit dinner on the superyacht deck above the dark sea', 'sky lounge dinner in warm luxury above the Mediterranean or Caribbean night', 'the most exclusive dinner on earth — on the superyacht deck'],
    evening: ['sky lounge after dinner above the sea at night — the yacht world at rest', 'stern evening above the dark open sea in yacht luxury', 'the superyacht evening — private, exclusive, and above the world'],
    night: ['master cabin private night above the dark open sea', 'the superyacht at rest in open water at night', 'private yacht cabin in the dark sea at night — the most exclusive private night'],
  },

  environmentPools: {
    wake: ['master cabin with ocean horizon through porthole windows in morning sea light', 'private superyacht master suite above open water in morning', 'yacht interior in warm marine morning light'],
    morning_refresh: ['luxury superyacht master bathroom above the sea in morning light', 'yacht bathroom with ocean barely visible through porthole', 'marine interior self-care setting in yacht morning'],
    getting_dressed: ['master cabin morning dressing in warm marine interior light', 'superyacht interior in warm morning sea light for dressing', 'yacht cabin dressing in private morning sea light'],
    breakfast: ['superyacht main deck above open sea in warm morning', 'sky lounge with panoramic ocean glass in breakfast morning light', 'the most exclusive outdoor breakfast setting — above the open sea'],
    late_morning: ['yacht bow above open water in strong late-morning Mediterranean or Caribbean sun', 'main deck with ocean panorama in late-morning sea-breeze', 'the superyacht above the open sea in late-morning editorial light'],
    lunch: ['al-fresco deck above the sea in full noon sun at the superyacht table', 'sky lounge in warm superyacht interior with ocean all around at lunch', 'the most exclusive lunch environment — superyacht deck above open water'],
    afternoon: ['swim platform at stern with open sea visible all around at anchor', 'superyacht deck in the strongest afternoon Mediterranean or Caribbean sun', 'yacht afternoon at sea — swim platform or deck sunbathing'],
    reset: ['master cabin below deck in warm private afternoon light', 'superyacht private cabin reset between day and evening', 'yacht interior in warm private afternoon before the golden-hour deck'],
    golden_hour: ['superyacht stern with the entire sea horizon turning amber at golden hour', 'deck at golden hour with the most beautiful sea panorama in amber light', 'the superyacht in open water at the most cinematic marine golden hour'],
    dinner: ['superyacht deck al-fresco candlelit dinner above the dark sea in warm evening', 'sky lounge in warm superyacht interior dinner above the sea at night', 'the most exclusive dinner environment on earth'],
    evening: ['sky lounge above the dark sea in warm yacht evening interior', 'yacht stern at night above the dark Mediterranean or Caribbean', 'superyacht evening in luxury private setting above open water'],
    night: ['master cabin above the dark open sea in warm private yacht night', 'private superyacht cabin in warm interior above the ocean at night', 'the most exclusive private night — above the open sea in the superyacht'],
  },

  moodPools: {
    wake: ['exclusive private yacht morning above the open sea', 'the superyacht at rest in the morning — private and above the world', 'the most exclusive morning wake in the world'],
    morning_refresh: ['yacht morning self-care in private marine luxury', 'the superyacht morning preparation ritual energy', 'private yacht self-care above the open sea'],
    getting_dressed: ['yacht dressing ritual — choosing for deck and sea', 'the superyacht morning dressing energy above open water', 'private exclusive yacht morning dressing ease'],
    breakfast: ['deck breakfast ease above the open sea', 'the most exclusive morning meal on earth on the superyacht deck', 'yacht morning luxury above the open water'],
    late_morning: ['free and alive above the open sea on the yacht bow or deck', 'superyacht late-morning editorial open-water energy', 'the most exclusive deck in the world in late-morning sea light'],
    lunch: ['the superyacht lunch — the most exclusive al-fresco on earth', 'open water deck lunch in full yacht luxury', 'exclusive midday above the sea on the superyacht'],
    afternoon: ['open-sea freedom at the swim platform or deck', 'the superyacht afternoon — swimming and sunbathing above the world', 'the most exclusive afternoon in the world at anchor in open water'],
    reset: ['private yacht cabin reset between day and golden hour', 'below-deck ease before the most beautiful part of the day', 'superyacht private cabin reset in warm afternoon'],
    golden_hour: ['the superyacht at golden hour — the entire sea turning amber around the vessel', 'the most cinematic yacht moment — the sea and the boat and the light', 'the most exclusive golden-hour on earth above open water'],
    dinner: ['superyacht dinner — the most exclusive dinner on the planet above the dark sea', 'candlelit al-fresco dinner above the Mediterranean or Caribbean at night', 'the yacht dinner — exclusive, cinematic, and beautiful above open water'],
    evening: ['superyacht evening above the dark sea in luxury private ease', 'the most exclusive evening — sky lounge or stern above the ocean at night', 'yacht evening in warm private marine luxury'],
    night: ['the most private and exclusive night — above the open sea on the superyacht', 'master cabin above dark water at night in yacht luxury', 'private marine night in the most exclusive vessel in the world'],
  },

  cameraPools: {
    wake: ['85mm low angle in master cabin, porthole ocean barely visible dissolved behind', '135mm close-up at face height, warm marine morning light defining edge'],
    morning_refresh: ['85mm yacht bathroom mirror close, ocean through porthole dissolved behind', '50mm yacht bathroom mid shot, marine morning light compressing behind'],
    getting_dressed: ['50mm master cabin dressing framing, marine interior depth behind', '85mm yacht cabin dressing angle, warm marine interior behind subject'],
    breakfast: ['24mm wide deck breakfast, ocean horizon filling entire background beyond', '85mm sky lounge breakfast framing, panoramic ocean glass behind subject'],
    late_morning: ['135mm bow close-up, open sea dissolving in marine light behind', '24mm wide bow shot, open sea horizon filling all background'],
    lunch: ['85mm deck lunch framing, ocean horizon compressed behind the table', '50mm sky lounge lunch side, panoramic ocean glass behind seated subject'],
    afternoon: ['24mm wide swim platform, open sea all around in background', '50mm deck sunbathing low angle, sea surface in foreground, horizon dissolved beyond'],
    reset: ['85mm yacht cabin reset, marine interior depth dissolved behind subject', '135mm cabin close, warm marine afternoon interior behind'],
    golden_hour: ['135mm stern golden-hour close, amber sea rim light defining edge of subject', '24mm wide stern shot, entire sea turning amber around the vessel in background'],
    dinner: ['85mm candlelit deck portrait, warm candle as key source, dark sea beyond', '50mm sky lounge dinner side, warm yacht interior and dark sea through glass behind'],
    evening: ['85mm sky lounge evening, warm interior with dark sea through panoramic glass', '50mm stern evening, dark sea and yacht lights in background'],
    night: ['135mm cabin night close-up, single warm lamp as sole source', '85mm soft side angle, warm cabin interior, porthole dark outside'],
  },

  lightingPools: {
    wake: ['pale 5600K sea morning entering through porthole, warm edge on white linen and cabin interior', 'soft marine morning through porthole, warm sea-reflected light in cabin interior'],
    morning_refresh: ['clean 5800K yacht bathroom in marine morning, bright and warm on luxury surfaces', 'sea-reflected light in yacht bathroom — the particular beauty of marine morning'],
    getting_dressed: ['warm 5200K marine morning in master cabin, natural sea light through porthole on fabric', 'yacht interior warm morning dressing light in private cabin'],
    breakfast: ['warm 5400K open sea deck morning, secondary fill from sea surface below', 'sky lounge panoramic ocean morning — clean 5600K from all directions through glass'],
    late_morning: ['5000K open sea late-morning in strong Mediterranean or Caribbean sun, specular on water', 'clear sea-breeze day — high saturation and color in strong marine light'],
    lunch: ['high noon 5800K on deck or sky lounge, ocean surface creating secondary fill below', 'warm marine noon — al-fresco deck in full Mediterranean or Caribbean sun'],
    afternoon: ['strong 4600K Mediterranean or Caribbean afternoon, water surface creating moving light', 'swim platform — warm sea reflecting light in the most beautiful marine afternoon'],
    reset: ['warm 4000K yacht cabin in afternoon reset, soft and flattering in marine interior', 'private cabin warm afternoon ambient — the yacht below deck in afternoon ease'],
    golden_hour: ['rich 2700K golden sea horizon light entering from low angle, everything amber', 'warm sunset from open sea at near-zero angle — the most beautiful marine golden hour'],
    dinner: ['candlelight at 1800K on deck above dark sea, warm intimate fill with ocean beyond', 'warm yacht evening candlelit dinner — 2600K mix on deck or sky lounge'],
    evening: ['warm 2800K sky lounge interior above dark sea, ocean barely visible through glass', 'yacht stern evening — warm 2600K navigation lights and ambient above dark water'],
    night: ['single warm 2200K cabin lamp, porthole dark outside, warm marine night interior', 'private superyacht night — warm 2400K cabin ambient, the sea invisible outside'],
  },

  stylingPools: {
    wardrobe: {
      wake: ['silk in master cabin morning above the sea', 'private yacht morning minimal in marine interior', 'warm private yacht morning in white or silk linen'],
      morning_refresh: ['white towel in yacht bathroom after morning rinse', 'marine morning wrap after shower', 'yacht bathroom private morning before the deck'],
      getting_dressed: ['luxury swimwear and linen cover for the deck', 'yacht day look — bikini and cover-up for the open sea', 'the superyacht deck look — elevated swimwear and luxury cover'],
      breakfast: ['linen cover or yacht morning look at deck breakfast', 'sky lounge morning look — elevated casual for the open sea breakfast', 'yacht morning deck breakfast styling'],
      late_morning: ['editorial swimwear at the yacht bow or deck', 'luxury bikini at the superyacht bow in late-morning sea light', 'the yacht bow editorial look in open sea'],
      lunch: ['elevated beach or yacht cover at deck lunch', 'sky lounge elevated yacht casual for midday above the sea', 'superyacht lunch styling — elevated and sea-breeze perfect'],
      afternoon: ['luxury swimwear at swim platform or deck — the most important afternoon detail', 'editorial bikini at sea anchor in strongest afternoon light', 'swim platform swimwear in Mediterranean or Caribbean afternoon'],
      reset: ['linen robe or cover in cabin reset after sea and sun', 'private cabin wrap or cover in the yacht afternoon reset', 'below-deck reset look in yacht interior warmth'],
      golden_hour: ['golden-hour yacht deck look — elevated and warm', 'the most beautiful deck look at golden hour above the sea', 'yacht golden-hour styling — silk, linen, or elevated swimwear in amber light'],
      dinner: ['superyacht dinner look — elevated elegant above the sea', 'yacht dinner styling — silk dress or elevated evening above the ocean', 'the most exclusive dinner look on earth — al-fresco superyacht'],
      evening: ['yacht evening look — elevated warm interior sky lounge styling', 'post-dinner superyacht evening above the dark sea', 'warm yacht evening look in sky lounge interior'],
      night: ['private cabin night above the dark sea — silk or minimal', 'yacht private night in master cabin — warm and intimate', 'private superyacht night — the most exclusive private night look'],
    },
    details: {
      wake: ['warm sea morning hair on yacht pillow', 'bare warm skin in marine morning', 'private yacht morning natural detail'],
      morning_refresh: ['natural post-sea-morning freshness', 'wet or fresh hair in yacht bathroom', 'marine morning skin detail in warm light'],
      getting_dressed: ['yacht accessory — gold with swimwear', 'sun oil or SPF on yacht deck preparation', 'the yacht day look detail — elevated coastal accessory'],
      breakfast: ['breakfast prop detail on yacht deck', 'coffee and ocean air at deck table', 'yacht morning styling detail in sea-breeze light'],
      late_morning: ['bow editorial swimwear detail in sea light', 'sea-breeze hair at the yacht bow', 'editorial marine detail in late-morning light'],
      lunch: ['elevated lunch detail on superyacht deck', 'chilled wine or water glass at yacht table above the sea', 'superyacht al-fresco lunch styling detail'],
      afternoon: ['water on skin at swim platform — the defining yacht afternoon detail', 'sea-wet hair at the swim platform or deck', 'open-sea water-soaked afternoon yacht detail'],
      reset: ['linen or robe post-sea detail in cabin', 'below-deck reset styling detail', 'private yacht cabin afternoon ease detail'],
      golden_hour: ['amber sea light on skin and silk at the yacht golden hour', 'warm gold accessory in amber sea light', 'yacht golden-hour detail — elevated and beautiful'],
      dinner: ['elevated dinner jewelry on superyacht deck', 'silk dress detail in warm yacht candlelight above the sea', 'the most exclusive dinner detail — on the superyacht above open water'],
      evening: ['warm sky lounge or stern evening detail', 'yacht evening accessory in warm interior or above dark sea', 'post-dinner superyacht evening styling detail'],
      night: ['private cabin night detail — warm and intimate', 'yacht private night after the sea day', 'the most exclusive private night detail — above the open sea'],
    },
    changeMoments: {
      wake: ['private morning in master cabin before the deck day', 'silk or nothing above the morning sea in private cabin'],
      morning_refresh: ['between cabin and deck — in yacht bathroom morning ritual', 'towel wrap after yacht morning bathroom'],
      getting_dressed: ['choosing the deck look — swimwear and cover for the superyacht', 'the yacht day look being assembled in cabin'],
      breakfast: ['elevated deck morning look for breakfast above the sea', 'the yacht morning at the deck table'],
      late_morning: ['editorial swimwear at the bow in sea light', 'the yacht editorial look in late-morning sea'],
      lunch: ['elevated lunch look on the superyacht deck or sky lounge', 'the most exclusive midday above the sea'],
      afternoon: ['swimwear at the swim platform or deck — editorial peak', 'the yacht afternoon in open water — editorial swimwear at sea'],
      reset: ['transitioning from sea day to yacht evening in cabin', 'below-deck reset from swimwear to yacht evening'],
      golden_hour: ['the yacht golden-hour deck look — elevated from the day', 'silk or elevated look in the amber sea light'],
      dinner: ['fully assembled yacht dinner look above the open sea', 'the most exclusive dinner look on earth'],
      evening: ['post-dinner superyacht evening in sky lounge or on stern', 'the yacht world at evening ease above the dark sea'],
      night: ['private master cabin night above the open sea', 'the most exclusive private night — on the superyacht'],
    },
  },

  sensoryPools: {
    wake: ['sea air through the porthole in yacht morning', 'the gentle motion of the superyacht in private morning', 'warm marine interior in the first moments of the open sea day'],
    morning_refresh: ['warm marine bathroom above the sea in morning', 'the particular clean of a yacht bathroom rinse above open water', 'marine morning self-care in the most exclusive setting'],
    getting_dressed: ['the anticipation of the deck in yacht morning dressing', 'sea-breeze beginning to enter the cabin in marine morning', 'warm yacht interior in private dressing morning'],
    breakfast: ['salt air and sea-breeze at deck breakfast above the horizon', 'the open sea smell at the most beautiful breakfast table on earth', 'ocean all around at the superyacht deck breakfast'],
    late_morning: ['wind and sea spray at the yacht bow in open water', 'strong sea-breeze and Mediterranean or Caribbean sun at late morning', 'the most alive sensory moment — above open water at the bow'],
    lunch: ['sea air and warm sun at the superyacht deck lunch', 'the open water around the most exclusive lunch table', 'Mediterranean or Caribbean warm sea at the yacht al-fresco lunch'],
    afternoon: ['warm sea water at the swim platform — the defining yacht sensory', 'salt and warm open Mediterranean or Caribbean at sea anchor', 'diving into the open sea from the superyacht — the most alive sensory'],
    reset: ['warm below-deck cabin after the sea and sun', 'the interior yacht air in private cabin reset', 'warm private marine interior after the open-water afternoon'],
    golden_hour: ['warm amber sea air at the stern at golden hour', 'the entire open sea turning amber around the superyacht — the most cinematic marine sensory', 'warm golden sea light at the most cinematic open water moment'],
    dinner: ['sea air and candlelight above the dark Mediterranean or Caribbean at dinner', 'warm candle and ocean air at the superyacht dinner deck', 'the most exclusive dinner sensory — above the open sea at night'],
    evening: ['warm sky lounge interior above dark open water', 'the particular warmth of a superyacht evening above the dark sea', 'warm yacht evening in private luxury above the world'],
    night: ['the gentle motion of the superyacht above dark open water at night', 'private cabin above the open sea — the most exclusive private night sensory', 'warm marine interior above the dark open water at night'],
  },

  socialEnergyPools: {
    wake: ['completely private yacht morning above the sea', 'the superyacht at rest in private morning — exclusively yours'],
    morning_refresh: ['private yacht self-care above the sea', 'alone in the marine bathroom before the deck day begins'],
    getting_dressed: ['private yacht morning dressing ritual', 'alone choosing the deck look in the master cabin'],
    breakfast: ['private yacht deck ease — the crew serves, the horizon is yours', 'exclusive morning social ease above the open sea'],
    late_morning: ['the bow — visible on the most exclusive deck in the world', 'editorial yacht presence in the most exclusive sea setting'],
    lunch: ['exclusive yacht lunch ease — the sea is the only company that matters', 'al-fresco superyacht lunch social in the most exclusive setting'],
    afternoon: ['open-sea freedom at the swim platform — the most private exclusive afternoon', 'the yacht anchored at sea — completely yours in open water'],
    reset: ['below-deck private reset — the most exclusive private moment', 'alone in the master cabin after the sea afternoon'],
    golden_hour: ['the stern at golden hour — visible and stunning above the amber sea', 'the most cinematic exclusive visibility — the superyacht at golden hour'],
    dinner: ['yacht dinner social — the most exclusive dining social on earth', 'the superyacht candlelit dinner — the most exclusive table'],
    evening: ['private sky lounge or stern evening above the sea', 'yacht evening social ease in luxury private marine setting'],
    night: ['completely private above the open sea in master cabin', 'the most exclusive private night — the superyacht at night'],
  },

  atmospherePools: {
    wake: ['warm marine morning above the open sea — the most exclusive wake in the world', 'superyacht private morning above the horizon', 'the yacht at rest in morning — quiet and exclusively yours'],
    morning_refresh: ['warm marine bathroom morning atmosphere', 'yacht morning self-care above the sea', 'the most exclusive morning ritual — on the superyacht at sea'],
    getting_dressed: ['master cabin morning dressing atmosphere above the open sea', 'warm marine interior before the deck day begins', 'private superyacht dressing atmosphere'],
    breakfast: ['deck breakfast atmosphere above the full ocean horizon — the most exclusive morning', 'sky lounge panoramic morning atmosphere above the sea', 'the superyacht breakfast atmosphere — the most exclusive in the world'],
    late_morning: ['open sea at the bow — the most free and alive marine atmosphere', 'yacht late-morning above the Mediterranean or Caribbean — strong light and sea-breeze', 'the editorial bow atmosphere in open water'],
    lunch: ['al-fresco deck lunch atmosphere above the open sea in full sun', 'sky lounge lunch atmosphere — panoramic ocean glass all around', 'the most exclusive lunch atmosphere — the superyacht at sea'],
    afternoon: ['open-sea swim platform atmosphere — sea all around at anchor', 'deck sunbathing above the Mediterranean or Caribbean in strongest afternoon', 'the most exclusive afternoon atmosphere — the superyacht at sea anchor'],
    reset: ['below-deck private cabin atmosphere after sea and sun', 'warm marine interior in private afternoon ease', 'private yacht cabin reset atmosphere'],
    golden_hour: ['the most beautiful marine atmosphere — the superyacht at golden hour with amber sea', 'open-water sunset atmosphere — the entire sea turning amber around the vessel', 'golden hour on the superyacht — the most cinematic marine atmosphere'],
    dinner: ['superyacht candlelit dinner deck atmosphere — the most exclusive dinner', 'sky lounge dinner above the sea atmosphere in warm marine evening', 'the most exclusive dinner atmosphere on earth — above the open sea'],
    evening: ['warm sky lounge or stern atmosphere above the dark sea', 'private marine evening atmosphere in the most exclusive setting', 'superyacht evening atmosphere in warm luxury above the world'],
    night: ['private master cabin night atmosphere above the open sea', 'the superyacht at night — the most exclusive private marine atmosphere', 'warm interior night above the dark open sea'],
  },

  propPools: {
    wake: ['porthole with ocean barely visible in morning light', 'luxury yacht bedding in master cabin', 'marine morning detail in private cabin interior'],
    morning_refresh: ['yacht bathroom marine interior detail', 'luxury marine bathroom morning products', 'porthole in yacht bathroom with ocean light'],
    getting_dressed: ['swimwear or linen cover for the yacht deck', 'sun oil and accessories in yacht cabin morning', 'the deck look being assembled in the master cabin'],
    breakfast: ['coffee or juice at the deck table with ocean horizon behind', 'deck breakfast service above the open sea', 'the superyacht deck breakfast setting with ocean all around'],
    late_morning: ['bow railing above the open sea in late-morning', 'wind in hair at the yacht bow with sea panorama', 'editorial bow detail above open water'],
    lunch: ['chilled white wine or water at the deck lunch table', 'superyacht al-fresco lunch setting above the sea', 'sky lounge lunch props with ocean through panoramic glass'],
    afternoon: ['swim platform ladder into open Mediterranean or Caribbean sea', 'the open sea all around the yacht at anchor', 'deck lounger in strongest afternoon sea light'],
    reset: ['linen or robe in yacht cabin reset', 'marine interior afternoon ease prop detail', 'below-deck yacht prop in private afternoon'],
    golden_hour: ['the amber sea horizon from the stern at golden hour', 'champagne glass in warm amber sea light at golden hour', 'the superyacht stern with the entire sea amber behind'],
    dinner: ['candles on the superyacht dinner deck above the dark sea', 'white tablecloth al-fresco above the Mediterranean or Caribbean at night', 'wine and luxury dinner detail on the superyacht deck'],
    evening: ['sky lounge interior with dark sea through panoramic glass', 'champagne in warm sky lounge or stern above the night sea', 'warm yacht evening prop above the dark open water'],
    night: ['single warm lamp in master cabin with porthole dark beyond', 'private yacht cabin bedding at night above the open sea', 'the most exclusive private night prop — the superyacht above dark water'],
  },

  bodyLanguagePools: {
    wake: ['slow warm yacht morning posture in master cabin above the sea', 'private marine morning body language in yacht luxury', 'the most exclusive morning wake body language — above the open sea'],
    morning_refresh: ['warm yacht bathroom morning ritual posture', 'marine morning self-care body language above the sea', 'private yacht bathroom morning ease'],
    getting_dressed: ['deliberate yacht dressing body language in master cabin', 'choosing the deck look posture in marine interior', 'warm private yacht dressing ease in morning'],
    breakfast: ['deck breakfast posture — relaxed luxury above the sea with complete ease', 'the superyacht deck breakfast body language — the horizon is yours', 'sky lounge morning posture with panoramic ocean all around'],
    late_morning: ['the bow posture — confident and alive above the open sea', 'editorial yacht bow body language in marine light', 'the superyacht late-morning body language — the most exclusive deck in the world'],
    lunch: ['al-fresco deck lunch posture in warm sea-breeze', 'sky lounge lunch body language with ocean all around', 'the superyacht lunch body ease — the most exclusive'],
    afternoon: ['swim platform posture — at the edge of the open sea', 'deck sunbathing posture above the Mediterranean or Caribbean', 'the yacht afternoon body language — free and alive above the open water'],
    reset: ['below-deck private cabin reset body language', 'warm marine interior afternoon ease', 'private yacht cabin reset body language between sea and evening'],
    golden_hour: ['the stern at golden hour — the most cinematic yacht posture', 'standing above the amber sea at the superyacht stern', 'the golden-hour yacht body language — the entire sea yours'],
    dinner: ['superyacht dinner posture — the most exclusive dining body language', 'candlelit above the dark sea at dinner on the deck', 'yacht dinner composure — the most elevated marine dining'],
    evening: ['sky lounge or stern evening body language above the dark sea', 'warm yacht evening marine posture in luxury interior', 'the superyacht evening body — private and elevated'],
    night: ['private master cabin night above the dark sea', 'warm marine private night body language in the superyacht', 'the most exclusive private night posture — above the open ocean'],
  },

  facialExpressionPools: {
    wake: ['warm marine morning expression in private cabin', 'the superyacht morning — private and exclusive expression', 'warm sea morning face above the horizon'],
    morning_refresh: ['marine morning fresh expression in yacht bathroom', 'private yacht self-care expression above the sea', 'warm marine morning ritual expression'],
    getting_dressed: ['warm yacht morning dressing expression in marine interior', 'the superyacht dressing moment — calm and exclusive', 'private cabin above the sea — morning expression'],
    breakfast: ['deck breakfast ease expression — the horizon is yours', 'superyacht morning deck ease expression', 'sky lounge breakfast expression with ocean panorama around'],
    late_morning: ['alive and free expression at the yacht bow in open sea', 'the most exciting marine expression — above open water at the bow', 'editorial yacht expression in strong sea light at the bow'],
    lunch: ['relaxed exclusive deck lunch expression above the sea', 'superyacht lunch ease — the most exclusive midday expression', 'warm sea-breeze expression at the deck lunch'],
    afternoon: ['the most alive open-sea expression — swim platform in Mediterranean or Caribbean', 'free and exclusive afternoon expression above the open water', 'swim platform expression — the open sea all around'],
    reset: ['warm private cabin reset expression after sea and sun', 'below-deck ease expression in marine afternoon interior', 'private cabin yacht reset expression'],
    golden_hour: ['the superyacht golden-hour expression — the amber sea all around', 'the most cinematic marine expression — at the stern in amber light', 'warm amber sea expression at the yacht golden hour'],
    dinner: ['warm exclusive dinner expression on the superyacht deck', 'the most exclusive dinner face — above the dark sea on the yacht', 'superyacht candlelit dinner expression in warm sea air'],
    evening: ['warm private sky lounge or stern evening expression', 'exclusive marine evening expression above the dark open water', 'warm yacht evening expression in luxury private marine setting'],
    night: ['private master cabin night expression above the dark sea', 'the most exclusive private night expression — on the superyacht', 'warm marine private night expression in the most exclusive setting'],
  },

  handDetailPools: {
    wake: ['hand on yacht linen in morning cabin', 'fingers near porthole in warm morning light', 'hand on warm marine cabin surface in morning'],
    morning_refresh: ['hand on yacht bathroom counter above the sea', 'fingers in marine bathroom morning detail', 'hand in warm yacht bathroom morning ritual'],
    getting_dressed: ['hand on swimwear or cover in cabin dressing selection', 'fingers applying sun oil in yacht morning preparation', 'deck look being assembled — hand detail in marine cabin'],
    breakfast: ['hand around coffee or juice cup at deck above the horizon', 'fingers on deck table with ocean behind', 'hand resting at deck breakfast table with sea all around'],
    late_morning: ['hand on bow railing above open water in sea light', 'fingers in sea-breeze hair at the yacht bow', 'hand at the yacht bow with open sea panorama behind'],
    lunch: ['hand near wine or water glass at superyacht deck lunch', 'fingers on deck table above the sea at lunch', 'the most exclusive hand detail — at the superyacht al-fresco lunch'],
    afternoon: ['hand in sea water at the swim platform', 'fingers trailing through open Mediterranean or Caribbean water', 'the swim platform hand — the most alive marine hand detail'],
    reset: ['hand on below-deck cabin surface in afternoon reset', 'fingers near linen or robe in yacht cabin reset', 'warm private marine hand in cabin afternoon ease'],
    golden_hour: ['hand at stern railing with amber sea behind at golden hour', 'champagne glass hand at yacht golden hour', 'the most cinematic yacht hand detail — at stern in amber sea light'],
    dinner: ['hand near wine glass above the dark sea at yacht dinner', 'fingers on white tablecloth at superyacht dinner deck', 'the most exclusive dinner hand — above the open sea at night'],
    evening: ['hand on sky lounge surface with dark sea through glass', 'champagne hand above the dark open water in yacht evening', 'warm private marine evening hand detail'],
    night: ['hand near warm cabin lamp above the dark sea', 'fingers on yacht linen in private marine night', 'the most exclusive private night hand — on the superyacht'],
  },

  movementEnergyPools: {
    wake: ['slow', 'marine-morning', 'exclusive'],
    morning_refresh: ['private', 'ritual', 'sea-warm'],
    getting_dressed: ['deliberate', 'yacht-ease', 'deck-ready'],
    breakfast: ['relaxed', 'sea-breeze', 'exclusive'],
    late_morning: ['alive', 'free', 'open-sea'],
    lunch: ['easy', 'exclusive', 'sea-warmth'],
    afternoon: ['free', 'water', 'alive'],
    reset: ['private', 'below-deck', 'marine-ease'],
    golden_hour: ['cinematic', 'amber-sea', 'still'],
    dinner: ['exclusive', 'candlelit', 'marine-elegance'],
    evening: ['private', 'yacht-ease', 'warm'],
    night: ['quiet', 'exclusive', 'marine-dark'],
  },

  transitionPools: {
    human: {
      wake: ['the superyacht morning above the open sea', 'private marine morning in the most exclusive vessel'],
      morning_refresh: ['yacht bathroom morning ritual above the water', 'marine self-care in private cabin morning'],
      getting_dressed: ['choosing the deck look in the master cabin', 'dressing for the superyacht day above the sea'],
      breakfast: ['deck breakfast above the full ocean horizon', 'the most exclusive breakfast above the open water'],
      late_morning: ['the bow above the open sea in late-morning', 'the superyacht editorial moment in open water'],
      lunch: ['al-fresco lunch on the superyacht deck', 'the most exclusive lunch above the sea'],
      afternoon: ['swim platform at anchor in the open sea', 'diving off the superyacht into open water'],
      reset: ['below-deck cabin reset after the sea afternoon', 'private cabin between sea day and yacht evening'],
      golden_hour: ['the stern at golden hour — the sea turning amber', 'the most cinematic yacht golden-hour moment'],
      dinner: ['superyacht candlelit dinner above the dark sea', 'the most exclusive dinner on earth'],
      evening: ['sky lounge or stern evening above the dark water', 'yacht evening in warm private marine luxury'],
      night: ['private master cabin above the dark open sea', 'the most exclusive private night in the world'],
    },
  },

  narrativeIntentPools: {
    wake: ['the superyacht morning — the most exclusive private wake in the world above the open sea', 'private marine luxury at its most exclusive beginning'],
    morning_refresh: ['yacht self-care above the sea — the private marine morning ritual', 'the most exclusive morning preparation in the world'],
    getting_dressed: ['choosing for the deck and the sea — the superyacht day look', 'the most exclusive dressing ritual — on the superyacht above open water'],
    breakfast: ['the most exclusive breakfast on earth — above the full ocean horizon', 'the superyacht morning luxury at the deck table with sea all around'],
    late_morning: ['the bow above open water — the most free and alive marine editorial', 'the superyacht at sea in late-morning — the most exclusive deck in the world'],
    lunch: ['the most exclusive lunch on earth — al-fresco above the open sea', 'superyacht al-fresco luxury at the most beautiful outdoor table'],
    afternoon: ['open-sea freedom at the swim platform — the most exclusive afternoon', 'the superyacht at anchor in open water — the world is yours'],
    reset: ['below-deck private ease after the open-sea afternoon', 'the most exclusive private reset — in the superyacht master cabin'],
    golden_hour: ['the superyacht at golden hour — the entire sea turning amber around the vessel', 'the most cinematic marine moment — above open water at golden hour'],
    dinner: ['the most exclusive dinner on earth — above the open sea on the superyacht', 'superyacht dinner at night — candlelit above the dark Mediterranean or Caribbean'],
    evening: ['the superyacht evening — private, exclusive, and above the world', 'warm luxury marine evening in the most exclusive private setting'],
    night: ['the most exclusive private night on earth — the superyacht above the open sea', 'private master cabin above dark open water — the ultimate exclusive'],
  },

  fallbackRules: {
    pacingProfile: { wake: 'slow', morning_refresh: 'slow', getting_dressed: 'slow', breakfast: 'slow', late_morning: 'medium', lunch: 'slow', afternoon: 'medium', reset: 'slow', golden_hour: 'slow', dinner: 'slow', evening: 'slow', night: 'slow' },
    repetitionBreakers: { avoidBackToBackSameLocation: true, avoidBackToBackSameLightingStyle: true, encourageWardrobeEvolution: true },
    worldDefaults: { allowSceneGroupFallbackToPhasePools: true, allowSubLocationFallbackToWorldPools: true, preferSceneGroupsWhenPresent: true },
  },

  exclusions: {
    premium: ['non-luxury boat or charter settings', 'crowded marina energy', 'fishing boat aesthetic', 'non-exclusive water settings'],
    hard: ['land or urban settings without water context', 'corporate or office settings', 'cold weather marine settings', 'non-superyacht water settings'],
  },

  routeRules: {
    worldIdentity: ['the mega yacht world must feel ultra-exclusive, open-water, sun-drenched, and marine-luxurious throughout', 'the superyacht deck, swim platform, master cabin, and sky lounge are the core locations'],
    humanFlow: ['the day begins in private master cabin morning, moves to deck breakfast and bow editorial, through afternoon swim platform at anchor, golden-hour stern moment, yacht dinner, and private cabin night'],
    styling: ['luxury swimwear, elegant covers, and superyacht elevated deck wear — evolving to silk or elevated evening for dinner and private cabin silk for night'],
    atmosphere: ['open Mediterranean or Caribbean sea always present — the sea is the defining environmental element throughout', 'the superyacht above open water is the constant world'],
  },
}
