export const STORY_WORLD_ROCKSTAR = {
  id: 'rockstar',
  name: 'Rockstar',
  description:
    'A cinematic world of stadium energy and hotel room mythology — the stage at 80,000, backstage before and after, tour bus and hotel suite between cities, the particular glamour of someone who owns a stage and knows it.',

  geography: { country: 'global music world', region: 'concert stage, backstage, tour hotel suite, tour bus, VIP dressing room, after-show venue' },

  identity: {
    archetype: 'rockstar — stage presence and tour luxury',
    vibe: ['the stage as the most powerful room on earth', 'backstage mythology and pre-show ritual', 'hotel suite mythology on tour', 'the body and the mic and the crowd', 'music as identity and power'],
    tone: ['electric', 'raw', 'powerful', 'magnetic', 'tour-mythological', 'cinematic', 'free'],
    persona: ['the most powerful person on the stage and the most real in the hotel room', 'owns every room she enters including the one with 80,000 people', 'the particular combination of discipline and freedom that creates a rockstar', 'beautiful in both the spotlight and the 4am hotel quiet'],
  },

  phaseOrder: ['wake', 'morning_refresh', 'getting_dressed', 'breakfast', 'late_morning', 'lunch', 'afternoon', 'reset', 'golden_hour', 'dinner', 'evening', 'night'],

  phases: {
    wake:            { label: 'Wake',            timeWindows: ['tour hotel morning after a show', 'late morning wake after a late night on stage'],        pacing: 'slow',   subLocations: ['tour-hotel-bedroom', 'hotel-suite-morning'] },
    morning_refresh: { label: 'Morning Refresh', timeWindows: ['hotel bathroom after the show night', 'tour morning self-care ritual'],                       pacing: 'slow',   subLocations: ['hotel-bathroom', 'hotel-vanity'] },
    getting_dressed: { label: 'Getting Dressed', timeWindows: ['tour hotel dressing morning', 'rockstar style selection before the day'],                     pacing: 'slow',   subLocations: ['hotel-suite-morning', 'hotel-vanity'] },
    breakfast:       { label: 'Breakfast',       timeWindows: ['late hotel breakfast after the show', 'tour morning meal in hotel'],                          pacing: 'slow',   subLocations: ['tour-hotel-bedroom', 'hotel-suite-morning'] },
    late_morning:    { label: 'Late Morning',    timeWindows: ['soundcheck or venue arrival', 'pre-show afternoon in venue environment'],                     pacing: 'medium', subLocations: ['venue-backstage', 'soundcheck-stage'] },
    lunch:           { label: 'Lunch',           timeWindows: ['backstage lunch before the show', 'catering at venue in pre-show energy'],                   pacing: 'slow',   subLocations: ['backstage-catering', 'venue-backstage'] },
    afternoon:       { label: 'Afternoon',       timeWindows: ['pre-show preparation and dressing', 'backstage transformation into stage persona'],           pacing: 'slow',   subLocations: ['dressing-room-rockstar', 'backstage-mirror'] },
    reset:           { label: 'Reset',           timeWindows: ['final pre-show backstage ritual', 'the hour before the stage'],                              pacing: 'slow',   subLocations: ['dressing-room-rockstar', 'backstage-mirror'] },
    golden_hour:     { label: 'Golden Hour',     timeWindows: ['side of the stage before going on', 'the golden light before the show begins'],              pacing: 'slow',   subLocations: ['stage-side', 'venue-backstage'] },
    dinner:          { label: 'Dinner',          timeWindows: ['on stage — the show at full power', 'the concert in full energy'],                            pacing: 'slow',   subLocations: ['on-stage', 'concert-peak'] },
    evening:         { label: 'Evening',         timeWindows: ['after-show backstage', 'post-show adrenaline in backstage or after-party'],                  pacing: 'medium', subLocations: ['after-show-backstage', 'tour-after-party'] },
    night:           { label: 'Night',           timeWindows: ['after-show hotel suite at 2-4am', 'the rockstar after the stage — private and real'],        pacing: 'slow',   subLocations: ['tour-hotel-bedroom', 'hotel-suite-morning'] },
  },

  locations: [
    'tour hotel suite morning after the show', 'backstage dressing room before the stage',
    'the stage in spotlight at full show energy', 'soundcheck on the empty stage',
    'backstage catering and pre-show ritual', 'side of stage before going on',
    'after-show backstage in full adrenaline', 'hotel suite at 4am after the concert',
  ],

  subLocations: {
    'tour-hotel-bedroom': {
      id: 'tour-hotel-bedroom', name: 'Tour Hotel Bedroom', mapAnchor: 'hotel bedroom on tour',
      category: 'private-tour',
      bestPhases: ['wake', 'night'],
      overlays: ['hotel room on tour — the mythology of the rock hotel suite', 'scattered tour life and warm private morning', 'the morning after the show in private hotel luxury'],
      locations: ['tour hotel bedroom in late morning after the show', 'hotel suite on tour — private and warm', 'the rock mythology hotel room morning'],
    },
    'hotel-suite-morning': {
      id: 'hotel-suite-morning', name: 'Hotel Suite Morning', mapAnchor: 'hotel suite on tour',
      category: 'private-hotel-tour',
      bestPhases: ['wake', 'breakfast', 'getting_dressed', 'night'],
      overlays: ['luxury hotel suite interior on tour', 'the morning after the show — scattered energy', 'tour hotel suite in warm private morning'],
      locations: ['hotel suite morning on tour', 'luxury tour hotel interior in warm morning', 'the morning after the concert in hotel suite'],
    },
    'hotel-bathroom': {
      id: 'hotel-bathroom', name: 'Hotel Bathroom', mapAnchor: 'tour hotel bathroom',
      category: 'self-care-tour',
      bestPhases: ['morning_refresh'],
      overlays: ['hotel bathroom on tour after the show', 'post-show shower and morning ritual', 'tour morning self-care in hotel luxury'],
      locations: ['hotel bathroom morning ritual on tour', 'post-show shower in hotel bathroom', 'tour morning bathroom self-care setting'],
    },
    'hotel-vanity': {
      id: 'hotel-vanity', name: 'Hotel Vanity', mapAnchor: 'hotel vanity on tour',
      category: 'preparation-tour',
      bestPhases: ['morning_refresh', 'getting_dressed'],
      overlays: ['hotel vanity in morning on tour', 'rockstar morning preparation at hotel mirror', 'tour morning beauty ritual at hotel vanity'],
      locations: ['hotel vanity morning preparation on tour', 'rockstar morning ritual at the hotel mirror', 'tour hotel morning getting-ready setting'],
    },
    'venue-backstage': {
      id: 'venue-backstage', name: 'Venue Backstage', mapAnchor: 'concert venue backstage',
      category: 'backstage',
      bestPhases: ['late_morning', 'lunch', 'golden_hour'],
      overlays: ['concert venue backstage before the show', 'pre-show backstage energy building', 'the backstage world before the stage'],
      locations: ['backstage corridor before the show', 'venue backstage in pre-show energy', 'the pre-show backstage world'],
    },
    'soundcheck-stage': {
      id: 'soundcheck-stage', name: 'Soundcheck Stage', mapAnchor: 'empty stage at soundcheck',
      category: 'stage-prep',
      bestPhases: ['late_morning'],
      overlays: ['the empty stage at soundcheck in afternoon venue light', 'the stage before the crowd — the most private stage moment', 'soundcheck on the concert stage in venue light'],
      locations: ['empty concert stage at soundcheck in afternoon', 'the stage in venue light before the show', 'soundcheck on the most powerful stage'],
    },
    'backstage-catering': {
      id: 'backstage-catering', name: 'Backstage Catering', mapAnchor: 'backstage catering area',
      category: 'pre-show-fuel',
      bestPhases: ['lunch'],
      overlays: ['backstage catering in pre-show energy', 'the rockstar eating backstage before the show', 'backstage catering ritual before the stage'],
      locations: ['backstage catering before the concert', 'the pre-show meal in backstage setting', 'backstage food ritual in pre-show energy'],
    },
    'dressing-room-rockstar': {
      id: 'dressing-room-rockstar', name: 'Rockstar Dressing Room', mapAnchor: 'rockstar backstage dressing room',
      category: 'transformation-backstage',
      bestPhases: ['afternoon', 'reset'],
      overlays: ['the rockstar dressing room before the show', 'mirrors and lights and the stage persona being assembled', 'the transformation into the rockstar in the dressing room'],
      locations: ['rockstar dressing room backstage before the show', 'the pre-show transformation in the backstage mirror', 'the dressing room where the rockstar becomes herself'],
    },
    'backstage-mirror': {
      id: 'backstage-mirror', name: 'Backstage Mirror', mapAnchor: 'backstage mirror with lights',
      category: 'pre-show-mirror',
      bestPhases: ['afternoon', 'reset'],
      overlays: ['the lit backstage mirror before going on', 'the rockstar face being assembled in backstage light', 'the pre-show mirror ritual'],
      locations: ['lit backstage mirror in pre-show preparation', 'the dressing room mirror before the stage', 'backstage mirror with makeup lights'],
    },
    'stage-side': {
      id: 'stage-side', name: 'Stage Side', mapAnchor: 'side of stage before going on',
      category: 'pre-show-threshold',
      bestPhases: ['golden_hour'],
      overlays: ['side of the stage before going on — the most electric pre-show moment', 'the crowd visible, the lights warm, the threshold before the stage', 'the rockstar at the edge of the stage about to go on'],
      locations: ['side of the concert stage with crowd visible before going on', 'the threshold before the stage in warm concert light', 'side of stage — the most electric pre-performance moment'],
    },
    'on-stage': {
      id: 'on-stage', name: 'On Stage', mapAnchor: 'concert stage in spotlight',
      category: 'stage-peak',
      bestPhases: ['dinner'],
      overlays: ['the concert stage in spotlight at full show energy', 'the rockstar performing for the crowd', 'the most powerful stage moment — full show at peak'],
      locations: ['concert stage in spotlight during the show', 'the rockstar performing at full concert energy', 'the stage — the most powerful room on earth'],
    },
    'concert-peak': {
      id: 'concert-peak', name: 'Concert Peak', mapAnchor: 'concert at full energy peak',
      category: 'performance-peak',
      bestPhases: ['dinner'],
      overlays: ['the concert at its most electric peak', 'stage lights and crowd energy at maximum', 'the rockstar at full performance power on stage'],
      locations: ['concert at full peak energy in stage light', 'the performance at its most electric', 'stage at maximum energy and power'],
    },
    'after-show-backstage': {
      id: 'after-show-backstage', name: 'After-Show Backstage', mapAnchor: 'backstage after the show',
      category: 'post-show',
      bestPhases: ['evening'],
      overlays: ['backstage after the show — adrenaline and warm energy', 'the dressing room after the concert', 'post-show backstage in warm electric aftermath'],
      locations: ['backstage after the concert in adrenaline warmth', 'the dressing room after the show', 'post-show backstage energy'],
    },
    'tour-after-party': {
      id: 'tour-after-party', name: 'Tour After-Party', mapAnchor: 'after-show party',
      category: 'post-show-social',
      bestPhases: ['evening'],
      overlays: ['after-show party in warm venue or hotel space', 'the rockstar at the after-party post-concert', 'warm social energy after the show'],
      locations: ['after-show party after the concert', 'rockstar at the post-show celebration', 'warm electric after-party energy'],
    },
  },

  sceneVariants: {
    wake: ['late hotel morning after the show — the tour mythology morning', 'waking in a hotel suite on tour with the show energy still in the room'],
    morning_refresh: ['hotel bathroom tour morning after the concert', 'the rockstar morning ritual on tour in hotel bathroom'],
    getting_dressed: ['hotel suite getting ready on tour — the rockstar morning look', 'dressing for the day between cities on tour'],
    breakfast: ['late hotel breakfast after the show — tour morning fuel', 'the tour morning meal in the hotel suite'],
    late_morning: ['soundcheck on the empty stage in venue light', 'the pre-show venue arrival and backstage atmosphere'],
    lunch: ['backstage catering before the show in pre-show energy', 'the rockstar eating backstage before the concert'],
    afternoon: ['backstage dressing room transformation — becoming the stage persona', 'the pre-show mirror ritual in the rockstar dressing room'],
    reset: ['the final hour before the stage — backstage and charged', 'the pre-show ritual complete — ready for the stage'],
    golden_hour: ['side of the stage before going on — the most electric pre-show moment', 'the threshold between backstage and the stage in warm concert light'],
    dinner: ['on the concert stage in spotlight at full show energy', 'the rockstar performing at the peak of the concert'],
    evening: ['backstage after the show in post-concert adrenaline', 'the after-show energy backstage or at the party'],
    night: ['hotel suite at 4am after the concert — the rockstar private', 'the real private person after the stage at 4am in the hotel room'],
  },

  actionPools: {
    wake: ['late morning wake in hotel suite after the concert', 'the tour hotel morning — slow and private after the show', 'waking in the mythology of a tour hotel room'],
    morning_refresh: ['hotel bathroom morning ritual after the show night', 'the post-show morning self-care on tour', 'tour morning in hotel bathroom after the concert'],
    getting_dressed: ['choosing the tour day look in hotel suite morning', 'the rockstar hotel dressing ritual on tour', 'hotel vanity morning preparation on tour'],
    breakfast: ['late hotel breakfast after a concert night', 'tour morning fuel in hotel suite', 'the post-show morning hotel breakfast ritual'],
    late_morning: ['soundcheck on the empty stage in venue light', 'the pre-show venue walk and backstage arrival', 'the stage at soundcheck — the empty most powerful room'],
    lunch: ['backstage catering before the concert', 'the pre-show meal in backstage setting', 'eating in the backstage pre-show energy'],
    afternoon: ['the dressing room transformation — becoming the stage persona', 'the backstage mirror ritual before the show', 'the pre-show transformation in the rockstar dressing room'],
    reset: ['the final pre-show backstage hour', 'the pre-show ritual complete at the backstage mirror', 'the charged hour before the stage begins'],
    golden_hour: ['standing at the side of the stage with the crowd visible beyond', 'the most electric moment — side of stage about to go on', 'the threshold between backstage and the concert stage'],
    dinner: ['on the concert stage in spotlight at full concert energy', 'performing at the peak of the show in stage light', 'the stage — the most powerful moment of the rockstar life'],
    evening: ['backstage after the show in post-concert adrenaline', 'the after-show party in warm electric energy', 'post-concert euphoria backstage or at the after-party'],
    night: ['hotel suite at 4am after the concert — real and private', 'the rockstar after the stage — alone and warm in the tour hotel', 'the private person at 4am after 80,000 people'],
  },

  environmentPools: {
    wake: ['tour hotel suite in late morning light after the concert', 'hotel bedroom on tour with scattered tour energy and warm morning', 'the mythology hotel room morning after the show'],
    morning_refresh: ['hotel bathroom on tour after the concert night', 'warm hotel bathroom morning ritual', 'tour hotel bathroom in warm morning light after the show'],
    getting_dressed: ['hotel suite morning dressing area on tour', 'hotel vanity in tour morning warm light', 'the rockstar morning getting-ready setting in hotel suite'],
    breakfast: ['hotel suite or room service in tour morning', 'late hotel breakfast after the concert', 'the tour hotel morning meal setting'],
    late_morning: ['the concert venue backstage in pre-show energy', 'the empty stage at soundcheck in venue afternoon light', 'backstage venue before the show'],
    lunch: ['backstage catering area in pre-show energy', 'the backstage meal setting before the concert', 'pre-show backstage fuel area'],
    afternoon: ['the rockstar dressing room with lit mirror and pre-show energy', 'backstage dressing room in transformation preparation', 'the lit backstage mirror in pre-show transformation'],
    reset: ['backstage charged final hour before the stage', 'the dressing room in the final pre-show moment', 'backstage at maximum pre-show energy before going on'],
    golden_hour: ['side of the stage with crowd and concert lights visible', 'the stage threshold in warm concert golden light before going on', 'the most electric pre-show stage-side moment'],
    dinner: ['concert stage in spotlight at full show energy', 'the stage lights and crowd at maximum concert energy', 'on-stage at the peak of the concert'],
    evening: ['backstage after the show in post-concert adrenaline warmth', 'the after-show space in warm electric backstage energy', 'post-show energy in backstage or after-party'],
    night: ['hotel suite at 4am after the concert in warm private quiet', 'the tour hotel room at night after the show', 'private quiet in the hotel after the most powerful night'],
  },

  moodPools: {
    wake: ['post-show private morning ease — the tour mythology wake', 'late hotel morning after the concert — warm and real', 'the particular warmth of waking after being on stage'],
    morning_refresh: ['tour morning self-care after the show night', 'the post-concert morning ritual energy', 'warm private tour hotel bathroom morning'],
    getting_dressed: ['tour day dressing energy — between cities and between shows', 'the rockstar between performances — real and composed', 'hotel suite morning dressing on tour'],
    breakfast: ['post-show hotel morning ease and fuel', 'late tour breakfast after the concert night', 'the warm tour hotel morning after the stage'],
    late_morning: ['the pre-show energy building at the venue', 'soundcheck on the empty stage — the most powerful quiet moment', 'the venue before the show — electric anticipation'],
    lunch: ['backstage pre-show calm and fuel', 'the pre-show eating ritual in backstage energy', 'building toward the show in backstage setting'],
    afternoon: ['the transformation — becoming the stage persona in the dressing room', 'the pre-show ritual building toward full stage readiness', 'the backstage mirror before the stage — most charged moment of preparation'],
    reset: ['the final charged pre-show hour — maximum anticipation', 'the backstage at full pre-show peak — ready', 'the threshold moment before the most powerful room'],
    golden_hour: ['the most electric pre-show moment — side of stage with crowd beyond', 'the stage threshold energy at maximum', 'the rockstar at the edge of the most powerful moment'],
    dinner: ['on stage — the most powerful energy in the rockstar world', 'full concert stage presence at peak energy', 'the stage — complete power and presence and freedom'],
    evening: ['post-show adrenaline and electric relief', 'the after-show energy — the concert complete', 'electric post-performance energy in warm backstage'],
    night: ['the private real person after the stage — warm and true', 'the hotel after the show — the mythology moment', '4am hotel truth after 80,000 people'],
  },

  cameraPools: {
    wake: ['85mm low angle in tour hotel suite, warm morning light through curtains dissolved behind', '135mm close-up at face height, tour hotel morning light defining edge'],
    morning_refresh: ['85mm hotel bathroom mirror close, tour morning reflection at same focal plane', '50mm hotel vanity mid shot, warm tour morning light compressing behind'],
    getting_dressed: ['50mm hotel suite dressing framing, tour hotel depth behind', '85mm hotel mirror morning angle, warm tour interior behind subject'],
    breakfast: ['24mm wide hotel suite breakfast, tour hotel interior in warm background', '85mm tour hotel morning meal framing, hotel room depth behind'],
    late_morning: ['85mm empty stage soundcheck medium, vast empty venue behind in ambient', '50mm backstage venue wide, backstage energy and corridors behind'],
    lunch: ['85mm backstage catering seated, pre-show backstage energy behind subject', '50mm backstage lunch framing, venue energy dissolved behind'],
    afternoon: ['85mm dressing room mirror close, lit mirror creating dramatic key light', '50mm backstage transformation wide, dressing room depth and energy behind'],
    reset: ['135mm backstage charged close, warm backstage light on face before going on', '85mm backstage pre-show medium, backstage energy building behind subject'],
    golden_hour: ['135mm stage-side backlit close, concert light and crowd dissolved in warm behind', '85mm stage threshold shot, stage opening and crowd behind subject'],
    dinner: ['85mm on-stage dramatic medium, spotlight creating key light, crowd dissolved', '50mm wide stage shot, concert lights and stage design filling background'],
    evening: ['85mm post-show backstage medium, warm aftermath light behind subject', '50mm after-party wide, warm post-show venue energy behind'],
    night: ['135mm hotel suite night close, single warm lamp as sole source', '85mm soft side angle, warm tour hotel room dissolved behind subject'],
  },

  lightingPools: {
    wake: ['warm 4500K hotel morning through curtains, soft scattered light across hotel suite after the show', 'pale warm hotel morning light in tour suite interior'],
    morning_refresh: ['clean 5200K hotel bathroom in tour morning, fresh and warm on white surfaces', 'warm hotel bathroom light on post-show morning skin'],
    getting_dressed: ['warm 4800K hotel interior morning, dressing area in tour suite light', 'hotel suite morning warm light on clothing and rock aesthetic'],
    breakfast: ['warm 5000K hotel morning for late breakfast after the show', 'hotel suite morning service in warm tour light'],
    late_morning: ['5000K venue overhead ambient at soundcheck — vast and industrial on the empty stage', 'pre-show venue natural and overhead light in backstage corridors'],
    lunch: ['warm 4200K backstage catering area light — functional and warm pre-show', 'backstage pre-show light in catering setting'],
    afternoon: ['warm 3000K lit dressing room mirror — theatrical makeup light on skin', 'the backstage transformation light — lit mirror against warm dressing room backdrop'],
    reset: ['warm 2800K pre-show backstage — charged atmospheric warm light', 'backstage pre-show warm amber building anticipation'],
    golden_hour: ['dramatic concert warm light at stage-side — mixed warm stage and venue light', 'warm 2900K stage side light with concert mix visible before going on'],
    dinner: ['dramatic concert stage lighting — high-contrast key spots and atmospheric fills, mixed warm', 'stage lighting — the most dramatic mixed-source light of the rockstar world'],
    evening: ['warm 2800K post-show backstage — warm relief and electric warmth after the stage', 'post-show warm ambient with adrenaline energy in backstage'],
    night: ['single warm 2200K hotel lamp at 4am, pool of quiet light after the show', 'warm 2400K tour hotel room at night — private and still after the stage'],
  },

  stylingPools: {
    wardrobe: {
      wake: ['hotel morning — whatever was left from last night, leather or band shirt', 'tour hotel private morning look — real and rockstar simultaneously', 'the mythology of what a rockstar wears in a tour hotel morning'],
      morning_refresh: ['hotel robe or nothing in tour hotel bathroom', 'post-show shower and private tour morning', 'the real person after the stage in hotel bathroom warm'],
      getting_dressed: ['leather jacket and rock aesthetic for the tour day', 'band or vintage rock styling between shows', 'the rockstar tour day look — real and aesthetically powerful'],
      breakfast: ['rock morning tour look for hotel breakfast', 'tour day comfort aesthetic for post-show morning', 'the real rockstar morning hotel look'],
      late_morning: ['soundcheck or venue look — rock aesthetic in venue environment', 'backstage arrival look in authentic rock style', 'the pre-show venue look — real and powerful'],
      lunch: ['backstage rock aesthetic for pre-show catering', 'the rockstar eating backstage — real and composed', 'pre-show authentic rock styling in backstage setting'],
      afternoon: ['pre-show transformation beginning in dressing room', 'stage look being assembled in the dressing room', 'the stage persona being built on the body in the dressing room'],
      reset: ['the complete stage look — the final rockstar transformation', 'full stage persona assembled before going on', 'the most powerful version of the rock look before the stage'],
      golden_hour: ['the stage look at the threshold — complete and electric', 'full stage persona at the side of the stage', 'the complete rockstar stage look at maximum power'],
      dinner: ['the full concert stage look in spotlight', 'the stage persona at peak power in concert lighting', 'the complete rockstar performance look on stage'],
      evening: ['post-show look — stage persona slightly loosened after the concert', 'the rockstar after the show — real but still electric', 'after-show styling in warm post-concert energy'],
      night: ['hotel private late-night after the concert — real and warm', 'the rockstar private at 4am — band shirt or nothing in hotel room', 'the mythology private hotel room look after the stage'],
    },
    details: {
      wake: ['dishevelled rock mythology morning hair in tour hotel', 'the morning after the show detail — real and electric', 'tour hotel morning energy in the styling detail'],
      morning_refresh: ['post-show skin in tour hotel bathroom morning', 'the natural face after the stage in morning light', 'tour hotel morning self-care detail'],
      getting_dressed: ['leather, chain, ring, or rock accessory for the tour day', 'the rock aesthetic detail in tour day styling', 'rockstar tour styling accessories'],
      breakfast: ['tour day rock aesthetic detail at hotel breakfast', 'real rock morning detail in hotel suite morning', 'the rockstar between shows detail'],
      late_morning: ['soundcheck and venue detail — the rock world before the show', 'backstage pass and venue energy detail', 'the pre-show venue detail'],
      lunch: ['backstage catering detail in pre-show energy', 'the pre-show fuel detail in backstage setting', 'rock pre-show detail in catering'],
      afternoon: ['stage makeup and styling being applied in dressing room', 'the transformation detail — stage persona building', 'dressing room makeup and rock styling assembly'],
      reset: ['complete stage look detail before going on', 'the final styling check detail at the backstage mirror', 'the pre-show complete rockstar detail'],
      golden_hour: ['full stage look detail at the stage side threshold', 'the most powerful rock styling moment before going on', 'stage persona detail at the concert threshold'],
      dinner: ['stage performance detail in concert spotlight', 'the rock performance aesthetic in stage light', 'full concert stage look detail'],
      evening: ['post-show energy detail in backstage warmth', 'the after-show real detail after the stage persona', 'post-concert natural and warm detail'],
      night: ['hotel private detail at 4am after the concert', 'the real person detail in warm hotel room night', 'the mythology 4am hotel detail'],
    },
    changeMoments: {
      wake: ['whatever the night left in the hotel morning — real and rockstar', 'the mythology tour hotel morning private state'],
      morning_refresh: ['hotel robe or nothing in tour bathroom', 'between show and tour day in hotel bathroom'],
      getting_dressed: ['the tour day rock look being assembled in hotel', 'dressing for the day between cities on tour'],
      breakfast: ['tour day rock aesthetic at hotel breakfast', 'real between-shows rockstar morning'],
      late_morning: ['the venue and soundcheck rock look', 'pre-show authentic at the venue'],
      lunch: ['backstage pre-show real rock aesthetic', 'the building pre-show rock energy in styling'],
      afternoon: ['stage look being assembled in dressing room', 'the transformation in progress'],
      reset: ['complete stage persona assembled — ready', 'the full stage look at the threshold'],
      golden_hour: ['full stage look at the side of the stage', 'the most powerful styling moment before the crowd'],
      dinner: ['on stage — the complete stage persona in concert light', 'the rockstar performing at full power'],
      evening: ['stage persona loosening after the show', 'post-show real but still electric'],
      night: ['private hotel after the show — real and 4am warm', 'the mythology private rockstar hotel night'],
    },
  },

  sensoryPools: {
    wake: ['the tour hotel warm morning after the show — the room smells of the night before', 'warm sheets in the mythology of a tour hotel suite after the concert', 'the particular private warmth of a rockstar morning after the stage'],
    morning_refresh: ['hotel shower washing off the show — warm and private', 'post-show clean skin in warm hotel bathroom', 'the clean private ritual after being seen by 80,000'],
    getting_dressed: ['leather and chain against post-show skin in hotel morning', 'the rock aesthetic fabric in warm tour hotel morning', 'getting dressed for the day between cities and between shows'],
    breakfast: ['late hotel breakfast after the concert night — warm and earned', 'the post-show morning fuel in tour hotel warmth', 'coffee and the warm tour morning after the stage'],
    late_morning: ['the empty concert stage at soundcheck — vast and electric even without the crowd', 'the particular silence of a stage before the show begins', 'the venue before the crowd — the most powerful empty space'],
    lunch: ['backstage catering — the particular backstage smell and energy before the show', 'the pre-show fuel in backstage setting', 'eating before the most powerful night in warm backstage energy'],
    afternoon: ['the dressing room before the show — the makeup and the music and the transformation', 'the backstage smell of hairspray and music and preparation', 'the lit mirror and the transformation ritual sensory'],
    reset: ['the charged pre-show backstage hour — the most electric anticipation sensory', 'the final moment before going on stage — electric and charged and real', 'the body and the music and the 80,000 waiting beyond the stage'],
    golden_hour: ['the roar beginning as the lights dim — the crowd energy from the stage side', 'concert light on skin at the stage threshold before going on', 'the most electric sensory moment in the rockstar world'],
    dinner: ['the concert stage — the crowd, the sound, the light, the complete power', 'the physical electricity of performing for 80,000 in stage light', 'the stage — the most alive sensory experience in the world'],
    evening: ['post-show adrenaline and physical warmth backstage', 'the particular relief and electricity of after the show', 'warm post-concert energy and the body after the stage'],
    night: ['the tour hotel at 4am — the absolute private quiet after the most powerful night', 'warm hotel sheets at 4am and the quiet after the stage', 'the mythology of the hotel room after 80,000 people'],
  },

  socialEnergyPools: {
    wake: ['completely private tour hotel morning after the show', 'the rockstar before the world — alone and real in hotel warmth'],
    morning_refresh: ['private tour hotel bathroom morning', 'alone after the show in warm hotel bathroom'],
    getting_dressed: ['private tour hotel dressing between shows', 'the rockstar alone with the mirror in hotel morning'],
    breakfast: ['private or semi-private hotel morning after the concert', 'tour morning in hotel private ease'],
    late_morning: ['the venue and backstage — semi-public pre-show world', 'seen in the venue before the crowd arrives'],
    lunch: ['backstage social energy — crew and pre-show team', 'the pre-show backstage social world'],
    afternoon: ['the dressing room transformation — private ritual in semi-private backstage', 'the pre-show private transformation before the most public moment'],
    reset: ['the final backstage private charged hour before going on', 'alone at the stage threshold before 80,000'],
    golden_hour: ['side of stage — the most charged transition to maximum public visibility', 'the threshold before the most visible moment'],
    dinner: ['on stage — the most public moment in the rockstar world — 80,000 watching', 'maximum visibility at maximum power'],
    evening: ['post-show social warmth and backstage celebration', 'after-show energy — visible and celebrated after the stage'],
    night: ['completely private at 4am in the tour hotel after everything', 'the real private person after the most public night'],
  },

  atmospherePools: {
    wake: ['tour hotel mythology morning after the show', 'warm private post-concert morning in hotel suite', 'the rockstar morning — the mythology of the day after'],
    morning_refresh: ['warm tour hotel bathroom morning ritual after the concert', 'the private morning after being seen by thousands', 'clean private tour bathroom energy'],
    getting_dressed: ['tour hotel morning dressing atmosphere between shows', 'the between-cities rockstar daily life atmosphere', 'tour hotel suite morning energy'],
    breakfast: ['post-show late hotel breakfast atmosphere', 'warm tour morning after the concert night', 'the tour hotel morning meal energy'],
    late_morning: ['venue pre-show atmosphere — the space before the crowd', 'soundcheck on the empty stage — the most powerful pre-show atmosphere', 'pre-show venue energy building'],
    lunch: ['backstage pre-show catering atmosphere', 'the building pre-show energy in backstage world', 'pre-concert backstage atmosphere'],
    afternoon: ['dressing room pre-show transformation atmosphere', 'the backstage becoming-the-stage-persona atmosphere', 'the lit dressing room atmosphere before the concert'],
    reset: ['the charged final backstage hour — maximum pre-show atmosphere', 'the backstage at peak before going on', 'the pre-show atmosphere at its most electric'],
    golden_hour: ['stage-side pre-show atmosphere — the most electric', 'the concert threshold atmosphere with crowd energy building', 'the most powerful pre-show atmosphere'],
    dinner: ['concert stage atmosphere at full show energy — the most powerful atmosphere in music', 'on-stage atmosphere at 80,000 peak', 'the concert at its most alive'],
    evening: ['post-show backstage warm release atmosphere', 'the after-show energy — warm and electric and celebrating', 'post-concert atmosphere in warm backstage or party'],
    night: ['tour hotel 4am atmosphere after the show', 'the private mythology hotel room after the concert', 'the quiet after the most powerful night'],
  },

  propPools: {
    wake: ['tour hotel bedding scattered with rock mythology detail', 'hotel room tour morning props — real and electric', 'the mythology tour hotel morning detail'],
    morning_refresh: ['hotel bathroom tour morning prop detail', 'post-show shower in hotel bathroom', 'tour hotel bathroom morning ritual props'],
    getting_dressed: ['leather jacket or rock accessory in hotel morning', 'ring or chain or rock styling detail at hotel mirror', 'tour day rock aesthetic props in hotel suite'],
    breakfast: ['hotel room service or late breakfast props on tour', 'tour hotel morning coffee and post-show fuel', 'hotel suite tour morning breakfast detail'],
    late_morning: ['empty concert stage and venue equipment at soundcheck', 'backstage pass and backstage corridor detail', 'pre-show venue props and backstage world'],
    lunch: ['backstage catering trays and pre-show food detail', 'the backstage pre-concert meal props', 'pre-show fuel props in backstage setting'],
    afternoon: ['lit dressing room mirror and stage makeup detail', 'stage look being assembled — costumes and stage styling props', 'the dressing room transformation props'],
    reset: ['complete stage look at the backstage mirror', 'the final pre-show prop detail at backstage threshold', 'the charged pre-show backstage prop moment'],
    golden_hour: ['side of stage prop — the crowd and concert lights visible beyond', 'stage threshold prop detail before going on', 'the most electric prop detail in the rockstar world'],
    dinner: ['concert stage microphone and stage design in spotlight', 'the stage in full concert light — performance props', 'on-stage concert performance prop detail'],
    evening: ['post-show backstage champagne or celebration detail', 'after-show warm backstage prop', 'the after-concert celebration prop'],
    night: ['hotel suite 4am — whatever remains from the night', 'the tour mythology hotel room night props', 'warm private hotel at 4am after the show'],
  },

  bodyLanguagePools: {
    wake: ['the rockstar late morning hotel posture — real and warm after the show', 'post-concert morning body ease in hotel warmth', 'the private body language of a rockstar after the stage'],
    morning_refresh: ['warm hotel bathroom post-show morning body language', 'tour bathroom morning easy and real', 'the rockstar private morning body language'],
    getting_dressed: ['tour hotel dressing rock aesthetic body language', 'the between-shows rockstar body language at the hotel mirror', 'rock morning hotel body ease'],
    breakfast: ['late post-show hotel breakfast body ease', 'the tour morning meal body language — real and warm', 'rock morning tour hotel ease'],
    late_morning: ['soundcheck stage body language — powerful even in the empty venue', 'the rockstar on the empty stage at soundcheck — owning the space', 'pre-show venue body language before the crowd'],
    lunch: ['backstage pre-show relaxed but building body language', 'the pre-concert body language — building but controlled', 'backstage rock pre-show ease'],
    afternoon: ['dressing room transformation body language — becoming the stage persona', 'the building stage persona body language in the dressing room mirror', 'the pre-show transformation body energy'],
    reset: ['charged pre-show backstage body language — the final preparation', 'the most electric pre-show body energy before going on', 'the stage threshold body language at maximum charge'],
    golden_hour: ['stage-side body language — the most electric threshold posture', 'the rockstar at the stage edge about to go on — the defining posture', 'side of stage maximum charged body language'],
    dinner: ['on-stage body language at full concert power — the complete rockstar', 'stage performance body language at maximum energy', 'the most powerful body language in the rockstar world'],
    evening: ['post-show backstage body ease and electric relief', 'the after-show body language — the energy releasing after the stage', 'warm post-concert body ease and celebration'],
    night: ['the 4am hotel private body language — real and warm and alone', 'the rockstar private after the stage — the most human body language', 'warm private hotel night body ease at 4am'],
  },

  facialExpressionPools: {
    wake: ['tour hotel morning-after expression — real and warm and post-show', 'the rockstar morning face — electric even in rest', 'warm private post-concert morning expression'],
    morning_refresh: ['post-show morning clean face in tour hotel bathroom', 'the real person expression after the concert night', 'warm private tour bathroom morning expression'],
    getting_dressed: ['tour day rock aesthetic expression at hotel mirror', 'the between-shows rockstar face — composed and real', 'hotel morning tour expression'],
    breakfast: ['late post-show hotel breakfast expression — warm and fueled', 'the tour morning face after the concert night', 'warm rock morning hotel expression'],
    late_morning: ['soundcheck stage expression — powerful and focused on the empty stage', 'the pre-show building anticipation expression at the venue', 'the rockstar expression at soundcheck — owning the space'],
    lunch: ['backstage pre-show building expression — the energy rising', 'the pre-concert face in backstage setting', 'backstage pre-show composition building on the face'],
    afternoon: ['the transformation expression in the dressing room mirror', 'the stage persona being assembled expression', 'the pre-show building power expression at the backstage mirror'],
    reset: ['the charged pre-show expression — the most electric before going on', 'the final backstage expression before the stage', 'maximum charged pre-show expression at the threshold'],
    golden_hour: ['side of stage expression — the most electric threshold expression', 'the rockstar at the stage edge — the defining electric expression', 'the pre-show maximum expression before going on'],
    dinner: ['on-stage concert expression — the most powerful in the rockstar world', 'the stage persona at full performance power', 'the concert face — complete power and presence'],
    evening: ['post-show backstage expression — electric relief and warm', 'the after-show expression — the concert complete and real', 'warm post-concert expression in backstage warmth'],
    night: ['the 4am hotel private expression — the real person after everything', 'the rockstar private at night — warm and true', 'the most human rock expression at 4am in the hotel'],
  },

  handDetailPools: {
    wake: ['hand on tour hotel pillow in morning after the show', 'fingers near hotel morning detail in post-concert suite', 'the tour mythology morning hand detail'],
    morning_refresh: ['hand on hotel bathroom counter in tour morning', 'fingers in hair after post-show shower', 'tour hotel bathroom morning hand detail'],
    getting_dressed: ['hand on leather jacket or ring detail at hotel mirror', 'fingers fastening chain or rock accessory', 'the rock aesthetic hand in hotel morning'],
    breakfast: ['hand around hotel coffee cup in tour morning', 'fingers on hotel breakfast detail post-concert', 'tour morning hand at hotel breakfast'],
    late_morning: ['hand on microphone stand at empty stage soundcheck', 'fingers at backstage corridor wall or venue detail', 'the soundcheck hand on the stage equipment'],
    lunch: ['hand near backstage catering in pre-show energy', 'fingers on backstage catering detail pre-concert', 'the pre-show backstage hand at catering'],
    afternoon: ['hands applying stage makeup in lit dressing room mirror', 'fingers adjusting stage look in the dressing room', 'the transformation hands in dressing room'],
    reset: ['hand at backstage mirror in final pre-show preparation', 'fingers on stage look detail at the charged backstage threshold', 'the pre-show charged hand at maximum preparation'],
    golden_hour: ['hand at the stage-side threshold — the crowd beyond the fingertips', 'fingers on the stage-side wall as the crowd roar begins', 'the most electric hand detail — at the stage threshold'],
    dinner: ['microphone in hand on the concert stage', 'hands in performance gesture on stage in spotlight', 'the stage hands at full performance power'],
    evening: ['hand near post-show drink in backstage warmth', 'fingers in post-show celebration at the after-party', 'the post-concert hand in warm backstage relief'],
    night: ['hand on hotel pillow at 4am after the concert', 'fingers near hotel detail at 4am in warm quiet suite', 'the 4am private hotel hand after the stage'],
  },

  movementEnergyPools: {
    wake: ['slow', 'warm', 'post-show'],
    morning_refresh: ['private', 'warm', 'real'],
    getting_dressed: ['rock', 'composed', 'between-shows'],
    breakfast: ['warm', 'fueled', 'tour-morning'],
    late_morning: ['building', 'powerful', 'pre-show'],
    lunch: ['charged', 'backstage', 'building'],
    afternoon: ['transforming', 'charged', 'pre-show'],
    reset: ['electric', 'final', 'threshold'],
    golden_hour: ['maximum', 'electric', 'stage-edge'],
    dinner: ['full-power', 'stage', 'electric'],
    evening: ['releasing', 'post-show', 'warm'],
    night: ['private', 'real', '4am'],
  },

  transitionPools: {
    human: {
      wake: ['the tour hotel morning after the show', 'the rockstar waking in the mythology of a tour suite'],
      morning_refresh: ['hotel bathroom morning after the concert', 'the private ritual after being seen by thousands'],
      getting_dressed: ['tour hotel dressing between shows', 'the rock aesthetic assembled in the hotel morning'],
      breakfast: ['late hotel breakfast after the show night', 'tour morning fuel in warm hotel suite'],
      late_morning: ['the venue and soundcheck — the pre-show beginning', 'the empty stage at soundcheck — the most powerful pre-show moment'],
      lunch: ['backstage catering before the concert', 'the pre-show fuel in backstage setting'],
      afternoon: ['the dressing room transformation beginning', 'becoming the stage persona in the backstage mirror'],
      reset: ['the final charged hour before the stage', 'the pre-show complete at the backstage threshold'],
      golden_hour: ['side of stage — the most electric threshold', 'the crowd beyond, the stage ahead — the defining moment'],
      dinner: ['on stage at full concert power', 'the most powerful moment in the rockstar world'],
      evening: ['post-show backstage — the adrenaline and the warmth', 'the after-show world in warm backstage energy'],
      night: ['hotel suite at 4am after the concert', 'the rockstar private after everything — real and warm'],
    },
  },

  narrativeIntentPools: {
    wake: ['the private mythology of the day after the stage — warm and real in the tour hotel', 'the rockstar before the world sees them — alone in the hotel morning after the show'],
    morning_refresh: ['the private self-care after maximum public visibility — the real person after the stage', 'the tour morning ritual as the hidden foundation of the rockstar life'],
    getting_dressed: ['the rock aesthetic between shows — the real daily life of touring', 'the tour hotel dressing as the authentic chapter between the public chapters'],
    breakfast: ['the post-show morning fuel — the real private human after the most powerful public night', 'the tour morning as the authentic private world between concerts'],
    late_morning: ['the empty stage at soundcheck — the most powerful room on earth when it\'s empty', 'the pre-show venue as the first act of the concert day'],
    lunch: ['the backstage pre-show world — the hidden life that enables the public stage', 'pre-show fuel and the building concert energy'],
    afternoon: ['the transformation from person to stage persona — the core ritual of the rockstar world', 'the dressing room as the sacred backstage threshold before the stage'],
    reset: ['the charged final hour before the most powerful room — the maximum pre-show', 'the backstage threshold as the most electric anticipation moment in the rockstar life'],
    golden_hour: ['side of stage — the single most electric moment in the rockstar world', 'the threshold between person and performer — the crowd beyond, the show beginning'],
    dinner: ['on stage — the complete expression of the rockstar life', 'the concert as the most powerful human experience of presence and performance'],
    evening: ['post-show — the warm real release after the most powerful public moment', 'backstage after the concert — the authentic human after the performance persona'],
    night: ['the 4am hotel room — the most mythological private rockstar moment', 'the real human alone in the hotel at 4am after being on stage for 80,000'],
  },

  fallbackRules: {
    pacingProfile: { wake: 'slow', morning_refresh: 'slow', getting_dressed: 'slow', breakfast: 'slow', late_morning: 'medium', lunch: 'slow', afternoon: 'slow', reset: 'slow', golden_hour: 'slow', dinner: 'slow', evening: 'medium', night: 'slow' },
    repetitionBreakers: { avoidBackToBackSameLocation: true, avoidBackToBackSameLightingStyle: true, encourageWardrobeEvolution: true },
    worldDefaults: { allowSceneGroupFallbackToPhasePools: true, allowSubLocationFallbackToWorldPools: true, preferSceneGroupsWhenPresent: true },
  },

  exclusions: {
    premium: ['cheap generic rock clichés', 'non-luxury tour setting', 'budget hotel aesthetic', 'generic music industry energy'],
    hard: ['daylight suburban settings', 'office or corporate environments', 'clean wellness aesthetic', 'non-music world settings'],
  },

  routeRules: {
    worldIdentity: ['the rockstar world must feel electric, real, mythological, and cinematic — the stage and the hotel room with equal power', 'leather and stage light and tour hotel mythology are the core visual language'],
    humanFlow: ['the day moves from tour hotel mythology morning through the pre-show build to the stage peak and post-show warmth and 4am private hotel truth', 'the concert is the narrative center of every day'],
    styling: ['rock aesthetic throughout — leather, chain, vintage, and stage persona evolving from tour casual to full stage look and back to private hotel night'],
    atmosphere: ['tour hotel warmth, backstage electric anticipation, stage spectacular, post-show warm release, and 4am private mythology are the defining atmospheres'],
  },
}
