export const STORY_WORLD_VICTORIAS_ANGEL = {
  id: 'victorias-angel',
  name: "Victoria's Angel",
  description:
    'A cinematic world of high-fashion lingerie editorial — the dressing room before the show, backstage wings and diamonds, the runway walk itself, and intimate luxury aftermath. The body as the ultimate luxury product.',

  geography: { country: 'fashion world / private interior', region: 'backstage dressing room, runway, penthouse suite, editorial studio' },

  identity: {
    archetype: 'luxury lingerie angel — runway editorial creator',
    vibe: ['wings and diamonds and silk', 'the backstage before the most famous lingerie show', 'the runway as the most powerful stage', 'intimate luxury editorial', 'the body as the ultimate fashion product'],
    tone: ['theatrical', 'glamorous', 'intimate', 'editorial', 'powerful', 'beautiful', 'deliberate'],
    persona: ['the most beautiful woman on the most famous runway', 'completely at ease in wings and diamonds and nothing else', 'the editorial lingerie moment as art and power', 'the Victoria\'s Angel as the cultural ideal of feminine luxury beauty'],
  },

  phaseOrder: ['wake', 'morning_refresh', 'getting_dressed', 'breakfast', 'late_morning', 'lunch', 'afternoon', 'reset', 'golden_hour', 'dinner', 'evening', 'night'],

  phases: {
    wake:            { label: 'Wake',            timeWindows: ['model morning in hotel or suite before the show', 'the angel morning — private luxury before the runway'],    pacing: 'slow',   subLocations: ['angel-suite', 'model-hotel'] },
    morning_refresh: { label: 'Morning Refresh', timeWindows: ['pre-show beauty morning ritual', 'hotel bathroom morning before the show'],                                    pacing: 'slow',   subLocations: ['hotel-bathroom', 'angel-vanity'] },
    getting_dressed: { label: 'Getting Dressed', timeWindows: ['the fitting ritual', 'trying on the angel look for the shoot or show'],                                       pacing: 'slow',   subLocations: ['dressing-room', 'angel-vanity'] },
    breakfast:       { label: 'Breakfast',       timeWindows: ['model morning breakfast in hotel suite', 'angel morning before the show'],                                     pacing: 'slow',   subLocations: ['angel-suite', 'model-hotel'] },
    late_morning:    { label: 'Late Morning',    timeWindows: ['backstage preparation morning', 'editorial beauty preparation in backstage or studio'],                         pacing: 'medium', subLocations: ['backstage', 'editorial-studio'] },
    lunch:           { label: 'Lunch',           timeWindows: ['backstage or hotel pre-show midday', 'model lunch before the editorial or show'],                              pacing: 'slow',   subLocations: ['backstage', 'angel-suite'] },
    afternoon:       { label: 'Afternoon',       timeWindows: ['full hair and makeup and fitting afternoon', 'the transformation into the angel look'],                         pacing: 'slow',   subLocations: ['backstage', 'dressing-room'] },
    reset:           { label: 'Reset',           timeWindows: ['the final preparation hour before the show or editorial', 'wings fitting and diamond styling'],                pacing: 'slow',   subLocations: ['dressing-room', 'angel-vanity'] },
    golden_hour:     { label: 'Golden Hour',     timeWindows: ['the pre-show golden moment', 'the angel before the runway or editorial camera in warm light'],                pacing: 'slow',   subLocations: ['pre-show-corridor', 'dressing-room'] },
    dinner:          { label: 'Dinner',          timeWindows: ['the runway or editorial show moment', 'the angel on the runway or in the editorial frame'],                    pacing: 'slow',   subLocations: ['runway', 'editorial-studio'] },
    evening:         { label: 'Evening',         timeWindows: ['post-show luxury — the after party or suite', 'angel after the runway in private luxury'],                     pacing: 'slow',   subLocations: ['after-party', 'angel-suite'] },
    night:           { label: 'Night',           timeWindows: ['private suite after the show', 'the angel at private rest after the runway'],                                  pacing: 'slow',   subLocations: ['angel-suite', 'model-hotel'] },
  },

  locations: [
    'hotel suite before the show', 'backstage dressing room with wings and diamonds', 'editorial studio with angel look',
    'the runway in wings and luxury lingerie', 'pre-show corridor in complete angel styling', 'after-party luxury suite',
    'angel vanity with beauty and diamond styling', 'model hotel room in morning',
  ],

  subLocations: {
    'angel-suite': {
      id: 'angel-suite', name: 'Angel Suite', mapAnchor: 'luxury hotel suite before the show',
      category: 'private-angel',
      bestPhases: ['wake', 'breakfast', 'lunch', 'evening', 'night'],
      overlays: ['luxury hotel suite in show-city morning', 'white linen and private luxury before the runway', 'the angel at private rest or preparation'],
      locations: ['luxury hotel suite in show morning', 'angel private suite before the runway', 'private hotel luxury in show-world setting'],
    },
    'model-hotel': {
      id: 'model-hotel', name: 'Model Hotel Room', mapAnchor: 'model hotel room',
      category: 'private-model',
      bestPhases: ['wake', 'night'],
      overlays: ['model morning hotel room before the show', 'private hotel interior before the runway', 'the angel at rest in hotel luxury'],
      locations: ['model hotel room before the show in morning', 'private hotel interior in show setting', 'model morning private hotel luxury'],
    },
    'hotel-bathroom': {
      id: 'hotel-bathroom', name: 'Hotel Bathroom', mapAnchor: 'hotel bathroom morning',
      category: 'self-care-angel',
      bestPhases: ['morning_refresh'],
      overlays: ['hotel bathroom morning ritual before the show', 'luxury bathroom in pre-show morning', 'model morning self-care ritual'],
      locations: ['hotel bathroom morning ritual pre-show', 'luxury model morning bathroom', 'pre-runway morning self-care setting'],
    },
    'angel-vanity': {
      id: 'angel-vanity', name: 'Angel Vanity', mapAnchor: 'angel preparation vanity',
      category: 'preparation-angel',
      bestPhases: ['morning_refresh', 'getting_dressed', 'reset'],
      overlays: ['vanity with diamond and beauty products', 'angel transformation preparation', 'the vanity where the angel look is built'],
      locations: ['angel preparation vanity with diamonds', 'the transformation vanity in show setting', 'luxury preparation with angel beauty and jewelry'],
    },
    'dressing-room': {
      id: 'dressing-room', name: 'Dressing Room', mapAnchor: 'backstage angel dressing room',
      category: 'transformation',
      bestPhases: ['getting_dressed', 'afternoon', 'reset'],
      overlays: ['backstage dressing room with wings and lingerie', 'the transformation space before the angel walk', 'diamond fantasy dressing room energy'],
      locations: ['backstage dressing room with wings hanging', 'angel lingerie and diamond fitting room', 'the transformation space backstage'],
    },
    'backstage': {
      id: 'backstage', name: 'Backstage', mapAnchor: 'backstage before the show',
      category: 'pre-show',
      bestPhases: ['late_morning', 'lunch', 'afternoon'],
      overlays: ['backstage before the most famous lingerie show', 'angels getting ready around her', 'backstage beauty and editorial energy'],
      locations: ['backstage with other angels in preparation', 'backstage mirror and beauty area', 'pre-show backstage energy in full preparation'],
    },
    'editorial-studio': {
      id: 'editorial-studio', name: 'Editorial Studio', mapAnchor: 'luxury editorial lingerie studio',
      category: 'editorial-shoot',
      bestPhases: ['late_morning', 'dinner'],
      overlays: ['luxury editorial studio with angel look', 'fashion photography studio with wings and lingerie', 'editorial angel in professional studio light'],
      locations: ['luxury editorial studio with angel styling', 'fashion studio in angel lingerie editorial', 'professional editorial studio with wings and diamond'],
    },
    'pre-show-corridor': {
      id: 'pre-show-corridor', name: 'Pre-Show Corridor', mapAnchor: 'backstage corridor before runway',
      category: 'pre-runway',
      bestPhases: ['golden_hour'],
      overlays: ['backstage corridor before the runway walk', 'the angel in full look before the cameras', 'pre-show corridor energy with wings and diamonds'],
      locations: ['backstage corridor in full angel look before runway', 'the moment before the runway walk', 'pre-show corridor in wings and complete angel styling'],
    },
    'runway': {
      id: 'runway', name: 'Runway', mapAnchor: 'the runway walk',
      category: 'runway-moment',
      bestPhases: ['dinner'],
      overlays: ['the runway in wings and luxury lingerie', 'the most famous walk in fashion', 'the angel on the runway at full presence'],
      locations: ['the runway in wings and diamond lingerie', 'the most powerful walk — angel on the runway', 'the complete angel moment on the fashion runway'],
    },
    'after-party': {
      id: 'after-party', name: 'After Party', mapAnchor: 'show after-party',
      category: 'post-show',
      bestPhases: ['evening'],
      overlays: ['show after-party in luxury venue', 'the angel post-show in glamour', 'celebration after the runway walk'],
      locations: ['luxury after-party post-show venue', 'angel at after-party in glamorous setting', 'post-runway celebrity after-party'],
    },
  },

  sceneVariants: {
    wake: ['the angel morning — hotel luxury before the most famous lingerie runway', 'waking in a hotel suite in show city in warm private morning'],
    morning_refresh: ['hotel bathroom morning ritual before the show', 'the angel self-care in luxury hotel bathroom before the runway'],
    getting_dressed: ['the fitting ritual — wings and diamonds in the dressing room', 'trying on the angel look in the backstage dressing room'],
    breakfast: ['model breakfast in hotel suite before the show day begins', 'the angel morning meal before the backstage preparation'],
    late_morning: ['backstage preparation beginning — hair, makeup, and wings', 'editorial studio angel look being assembled in professional light'],
    lunch: ['backstage model lunch in preparation energy', 'the angel midday before the full transformation into the runway look'],
    afternoon: ['the full angel transformation — wings fitted, diamonds on, lingerie complete', 'hair and makeup and wings in the backstage dressing room'],
    reset: ['the final moments before the runway — wings perfect, look complete', 'the angel in the dressing room before the walk begins'],
    golden_hour: ['the pre-show corridor — the angel in full look before the cameras', 'the most powerful pre-runway moment — wings and diamonds complete'],
    dinner: ['the runway walk — the angel in wings and luxury lingerie on the world\'s most famous stage', 'the editorial studio moment — the angel in the most beautiful editorial light'],
    evening: ['post-show luxury at the after-party — the angel after the runway', 'the celebration after the most famous lingerie walk'],
    night: ['private suite after the show — the angel at rest', 'the runway world complete in private hotel luxury at night'],
  },

  actionPools: {
    wake: ['waking in hotel suite before the show in morning luxury', 'the angel morning — private and composed before the most famous walk', 'hotel morning ease before the backstage world begins'],
    morning_refresh: ['hotel bathroom morning ritual in luxury pre-show setting', 'the angel self-care in warm bathroom before backstage', 'beauty preparation beginning in private hotel morning'],
    getting_dressed: ['fitting the wings in the backstage dressing room', 'trying on the complete angel look with diamonds and lingerie', 'the transformation ritual — wings, diamonds, and the complete angel style'],
    breakfast: ['hotel suite breakfast before the show day begins', 'model morning meal in private hotel luxury', 'the angel eating before the backstage preparation'],
    late_morning: ['backstage preparation — hair and makeup beginning', 'editorial studio preparation with the full angel look', 'the angel transformation beginning in professional backstage setting'],
    lunch: ['backstage model lunch in full preparation energy', 'the angel midday meal before the complete transformation', 'eating well backstage before the runway energy builds'],
    afternoon: ['the full angel transformation — wings, diamonds, and lingerie', 'complete hair and makeup in backstage dressing room', 'the dressing room ritual — every detail of the angel look being perfected'],
    reset: ['the final dressing room moment — look complete, ready for the walk', 'wings being adjusted one final time before the corridor', 'the angel at the mirror in complete look before the runway'],
    golden_hour: ['the pre-show corridor in complete angel look — the most powerful pre-runway moment', 'standing in wings and diamonds before the cameras in the corridor', 'the angel the moment before the walk begins'],
    dinner: ['the runway walk in wings and luxury lingerie on the world\'s most famous stage', 'the editorial studio moment — the angel in perfect light with wings', 'the most powerful fashion moment — angel on the runway or in editorial frame'],
    evening: ['the after-party celebration post-show in luxury setting', 'the angel post-runway in glamorous evening', 'celebrating after the most famous walk in luxury after-party'],
    night: ['private suite after the show — the wings off and at rest', 'the angel at private luxury rest after the runway', 'hotel suite night after the most powerful fashion day'],
  },

  environmentPools: {
    wake: ['luxury hotel suite in show city in morning light', 'model hotel room before the backstage preparation', 'private hotel interior in warm morning before the angel world begins'],
    morning_refresh: ['luxury hotel bathroom in pre-show morning', 'warm hotel bathroom ritual before the backstage world', 'private hotel bathroom before the angel transformation'],
    getting_dressed: ['backstage dressing room with wings and diamonds being assembled', 'angel lingerie and diamond fitting room with runway energy', 'the transformation space where the complete angel look is created'],
    breakfast: ['hotel suite breakfast setting in show morning', 'model hotel room meal before the backstage preparation', 'private hotel luxury before the angel runway day'],
    late_morning: ['backstage preparation area with other angels getting ready', 'editorial studio with professional lighting and angel look', 'pre-show backstage environment in full preparation energy'],
    lunch: ['backstage area in midday preparation energy', 'angel suite or hotel room lunch before the full transformation', 'backstage or model suite midday in show preparation'],
    afternoon: ['backstage dressing room in full transformation — wings, diamonds, complete', 'the most theatrical transformation space before the show', 'complete angel dressing room in full preparation'],
    reset: ['dressing room in complete angel look one final time before the corridor', 'wings and diamonds and the mirror before the walk', 'the final pre-runway dressing room moment'],
    golden_hour: ['pre-show corridor in complete wings and diamond angel look', 'the backstage corridor before the runway cameras', 'the angel at the threshold between backstage and runway in full look'],
    dinner: ['the runway in wings and luxury lingerie under the most dramatic show lighting', 'editorial studio in wings and diamonds in professional editorial light', 'the most powerful fashion environment — angel on the runway or in the studio'],
    evening: ['luxury after-party venue post-show in glamorous setting', 'the celebration space after the most famous lingerie walk', 'post-runway luxury social setting in show city evening'],
    night: ['private hotel suite after the show — wings removed, at rest', 'luxury hotel night after the runway day', 'private hotel interior in warm night after the angel world is complete'],
  },

  moodPools: {
    wake: ['private luxury model morning before the show', 'the angel at private rest before the most powerful day', 'hotel suite morning ease before everything begins'],
    morning_refresh: ['preparation beginning — the angel building toward the runway', 'pre-show morning self-care ritual energy', 'the private beauty ritual before the public transformation'],
    getting_dressed: ['the theatrical transformation — wings and diamonds being assembled', 'the most powerful dressing ritual in fashion', 'the angel becoming in the backstage dressing room'],
    breakfast: ['model morning fuel before the show energy builds', 'private luxury model morning ease before backstage', 'the angel before the show — private and composed'],
    late_morning: ['backstage building energy — preparation and beauty', 'the angel transformation building in professional backstage', 'editorial studio energy with wings and editorial preparation'],
    lunch: ['midday calm before the complete angel transformation', 'backstage ease before the full preparation peak', 'the angel gathering energy before the runway moment'],
    afternoon: ['the complete transformation — the most theatrical beautiful moment', 'wings, diamonds, and the complete angel look assembled', 'the dressing room at its most powerful — the angel complete'],
    reset: ['the final pre-runway moment — composed, complete, ready', 'the angel before the walk in wings and full look', 'the most powerful pre-show dressing room energy'],
    golden_hour: ['the pre-show corridor — the angel at maximum power before the cameras', 'wings and diamonds and the walk ahead — the most theatrical moment', 'the corridor before the runway — the most electric fashion energy'],
    dinner: ['the runway — the most powerful fashion energy on earth', 'the angel on the runway or in editorial — the complete theatrical peak', 'wings, diamonds, and the walk — the defining fashion editorial moment'],
    evening: ['post-show luxury celebration — the angel after the runway', 'glamorous after-party energy after the most famous walk', 'the fashion night continuing in luxury after the runway'],
    night: ['private hotel suite after the show — the angel at private rest', 'the luxury private night after the most powerful fashion day', 'the angel complete and private after the runway world'],
  },

  cameraPools: {
    wake: ['85mm low angle in hotel suite, warm morning window dissolved behind', '135mm close-up at face height, warm hotel morning light defining edge'],
    morning_refresh: ['85mm hotel bathroom mirror close, reflection at same focal plane', '50mm hotel bathroom mid shot, warm morning light compressing behind'],
    getting_dressed: ['50mm dressing room framing, wings and diamonds visible behind in warm light', '85mm transformation mid-length angle, dressing room depth behind'],
    breakfast: ['24mm wide hotel suite breakfast, show-city morning window in background', '85mm hotel suite breakfast framing, morning dissolved behind'],
    late_morning: ['85mm backstage medium, preparation energy behind subject', '50mm editorial studio with professional light and angel editorial detail'],
    lunch: ['85mm backstage or suite lunch, preparation energy soft behind subject', '50mm angel suite lunch framing, hotel or backstage depth behind'],
    afternoon: ['85mm dressing room transformation, wings visible in full background', '50mm complete angel look framing, dressing room detail behind subject'],
    reset: ['135mm dressing room close in complete angel look, wings in warm background', '85mm final pre-runway look — wings and diamonds at full editorial beauty'],
    golden_hour: ['135mm corridor pre-show close, warm backlight defining edge in wings and diamond', '85mm dramatic corridor angel medium, show light behind in warm glow'],
    dinner: ['85mm runway dramatic medium, runway lights creating epic glow behind', '50mm editorial studio angel, professional editorial light filling background'],
    evening: ['85mm after-party medium, warm luxury venue ambient behind subject', '50mm after-party interior, warm golden post-show ambient depth behind'],
    night: ['135mm hotel suite night close, warm private lamp as sole source', '85mm soft side angle, warm hotel room dissolved behind subject'],
  },

  lightingPools: {
    wake: ['warm 4800K hotel morning through curtains, soft shadows across white linen', 'pale warm hotel morning entering through hotel glass — soft and private'],
    morning_refresh: ['clean 5400K hotel bathroom mirror light, precise and warm', 'hotel bathroom warm morning light — flattering and clean'],
    getting_dressed: ['warm 4000K dressing room light — flattering and theatrical', 'backstage warm dressing room lighting on wings and diamond detail'],
    breakfast: ['warm 5000K hotel suite morning, clean city light beyond window', 'warm hotel morning breakfast light — private and clean'],
    late_morning: ['5000K professional backstage or studio preparation light — controlled and precise', 'editorial studio professional fill light in preparation'],
    lunch: ['warm 4200K backstage or suite midday, soft ambient fill', 'midday preparation ambient in backstage or hotel suite'],
    afternoon: ['warm 3800K dressing room transformation — theatrical and flattering on wings and diamonds', 'backstage warm amber transformation light in dressing room'],
    reset: ['warm 3500K dressing room before the walk — most flattering final preparation light', 'warm amber dressing room in complete angel look before the corridor'],
    golden_hour: ['dramatic 2800K corridor warm light before the runway — the most powerful pre-show light', 'amber backstage corridor at pre-show — warm and theatrical'],
    dinner: ['dramatic show lighting — 4000K front fill with 2800K warm side, full runway theatrical', 'editorial studio professional key light with warm dramatic fill on angel look'],
    evening: ['warm 2800K after-party luxury venue ambient — celebration and gold', 'post-show after-party warm low ambient with celebration energy'],
    night: ['single warm 2200K hotel lamp, soft private suite after the show', 'low warm 2400K hotel room night — private and quiet after the runway'],
  },

  stylingPools: {
    wardrobe: {
      wake: ['hotel silk or minimal in suite morning', 'model morning hotel luxury before the show', 'private silk or nothing in warm hotel morning'],
      morning_refresh: ['hotel robe or towel in morning bathroom', 'pre-show white towel and minimal morning styling', 'model morning private before backstage'],
      getting_dressed: ['first fitting — the angel lingerie and bra being placed on', 'the initial trying-on of the complete angel look in dressing room', 'wings being adjusted in dressing room fitting'],
      breakfast: ['hotel robe or minimal model morning at suite table', 'model morning suit or casual pre-show at hotel', 'the angel private morning look before backstage'],
      late_morning: ['editorial or show prep look — beginning the transformation in backstage', 'backstage robe or partial styling during preparation', 'beginning to assemble the complete angel look in preparation'],
      lunch: ['backstage model midday — partial preparation or hotel casual', 'the angel midday between preparation stages', 'backstage or hotel midday comfort before the transformation peak'],
      afternoon: ['complete angel look assembling — wings, diamonds, luxury lingerie', 'the angel transformation at peak — wings on, complete', 'full editorial angel look in backstage dressing room'],
      reset: ['complete angel look — wings, diamond bra or lingerie, complete', 'the final angel look before the corridor and runway', 'the most complete and theatrical angel styling moment'],
      golden_hour: ['complete angel look in the corridor — wings, diamonds, full runway ready', 'the angel at maximum editorial beauty before the walk', 'wings, diamond lingerie, and the complete angel styling in the corridor'],
      dinner: ['the runway angel look — wings, diamond bra, fantasy lingerie, complete show styling', 'editorial studio complete angel look — the most theatrical and beautiful fashion moment', 'the angel on the runway or in studio — the most complete editorial moment'],
      evening: ['post-show after-party look — transitioned from runway to evening glamour', 'the angel after the show — slightly softened but still glamorous', 'after-party fashion look after the runway'],
      night: ['private hotel suite night — the wings are off, private silk or nothing', 'the angel private after-show look in hotel suite', 'private night after the runway — the most private state'],
    },
    details: {
      wake: ['hotel pillow hair in morning', 'bare natural model skin in morning', 'private morning before the glamour begins'],
      morning_refresh: ['clean face being prepared for the show transformation', 'model natural morning before backstage begins', 'pre-show clean skin and natural hair'],
      getting_dressed: ['diamond detail being placed', 'wings being adjusted — the most theatrical dressing detail', 'the complete angel look detail being assembled piece by piece'],
      breakfast: ['natural model morning detail at hotel table', 'casual pre-show hotel morning accessory detail', 'model morning before backstage preparation'],
      late_morning: ['backstage beauty transformation beginning — hair, lashes, body detail', 'editorial preparation building beauty detail', 'early beauty preparation in backstage environment'],
      lunch: ['backstage partial preparation detail', 'model midday between preparation stages', 'preparation building in backstage or suite midday'],
      afternoon: ['wings fitted — the most theatrical preparation detail', 'diamond lingerie and bra on skin in dressing room', 'complete angel transformation detail — wings, diamonds, complete'],
      reset: ['final wings adjustment — the most important final detail', 'complete angel look check at the dressing room mirror', 'the last detail check before the corridor'],
      golden_hour: ['wings spread in the corridor — the most powerful fashion editorial detail', 'diamonds and wings in warm pre-show light', 'complete angel look at maximum theatrical detail'],
      dinner: ['the runway angel look at full theatrical detail — wings, diamonds, fantasy lingerie', 'editorial studio angel detail in professional light', 'the most complete theatrical fashion detail — on the runway or in editorial'],
      evening: ['after-party glamour detail transition from runway', 'post-show celebration styling detail', 'the angel after the runway — glamorous and elevated'],
      night: ['wings removed — the most private detail', 'hotel private night silk or nothing detail', 'the angel at rest — no wings, private and warm'],
    },
    changeMoments: {
      wake: ['hotel morning private state — before the angel begins', 'private model morning before the show'],
      morning_refresh: ['between hotel and backstage — in the morning transition', 'pre-backstage model morning ritual'],
      getting_dressed: ['the first fitting — becoming the angel', 'the dressing room transformation beginning'],
      breakfast: ['model hotel morning casual before the show world', 'private morning ease before the runway day'],
      late_morning: ['backstage partial preparation — between model and angel', 'the transformation building in backstage'],
      lunch: ['midday between preparation stages', 'the angel midday in partial backstage look'],
      afternoon: ['complete angel transformation — the moment of becoming fully', 'wings on and complete — the angel is ready'],
      reset: ['the final complete look check — angel at maximum', 'the complete angel before the corridor'],
      golden_hour: ['the complete angel in the corridor — the defining transition moment', 'wings and diamonds in the pre-show corridor'],
      dinner: ['the runway angel — the most complete editorial fashion moment', 'fully the angel on the runway or in studio'],
      evening: ['transitioning from runway angel to after-party glamour', 'the angel after the show in post-runway setting'],
      night: ['the angel private after the show — wings off, private again', 'private hotel night — the model beneath the angel'],
    },
  },

  sensoryPools: {
    wake: ['warm hotel silk in private morning before the show', 'the quiet luxury of a model hotel before the show world begins', 'private warm hotel before the most theatrical day'],
    morning_refresh: ['warm hotel bathroom morning ritual pre-show', 'clean skin and fresh energy before the backstage world', 'the private morning self-care before the theatrical transformation'],
    getting_dressed: ['wings being placed on — the physical sensation of the most theatrical fashion accessory', 'diamond weight on skin in the dressing room', 'silk and lace and diamond in the dressing room transformation'],
    breakfast: ['hotel morning meal — calm fuel before the runway energy', 'private model hotel suite in the morning before everything', 'warm hotel breakfast before backstage begins'],
    late_morning: ['backstage energy building around her — beauty, preparation, angel energy', 'the editorial studio professional light on the angel look', 'backstage sound and movement as the preparation builds'],
    lunch: ['backstage midday calm before the peak preparation', 'the angel gathering before the transformation peak', 'model midday in backstage or suite before the wings'],
    afternoon: ['the weight and drama of wings being fitted', 'diamonds on skin in the warm dressing room', 'the complete theatrical transformation — the most sensory intense fashion moment'],
    reset: ['the complete angel look — wings spread, diamonds on, the final sensory check', 'the mirror check in complete angel look before the walk', 'the corridor anticipation before the most famous walk in fashion'],
    golden_hour: ['the corridor — the sound of the show about to begin beyond the doors', 'wings spread in the warm pre-show corridor light', 'the most theatrical pre-runway sensory moment in fashion'],
    dinner: ['the runway — stage light, sound, the walk, wings in motion', 'the editorial studio — professional light, direction, and the angel look at peak', 'the most theatrical and alive sensory moment of the fashion day'],
    evening: ['after-party celebration — champagne, music, and the warm glow post-runway', 'the angel post-show in luxury celebration setting', 'after-party luxury sensory after the runway'],
    night: ['private hotel suite after — wings off, warm silk, total private quiet', 'the model private after the angel world — warm and at rest', 'hotel night after the most theatrical day — warm and complete'],
  },

  socialEnergyPools: {
    wake: ['completely private hotel model morning', 'the angel before the show — private and composed'],
    morning_refresh: ['private morning self-care before the backstage', 'the model alone in bathroom before the transformation'],
    getting_dressed: ['backstage social energy — angels and beauty team together', 'the transformation in the social backstage environment'],
    breakfast: ['private hotel morning before the backstage world begins', 'the model private before the show energy'],
    late_morning: ['backstage social preparation energy — controlled and building', 'editorial studio professional energy with team'],
    lunch: ['midday ease in backstage or suite social energy', 'the model before the peak preparation in social ease'],
    afternoon: ['backstage transformation energy — focused professional creative social', 'the dressing room at full theatrical social energy'],
    reset: ['focused solo final preparation in the dressing room', 'the angel alone with the mirror before the corridor'],
    golden_hour: ['the corridor — the most theatrical charged social energy before the walk', 'the angel visible to all before the runway begins'],
    dinner: ['the runway — fully public, the most visible moment in fashion', 'editorial studio professional focused creative social energy'],
    evening: ['after-party luxury social celebration energy post-show', 'the angel socializing in luxury after the runway'],
    night: ['private hotel quiet after the show', 'the model alone again after the theatrical public day'],
  },

  atmospherePools: {
    wake: ['warm private hotel model morning before the show', 'the angel world beginning slowly in luxury morning', 'hotel suite quiet before the theatrical day'],
    morning_refresh: ['pre-show morning ritual atmosphere in warm hotel', 'private self-care atmosphere before backstage begins', 'model morning private before the transformation'],
    getting_dressed: ['backstage dressing room atmosphere — theatrical, warm, creative', 'the transformation space atmosphere — wings and diamonds and beauty', 'the most theatrical fashion atmosphere — angel dressing room'],
    breakfast: ['hotel suite model morning atmosphere before the show', 'private luxury hotel morning before backstage', 'warm hotel morning atmosphere before the angel world'],
    late_morning: ['backstage preparation atmosphere building toward the show', 'editorial studio professional creative atmosphere', 'backstage growing energy before the runway'],
    lunch: ['backstage midday ease before the theatrical peak', 'midday model atmosphere between preparation stages', 'calm before the storm of the complete angel preparation'],
    afternoon: ['backstage dressing room at full theatrical transformation atmosphere', 'the complete angel transformation atmosphere — the most theatrical fashion moment', 'wings, diamonds, and beauty — the peak dressing room atmosphere'],
    reset: ['final pre-runway dressing room atmosphere — complete and powerful', 'the angel at maximum theatrical beauty before the corridor', 'the most charged pre-show dressing room atmosphere'],
    golden_hour: ['pre-show corridor atmosphere — the most electric pre-runway fashion energy', 'wings spread in the corridor before the show — the most theatrical atmosphere', 'the show about to begin atmosphere — maximum theatrical tension and beauty'],
    dinner: ['the runway show atmosphere — the most theatrical fashion environment on earth', 'editorial studio professional creative atmosphere with angel complete', 'the defining fashion theatrical atmosphere — runway lights and angel wings'],
    evening: ['post-show luxury celebration atmosphere in after-party', 'the angel after the runway in luxury social celebration', 'after-party glamorous fashion atmosphere'],
    night: ['private hotel quiet after the theatrical day', 'warm hotel luxury private night after the show', 'the angel at private rest — the theatrical world complete'],
  },

  propPools: {
    wake: ['luxury hotel bedding and white linen in morning', 'hotel suite morning light detail', 'model private hotel morning props'],
    morning_refresh: ['hotel bathroom products and warm morning ritual', 'luxury pre-show hotel bathroom detail', 'model morning hotel bathroom props'],
    getting_dressed: ['wings being assembled in dressing room', 'diamond bra and lingerie in dressing room fitting', 'dressing room mirror and beauty team detail'],
    breakfast: ['hotel suite breakfast tray in model morning', 'coffee or juice in hotel suite before backstage', 'model hotel morning meal props'],
    late_morning: ['backstage beauty chairs and preparation tools', 'editorial studio lighting equipment and angel styling', 'backstage preparation detail props'],
    lunch: ['backstage or hotel suite meal props', 'model midday in preparation environment', 'angel preparation midday props'],
    afternoon: ['wings in full fitting in dressing room', 'diamond lingerie on skin in dressing room fitting', 'complete transformation dressing room props'],
    reset: ['wings fully fitted at dressing room mirror', 'the angel in complete look at the mirror', 'final pre-runway dressing room props'],
    golden_hour: ['wings spread in the pre-show corridor', 'diamonds in warm corridor pre-show light', 'the complete angel look in the corridor before the walk'],
    dinner: ['runway stage lighting and the angel walk', 'editorial studio professional equipment and angel complete look', 'the defining fashion prop — wings on the runway or in studio'],
    evening: ['after-party champagne and luxury venue detail', 'post-show celebration props in luxury setting', 'angel after-party glamour props'],
    night: ['hotel suite after the show — wings removed, private', 'luxury hotel night detail after the runway', 'the angel private hotel night props'],
  },

  bodyLanguagePools: {
    wake: ['slow warm hotel morning posture in luxury bed', 'model morning hotel ease before the theatrical day', 'private morning body language before the show'],
    morning_refresh: ['composed hotel bathroom morning ritual posture', 'pre-show morning self-care body language', 'the model private morning in hotel bathroom'],
    getting_dressed: ['the theatrical fitting posture — wings being placed and adjusted', 'deliberate angel transformation body language in dressing room', 'the most theatrical fashion body language — wings and diamond fitting'],
    breakfast: ['relaxed hotel suite morning body language before the show', 'model hotel breakfast posture — calm and composed', 'private hotel morning body ease before backstage'],
    late_morning: ['backstage preparation posture — beauty team at work around her', 'editorial studio preparation posture — composed and ready', 'building toward the complete angel transformation body language'],
    lunch: ['midday backstage ease in preparation body language', 'the model between transformation stages — at ease', 'angel midday calm before the theatrical peak'],
    afternoon: ['the transformation body language — wings on, standing, the angel fully', 'theatrical full angel complete posture in dressing room', 'wings spread in dressing room — the most theatrical posture'],
    reset: ['complete angel posture — full look, composed, the walk ahead', 'the angel before the runway — the most composed theatrical posture', 'final dressing room mirror assessment in complete angel look'],
    golden_hour: ['wings spread in the corridor — the most powerful angel posture', 'the complete angel in the corridor before the cameras', 'the runway walk posture beginning — wings, diamonds, ready'],
    dinner: ['the runway walk — the most iconic fashion posture on earth', 'editorial studio angel posture — theatrical and editorial in professional light', 'the angel on the runway — wings, walk, complete body language'],
    evening: ['post-show after-party relaxed glamour posture', 'the angel after the runway — slightly softened, still glamorous', 'after-party fashion body language in luxury celebration'],
    night: ['private hotel suite after the show — the most natural quiet body language', 'the model at private rest after the theatrical day — composed and warm', 'hotel private night body language — quiet and complete'],
  },

  facialExpressionPools: {
    wake: ['warm private hotel morning face before the show', 'model morning natural expression in hotel luxury', 'private before-show face — calm and at ease'],
    morning_refresh: ['focused pre-show morning expression at the mirror', 'model morning self-care expression before backstage', 'the angel building herself in private morning expression'],
    getting_dressed: ['the transformation expression — becoming the angel in the dressing room', 'focused theatrical dressing room expression', 'the angel being assembled — deliberate and theatrical expression'],
    breakfast: ['relaxed hotel morning model expression before the show', 'calm composed hotel breakfast expression', 'the angel before the show — private and warm expression'],
    late_morning: ['backstage preparation building expression', 'editorial beauty transformation expression in professional setting', 'the angel becoming in backstage expression'],
    lunch: ['midday calm model expression in backstage ease', 'the angel between transformation stages expression', 'composed midday model expression before the theatrical peak'],
    afternoon: ['the complete transformation expression — the angel full', 'wings on and the theatrical expression of complete angel power', 'the most theatrical fashion expression — the complete angel look'],
    reset: ['the final dressing room expression — composed, complete, the walk ahead', 'the angel at maximum beauty before the corridor — the most powerful expression', 'pre-runway complete angel expression — confident and theatrical'],
    golden_hour: ['the corridor angel expression — wings spread, the walk imminent', 'the most electric pre-runway fashion expression', 'complete angel theatrical confidence before the cameras'],
    dinner: ['the runway expression — the angel walk at full theatrical power', 'editorial studio angel expression in professional dramatic light', 'the defining fashion expression — the angel on the runway or in editorial'],
    evening: ['post-show glamorous after-party expression', 'the angel after the runway — relieved and beautiful and alive', 'after-party glamour expression in luxury celebration'],
    night: ['private hotel quiet expression after the show', 'the model at private rest after the theatrical day', 'warm private hotel expression after the complete angel world'],
  },

  handDetailPools: {
    wake: ['hand on hotel white linen in morning', 'fingers near hotel morning detail', 'warm private hotel morning hand placement'],
    morning_refresh: ['hand at hotel bathroom counter in morning', 'fingers in hotel morning beauty routine', 'model morning hotel bathroom hand detail'],
    getting_dressed: ['hand adjusting wing strap in dressing room fitting', 'fingers touching diamond detail in transformation', 'the wing adjustment hand — the most theatrical fashion hand detail'],
    breakfast: ['hand around hotel coffee cup in morning', 'fingers on hotel suite table at model breakfast', 'hotel morning hand at the breakfast table'],
    late_morning: ['hand in backstage beauty preparation', 'fingers in editorial studio preparation detail', 'hands in backstage beauty transformation'],
    lunch: ['hand near model meal in backstage or suite', 'fingers in midday preparation detail', 'backstage midday hand placement'],
    afternoon: ['hand under wing in dressing room — the transformation hand detail', 'fingers on diamond detail in complete fitting', 'the most theatrical hand detail — touching wings or diamonds in transformation'],
    reset: ['hand on wing in final dressing room check', 'fingers adjusting complete angel look at the mirror', 'the final dressing room hand detail before the corridor'],
    golden_hour: ['wings spread — the hand beneath the wing in the corridor', 'fingers touching diamond detail in warm corridor pre-show light', 'the complete angel corridor hand detail'],
    dinner: ['the runway walk hands — composed and editorial in motion', 'editorial studio hand in complete angel look in dramatic light', 'the defining fashion hand — the angel on the runway'],
    evening: ['after-party hand with champagne in luxury celebration', 'fingers in post-show glamour detail', 'after-party luxury hand placement'],
    night: ['hand on hotel pillow after the show', 'fingers near hotel private night detail', 'the angel at rest — the most private hotel hand placement'],
  },

  movementEnergyPools: {
    wake: ['slow', 'private', 'model-morning'],
    morning_refresh: ['composed', 'deliberate', 'pre-show'],
    getting_dressed: ['theatrical', 'deliberate', 'transformation'],
    breakfast: ['relaxed', 'warm', 'private'],
    late_morning: ['building', 'professional', 'preparation'],
    lunch: ['calm', 'midday', 'gathering'],
    afternoon: ['theatrical', 'transforming', 'peak'],
    reset: ['composed', 'complete', 'ready'],
    golden_hour: ['electric', 'theatrical', 'imminent'],
    dinner: ['iconic', 'editorial', 'walking'],
    evening: ['glamorous', 'celebratory', 'post-show'],
    night: ['quiet', 'private', 'model-night'],
  },

  transitionPools: {
    human: {
      wake: ['the model morning in hotel before the show world', 'private luxury morning before the angel transformation'],
      morning_refresh: ['hotel bathroom morning ritual before backstage', 'the angel self-care beginning privately'],
      getting_dressed: ['the dressing room transformation beginning', 'wings and diamonds assembling — becoming the angel'],
      breakfast: ['model hotel morning before the show day begins', 'private morning ease in hotel before backstage'],
      late_morning: ['backstage preparation building — the transformation beginning', 'editorial studio angel look assembling'],
      lunch: ['midday in backstage ease before the transformation peak', 'the angel gathering before the wings'],
      afternoon: ['the complete transformation — wings on, angel complete', 'the backstage dressing room at theatrical peak'],
      reset: ['the final look complete — the corridor is next', 'the angel before the most famous walk in fashion'],
      golden_hour: ['the corridor — wings spread, the walk about to begin', 'the most electric pre-runway fashion moment'],
      dinner: ['the runway walk — the most iconic moment in fashion', 'the editorial studio complete angel editorial shoot'],
      evening: ['the after-party celebration after the runway', 'the angel post-show in luxury celebration'],
      night: ['private hotel after the show — the model beneath the angel', 'the theatrical world complete and private night'],
    },
  },

  narrativeIntentPools: {
    wake: ['the private human beginning of the most theatrical fashion day', 'the model before the angel — private and warm'],
    morning_refresh: ['building the angel identity from private morning through self-care ritual', 'the private preparation before the theatrical transformation begins'],
    getting_dressed: ['the theatrical transformation from model to angel — wings, diamonds, lingerie', 'the most powerful dressing ritual in fashion becoming the complete editorial identity'],
    breakfast: ['the model private morning ease before the show world takes over', 'fuel and calm before the theatrical transformation day'],
    late_morning: ['the transformation building in the backstage professional environment', 'the angel editorial look assembling piece by piece'],
    lunch: ['midday ease before the theatrical peak of the transformation', 'gathering before the wings and the complete angel look'],
    afternoon: ['the complete angel transformation — the most theatrical fashion moment', 'wings, diamonds, and the complete editorial identity fully assembled'],
    reset: ['the final complete angel look at the mirror — ready for the most famous walk', 'the corridor is next — the angel at maximum theatrical beauty'],
    golden_hour: ['the pre-show corridor — the most electric pre-runway fashion energy', 'wings spread before the cameras — the defining angel moment'],
    dinner: ['the runway walk or editorial shoot — the angel at full theatrical editorial power', 'the most iconic fashion moment — the angel on the runway in wings and diamonds'],
    evening: ['post-show luxury celebration — the angel after the runway in glamorous ease', 'the fashion world celebrating the most beautiful walk'],
    night: ['the model returning from the angel — private hotel quiet after the theatrical day', 'the most private moment — the angel identity at rest in the hotel suite'],
  },

  fallbackRules: {
    pacingProfile: { wake: 'slow', morning_refresh: 'slow', getting_dressed: 'slow', breakfast: 'slow', late_morning: 'medium', lunch: 'slow', afternoon: 'slow', reset: 'slow', golden_hour: 'slow', dinner: 'slow', evening: 'slow', night: 'slow' },
    repetitionBreakers: { avoidBackToBackSameLocation: true, avoidBackToBackSameLightingStyle: true, encourageWardrobeEvolution: true },
    worldDefaults: { allowSceneGroupFallbackToPhasePools: true, allowSubLocationFallbackToWorldPools: true, preferSceneGroupsWhenPresent: true },
  },

  exclusions: {
    premium: ['cheap or non-luxury lingerie settings', 'non-theatrical or editorial environments', 'casual everyday settings unrelated to runway', 'non-model non-editorial energy'],
    hard: ['corporate settings', 'beach swimwear without runway context', 'outdoor non-editorial public spaces', 'non-fashion environments'],
  },

  routeRules: {
    worldIdentity: ['the angel world must feel theatrical, beautiful, luxury, and editorial — the most famous lingerie runway world elevated to editorial art', 'wings, diamonds, luxury lingerie, and the runway are the core visual language'],
    humanFlow: ['the day begins in private hotel morning, builds through backstage preparation and transformation, peaks on the runway or in editorial, and closes in post-show luxury and private hotel night'],
    styling: ['luxury lingerie and the iconic wings — the angel editorial identity is the defining styling language', 'the transformation from model to angel is the core styling narrative'],
    atmosphere: ['backstage theatrical atmosphere, runway drama, editorial studio professional light, and luxury hotel private ease', 'the theatrical fashion world is always present'],
  },
}
